### ISSUE TITLE
Change reference for the spinal cord toolbox in the readme + sourceforge

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1020]

**Comment by tanguyduval** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/27720818

De Leener, B., Lévy, S., Dupont, S.M., Fonov, V.S., Stikov, N., Louis Collins, D., Callot, V., Cohen-Adad, J., 2016. SCT: Spinal Cord Toolbox, an open-source software for processing spinal cord MRI data. Neuroimage. doi:10.1016/j.neuroimage.2016.10.009

**Comment by jcohenadad** [comment]
done a long long time ago
