### ISSUE TITLE
[sct_process_segmentation] CSA is corrected with respect to the angle with the B0 field --> should be corrected by the angle with the slice direction

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1022]
Computation of CSA is wrong if FOV is tilted --> angle should be computed with respect to the slice direction.

Also in the doc it is not clear which angle is computed.

Also in the doc there is a typo:
`````
angle_image.nii.gz: the cord segmentation (nifti file) where 
                                  each slice's value is equal to the CSA (mm^2),
`````

I bypassed this issue by changing the qmatrix to a diagonal one (as if the FOV wasn't tilted):

**Comment by jcohenadad** [comment]
bug still there:
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/176443580

**Comment by jcohenadad** [comment]
@benjamindeleener: i've implemented integrity testing on test_sct_process_segmentation. It tests CSA on 1: image, 2: image_rotated and 3: image with rotated header.
Currently, 1, 2 pass and 3 fails.
