### ISSUE TITLE
shape analysis

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1030]
idea: add numerical outputs from segmentation that are sensitive to abnormal cord shape (compression).

- [ ] RL/AP eigenvalue ratio + max derivative along Z (Julien)
- [ ] rotation angle + max derivative along Z (Julien)
- [ ] columnwise RMS displacement + max derivative along Z (Julien)
- [ ] CSA max derivative along Z (Julien)
- [ ] contour analysis (Ben)

**Comment by benjamindeleener** [comment]
This feature is introduced into `sct_process_segmentation -p shape` and includes AP diameter, RL diameter, area eccentricity, equivalent diameter, orientation, ratio_minor_major, shape solidity, shape symmetry.

These features can be calculated per slice or averaged over vertebral levels.

**Comment by jcohenadad** [comment]
fixed via #1332
