### ISSUE TITLE
sct_warp_template: flag -s to warp spinal levels is not working anymore with PAM50

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#1039]
Because spinal levels don't exist for this template
But flag is still there...

**Comment by jcohenadad** [comment]
PAM50 now includes a newly-generated spinal levels: https://osf.io/st8k4/?action=download&version=5

**Comment by jcohenadad** [comment]
For info, below is the spinal level (only few levels displayed) for PAM50 (left) and MNI-Poly-AMU (right)
![screen shot 2016-11-28 at 20 49 57](https://cloud.githubusercontent.com/assets/2482071/20693560/32cf3a50-b5ad-11e6-8358-c8aeb1c40e45.png)

**Comment by jcohenadad** [comment]
![fig_spinal-to-vertebraldistance](https://cloud.githubusercontent.com/assets/2482071/20693601/82fd0958-b5ad-11e6-9605-2cd34186f032.png)
![fig_spinallevels](https://cloud.githubusercontent.com/assets/2482071/20693602/8304ba18-b5ad-11e6-81c4-9610ce119090.png)
![fig_spinalvariance](https://cloud.githubusercontent.com/assets/2482071/20693603/8304bd60-b5ad-11e6-9d48-6986928d8060.png)
