### ISSUE TITLE
sct_download_data: update URL for PAM50

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1041]
when we will do a release, we will need to update the URL pointing to the PAM50, sct_testing_data and binaries. Currently, they point to a temporary folder on my Dropbox.

**Comment by peristeri** [comment]
I'm not sure I understand what is the problem.

**Comment by jcohenadad** [comment]
sorry, i've clarified the comment

**Comment by jcohenadad** [comment]
fixed in PR #1052
