### ISSUE TITLE
error MKL during installation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1042]
on Ubuntu16

**Comment by jcohenadad** [comment]
cannot reproduce error

**Comment by poquirion** [comment]
I was able to reproduce the bug on Alex machine. It seems to come from ~/.local/ libraries install pollution.  I will force the exclusion of these libraries with  `export PYTHONNOUSERSITE=1` in sct_launcher. It should limit the possibilities of this bug appearing again. But I am still investigating.

**Comment by poquirion** [comment]
NOTE:
If it comes back and you need a quick fix on UBUNTU, run the following in the user install:
```
$SCT_DIR/python/bin/conda remove --force mkl
$SCT_DIR/python/bin/conda install mkl==11.3.3
```
