### ISSUE TITLE
update the wiki documentation.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1045]
https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_extract_metric/ does not match the code.

the necessary -o and -method parameters are missing.

**Comment by benjamindeleener** [comment]
The documentation of `sct_label_utils` does not match the code either: https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_label_utils/

**Comment by joshuacwnewton** [comment]
The documentation is now handled in RTD, and the parameter descriptions are generated from argparse `--help`, so they match the code automatically. Closing.
