### ISSUE TITLE
need a function to compute mutual information

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#1054]
Add options to `sct_maths`: 
- [x]  to compute mutual information (using sklearn) --> flag `-mi`
- [x]  to compute correlation --> flag `-corr` (not cross correlation)
- [x]  output a file with result: text file or pickle

--> on branch sd_compute_mi_cc

**Comment by jcohenadad** [comment]
i would do compute the correlation instead of the cross-correlation, because we are not looking at how the correlation varies as a function of phase between series 1 and series 2, but instead we are looking at a single correlation value at phase=0. Hence i would suggest flag -corr

**Comment by SaraDupont** [comment]
Ok

**Comment by SaraDupont** [comment]
This done in on branch `sd_compute_mi_cc`(see PR #1056) 
--> To compute the mutual information of the correlation between two images, they need to be in the same space (or at least have the same dimensions). I've added an error message and a guideline (to solve the size issue) in commit 1d32d93 in case the images doesn't have the same size.

**Comment by SaraDupont** [comment]
Just merged PR #1056 to master.

**Comment by H-Snoussi** [comment]
Thank you !!
