### ISSUE TITLE
empty inverse warping field

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1068]
related to: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/c94da3ab/

data: **folder_shared/sct_issues/issue_1068**

syntax:
~~~
sct_register_graymatter -gm crop_Smith_229826_sWIP_mFFE_065_SENSE_4_3_mask_GM.nii -wm crop_Smith_229826_sWIP_mFFE_065_SENSE_4_3_mask_WM.nii -w warp_template2anat.nii.gz -winv warp_anat2template.nii.gz
sct_apply_transfo -i crop_Smith_229826_sWIP_mFFE_065_SENSE_4_3_mask_WM.nii -d /Users/julien/code/sct/data/PAM50/template/PAM50_wm.nii.gz -w warp_crop_Smith_229826_sWIP_mFFE_065_SENSE_4_3_mask_GM_gm2template.nii.gz -o crop_Smith_229826_sWIP_mFFE_065_SENSE_4_3_mask_WM_reg-gm.nii
~~~

**Comment by SaraDupont** [comment]
This was due to the conversion of the invert warping field (`warp_anat2template`) to the tmp folder --> I omitted to remove the "squeeze" data option. 
Fixed in commit 2b395a7. 
Just opened PR #1069 to merge to master.
