### ISSUE TITLE
create a function to compute MTsat

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1073]
similar to sct_compute_mtr

could be called sct_compute_mtsat

**Comment by slevyrosetti** [comment]
This function was created in branch **sl_sct_compute_mtsat** (`sct_compute_mtsat`) as well as the corresponding testing script (`testing/test_sct_compute_mtsat`). It is only waiting the testing data (`sct_testing_data`) to adapt `test_sct_compute_mtsat` to the right data path.

**Comment by zougloub** [comment]
Fixed by #1672
