### ISSUE TITLE
very long processing time for hires data

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1075]
data: 20161221_issue1074

syntax:
~~~
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz 
~~~

processing time: 649s on my laptop

maybe we should reinterpolate to 1mm iso before straightening?

**Comment by peristeri** [comment]
I would like to run a profiler on this particular case. Can you send me the
file? I would like to test my hypothesis.

**Comment by benjamindeleener** [comment]
Seems like a lot of time is spent on the `straight2curve` transformation, because of the high resolution of the initial image. Changing to isotropic 1mm resolution would certainly decrease the computational time. However, we've seen differences in the results when doing that. Maybe we can find a compromise.

Another significant amount of time is spent on testing the accuracy of straightening (at least half of it!).

Hereafter is the result of the cprofile (50 first results sorted by cumulative time):

``` 
/Users/benjamindeleener/data/20161221_issue1074/data/log_profile.pyprof% stats 50
Wed Dec 21 21:17:45 2016    /Users/benjamindeleener/data/20161221_issue1074/data/log_profile.pyprof

         13803858 function calls (13793623 primitive calls) in 616.982 seconds

   Ordered by: cumulative time
   List reduced from 2094 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.221    0.221  616.983  616.983 sct_straighten_spinalcord.py:15(<module>)
        1  228.367  228.367  616.354  616.354 sct_straighten_spinalcord.py:203(straighten)
     1572    0.006    0.000  249.471    0.159 msct_types.py:184(find_nearest_indexes)
     1572  227.864    0.145  249.466    0.159 {method 'query' of 'scipy.spatial.ckdtree.cKDTree' objects}
1442058/1434102   36.616    0.000   37.896    0.000 {numpy.core.multiarray.array}
     1572   24.666    0.016   25.030    0.016 msct_types.py:295(get_projected_coordinates_on_planes)
  1333703    0.652    0.000   22.677    0.000 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/numpy/core/numeric.py:414(asarray)
        1    0.007    0.007   20.442   20.442 sct_straighten_spinalcord.py:30(smooth_centerline)
        1    0.001    0.001   20.056   20.056 msct_smooth.py:273(b_spline_nurbs)
        1    9.248    9.248   20.055   20.055 /Users/benjamindeleener/code/sct/scripts/msct_nurbs.py:79(__init__)
        9    0.001    0.000   19.636    2.182 sct_utils.py:78(run)
       57   19.597    0.344   19.597    0.344 {method 'readline' of 'file' objects}
     1572    1.404    0.001   13.995    0.009 msct_types.py:235(get_distances_from_planes)
     1574    0.153    0.000   13.715    0.009 msct_image.py:714(transfo_pix2phys)
     5648   13.245    0.002   13.245    0.002 {numpy.core.multiarray.einsum}
     1582   12.640    0.008   12.640    0.008 {method 'tolist' of 'numpy.ndarray' objects}
        3    0.000    0.000   12.370    4.123 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/loadsave.py:77(save)
        3    0.000    0.000   12.370    4.123 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/filebasedimages.py:323(to_filename)
        3    0.000    0.000   12.370    4.123 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/analyze.py:1015(to_file_map)
        3    0.000    0.000   12.350    4.117 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/arraywriters.py:540(to_fileobj)
        3    0.011    0.004   12.350    4.117 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/volumeutils.py:543(array_to_file)
        3    0.058    0.019   12.340    4.113 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/volumeutils.py:769(_write_data)
     1572    0.025    0.000   10.565    0.007 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/numpy/core/fromnumeric.py:1574(shape)
     5219   10.098    0.002   10.098    0.002 {zip}
      944    0.001    0.000   10.025    0.011 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/openers.py:170(write)
      947    0.020    0.000   10.024    0.011 /Users/benjamindeleener/code/sct/python/lib/python2.7/gzip.py:227(write)
      944    9.189    0.010    9.189    0.010 {built-in method compress}
   881234    2.248    0.000    9.057    0.000 /Users/benjamindeleener/code/sct/scripts/msct_nurbs.py:299(evaluateN)
   629226    0.326    0.000    6.808    0.000 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/numpy/lib/polynomial.py:1137(__call__)
   629226    2.669    0.000    6.482    0.000 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/numpy/lib/polynomial.py:615(polyval)
       13    0.405    0.031    5.722    0.440 /Users/benjamindeleener/code/sct/scripts/msct_nurbs.py:562(reconstructGlobalApproximation)
       13    0.285    0.022    3.183    0.245 /Users/benjamindeleener/code/sct/scripts/msct_nurbs.py:345(construct3D)
        1    0.798    0.798    2.881    2.881 msct_image.py:429(getNonZeroCoordinates)
     1572    1.480    0.001    2.369    0.002 msct_types.py:313(get_in_plans_coordinates)
        1    0.003    0.003    2.293    2.293 sct_apply_transfo.py:108(apply)
   629226    0.881    0.000    2.246    0.000 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/numpy/core/numeric.py:86(zeros_like)
      967    1.908    0.002    1.908    0.002 {method 'tostring' of 'numpy.ndarray' objects}
        1    0.002    0.002    1.880    1.880 /Users/benjamindeleener/code/sct/scripts/msct_nurbs.py:905(construct3D_uniform)
   427612    1.509    0.000    1.879    0.000 msct_types.py:43(__init__)
        2    0.156    0.078    1.550    0.775 /Users/benjamindeleener/code/sct/scripts/msct_nurbs.py:854(compute_curve_from_parametrization)
    63666    0.038    0.000    1.399    0.000 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/numpy/core/numeric.py:484(asanyarray)
        7    0.000    0.000    1.268    0.181 msct_image.py:201(__init__)
        7    0.001    0.000    1.267    0.181 msct_image.py:266(loadFromPath)
       10    0.000    0.000    1.238    0.124 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/spatialimages.py:440(get_data)
        7    0.022    0.003    1.238    0.177 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/arrayproxy.py:143(__array__)
        7    0.000    0.000    1.216    0.174 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/arrayproxy.py:129(get_unscaled)
        7    0.097    0.014    1.215    0.174 /Users/benjamindeleener/code/sct/python/lib/python2.7/site-packages/nibabel/volumeutils.py:451(array_from_file)
        7    0.037    0.005    1.112    0.159 {method 'readinto' of '_io._BufferedIOBase' objects}
       35    0.021    0.001    1.096    0.031 /Users/benjamindeleener/code/sct/python/lib/python2.7/gzip.py:248(read)
       75    0.001    0.000    1.074    0.014 /Users/benjamindeleener/code/sct/python/lib/python2.7/gzip.py:285(_read)
```

**Comment by jcohenadad** [comment]
maybe results with 1mm is good enough for what we want to do (reg2template, vertebral labeling) and therefore better to prioritize time vs. accuracy? 
maybe we can add a flag to switch on/off accuracy results?

**Comment by benjamindeleener** [comment]
Indeed. I like the idea of proposing a flag for low/high accuracy, depending of the time we have for processing. Which one should be the default one?

FYI, when fixing the edge effect issue, the time for this dataset reduced to 428 seconds.

Note that most of the time is spent on the straight2curve transformation, which can be disabled if necessary, with the option `-disable-straight2curved`. There is also an option `-disable-curved2straight`.

**Comment by jcohenadad** [comment]
great! i think straight2curve is important from a reg2template point of view.  I would definitely do the reinterpolation to 1mm the default one (unless it produces horrible results, but i doubt it). 

i would call the flag -resample to be more specific (and we can comment in the usage help that -resample 0 is slower but potentially more accurate).

**Comment by benjamindeleener** [comment]
Perfect. I implemented the feature described above. A new option available for sct_traighten_spinalcord:
```
 -resample <float>            Isotropic resolution of the straightening output, in millimeters.
                                Resampling to lower resolution decreases computational time while 
                                  decreasing straightening accuracy.
                                To keep native resolution, set this option to 0.0mm.
                                 Default value = 1.0
```

The resolution of straight image varies with this parameter.

On the dataset above:
`sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -resample 0.0` --> 428 sec
`sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -resample 1.0` --> 62 sec
`sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -resample 2.0` --> 19 sec


Here is the result of straightening with three options:
high --> native resolution
medium --> 1mm
low --> 2mm
![benjamindeleener_4](https://cloud.githubusercontent.com/assets/7757117/21464229/0d546812-c945-11e6-95ef-edb9bb52aa3b.gif)

We could also allow for non-isotropic resolution, for example `0.5x0.5x2`. What do you think?

**Comment by jcohenadad** [comment]
great! i don't think we need the non-isotropic for now.

i would just change the entry to make it more user-friendly: 1.0 --> 1

also, in the help, it says to put 0.0mm, with the "mm" specified, whereas "mm" is not specified in the 1.0. So with my comment above, i would replace "0.0mm" with "0".

**Comment by benjamindeleener** [comment]
Ok. I left the possibility to enter a float but I changed the help to make people input integers.

**Comment by jcohenadad** [comment]
Awesome!
Did you also add a flag for accuracy results  (turned off by default)?
Thx

**Comment by benjamindeleener** [comment]
I will. But I don't think we should disable the accuracy results by default. It is important quantitative information about the results and users (and us) should always look at them.

**Comment by benjamindeleener** [comment]
The command:
```
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -resample 1 -param accuracy_results=0
```
spent 55 seconds compared to 57 seconds with accuracy results.

**Comment by jcohenadad** [comment]
I would disable accuracy results if it takes substantial amount of time. A few seconds is reasonable, but you pointed out at the beginning of this thread that it took half of it (650s/2 --> 325s). So we need to have a better sense of how much time it takes, regardless of the dataset size and resolution. 
Thanks

**Comment by jcohenadad** [comment]
I gave it more though, and realized there is an issue of interpolating the destination straight space to 1mm iso (or 2mm iso) for `sct_register_to_template`, because if user enters a 0.5x0.5x3mm resolution input image, the registration to template will be done at 1mm iso (instead of 0.5mm iso). So, what i was thinking is to stick with a sub-sampled warping field (e.g. 1mm iso), but resample the destination straight space (e.g. 1x1x1 --> 0.5x0.5x0.5) at the end of `sct_straighen_spinalcord`. This last resampling + apply transfo steps should only take a few seconds. Let's brainstorm further to anticipate the implications in other workflows.

**Comment by benjamindeleener** [comment]
No problem. I also prefer to output a resolution similar to the input resolution. And there is no difficulties to create a subsampled warping field that would be applied on the native resolution. We will lose some times creating the straight space but I don't think it will be too much. I'll implement that quickly so we can try on a large dataset.

**Comment by benjamindeleener** [comment]
I analyzed the processing time of `sct_straighten_spinalcord` and the time necessary to compute its accuracy. Results are in the figure below for two values of the parameters `-resample`: `native resolution`and `1mm`.

<img width="1475" alt="screen shot 2017-01-04 at 20 22 03" src="https://cloud.githubusercontent.com/assets/7757117/21665831/0e7869a2-d2bc-11e6-8596-053dbbc41739.png">

With `-resample 0` (native resolution):
```
Duration: 3139s
Passed: 161/175
Crashed: 0/175
Mean: {'duration_accuracy_results': 10.382857142857143, 'dist_max': 1.6541714285714284, 'dice': 0.9690104857142853, 'rmse': 0.8018857142857145, 'duration': 93.05989974703108}
STD: {'duration_accuracy_results': 34.11267238252048, 'dist_max': 1.513063526363373, 'dice': 0.008995892006819443, 'rmse': 0.46198023116811815, 'duration': 87.05429177997445}
```

With `-resample 1`:
```
Duration: 2885s
Passed: 96/175
Crashed: 0/175
Mean: {'duration_accuracy_results': 9.205714285714286, 'dist_max': 2.353142857142857, 'dice': 0.9618644628571433, 'rmse': 0.9912571428571436, 'duration': 76.69758839879717}
STD: {'duration_accuracy_results': 27.840741076900265, 'dist_max': 1.7628930171225294, 'dice': 0.008382528825057677, 'rmse': 0.45766978150172394, 'duration': 41.334729412897396}
```

As you can see, computation time is decreased (77 vs 93 s) when resampling the warping field to 1mm (while keeping final resolution to the native resolution) but the accuracy decreases as well (rmse: 0.99 vs 0.80 mm, max_dist: 1.76 vs 1.51 mm).

The time spent to compute the straightening accuracy is between 0 and 15% of the total time, with some outliers (when the straightening failed). I suspect outliers to have wrong manual segmentations. I'll check that.

**Comment by benjamindeleener** [comment]
To be short: 
- the computation time of the accuracy calculation can (and should) be decreased
- I would recommend to keep native resolution as the computation time increase is not dramatic. The option would still be left for users usage.

**Comment by jcohenadad** [comment]
i would make accuracy calculation optional, as most people care more about their precious time. But we can discuss it offline

**Comment by benjamindeleener** [comment]
I disabled it for now in PR #1097. It can be enabled using the option `-param accuracy_results=1`.

**Comment by benjamindeleener** [comment]
By the way, the default parameter for `-resample` is still `1` (means that the warping field has 1mm isotropic resolution). Do we want to keep that this way or do I change default to the native resolution?

**Comment by jcohenadad** [comment]
based on the violin plot, it looks like 3 (vs. 1 for -resample 1) subjects are outliers, with processing time >200s. Apart from these outliers, processing time doesn't seem outrageous.
Moreover, some people might want good accuracy if they only use straightening (e.g., ISMRM'16 in ex vivo human), so I would suggest -resample 0.

**Comment by benjamindeleener** [comment]
Below are results when I corrected three segmentation that were wrong (failure for one subject and edge effects for two others). The outliers were due to these issues and have been corrected, but there are probably a lot more edge effects in sct_testing.

<img width="1503" alt="screen shot 2017-01-05 at 07 49 40" src="https://cloud.githubusercontent.com/assets/7757117/21686563/df578658-d333-11e6-94c6-d7036de0a596.png">

**Comment by jcohenadad** [comment]
could you also copy/paste the numerical results? i find the dynamic range difficult to interpret the plots due to the outlier-- thanks!

**Comment by benjamindeleener** [comment]
Oops I updated my post above.
