### ISSUE TITLE
if entry is None or '', the field should still exist

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1087]
it will allow this writing:
~~~
    email = arguments['-email']
~~~

instead of this longer one:
~~~
    if '-email' in arguments:
        email = arguments['-email']
    else:
        email = ''
~~~

**Comment by joshuacwnewton** [comment]
Closing, as this is no longer an issue when using `argparse`. For the above example, specifiying `arguments.email` will now always work.
