### ISSUE TITLE
sct_extract_metric combined labels duplicate

### ISSUE THREAD

**Issue by emilljungberg** [neuropoly/spinalcordtoolbox#1100]
In the most recent release (v3.0_beta29) I noticed that there is a duplicate in the combined labels in `sct_extract_metric`. The `info_label.txt` file reads:

```
# Combined labels
# Keyword=CombinedLabels (Please DO NOT change this line)
# ID, name, IDgroup
50, spinal cord, 0:35
51, white matter, 0:29
52, gray matter, 30:35
52, dorsal columns, 0:3
53, lateral funiculi, 4:13
54, ventral funiculi, 14:29
```

So the gray matter and dorsal column have the same ID 52. It reads the same in the help for the command (although I guess this reads from the info_label.txt file?).

Thanks guys!

**Comment by jcohenadad** [comment]
thank you for noticing Emil! I've recently updated the PAM50 so we will create a new release with that issue fixed as well

**Comment by jcohenadad** [comment]
fixed in version 2.0:
https://osf.io/gdwn6/

**Comment by emilljungberg** [comment]
Great! Thanks. I really like the new PAM50 template.

**Comment by jcohenadad** [comment]
fixed in new release:
https://github.com/neuropoly/spinalcordtoolbox/releases/tag/v3.0_beta30
