### ISSUE TITLE
find a way to list changes in CHANGES.md

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1105]
instead of doing it manually

**Comment by peristeri** [comment]
One way is to look at the commit logs such as:

`git log v3.0_beta20..HEAD --pretty=format:'%s [view commit](http://github.com/neuropoly/spinalcordtoolbox/%H) ' --reverse --no-merges`

An other possibility is to collect all pull requests from github and build a report from the results:
`"https://api.github.com/repos/neuropoly/spinalcordtoolbox/pulls?state=closed&amp;base=master"`

**Comment by peristeri** [comment]
To have a quick look of all the commits done since the last tag:

`https://github.com/neuropoly/spinalcordtoolbox/compare/v3.0_beta29`

and to compare between 2 tags:

`https://github.com/neuropoly/spinalcordtoolbox/compare/v3.0_beta28...v3.0_beta29`
