### ISSUE TITLE
discontinuities on segmentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1109]
data: **sct_issues/20170115_issue1109**

tested with Spinal Cord Toolbox (master/20e5e8e3263c314fce31378131e6ad3c738e7daf)

<img width="316" alt="screen shot 2017-01-15 at 20 55 19" src="https://cloud.githubusercontent.com/assets/2482071/21968669/0f2579ba-db65-11e6-8f59-7f472081ad59.png">

**Comment by jcohenadad** [comment]
note: resample to 1mm doesn't help:
<img width="247" alt="screen shot 2017-01-15 at 21 02 28" src="https://cloud.githubusercontent.com/assets/2482071/21968742/f237007a-db65-11e6-9fbb-83c4c5d44bdc.png">

**Comment by benjamindeleener** [comment]
The error was produced by the new `check_and_correct` function. Indeed, it happens that more errors can be found along the centerline but not only on the edges. In these cases, the `check_and_correct` function produces sparse outputs.

I corrected this by eliminating all slices above and below the first "error" encountered, starting from the center of the spinal cord.

**Comment by jcohenadad** [comment]
I have encountered the same issue again:
data: sct_004/t2
version: Spinal Cord Toolbox (master/56d03f1d4e164f0398a52e54b5da4a2265a4abf3)
syntax: 
~~~
sct_propseg -i t2.nii.gz -c t2
~~~
Results:
<img width="340" alt="screen shot 2017-03-06 at 08 35 33" src="https://cloud.githubusercontent.com/assets/2482071/23612133/3407db38-0248-11e7-8725-5fc192387aab.png">

**Comment by benjamindeleener** [comment]
I cannot reproduce the issue.
When I try to segment the spinal cord directly with the command above, the spinal cord detection fails. When I initiate the segmentation with a three-point mask (using the viewer), the issue doesn't appear.

Could you please check the command you used to generate this result?

**Comment by jcohenadad** [comment]
i confirm i get the same error again. 

Version SCT: master/56d03f1d4e164f0398a52e54b5da4a2265a4abf3

Syntax
~~~
sct_propseg -i t2.nii.gz -c t2
~~~

data: sct_issues/20170307_issue1109/

**Comment by benjamindeleener** [comment]
`master/56d03f1d4e164f0398a52e54b5da4a2265a4abf3` correspond to

```
commit 56d03f1d4e164f0398a52e54b5da4a2265a4abf3
Merge: 54db637 a1519e6
Author: Julien Cohen-Adad <jcohen@polymtl.ca>
Date:   Sun Feb 26 10:29:12 2017 -0500

    Merge pull request #1183 from neuropoly/jca_issue1182
    
    Changed default threshold_distance from 2.5 to 10 to avoid edge effect
```

Could you please try with the latest version: `master/4159bcacd16124ed920d90bd2696299a287bc987`

**Comment by jcohenadad** [comment]
i've tried with the latest commit on master, still the same result:
Spinal Cord Toolbox (master/188c20e8ec6a7a501e42636e2d026fab324d5303)

**Comment by benjamindeleener** [comment]
Ok I was able to reproduce the issue. I'm working on it.
