### ISSUE TITLE
Add message to user when spinal cord is not detected

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#1113]
Lots of tests are crashing, because the spinal cord is not detected in `sct_propseg`.

It would be fairly straightforward to detect the crash (with a try/except) and exit the program with exit status 0 and a printout that tells the user that "spinal cord could not be detected, please do a manual initialization using -init-mask viewer, or -init-centerline viewer"?

**Comment by jcohenadad** [comment]
@benjamindeleener: I cannot assume that if file does not exist it implies that detection failed, because an older segmentation can already be there (false negative).

instead, i am trying to use status from isct_propseg. With detection failing, i get status=-11: is that specific to failed detection? Is it cross-OS compatible?

**Comment by benjamindeleener** [comment]
When the spinal cord is not detected in `isct_propseg`, the following code is called:
```c++
cerr << "Error: Unable to detect the spinal cord. Please provide the initial position and orientation of the spinal cord (-init, -init-mask)" << endl;
return EXIT_FAILURE;
```

The `EXIT_FAILURE` should be cross-platform as it is the standard C++ failure termination code (http://www.cplusplus.com/reference/cstdlib/EXIT_FAILURE/) but I don't know if the status code is always the same. Moreover, the `EXIT_FAILURE` is also called in several other failure cases (e.g., wrong input parameters, invalid input contrast (t1 and t2), help, failure when reading the image, error during symmetry computation, wrong initialization). In all cases, the same status code is called and can be detected.

**Comment by jcohenadad** [comment]
ok so i'll just exit as warning (instead of error) and display the output message

**Comment by jcohenadad** [comment]
since we want to exit with an error anyway (we need to detect crash for testing), i will also modify isct_test_function to remove the verbose of crashed function (we can examine individual verbose in output.txt)

**Comment by benjamindeleener** [comment]
I fully agree with that.

**Comment by benjamindeleener** [comment]
OptiC always return a centerline (on all slices), even if it has failed. So this issue is not relevant anymore.
