### ISSUE TITLE
Testing ants failure from Aviv's group

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1138]
Hello!

Aviv's group developed a script that can assess how the Ants registration went. Do we have/need something like that? Could be useful if you launch a pipeline in 200 subjects.. he is willing to share the code

Tanguy

**Comment by jcohenadad** [comment]
sounds good but we need to go into the specifics of "how well registration went". There is already a metric to assess src-dest similarity (used by ants for convergence). So what does the script do exactly?

**Comment by tanguyduval** [comment]
Aviv's answer:
"
We use ANTS to register the brain's VFA (flash) T1 map to the SEIR (epi) T1 map. Note that both have the same contrast.
To quantify the registration quality, we calculate the difference between the image and the local gradient within it.
We find that this is a good predictor of ANTS' capacity as a method of non-linear registration.
We have found that the registration is good in many cases, but sometimes it fails completely, and in some cases it is neither good nor a clear failure (this the worst case!).
"

What is the name of the script in SCT to assess the src-dest similarity ??

**Comment by jcohenadad** [comment]
DICE coefficient can be assessed using ```sct_dice_coefficient```, or metrics of similarity such as mutual information and correlation can be computed using ```sct_maths -mi/-corr```

**Comment by tanguyduval** [comment]
Try different metrics to assess registration performance --> return a warning to the user if failure is detected
