### ISSUE TITLE
sct_register_multimodal 

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1155]
To register t1 and dmri, I would like to know why the two following instructions give me the same result please :
```
sct_register_multimodal -i t1.nii.gz -d b0.nii.gz -identity 1 -x nn -o t1_reg.nii.gz
sct_register_multimodal -i t1.nii.gz -d b0.nii.gz -param step=0,type=label,algo=rigid,metric=MI -identity 1 -x nn -o t1_reg.nii.gz
```

[https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/d601df63/#e7fa](url)

**Comment by jcohenadad** [comment]
already answered
