### ISSUE TITLE
with init-mask viewer, enable to change slice from left window

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1160]
related to: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/70e45f83/

it would accommodate data like the one below:

![screen shot 2017-02-13 at 09 48 29](https://cloud.githubusercontent.com/assets/2482071/22887882/afe714f8-f1d1-11e6-9280-a2ea9f63e0c4.png)

**Comment by benjamindeleener** [comment]
@jcohenadad PR #1163 includes the changes
