### ISSUE TITLE
with -init-mask and automatic slice display disabled, slice initialization seems to be still at the center of FOV

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1166]
for example when i use an mprage with brain, i initialize with -init-mask viewer, then select the bottom of the FOV, then create three points along the upper c-spine, but output segmentation is empty: i suspect this is because the initialized slice for propseg is still the mid-slice --> it should be the mid point instead, shouldn't it?

**Comment by benjamindeleener** [comment]
When using the `-init-mask` option, the initialized slice is at the mid-point, not the mid-slice. The error might come from somewhere else. I'll try to reproduce the error.

**Comment by jcohenadad** [comment]
data here: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/70e45f83/
