### ISSUE TITLE
default threshold_distance not consistent with the usage and suggest changing threshold

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1182]
in the usage, it says: 
~~~
threshold_distance: [0.0,inf[. Threshold for which voxels are not 
                                  considered into displacement. Increase this threshold if the image
                                   is blackout around the spinal cord too much. Default=1.0"
~~~

However, it is set in the code at threshold_distance=2.5.

Moreover, in a 0.8mm isotropic image, I find that threshold_distance=10 gives best results and I would suggest to use this as a default value. Is there any cons in using a higher default value? Computational time is very similar.

See example below (sct_006):

command:
~~~
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg.nii.gz -param threshold_distance=X
~~~

Input image:
![screen shot 2017-02-26 at 08 38 13](https://cloud.githubusercontent.com/assets/2482071/23340183/ff4dfc0e-fbff-11e6-9da0-09193063bfe8.png)

threshold_distance=0.5
![threshold_distance 0 5](https://cloud.githubusercontent.com/assets/2482071/23340237/cdb9bb5a-fc00-11e6-993f-8374029b3641.png)

threshold_distance=1
![threshold_distance 1](https://cloud.githubusercontent.com/assets/2482071/23340292/adc0fa06-fc01-11e6-9a14-4977f56b6cca.png)

threshold_distance=2
![threshold_distance 2](https://cloud.githubusercontent.com/assets/2482071/23340241/d2786704-fc00-11e6-8dac-462ccf95c331.png)

threshold_distance=5
![threshold_distance 5](https://cloud.githubusercontent.com/assets/2482071/23340245/d80d3712-fc00-11e6-9562-fa2fd02618ca.png)

threshold_distance=10
![threshold_distance 10](https://cloud.githubusercontent.com/assets/2482071/23340246/daf79c2e-fc00-11e6-917a-79b59451aacb.png)

**Comment by benjamindeleener** [comment]
No problem with changing the default value of the distance threshold.

Its purpose was mainly to avoid duplication effects on edges but it doesn't appear often.
