### ISSUE TITLE
Centerline angle is biased on edge when using NURBS

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#1212]
Still need to find data... More to come later

**Comment by jcohenadad** [comment]
@benjamindeleener this is 1+ year old. Are you still planning to work on this? if not please close it, or leave it open but document the issue with more details and guidelines to help other researchers find a solution. Thx

**Comment by benjamindeleener** [comment]
@jcohenadad not planning on working on this for now.
