### ISSUE TITLE
[FEATURE] Build the base elements to GUI applications

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1240]
# Motivation

All gui implementation can be broken down to 5 core classes :

* Window = Wraps the GUI
* Header = a display of the status the GUI and the current errors.
* Main Pannel= Views and controls the user manipulates to collect information.
* Image Plot = Displays the anatomical view.
* Control Buttons = Set of controllers to 

# Action

Create base classes that implement the common functionally.

**Comment by alexandrospopov** [comment]
Started to work on specific branch _viewerQt_ .

**Comment by peristeri** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build the base elements to GUI applications](https://trello.com/c/7mMuAf3c/2-build-the-base-elements-to-gui-applications)
