### ISSUE TITLE
[FEATURE] Introduce quality control commands.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1247]
# Motivation

When running any registration commands, the generated nitfi files are not validate for correctness. One way of validating is to generate a mosaic out of the slices of the generated files and use the original as a background.

# Steps

Introduce to the registration commands a parameter `-qc` that takes a `output path` as a value. Let's call this folder `qc_data` for now.

If the command is called with this parameter, the command validates the path.
 - If the path does not exist, create it.
 - If the path is empty, create a json file `qc_results.json`.
 - If the path is not empty and the json file does not exist, display a warning that the path is not a valid quality control folder and exit.

1) The command extracts the user's name and contrast from the path the input file is saved in `[contrast]/[subject]/filename.nii.gz`. And create a path in the qualitycontrol path `[working_dir]/qc_data/[contrast]/[subject]/[command]/[timestamp]`

2) In the path, the application will create 2 files, a mosaic of axial views and a full saggital view. The 2 types of images will be created for each input file as well as the output files. The resulting mosaic will keep as much of the fidelity of the original, while cropping to the size of 200x200. While the saggital view will keep as much of the fidelity as possible.

3) Update the qualitycontrol.json file with the information of the command and location of the mosaic path.

The json schema will have a minimum

    | subject
    | contrast [t1, t2, mt]
    | date and time
    | command_output
    | orientation [sagittal | axial]
    | input_path
    | output_path
    | dimension

**Comment by jcohenadad** [comment]
this is now handled by `sct_qc`.
