### ISSUE TITLE
add optic

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1249]
- [x] replace centerline detection with optic in propseg (Ben)
- [x] package binary
- [x] change name `dmri_model.yml` for `dwi_model.yml` (Julien)
- [x] test optic call with sh/tcsh env (to make sure FSLOUTPUTTYPE is properly passed)

**Comment by charleygros** [comment]
Model generated for each contrast (t1, t2, t2s and dmri).

Available under `/Public_JCA/temp/charley/linux/models/`

**Comment by benjamindeleener** [comment]
I've create the branch `issue_1249`. In this branch, I integrated OptiC into PropSeg, without the use of a wrapper. It is a first step for creating a wrapper for OptiC that would be called by PropSeg.

Link to PropSeg in new branch: https://github.com/neuropoly/spinalcordtoolbox/blob/issue1249/scripts/sct_propseg.py

**Comment by charleygros** [comment]
MacOs Binaries available under `/Public_JCA/temp/charley/mac/10_7/` and `/Public_JCA/temp/charley/mac/10_11/`

**Comment by jcohenadad** [comment]
does version 10_7 work for all >10.7 osx? 
if so, any advantage in copying 10_11?

**Comment by jcohenadad** [comment]
i've updated uploaded binaries on OSF and updated the branch for the install part. Please update your local installation to reflect changes:
~~~
./install_sct -m
~~~

**Comment by charleygros** [comment]
I have tested `10_7` on my machine (El Capitan, 10.11.5): it works well!
I do not see advantage to use 10_11

**Comment by benjamindeleener** [comment]
Unix binary of `isct_spine_detect` seems to use FSL:

```
django:t1 bedelb$ isct_spine_detect -ctype=dpdt -lambda=1.0 "/Users/bedelb/code/spinalcordtoolbox/data/models/t1_model.yml" "t1_int16_RPI_imghdr" "t1_int16_RPI_imghdr_optic"
ERROR:: Environment variable FSLOUTPUTTYPE is not set!
Please make sure that the appropriate configuration file is sourced by your shell (e.g. by putting it in .profile).
e.g. bash or sh users add the line ". ${FSLDIR}/etc/fslconf/fsl.sh"
e.g. tcsh or csh users add the line "source ${FSLDIR}/etc/fslconf/fsl.csh"
```

**Comment by benjamindeleener** [comment]
Here are the results for `sct_testing/large`:

## T1-weighted
```
Command: "sct_propseg -i t1/t1.nii.gz -c t1 -init-centerline optic
Dataset: /Volumes/Public_JCA/sct_testing/large/
GLOBAL RESULTS:
Duration: 1483s
Passed: 75/116
Crashed: 0/116
Mean: {'dice_segmentation': 0.8661204544467307, 'duration [s]': 81.44691399048115}
STD: {'dice_segmentation': 0.18441609014819368, 'duration [s]': 30.866210507926827}

Command: "sct_propseg -i t1/t1.nii.gz -c t1
Dataset: /Volumes/Public_JCA/sct_testing/large/
GLOBAL RESULTS:
Duration: 1066s
Passed: 24/116
Crashed: 1/116
Mean: {'dice_segmentation': 0.6692521998875399, 'duration [s]': 52.99569157074238}
STD: {'dice_segmentation': 0.30516104566549374, 'duration [s]': 32.57508440274568}
```
![results_t1](https://cloud.githubusercontent.com/assets/7757117/25063759/f3415fec-21ba-11e7-9103-4078d81be204.png)

## T2-weighted
```
Command: "sct_propseg -i t2/t2.nii.gz -c t2 -init-centerline optic
Dataset: /Volumes/Public_JCA/sct_testing/large/
GLOBAL RESULTS:
Duration: 1558s
Passed: 183/256
Crashed: 0/256
Mean: {'dice_segmentation': 0.8965265611318537, 'duration [s]': 41.221134138293564}
STD: {'dice_segmentation': 0.15291260300075263, 'duration [s]': 13.274626862061824}

Command: "sct_propseg -i t2/t2.nii.gz -c t2
Dataset: /Volumes/Public_JCA/sct_testing/large/
GLOBAL RESULTS:
Duration: 1549s
Passed: 118/256
Crashed: 36/256
Mean: {'dice_segmentation': 0.7161338428029882, 'duration [s]': 39.81973373796791}
STD: {'dice_segmentation': 0.3738910200186539, 'duration [s]': 18.235122280997768}
```
![results_t2](https://cloud.githubusercontent.com/assets/7757117/25063760/f79d9984-21ba-11e7-8753-b1d38b5d4f54.png)

## T2*-weighted
```
Command: "sct_propseg -i t2s/t2s.nii.gz -c t2s -init-centerline optic
Dataset: /Volumes/Public_JCA/sct_testing/large/
GLOBAL RESULTS:
Duration: 1374s
Passed: 132/267
Crashed: 0/267
Mean: {'dice_segmentation': 0.8312970396151269, 'duration [s]': 32.0688976955771}
STD: {'dice_segmentation': 0.1911104445470129, 'duration [s]': 11.959219802345736}

Command: "sct_propseg -i t2s/t2s.nii.gz -c t2s
Dataset: /Volumes/Public_JCA/sct_testing/large/
GLOBAL RESULTS:
COMING SOON
```

**Comment by benjamindeleener** [comment]
I have enabled OptiC by default for PropSeg. To use old detection method, use option `-init-centerline hough` (should we hide it from the documentation or display it, knowing it is less robust?)

We should also replace the documentation concerning the contrast:
```
type of image contrast, t2: cord dark / CSF bright ; t1: cord bright / CSF dark
```

Proposition:
```
type of image contrast, if your contrast is not in the available options (t1, t2, t2s, dmri), use t1 (cord bright / CSF dark) or t2 (cord dark / CSF bright)
```

**Comment by jcohenadad** [comment]
Je remplacerais dmri par dwi, car des gens pourraient penser qu'il sagit de la b=0 (qui est en fait T2w)


--Julien
-------- Original message --------From: Benjamin De Leener <notifications@github.com> Date: 2017-04-15  12:04 PM  (GMT-05:00) To: neuropoly/spinalcordtoolbox <spinalcordtoolbox@noreply.github.com> Cc: Julien Cohen-Adad <jcohen@polymtl.ca>, Assign <assign@noreply.github.com> Subject: Re: [neuropoly/spinalcordtoolbox] add optic (#1249) 
I have enabled OptiC by default for PropSeg. To use old detection method, use option -init-centerline hough (should we hide it from the documentation or display it, knowing it is less robust?)
We should also replace the documentation concerning the contrast:
type of image contrast, t2: cord dark / CSF bright ; t1: cord bright / CSF dark

Proposition:
type of image contrast, if your contrast is not in the available options (t1, t2, t2s, dmri), use t1 (cord bright / CSF dark) or t2 (cord dark / CSF bright)


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/neuropoly/spinalcordtoolbox","title":"neuropoly/spinalcordtoolbox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/neuropoly/spinalcordtoolbox"}},"updates":{"snippets":[{"icon":"PERSON","message":"@benjamindeleener in #1249: I have enabled OptiC by default for PropSeg. To use old detection method, use option `-init-centerline hough` (should we hide it from the documentation or display it, knowing it is less robust?)\r\n\r\nWe should also replace the documentation concerning the contrast:\r\n```\r\ntype of image contrast, t2: cord dark / CSF bright ; t1: cord bright / CSF dark\r\n```\r\n\r\nProposition:\r\n```\r\ntype of image contrast, if your contrast is not in the available options (t1, t2, t2s, dmri), use t1 (cord bright / CSF dark) or t2 (cord dark / CSF bright)\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/neuropoly/spinalcordtoolbox/issues/1249#issuecomment-294302181"}}}

**Comment by benjamindeleener** [comment]
Bonne idée. Il faudrait changer le nom du modèle dans `data/` aussi.

**Comment by jcohenadad** [comment]
effectivement, je m'en occupe

**Comment by benjamindeleener** [comment]
Ca a l'air de crasher sur Travis, et je ne sais pas trop pourquoi:
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/222376744#L514

Une idée? 
`sct_testing` fonctionne bien chez moi.

**Comment by jcohenadad** [comment]
les binaires linux ne sont pas encore sur osf ;-)

**Comment by jcohenadad** [comment]
je fais ca asap

**Comment by benjamindeleener** [comment]
Cool. Par contre ca fait la même erreur sur Travis/osx

**Comment by jcohenadad** [comment]
ah mince... il faudrait faire un printout de l'erreur

**Comment by benjamindeleener** [comment]
@jcohenadad Oops (on Travis: https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/222478501#L655)
```
Checking test_sct_propseg...........................
OUTPUT:
--
sct_propseg  -v 1 -i /home/travis/build/neuropoly/spinalcordtoolbox/sct_testing_data/t2/t2.nii.gz -c t2 -r 1 -ofolder sct_propseg_sct_testing_data_170416025213_413774/
Running /home/travis/build/neuropoly/spinalcordtoolbox/scripts/sct_propseg.py -v 1 -i /home/travis/build/neuropoly/spinalcordtoolbox/sct_testing_data/t2/t2.nii.gz -c t2 -r 1 -ofolder sct_propseg_sct_testing_data_170416025213_413774/
Check folder existence...
Detecting the spinal cord using OptiC
/bin/sh: 1: isct_spine_detect: not found
```

**Comment by benjamindeleener** [comment]
Works on OSX now.

**Comment by jcohenadad** [comment]
Works on linux (debian) as well.
I removed some todo:
- add optic test --> already tested via propseg
- add wrapper --> not urgent. Running propseg already output the centerline
