### ISSUE TITLE
[sct_register_gm] no option to use custom template for -winv

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1264]
-winv use PAM50 or MNI-POLY-AMU... I would like to use a custom template...

**Comment by SaraDupont** [comment]
## Prerequisites
The files needed from the template (other than the warping fields) are : 
1- the GM from the template warped to the subject space (i.e. `label/template/PAM50_gm.nii.gz`)
2- the WM from the template warped to the subject space (i.e. `label/template/PAM50_wm.nii.gz`)
3- a file from the template's original space (i.e. `spinalcortoolbox/data/PAM50/template/PAM50_t2.nii.gz`) --> only if the inverse warping field is requested

## How to do it
--> a new flag is needed to input the file name of the template in it's original space (file 3-) to be able to concatenate the inverse warping fields: **what would be the best name for this flag ?** 


--> for files 1- and 2-: two options to add the possibility of using a custom template:

A) --> keep flag `-t` and impose the structure `label_custom/template/blabla_gm.nii.gz`
**PRO**: keep the flags as they are,  preserve compatibility with older codes
**CON**: forces the user to reorganize its custom template

B) --> create 2 new flags  `-t-gm` and `-t-wm` (that would replace flag `-t`) with default values
**PRO**: the user can use whatever template organization, no impact on the people using the default parameters
**CON**: changing the flags implies that users who had scripts with flag `-t` would have to change them (probably very few people)

## Additional information
Documentation of  `sct_register_graymatter`:

```
DESCRIPTION
Registration function to improve the template registration by accounting for the gray and white 
matter shape using a multi-label approach. Output is a warping field from the template to the 
target image accounting for the gray matter shape. If -winv is used, output also includes the 
inverse warping field (from the target image to the template).

USAGE
sct_register_graymatter -gm <file> -wm <file> -w <file>

MANDATORY ARGUMENTS
 -gm <file>                   Gray matter automatic segmentation
 -wm <file>                   White matter automatic segmentation
 -w <file>                    Warping field: template -> image

OPTIONAL ARGUMENTS
 -t <folder>                  Path to template (registered on target image) Default value = label/
 -param <str>                 Parameters for the multimodal registration between multilabel images 
                              Default value = 
                              step=1,type=seg,
                              algo=centermassr
                              ot,metric=MeanSq
                              uares:step=2,typ
                              e=im,algo=syn,me
                              tric=MeanSquares
                              ,iter=10,smooth=
                              0,shrink=2:step=
                              3,type=im,algo=bsplinesyn,metric=MeanSquares,iter=5,smooth=0

OUTPUT OTIONS
 -winv <file>                 Warping field: image -> template.
 -ofolder <folder_creation>   Path to an output folder      

VALIDATION: Use both flags for validation.
 -manual-gm <file>            Manual gray matter segmentation on the target image. 
 -sc <file>                   Spinal cord segmentation on the target image. 

MISC
 -qc {0,1}                    Output images for quality control. Default value = 1
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1
```

**Comment by jcohenadad** [comment]
@SaraDupont: about file #3: if you only need an image with correct matrix/header, why not using PAM50_gm or PAM50_wm since they are in the same space of PAM50_t2?

**Comment by jcohenadad** [comment]
i would be leaning towards option A. I think the current number of people with custom template is N=1 ;-)
