### ISSUE TITLE
The command `test_regist` is broken.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1268]
After further examination, the command `script/test_regist.py` was last updated 2 years ago. Function signatures has changed.

Is this command still used?

**Comment by peristeri** [comment]
@jcohenadad @benjamindeleener can you provide some feedback?

**Comment by jcohenadad** [comment]
i don't think this command is used anymore. Have you checked if it is called by any script in /scripts and /testing?

**Comment by peristeri** [comment]
I can't find any mention anywhere in the code base. It was created 2 years ago by Tanguy Magnan and never maintained.

**Comment by jcohenadad** [comment]
ok let's remove it then
