### ISSUE TITLE
various improvements on QC

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1271]
- [x] add github tag for QC
- [x] add indication on html page like "use right/left arrows to move across rows"
- [x] improve contrast on displayed images-- contrast could be adjusted using the 5-95 percentile
- [x] Include sct_segment_graymatter QC
- [x] Replace Sagittal view with Axial mosaic for sct_register_to_template
- [ ] The keyboard shortcut for refresh (CMD+R on mac) does not work anymore with caf11f46d92fe8765490a53325acbf0e2b36b8f1
- [ ] Display full syntax below the image (e.g.: sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l labels.nii.gz -qc ~/qc_test).
- [ ] Indicate on the web page the location of the QC data
- [ ] improve visualization of sct_label_vertebrae (see snapshot below)

problems: image too small (could auto crop using kwowledge from cord location, or find better way to display), labels misplaced, contrasts not good (too dark)
<img width="1007" alt="screen shot 2017-06-28 at 15 43 34" src="https://user-images.githubusercontent.com/2482071/27663753-bd2b0456-5c18-11e7-9c50-08d1033b06f4.png">

**Comment by peristeri** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [various improvements on QC](https://trello.com/c/nODyATlC/6-various-improvements-on-qc)

**Comment by peristeri** [comment]
@jcohenadad For the 4th point, what is a resulting QC images for sct_segment_graymatter?

**Comment by jcohenadad** [comment]
@peristeri: probabilistic map of grey matter (thresholded 0.3-1) with colorbar displayed. @SaraDupont knows.

**Comment by zougloub** [comment]
- I used CLAHE to improve the qc image contrast, not the 5-95% as was proposed. Is that OK?
- Just to confirm, since the `sct_segment_graymatter` qc parameter is an integer, we'd change it and break the command-line API?

**Comment by jcohenadad** [comment]
@zougloub:
- OK for CLAHE (we might roll back to the uniform histogram equalization if images look too weird)
- indeed, the qc parameter in `sct_segment_graymatter` is a legacy and we should get rid of it at some point

**Comment by zougloub** [comment]
I added QC for `sct_segment_graymatter`; since we have 2 segmentation images, with either "probability" or label, a compound image is generated after binarization.

Note that while testing with `sct_example_data` (basically ran `batch_processing.sh`, then ran `sct_segment_graymatter -i mt0_crop_reg.nii.gz -s mt1_crop_seg.nii.gz -qc ~/qc_batch_processing`) I notice that there is something wrong with the segmentation. Will discuss offline

**Comment by zougloub** [comment]
I'm not sure the last 2 action items re absolutely necessary at this point:
- `sct_qc` is running with the location of the qc data as parameter  
   (having intex.html being a template would "solve" the problem);
- `sct_label_vertebrae`'s figure is ugly but still fully functional  
  (shifting the labels to the right by a few pixels... then other people might say it's not feng shui enough or something).
