### ISSUE TITLE
Create a process to install SCT VM

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1279]
- [x] Since the VM uses git installation, i would not call it v3.0.2 on OSF. Maybe: `SCT_20170424.ova`
- [x] Fix https://github.com/neuropoly/spinalcordtoolbox/issues/1280
- [x] sct_qc: there is no blinking in the qc report.
- [x] install open office to read XLS files

**Comment by peristeri** [comment]
For the third point, the version of chrome in the VM is very old and needs updating.

**Comment by jcohenadad** [comment]
how do you update?

**Comment by peristeri** [comment]
I will update in the new VM. It might grow the size of the VM a bit, but should be reasonable.

**Comment by peristeri** [comment]
Do we have any size constraints? Presently with the addition of libreoffice, the VM is now 4GB

**Comment by jcohenadad** [comment]
Hum, going from 1.8 to 4G only because of libre office, not sure it's worth it.
If easy to install I'd rather give the instructions on SF

**Comment by peristeri** [comment]
https://sourceforge.net/p/spinalcordtoolbox/wiki/virtual_machine/ is updated.
