### ISSUE TITLE
assets folder (for QC) is not copied during user installation

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#1300]
Leads to a bug when calling `sct_qc` because of missing folder.

**Comment by peristeri** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [assets folder (for QC) is not copied during user installation](https://trello.com/c/C3XIrit6/10-assets-folder-for-qc-is-not-copied-during-user-installation)
