### ISSUE TITLE
Create a command to create QC mosaic manually.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1309]
### Description

With segmentation files already created either manually or from a older version, the user wants to create a QC on these files

### Expected Behavior

- Run the command `sct_qc` with the options 
    - `-type` = `['axial-mosaic', 'sagittal-center']` 
    - `-file` = nifti-image. If 4D, a movie showing all frames will be created.
    - `-file-overlay` = nifti-image that will overlay the original image
    - `-title` = a title message
    - `-contrast` = a contrast message
    - `-folder` = the output folder

**Comment by peristeri** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a command to create QC mosaic manually.](https://trello.com/c/p6I0jKCu/4-create-a-command-to-create-qc-mosaic-manually)

**Comment by jcohenadad** [comment]
the trello link does not work on my side

**Comment by peristeri** [comment]
@charleygros can you provide feedback too.

**Comment by zougloub** [comment]
With a first QC refactor, it is now possible to run QC separately from the script (albeit with a Python API, not command-line). Given the variability of scripts `generate_qc()` parameters, I'll close this for now.
