### ISSUE TITLE
Inconsistent WM boundary between WM_seg and input segmentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1314]
![webp net-gifmaker](https://cloud.githubusercontent.com/assets/2482071/25903800/7137abcc-356b-11e7-9458-698cefb79ec6.gif)

Data: 20170510_issue1314

~~~
sct_segment_graymatter -i medic.nii.gz -s medic_seg.nii.gz
--
Spinal Cord Toolbox ((detached/530d3b9dfaaf46299a0178dedccf2c4bc763ab60)
~~~

**Comment by SaraDupont** [comment]
Fix suggestion by @jcohenadad is to get the WM by substracting GM to SC segmentation.  See PR #1317.
