### ISSUE TITLE
Image class loads the entire image into memory

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1316]
The `Image` class uses the `get_data()` method from the nibabel opened file in order to get the numpy data array representation. This is problematic for cases where images are large, such as 700MB+, because it will cause the entire image array to be loaded in memory instead of only the required parts of the data that the operation needs. 

A example is when we use the `split` operation from the `sct_image` command, if we need to split across the z-axis, we wouldn't need the entire image in memory, because we can do I/O on demand by loading only the required slices in memory.

As an alternative, it should be more appropriate if we could use the `.dataobj` attribute from the nibabel loaded image instead of the `.get_data()`, because the `dataobj` is an proxy object to the data on the disk that can be used to load partial chunks of data on demand. For operations that reuses the same data many times, then I believe that it makes sense to cache the data in memory, but otherwise we may have issues with large files.

To reproduce the issue:

    sct_image -i <largefile> -split z

This can also potentially be reproduced on any other operation that uses the `Image` class to load data.

**Comment by jcohenadad** [comment]
I agree. @benjamindeleener can you please investigate the feasibility of this approach?

**Comment by benjamindeleener** [comment]
I'll look into it. Thanks for the advice @perone!

**Comment by jcohenadad** [comment]
@benjamindeleener do you have any update on this issue?

**Comment by zougloub** [comment]
nibabel link on this subject: http://nipy.org/nibabel/images_and_memory.html#saving-time-and-memory

Note that memory mapping works well on uncompressed files, but `nii.gz` files are used a lot in the code... perhaps they shouldn't, unless it's explicitly in the user's command line.

**Comment by jcohenadad** [comment]
`nii.gz` is quite important when working with segmentations. It saves a lot of space. Issues with memory are marginal and if we had to chose i would favor the use of `nii.gz`.

of course if we can have the best of both worlds...

**Comment by perone** [comment]
Just adding some more information regarding the [nibabel interface](http://nipy.org/nibabel/reference/nibabel.dataobj_images.html?highlight=get_fdata#nibabel.dataobj_images.DataobjImage.get_data): the `get_data()` method will be deprecated and removed in the future. They introduced the `get_fdata()` method that should be used (they also added an interesting parameter to specify the numpy `dtype`) in new code.

**Comment by benjamindeleener** [comment]
I feel this is an improvement in SCT core that I am not feeling comfortable to solve. Therefore, I'll remove myself as an assignee.

**Comment by jcohenadad** [comment]
let's close this issue because it is an isolated case, and we need to slowly transition towards a code that mostly uses image objects across SCT functions (instead of read/write all the time)
