### ISSUE TITLE
add QC for sct_dmri_moco and sct_fmri_moco

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1325]
- [ ] Create a movie that shows all frames in axial orientation

**Comment by peristeri** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add QC for sct_dmri_moco and sct_fmri_moco.](https://trello.com/c/XdnfipBC/5-add-qc-for-sct-dmri-moco-and-sct-fmri-moco)

**Comment by jcohenadad** [comment]
duplicate of https://github.com/neuropoly/spinalcordtoolbox/issues/1343
