### ISSUE TITLE
Compare multiple images for each QC.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1326]
### Description

In most commands, multiple files are created. It would be useful to have QC images of these intermediate images.

### Excepted Behavior

when running command such as `sct_register_to_template` with the `qc` option, the command will generate a report for anat2template/template and template2anat/anat. 
Axial view for the native space and template space. To avoid showing black slices (esp. in the template), we could detect non-null slices and just show them.

**Comment by peristeri** [comment]
@charleygros can you provide some feedback?

**Comment by jcohenadad** [comment]
Closing for now (minimum need)
