### ISSUE TITLE
create standalone function for optic

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1327]

**Comment by perone** [comment]
I'll work on this issue.
PS: I still cannot assign issues to my Github user.

**Comment by peristeri** [comment]
@benjamindeleener @jcohenadad what I proposed is to re-appropriate the `sct_get_centerline`.

I don't see it tested or used by other commands. Is it safe to rewrite the `sct_get_centerline` and have it focus on OptiC?

**Comment by jcohenadad** [comment]
@peristeri I would re-appropriate ```sct_get_centerline```
