### ISSUE TITLE
Update the ANTs binary to run on OSX 10.6 and above

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1331]
Compile the binaries to run on version 10.6 and above

**Comment by jcohenadad** [comment]
related to: https://github.com/neuropoly/spinalcordtoolbox/issues/561

**Comment by jcohenadad** [comment]
Given that 10.6 is already pretty old, and not supported by major software, I think we should close this issue and not maintain 10.6 compatibility anymore.
