### ISSUE TITLE
[sct_register_multimodal] restrict deformation optional

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1345]
Please make `restrict deformation` an optional argument. 
Atef is using Ants for the Brain, sct_register_multimodal is very useful (notably because AntsRegister provides no feedbacks on user), but I had to remove `Line 639: --restrict-deformation 1x1x0 `

**Comment by jcohenadad** [comment]
glad to hear that SCT can be useful for brain data ;-) 
OK, we will make the change
