### ISSUE TITLE
Add documentation and templates for sct_pipeline

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1348]
### Description

Document how to setup and run a pipeline on both HPC and locally. With the documentation, provide a template script for the most common use cases.

**Comment by poquirion** [comment]
psutil from pip break on scinet (centos 6.4) but not on guillimin (centos 6.6). Not sure why but the conda version is ok. Updating that in the requirements.

**Comment by poquirion** [comment]
@benjamindeleener 
I am adding doc to [run `sct_pipeline` on hpc](https://sourceforge.net/p/spinalcordtoolbox/wiki/mpi%20install/). However, I might no be the best one to [document the command itself](https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_pipeline/), I've started doing it, but it might be better if you have a look at it.
