### ISSUE TITLE
[on branch viewerQt] -init-centerline viewer doesn't save and proceed with segmentation

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#1356]
### Prerequisites
On branch viewerQt

### Description
When using ` -init-centerline viewer`, the "save & quit" button doesn't seem to work. When clicking, nothing is happening, the window stays open and the segmentation is stuck. 

### Steps to Reproduce
Command used: 
`sct_propseg -i t1.nii.gz -c t1 -init-centerline viewer`

Data: 
`sct_example_data/t1`

### State of spinalcordtoolbox
```
$ sct_propseg -i t1.nii.gz -c t1 -init-centerline viewer

--
Spinal Cord Toolbox (viewerQt/06fcfe0bf91ddec1ecfc651334602be95ac082cc)
Running /Users/saradupont/Neuropoly/code/spinalcordtoolbox/scripts/sct_propseg.py -i t1.nii.gz -c t1 -init-centerline viewer

...
```

### Additional Information

![on_viewerqt_init-centerline](https://user-images.githubusercontent.com/5857909/27055775-86e5a36a-4f93-11e7-8fba-bfe20412147b.png)

**Comment by peristeri** [comment]
Fixed in the new viewer
