### ISSUE TITLE
Fixes for multi-processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1371]
- [x] systematic redirection of "output" in case of error
- [x] creation of subject-specific log file (done at the parent process instead of within testing)
- [x] display the correct CPU core in case using --mpi
- [x] make it possible to select number of CPU for multiproc mode (not mpi)
- [x] create doc
- [x] create template files for easy testing
- [x] indicate user that he is running mpi or normal mode

**Comment by poquirion** [comment]
see #1409  for log part
