### ISSUE TITLE
Integrate SCT in Flywheel 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1380]
Link: https://flywheel.io/about/

I talked to the CEO of Flywheel at OHBM17, it's fairly easy to integrate third-party software. SCT needs to be dockerized, then a json file describes the actions and i/o for files.

Contact person: Travis Richardson

**Comment by peristeri** [comment]
This is a decision the lab need to make. The company's strength is managing large medical datasets.  Does the lab want to offload the management of the dataset to flywheel? The company's literature does not give details on how is it done, if it works with OSF.

**Comment by jcohenadad** [comment]
closing that for now, we have other priorities for SCT integration (e.g. CBRAIN)
