### ISSUE TITLE
the documentation of the parameter -winv is incorrect

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1403]
### Description

When calling `sct_register_graymatter` with the `-winv` parameter the application throws an exception:
The command
```
/home/brain/sct_3.0.6/scripts/sct_register_graymatter.py -gm merge_cropped_gmseg.nii.gz -wm merge_cropped_wmseg.nii.gz -w warp_PAM50_t22merge_cropped.nii.gz -winv warp_merge_cropped_reg_gm2PAM50_t2.nii.gz
```
returns
```
ERROR: The file warp_merge_cropped_reg_gm2PAM50_t2.nii.gz does not exist. Exit program.
```

Instead of creating the file.

EDIT:

The documentation of the parameter is incorrect. the parameter is an input file and not a output file.

**Comment by jcohenadad** [comment]
Hi George, how exactly did you call this fonction?

**Comment by peristeri** [comment]
The issue was reported by https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/c44382f5/

The command is :
```
/home/brain/sct_3.0.6/scripts/sct_register_graymatter.py -gm merge_cropped_gmseg.nii.gz -wm merge_cropped_wmseg.nii.gz -w warp_PAM50_t22merge_cropped.nii.gz -winv warp_merge_cropped_reg_gm2PAM50_t2.nii.gz

```

**Comment by jcohenadad** [comment]
if you look into the code, you will notice that ``fname_warp_target2template`` from flag ``-winv`` is in fact an input argument, not output.
The usage needs to be adapted accordingly. I assigned @SaraDupont to this

**Comment by SaraDupont** [comment]
Yes, the param -winv is in fact an input param i.e. the user needs to input the inverse warping field (anat --> template) to be able to output the corrected inverse warping field. 
What about replacing: 
``` -winv <file>                 Warping field: image -> template.```
by:
``` -winv <file>                 Input the inverse warping field: [anat -> template] if you need to output the corrected inverse warping field.  ```

**Comment by jcohenadad** [comment]
sounds good, please also move this flag out of the "OUTPUT" sub-section

**Comment by SaraDupont** [comment]
Ok !
