### ISSUE TITLE
Add flag to change voxel dimension before running PropSeg

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1406]
### Description

In cases of cord compression, propseg often fails because it initialize using a cylindrical mesh. One solution is to stretch the image in the AP direction, run propseg and compress back the seg. Example here:
https://www.dropbox.com/s/okst58h8r9sx2do/20170713_propseg_stretched.m4v?dl=0

**Comment by jcohenadad** [comment]
add this tips to the documentation, and maybe suggest this also for `sct_deepseg_sc`

**Comment by jcohenadad** [comment]
@benjamindeleener i have received several requests from people who would like to use propseg in small animals. As you know it currently fails because the cord is too small, which is why we proposed a hack to stretch the cord (and then compress it), as exemplified [here](https://github.com/sct-pipeline/mouse_segmentation).

However, i was wondering what it would take to modify propseg to allow inputing custom size. My understanding is that setting the already-existing flag `-radius` is not enough (because when we try, e.g., `-radius 2` it still does not work). Could you please let us know if you see this as a possible/easy fix? I think it would make it much easier for people to bypass the stretch/compress hack, which is not so simple to do (e.g., they need to find the `FixedParameters` ITK param, they need to do some trial-and-error if the cord is not centered, etc.).

**Comment by benjamindeleener** [comment]
@jcohenadad unfortunately, this is not an easy fix. PropSeg contains many parameters (deformable models balance/constraints) that were adjusted for the dimensions of humans. This explains why reducing the radius of the initial mesh will not properly work. Playing with other parameters in the command-line might help: `-d`, `-distance-search` and `-alpha`. I'll refer you to the documentation and the paper for in-depth explanation of what the parameters do in the deformable models. However, the parameters for adjusting the propagation are not available in the command.

**Comment by jcohenadad** [comment]
@benjamindeleener i see, basically the issue is that there is an interplay between some of the parameters (alpha, beta, h, l, etc.), which makes the problem non-scalable (i.e., non-linear). In that case, how about introducing a scaling parameter to the propseg API, that would change the pixel dimension of the header (e.g., -scale 0.5 would multiply px, py and pz by 0.5) before running propseg. The nice thing is that it would be instantaneous. Would something like this work? Have you already tried it?

**Comment by benjamindeleener** [comment]
@jcohenadad Yes, actually, I think changing the header of the image would suffice to "fool" PropSeg and make it work for animals. And this could be done in the Python script, which would avoid us to change the C++ code and need to recompile.

**Comment by jcohenadad** [comment]
Reopening this issue, because improvements could include:
- having sct_resample do the job (instead of dumping code inside sct_propseg)
- sform should also be updated (not only qform), otherwise straightening will fail.

**Comment by jcohenadad** [comment]
now addressed with flag `-rescale`
