### ISSUE TITLE
Feature to detect the PMJ presence/position

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1410]
### Description

- New feature
- Goal: Detect the presence/position of the PMJ on T2 or T1 images
- Could be used for: separating brain/spine sections, croping an image or a centerline mask or a SC segmentation mask, analyzing the CSA between C3 and PMJ levels...etc.

### Suggestion 1:
```
sct_detect_XX -i t2.nii.gz -c t2 -s t2_centerline.nii.gz
```

Function's name suggestions:
- `sct_dectect_pmj`
- `sct_detect_brain_section`

Output:
- an image with one voxel with value = 50 (cf label_vertebrae convention) if PMJ detected, empty image if not (or no output?)

Flag description:
- `-c`: Mandatory, {t1, t2}: there is one model for T2-like images and another for T1-like images
- `-s`: Optional, SC segmentation file OR SC centerline file: could help if the PMJ is not clearly visible on the 2D mid-sagital slice because the detection is done on the 2D mid-sagital slice

### Suggestion 2:
(---> If the PMJ detection is only used for cropping the centerline between brain and spine regions)

A module used by/integrated in `sct_get_centerline` instead of a new sct function

**Comment by jcohenadad** [comment]
I would go with suggestion 1: `sct_dectect_pmj`. While I agree with suggestion 2, it is not incompatible with suggestion 1. We could write the function with the new proposed architecture by PO/George, i.e., having a module `dectect_pmj` that could be imported from other functions (e.g., `sct_get_centerline`). Having it in a standalone file allows more flexibility and visibility (if users go with "sct + TAB" to see all SCT functions).

**Comment by charleygros** [comment]
# Report 24 July 2017

Development on the branch called: `cg_i1410`

I have finished a first version of this function and I would like your advices on it.

### Usage
```
DESCRIPTION
Detection of the Ponto-Medullary Junction (PMJ).
   This method is machine-learning based and adapted for T1w-like or T2w-like images.
   If the PMJ is detected from the input image, a nifti mask with one voxel, with the value 50,
   located at the predicted PMJ level, is output ("*_pmj.nii.gz").
   If the PMJ is not detected, anything is output from this function.

USAGE
sct_detect_pmj -i <file> -c {t1,t2}

MANDATORY ARGUMENTS
 -i <file>                    input image.                  
 -c {t1,t2}                   type of image contrast, if your contrast is not in the available 
                              options (t1, t2), use t1 (cord bright / CSF dark) or t2 (cord dark / 
                              CSF bright)

OPTIONAL ARGUMENTS
 -s <file>                    SC segmentation or SC centerline mask. Provide this mask could help 
                              the detection of the PMJ
 -ofolder <folder_creation>   Output folder                 
 -qc {0,1}                    Output png image for quality control. Default value = 0
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   Verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1
```

### Terminal output
```
python sct_detect_pmj.py -i /Users/chgroc/data/i1410/t1/t1.nii.gz -c t1 -s /Users/chgroc/data/i1410/t1/t1_seg_manual.nii.gz -ofolder /Users/chgroc/data/i1410/t1 -qc 1 -r 0
Check folder existence...

Create temporary folder...
sct_crop_image -i t1.nii.gz -start 88 -end 88 -dim 2 -o t1_midSag.nii

Run PMJ detector

Ponto-Medullary Junction detected

Save quality control images...
QC output image: /Users/chgroc/data/i1410/t1/t1_sagittal_plane.png & /Users/chgroc/data/i1410/t1/t1_sagittal_plane_seg.png
WARNING: File t1_pmj.nii.gz already exists. Deleting it.
	x_pmj = 142
	y_pmj = 194
	z_pmj = 87

Save resulting file...

Done! To view results, type:
fslview /Users/chgroc/data/i1410/t1/t1.nii.gz /Users/chgroc/data/i1410/t1/t1_pmj.nii.gz -l Red -t 0.7 &
```

### Script architecture
I have tried to follow the guidelines of Pierre-Olivier. I will ask him his opinion on it.

### Quality control image
- May be we want to adapt it in order to be integrated into sct_qc process?

- It needed small changes in msct_image/save_quality_control in order to output a specific slice (index_slice parameter)

- output a png image (small small red dot):
![t1_sagittal_plane_seg](https://user-images.githubusercontent.com/14353425/28536320-3b2fd816-7075-11e7-9292-b456773d17a3.png)

Any comment is more than welcome!

**Comment by jcohenadad** [comment]
a few comments:
- "...If the PMJ is not detected, anything is output from this function." --> did you mean "nothing is output"?
- QC image: rotate it, and make the red spot way bigger. Alternatively, make a ~15x15mm green box centered around the PMJ (i prefer this option)
- usage/output we can affine these details later

**Comment by charleygros** [comment]
Few comments addressed and pushed.

![qc_pmj](https://user-images.githubusercontent.com/14353425/28548780-04adf6a4-70a4-11e7-9789-a8e5ad9d9c22.png)

**Comment by jcohenadad** [comment]
nice, i would go for a flashy green:

<img width="319" alt="screen shot 2017-07-25 at 08 11 01" src="https://user-images.githubusercontent.com/2482071/28558182-07708d44-7111-11e7-9ead-beb7fbfde4b7.png">

**Comment by benjamindeleener** [comment]
Documentation (`-help`):
`-s` parameter shouldn't be there. It is too dangerous as segmentation/centerline usually don't reach the PMJ.

**Comment by charleygros** [comment]
Results without straightening:

*T1w*:
```
Recall = 1.0
Precision = 0.987
Distance error = 0.46 +/- 11.37 mm
```

*T2w*:
```
Recall = 0.86
Precision = 0.888
Distance error = 0.108 +/- 13.59 mm
```
