### ISSUE TITLE
parser should expand tilde 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1416]
currently, if "~" is used to describe file or folder, it is not interpreted correctly. A solution is to use ```os.path.expanduser()``` python function in the parser.

Once done, remove all "expanduser" in the code.

**Comment by zougloub** [comment]
Suggest to close : the shell (which invokes the program) is responsible for doing the expansion of `~`. About the only time `os.path.expanduser()` is used is in very specific contexts (eg. reading of some config. files).
