### ISSUE TITLE
[sct_register] manage dimensionality for 2D

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1429]
Register
`````
isct_antsRegistration --dimensionality 2 --transform Affine[0.5] --metric MeanSquares[dest.nii.gz,src_regaffine_smooth.nii.gz,1,4] --convergence 100x100 --shrink-factors 2x2 --smoothing-sigmas 1x1vox --transform BSplineSyN[0.5,3] --metric MeanSquares[dest.nii.gz,src_regaffine_smooth.nii.gz,1,4] --convergence 500x500 --shrink-factors 2x2 --smoothing-sigmas 1x1vox --output [warp_,src_regaffine_smooth_reg.nii.gz]

fslview dest.nii.gz src_regaffine_smooth_reg.nii.gz &
`````
![screen shot 2017-08-01 at 11 34 10 am](https://user-images.githubusercontent.com/7785316/28833450-5d12d03a-76ad-11e7-8ab1-f6aa4faa9639.png)

Then
`````
sct_concat_transfo -d dest.nii.gz -w warp_1Warp.nii.gz,warp_0GenericAffine.mat
`````
and
`````
sct_apply_transfo -i src_regaffine_smooth.nii.gz -d dest.nii.gz -w warp_final.nii.gz
fslview dest.nii.gz src_regaffine_smooth_reg.nii.gz &
`````

![screen shot 2017-08-01 at 11 35 00 am](https://user-images.githubusercontent.com/7785316/28833488-7a065586-76ad-11e7-9926-0e50481ece14.png)

data under:
````
/Volumes/folder_shared/sct_issues/20170801_tanguy
````

**Comment by tanguyduval** [comment]
I tried

1. invert warp and affine in sct_concat_transfo
2. Remove affine transfo : `isct_antsRegistration --dimensionality 2 --transform BSplineSyN[0.5,3] --metric MeanSquares[dest.nii.gz,src_regaffine_smooth.nii.gz,1,4] --convergence 500x500 --shrink-factors 2x2 --smoothing-sigmas 1x1vox --output [warp_,src_regaffine_smooth_reg.nii.gz]`

**Comment by benjamindeleener** [comment]
Solution is fixed by PR #1420. We should merge soon @peristeri

**Comment by tanguyduval** [comment]
@benjamindeleener I have a similar issue...
Data under: folder_shared/sct_issues/20171121_tanguy
Commands:
````
sct_concat_transfo -d dest.nii.gz -w affine_0GenericAffine.mat,warp_Forward.nii.gz -o warp_forward_final.nii.gz
sct_apply_transfo -i srcAP.nii.gz -d dest.nii.gz -w warp_forward_final.nii.gz
````
Results:
![image](https://user-images.githubusercontent.com/7785316/33099677-a299d754-cedf-11e7-8920-0815ca8c7ef7.png)

However, if done separatly (without `sct_concat_transfo`):
````
sct_apply_transfo -i srcAP.nii.gz -d dest.nii.gz -w affine_0GenericAffine.mat
sct_apply_transfo -i srcAP_reg.nii.gz -d dest.nii.gz -w warp_Forward.nii.gz
````
![image](https://user-images.githubusercontent.com/7785316/33099730-dc2f1fba-cedf-11e7-8797-bcf424d52664.png)

**Comment by tanguyduval** [comment]
Note that I see in terminal `isct_antsApplyTransforms -d 2` and `isct_ComposeMultiTransform 3`

**Comment by tanguyduval** [comment]
Ok I'm updating and testing with last version of SCT...

**Comment by tanguyduval** [comment]
still have
````
isct_ComposeMultiTransform 3
````

**Comment by tanguyduval** [comment]
still have
````
isct_ComposeMultiTransform 3
````

SCT version: `Spinal Cord Toolbox (master/303bbffc75e825dd9d196676e129df551c36673e)`

**Comment by tanguyduval** [comment]
still have
````
isct_ComposeMultiTransform 3
````

SCT version: `Spinal Cord Toolbox (master/303bbffc75e825dd9d196676e129df551c36673e)`

**Comment by tanguyduval** [comment]
Calling `isct_ComposeMultiTransform 2` solves the issue. `isct_ComposeMultiTransform` should detect 2D!

**Comment by tanguyduval** [comment]
Calling `isct_ComposeMultiTransform 2` solves the issue. `sct_concat_transfo` should detect 2D!

**Comment by tanguyduval** [comment]
https://github.com/neuropoly/spinalcordtoolbox/blob/3ca9f79a0f7bd2aa3c98ed6a08b2e91a6932bf8e/scripts/sct_register_multimodal.py#L639

**Comment by jcohenadad** [comment]
@tanguy please revert back to the original title of the issue. Otherwise it messes up the tracking history. 
what you raised is another issue, related to another script.
please open a new issue, with data + syntax, assign me, i'll look into it
thx
