### ISSUE TITLE
Multiple crashes caused by check_and_correct_segmentation()

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1454]
Examples:
  * xuanwu_20160624-yaou_MS013

I'd like to do an extensive test, with/without this feature. We will keep the best one.

### State of spinalcordtoolbox

Spinal Cord Toolbox (master/a0617b16c5d7776a91ff8b8e2bc03c95fb869ba3)

#### sct_propseg -i t1/t1.nii.gz -c t1

d14a478cba159b5b27139192cabebcf32ff3682c/master:
~~~
Passed: 76/116
Crashed: 0/116
Mean: {'dice_segmentation': 0.8675209610129629, 'duration [s]': 80.44931010542244}
~~~

#### sct_propseg -i t2/t2.nii.gz -c t2

d14a478cba159b5b27139192cabebcf32ff3682c/master:
~~~
Passed: 223/301
Crashed: 0/301
Mean: {'dice_segmentation': 0.8995392931500836, 'duration [s]': 65.27538325461835}
~~~

b93178e48e0f08d27ebbbc0c90ea39545f86de5a/jca_issue1454
~~~
Passed: 220/301
Crashed: 0/301
Mean: {'dice_segmentation': 0.9118571356288937, 'duration [s]': 62.04237300612998}
~~~

#### sct_propseg -i t2s/t2s.nii.gz -c t2s

d14a478cba159b5b27139192cabebcf32ff3682c/master:
~~~
Passed: 201/336
Crashed: 0/336
Mean: {'dice_segmentation': 0.8597158948811471, 'duration [s]': 44.255353592690966}
~~~

b93178e48e0f08d27ebbbc0c90ea39545f86de5a/jca_issue1454
~~~
Passed: 201/336
Crashed: 0/336
Mean: {'dice_segmentation': 0.8621050399869569, 'duration [s]': 41.51233793795109}
~~~

**Comment by benjamindeleener** [comment]
`check_and_correct_segmentation()` is extremely important when approximating the centerline (straightening). If it fails, it should be fixed and not removed.

**Comment by jcohenadad** [comment]
ok, at the end the crase was NOT caused by check_and_correct_segmentation(). So we can close this issue.
