### ISSUE TITLE
Create an option to generate a centerline from a few points

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#1461]
### Description

We need a function to quickly create a proper centerline manually. The idea would be to have a viewer in which we select a few points along the centerline, and then the function creates a centerline that passes through the points.

This tool should be pretty straight forward to create. Basically, it would include these steps:
1. open a viewer to click on a few slices (we need a minimum number of points to have a correct centerline)
2. use smooth_centerline to approximate the centerline with NURBS (there is an option to get the point on each slices)
3. create an image with the centerline

**Expected behavior:**

The centerline should cover the region between the top and bottom points, be smooth and continuous.

A proposition for the command would be:
```
sct_get_centerline -i t2.nii.gz -mode viewer
```

**Comment by jcohenadad** [comment]
sounds good. To homogeneize the flag that refers to the mode/method/approach/etc. i was thinking of calling this flag `-method` as done in sct_extract_metric.

on the other hand, `-mode` is shorter, therefore better. 

in any case, let's take this opportunity to establish a convention for such flag and then add it to the wiki:
https://github.com/neuropoly/spinalcordtoolbox/wiki/flags

**Comment by jcohenadad** [comment]
fixed in PR #1467
