### ISSUE TITLE
fslview is now deprecated, which might cause issues if users have the new version

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1471]
### Description

New command: fsleyes. Old command deprecated to: fslview_deprecated.

### Proposed fix

Create function `display_viewer` in `sct_utils`, which would spit out on stdout the syntax for the default viewer. This function will be called at the end of each SCT function that has an image output. In the short term, this will be useful at the end of `sct_propseg` for fixing segmentation errors. 

we need to let the user choose during installation if he has **fslview** or **fsleyes** (in the future, other viewers could be supported), and this info would be encoded in a config file. E.g.: 
~~~
viewer=fslview  # possible options: fslview, fsleyes
~~~

@zougloub, @poquirion, @peristeri: does this sound like a reasonable fix? Any suggestions about the default config file? How to call it? where to put it: `~` or in `$SCT_DIR`?

### Working branch
https://github.com/neuropoly/spinalcordtoolbox/tree/jca_fslview

**Comment by zougloub** [comment]
The recommended location of configuration files depends on the platform (eg. on linux the current fashion is to have it in `~/config/` (= `${XDG_CONFIG_HOME}/`; see https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)), and it is not recommended to put configuration files (or any R/W file in the program installation folder, usually configured read-only by the user). Programs will usually start looking in there and may try `~/`after, and finally a system-wide configuration file (`/etc/`).

Then there is already a `.sctrc` file used by the launcher, setting a preferred viewer could be done in there. If no viewer is selected, the suggested function `display_viewer()` could try and see which first entry in series of viewers is executable, with something like (https://github.com/waf-project/waf/commit/f3f9e9f99d1c9a8975fa8afb2a8fd9f4b70edc62?diff=unified#diff-b7b076bb4de44dd3a2562a92af482f3eR453). So the configuration key would not be really *needed*.
