### ISSUE TITLE
Update -create-viewer argument to use parse_num_list function

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1476]
- [x]  move -create-viewer flag right after the "-create-seg" flag --> fixed by https://github.com/neuropoly/spinalcordtoolbox/pull/1712
- [x] enable to use ":", e.g., 2:5 for 2,3,4,5 --> use existing smart function from python

**Comment by joshuacwnewton** [comment]
> enable to use ":", e.g., 2:5 for 2,3,4,5 --> use existing smart function from python

The smart function here is `parse_num_list`:

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/spinalcordtoolbox/utils.py#L357-L370

This could still be done, but I'm not sure about this function in general. I want to think about it in the greater context of our argparse switch. So, adding it to the project board for now.

**Comment by lrouhier** [comment]
The use of 2:5 for 2,3,4,5 will be enabled with #3076.
