### ISSUE TITLE
-nbiter, max-area, max-deformation don't behave as expected

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1486]
### Description

Propseg parameters don't behave as expected. Here is a video:
https://www.dropbox.com/s/vawrrpby3vpgjw7/20171011_bugPropseg.m4v?dl=0

### Steps to Reproduce

data: duke/sct_testing/issues/20171011_issue1485

### State of spinalcordtoolbox

Spinal Cord Toolbox (jca_issue1484/be85eed7d070d9e16aae45ecd23aba1de12f8a82)

**Comment by benjamindeleener** [comment]
That's a complicated user case, as there is a huge contrast not far from the spinal cord and that the image is relatively small.

The parameters `-nb-iter`, `-max-deformation` and `-max-area` stop the propagation (in the z direction) of the deformable model. It does not actually affect the area that will be segmented on the first iteration.

For this particular user case, you should look into reducing the parameter `-distance-search` and modifying the parameter `-d`.

**Comment by jcohenadad** [comment]
ok i see, so the first thing would be to explicit in the usage that these parameters only affect propagation along z.

**Comment by jcohenadad** [comment]
btw, one thing that helped a lot (but really a lot!) was to simply rescale the image by 2x in the x and y direction. I have added documentation under "Stretching/Compressing the image" here:
https://sourceforge.net/p/spinalcordtoolbox/wiki/correction_PropSeg/

But what i don't understand is that by changing the default radius, this did not help at all.
