### ISSUE TITLE
sct_apply_transform issue when modifying warping field

### ISSUE THREAD

**Issue by alzaia** [neuropoly/spinalcordtoolbox#1488]
I am using the sct to do ANTS registration. When using my original warping field, it works (i.e. the output is different from the input). However, when I want to apply the warp/2 (i.e. values of the warping field divided by 2), the output is identical to the input. My warping field divided by 2 looks OK: similar to original warp, but range values are 2x smaller. To divide a warping field, I simply use element wise division, and then I save my new warp.

My calls: 

sct_apply_transfo -i tract1.nii.gz -d tract1_flip.nii.gz -w warp.nii.gz -o tract1_reg.nii.gz
sct_apply_transfo -i tract1.nii.gz -d tract1_flip.nii.gz -w warp_divided.nii.gz -o tract1_reg.nii.gz

First lines of the terminal:

--
Spinal Cord Toolbox (master/e63e9b9f2f37002627b5f741697580b91f9f717b)
Running /Users/alzaia/spinalcordtoolbox/scripts/sct_apply_transfo.py -i tract1.nii.gz -d tract1_flip.nii.gz -w warp1to2div.nii.gz -o tract1_reg.nii.gz

Parse list of warping fields...
  Transfo #0: warp1to2div.nii.gz

Get dimensions of data...
  35 x 53 x 1 x 1

Apply transformation...
isct_antsApplyTransforms -d 3 -i tract1.nii.gz -o tract1_reg.nii.gz -t warp1to2div.nii.gz -r tract1_flip.nii.gz -n BSpline[3]

**Comment by jcohenadad** [comment]
the format of ITK-compatible warping fields can be tricky (5-dimension file), so maybe this issue is related to the way you do the division and then save the warping field.

in order to reproduce the issue, we need the full list of commands.

**Comment by joshuacwnewton** [comment]
Closing, as this is a usage issue that has not received input in several years.

@alzaia If you still require assistance, please let us know and we can re-open this issue. :)
