### ISSUE TITLE
Improvement on the viewer

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1494]
- Add CMD+q option to quit process.
- When hitting CMD+q, quit `sct_propseg` and do not further process the segmentation.
- Fix: Title of the axial view is overlapping with image
- in -init-centerline 'auto' mode, at the most bottom slice, the last point does not appear
- The first and last slices are not available in the automatic mode.

**Comment by peristeri** [comment]
- For the third point, is it for all images? or is it for a specific image? I only get that behavior if the user zoomed in.

- Should the first and last slice be(0, max heigth) ?

**Comment by jcohenadad** [comment]
@peristeri: indeed, this happens when user zooms in.
first/last slice: i will let @benjamindeleener answer

**Comment by benjamindeleener** [comment]
@peristeri Not the first and last slices should not always be (0, max height) because of contrast issues at the edges. Let's keep it that way for now and see if it represent an issue as a user experience point-of-view.

**Comment by jcohenadad** [comment]
Personnally i would set 0-max, because we have a lot of users with 2d scans, and it is more detrimental for them to miss the 1st and last than to press skip on 3d data in case the 1st/last slices are missing
