### ISSUE TITLE
Error in refactored wm atlas creation pipeline

### ISSUE THREAD

**Issue by stephaniealley** [neuropoly/spinalcordtoolbox#1498]
### Description

Errors in create_atlas.m

### Additional Information

Bug 1:

Index exceeds matrix dimensions.

Error in create_atlas (line 620)
imagesc(tract_sum(:,:,800)), axis square, title('tract sum'), colorbar
 
620 imagesc(tract_sum(:,:,800)), axis square, title('tract sum'), colorbar

Bug 2:

Undefined function or variable 'which_template'.

Error in create_atlas (line 689)
filetractML = [path_out,folder_final,which_template,global_suffix];
 
689 filetractML = [path_out,folder_final,which_template,global_suffix];

**Comment by jcohenadad** [comment]
fixed in PR #1499
