### ISSUE TITLE
Clicking labels with viewer should allow 3D navigation

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#1501]
On some images, the spinal cord is not at the centre of the image, or does not stay at its centre when you go up and down.

One example of mislabeling can be seen below, where the red dot is a label I wanted to be at the PMJ and the green dot is the centerline.

![screen shot 2017-10-25 at 07 22 02](https://user-images.githubusercontent.com/7757117/31996257-cb3477f4-b955-11e7-9c47-245b5e8c22ee.png)

Command used:
```
sct_label_utils -i t2.nii.gz -create-viewer 50,49,1,2,3,4,5,6,7,8,9,10
```

**Comment by jcohenadad** [comment]
@benjamindeleener to make sure i understand: is it a mislabeling (i.e. the red point in the viewer does not correspond to the created voxel label), or is it a non-intuitive displacement of the image in the viewer when doing zoom/unzoom, which could lead to mislabelling?

If the former, we should label this as high priority

**Comment by benjamindeleener** [comment]
@jcohenadad The viewer currently only displays one sagittal slice (middle of the image), which is not convenient for labelling and lead to labels that are not centered in the spinal cord (or on the centerline), and this could lead to errors when reporting the labels to the centerline.

So being able to navigate in 3D would be useful, but is not critical for most user cases.

**Comment by jcohenadad** [comment]
ah! ok got it. Indeed i agree. We should also discuss in this thread possible design. For example, using arrows to change slices (and having an axial view that displays the current slice with a red line)

**Comment by benjamindeleener** [comment]
@peristeri 
Here are some details for the requested feature on the sagittal viewer:
```
sct_label_utils -i t2.nii.gz -create-viewer 50,49,1,2,3
```
- we need an **axial** image on the left of the sagittal image that would act as a slider. Moving around on the axial image would change the slice that is displayed on the sagittal panel. A red line  showing the current sagittal slice should be displayed on the axial panel.
- we need two buttons, **LEFT** and **RIGHT** that changes the slice in the sagittal panel. Left and right keys (on the keyboard) should be linked to these buttons.
