### ISSUE TITLE
sct_get_centerline description is missing

### ISSUE THREAD

**Issue by aliikhatibi** [neuropoly/spinalcordtoolbox#1504]
$sct_get_centerline 
sct_get_centerline does not show description and help information (in previous stable release 3.0.8 the help information are correct but current git version does not show them (no error message will be shown, still runs perfectly when arguments are included).

#sct_get_centerline 

--
Spinal Cord Toolbox (master/a7b4a1d582e19102ad945d7e6c547b1017e6f8a6)
Running /home/csayour/sct_master/sct/scripts/sct_get_centerline.py

**Comment by jcohenadad** [comment]
hi @aliikhatibi, thank you for reporting this issue. We have fixed it in the PR https://github.com/neuropoly/spinalcordtoolbox/pull/1453.
It should be merged with master within an hour.

**Comment by jcohenadad** [comment]
Fixed it in the PR #1453.
