### ISSUE TITLE
Rotations are badly regularized during registration to template

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#1515]
As rotations around the S-I axis are not regularized, large local rotation can occur.

Solution: develop a more accurate method to calculate the Z-rotation of the spine, that is regularized in the S-I direction.

Meanwhile, a flog to enable/disable the rotation in `sct_register_to_template` is a good quick solution for users.

Proposition for the name of the flag: `-rotation 0/1` (default 1). Any other idea?

**Comment by charleygros** [comment]
In which cases we would not want to regularize in the SI axis (rotation =1)?

**Comment by jcohenadad** [comment]
@benjamindeleener I though from Falk's email that the issue was rotation during straightening. If the issue is in fact during register_to_template, then there is already the possibility to not have rotations. 
Default param is: `step=1,algo=centermassrot`, and the user can use instead: `step=1,algo=centermass`.

**Comment by benjamindeleener** [comment]
Sorry I wasn't precise enough and you are right. The rotation that is currently calculated during the registration to the template is regularized by default with a polynomial function of degree 5 and can produce local errors.

I actually run `sct_register_to_template` on `sct_testing` and it produces large rotation errors.

A movie with the error here (MUST SEE!): https://www.dropbox.com/s/buejsn2kt1g8jhh/sct_testing_rotation_errors.mov?dl=0

I would like to change the default method from `step=1,algo=centermassrot` to `step=1,algo=centermass` until we find a better regularization and/or rotation detection method. What do you think?

@jcohenadad There is no rotation involved in the straightening. All rotations are in `sct_registration_to_template`.

**Comment by jcohenadad** [comment]
geeze... scary video. A bit too late for halloween now...
ok for setting default value to `algo=centermass`
