### ISSUE TITLE
indicate full OS during installation and remote connection

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1524]
easier to debug such cases:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/9d988979/?limit=25#bc03

**Comment by peristeri** [comment]
It seams that the pandas package dependency "pytz" is not accessible. Can the user print out the list packages? The channel which the package is installed comes from `conda_forge`, while in my version it comes from the `default` channel. There might be a conflict in channels.

Check if the user's `~/.condarc` looks something like this:

```
channels:
  - defaults
  - conda-forge
```

**Comment by poquirion** [comment]
`sct-dirt/python/bin/conda config --show`

Would also help. But it is most likely set in `~/.condarc`

**Comment by zougloub** [comment]
Printed by sct_check_dependencies -> closing
