### ISSUE TITLE
Integrate linters into TravisCI

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1538]
In order to automatically catch small issues like unused imports, undefined variables, etc, we can just integrate tools such as [Flake8](http://flake8.pycqa.org/en/latest/index.html), [Pylinter](https://www.pylint.org/) and [PEP8](https://pypi.python.org/pypi/pep8) into the continuous integration. By doing that, pull-requests can be fixed before the review process, taking less time of reviewers and enforcing code-style conventions, etc.

**Comment by zougloub** [comment]
We should first do a clean-up of the issues prior to have *all* the PR fail because of having merged this too early.
So I'd suggest for the PR fixing this commit, to do something to all the .py files, such as removing the "modified" header... and fixing the pending issues.
I am in the middle of something that touches a lot of files and wouldn't want someone to suffer from merging, so I'd recommend to wait for #1535 to be merged prior starting to fixup the linting issues...

**Comment by cfhammill** [comment]
It might be worthwhile to add this to CI now or at least after a little progress has been made on #2439, but set it such that noncompliance is a warning, not a failure. We can change it to a failure once that wouldn't cause most PRs to fail.

**Comment by joshuacwnewton** [comment]
Worth noting, we do have a linter running in `.ci.sh`, but it's not very useful at the moment (as described in https://github.com/neuropoly/spinalcordtoolbox/issues/3142#issuecomment-752818671).

https://github.com/neuropoly/spinalcordtoolbox/blob/6172cd22feeb0f64ac1bd68bce3f89f7109e68b8/.ci.sh#L26-L28

If/when a linter is added, this old call should be removed.

**Comment by kousu** [comment]
I'm proposing to remove the old call in #3125 since it's completely useless and just adding an extra 3 minutes (3*N cumulatively) to our CI runs.

That would make this issue here about re-adding a `flake8` instead.

**Comment by joshuacwnewton** [comment]
I've added a GH Action workflow in #3215 that places pretty annotations right next to line diffs. :smile: 

![Screenshot from 2021-02-09 11-40-35](https://user-images.githubusercontent.com/16181459/107396435-befba400-6acb-11eb-92ae-314fe2de3e2e.png)

**Comment by joshuacwnewton** [comment]
One other note: I think whichever method we land on should be able to cleanly replace the [Code style](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Code-style) Wiki page. I'm happy to make the internal docs a little leaner when appropriate; the fewer things that need to be looked up, the better. 🙂
