### ISSUE TITLE
Performance improvements for the tests

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1539]
By using Python multiprocessing capabilities, we can launch each test from the `sct_testing` in parallel instead of executing them serially. I did a small test and it improved ~3.4x the execution time of the tests on a machine with 4 cores, however, more work is required to accommodate the logging messages during the parallel execution.

**Comment by zougloub** [comment]
Not only for the resulting performance improvement, but because of #1620 we could also end up using multiprocessing.

**Comment by joshuacwnewton** [comment]
This has been addressed by #1872. Closing.
