### ISSUE TITLE
Installer PATH management inconsistencies

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1542]
Exhibit A:
```
Not adding /home/cJ/sct_dev to $PATH
You can always add it later or call SCT functions with full path /home/cJ/sct_dev/bin/sct_function
```
This:
- Should mention `sct_dev/bin`.
- Should mention "full path:" and `${sct_function}` or `<sct_function>` or "eg. /path/to/sct_propseg".

Exhibit B:
```
Open a new Terminal window to load environment variables, or run:
 source /home/cJ/.bashrc
```
This was after refusing to add to PATH, so this shouldn't be stated.

**Comment by joshuacwnewton** [comment]
I believe this has been addressed. The install script now ends with:

```
To use SCT, please update your environment by running:
export PATH="/home/joshua/Desktop/spinalcordtoolbox/bin:$PATH"
```

Rather stating the message in the description.
