### ISSUE TITLE
Issues building C++ with ITK 4.12.0

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1543]
To be able to build binaries in master:
- [x] Had to add `ITKIOTransformBase` to linked libs in isct_propseg
- [ ] Same thing for sct_detect_spinalcord, plus `ITKOptimizers`

This might due to a reorg of ITK libraries, or maybe it's a problem that is highlighted by the `--as-needed` linker flag that is by default on my system, I haven't investigated.

I also saw 2fa99983156abcc083f92d76286a399c5cb7a562, which I didn't test, so some cmake-fu might be required to make all that work.

**Comment by zougloub** [comment]
Will submit a first PR, If someone could try my changes on the reference build platforms to see if they also work, that would be nice.

**Comment by zougloub** [comment]
(propseg done: #1685)

**Comment by joshuacwnewton** [comment]
> Same thing for sct_detect_spinalcord, plus ITKOptimizers

I'm a little confused about this. From what I understand, we no longer compile our own binaries for spinal cord detection, and instead use the [external `isct_spine_detect`](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Pre-compiled-binaries#isct_spine_detect-isct_train_svm). 

But, `sct_detect_spinalcord` is still listed in `make_binaries.sh`:

https://github.com/neuropoly/spinalcordtoolbox/blob/d94f602fe0b9466e656122f1bc554860002918ef/install/make_binaries.sh#L11-L12

Is `make_binaries.sh` out of date, then?

**Comment by kousu** [comment]
I don't believe anything in `./install/` is still in use, nor `./dev/`. Certainly nothing in there is getting tested regularly. I tried briefly to get one of them compiling a few months and failed miserably, so..yeah that script is broken.

We are still distributing `isct_propseg` and `isct_dice_coefficient` in our compiled deps but I don't know where we're using them either.

**Comment by joshuacwnewton** [comment]
Thanks for the input, @kousu! It sounds like binary compilation has evolved a lot since this issue, and now has a different set of problems now. I don't think the info in this issue is as relevant -- #2669 looks to be sufficient here. Closing. :)
