### ISSUE TITLE
QC: generated qc folder should be opened without sct 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1555]
for easy sharing

**Comment by zougloub** [comment]
I guess that instead of containing a JSON file, the qc folder would have to have an HTML file.
Since images are linked and not embedded, the JSON file could stay as is, but an HTML entry point that uses it could be generated.
Note that if the file is to be shared, perhaps embedding the image data inside would be relevant. But it could grow to unreasonable sizes so that should optional.

**Comment by jcohenadad** [comment]
@peristeri can we start discussing possible designs for solving this issue?

**Comment by peristeri** [comment]
The biggest constraint is the browser itself. Most modern browsers have a security feature that prevents loading javascript stored on the local machine. Thus why I created the script sct_qc. The script itself does not depend on SCT (I could replace msct_parser with python's argparse). So one solution is to copy the sct_qc in the same directory as the index.html and thus the user can call sct_qc without installing SCT, as long as the machine has a working copy of python.

**Comment by jcohenadad** [comment]
Is there any workaround to the security issue? Like not using javascript? FSL generates html reports which can be opened by any browser. 
@zougloub @perone any idea?

**Comment by perone** [comment]
I think that if the html file is opened from a local filesystem in the browser (not serving it on a http server), it should be ok, sphinx documentation is an example of that, it loads javascript from the html docs from the local folder (at least on Chrome, not sure about safari and other browsers, @peristeri was this happening on which browser ?).

Now, another alternative that would be easy is to use the fsleyes `render` command that allows you to [off-screen rendering](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/command_line.html#off-screen-rendering) for the purpose of quality control.

Some examples of the images generated using the `sct_deepseg_sc` command below:

`fsleyes render --scene ortho -of ortho.png t2.nii.gz t2_seg.nii.gz -a 50 -cm yellow`

![image](https://user-images.githubusercontent.com/412328/38041493-e073e6ec-327f-11e8-9b17-273ae9f3b03e.png)

and also a very similar to the ones generated by `sct_qc`:

`fsleyes render --scene lightbox -of lightbox.png t2.nii.gz t2_seg.nii.gz -a 50 -cm yellow`

![image](https://user-images.githubusercontent.com/412328/38041523-f4e24dbc-327f-11e8-8626-ac0941edba27.png)

There are also many other options that can be used:

`fsleyes render --fullhelp`

Anyway, it's something worth considering, given that if it is possible to use it for what we want, then we don't need to develop anything except for a wrapper calling `fsleyes`, saving images, etc.

**Comment by peristeri** [comment]
@perone There was feedback I got in the initial development of report generator that concluded in the development of sct_qc. I realized that previous statement is wrong and I was going on what I remembered. 

Opening the index.html file should work directly in the browser (I tested it on firefox)

**Comment by jcohenadad** [comment]
@perone fsleyes is nice but for such an important feature we'd prefer to minimize dependency with FSL, because we had license compatibility issues in the past (i.e. FSL license is not compatible with commercial use whereas SCT license (MIT) is).

@peristeri I tried to open index.html and the images did not load. See below:
<img width="492" alt="screen shot 2018-03-29 at 15 05 12" src="https://user-images.githubusercontent.com/2482071/38072792-f83f0ffc-3362-11e8-8899-152b368d7ca4.png">

**Comment by peristeri** [comment]
@jcohenadad can you press `Cmd+Opt+J` and refresh the page, and post any errors you get. Also try loading the page in incognito mode with none of the extension activated (it might be one of your extension that is blocking the loading of the json file.)

**Comment by jcohenadad** [comment]
on CHROME Version 65.0.3325.181 (with and without incognito mode):
~~~
jquery-3.1.0.min.js:4 Failed to load file:///Users/julien/qc_test/qc_results.json?no-cache=123&order=asc&_=1522373064047: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
~~~

on Safari 11.0.3:
~~~
[Error] Failed to load resource: Preflight response is not successful (qc_results.json, line 0)
[Error] XMLHttpRequest cannot load file:///Users/julien/qc_test/qc_results.json?no-cache=123&order=asc&_=1522373188734. Preflight response is not successful
~~~

**Comment by peristeri** [comment]
@jcohenadad it might be a security setting that's preventing access to local files. 

I suggest creating a minimal http server and copy it next to the index file. The only requirement is python.

**Comment by jcohenadad** [comment]
@perone @zougloub: do you have any other suggestion? i would really like to avoid creating a local server and depend on local python (what if python is not installed, etc.). Again, FSL reports don't require python. We just click on the index.html and it works in all browser.

**Comment by zougloub** [comment]
(I'm still AFK) Appending new QC entries to a single HTML file with an embedded payload (table/json, perhaps the pictures could be embedded too so the users can exchange QC reports without having to zip a whole folder or in case the images are also blocked) is certainly doable.

So as a user, I'd pass `-qc /path/to/qc-report.html` and send that file to my friends.

It's more RAM per entry, so with a few hundred/thousand images, the browser might start to feel bad.

**Comment by perone** [comment]
This is due to the browser security policies to avoid security issues. You can probably overcome that on Chrome by starting Chrome with a flag called `--allow-file-access-from-files`, however, browsers are recently getting even more restrictive on these matters.

A suggestion that I think that it will work well is to do the following:
1) Render the static HTML content using a templating engine (such as [jinja](http://jinja.pocoo.org/)) and avoid using external JSON file;
2) Save the generated images as files (as it is done today) but don't embed them;
3) Control animation, interactivity using Javascript, but without accessing local webserver;

And that is it, you'll have a single package with all the information you require and you won't have issues with different origin requests because everything is static (you don't need a webserver). This is the same approach adopted by Sphinx to generate docs, and for many static site generators such as [Pelican](https://blog.getpelican.com/), [Hugo](https://gohugo.io/), [Jekyll](https://jekyllrb.com/), etc.

Does anyone see a problem with that ? As I understand, we can have the same that we have today without the webserver.

**Comment by jcohenadad** [comment]
great, thanks very much @perone and @zougloub, a few comments:
- we certainly don't want to ask users to modify their browsers security preferences (e.g. flag `--allow-file-access-from-files`)
- having to zip a folder (to exchange QC folder between users) is not too problematic in case embedding all images becomes an issue wrt. speed, RAM, etc.
- in most cases we won't have to deal with hundred/thousand images. Likely below 100. 

@peristeri: what do you think? can the discussed approach be implemented quickly so that we could test/fix possible issues that were not anticipated?

**Comment by peristeri** [comment]
For the sake of clarity, what is suggested is: 

The new implementation is to copy the json file in the html as a javascript variable. And the remaining structure will remain unchanged. It is the user's responsability to share qc directory and manually open the index.html file.

**Comment by perone** [comment]
Just to complement: if you use a templating language to generate the HTML files, there is no need for the JSON, but if the JSON reading code is already done, then adding its contents as a variable would be easier.
