### ISSUE TITLE
sct_pipeline broken

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#1558]
I get that at the end of a process that has run successfully

```
====================================================================================================
INTEGRITY TESTING
====================================================================================================

Param instance has no attribute 'fname_gt'
```

Comming form the function_launcher running extra tests

**Comment by jcohenadad** [comment]
@poquirion could you please add the syntax you used (would be useful to know what test function misses the fname_gt). Thx

**Comment by poquirion** [comment]
```
../spinalcordtoolbox/bin/sct_pipeline -cpu-nb 3 -f sct_propseg -d /home/poquirion/neuropoly/very_small  -p  \"-i t2s/t2s.nii.gz  -c t2s\"
```

**Comment by jcohenadad** [comment]
`sct_pipeline` is not more broken. there have been a couple of PRs since, so it is difficult (i.e. takes time) to retrace which one fixes this issue.
