### ISSUE TITLE
Formatting problem with the sourceforge generation syntax

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1560]
The syntax:
~~~
sct_register_multimodal -sf
~~~
Produces ugly-looking entries for flag param:
https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_register_multimodal/

I guess this will be solved when we will be moving to sphinx-type doc, but some outstanding issues should be solved now because people are currently using the SF doc.

**Comment by joshuacwnewton** [comment]
> I guess this will be solved when we will be moving to sphinx-type doc

Indeed! :stuck_out_tongue_winking_eye:
