### ISSUE TITLE
implement the deep learning-based cord segmentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1566]
this is becoming quite urgent as more and more users are struggling with propseg.

**Comment by benjamindeleener** [comment]
The deep learning-based segmentation, based on @charleygros work is being implemented in branch [bdl_scdeepseg](https://github.com/neuropoly/spinalcordtoolbox/tree/bdl_scdeepseg). Work in progress.

**Comment by benjamindeleener** [comment]
The function is implemented and functional.

Here are some preliminary results on a T2- and T2*-weighted image from a DCM patient (with compression).

T2: https://www.dropbox.com/s/tk51xe28pjdmkwg/deepscseg_t2_DCM.mov?dl=0
T2*: https://www.dropbox.com/s/cnwpdtlgw8wu9kt/deepscseg_t2s_DCM.mov?dl=0

The results are great although not perfect. More to come soon.
