### ISSUE TITLE
General improvement of QC module

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1573]
- See: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/b97dd880/?limit=25
- To evaluate the state of the QC module, run the following: ./batch_processing.sh. And at the end, run sct_qc as explained.
- Use this QC for more functions.
  - sct_deepseg_gm
  - sct_deepseg_sc

**Comment by zougloub** [comment]
Added `sct_deepseg_*` qc calls.

As for the "general improvements"... not sure what to do at this point. `qc` is called inside a module's main function, to generate (for smoke-testing purposes) a pair of background/overlay images and append some execution context information in a JSON file. Then there's a simple web GUI, which is pretty explicit as to what it does.
I'd propose to refactor the code, to allow each process to expose how it would be performing generation of smoke-testing data (as is done now) as well as A/B-testing by using common code (see #1603 about "diff reports"... the generated data could be included in these reports... a refactoring could deal with all these related issues).

**Comment by zougloub** [comment]
Fixed by #1647
