### ISSUE TITLE
Slice counting is wrong (only verbose issue)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1583]
To reproduce: `batch_processing`, look for process:
~~~
sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l labels.nii.gz -c t2 -qc /Users/julien/qc_batch_processing
~~~

output:
~~~
Split destination volume...
127/128..
 Done
~~~

should be:
~~~
Split destination volume...
127/127..
 Done
~~~

or:
~~~
Split destination volume...
128/128..
 Done
~~~

We need to decide if we want to go with 127/127 (meaning that slice starts at 0, which is the python way of counting) or 128/128 (slice starts at 1, which is the "human" way of counting).
@benjamindeleener, @charleygros any suggestion?

### State of spinalcordtoolbox

4398786185731564a37748ea6d3651112c9b5146

**Comment by jcohenadad** [comment]
i would start with 1 (instead of 0)

**Comment by fperdigon** [comment]
@jcohenadad  @zougloub  I already fix the count error, but I would like to report even before modifying the code if I add the -qc parameter, the error that is listed below appears. I do not know if this is due to any modification that is being made to the QC module.

```
Finished! Elapsed time: 87s
Traceback (most recent call last):
  File "/home/fco/spinalcordtoolbox/scripts/sct_register_to_template.py", line 686, in <module>
    main()
  File "/home/fco/spinalcordtoolbox/scripts/sct_register_to_template.py", line 596, in main
    generate_qc(fname_data, fname_template2anat, fname_seg, args, os.path.abspath(param.path_qc))
  File "/home/fco/spinalcordtoolbox/scripts/sct_register_to_template.py", line 610, in generate_qc
    qc.add_entry(
AttributeError: 'module' object has no attribute 'add_entry'
```

**Comment by zougloub** [comment]
Only explanation I could see would be if you hadn't reinstalled SCT to propagate the changes performed in `qc`: the `add_entry()` function is really there:
```
$ git rev-parse HEAD
caf11f46d92fe8765490a53325acbf0e2b36b8f1
$ git grep add_entry
scripts/sct_deepseg_gm.py:    qc.add_entry(
scripts/sct_deepseg_sc.py:    qc.add_entry(
scripts/sct_detect_pmj.py:    qc.add_entry(
scripts/sct_label_vertebrae.py:    qc.add_entry(
scripts/sct_propseg.py:    qc.add_entry(
scripts/sct_register_to_template.py:    qc.add_entry(
scripts/sct_segment_graymatter.py:    qc.add_entry(
scripts/sct_straighten_spinalcord.py:    qc.add_entry(
scripts/sct_warp_template.py:    qc.add_entry(
spinalcordtoolbox/reports/qc.py:def add_entry(src, process, args, path_qc, plane, background=None, foreground=None,
```

**Comment by fperdigon** [comment]
@zougloub Ooo, I see. If that is exactly what happens, I was working on the computer that I have in home, in which I have not reinstalled the SCT for some time. Thank you very much for the information.
