### ISSUE TITLE
Error with sct_env using zsh

### ISSUE THREAD

**Issue by emilljungberg** [neuropoly/spinalcordtoolbox#1590]
I'm running sct_v3.1.0 and having some issues using `sct_env` with [Z shell](https://en.wikipedia.org/wiki/Z_shell). When `sct_env` is sourced in my `.zshrc` it returns the following error
```
addtopath:3: bad substitution
```
When running bash as my shell, this error doesn't occur. It seems to be this line that gives the error
```
if [[ ":${!2}:" != *":$1:"* ]]; then
```
Apparently there are some differences between zsh and bash in terms of handling arrays which might be the root cause here. I tried to figure out how to fix this but couldn't find a fix directly. Thought someone here, better versed with the shell, might know.

It should be reproducible by installing zsh and running `source sct_env`.

This is not a major issue since most users probably doesn't use zsh but thought I would let you know. It is easy to do a manual workaround for me at the moment.

Thanks!

**Comment by jcohenadad** [comment]
Thank you for the feedback @emilljungberg! We are working on it.

**Comment by zougloub** [comment]
Note that I'm not an avid zsh user -- I just I tried to make use of a compatible subset of the bash/zsh languages until it worked... and removed the useless "I pretend to support csh" line of code -- so if someone knows how to do the same more elegantly (eg. getting rid of `eval` / how to `declare -n` in zsh???) that would be appreciated.

**Comment by jcohenadad** [comment]
@zougloub indeed, this is probably a trace from history. I let you remove it if you think this is no more required.

**Comment by emilljungberg** [comment]
@zougloub I tried your version of `sct_env` above but then I unfortunately get the following error:
```
/Users/emilljungberg/software/sct_v3.0/bin/sct_env:79: command not found: realpath
```
After reading up on it it seems like `realpath`, and the newer version `redlink` are available in `coreutils` which is not readily available in OS X.

**Comment by zougloub** [comment]
Should have thought about that... anyway, [here's a new version](https://github.com/neuropoly/spinalcordtoolbox/blob/cJ_zsh/install/sct_env) after falling back to the good old `cd $1; pwd`...

**Comment by emilljungberg** [comment]
Trying the new version I get this output, it doesn't seem to catch the right SCT path
```
Last login: Wed Jan 31 17:01:46 on ttys003
(base) ➜  ~ echo $SCT_DIR
/Users/emilljungberg
(base) ➜  ~ echo $PYTHONPATH
/Users/emilljungberg/scripts:/Users/emilljungberg/PhD/Code:
(base) ➜  ~ bash
bash-3.2$ echo $SCT_DIR
/Users/emilljungberg/software/sct_v3.0
bash-3.2$ echo $PYTHONPATH
/Users/emilljungberg/software/sct_v3.0/scripts:/Users/emilljungberg/scripts:/Users/emilljungberg/PhD/Code:
bash-3.2$
```
In bash it works fine but for some reason zsh doesn't grab the full path it seems. Can you reproduce this on your system or could there be something wrong in my zsh configuration?

**Comment by zougloub** [comment]
Your configuration is fine, the problem is that I didn't do a proper test... if you can try again (same link), it *should* work.

**Comment by emilljungberg** [comment]
Thanks @zougloub! All works now without any problems. 

Cheers!
