### ISSUE TITLE
Enable keyboard interruption

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1609]
If user needs to exit after long processing time. Currently, it is not handled properly, and terminal should be terminated:
~~~
julien-macbook:~/data/juntendo/mice_mri/template $ sct_maths -i tmp.template_mask-csf.nii.gz -dilate 15 -o tmp.template_mask-csf_dilate15.nii.gz 

--
Spinal Cord Toolbox (master/2b78f815bf1c7c66be65b2c7368d385fe50751f0)
Running /Users/julien/code/sct/scripts/sct_maths.py -i tmp.template_mask-csf.nii.gz -dilate 15 -o tmp.template_mask-csf_dilate15.nii.gz
^C^C^C^C^C^C


^C^C^C^C^C^C^C^C^C


^C
~~~

**Comment by fperdigon** [comment]
I have tried 2 approach to try to solve this, but without results
1- Using a signal
```
def signal_handler(signal, frame):
  print('Exit')
  sys.exit()
```
Then I put these before call the main function
```
import signal
    # to capture the Ctrl+C signal
    signal.signal(signal.SIGINT, signal_handler)
```
2- Use try , except 
 ```
try:
        main()
    except KeyboardInterrupt:
        print('Exit')
        sys.exit()
```
In both cases Ctrl + C only take effect once the dilation operation is finished.

I followed the source code of the morphological operation from scikit-image to scipy.
The function skimage.morphology.dilation calls a function in scipy written in C++ that performs the dilation([here](https://github.com/scipy/scipy/tree/93bf1a6a494fef15b383831529543c7c17635f24/scipy/ndimage/src))
when calling the aforementioned function python gives control of execution to the C ++ application, for this reason Ctrl + Z does not work

@peristeri @zougloub could you give me some idea

**Comment by jcohenadad** [comment]
@fperdigon if there is no "easy" solution i would just close this issue since this is an isolated case.

**Comment by perone** [comment]
The fix for that isn't worth it, you'll need to wrap the extension code to execute in another process or thread depending if the extension is holding the GIL or not. I would close this as @jcohenadad said.
