### ISSUE TITLE
ITK error when searching for body symetry

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#161]
data (on local): dev/gray_matter_segmentation/errsm_30/template_in_t2star_space/template/
sct_propseg -i MNI-Poly-AMU_T2.nii.gz -t t2 -verbose
Exception caught while computing symmetry
/usr/local/ITK-static/include/ITK-4.5/itkImageBase.hxx:184:
itk::ERROR: Image(0x7f9ac1b011e0): A spacing of 0 is not allowed: Spacing is [0, 33.9728]

**Comment by jcohenadad** [comment]
this happened on sct_example_data:
~~~
sct_smooth_spinalcord -i t1.nii.gz -s t1_seg.nii.gz
sct_propseg -i t1_smooth.nii.gz -c t1
~~~

**Comment by jcohenadad** [comment]
will be fixed with the new detection method
