### ISSUE TITLE
Make -c a mandatory input

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1613]
I had recent feedback from users who did not pay attention to this flag, and it resulted in bad segmentation (input was t1-weighted).

**Comment by rtopfer** [comment]
*bump
"-c" still listed under "OPTIONAL ARGUMENTS"

**Comment by charleygros** [comment]
*bump_bis

It will be fixed when this PR will be merged:
https://github.com/neuropoly/spinalcordtoolbox/pull/1647

**Comment by abtahizadeh** [comment]
Should be closed via #1647 ??

Reference: 
```mandatory=True``` applied

**Comment by jcohenadad** [comment]
fixed via #1647
