### ISSUE TITLE
Proposal: eliminate Pickled data (pickle is evil)

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1616]
Various compatibility issues brought by using Pickle to load and save data, which is the quick and dirty solution:

- Incompatibility with Python 3:  
```
   File ".../scripts/msct_multiatlas_seg.py", line 461, in load_model
   self.intensities = pickle.load(gzip.open(model_files['intensity'], 'rb'))
   UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 0: ordinal not in range(128)
```

- Pickling of data that is not really "serialized" and will cause issues on library updates (#1651, #1619):  
```
/sklearn/base.py:312: UserWarning: Trying to unpickle estimator PCA from version pre-0.18 when using version 0.19.0. This might lead to breaking code or invalid results. Use at your own risk.
```

**Comment by jcohenadad** [comment]
@zougloub what alternative to pickle would you suggest?

**Comment by zougloub** [comment]
HDF5-packaged data shouldn't be a bad idea, since h5py is already a dependency.
Would need to devise a structure for each case. I haven't looked at what's inside these msct_multiatlas_seg models.

**Comment by jcohenadad** [comment]
well, the thing is, `msct_multiatlas_seg` is to be used with `sct_segment_graymatter`, which is being replaced by `sct_deepseg_gm`. I am not sure we will (or should) continue to maintain `sct_segment_graymatter` in the near future.

**Comment by zougloub** [comment]
Personal opinion, there's merit in `msct_multiatlas_seg` (it provides another segmentation method, and usage of PCA is more "transparent") and the replacement is far from being production-ready... so I'd advocate to think about dealing with the issue before it becomes more expensive.

**Comment by joshuacwnewton** [comment]
We no longer use `msct_multiatlas_seg` nor do we use `sct_segment_graymatter`. We have also already made the leap to Python3. `pickle.load` is nowhere to be found in SCT, even! So, I believe this issue was addressed at some point. Closing. :)
