### ISSUE TITLE
msct_multiatlas_seg: replace model data format

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1617]
(part of #1616)

The model currently uses Pickle and tests fail with newer library (sklearn, numpy) or python versions.

**Comment by joshuacwnewton** [comment]
We no longer use `msct_multiatlas_seg` nor do we use `sct_segment_graymatter`. `pickle.load` is nowhere to be found in SCT, even! So, I believe this issue was addressed at some point. Closing. :)
