### ISSUE TITLE
sct_register_to_template Dice index change with some newer version of python packages

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1619]
At some point this issue is going to hit the bundled version too...

Running 3.1.1 with conda:
```
Checking sct_register_to_template...................[OK]
```

Running 3.1.1 with system interpreter with latest packages:
```
Checking sct_register_to_template...................[WARNING]
[...]
   Dice[seg,template_seg_reg]: 0.546286876907
   --> FAILED

   Dice[seg_reg,template_seg]: 0.612099644128
   --> FAILED
```

Also... the index is different when running with python3 (all packages being the same version):
```
   Dice[seg,template_seg_reg]: 0.348769490889
   --> FAILED
   
   Dice[seg_reg,template_seg]: 0.23642172524
   --> FAILED
```

Not sure yet which package would be to blame... but something odd is going on.

**Comment by jcohenadad** [comment]
wow nice catch!  @benjamindeleener can you please have a look?

**Comment by benjamindeleener** [comment]
I was able to reproduce the error, but I was not able yet to find where it came from. Everything is good until the concatenation of the warping field. So it might come from there. Still investiguating.

**Comment by zougloub** [comment]
I haven't provided reproduction steps, I hope you didn't waste too much time doing it.

**Comment by zougloub** [comment]
It's the model Pickle (of sklearn PCA) that's causing this issue.
Linking to #1616

**Comment by joshuacwnewton** [comment]
`test_sct_register_to_template` is currently passing using Python3 and the most recent versions of various packages. 

I'm not sure _how_ things were fixed, but as the original issue description is for Python2 as well as older package versions, I believe it is outdated and no longer relevant. We can open a new issue if this becomes a problem again.
