### ISSUE TITLE
sct_testing TLS memory usage grows beyond limit

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1620]
It seems that TensorFlow is hungry on TLS memory and this causes sct_testing to fail (on py3k for now) in Travis.

```
ImportError: dlopen: cannot load any more object with static TLS
```

Since `sct_testing`is importing all the code and it's not yet possible to un-import modules, we will end up having a problem.
Suggest to change `sct_testing` to use multiprocessing or subprocesses, to avoid this issue.

**Comment by jcohenadad** [comment]
Fixed by #1872
