### ISSUE TITLE
Temporary folder not flushed

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1624]
### Prerequisites

* [x] Did you check past issues for similar issue(s) ?
* [x] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [x] If you are using a development environment, is your environment updated ?

### Description

Some scripts keep temporary folders even if flag `-r` is set to 1. The scripts where this happen include:
- `sct_straighten_spinalcord` called in `sct_label_vertebrae`
- `sct_register_multimodal` called in `sct_register_to_template`
More details here: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/79d04fb7/?limit=25

### Steps to Reproduce

1. go to `sct_testing_data/t2`
2. run `sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -r 1 -c t2`
3. look for the line that indicate temporary folder for `sct_straighten_spinalcord`, example: 
~~~
Straighten spinal cord...
sct_straighten_spinalcord -i data.nii -s segmentation.nii.gz -r 0 -qc 0 # in /private/var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-180228093153-label_vertebrae-1HjVtZ
~~~
4. The folder indicated above is removed, however another folder called something like `sct-180228093558-straighten_spinalcord-zJLgvU` is also created, but not removed.

**Reproduces how often:**
Always.

### State of spinalcordtoolbox

v3.1.1.

### Additional Information

With `sct_register_to_template`, the following temporary folder remains: `sct-180228094036-register-8fCsaZ`

**Comment by zougloub** [comment]
`sct_straighten_spinalcord` was called with a hardcoded `-r 0`.
Applied as a patch in branch for #1618 (it would cause a merge conflict otherwise).

**Comment by jcohenadad** [comment]
👍 I'll review PR #1618 ASAP then. Thanks

**Comment by zougloub** [comment]
Taking a few minutes to also spot anything dodgy about unmatched temp. folder creation vs. removal, and respect of the remove_temp_files option.

**Comment by zougloub** [comment]
Should be better now.

Exhaustive check done that:

- The temp folder creation & removal are balanced for all the scripts:  
```sh
git grep -E "(path_tmp = |sct.rmtree.path_tmp.)" -- scripts/ spinalcordtoolbox
```
- No script is called with hardcoded `-r` argument (when it means remove temp. files):  
```sh
git grep '.-r., ..'
```

There was one script  (`sct_compute_snr`) that didn't have the option to not remove temp. files, so I added it, for consistency.

**Comment by imanbrouwer** [comment]
Hi guys,
I'm the one who posted the issue on the sourceforge help forum. I tested the tar that Julien posted and it works well. Thanks for the very fast fix!

Iman

P.S. The forum on sourceforge gives a 'static offline' notice the whole day already, that's why i'm posting here.

**Comment by zougloub** [comment]
Thank you @imanbrouwer, closing the issue then!
