### ISSUE TITLE
Github pull request template improvements

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1628]
(TBDiscussed)

Enter your suggestions here and thumbs up/down...

**Comment by zougloub** [comment]
Suggest to remove "Is there a issue open describing the motivation for this pull request ?" since linked issues become immediately visible upon code push (commits should themselves contain the issue id that are dealt with).

**Comment by zougloub** [comment]
Suggest to change the title `Description of the Change` to `Pull Request Justification` because the changes should be described by commits, and the PR should be higher level than that.

**Comment by zougloub** [comment]
Suggest to change the first section into a removable soft-checklist, with statements instead of questions.

**Comment by jcohenadad** [comment]
i suggest to simplify the section "State of spinalcordtoolbox", which is heavy. A simple commit number should suffice, no?

**Comment by jcohenadad** [comment]
i suggest to remove: "**Reproduces how often:** What percentage of the time does it reproduce?". Usually when things go wrong in SCT they go wrong for good ;-)
