### ISSUE TITLE
Update course manual

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1643]
- [x] Add improved QC reports
- [x] Add fsleyes UI integration
- [x] Add `sct_deepseg_sc`
- [x] Add `sct_deepseg_gm`
- [ ] Add `sct_analyze_lesion`

**Comment by perone** [comment]
I can do the fsleyes integration docs.

**Comment by jcohenadad** [comment]
@perone since we are in a rush i'll take care of the fsleyes integration slide
