### ISSUE TITLE
sct_utils create_folder and exception handling/throwing (built-in exceptions)

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1658]
I opened this issue to discuss the problem of the exception handling and throwing built-in exceptions.

So, there is an important issue and I think that we should start addressing these kinds of issues.
The `create_folder` from `sct_utils` looks more like a C-API than a Python API, it is handling an exception, silencing it and returning an error code (that is already present in the exception itself). Now what happens is that **everyone calling this function will have to handle this error code and throw an exception again later**, as we can see in the PR #1592.

However, it would be much more appropriate in my opinion, to have the `create_folder()` function to create the directory or throw an exception if it wasn't able to create it, that's what is the purpose of the exception being silenced in the `create_folder` function.

Now, every platform has their own errors and messages, the `errno` attribute in the `OSError` exception is an especial code, and according to this code, Python will throw another kind of exception (such as `PermissionError` for errno = 1 or `FileNotFoundError` for errno = 2). That is also another reason to avoid throwing built-in exceptions as I mentioned before because an `OSError` is only thrown by system errors and not incidental errors (as described in the [official docs](https://docs.python.org/2/library/exceptions.html#exceptions.OSError)).

Besides that, what can happen if we start to catch this error, return a code and then raise it again without a proper `errno` defined is that it is very difficult to handle it correctly and get the Sentry errors with meaningful information. That's why I think that we shouldn't use built-in system exceptions that aren't meant for incidental errors and instead use the traditional `RuntimeError` or another custom exception that inherits from the `Exception` class when we want to propagate structured data together with the exception.

**Comment by Drulex** [comment]
Noticed this pattern in a couple of utility functions during the refactor (#2949). None of the callers checks the return codes so I removed the C style error handling and refactored the callers to handle the exceptions.
