### ISSUE TITLE
brightness/contrast features for sct_label_utils -create-viewer

### ISSUE THREAD

**Issue by fperdigon** [neuropoly/spinalcordtoolbox#1660]
There are some very dark images in which it is very difficult/imposible to label.
Proposal:
- Include a slice control bar to adjust the brightness
- Include a slice bar control to adjust the contrast
- Include a check box, when active performs an automatic histogram adjustment, for example adaptive equalization, see exposure.equalize_adapthist () function in scikit-image, link below
http://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_equalize.html

**Comment by peristeri** [comment]
The improvements using CLAHE are small. With the help of @fperdigon we concluded that for most cases the adjustments will be enough but edge cases will still exists such as `sct_testing/large/twh_allan_e26407/t2/t2.nii.gz`

**Comment by jcohenadad** [comment]
for edge cases, maybe the best would be to have contrast/brightness adjustment using right click top/bottom (brightness) and right/left (contrast).
@benjamindeleener has implemented this already and can point you to the code

**Comment by benjamindeleener** [comment]
Here is the code for adjusting the contrast on the image with the right click: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_viewer.py#L354
