### ISSUE TITLE
equalize_adapthist leaves artefacts when image size is not a multiple of tile size

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1664]
#Reported [here](https://github.com/scikit-image/scikit-image/issues/2219), [here](https://github.com/neuropoly/spinalcordtoolbox/pull/1661#issuecomment-377128058) and [here](https://github.com/neuropoly/spinalcordtoolbox/pull/1647#issuecomment-377090220).

A possible workaround is to pad the image to a multiple of the kernel size, apply CLAHE, and then output the image after unpadding. By default, 1/8 of NX and NY is used, which means that the padding should result in NX and NY being a multiple of 8.

**Comment by zougloub** [comment]
Only user of the code has a fix for the issue, closing.
