### ISSUE TITLE
Update SCT virtual machine

### ISSUE THREAD

**Issue by fperdigon** [neuropoly/spinalcordtoolbox#1665]
Update SCT virtual machine to next release

**Comment by zougloub** [comment]
@fperdigon if you can write down somewhere (eg. here) the VM installation procedure, and point to the online location of the VM files, I can add that to the [Sphinx docs](https://github.com/neuropoly/spinalcordtoolbox/pull/1683), thanks!

**Comment by zougloub** [comment]
VM was obsoleted in favor of [docker](https://github.com/neuropoly/sct_docker) -> closing
