### ISSUE TITLE
Organize functions under spinalcordtoolbox/ folder

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1674]
to address [this comment](https://github.com/neuropoly/spinalcordtoolbox/pull/1672#discussion_r180408021):

>  zougloub on Apr 10 Member
> Could mtsat be in a folder that may contain other "similar" tools?
> `from x.something import something` to import a module is not the prettiest.
>
> jcohenadad on Apr 10 Member
> Agreed, however I believe this requires group discussion. Opened an issue here

**Comment by joshuacwnewton** [comment]
`compute_mtsat` now lives in `spinalcordtoolbox.qmri.mt`. So, I believe the core concern here has been addressed.
