### ISSUE TITLE
Installation error not caught by Travis

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1679]
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/364742340#L1422

need to check if the recent updates on `install_sct` fix it

**Comment by jcohenadad** [comment]
nope! recent updates did not fix it:
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/365429679#L1499

**Comment by zougloub** [comment]
Issues identified:
- `sct_check_dependencies` failing which nevertheless causes "Installation successful"
- an `msct_parser` warning
- `Check if pytest-cov (2.5.1) is installed............[FAIL]` (on your second link)
