### ISSUE TITLE
Running SCT on Windows is not working

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1682]
This is just a placeholder issue to state the fact, until it's not true anymore.

**Comment by joshuacwnewton** [comment]
SCT now recommends WSL for Windows 10 installations, which is currently working (see: [Windows Sever 1809 CI builds](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/735502379)). I believe any further Windows-focused development can be handled by newer issues, e.g. #2747. Closing.
