### ISSUE TITLE
Improve filtering of subjects

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1699]
### Description

Currently the filtering is done using flags -subj and -file-subj. The usage is not well documented, and also this features requires an XLS file, which is not convenient.

One suggestion is to add a flag that enables filtering using string parsing, e.g., `-subj-str nih` for selecting all folders that include the string `nih`.

Another suggestion is to add json parsing capabilities, to have an alternative to the xls format.

**Comment by jcohenadad** [comment]
related to https://github.com/neuropoly/spinalcordtoolbox/issues/1763

**Comment by joshuacwnewton** [comment]
`sct_pipeline` has been replaced by `sct_run_batch`. The new script has `-include-list`/`-exclude-list`, as well as `-include`/`-exclude` which support regex. So, I believe the core idea of this issue has been addressed.
