### ISSUE TITLE
Testing branches

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1702]
I have a git installation of SCT. I wanted to test a branch, did a checkout, fetch, rebase, and then i ran:
~~~
SCT_INSTALL_TYPE=in-place add_to_path=no change_default_path=yes ./install_sct -d -b -m
~~~

as per the instruction here: https://github.com/neuropoly/spinalcordtoolbox/wiki/development-hints#testing-environments

however, the spinalcordtoolbox/gui was not updated.

i had to do the following to update it:
~~~
pip install -e .
~~~

what is the correct procedure for testing a branch so that we can be sure 100% of the time that we are testing the right thing?  Once clarified we can update this link:
https://github.com/neuropoly/spinalcordtoolbox/wiki/development-hints#testing-environments

**Comment by zougloub** [comment]
The installer always performs that `pip install` of SCT (with Conda's pip).
How are you launching the GUI? Any chance the pip you are using isn't the one from the Conda environment?

**Comment by jcohenadad** [comment]
> The installer always performs that pip install of SCT (with Conda's pip).
yes, i'm also puzzled. The GUI was launched from the terminal (in that case i think it was `sct_label_utils -i XX -create-viewer`). I am pretty sure i was using SCT Conda's pip (after doing a `source python/bin/activate` within `$SCT_DIR`). Next time it happens to me i will document better (i.e. with exact commit, etc.).

**Comment by jcohenadad** [comment]
Another fail in updating modules after running ./install_sct, resulting in wasted time: https://github.com/neuropoly/spinalcordtoolbox/pull/1746#issuecomment-390824936

**Comment by jcohenadad** [comment]
OK, I figured out the culprit:
- when i do `pip install .` (default mode in `./install_sct`) --> it does NOT work, meaning, I cannot access the modified functions under `spinalcordtoolbox` modules
- when i do `pip install -e .` (dev mode in `./install_sct`) --> it does work.

looking at the pip help, it says that -e "Installs a project in editable mode (i.e. setuptools "develop mode")", but i don't get it. If someone can explain to me why a fresh SCT install (including conda install) makes `pip install .` works, while running `pip install .` without reinstalling conda is problematic.

**Comment by zougloub** [comment]
What ``-e`` does is (mostly) writing to an `easy-install.pth` file (import path addition) the location of the spinalcordtoolbox parent folder.
After copying the files from the unpack folder to the install destination folder, `-e` could be used, right now without the option pip is used as a "copy" command.
I think it's a good idea to do ``-e`` in the installer, will propose a PR.

**Comment by perone** [comment]
I think it would be better to have a flag to install in "development mode" or something similar, and then in this mode it will enable the `-e` flag in `pip` which is very common for development.

**Comment by zougloub** [comment]
You mean as already exists right now? :D

**Comment by perone** [comment]
But the "development mode" we have today doesn't enable the `-e` flag, right ? or it does ?

**Comment by zougloub** [comment]
It does. But ``-e`` could also be used in a normal install, to be able to modify files in the install folder, the current dev mode is used to refer to files in the source folder.
