### ISSUE TITLE
List of unsupported old Linux distros

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1704]
The following "old" Linux distributions are known to have issues running SCT:

- Centos 6

---

The following distributions aren't having issues with SCT per se, but other components used jointly:

- Debian 7 (the NiFTI viewer fsleyes is quite hard to install there)

---

Issues:
- `isct_antsSliceRegularizedRegistration` execution failure  
```
sct_utils.RunError: isct_antsSliceRegularizedRegistration: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by isct_antsSliceRegularizedRegistration)
```  
This happens on Centos 6 and is similar to #564 ; could be fixed by statically linking to libstdc++.

**Comment by jcohenadad** [comment]
should we close this?

**Comment by zougloub** [comment]
Since it's part of limitations, I was thinking of keeping it open and updating as we go (eg. adding more if we upgrade TF, etc.).

**Comment by joshuacwnewton** [comment]
We now have a [Requirements section](https://spinalcordtoolbox.com/en/latest/user_section/installation.html#requirements) in our documentation, which more or less covers this issue. (e.g. we list `RedHat/CentOS >= 7` which covers CentOS 6, and we can do the same for other distros). So, I'm closing this. :)
