### ISSUE TITLE
Sentry "false positives"

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1707]
As we are integrating issue reporting, there may be issues reported by Sentry, that don't really need to be.

Examples:

- [x] `ValueError: File ${file}.nii.gz does not exist. Exiting`
- [x] `WARNING: NURBS instability -> wrong reconstruction`

**Comment by zougloub** [comment]
- `ValueError: File ${file}.nii.gz does not exist. Exiting` to be fixed by parser update in PR #1720

**Comment by joshuacwnewton** [comment]
Closing, as the two examples given were addressed already. Any other false positives can be handled on a case-by-case basis, rather than keeping a perpetually open issue.
