### ISSUE TITLE
Sentry: display message to indicate how to opt out from Sentry 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1708]
### Description

It is likely that some users who have initially opted in for sentry (crash report) will be annoyed. They need to be able to opt out at anytime, hence this should be documented. One suggestion is to display a message like:
~~~
If you don't want to send crash report anymore, edit the file ${SCT_DIR}/bin/sct_launcher and delete the line that starts with "export SENTRY_DSN"
~~~

Ideally, this message should be displayed everytime an error is sent. I don't know if there is a method in `raven` that enables to add custom message upon connection.

**Comment by zougloub** [comment]
Fixed by #1753
