### ISSUE TITLE
make video tutorial on how to use shape analysis 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1715]
### Prerequisites

* [ ] Did you check past issues for similar issue(s) ?
* [ ] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [ ] If you are using a development environment, is your environment updated ?

### Description

Description of the issue and use the labels to add additional context.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

What you expect to happen

**Actual behavior:**

What actually happens

**Reproduces how often:**

What percentage of the time does it reproduce?

### State of spinalcordtoolbox

Include the first 3 lines printed when running the command.
Example:

```
$ sct_qc

--
Spinal Cord Toolbox (github-templates/a63f51caa065655ad1b926901adf7ef144d2cc2b)
Running /Users/geper/devel/spinalcordtoolbox/scripts/sct_qc.py

...
```

### Additional Information

Screen-shots, error logs and output files.

**Comment by joshuacwnewton** [comment]
Closing. See https://github.com/neuropoly/spinalcordtoolbox/issues/592#issuecomment-708090189 for rationale.
