### ISSUE TITLE
restrict the writing permission in the Forum News.

### ISSUE THREAD

**Issue by fperdigon** [neuropoly/spinalcordtoolbox#1717]
Restrict the writing permission of Forum News in the Sourceforge page to the developer team.

**Comment by fperdigon** [comment]
@jcohenadad ,  SourceForge only allows you to define permissions for a Discussion tab.
The solution for this would be to create a new tab called News where only the developer team has write permission. The current Discussion tab can be renamed to Help with will have writing permission for users to post their doubts.
Here is a link to the help of SourceForge regarding this
https://sourceforge.net/p/forge/documentation/Discussion/

**Comment by jcohenadad** [comment]
@fperdigon if we create a new tab "news", is there a possibility to move the current content of the Forum/Help to the new tab Help? 

If so, could you please do it?

thx

**Comment by jcohenadad** [comment]
@fperdigon: I suggest we simply remove the "News" tab. 

Pros:
* Removes one tab, hence clearer from UX standpoint
* No risk of people posting help request on News forum
* Less maintenance of SF

Cons:
* No more news, however I don't think it has been very useful so far. When we have new releases I advertise via existing mailing list (sct-mailing, neuroimaging-python, nitrc, etc.) so most people are aware.

@neuropoly/spinal-cord-toolbox Please vote with thumbs up/down

**Comment by fperdigon** [comment]
just to be sure:  :+1: is to eliminate?

**Comment by jcohenadad** [comment]
@fperdigon i see the "news" tab is still there-- could you please remove it, and once remove, close this issue-- thanks

**Comment by fperdigon** [comment]
@jcohenadad, Done
