### ISSUE TITLE
Implement all coverage

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1731]
Maybe explore this solution: https://coveralls.io/

**Comment by abtahizadeh** [comment]
Yes, this is basically what I was suggesting.
For the test framework, I am flexible with whatever your developers feel convenient.
Not much a difference, only auto-discovery can save us time.

**Comment by jcohenadad** [comment]
comment from @perone:
> pytest you can configure where it will look for the tests and it will perform a recursive search. On the other hand, my opinion is that it is always better to centralize the tests in the same place.
Please also note that nose is in maintenance mode with the risk of being stopped and nose2 is just prioritizing bug fixes due to the community interest in pytest.

**Comment by abtahizadeh** [comment]
Thanks @perone ,
I was actually talking about Nose2, we use it in production in our company. 
However, I totally agree with choosing the right eco-system, let's keep on working with PyTest, I'm also familiar with that.

**Comment by abtahizadeh** [comment]
@jcohenadad In folder "unit_testing" I see only two small python modules, is it the beginning of writing Unit Tests and using a framework or is there another branch containing all Unit Tests that I must look into?

**Comment by jcohenadad** [comment]
@abtahizadeh there is no other branch that i'm aware of. So yes, `unit_testing/` includes initial attempts

**Comment by abtahizadeh** [comment]
- Coveralls integrated,
- We will use Pytest.
