### ISSUE TITLE
Is sct_make_ground_truth still useful?

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1732]
@neuropoly/spinal-cord-toolbox is anyone still using [this function](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_make_ground_truth.py)? If not I suggest we remove (duplication with `sct_label_utils -create-viewer`).

**Comment by fperdigon** [comment]
I am using only `sct_label_utils -create-viewer`, I agree with the deletion

**Comment by jcohenadad** [comment]
ok let's do it then
