### ISSUE TITLE
sct_process_segmentation -discfile -p label-vert

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1734]
2 detected issues with the function:
`sct_process_segmentation -discfile -p label-vert`

1. Assume images with RPI orientation:
```
cd /Volumes/temp/charley/i_1734
sct_process_segmentation -i t2_sag_cerv_seg_AIL.nii.gz -discfile label_discs_AIL.nii.gz -p label-vert
```

2. Use the convention "disc labelvalue=3 ==> disc C3/C4" instead of "disc labelvalue=3 ==> disc C2/C3"
```
cd /Volumes/temp/charley/i_1734
sct_process_segmentation -i t2_sag_cerv_seg_RPI.nii.gz -discfile label_discs_RPI.nii.gz -p label-vert
```
Or I am missing something? :/

**Comment by charleygros** [comment]
```
sct_process_segmentation was using a wrong definition of disc, i.e. 3 --> C3/C4 (old definition --> wrong) instead of 3 --> C2/C3 (new definition --> good).
```
Yes correct --> That s the goal of this PR: correct `sct_process_segmentation` in this respect.
And that s why I have not modified the label values in `sct_label_vertebrae`.

```
Now, i see that the PR deals with sct_label_vertebrae, while it should not. sct_label_vertebrae outputs a segmented labeled for vertebral levels (not discs). I don't see anything wrong with the implementation of sct_label_vertebrae
```
I will remove my comments "TODO ... " --> I am realizing they are false. My bad.

To summarize:
- definition of disc corrected in `sct_process_segmentation`
- add an im.change_orientation('RPI') in label_segmentation (cf first post)

**Comment by jcohenadad** [comment]
👍 OK I get it now, so I [modified the title of the PR](https://github.com/neuropoly/spinalcordtoolbox/pull/1735#event-1628497368) because `sct_label_vertebrae` has no impact in the old/new ldisc definition debate (it outputs vertebral, not disc levels).
