### ISSUE TITLE
improve robustness of sct_dmri_moco and other minor fixes

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#174]
fslview -m ortho,ortho /home/django/tanguy/data/Boston/2014-07/Connectome/HC_SC_005/GrappaNoGrappa/GrappaNoGrappa.nii /home/django/tanguy/data/Boston/2014-07/Connectome/HC_SC_005/GrappaNoGrappa/GrappaNoGrappa_moco.nii

sct_dmri_moco -i GrappaNoGrappa.nii -b bvecs.txt

**Comment by jcohenadad** [comment]
several improvements to do:
- [ ] change default params for "-param 2,0,0.5,MI"
- [ ] make sure output dmri has same nifti scaling as input (slope param in nifti header)

**Comment by tanguyduval** [comment]
Also sct_dmri_moco crash if only 1 slice : 4th dimension is interpreted as the 3rd dimension.

**Comment by jcohenadad** [comment]
Closing because old and not active.
