### ISSUE TITLE
Temporary folder is removed even with -r 0

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1742]
### Description

This is caused by [this line](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg_sc.py#L227)

Fix is to replace:
```python
remove_temp_files = arguments['-r']
```
by
````python
remove_temp_files = int(arguments['-r'])
````

**Comment by zougloub** [comment]
Fixed by #1753
