### ISSUE TITLE
Failing build messages on TravisCI

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1756]
Just saw these messages on TravisCI for the master:

![image](https://user-images.githubusercontent.com/412328/40271922-8034b754-5b72-11e8-88f3-a58cf2740f4d.png)

**Comment by zougloub** [comment]
Hi, that's expected. The VTK install is broken on Ubuntu. We're already testing more than before, where the code wasn't compiled.

**Comment by perone** [comment]
I'm reopening this because I saw this error again on Travis. I don't see a reason to keep building propseg on Travis if it always fail, it is just adding more time to the already long building process. A checking can be added to avoid it.

**Comment by jcohenadad** [comment]
@zougloub is there a reason we want to keep the propseg build on Travis? given that we are shipping the binaries of propseg (which could be different from those that are built within travis), i am wondering if we should maybe move this build test somewhere else because it adds up some travis time.

**Comment by zougloub** [comment]
I agree with you and @perone on this.
I'll remove the build.
FYI I'm also thinking of removing the python3 jobs for now, maybe replacing them by linting (restricted to checking py3k incompatibility), TBD after testing.

**Comment by joshuacwnewton** [comment]
Closing, as we no longer build sct_propseg in Travis thanks to #1970.
