### ISSUE TITLE
"open file" does not work on OSX

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1772]
### Description

At the end of a processing, the following command display is issued for users to open a browser and glance at QC results:
~~~
open file "/Users/julien/qc_batch_processing/index.html"
~~~

However, this command fails on OSX and needs to be replaced with:
~~~
open "/Users/julien/qc_batch_processing/index.html"
~~~

### State of spinalcordtoolbox

Spinal Cord Toolbox (jca_batchProc/dea98c961553315202c90086fddedf923e99a768)

**Comment by zougloub** [comment]
On Linux, `xdg-open`.

**Comment by abtahizadeh** [comment]
@jcohenadad I see the command is already "open", is there somewhere else I should've looked? is the condition to check the OS wrong? (seems fine to me)

`if uname -a | grep -i  darwin > /dev/null 2>&1; then
  # OSX
  open_command="open"
elif uname -a | grep -i  linux > /dev/null 2>&1; then
  # Linux
  open_command="xdg-open"
fi`

**Comment by jcohenadad** [comment]
@abtahizadeh the displayed command is "open file": https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/reports/qc.py#L416
