### ISSUE TITLE
Change output name XXX_centerline_optic --> XXX_centerline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1777]
### Description

The current convention for output file name is only the "what", not the "how".

Regarding `sct_propseg`, i suggest we remove the default output centerlines.

**Comment by jcohenadad** [comment]
@charleygros agreed, i've updated the proposed change [here](https://github.com/neuropoly/spinalcordtoolbox/issues/1777#issue-325592803)

**Comment by abtahizadeh** [comment]
Please clarify, what sort of action is requested on this?
the change XXX_centerline_optic --> XXX_centerline would result in not having distinct files?

```
file_ctr = os.path.join(param_test.path_output, sct.add_suffix(param_test.file_input, '_centerline_optic'))
```

**Comment by jcohenadad** [comment]
@abtahizadeh 
- in sct_propseg: the idea is to not output "XX_i_centerline" from sct_propseg anymore (i.e. the one generated from the segmentation), but only output the centerline from OptiC, which we would then call  XX_i_centerline (previously called XX_i_centerline_optic)
- in sct_get_centerline: change output name XX_i_centerline_optic --> XX_i_centerline

**Comment by jcohenadad** [comment]
@charleygros @benjamindeleener: after giving it more thoughts, i'm not sure this is a good idea to remove the "_optic" suffix and output the centerlines without it. The problem is that some people use the output centerline for subsequent tasks (e.g. straightening, smoothing, etc.) where they should be using the segmentation instead (more accurate). So, i suggest we simply don't output any centerlines anymore after `sct_propeg` or `sct_deepseg_sc`. If people want them (for debugging purpose), we can add a flag for it. Pls let me know your thoughts.

**Comment by charleygros** [comment]
@jcohenadad : My argument for outputting the centerline after the segmentation tools were to easily see if a segmentation fail is due to the centerline detection or the segmentation module itself. And subsequently, facilitate the found of a way to fix it --> if we observe that the detection fails, we can opt for another `-ctr` algo (e.g. `cnn` or `svm` or `viewer`).
A flag dedicated to this could be a solution

**Comment by jcohenadad** [comment]
if we go that route, we also need to find a convention for flags, regarding centerline "method" and centerline "output". In `sct_deepseg_sc`, the plan was to replace `ctr` with `centerline`, but then we need to find a good flag for naming the output centerline. Alternatively, we don't create a specific flag for it, and instead we set `-r 0`(don't remove temp files). After all, this flag was created for the purpose of debugging.

**Comment by charleygros** [comment]
Just wanted to summarize what we said above to check if we still agree on it, before to (finally) implement it:
-- `sct_propseg`, `sct_deepseg_sc` and `sct_deepseg_lesion`: do not output a centerline file. If the user need it, she/he could use the flag `-r 0`.
-- `sct_get_centerline`: output a centerline image with the filename convention: `*_centerline.nii.gz`. Currently: `-method viewer` --> `*_viewer_centerline.nii.gz` and `-method optic` --> `*_centerline_optic.nii.gz`

Is it correct?

**Comment by jcohenadad** [comment]
The new proposed implementation is that sct_get_centerline would have flag "-o" for file prefix (no more "-ofolder"), and would output, for example with `-o centerline`:
- centerline.nii.gz --> discrete centerline per slice
- centerline.csv --> continuous centerline per slice
