### ISSUE TITLE
Enhancement sct_crop_image documentation

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1818]
### Description

Just wanted to open a discussion about `sct_crop_image`
The documentation of `sct_crop_image` is a bit confusing to me.

```-start <list of: float>      start slices, ]0,1[: percentage, 0 & >1: slice number```
--> this flag indicates the slice number to remove or to keep? same for `-end`.
What about:
```-start <list of: float>      start slices kept in the output file, ]0,1[: percentage, 0 & >1: slice number```

Would it be relevant to do not specify the `-end` flag if the `-start` is specified?
--> If `-end` is not specified, then the output image is made of all the slices from the ones specified by `-start` to the end. --> It could simplify the use of this function (and avoid error).

**Comment by jcohenadad** [comment]
Alternatively, we could also change the behaviour of this function and have something more similar to FSL, which I find very intuitive:
~~~
fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize>
~~~

So we could make it like this:
~~~
sct_crop_image -i <input> -o <output> -xmin <> -xmax <> -ymin <> -ymax <> -ymax <> -zmin <> -zmax <>
~~~
Inputting -1 for a max will set it to the full image extent for that dimension.

**Comment by charleygros** [comment]
I would agree with this solution --> much more intuitive to me
And put `-1` as the default value of these flags.
