### ISSUE TITLE
bach_processing: remove register_graymatter

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1821]
and replace it with register_multimodal on the WM seg-- it works similarly well and less confusing for users.

at some point we should also remove this function

**Comment by joshuacwnewton** [comment]
It's funny, `sct_register_graymatter` was indeed removed as a function, yet it still exists in `batch_processing.sh`.

https://github.com/neuropoly/spinalcordtoolbox/blob/f497c2f4cf512d184e07761f712631016d3e0454/batch_processing.sh#L114-L123

If it's not too time-consuming, would you be able to help with the proper `sct_register_multimodal` usage, @jcohenadad?

**Comment by jcohenadad** [comment]
i'm on it!

**Comment by jcohenadad** [comment]
this one is a winner:
```bash
# OPTIONAL: Update template registration using information from gray matter segmentation
# # <<<
# # Register WM/GM template to WM/GM seg
# sct_register_multimodal -i $SCT_DIR/data/PAM50/template/PAM50_wm.nii.gz -d t2s_wmseg.nii.gz -dseg t2s_seg.nii.gz -param step=1,type=im,algo=syn,slicewise=1,iter=5 -initwarp warp_template2t2s.nii.gz -initwarpinv warp_t2s2template.nii.gz -qc "$SCT_BP_QC_FOLDER"
# # Rename warping fields for clarity
# mv warp_t2s_wmseg2PAM50_wm.nii.gz warp_t2s2template.nii.gz
# mv warp_PAM50_wm2t2s_wmseg.nii.gz warp_template2t2s.nii.gz
# # Warp template (this time corrected for internal structure)
# sct_warp_template -d t2s.nii.gz -w warp_template2t2s.nii.gz -ofolder label_gm_aware -qc "$SCT_BP_QC_FOLDER"
# # >>>
```
