### ISSUE TITLE
Add total processing time

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1827]
Purpose: display processing time at the end of the function, as done here:
https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_register_to_template.py#L657

**Comment by abtahizadeh** [comment]
What is the scope?

**Comment by jcohenadad** [comment]
@abtahizadeh i've edited the comment to explicit a bit more. Pls let me know what is unclear

**Comment by abtahizadeh** [comment]
@jcohenadad  To be implemented on all sct_* main functions or specifically for each method of them?

**Comment by jcohenadad** [comment]
@abtahizadeh yes, on all sct_* main, so there is probably a smart way to do it in a parent call (sct_launcher?)
