### ISSUE TITLE
sct_testing issue when parser with value_type file, in -vertfile of sct_extract_metric

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1829]
See https://github.com/neuropoly/spinalcordtoolbox/pull/1798#discussion-diff-193218429R116

**Comment by joshuacwnewton** [comment]
This specific issue is no longer relevant with argparse, as we no longer do file validation that `msct_parser` used to do.

Now, whether that's preferable is debatable. Perhaps we should be doing file validation with argparse, too. But, that's out of scope of this specific issue, so I'm closing.
