### ISSUE TITLE
Output segmentation should be overlaid with opacity=100 in display_syntax_viewer()

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1833]
### Description

At the end of the process, the `display_syntax_viewer()` currently sets the opacity to 70%, which makes the segmentation appear a bit dark (esp. on dark images). Since the best way to assess segmentation accuracy is to switch on/off the overlaid seg, we should simply make it with 100% opacity. They will appear clearer at the first place.

**Comment by benjamindeleener** [comment]
When I assess the quality of a spinal cord segmentation, I usually set the opacity to 40%. It is easier than switching on/off.

**Comment by charleygros** [comment]
@jcohenadad : I totally agree that 70% is too high.
I used to set my threshold at 20%. And.. I think I would prefer 20% compared to 0% (of transparency, ie 100% opacity). Indeed, 20% allows to clearly see the borders of the target structure (at least for the SC, not sure if that s also the case for GM) without having to switch on/off the overlaid seg.
Also, let's say I run `sct_deepseg_sc`, the terminal kindly asks me to visualize the results of the segmentation, fslview window pops but... no segmentation appears at first glance --> I am wondering if this could be disturbing.

**Comment by jcohenadad** [comment]
@charleygros i meant 100% opacity, as defined by fsleyes --> the segmentation appears very clear (it is 100% opaque).

@benjamindeleener i see your point. Have you tried the "CMD+F" on the new fsleyes? it changed my life (you can even call it while z-scrolling). That's where i felt that the transparency was not required anymore.

**Comment by perone** [comment]
The problem with opacity is that you won't see if there is a false negative or a false positive far away from your region of interest.

**Comment by jcohenadad** [comment]
all, i think there is some misunderstanding as to what we call opacity (otherwise @perone's comment doesn't make sense, because a false positive far away from the ROI is only seen with high opacity, not low opacity). What i call 100% opacity is when the object is completely opaque. Below example so we are all on the same page:

<img width="509" alt="screen shot 2018-06-08 at 05 45 05" src="https://user-images.githubusercontent.com/2482071/41125402-546869f0-6adf-11e8-9060-bfa8fc610fb6.png">

so, from this example i understand @benjamindeleener's comment about the need to lower the opacity, because the 70% (current default) is too opaque. My approach was to set 100% by default (because it is clearer) and have the user switch on/off the overlay.

now the debate can continue :-)

**Comment by perone** [comment]
Sorry my comment was misleading I agree with the **opacity=100%**, it will make it easier to see if there are false positives or false negatives in the predictions.
