### ISSUE TITLE
sct_get_centerline -method viewer: should use the new viewer

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1837]
It would be nice to use the new viewer for `sct_get_centerline` script. The new viewer is for example used by `sct_propseg` when calling e.g.: `sct_propseg -i IMAGE -c CONTRAST -init-centeline viewer` (the viewer is called here: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_propseg.py#L540)

**Comment by charleygros** [comment]
I think we can close this issue, is it correct?
