### ISSUE TITLE
Coveralls not capturing changes correctly

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1849]
Even though I added more lines and more testing coverage in the PR #1846 (already merged), it seems that coveralls isn't capturing these changes correctly as seen by [this report here](https://coveralls.io/builds/17421313).

It seems that it is always showing the same output:

![image](https://user-images.githubusercontent.com/412328/41242380-559b77aa-6d6d-11e8-85e9-9963bdf8d7a3.png)

Even though the `metadata.py` file wasn't touched in the merged PR.

**Comment by jcohenadad** [comment]
also, can someone clarify to me what this "85%" means?  since we currently have almost no unit testing, how can this number be so high?

**Comment by perone** [comment]
I think coveralls right now is just getting coverage information for the `metadata.py` unit-testing, hence the high number.

**Comment by abtahizadeh** [comment]
It shows 100% for some files, just because there is no test maintained in them.
Check the status report:

`python -m pytest --cov`

The numbers (total percentage) starts to make sense only when all the modules are actually tested (have a unit test). So I think it's ok for now....

**Comment by abtahizadeh** [comment]
@perone #1852 should fix this.

**Comment by abtahizadeh** [comment]
Fixed via #1852 ?
