### ISSUE TITLE
SCT logo isn't being copied to the installation folder

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1868]
FSLEyes plugin requires a SCT logo image (`/documentation/imgs/logo_sct.png`) that is not being copied to the installation folder. This problem occurs only when the user installs the SCT on a different folder than the one he unzipped the installation package.

For more information, see [user report](https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/e1c8a8f6).

**Comment by abtahizadeh** [comment]
Variable related to this: `SCT_LOGO_REL_PATH`

**Comment by abtahizadeh** [comment]
One trick could be to set this directory dynamically and try to locate the logo file:
```
logo_file = os.path.join(os.environ[self.SCT_DIR_ENV],
                                 self.SCT_LOGO_REL_PATH)
```

**Comment by abtahizadeh** [comment]
@jcohenadad yeah, we need to somehow copy the file during the installation to `SCT_DIR_ENV/logo_sct.png` maybe (no need to make directories) ....

**Comment by jcohenadad** [comment]
why not simply copying at the same location as in the github repos? (documentation/imgs/logo_sct.png) so that we don't need to add another variable
