### ISSUE TITLE
add checks

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#187]
- check if 2nd step is chosen with sliceReg --> currently fails
- check if 2 images are same dimension if use sliceReg

**Comment by benjamindeleener** [comment]
try to simplify sct_register_multimodal by:
- only keeping one step
- changing the pipeline by running register_multimodal sequentiallty, e.g.,:
  - seg_src --> seg_dest
  - apply_warp on im_src
  - im_src_reg --> im_dest
