### ISSUE TITLE
Error in msct_image if input NIFTI header has corrupted qform

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1896]
### Description

Sentry info [here](https://sentry.io/share/issue/a6bc4fb659f246e38b0f57d6576efc4b/).

Suggestion for fix: check header (could be done in a new spinalcordtoolbox module) before doing processing.

**Comment by zougloub** [comment]
Can't access that Sentry link anymore :/.
Is there some way to reproduce the problem?

**Comment by jcohenadad** [comment]
Sorry the Sentry link is indeed broken-- might be due to a change in the Sentry organization (to deal with our other project qMRLab). 

If i remember correctly, an error was raised because in that case the input data were 2d.

The data provided in https://github.com/neuropoly/spinalcordtoolbox/issues/2106 would be a good starting point.

**Comment by jcohenadad** [comment]
closing because not enough information to reproduce
