### ISSUE TITLE
false negative on Travis

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1899]
`sct_testing` failed to run (due to problems in `sct_launcher`), yet Travis gave a green check. This happened both on [Linux](https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/398746942) and [OSX](https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/398746943)

**Comment by zougloub** [comment]
Fixed by #1902.
The issue was that I had messed up when capturing and rethrowing the wrapped command error code in SCT launcher, not realizing that the script could be sourced.
