### ISSUE TITLE
Propseg: WARNING: In /usr/local/ITK-static/include/ITK-4.5/itkGaussianOperator.hxx

### ISSUE THREAD

**Issue by neuropoly** [neuropoly/spinalcordtoolbox#19]
when running propseg on the MNI-Poly-AMU t2 template:

command ran:
    sct_segmentation_propagation -i MNI-Poly-AMU_T2.nii.gz -t t2 -mesh

'''''
WARNING: In /usr/local/ITK-static/include/ITK-4.5/itkGaussianOperator.hxx, line 61
itkGaussianOperator (0x7fff5b50f0f8): Kernel size has exceeded the specified maximum width of 32 and has been truncated to 33 elements.  You can raise the maximum width using the SetMaximumKernelWidth method.
'''''

**Comment by benjamindeleener** [comment]
This error will be fixed when using new version of spinal cord detection for PropSeg
