### ISSUE TITLE
Refactor the code to make it API friendly according to the new scheme

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1922]
There is no python API on the `spinalcordtoolbox` module for the `sct_deepseg_sc` and for the `sct_deepseg_lesion`. Most part of the code is inside the script itself, we should consider refactoring it according to the new refactoring plans (as in `sct_resample`, etc):

![resample](https://user-images.githubusercontent.com/412328/42654017-33ef1888-85e5-11e8-909a-4eea855238bd.png)

The main point is: the script itself (inside the `script`) folder should just consume the Python API from the module.

**Comment by joshuacwnewton** [comment]
We now have `spinalcordtoolbox/deepseg_lesion/` and `spinalcordtoolbox/deepseg_sc/`, which was started by #2147 and has received many updates since. I believe this is largely handled. New refactoring issues are also being created by @Drulex, so I don't think this issue is useful anymore.
