### ISSUE TITLE
add output from analyze_lesion and shape_analysis in batch_processing 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1929]
### Description

For the purpose of testing PRs and pre-release on functions that are not well covered by integrity testing, it would be nice to add a few functions in the `batch_processing` and append results at the end.

Notably:
- `sct_analyze_lesion`
- `sct_process_segmentation -p shape` (already run but not appended to final results)

**Comment by joshuacwnewton** [comment]
Closing as I've grouped all of the ideas into one issue here: https://github.com/neuropoly/spinalcordtoolbox/issues/3250
