### ISSUE TITLE
remove sct_compute_tsnr.sh

### ISSUE THREAD

**Issue by augustinr** [neuropoly/spinalcordtoolbox#193]

**Comment by SaraDupont** [comment]
Pushed a new python script to master : sct_fmri_compute_tsnr.py (didn't remove the shell script yet), if that script works correctly, this issue can be closed.

**Comment by jcohenadad** [comment]
I tried running the script and get:
~~~~
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_fmri_compute_tsnr", line 123, in <module>
    arguments = parser.parse(sys.argv[1:])
NameError: name 'sys' is not defined
~~~~

**Comment by jcohenadad** [comment]
also, could you please add a "test_sct_fmri_compute_tsnr" in /test?

thanks!
