### ISSUE TITLE
Duplication: sct_get_centerline.viewer and sct_process_segmentation.extract_centerline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1934]
### Description

I suggest to remove the duplication in `sct_process_segmentation` and refer to the implementation in sct_get_centerline.viewer. However, we need to take care of a few things:
-  sct_process_segmentation.extract_centerline has more features, notably the `use_phys_coord` option.

**Comment by charleygros** [comment]
@jcohenadad : Is this issue still open? I am thinking that it was fixed by: [PR 2035](https://github.com/neuropoly/spinalcordtoolbox/pull/2035)

**Comment by jcohenadad** [comment]
@charleygros you're right-- `sct_get_centerline` is now using `sct_process_segmentation.extract_centerline`.
