### ISSUE TITLE
process_segmentation.extract_centerline: should not apply smoothing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1936]
### Description

The explicit purpose of this function if to extract the centerline from an input segmentation. Currently, the function smooth the centerline before outputting the coordinates, which can be misleading. I would suggest to simply stick to what the function is supposed to do, i.e., output the center of mass of an input segmentation for each slice that is non-null. 

For more fancy calculation of centerline (smoothing, based on sparse points), people can use `sct_get_centerline`, which will then require the following refactoring. Currently, two methods are available: "optic" and "viewer". I suggest we replace "viewer" with "interp" (for interpolation) and the user will have the option of using either the viewer to select points, or to input a file with already-existing labels (the current use-case of `process_segmentation.extract_centerline`).

@benjamindeleener what do you think?

**Comment by charleygros** [comment]
(Between "viewer" and "interp" --> I think that 'viewer' is more self-explanatory than 'interp'. What about having 3 methods available: "viewer", "optic", "interp" (when the user input a file with labels) ?)

**Comment by jcohenadad** [comment]
@charleygros i agree with you-- it was an old comment. For now i suggest we stick with "optic" and "viewer". No need for "interp".
