### ISSUE TITLE
Figuring out orientation so `set_orientation()` can be deprecated in favor of an updated `change_orientation()`.

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1944]
Context: trying to get rid of `isct_*` binaries.

Throughout the SCT code we're changing image orientations, in 2 different ways:

- change_orientation() which alters im.data but doesn't touch the NIFTI header
- set_orientation() which says it only alters the NIFTI header (but somehow when I ran it and performed a diff, I saw that the extent of modification wasn't just on the header...)

I understand that the idea of the first one is to quickly change the data orientation without going through nibabel's physical to pixel transforms, so that can be done:
- iterating through image slices
- operating in a frame where an algorithm was designed to work in
It's not updating an image header, so if we were to save a resulting file, consistency between the voxel indices and the corresponding physical positions is lost.

The second one is calling an external binary which we'd want to get rid of.

I would like to update change_orientation() so that it also updates the header, so we can get rid of the second thing (+ fix #605, #842), and the files could be saved without fear.

First, as the code is only considering the [`sform`](http://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Pair.get_qform) transform, I'm thinking of updating the affine and doing `hdr.set_sform()`.
Am I missing something?

Secondly, is it safe to only consider the `sform` ? I don't have much real-life usage history of NIFTI .
nibabel uses [an algorithm](http://nipy.org/nibabel/nifti_images.html#choosing-image-affine) to figure out the affine depending on the available header fields.

**Comment by zougloub** [comment]
Correction: `get_orientation()` is using `hdr.get_best_affine()`. Other functions use `hdr.get_sform()`.

**Comment by zougloub** [comment]
Follow-up observation: I realize that nibabel's orientation labeling is opposite of that of SCT, ie. SCT's "RPI" is nibabel's "LAS" (SCT uses the origin for the label, whereas nibabel uses the positive direction / destination):
```
>>> affine = img.hdr.get_best_affine()
>>> code = nibabel.orientations.aff2axcodes(affine)
>>> print("SCT: %s nib: %s" % (img.orientation, code))
SCT: RPI nib: ('L', 'A', 'S')
```
I am not confused but this is raising questions.

**Comment by jcohenadad** [comment]
regarding the [comment about nibabel/SCT orientation](https://github.com/neuropoly/spinalcordtoolbox/issues/1944#issuecomment-405808889), i confirm the two don't follow the same convention, and I agree we should align with nibabel's convention. 
Maybe @benjamindeleener has some comments?

**Comment by jcohenadad** [comment]
for additional inspiration on how FSL is dealing with orientation stuff:
~~~
fslorient
Usage: fslorient <main option> <filename>

  where the main option is one of:
    -getorient             (prints FSL left-right orientation)
    -getsform              (prints the 16 elements of the sform matrix)
    -getqform              (prints the 16 elements of the qform matrix)
    -setsform <m11 m12 ... m44>  (sets the 16 elements of the sform matrix)
    -setqform <m11 m12 ... m44>  (sets the 16 elements of the qform matrix)
    -getsformcode          (prints the sform integer code)
    -getqformcode          (prints the qform integer code)
    -setsformcode <code>   (sets sform integer code)
    -setqformcode <code>   (sets qform integer code)
    -copysform2qform       (sets the qform equal to the sform - code and matrix)
    -copyqform2sform       (sets the sform equal to the qform - code and matrix)
    -deleteorient          (removes orient info from header)
    -forceradiological     (makes FSL radiological header)
    -forceneurological     (makes FSL neurological header - not Analyze)
    -swaporient            (swaps FSL radiological and FSL neurological)

       Note: the stored data order is never changed here - only the header info.
       To change the data storage use fslswapdim.

  e.g.  fslorient -forceradiological myimage
        fslorient -copysform2qform myimage
        fslorient -setsform -2 0 0 90 0 2 0 -126 0 0 2 -72 0 0 0 1 myimage
~~~

**Comment by jcohenadad** [comment]
> First, as the code is only considering the sform transform, I'm thinking of updating the affine and doing hdr.set_sform(). 

I cannot confidently say "ok". I think that in instances where the qform or Analyze-based format is used, this might become problematic. This is something that should be tested.

> Secondly, is it safe to only consider the sform ? I don't have much real-life usage history of NIFTI .
nibabel uses an algorithm to figure out the affine depending on the available header fields.

This is linked to my previous response. I think we should take this opportunity to switch to nibabel for dealing with orientation (getting and setting them). 
I know @benjamindeleener has invested a lot of time in this, and he might have had good reasons for not using nibabel. So it would be nice to have his feedback here.

**Comment by zougloub** [comment]
#1948 has documentation which clarifies all this orientation stuff, and new code that changes orientation (subject to unit tests), with the rest of the code was updated to use it.
