### ISSUE TITLE
Fancy new github issue templates?

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1945]
I just realized that github has these cool new issue templates thingy that make opening a bug look like this:
![20180718t012120](https://user-images.githubusercontent.com/998040/42861441-f8c29f94-8a28-11e8-9c77-bf4cf642e293.png)
This comes down to modifying the issue template to become many.
![20180718t012211](https://user-images.githubusercontent.com/998040/42861447-0363d8dc-8a29-11e8-9303-7b2d852ae861.png)

There's an extra indirection, but the issue template becomes much cooler.

**Comment by jcohenadad** [comment]
nice, i think we should use it
