### ISSUE TITLE
Add a flag to sct_deepseg_sc and sct_deepseg_lesion to input centerline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1952]
**Feature justification:**
In some cases, the centerline detection (svm- or cnn-based) fails, and it would be nice to be able to bypass this step by inputing our own centerline (e.g., obtained manually).

**Describe the solution you'd like**
A new option in the flag "centerline", where a file name would be input. Example of usage:
~~~
sct_deepseg_lesion -i my_image.nii.gz -c t2 -centerline file=my_centerline.nii.gz
~~~

@charleygros what do you think?

**Comment by jcohenadad** [comment]
also see https://github.com/neuropoly/spinalcordtoolbox/issues/1985

**Comment by charleygros** [comment]
@jcohenadad : I agree, this would be a very relevant feature.

Should we also allow the user to call the viewer to create the centerline, as in PropSeg (and suggested here #1985 ) ?
```
sct_deepseg_lesion -i my_image.nii.gz -c t2 -centerline viewer
```

**Comment by jcohenadad** [comment]
yes, we could indeed call the centerline-viewer module directly from `sct_deepseg_sc`.
