### ISSUE TITLE
sct_extract_metric -vert does not work properly

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#1963]
### Description

I did registration of template to T2 image, after it I warped atlases to T2 space. In this T2 space I have registred FA map as well. I would like to extract value of FA from WM from C3 to C6 vertebral levels, so I run:

`sct_extract_metric -i FA.nii.gz -method map -f label/atlas -l 51 -vert 3:6 -o metric.txt`

Function finds path to label and vertebral labeling file and recognizes vertebral levels, but returns me warnings during running (if I run same command without -vert flag I receive no warning):

> Checked parameters:
>   data ...................... FA.nii.gz
>   path to label ............. label/atlas
>   label ..................... 51
>   method .................... map
>   slices of interest ........ 
>   vertebral levels .......... 3:6
>   vertebral labeling file.... label/template/PAM50_levels.nii.gz
>   advanced parameters ....... ['10', '10']
> 
> 
> Load metric image...
> /usr/local/lib/sct/python/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /usr/local/lib/sct/python/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)

Function finishes without errors but metric.txt file contains metric from all slices, not only from slices at C3-C6 levels.
I use the latest stable SCT version v3.2.3 (master/438e48a6917eb31f657598f5704146a8b467b5ed).

**Comment by jcohenadad** [comment]
@valosekj this is strange. Would you mind sending me your data folder so i can try to debug?

**Comment by jcohenadad** [comment]
I noticed a bug that was introduced in v3.2.3 in the way slices are handled in `sct_extract_metrics`. I will produce a fix shortly.

**Comment by jcohenadad** [comment]
@valosekj I implemented a fix that you can test in a separate branch (see: https://github.com/neuropoly/spinalcordtoolbox/pull/1965, with instructions at the end for testing this branch). Would you mind testing it and letting me know if this is good for you?
Thanks

**Comment by valosekj** [comment]
@jcohenadad I just updated to the newest master version (because branch `jca/1963-extract-metric-bug-vert-level`  was deleted by zougloub) and tried to run function again with following progress:

> Spinal Cord Toolbox (master/b6141001c8a9f17d802eb741d58860ba1359a74f)
> Running /usr/local/lib/sct/scripts/sct_extract_metric.py -i FA.nii.gz -method map -f label/atlas -l 51 -vert 3:6 -o metric.txt
> 
> Checked parameters:
>   data ...................... FA.nii.gz
>   path to label ............. label/atlas
>   label ..................... 51
>   method .................... map
>   slices of interest ........ 
>   vertebral levels .......... 3:6
>   vertebral labeling file.... /md2/valosek/Template_registration/Julien/label/template/PAM50_levels.nii.gz
>   advanced parameters ....... ['10', '10']
> 
> 
> Load metric image...
> /usr/local/lib/sct/python/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /usr/local/lib/sct/python/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> 
> Saving results in: metric.txt ...
> Traceback (most recent call last):
>   File "/usr/local/lib/sct/scripts/sct_extract_metric.py", line 1207, in <module>
>     fname_mask_weight, fname_vertebral_labeling=fname_vertebral_labeling, perslice=perslice, perlevel=perlevel)
>   File "/usr/local/lib/sct/scripts/sct_extract_metric.py", line 472, in main
>     method, overwrite, fname_normalizing_label, fixed_label, vert_levels=vert_levels)
>   File "/usr/local/lib/sct/scripts/sct_extract_metric.py", line 619, in save_metrics
>     existing_book = open_workbook(fname_output_xls)
>   File "/usr/local/lib/sct/python/lib/python2.7/site-packages/xlrd/__init__.py", line 394, in open_workbook
>     f = open(filename, "rb")
> IOError: [Errno 2] No such file or directory: 'metric.xls'
> Total processing time: 1 min 4 s

**Comment by jcohenadad** [comment]
@valosekj indeed, let me investigate further. Sorry about that.

**Comment by jcohenadad** [comment]
@valosekj could you please try again on branch: `jca/1963-extract-metric-bug-vert-level`?

**Comment by valosekj** [comment]
@jcohenadad It is working now. Thank you!
