### ISSUE TITLE
Missing argv input for some useful functions' main()

### ISSUE THREAD

**Issue by mparizet** [neuropoly/spinalcordtoolbox#1966]
it would be nice to be able to load those modules within Python, and hence accept args within the main

- sct_propseg

**Comment by zougloub** [comment]
Note that we're (slowly) in the process of developing a proper Python API for SCT so using `main()` is a temporary solution that should be avoided in durable code.

Let's see if we can take a shortcut and get you a decent API for `sct_propseg` ASAP.
