### ISSUE TITLE
Output tensor eigenvectors

### ISSUE THREAD

**Issue by Aaronearlerichardson** [neuropoly/spinalcordtoolbox#1974]
I am trying to perform fiber tracking on a data set and to do that I need to obtain the eigenvectors calculated in DTI computation. Hoping to see if they are saved somewhere, I tried changing the verbosity for the sct_dmri_compute_dti and this is what I got:
```
sct_dmri_compute_dti -i dmri_crop_moco.nii.gz -bvec dmri.bvec -bval dmri.bval -method restore -v 2

Spinal Cord Toolbox (version: 3.2.2)
Running /Users/spineimaging/sct_3.2.2/scripts/sct_dmri_compute_dti.py -i dmri_crop_moco.nii.gz -bvec dmri.bvec -bval dmri.bval -method restore -v 2
data.shape (48, 56, 28, 63)
Computing tensor using "restore" method...
Computing metrics...
WARNING: File dti_FA.nii.gz already exists. Deleting it.
WARNING: File dti_MD.nii.gz already exists. Deleting it.
WARNING: File dti_RD.nii.gz already exists. Deleting it.
WARNING: File dti_AD.nii.gz already exists. Deleting it.
Total processing time: 3 min 48 s

sct_dmri_compute_dti -i dmri_crop_moco.nii.gz -bvec dmri.bvec -bval dmri.bval -method restore -v 1


Spinal Cord Toolbox (version: 3.2.2)
Running /Users/spineimaging/sct_3.2.2/scripts/sct_dmri_compute_dti.py -i dmri_crop_moco.nii.gz -bvec dmri.bvec -bval dmri.bval -method restore -v 1
data.shape (48, 56, 28, 63)
Computing tensor using "restore" method...
Computing metrics...
WARNING: File dti_FA.nii.gz already exists. Deleting it.
WARNING: File dti_MD.nii.gz already exists. Deleting it.
WARNING: File dti_RD.nii.gz already exists. Deleting it.
WARNING: File dti_AD.nii.gz already exists. Deleting it.
Total processing time: 3 min 33 s
```
Is this supposed to happen? How else could I obtain the eigenvectors?

**Comment by jcohenadad** [comment]
hi @Aaronearlerichardson, indeed, SCT does not output eigenvectors (because nobody was using it so far). It is super easy to add them though. I'll do it tmr.

**Comment by jcohenadad** [comment]
the plan is to add a boolean flag `-eigenvector` with default=0

**Comment by jcohenadad** [comment]
@Aaronearlerichardson what format would you like the eigenvectors on? as a single 5-d data, or as 3x 4-d data (V1, V2, V3 like in FSL's `dtifit`)?

**Comment by Aaronearlerichardson** [comment]
I am specifically looking for the first eigenvector in a 4d single matrix (row, column, slice, 3)

**Comment by jcohenadad** [comment]
ok, i'll implement the FSL way then

**Comment by jcohenadad** [comment]
@Aaronearlerichardson can you please test branch `jca/1974-dmri-tensor-eigenvector` and let me know if it does the job for you?

**Comment by Aaronearlerichardson** [comment]
Works perfectly for me. Thank you!
