### ISSUE TITLE
sct_register_to_template: Wrong projection of labels onto centerline is labels are not in the same space

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1977]
### Description

In `sct_register_to_template.project_labels_on_spinalcord()`, the labels are re-oriented to RPI, which can cause bugs in case labels (i) are not in the same voxel space as the input segmentation and (ii) are not RPI. In fact, labels should *not* be re-oriented, because their coordinates are transformed into physical coordinates.

A proposed fix is to remove the re-orientation of labels before projecting them onto the cord centerline.

**Comment by zougloub** [comment]
From the description it looks like it should be fairly straightforward to provide, from sct_example_data or sct_testing_data, reproduction steps that definitely cause the mentioned issues.

**Comment by jcohenadad** [comment]
data: 20180801_Mirriam/data
