### ISSUE TITLE
Use Developer Certificate of Origin?

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1981]
To responsabilize developers on contributed code.

Relevant links:
- https://developercertificate.org/
- https://docs.google.com/document/d/1zpjDzL7yhGBZz3_7jCjWLfRQ1Jryg1mlIVmG8y6B1_Q/edit

**Comment by jcohenadad** [comment]
@zougloub sounds good to me.

**Comment by joshuacwnewton** [comment]
I'm not a lawyer, but from what I understand, the DCO is [a legally binding statement that requries users to sign-off on _every_ commit](https://beeware.org/contributing/how/dco/what/). I believe it's more relevant to larger, company-backed open source projects that want to mitigate liability in the case of a lawsuit. 

Considering we're a (relatively) small project compared to giants like GitLab, I'm not confident that the effort is worth the added security. But, like choosing a license, I think this is one of those decisions that requires consulting a legal expert to understand the tradeoffs/benefits. 

Considering we're not legal experts, I'm closing this for now. But, feel free to re-open if my judgement is off here.
