### ISSUE TITLE
sct_pipeline: status=1 instead of 200 if label file is missing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1990]
When running `sct_pipeline -f sct_register_to_template -d $PATH_DATA -p \"-i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz -igt ${SCT_DIR}/data/PAM50/template/PAM50_cord.nii.gz\" -pickle 1 -test-integrity 1 -j 127`, if "t2/labels.nii.gz" is missing, output status =1 (crash) whereas it should be 200 (file missing).

**Comment by joshuacwnewton** [comment]
`sct_pipeline` has been replaced by `sct_run_batch`. Closing. :)
