### ISSUE TITLE
Add tSNR computation from fMRI data in batch_processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2034]
To inspire people as well as to be sensitive to modifications on fmri-related functions, it would be good to add this quantification in the batch_processing.

Lines to add:
~~~
sct_fmri_compute_tsnr -i fmri_crop_moco.nii.gz
sct_extract_metric -i fmri_crop_moco_tsnr.nii.gz -f fmri_crop_moco_mean_seg_manual.nii.gz -o tsnr.txt
~~~
And then to extract results:
~~~
echo "fmri/tSNR: " `awk -F"," ' {print $9}' fmri/tsnr.txt | tail -1`
~~~

**Comment by joshuacwnewton** [comment]
Closing as I've grouped all of the ideas into one issue here: https://github.com/neuropoly/spinalcordtoolbox/issues/3250
