### ISSUE TITLE
NURBS too sensitive to number of input points

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2038]
NURBS is used in key functions, including `sct_straighten_spinalcord` (used for template registration, smoothing, etc.), `sct_propseg`, `sct_deepseg_sc`. There are a couple of issues that arose, in relation to the sensitivity of NURBS to the number of control points, the gap and the number of input points:
- https://github.com/neuropoly/spinalcordtoolbox/issues/1863
- https://github.com/neuropoly/spinalcordtoolbox/issues/2031

It would be nice to re-think the method, as suggested [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2031#issuecomment-425689939), to increase the robustness of the method. 

Some more details about where nurbs is called:
- `sct_get_centerline` --> `sct_process_segmentation.extract_centerline`--> `sct_smooth_spinalcord.smooth_centerline` --> `msct_smooth.b_spline_nurbs` --> `msct_nurbs.NURBS`

**Comment by Nicolas-Pinon** [comment]
I implemented fixes for the singularity matrix errors which arose in https://github.com/neuropoly/spinalcordtoolbox/issues/1863 and 
https://github.com/neuropoly/spinalcordtoolbox/issues/2031 in the branch : 
https://github.com/neuropoly/spinalcordtoolbox/tree/nipin/issue2038-NURBS
This permits NURBS to work at all time, even if a singular matrix arise in the process. This removes the need to use Hanning filtering, unless the number of slices is too low. 

I did not implement changes in the method really, should I try to find ways to improve it ?

**Comment by jcohenadad** [comment]
@Nicolas-Pinon awesome! could you please open a PR and describe the purpose of your branch within the PR? The we can take the discussion from there and start iterating on implementation/testing. Thanks!
