### ISSUE TITLE
'filename' error due to recent change in OSF metadata

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2056]
A user experienced issues when downloading data from OSF. The error was found because it automatically switched to the mirror URL, but one was missing (related to #2055). Strangely, the user could "manually" download the data from OSF (i.e. not through the installer), suggesting that there might be a bug in the installer for some particular configurations.

It would be good to test the installer on a similar configuration and see if the installer can successfully download via OSF. @alexfoias can you please try on a 14.04 LTS Ubuntu (e.g. via Docker)? 

more info: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/753a5f3dad/

**Comment by jcohenadad** [comment]
OK, this problem is systematic and is caused by a recent change in OSF's metadata. Previously, [this line](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_download_data.py#L189) was used to retrieve the file name on the repository. However, the dictionary field has recently changed, causing the following error:
~~~
Link download error, trying next mirror (error was: 'filename')
~~~

The download procedure would then switch to the mirror URL, so in most case the error is not a problem. However, we need to do something (e.g. if the mirror fails, the download fails).

One workaround, which has recently been implemented in [AxonDeepSeg](https://github.com/neuropoly/axondeepseg/pull/150/files#diff-bb7b85302b2b6a61c4fb63cce64c038fR175), is to input the zip file name in the function. However, this is definitely not clean and asks for more maintenance.

I've contacted OSF support to inquire about this.

To reproduce:
~~~
sct_download_data -d pmj_models
~~~

Also see: https://sourceforge.net/p/spinalcordtoolbox/help/2/

**Comment by felliott** [comment]
Hey @jcohenadad,

I'm a developer at COS.  Your diagnosis is correct.  We removed the `filename` parameter of the `Content-Disposition` header and added `filename*` so that we could correctly handle non-ascii characters in filenames.  I didn't consider that there might be existing software that supported only the former.  I will look at adding it back in, but the name will need be to be munged to not include any high-order bytes.  This means a filename like `résumé.docx` might be exported as `resume.docx` or `r_sum_.docx`.  Would that be okay for your use-case?

Cheers,
@felliott

**Comment by jcohenadad** [comment]
> a filename like résumé.docx might be exported as resume.docx or r_sum_.docx. Would that be okay for your use-case?

@felliott, yes that would be perfectly OK (we have banned all non-ascii characters from our ecosystem-- they are evil as i'm sure you know ;-) ). Thank you so much for accommodating!

**Comment by felliott** [comment]
I'm aiming for tomorrow or Friday.  I've got a fix coded up, and I'm just trying to figure out how to break it. :)

**Comment by felliott** [comment]
Hey @jcohenadad,

Sorry for the delay!  We've released our fix.  Now `Content-Disposition` headers should contain *both* the `filename` parameter and the `filename*` parameter.  For filenames containing only printable ascii characters these should be the same value.  Please let us know if that works for you, and thank you for the report!

Cheers,
@felliott

**Comment by jcohenadad** [comment]
@felliott this is working again. Thank you so much!!!
