### ISSUE TITLE
sct_image -setorient and -setorient-data don't effectively change orientation

### ISSUE THREAD

**Issue by Nicolas-Pinon** [neuropoly/spinalcordtoolbox#2062]
### Description

When using `sct_image -setorient` or `sct_image -setorient-data` to reorient images : 

Description says that `sct_image -setorient` changes only the header and that `sct_image -setorient-data` changes only the data (from the previous orientation to the newly defined one)

Using this image as a test : https://osf.io/akr3y

When running `sct_image -i PiginT1w_before.nii -getorient` we get the output : 

`--
Spinal Cord Toolbox (nipin/issue2043-nurbs-low-points/111e7e792d364511dca36fd1f79822a7f1ca188b)
Running /Users/nipin_local/GitHub/spinalcordtoolbox/scripts/sct_image.py -i PiginT1w_before.nii -getorient
RPI
Total processing time: 0 min 1 s`

So image is oriented in RPI

Now trying to perfom RPI to IPR change, using both methods to see the results : 

`sct_image -i PiginT1w_before.nii -setorient IPR -o PiginT1w_after_setorient.nii`
and `sct_image -i PiginT1w_before.nii -setorient-data IPR -o PiginT1w_after_setorientdata.nii`

Now we can use `-getorient` to see that : 

`--
Spinal Cord Toolbox (nipin/issue2043-nurbs-low-points/111e7e792d364511dca36fd1f79822a7f1ca188b)
Running /Users/nipin_local/GitHub/spinalcordtoolbox/scripts/sct_image.py -i PiginT1w_after_setorient.nii -getorient
IPR
Total processing time: 0 min 1 s`

`--
Spinal Cord Toolbox (nipin/issue2043-nurbs-low-points/111e7e792d364511dca36fd1f79822a7f1ca188b)
Running /Users/nipin_local/GitHub/spinalcordtoolbox/scripts/sct_image.py -i PiginT1w_after_setorientdata.nii -getorient
IPR
Total processing time: 0 min 1 s`

Both Header have changed to IPR, which is normal for the former, but not the later.

When visualizing the results with fsleyes, no difference can be seen between the two results.

Another problem is that when comparing the results (either one) with the original image, one can see that the visualization under fsleyes has changed, but the orientation didn't : 

<img width="2169" alt="before" src="https://user-images.githubusercontent.com/34742864/48426803-837b9f00-e735-11e8-8202-c33ccd7337e4.png">

_Original image (RPI)_

<img width="1888" alt="after" src="https://user-images.githubusercontent.com/34742864/48426828-8ececa80-e735-11e8-87f1-2b215d64766a.png">

_Image after switching to IPR (with either methods)_

Also, when visualizing with ITK_snap, no difference can be seen between before and after.

This issue can be problematic because if the image is not well oriented, functions like `sct_propseg` which operate by axial slices will obviously fail.

NB : issue #1944 (which was closed) seems kind of related to this problem

**Comment by jcohenadad** [comment]
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2106
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/1896
