### ISSUE TITLE
Extract TR/TE/alpha from BIDS-compatible json file 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2071]
When using BIDS-structured data, the json file alongside the MT, PD and T1w should have the necessary parameters to compute MTsat. So instead of inputing those parameters in the syntax, let's just read the json files (if they exist).

**Comment by joshuacwnewton** [comment]
Aha! Closing as this was handled by #2875. (I was here for this!) :tada:
