### ISSUE TITLE
Pipeline for re-training sct_deepseg_sc Keras model

### ISSUE THREAD

**Issue by armaneshaghi** [neuropoly/spinalcordtoolbox#2088]
I am aiming to re-train the Keras model behind `sct_deepseg_sc` on my data. Can I follow the instructions for `sct_deepseg_lesion` [here](https://github.com/sct-pipeline/deepseg-training)?

**Comment by charleygros** [comment]
@armaneshaghi: Indeed, the repo' that you pointed out aims at re-training the models behind both `sct_deepseg_sc` and `sct_deepseg_lesion` with few labeled data. However, we are still working on it to make it ready to be used. We will keep you updated.

**Comment by jcohenadad** [comment]
not relevant-- `sct_deepseg` is now the new function for DL stuff and it uses Pytorch
