### ISSUE TITLE
Detect c2c3 failing in one subject from spine_generic project

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2099]
It would be nice to have the automatic c2c3 detection work for all subjects in the [Multi-center/Multi-subjects](https://osf.io/jkxzp/) database. Here, we will list all failing subjects to try to find a solution that works for all subjects:
- unf_sub-04/t1

@charleygros maybe playing with the number of slices to average in the medial plane would increase robustness at inference time?

**Comment by charleygros** [comment]
Will have a look at this subject!
& investigate the number of slices to average, as you suggested. However, based on my first explorations, I do not think that it will improve it significantly: if the input segmentation is correct, then the flatten_sagittal should provide a sufficient view of the target structure.

Will keep you updated

**Comment by jcohenadad** [comment]
fixed by https://github.com/neuropoly/spinalcordtoolbox/pull/2103
