### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by RRivero48** [neuropoly/spinalcordtoolbox#2108]
I can not get the spinal cord segmentation in FSL eyes

The script messages are the following but I do not understand because I installed the most updated versions of spinalcordtoolbox and FSLeyes. I load the images, the integration with FSLeyes works but when I tried to process spinal cord segmentation It crashes.

Bad key "patch.force_edgecolor" on line 33 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "lines.dashed_pattern" on line 18 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.alignment" on line 268 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.markeredgecolor" on line 364 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.second" on line 228 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.major.right" on line 265 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.month" on line 224 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "scatter.marker" on line 340 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.minor.right" on line 267 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.major.left" on line 264 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.left" on line 252 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.minor.bottom" on line 249 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "axes.autolimit_mode" on line 213 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "hatch.color" on line 37 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.marker" on line 362 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.minute" on line 227 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.major.top" on line 246 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.day" on line 225 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.right" on line 253 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.bottom" on line 235 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.microsecond" on line 229 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.alignment" on line 250 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "hist.bins" on line 40 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "lines.scale_dashes" on line 21 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "axes.titlepad" on line 177 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "_internal.classic_mode" on line 515 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.hour" on line 226 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.markerfacecolor" on line 363 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.year" on line 223 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
/Users/ReneRivero/sct_3.2.7/python/lib/python2.7/site-packages/matplotlib/__init__.py:1069: UserWarning: Bad val "auto" on line #355
	"boxplot.flierprops.markerfacecolor: auto
"
	in file "/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle"
	Key boxplot.flierprops.markerfacecolor: auto does not look like a color arg
  (val, error_details, msg))
Bad key "lines.dotted_pattern" on line 20 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "axes.formatter.offset_threshold" on line 200 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.minor.top" on line 248 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.minor.left" on line 266 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "lines.dashdot_pattern" on line 19 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.major.bottom" on line 247 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.markersize" on line 365 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "hatch.linewidth" on line 38 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.top" on line 234 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "patch.force_edgecolor" on line 33 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "lines.dashed_pattern" on line 18 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.markeredgecolor" on line 362 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.second" on line 228 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.major.right" on line 264 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.month" on line 224 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "scatter.marker" on line 338 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.minor.right" on line 266 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.major.left" on line 263 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.left" on line 251 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.minor.bottom" on line 249 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "axes.autolimit_mode" on line 213 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "hatch.color" on line 37 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.marker" on line 360 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.minute" on line 227 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.major.top" on line 246 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.day" on line 225 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.right" on line 252 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.bottom" on line 235 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.microsecond" on line 229 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "hist.bins" on line 40 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "lines.scale_dashes" on line 21 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "axes.titlepad" on line 177 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "_internal.classic_mode" on line 513 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.hour" on line 226 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.markerfacecolor" on line 361 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "date.autoformatter.year" on line 223 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
/Users/ReneRivero/sct_3.2.7/python/lib/python2.7/site-packages/matplotlib/__init__.py:1069: UserWarning: Bad val "auto" on line #353
	"boxplot.flierprops.markerfacecolor: auto
"
	in file "/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle"
	Key boxplot.flierprops.markerfacecolor: auto does not look like a color arg
  (val, error_details, msg))
Bad key "lines.dotted_pattern" on line 20 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "axes.formatter.offset_threshold" on line 200 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.minor.top" on line 248 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "ytick.minor.left" on line 265 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "lines.dashdot_pattern" on line 19 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.major.bottom" on line 247 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "boxplot.meanprops.markersize" on line 363 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "hatch.linewidth" on line 38 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Bad key "xtick.top" on line 234 in
/Users/ReneRivero/Desktop/FSLeyes.app/Contents/Resources/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "/Users/ReneRivero/sct_3.2.7/scripts/sct_deepseg_sc.py", line 853, in <module>
    main()
  File "/Users/ReneRivero/sct_3.2.7/scripts/sct_deepseg_sc.py", line 792, in main
    arguments = parser.parse(args)
  File "/Users/ReneRivero/sct_3.2.7/scripts/msct_parser.py", line 414, in parse
    dictionary[arg] = self.options[arg].checkIntegrity(param)
  File "/Users/ReneRivero/sct_3.2.7/scripts/msct_parser.py", line 141, in checkIntegrity
    return self.checkIfNifti(param)
  File "/Users/ReneRivero/sct_3.2.7/scripts/msct_parser.py", line 240, in checkIfNifti
    elif param.lower() in self.list_no_image:
TypeError: argument of type 'NoneType' is not iterable
b'\n--\nSpinal Cord Toolbox (version: 3.2.7)\nRunning /Users/ReneRivero/sct_3.2.7/scripts/sct_deepseg_sc.py -i /Users/ReneRivero/T1/T1.img -c t1\nSentry is attempting to send 1 pending error messages\nWaiting up to 10 seconds\nPress Ctrl-C to quit\nTotal processing time: 0 min 21 s\n\n'
None
Traceback (most recent call last):
  File "/Users/ReneRivero/sct_3.2.7/contrib/fsl_integration/sct_plugin.py", line 187, in onButtonSC
    image = Image(outfilename)
  File "fsl/data/image.pyc", line 873, in __init__
  File "fsl/data/image.pyc", line 1450, in addExt
  File "fsl/utils/path.pyc", line 181, in addExt
fsl.utils.path.PathError: Could not find a supported file with prefix "/Users/ReneRivero/T1_seg.img"

Thanks in advance
Rene

**Comment by jcohenadad** [comment]
Thank you for reporting this bug @RRivero48, it is probably due to the recent changes of fsleyes. We will make sure to fix it before the next release.

**Comment by perone** [comment]
Hi @RRivero48, can you please provide us the version of FSLEyes you're using ? Thanks !

**Comment by RRivero48** [comment]
It is the version...

[FSLeyes.pdf](https://github.com/neuropoly/spinalcordtoolbox/files/2725445/FSLeyes.pdf)

**Comment by perone** [comment]
@charleygros I was looking into this error, do you know if `sct_deepseg_sc` supports `.img` files ? It looks like this might be the cause of this issue, given that the error shows the fsleyes calling the `sct_deepseg_sc`. Does anyone has a T1 volume in `.img` that can share with me to test it ?

**Comment by jcohenadad** [comment]
@perone SCT (i.e. including `sct_deepseg_sc`) does not support `.img` (a.k.a. "Analyze") format. Only NIFTI format.

**Comment by RRivero48** [comment]
I convert the images to nifty format and It worked well. But I only get the spinal cord segmentation. Is it not possible to label vertebral levels and obtain the spinal cord metrics in FSLeyes environment?

**Comment by jcohenadad** [comment]
Hi @RRivero48, yes it will be possible once we find some time to implement this feature. Thank you for your feedback.
