### ISSUE TITLE
Create a function for running batch processing with multi-processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2116]
We have an increasing number of shell-based processing pipelines, such as [this one](https://github.com/sct-pipeline/spine_generic). It simply loops across subjects (the file [run_process.sh](https://github.com/sct-pipeline/spine_generic/blob/master/run_process.sh) is the wrapper), so it would be more efficient to create a Python wrapper that would run each subject in a parallel, distributed across CPU cores.

**Comment by zougloub** [comment]
How about having the files use GNU parallel, which already exists?

**Comment by jcohenadad** [comment]
> How about having the shell files use GNU parallel, which already exists?

That sounds even better-- i was not aware of it.

**Comment by zougloub** [comment]
Example with `parallel`:
```sh
echo "--> " ${SITES[@]}

mkdir -p ${PATH_PROCESSING}

task=$1

do_one_subject() {
  local subject="$1"
  a="${PATH_PROCESSING}/$(basename $(dirname $subject))_$(basename $subject)"
  echo "rsync -Parisx ${subject}/ ${a}/; cd ${a}; ${task} $(basename $subject)"
}

for site in ${SITES[@]}; do
  find ${PATH_DATA}/${site} -mindepth 1 -maxdepth 1 -type d | while read subject; do
    do_one_subject "$subject"
  done
done \
 | parallel --hal-on-error soon,fail=1 sh -c "{}"
```

I have to say I'm not a huge fan of the shell approach, but it has the merit of being simple.

**Comment by jcohenadad** [comment]
@zougloub dummy question: what's this "-Parisx" in the rsync?

**Comment by zougloub** [comment]
It's my mnemonic flag set... I don't even remember what it does at this point. It's probably overkill and if I remember correctly it breaks on the native rsync from Apple (they stayed at non-GPLv3 versions).

**Comment by jcohenadad** [comment]
implemented here: https://github.com/sct-pipeline/spine_generic/blob/master/run_process.sh
