### ISSUE TITLE
Data for London 2019 course not present in sct_download_data

### ISSUE THREAD

**Issue by Nicolas-Pinon** [neuropoly/spinalcordtoolbox#2123]
Link to the London 2019 course data is not added in the `sct_download_data` script

**Comment by jcohenadad** [comment]
well spotted ;-) @Nicolas-Pinon 
but issue already listed in https://github.com/neuropoly/spinalcordtoolbox/issues/2114

**Comment by Nicolas-Pinon** [comment]
Oops my bad !
