### ISSUE TITLE
Possible regression which appears in integrity testing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2132]
Travis issue here: https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/482052671
Turned off integrity testing here: https://github.com/neuropoly/spinalcordtoolbox/pull/2129/commits/8bbdf317f1ff1a4dc5ed7f3ab42c28e266f9b132

i had to do it because of emergency (need a beta release for the course with priority functions working)

**Comment by joshuacwnewton** [comment]
Closing as this was addressed by #2315.
