### ISSUE TITLE
Look more into nipype for processing pipeline and parallelization

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#2142]
From discussions at 2019 SCT course in London, look more into [nipype](https://nipype.readthedocs.io/en/latest/) for batch processing and pipeline as advised by @fprados (Thanks! :) )

**Comment by jcohenadad** [comment]
related to https://github.com/neuropoly/spinalcordtoolbox/issues/2169 and https://github.com/neuropoly/spinalcordtoolbox/issues/1336

**Comment by jcohenadad** [comment]
A bit out of scope, and part of the neuroimaging community seems to push for NextFlow, so let's close for now
