### ISSUE TITLE
Fixture will break in recent version of pytest

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2150]
The way some functions used as session fixture are used will break in recent version of pytest (>3.7). Anticipating a move to py3k, we should rewrite some of the test functions which use fixtures.

Also see https://github.com/pytest-dev/pytest/issues/3950

**Comment by saulo-p** [comment]
I checked all `fixtures` in the tests and no occurrences of fixtures being called as functions exist anymore.
Some potentially troublesome instances were handled in commit 9f6d2d2c817fde3a692a94d8403dd9c2ecf0ba2e.

I think this issue can be closed.
