### ISSUE TITLE
sct_deepseg_sc temp file in input data folder

### ISSUE THREAD

**Issue by Nicolas-Pinon** [neuropoly/spinalcordtoolbox#2151]
When using `sct_deepseg_sc`, a file is created, named "image_in_RPI_resampled_seg.nii.gz", in the input data folder (i.e. the folder where the argument of `-i` is)

Regarding its name I think it is a temporary file and should be deleted at the end of the process (and surely be put in a temp folder when the process is ongoing)

To reproduce : 

run `sct_deepseg_sc` on any file

**Comment by charleygros** [comment]
@Nicolas-Pinon : Thank you for reporting this bug Nicolas!
I have made a small change, could you please review it and let me know how it goes? --> [This PR](https://github.com/neuropoly/spinalcordtoolbox/pull/2155)
Many thanks

**Comment by Nicolas-Pinon** [comment]
Thanks for fixing it !
