### ISSUE TITLE
sct_label_vertebrae -initz documentation

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#2162]
Hi,
I noticed change in help of `sct_label_vertebrae` function in the newer versions of SCT (from v4.0.0). In the example for `-initz` argument there is written that C3/4 disc corresponds to disc value 4:

https://github.com/neuropoly/spinalcordtoolbox/blob/fc2fc50f2061b1046ec53376fa371da014b5ac46/scripts/sct_label_vertebrae.py#L104

But in the previous versions of SCT (e.g. 3.1.1.) is mentioned that C3/4 disc corresponds to disc value 3.

Thanks,
Jan

**Comment by jcohenadad** [comment]
Hi Jan,
Indeed, you are right, we made this change to be consistent within SCT convention, because other functions use the new definition (i.e., C3/4 disc corresponds to disc value 4). Sorry about the break in retro-compatibility.

**Comment by jcohenadad** [comment]
Now fixed
