### ISSUE TITLE
sct_compute_mtr missing output file or folder flag

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/spinalcordtoolbox#2178]
**Feature justification: Is your feature request related to a problem? Please describe.**
The MTR script ([sct_compute_mtr.py](https://github.com/neuropoly/spinalcordtoolbox/blob/53b81c4b73fa65ad55ac391649ecb44744c077ad/scripts/sct_compute_mtr.py)) doesn't have a flag to either set the output filename and location ([it defaults to mtr.nii.gz in the active directory](https://github.com/neuropoly/spinalcordtoolbox/blob/53b81c4b73fa65ad55ac391649ecb44744c077ad/scripts/sct_compute_mtr.py#L85 )) like MTsat does ([see here](https://github.com/neuropoly/spinalcordtoolbox/blob/53b81c4b73fa65ad55ac391649ecb44744c077ad/scripts/sct_compute_mtsat.py#L64-L66)), or a flag to change the output directory of the file mtr.nii.gz (other functions have such a flag, like [here](https://github.com/neuropoly/spinalcordtoolbox/blob/53b81c4b73fa65ad55ac391649ecb44744c077ad/scripts/sct_deepseg_sc.py#L47-L52))

**Describe the solution you'd like**
Either of the two CLI flags solutions that I've pointed to above, maybe the first?

**Describe alternatives you've considered**
N/A

**Comment by jcohenadad** [comment]
First solution sounds good.
