### ISSUE TITLE
Parallel processing in python for sct

### ISSUE THREAD

**Issue by Nicolas-Pinon** [neuropoly/spinalcordtoolbox#2184]
Is there a way to parallelize python code in a simple way using one of the modules present in the python installation of sct, for instance `multiprocessing` ?
A simple case being : parallelizing a for loop that loops across many subjects

As discussed with @jcohenadad, opening an issue on this topic will allow future contributors to have a quick response to this simple question.

**Comment by jcohenadad** [comment]
@Nicolas-Pinon one approach is to use GNU-parallel, as illustrated [here](https://github.com/sct-pipeline/spine-generic/blob/master/run_process.sh#L84). I believe you can also do a system call of parallel within a Python script (if your for loop is within in Python).

Alternatively, we could explore more complex pipeline system as described in those issues:
- https://github.com/neuropoly/spinalcordtoolbox/issues/2169
- https://github.com/neuropoly/spinalcordtoolbox/issues/1336
- https://github.com/neuropoly/spinalcordtoolbox/issues/2142

**Comment by jcohenadad** [comment]
Another workflow management: https://snakemake.readthedocs.io/en/stable/

**Comment by Nicolas-Pinon** [comment]
Thanks for the propositions !

The bit of code I wanted to parallelize was this one : https://github.com/neuropoly/spinalcordtoolbox/blob/441cf21f160ce720a05fa57961bcc2f17fd28d10/scripts/nicolas_scripts/evaluate_hogancest.py#L76
But I have to transform it into a function that have files has an input to then parallelize it.

I guess it is easier to do everything _in_ python directly, and here I won't have to rewrite my searching for the files in a different shell script. Do you have any example of parallel called by system implemented somewhere ? 
I will definitely look on your propositions, but also on the multiprocessing module which seems easy to use.

Will update here on what I did and if it worked well 🙂

**Comment by jcohenadad** [comment]
for that application i would probably use the multiprocessing module. Nice tutorials:
- https://sebastianraschka.com/Articles/2014_multiprocessing.html
- https://pymotw.com/2/multiprocessing/basics.html

**Comment by Nicolas-Pinon** [comment]
Perfect, thanks !

**Comment by jcohenadad** [comment]
multiprocessing is now well covered by `sct_run_batch`
