### ISSUE TITLE
flag -a doesn't work

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#219]
Run command:
--------------------
~/data/criugm/d_sp_pain_pilot3/dmri $ sct_dmri_moco -i dmri.nii.gz -b dmri.bvec -a dmri.bval

Get output:
----------

Input parameters:
  input file ............dmri.nii.gz
  bvecs file ............dmri.bvec
  bvals file ............dmri.bval

Check file existence...
  OK: dmri.nii.gz
  OK: dmri.bvec
  OK: dmri.bval

Create temporary folder...
mkdir tmp.141124145552/

Copying input data to tmp folder and convert to nii...
cp /Volumes/users_hd2-1/slevy/data/criugm/d_sp_pain_pilot3/dmri/dmri.nii.gz tmp.141124145552/dmri.nii.gz
cp /Volumes/users_hd2-1/slevy/data/criugm/d_sp_pain_pilot3/dmri/dmri.bvec tmp.141124145552/bvecs.txt
fslchfiletype NIFTI dmri

Get dimensions of data...
  208 x 42 x 6

Identify b=0 and DWI images...

Identify b=0 and DWI images...
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_dmri_moco", line 483, in <module>
    main()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_dmri_moco", line 202, in main
    dmri_moco(param)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_dmri_moco", line 249, in dmri_moco
    index_b0, index_dwi, nb_b0, nb_dwi = identify_b0('bvecs.txt', param.fname_bvals, param.bval_min, param.verbose)
  File "/Users/slevy_local/spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py", line 233, in identify_b0
    bvals = numpy.array(map(float, f.readlines()))
ValueError: invalid literal for float(): 0 800 800 800 800 800 800 800 800 800 800 800 800 0 800 800 800 800 800 800 800 800 800 800 800 800 0 800 800 800 800 800 800 800 800 800 800 800 800 0 800 800 800 800 800 800 800 800 800 800 800 800

**Comment by benjamindeleener** [comment]
there is no more flag -a
