### ISSUE TITLE
-init flag ignored in v4.0.0-beta.1

### ISSUE THREAD

**Issue by thiagojrezende** [neuropoly/spinalcordtoolbox#2190]
The propseg function showed bad performance in the version 4.0.1-beta when compared with the stable version 3.2.7 for a same subject. 
Please verify the figures SCseg_v327 and SCseg_v4b1 that exemplifies the results obtained for each version of the software. 

In attachment, follow the commands used for each version and the messages with one image test. 

SCT version: 4.b.1

evans:~/Documents/testEnigma_3 $ sct_propseg -i cont_03.nii.gz -c t1 -down 0 -up 76 -init 15

--
Spinal Cord Toolbox (version: 4.0.0-beta.1)
Running /Users/thiago_admin/sct_4.0.0-beta.1/scripts/sct_propseg.py -i cont_03.nii.gz -c t1 -down 0 -up 76 -init 15
isct_propseg -t t1 -o ./ -down 0 -up 76 -verbose -i /Users/thiago_admin/Documents/testEnigma_3/cont_03.nii.gz -init-centerline centerline.nii.gz -centerline-binary # in /Users/thiago_admin/Documents/testEnigma_3
Initialization - using given centerline
Total propagation length = 262.548 mm

Segmentation finished. To view results, type:
fslview /Users/thiago_admin/Documents/testEnigma_3/cont_03.nii.gz ./cont_03_seg.nii.gz &

Check consistency of segmentation...

Create temporary folder (/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313115525.479446-propseg-oKiHRc)...
tmp.segmentation.nii.gz
tmp.centerline.nii.gz

Get data dimensions...
tmp.segmentation_RPI_c.nii.gz
WARNING: File /Users/thiago_admin/Documents/testEnigma_3/cont_03_seg.nii.gz already exists. Will overwrite it.
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313115525.479446-propseg-oKiHRc
Copy header input --> output(s) to make sure qform is the same.
WARNING: File /Users/thiago_admin/Documents/testEnigma_3/cont_03_seg.nii.gz already exists. Will overwrite it.
WARNING: File /Users/thiago_admin/Documents/testEnigma_3/cont_03_centerline.nii.gz already exists. Will overwrite it.

Done! To view results, type:
fslview /Users/thiago_admin/Documents/testEnigma_3/cont_03.nii.gz -l Greyscale /Users/thiago_admin/Documents/testEnigma_3/cont_03_seg.nii.gz -l Red -t 0.7 &

Total processing time: 0 min 40 s

![SCseg_v4b1](https://user-images.githubusercontent.com/48558200/54362517-71583180-463f-11e9-8d24-a5853136abf3.png)

SCT version: 3.2.7

evans:~/Documents/testEnigma_2 $ sct_propseg -i cont_03.nii.gz -c t1 -down 0 -up 76 -init 15

--
Spinal Cord Toolbox (version: 3.2.7)
Running /Users/thiago_admin/sct_3.2.7/scripts/sct_propseg.py -i cont_03.nii.gz -c t1 -down 0 -up 76 -init 15
Detecting the spinal cord using OptiC
cp /Users/thiago_admin/Documents/testEnigma_2/cont_03.nii.gz /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313090950.147465-Lf2x1v
cp cont_03_centerline_optic.nii.gz /Users/thiago_admin/Documents/testEnigma_2/./
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313090950.147465-Lf2x1v
isct_propseg -t t1 -o ./ -down 0 -up 76 -verbose -i /Users/thiago_admin/Documents/testEnigma_2/cont_03.nii.gz -init 0.0627615062762 -init-centerline ./cont_03_centerline_optic.nii.gz -centerline-binary # in /Users/thiago_admin/Documents/testEnigma_2
Initialization - using given centerline
Total propagation length = 92.501 mm

Segmentation finished. To view results, type:
fslview /Users/thiago_admin/Documents/testEnigma_2/cont_03.nii.gz ./cont_03_seg.nii.gz &

Check consistency of segmentation...

Create temporary folder (/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313091010.021429-propseg-l6_CY5)...
tmp.segmentation.nii.gz
tmp.centerline.nii.gz

Get data dimensions...
tmp.segmentation_RPI_c.nii.gz
WARNING: File /Users/thiago_admin/Documents/testEnigma_2/cont_03_seg.nii.gz already exists. Will overwrite it.
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313091010.021429-propseg-l6_CY5
Copy header input --> output(s) to make sure qform is the same.
WARNING: File /Users/thiago_admin/Documents/testEnigma_2/cont_03_seg.nii.gz already exists. Will overwrite it.
WARNING: File /Users/thiago_admin/Documents/testEnigma_2/cont_03_centerline.nii.gz already exists. Will overwrite it.

Done! To view results, type:
fslview /Users/thiago_admin/Documents/testEnigma_2/cont_03.nii.gz -l Greyscale /Users/thiago_admin/Documents/testEnigma_2/cont_03_seg.nii.gz -l Red -t 0.7 &

Total processing time: 0 min 25 s

![SCseg_v327](https://user-images.githubusercontent.com/48558200/54362518-71583180-463f-11e9-96d1-62be4af9780a.png)

[SCT_Propseg.docx]

(https://github.com/neuropoly/spinalcordtoolbox/files/2966733/SCT_Propseg.docx)
[cont_03.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/2966737/cont_03.nii.gz)

**Comment by jcohenadad** [comment]
@thiagojrezende thank you for raising that issue! I confirm that I can reproduce your observations. We will work on it with top priority.

**Comment by jcohenadad** [comment]
The problem of performance is caused by v4.0.0-beta.1 not accounting for the flag `-init` anymore. This is a regression bug which will be addressed

**Comment by jcohenadad** [comment]
After fixing the -init flag issue, processing time drastically decreases (20s vs. 40s).
