### ISSUE TITLE
set_label_vertebrae fails in version 4.0.0-beta.1

### ISSUE THREAD

**Issue by thiagojrezende** [neuropoly/spinalcordtoolbox#2191]
The command sct_label_vertabrae of SCT version 4.0.0-beta.1 failed to find C2-C3 in a T1w image. In contrast, for the same subject, the SCT version 3.2.7 identified automatically C2-C3.

In attachment, follows the description of the command used and messages obtained. In addition, follows a test imaging. 

SCT version: 3.2.7

<details>

~~~
evans:~/Documents/testEnigma_2 $ sct_label_vertebrae -i cont_03.nii.gz -s cont_03_seg.nii.gz -c t1

--
Spinal Cord Toolbox (version: 3.2.7)
Running /Users/thiago_admin/sct_3.2.7/scripts/sct_label_vertebrae.py -i cont_03.nii.gz -s cont_03_seg.nii.gz -c t1

Create temporary folder (/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t)...

Copying input data to tmp folder...

Create label to identify disc...

Straighten spinal cord...
sct_straighten_spinalcord -i data.nii -s segmentation.nii.gz -r 1 # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t

Resample to 0.5mm isotropic...
sct_resample -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t

Apply straightening to segmentation...
sct_apply_transfo -i segmentation.nii.gz -d data_straightr.nii -w warp_curve2straight.nii.gz -o segmentation_straight.nii.gz -x linear # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t
sct_maths -i segmentation_straight.nii.gz -thr 0.5 -o segmentation_straight.nii.gz # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t

Look for template...
Path template: /Users/thiago_admin/sct_3.2.7/data/PAM50

Open template and vertebral levels...

Disc values from template: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Z-values for each disc: [962, 939, 908, 871, 834, 801, 770, 736, 693, 647, 601, 552, 501, 450, 397, 343, 290, 232, 169, 106, 56]
Distances between discs (in voxel): [23, 31, 37, 37, 33, 31, 34, 43, 46, 46, 49, 51, 51, 53, 54, 53, 58, 63, 63, 50]

Detect C2/C3 disk...
.. Peak found: z=93 (correlation = 0.374294261593)

Detect intervertebral discs...
Current disc: 2 (z=78). Direction: superior
.. Peak found: z=0 (correlation = 0.52335737801)
Current disc: 1 (z=109). Direction: superior
.. correcting factor: 1.0
.. Switching to inferior direction.
Current disc: 3 (z=41). Direction: inferior
.. Peak found: z=9 (correlation = 0.519620547701)
.. correcting factor: 0.878378378378
Current disc: 4 (z=18). Direction: inferior
.. Peak found: z=3 (correlation = 0.598587032476)
.. correcting factor: 0.846846846847
Adding top disc based on adjusted template distance: #0
.. approximate distance: 19

Un-straighten labeling...
sct_apply_transfo -i segmentation_straight_labeled.nii.gz -d segmentation.nii.gz -w warp_straight2curve.nii.gz -o segmentation_labeled.nii.gz -x nn # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t

Clean labeled segmentation (correct interpolation errors)...
sct_maths -i segmentation_labeled.nii.gz -mul segmentation.nii.gz -o segmentation_labeled_mul.nii.gz # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t
sct_maths -i segmentation_labeled.nii.gz -dilate 2 -o segmentation_labeled_dilate.nii.gz # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t
sct_maths -i segmentation_labeled_mul.nii.gz -bin 0 -o segmentation_labeled_mul_bin.nii.gz # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t
WARNING: File /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t/segmentation_labeled.nii.gz already exists. Will overwrite it.

Label discs...

Generate output files...
  File created: ./cont_03_seg_labeled.nii.gz
  File created: ./cont_03_seg_labeled_discs.nii.gz
  File created: ./warp_curve2straight.nii.gz
  File created: ./warp_straight2curve.nii.gz
  File created: ./straight_ref.nii.gz

Remove temporary files...
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313104129.360303-label_vertebrae-lphp2t

Done! To view results, type:
fslview /Users/thiago_admin/Documents/testEnigma_2/cont_03.nii.gz -t 1 ./cont_03_seg_labeled.nii.gz -l MGH-Subcortical -t 0.5 &

Total processing time: 1 min 31 s
~~~

</details>

![VetebraeLabel_v327](https://user-images.githubusercontent.com/48558200/54363299-145d7b00-4641-11e9-971a-6603274763a1.png)

SCT version: 4.b.1

<details>

~~~
evans:~/Documents/testEnigma_3 $ sct_label_vertebrae -i cont_03.nii.gz -s cont_03_seg.nii.gz -c t1

--
Spinal Cord Toolbox (version: 4.0.0-beta.1)
Running /Users/thiago_admin/sct_4.0.0-beta.1/scripts/sct_label_vertebrae.py -i cont_03.nii.gz -s cont_03_seg.nii.gz -c t1

Create temporary folder (/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313115830.590073-label_vertebrae-SoameE)...

Copying input data to tmp folder...

Create label to identify disc...
Creating temporary folder...
Run C2-C3 detector...
C2-C3 not detected...
Remove temporary files...
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190313115833.209371-oAvLK1
Automatic C2-C3 detection failed. Please provide manual label with sct_label_utils
Traceback (most recent call last):
  File "/Users/thiago_admin/sct_4.0.0-beta.1/scripts/sct_label_vertebrae.py", line 842, in <module>
    main()
  File "/Users/thiago_admin/sct_4.0.0-beta.1/scripts/sct_label_vertebrae.py", line 256, in main
    sct.printv('Automatic C2-C3 detection failed. Please provide manual label with sct_label_utils', 1, 'error')
  File "/Users/thiago_admin/sct_4.0.0-beta.1/scripts/sct_utils.py", line 1016, in printv
    raise RuntimeError("printv(..., type=\"error\")")
RuntimeError: printv(..., type="error")
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Total processing time: 0 min 6 s
~~~

</details>

[SCT_Label_Vertebrae.docx]

(https://github.com/neuropoly/spinalcordtoolbox/files/2966797/SCT_Label_Vertebrae.docx)
[cont_03.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/2966798/cont_03.nii.gz)

**Comment by jcohenadad** [comment]
Thank you @thiagojrezende for reporting that issue! I can reproduce on my end. We will work on it with top priority.

**Comment by charleygros** [comment]
It seems that C2-C3 is correctly detected by the algorithm:
![c2c3_map](https://user-images.githubusercontent.com/14353425/54537392-81c52f00-49e6-11e9-8c37-eda0f0e6615c.png)

--> The issue certainly comes from the post-processing.
Also, it would be certainly helpful to add a `remove_tmp_file` option for the module `detect_c2c3`.

**Comment by jcohenadad** [comment]
> Also, it would be certainly helpful to add a remove_tmp_file option for the module detect_c2c3.

since we want to refactor this variable (heavy in the code, hard to maintain, etc.) for now we can just create all temp files with the `sct.tmp_create` module

**Comment by jcohenadad** [comment]
@thiagojrezende could you please confirm

**Comment by thiagojrezende** [comment]
I updated my SCT version, ran the sct_label_vertebrae and got the following error:


evans:~/Documents/Errors_SCT $ sct_label_vertebrae -i cont_03.nii.gz -s cont_03_seg.nii.gz -c t1

--
Spinal Cord Toolbox (version: dev)
Running /Users/thiago_admin/spinalcordtoolbox/scripts/sct_label_vertebrae.py -i cont_03.nii.gz -s cont_03_seg.nii.gz -c t1

Create temporary folder (/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190320093348.335334-label_vertebrae-oLdyzL)...

Copying input data to tmp folder...

Straighten spinal cord...
sct_straighten_spinalcord -i data.nii -s segmentation.nii -r 1 # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190320093348.335334-label_vertebrae-oLdyzL

Resample to 0.5mm isotropic...
sct_resample -i data_straight.nii -mm 0.5x0.5x0.5 -x linear -o data_straightr.nii # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190320093348.335334-label_vertebrae-oLdyzL

Apply straightening to segmentation...
isct_antsApplyTransforms -d 3 -i segmentation.nii -r data_straightr.nii -t warp_curve2straight.nii.gz -o segmentation_straight.nii -n Linear # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190320093348.335334-label_vertebrae-oLdyzL
sct_maths -i segmentation_straight.nii -thr 0.5 -o segmentation_straight.nii # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190320093348.335334-label_vertebrae-oLdyzL

Create label to identify disc...
Creating temporary folder...
Run C2-C3 detector...
C2-C3 detected...
Traceback (most recent call last):
  File "/Users/thiago_admin/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 395, in <module>
    main()
  File "/Users/thiago_admin/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 304, in main
    im_label_c2c3 = detect_c2c3(im_data, im_seg, contrast)
  File "/Users/thiago_admin/spinalcordtoolbox/spinalcordtoolbox/vertebrae/detect_c2c3.py", line 114, in detect_c2c3
    rl_c2c3 = int(np.rint(center_of_mass(nii_seg.data[:, is_c2c3, :])[1]))
  File "/Users/thiago_admin/spinalcordtoolbox/python/lib/python2.7/site-packages/scipy/ndimage/measurements.py", line 1289, in center_of_mass
    return [tuple(v) for v in numpy.array(results).T]
TypeError: 'numpy.float64' object is not iterable
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Total processing time: 1 min 2 s

**Comment by jcohenadad** [comment]
@charleygros can you please look into this?
@thiagojrezende i suggest you use git to update SCT install (not download the zip from github, which takes more time and does not allow us to track the exact master version you are using)

**Comment by thiagojrezende** [comment]
My apologies. But this was my first download from master branch and to keep update the SCT with git pull, I needed the clone of SCT from github. The next versions, I will use git. 
Just for the record, I used the latest version released 40 min ago.

**Comment by charleygros** [comment]
When I am running the `sct_label_vertebrae` command mentioned by @thiagojrezende --> I obtain the same error.

However, when I am running the pythonic module `detect_c2c3` from my terminal with the same inputs --> it works fine.

Keep investigating.

**Comment by charleygros** [comment]
The error reported by @thiagojrezende is due to this line:
```
rl_c2c3 = int(np.rint(center_of_mass(nii_seg.data[:, is_c2c3, :])[1]))
```

For some reason, the type of `nii_seg.data[:, is_c2c3, :]` is `<class 'numpy.core.memmap.memmap'>`, which causes the error.
To convert it to a `np.array` seems to solve the issue.

**Comment by jcohenadad** [comment]
yup, known issue (unsolved), e.g., see https://github.com/neuropoly/spinalcordtoolbox/issues/2148

it is likely that this bug will come up again at some point, in another SCT function. @zougloub do you have so clues as to how to solve it?  maybe the move to python 3 will fix it.

**Comment by charleygros** [comment]
Yes, that's indeed the same error: as in #2148, the bug is not observed when using the compressed segmentation file.

Should I submit a PR with `center_of_mass(np.array(.))` to fix `sct_label_vertebrae` bug? or should we wait for @zougloub insights?

**Comment by jcohenadad** [comment]
> Should I submit a PR with center_of_mass(np.array(.)) to fix sct_label_vertebrae bug? or should we wait for @zougloub insights?

Submit the PR, this is time sensitive. Thanks!
