### ISSUE TITLE
Account for rotation in default settings

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2204]
We should re-introduce centermassrot (or alternative algorithm) in `sct_register_to_template`, because in some cases, e.g. here for the London course, rotation of the cord is obvious and should be accounted for:

![anim](https://user-images.githubusercontent.com/2482071/55026041-89816680-4fd8-11e9-9f90-54277ce4583d.gif)

@Nicolas-Pinon could you open a PR on your current investigations so we can start cross-referencing all related issues

**Comment by Nicolas-Pinon** [comment]
Will do soon !

**Comment by Nicolas-Pinon** [comment]
Is it possible to have the location of this specific file ? It looks like a great example of spinal cord rotation

**Comment by jcohenadad** [comment]
@Nicolas-Pinon mentioned above ;-) "London course"
