### ISSUE TITLE
ValueError: Extra data when generating qc report

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2205]
### Description

When running a pipeline on an ssh-connected station (no tunnelling), I experienced a bug during QC report generation:

<details>

~~~
Mask type float64
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/scripts/sct_register_multimodal.py", line 812, in <module>
    main()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/scripts/sct_register_multimodal.py", line 553, in main
    path_qc=os.path.abspath(path_qc), process='sct_register_multimodal')
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/reports/qc.py", line 569, in generate_qc
    stretch_contrast_method='equalized',
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/reports/qc.py", line 481, in add_entry
    layout(qcslice)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/reports/qc.py", line 275, in wrapped_f
    self.qc_report.update_description_file(img.shape)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/spinalcordtoolbox/reports/qc.py", line 423, in update_description_file
    results = json.load(open(self.qc_params.qc_results, 'r'))
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 3346 column 2 - line 3348 column 2 (char 208880 - 208890)
~~~

</details>

### Investigations 1

- `sct_testing` --> pass
- Same dataset, running locally --> pass
- output in new qc folder --> pass
- output in old qc folder --> FAIL

After investigations (see Investigations 1) The source of this bug seems related to a corruption of the already-existing json file, which has the following text towards the end:

~~~
  {
    "orientation": "Axial", 
    "python": "/home/GRAMES.POLYMTL.CA/p101317/code/sct/python/bin/python", 
    "moddate": "2019-04-01 12:51:46", 
    "dataset": "mgh_spineGeneric", 
    "cmdline": "sct_deepseg_sc -i sub-06_acq-T1w_MTS_crop_r.nii.gz -c t1 -ofolder /home/GRAMES.POLYMTL.CA/p101317/spineGeneric_result/mgh_spineGeneric/derivatives/labels/sub-06/anat -qc /home/GRAMES.POLYMTL.CA/p101317/spineGeneric_qc", 
    "fname_in": "sub-06_acq-T1w_MTS_crop_r.nii.gz", 
    "subject": "sub-06", 
    "sct_version": "git-master-0b3d3c5a4739f909fea94c2bd4745def35648ba0", 
    "dimension": "30x600", 
    "command": "sct_deepseg_sc", 
    "background_img": "mgh_spineGeneric/sub-06/anat/sct_deepseg_sc/2019_04_01_125145.001709/bkg_img.png", 
    "overlay_img": "mgh_spineGeneric/sub-06/anat/sct_deepseg_sc/2019_04_01_125145.001709/overlay_img.png", 
    "cwd": "/home/GRAMES.POLYMTL.CA/p101317/spineGeneric_result/mgh_spineGeneric/sub-06/anat", 
    "contrast": "anat"
  }
]nat"
  }
]
~~~

Note the "]nat"" which are the cause of the problem. How was this corruption introduced needs further investigations.

It is likely that the corruption appeared while two parallel processes tried to access the same json file at the same time, given that the json was generated by a pipeline working with `parallel` framework. Interesting read:
- https://blog.gocept.com/2013/07/15/reliable-file-updates-with-python/

### Potential solution

The culprit is [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/reports/qc.py#L425).

One possible solution would be to check if the file is being used by another process, and if it is, wait until it is closed before opening and writing in it.

**Comment by zougloub** [comment]
Checking that the file is used by another process may not be feasible and would be costly. What can be done is to use [file locking](https://en.wikipedia.org/wiki/File_locking), maybe with [portalocker](https://pypi.org/project/portalocker/) which is suitably licensed for use.

**Comment by jcohenadad** [comment]
thanks @zougloub, i will implement that option
