### ISSUE TITLE
Clarify handling of logger, error and exceptions

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2213]
### Description of the problem
SCT uses several ways to communicate and raise exceptions:
- sct_utils.printv
- [sct_utils.log](https://github.com/neuropoly/spinalcordtoolbox/wiki/logging)
- logger module (e.g. [here](https://github.com/neuropoly/spinalcordtoolbox/blob/925987e5b179a67cdc95ea9bc10aa7e4758c69d2/spinalcordtoolbox/gui/sagittal.py))
- sct_utils.class Error(Exception)
- try/except

### Proposed solution
The purpose of this issue is to establish convention and update the code and [wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki/logging) accordingly. Also see #1941. For convenience, this box will be updated as we propose solutions for most scenarios (see below):

**Code in command-line functions (e.g. sct_propseg)**
```python
import spinalcordtoolbox.utils as sctu
sctu.printv('Running segmentation, type='normal')
sctu.printv('Finished! To view results, type: XYZ, type='info')
```

**Code in library's APIs (e.g. spinalcordtoolbox/resampling)**
```python
import logging
logging.info('Running segmentation')
logging.debug('Centerline fitting error is: {}'.format(fitting_error))
```

**Dealing with exceptions (both in API and library)**
```python
if something_right:
  # do something
elif something_wrong:
  raise ValueError('Something is wrong: XYZ')  # Replace with appropriate exception depending on the scenario
```

TODO:
- Refactor sct.printv (currently redirect to logging)
- Establish strategy for redirecting and cleaning logging into stdout when running API from Terminal. Could print in another color. 
- Establish strategy for filtering logging redirection following hierarchical approach (e.g., exclude child calls)

### Changes to the code
- Move printing-related stuff from `sct_utils` to `spinalcordtoolbox.utils`

**Comment by zougloub** [comment]
Logging is one thing, printing is another, and handling exceptions yet another thing.

In a sane world, according to my views:
- Library functions:
  - shouldn't do any printing;
  - can use logging;
  - throw exceptions (there is a sufficiently big hierarchy of built-in exceptions that we don't really need to invent new ones);
  - catch exceptions, log a sane message, and rethrow exceptions;
- Front-ends (command-line programs):
  - print stuff;
  - may use logging filters/formatters to print what library functions log;

`sct.log` has a problem when we consider going towards use of SCT functions in other programs (or Jupyter): it has hard-coded handlers, which makes library functions print.

**Comment by jcohenadad** [comment]
Thanks @zougloub! So do you think we should forget `sct_utils.log`?

And would the example ideally look like this?
```python
if something_right:
  # do something
elif something_wrong:
  logging.exception('Something is wrong: XYZ')
  raise ValueError
```

**Comment by jcohenadad** [comment]
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/1941

**Comment by jcohenadad** [comment]
Currently, when introducing `logging` in SCT python module, there is a conflict with sct_utils.printv, which causes duplication of output message in the terminale:
~~~
  WARNING: File ./t2_straight.nii.gz already exists. Deleting it...
INFO:sct:  WARNING: File ./t2_straight.nii.gz already exists. Deleting it...
  File created: ./t2_straight.nii.gz
INFO:sct:  File created: ./t2_straight.nii.gz
rm -rf /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190407150026.541177-straighten_spinalcord-B0sgxD
INFO:sct:rm -rf /var/folders/6f/wy6ljmx9453cgth2qwv5l1s80000gn/T/sct-20190407150026.541177-straighten_spinalcord-B0sgxD

Finished! Elapsed time: 2 s
INFO:sct:
~~~

A PR will need to go through all SCT functions, and introduce the logger at once, while modifying the current printv function (which relies on the logger) to avoid such problem
