### ISSUE TITLE
set_deep_sc fails in to identify cervical SC

### ISSUE THREAD

**Issue by thiagojrezende** [neuropoly/spinalcordtoolbox#2215]
Hi,
I ran the set_deep_sc command in patients with Friedreich ataxia and, in some subjects, the cervical spinal cord was not identified. However, the processing was finished as if everything went well and when I opened the segmentation image there was nothing or only 2 or 3 slices with wrong segmentation. 

Below, follows the description of the command used and the messages obtained. I am also sending some examples of the images that was used in these processing. 

Subject 01

evans:~/Documents/testSCT/Error_2 $ sct_deepseg_sc -i frda_15.nii.gz -c t1

--
Spinal Cord Toolbox (version: 3.2.7)
Running /Users/thiago_admin/sct_3.2.7/scripts/sct_deepseg_sc.py -i frda_15.nii.gz -c t1

Method:
	Centerline algorithm: cnn
	Assumes brain section included in the image: True
	Dimension of the segmentation kernel convolutions: 2d

Creating temporary folder...
cp frda_15.nii.gz /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408082828.105666-MEtHXa
Reorient the image to RPI, if necessary...
Resample the image to 0.5 mm isotropic resolution...
/Users/thiago_admin/sct_3.2.7/python/lib/python2.7/site-packages/nipy/io/files.py:145: FutureWarning: Default `strict` currently False; this will change to True in a future version of nipy
  ni_img = nipy2nifti(img, data_dtype = io_dtype)
Finding the spinal cord centerline...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
Brain section detected.
isct_spine_detect -ctype="dpdt" -lambda="1" "NONE" "frda_15_RPI_resampled_heatmap" "frda_15_RPI_resampled_heatmap" # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408082828.105666-MEtHXa
Cropping brain section.
WARNING: File /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408082828.105666-MEtHXa/frda_15_RPI_resampled_heatmap_ctr.nii.gz already exists. Will overwrite it.
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 2D patches...
Reassembling the image...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
Resampling the segmentation to the original image resolution...
Binarizing the segmentation to avoid interpolation effects...
WARNING: File frda_15_RPI_seg.nii.gz already exists. Will overwrite it.
Reorienting the segmentation to the original image orientation...
cp /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408082828.105666-MEtHXa/frda_15_seg.nii.gz /Users/thiago_admin/Documents/testSCT/Error_2
Remove temporary files...
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408082828.105666-MEtHXa

Done! To view results, type:
fslview frda_15.nii.gz -l Greyscale /Users/thiago_admin/Documents/testSCT/Error_2/frda_15_seg.nii.gz -l Red -t 0.7 &

Total processing time: 2 min 0 s

![Screen Shot 2019-04-08 at 9 22 27 AM](https://user-images.githubusercontent.com/48558200/55727475-12889c80-59e0-11e9-951e-a95dddc75c63.png)

Subject 02

evans:~/Documents/testSCT/Error_2 $ sct_deepseg_sc -i frda_65.nii.gz -c t1

--
Spinal Cord Toolbox (version: 3.2.7)
Running /Users/thiago_admin/sct_3.2.7/scripts/sct_deepseg_sc.py -i frda_65.nii.gz -c t1

Method:
	Centerline algorithm: cnn
	Assumes brain section included in the image: True
	Dimension of the segmentation kernel convolutions: 2d

Creating temporary folder...
cp frda_65.nii.gz /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408083132.633672-nCBUtt
Reorient the image to RPI, if necessary...
Resample the image to 0.5 mm isotropic resolution...
/Users/thiago_admin/sct_3.2.7/python/lib/python2.7/site-packages/nipy/io/files.py:145: FutureWarning: Default `strict` currently False; this will change to True in a future version of nipy
  ni_img = nipy2nifti(img, data_dtype = io_dtype)
Finding the spinal cord centerline...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
Brain section detected.
isct_spine_detect -ctype="dpdt" -lambda="1" "NONE" "frda_65_RPI_resampled_heatmap" "frda_65_RPI_resampled_heatmap" # in /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408083132.633672-nCBUtt
Cropping brain section.
WARNING: File /private/var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408083132.633672-nCBUtt/frda_65_RPI_resampled_heatmap_ctr.nii.gz already exists. Will overwrite it.
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 2D patches...
Reassembling the image...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
Resampling the segmentation to the original image resolution...
Binarizing the segmentation to avoid interpolation effects...
WARNING: File frda_65_RPI_seg.nii.gz already exists. Will overwrite it.
Reorienting the segmentation to the original image orientation...
cp /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408083132.633672-nCBUtt/frda_65_seg.nii.gz /Users/thiago_admin/Documents/testSCT/Error_2
Remove temporary files...
rm -rf /var/folders/dv/9t9_nj0d6ln20k7bw4wlqtvr0000gv/T/sct-20190408083132.633672-nCBUtt

Done! To view results, type:
fslview frda_65.nii.gz -l Greyscale /Users/thiago_admin/Documents/testSCT/Error_2/frda_65_seg.nii.gz -l Red -t 0.7 &

Total processing time: 1 min 12 s

![Screen Shot 2019-04-08 at 9 23 40 AM](https://user-images.githubusercontent.com/48558200/55727501-22a07c00-59e0-11e9-96e5-c614f321a380.png)

[frda_15_seg.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3054451/frda_15_seg.nii.gz)
[frda_15.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3054452/frda_15.nii.gz)
[frda_65_seg.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3054453/frda_65_seg.nii.gz)
[frda_65.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3054454/frda_65.nii.gz)

**Comment by jcohenadad** [comment]
@thiagojrezende before going further, we would need to know how you are planning to use the segmentations: is it for CSA measures? for registration to the template in order to use another image (e.g., diffusion)? What levels are you interested in?  Based on the image `frda_15.nii.gz`, I would not go below C3 because the SNR is quite low. But again, it depends what you are planning to do with the segmentations.

**Comment by thiagojrezende** [comment]
I would like to measure only CSA in C2/C3 levels for this kind of image.

**Comment by jcohenadad** [comment]
@thiagojrezende could you try with the latest version (4.0.0-beta.2) or from the master branch? Looks like your problem is now solved:

**frda_15**:
![Screen Shot 2019-04-08 at 10 53 21](https://user-images.githubusercontent.com/2482071/55733914-a3fe0b80-59ec-11e9-91ff-df2b6aa214ad.png)

**frda_65**:
![Screen Shot 2019-04-08 at 10 55 30](https://user-images.githubusercontent.com/2482071/55734039-df003f00-59ec-11e9-909f-704269f38600.png)

**Comment by thiagojrezende** [comment]
Yes, it works. 
I just run with this new version.
Thanks.

**Comment by jcohenadad** [comment]
@thiagojrezende i recommend you use the QC feature for quicker visual assessment, e.g.:
~~~
sct_deepseg_sc.py -i frda_65.nii.gz -c t1 -qc ~/qc
~~~

**Comment by thiagojrezende** [comment]
@jcohenadad , I am doing this for the new images processed with SCT since our last talking.
