### ISSUE TITLE
sct_process_segmentation CSA angle correction

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#2219]
Dear SCT experts,
we extracted values of cross-sectional area (CSA) from our dataset using `sct_process_segmentation` function (SCT v4.0) in two different setting (with and without angle correction):

1) With no-angle correction:
`sct_process_segmentation -i T2TRA_seg.nii.gz -p shape -vert 3:7 -vertfile T2TRA_seg_labeled.nii.gz -perslice 1 -no-angle 1 -append 1 -o noangle_correction.csv`

2) With angle correction:
`sct_process_segmentation -i T2TRA_seg.nii.gz -p csa -vert 3:7 -vertfile T2TRA_seg_labeled.nii.gz -perslice 1 -no-angle 0 -append 1 -o angle_correction.csv`

Values of extracted CSA trully differ. And the difference increases with higher angle between local cord centerline and SI axis. We computed percentage difference between non-corrected and corrected CSA as:

Diff [%] = (Non-corrected - Corrected) / Corrected * 100

After, we visualized a percentage difference through individual vertebral levels:

![CSA_error_levels](https://user-images.githubusercontent.com/39456460/55881254-9be7cc80-5ba2-11e9-9b1f-ba45c2c61b58.png)

We can see from the image that individual values of percentage difference form increasing non-linear function starting from the [0,0] point (as expected). But we can also see, that there is formed a strip of 3-5% uncertainty above the function. Is it caused by rounding errors or do you have some other explanation? While non-zero error for 0° rotation is a bit strange phenomenon.

And it says to us: if we would observe clinical difference/change in corrected CSA parameter about 0.1-5% between groups of controls and patients with SC compression. Then, the clinical result should not be relevant while it is hidden/blur behind the method error. Please correct us, if we are not right. But still it should be better than non-corrected CSA, where can be observed error in rages 0-40% for some slices.

Thanks in advance,
Jan and Rene

**Comment by jcohenadad** [comment]
Hi @valosekj, this is a very nice investigation. We've indeed observed instabilities in the computation of the angle, which was addressed in this PR (merged on master last week): https://github.com/neuropoly/spinalcordtoolbox/pull/2200
Would you be able to re-run your analysis using SCT master's version?
Cheers

**Comment by valosekj** [comment]
Hi @jcohenadad, thank you for suggestion. But after I updated to the latest SCT version using `git pull`, all SCT scripts fail with python's _portalocker_ package import error:

> --
> Spinal Cord Toolbox (master/d50102be4e00ead24651e5bfe701e645965961cb)
> Running /usr/local/lib/sct/scripts/sct_process_segmentation.py
> Traceback (most recent call last):
>   File "/usr/local/lib/sct/scripts/sct_process_segmentation.py", line 23, in <module>
>     import sct_utils as sct
>   File "/usr/local/lib/sct/scripts/sct_utils.py", line 27, in <module>
>     import portalocker
> ImportError: No module named portalocker
> Total processing time: 0 min 0 s

I installed portalocker manually using `python -m pip install portalocker` and checked it:

> user@machine:~$ pip freeze | grep portalocker
> portalocker==1.4.0

But it did not help...

Thanks! 
Jan

**Comment by jcohenadad** [comment]
Hi, you need to run: ./install_sct

**Comment by renelabounek** [comment]
Hi @jcohenadad, Jan has updated SCT to the latest master version at our machines and it seems the current algorithm version has an issue with AP angle estimation. Please, see attached visualization. Percentage differences for RL angle look relevant. AP angle still makes 0-10% CSA metric differences for angles close to 0°. We expect the whole 3D function (left graph) should have an elliptic paraboloid shape (z = x^2 + y^2), not the parabolic cylinder (z = x^2).

![csa_correction_error2](https://user-images.githubusercontent.com/12597538/56047766-c30ddd80-5d0b-11e9-91a9-0e61a89a9dd8.png)
**Note:** in graphs are also two outlayers with negative percentage difference.

We can also try to help to stabilize CSA angle corrected estimation. Just to be sure, is AP angle the angle between SI axis and local centerline tangent in cartesian coordinate system of sagittal projection? Is RL angle the angle between SI axis and local centerline tangent in cartesian coordinate system of coronal projection? And non-corrected CSA area is then rotated with a affine transformation utilizing a built rotation matrix with 0° angle for the axial projection?
________________________________________________________________________________
**Our recent observations:**
Unfortunately, we still are not high-level python hackers. But it seems, that the code version:
[https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/process_seg.py](url)
at rows 63-87 trully does very similar procedure, which we have written before finding it.

Only one difference, which we can see just now, is that you are doing 2D affine tranformation and not calculate with 0° angle for the axial projection. Just now, we are not able immediately say if it will or will not change a result.
Anyway, 2D or 3D rotation matrices expect 2 or 3 angles alpha (rotation around x-axis), beta (rotation around y-axis), gama (rotation around z-axis). Are you sure that angle_AP_rad and angle_RL_rad angles reflect the mentioned rotations? While they both seem to be z-axis (i.e. v1 = [0 1]) related in two mutually perpendicular projections.

For more details we would need to debug the code. Please let us know, if we should find time for it.
________________________________________________________________________________

Best,
Rene and Jan

**Comment by jcohenadad** [comment]
Hi @renelabounek, thank you so much for these exhaustive evaluations. It is always very helpful to have additional validation outside of our unit tests. 

A bit of clarification. First of all, AP angle means the angle about the AP axis, i.e., in the coronal plane, while the RL angle means the angle about the RL axis, i.e., in the sagittal plane, as specified in the (updated) [London SCT course '19](https://osf.io/gvs6f/) page 64. We will specify it in the function usage as well (issue opened https://github.com/neuropoly/spinalcordtoolbox/issues/2224).

Then, the way CSA is corrected is **not** by rotating the plane with a affine transformation (which, as you rightly point out, would require a 3x3 matrix). Instead, we apply an in-plane scaling factor, in both direction. This effect is similar than retrieving what the CSA would be if it was not projected onto a 2D plane (i.e. the axial plane of the slice). 

Regarding validation: we have established fairly exhaustive unit testing specifically for this function, testing various angles, FOV size, resolution bit encoding, etc.  The full unit test is accessible at [this link](https://github.com/neuropoly/spinalcordtoolbox/blob/master/unit_testing/test_process_seg.py). However, we currently only test for angles about the IS and RL axes. Following your investigations, I will add tests in the AP direction to make sure there is no problem with our implementation.

**Comment by jcohenadad** [comment]
Hi, I implemented more exhaustive tests for CSA with AP angulation (see https://github.com/neuropoly/spinalcordtoolbox/pull/2226), and all tests pass, so I don't think there is a problem with the implementation of the angle correction method.

What I think is happening in the bottom right panel of your graphic [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2219#issuecomment-482667793), is that by plotting delta_CSA=f(angle_AP), keep in mind that the delta_CSA is **also** affected by angle_RL (which is, in general, more prominent given that the cord is usually more angled about the RL axis vs. the AP axis), therefore, it is expected to see variability at delta_CSA=f(angle_AP=0, angle_RL!=0).

**Comment by renelabounek** [comment]
Hi @jcohenadad, I agree you are right. After your yesterday angle variable clarification, I was thinking about it in the evening and have got to the same conclusion. The angle_RL is the angle characterizes the most common spinal cord bendings with expected much larger angle value than for the angle_AP (which is more related to the phenonenon, if the subject has the neck in the scanner parallel or crooked).

It was an unfair 3D visualization, where x-axis limits and y-axis limits were not the same ranges. When I focused only at same ranges the function becomes trully to bby close to the eliptical parabolid as should be expected.

Still I am glad, we all are sure now that the CSA correction works fine in comparison to the previous version.

![csa_correction_error3](https://user-images.githubusercontent.com/12597538/56082550-c5416c00-5ddf-11e9-92aa-4d852c6ab416.png)

Many thanks for the discussion,
Rene

**Comment by jcohenadad** [comment]
We reached agreement, so the issue can be closed
