### ISSUE TITLE
ImportError: cannot import name 'factorial' from 'scipy.misc'

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2267]
New deprecation from nipy: https://github.com/nipy/nipy/issues/453

more info at: https://scipy.github.io/devdocs/release.1.3.0.html#scipy-interpolate-changes
Travis fail: https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/535398407#L1012

**Comment by jcohenadad** [comment]
A solution would be to temporarily (until nipy/nipy fixes the problem) use [this nipy fork](https://github.com/jcohenadad/nipy) instead of the official one during installation of SCT.

**Comment by jcohenadad** [comment]
Removing `priority:HIGH` because https://github.com/neuropoly/spinalcordtoolbox/pull/2269 temporarily fixes the issue.

Once the issue is fixed on the official nipy repos, we can move back to the previous configuration by reverting:
- `sct_check_dependencies`
- `requirements.txt`

**Comment by zijin-gu** [comment]
hi, how did you fix this issue eventually? I have the same problem for now.
my nipy version is nipy-0.4.2 and now I have downgrade my scipy version to 1.2, but still the problem.

**Comment by jcohenadad** [comment]
@zijin-gu we bypassed (not fixed) the issue by dropping nipy dependency to SCT. What version of SCT are you using? you should try the latest and you shouldn’t have that problem anymore

**Comment by zijin-gu** [comment]
sorry, I don't think I am using a package called SCT. What do you mean by that?

**Comment by jcohenadad** [comment]
SCT=spinalcordtoolbox, this repository.

**Comment by zijin-gu** [comment]
Sorry, I am not using that. 
I am just trying to use this function called `Similarity` like this 
`from nipype.algorithms.metrics import Similarity`
which requires nipy to be installed. 
And I followed the instructions on installation but encountered this error.
