### ISSUE TITLE
Allow for infinite amount of URLs in SCT forum

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2271]
from https://github.com/neuropoly/spinalcordtoolbox/issues/2270#issue-447265243:

I was trying to submit the instalation fail report at http://forum.spinalcordmri.org/c/sct as requested at the end of the installation log, but the web page does not allow it to me, while the log has lots of url links and the web page says: "Sorry, new users can only put 5 links in a post."

**Comment by alexfoias** [comment]
I added 1000 links limit.
