### ISSUE TITLE
QC report using too much memory (Nipy resampling)

### ISSUE THREAD

**Issue by Nicolas-Pinon** [neuropoly/spinalcordtoolbox#2272]
Generating QC is really slow and sometimes can use a lot of memory, for instance when trying to run :

`sct_propseg -i sub-01_T1w.nii.gz -c t1 -qc /whatever `

with sub-01 from unf_spineGeneric_multiSubjects

As I found myself and as reported in the issue #2217, the step responsible for this is the resampling, done with Nipy.

Might be fixed by #2269 ?

**Comment by jcohenadad** [comment]
> Might be fixed by #2269 ?

nope! ;-)

i'll need to put my hands in the code to see where to optimize.

**Comment by jcohenadad** [comment]
Duplicate of https://github.com/neuropoly/spinalcordtoolbox/issues/2217
