### ISSUE TITLE
Refactor sct_label_utils into Python module

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2288]
SCT would largely benefit from a pythonization of `sct_label_utils`. Proposed features include:
- creation of module `spinalcordtoolbox.labels`
- the class `process` would output the Image object (currently it automatically writes an image)
- Deal more elegantly with image re-orientation (function-dependent)

**Comment by jcohenadad** [comment]
@Drulex is this issue still relevant?

**Comment by Drulex** [comment]
Fixed via #2887. It's funny, I didn't even know this issue existed prior to doing the refactor, but it implements everything mentioned here :+1:
