### ISSUE TITLE
Label Vertebrae Errors in SCT v402 and v405

### ISSUE THREAD

**Issue by thiagojrezende** [neuropoly/spinalcordtoolbox#2300]
I ran sct_vertebrae_label using beta versions 4.0.0-beta.2 and 4.0.0-beta.5 (master branch) in a t1w imaging. 
For both versions I had the same error at C4 vertebra (please, look figures in attached). I am also sending the processed files in order to reproduce the same error.

![Screen Shot 2019-06-06 at 11 43 55 AM](https://user-images.githubusercontent.com/48558200/59046700-739de680-8850-11e9-8ee6-c8e10eee786a.png)
![Screen Shot 2019-06-06 at 11 44 20 AM](https://user-images.githubusercontent.com/48558200/59046708-7698d700-8850-11e9-82c0-24440c6bdc15.png)

[v402.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3262368/v402.zip)
[v405.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3262369/v405.zip)

**Comment by jcohenadad** [comment]
Hi @thiagojrezende:
- did you experience similar issues with 3.2.7?
- can you try with `-scale-dist 0.8`?

**Comment by thiagojrezende** [comment]
Hi @jcohenadad ,
Both strategies provides worse labeled vertebrae.

This is the version 3.2.7
![Screen Shot 2019-06-06 at 1 06 53 PM](https://user-images.githubusercontent.com/48558200/59052027-27f13a00-885c-11e9-9db1-ed35b8095769.png)

This is with -scale-dist 0.8
![Screen Shot 2019-06-06 at 1 06 11 PM](https://user-images.githubusercontent.com/48558200/59052058-3a6b7380-885c-11e9-989d-4405b8151164.png)

**Comment by jcohenadad** [comment]
could you try with -scale-dist 0.6?

**Comment by thiagojrezende** [comment]
Not worked as well.
![Screen Shot 2019-06-06 at 1 19 03 PM](https://user-images.githubusercontent.com/48558200/59052724-b87c4a00-885d-11e9-9db0-5ed68cc98a42.png)

**Comment by jcohenadad** [comment]
0.7?

**Comment by thiagojrezende** [comment]
Not worked again.
![Screen Shot 2019-06-06 at 2 47 53 PM](https://user-images.githubusercontent.com/48558200/59058233-2d558100-886a-11e9-8a8c-303e726fa6da.png)

**Comment by thiagojrezende** [comment]
Issue closed because the vertebrae labels used in this study will be C2 and C3. Less than 5% of all processed images showed problems in to identify the vertebrae label.
