### ISSUE TITLE
PyTorch compatibility with sct

### ISSUE THREAD

**Issue by bsauty** [neuropoly/spinalcordtoolbox#2305]
I noticed that all sct functions that imply deep learning (`deepseg_gm` or  `deepseg_sc` for instance) use keras, should I switch from PyTorch to keras to implement the modality classifier ? Is it to reduce the list of dependencies or are there compatibility issues at stake ?

**Comment by jcohenadad** [comment]
@bsauty if your current implementation uses Pytorch, I would suggest to create a branch in SCT repos with your implementation so it can be tested via [Travis](https://travis-ci.org/neuropoly/spinalcordtoolbox/builds/542929531) across several OSs. If it passes, then you're good to go with Pytorch. If not, we can look at where it breaks.

In the long term, it is likely that Pytorch will become our main framework.

**Comment by jcohenadad** [comment]
Pytorch is now part of SCT's python package 😊
