### ISSUE TITLE
Add CentOS7 build on Travis

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2313]
Useful links:
- https://travis-ci.com/saltstack-formulas/postgres-formula/jobs/197417111/config
- https://github.com/brianmario/mysql2/blob/master/.travis.yml
  - Dockerfile: https://github.com/brianmario/mysql2/blob/master/.travis_Dockerfile_centos

Also see NeuroPoly Slack #random (internal)

**Comment by kousu** [comment]
Related: #1677

**Comment by kousu** [comment]
We should also test CentOS6 (at least until #2675) and CentOS8, and Mac OS 10.15. And if we could figure out a way to get WSL working too that would be good, though I know we're leaning mostly on Docker for Windows users.

**Comment by jcohenadad** [comment]
> though I know we're leaning mostly on Docker for Windows users.

are we? i think we would like to lean more towards WSL due to its simpler use. See https://github.com/neuropoly/spinalcordtoolbox/pull/2643

**Comment by kousu** [comment]
Oh great, I'm more in favour of that than containers. I tend to see containers as only a kind of artificial compatibility.
