### ISSUE TITLE
Add bash script for batch processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2329]
The script [run_process](https://github.com/sct-pipeline/spine-generic/blob/master/processing/run_process.sh), which has been developed for a few projects relying on SCT, proved to be very useful. Currently, there are different versions of this file across multiple projects, so the idea would be to create only one version and host it under SCT. Few questions:

- Where should we put it? One suggestion would be under a new folder `${SCT_DIR}/bash/`. The installer would then add this directory to the ${PATH}.

**Comment by Nicolas-Pinon** [comment]
I really like the idea, this script is indeed very useful
Maybe we could specify in the name that it is supposed to be used with BIDS data structure ? Like `run_process_bids` 
Because it is indeed only usable with BIDS structure

**Comment by jcohenadad** [comment]
> I really like the idea, this script is indeed very useful
> Maybe we could specify in the name that it is supposed to be used with BIDS data structure ? Like `run_process_bids`
> Because it is indeed only usable with BIDS structure

Actually `run_process` is not incompatible with non-BIDS dataset. It simply loops across folders within a parent directory. The header is misleading thought (it says: "only works with BIDS"), so I will update it.
