### ISSUE TITLE
Errors in argparse

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#2336]
I am having some bugs while using `sct_crop_image`. I believe they have been introduced by the new parser.

```
(venv_sct) charley@charley:~/code/exvivo_atlas/preprocessing$ sct_crop_image -i im.nii.gz -end 49,49 -dim 0,1 -o im_crop.nii.gz

--
Spinal Cord Toolbox (git-master-679e93b3013965fda561464639c74217686ced2a)

usage: sct_crop_image [-i <file>] [-g {0,1}] [-o <str>] [-h] [-v {0,1}]
                      [-r {0,1}] [-m <file>] [-start [<list> [<list> ...]]]
                      [-end [<list> [<list> ...]]]
                      [-dim [<list> [<list> ...]]]
                      [-shift [<list> [<list> ...]]] [-b <float>] [-bmax]
                      [-ref <file>] [-mesh <file>] [-rof {0,1}]
sct_crop_image: error: argument -end: invalid float value: '49,49'
```

The bug is due to:
1. The type indicated for the arguments `start`, `end`, `dim` and `shift`. Float or Int are indicated whereas it should be a string. [Example](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_crop_image.py#L329).
2. In the `help` of these arguments, we should have `"40,30,5"` instead of `"40, 30, 5"` since we are splitting this way --> [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_crop_image.py#L97).

**Comment by YangHee-Min** [comment]
@charleygros When running an old version of `sct_crop_image` (the one that uses msct_parser as shown [(here)](https://github.com/neuropoly/spinalcordtoolbox/blob/2421463cd5df71cb91a57728924df75ab59b49a5/scripts/sct_crop_image.py#L23)), when running the command line:

`sct_crop_image -i t2/t2.nii.gz -end 49,49 -dim 0,1 -o im_crop.nii.gz`

with `sct_testing_data`, I get the following terminal log:
https://pastebin.com/jrkWDFQ2

However, as I played with the script, when I input valid `-start` and `-end` inputs, the function seems to work fine.

I was wondering if there is supposed to be a default value for the arguments `-start` and `-end`

**Comment by jcohenadad** [comment]
@charleygros oops! an oversight. Indeed, it's a bug and we should fix it. @YangHee-Min can you please add to the list of the things to fix in the next argparse-related PR

@YangHee-Min indeed, -end should have a -start (so you were getting another error). But to answer your question, there is no default value for start/end.
