### ISSUE TITLE
argparse refactoring that will break retro-compatibility

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2342]
While parser refactoring is underway (see #1548), we need to urgently perform the long overdue release of 4.0.0 (major release). Once 4.0.0 is released, only patches and retro-compatible changes will be allowed. Hence, changes in CLIs caused by the parser refactoring will break retro-compatibility and should therefore be performed **before** this major release.

The purpose of this issue is to identify and refactor the functions where this refactoring will change the CLI syntax.

The following files will cause problem:
- `sct_maths` flag `-add` and `-mul`: the function `get_data_or_scalar()` uses the old parser. I suggest that instead of listing multiple files separated with "," we separate them with space and use argparse to fetch individual file names as a list.
- `sct_merge_images`: like before: files should be separated by space, not comma (flags -i, -w)
- `sct_straighten_spinalcord`: replace _ with - for some flags (ldisc_input, ldisc_dest, speed_factor, xy_size
- `sct_image`: has -i flag that requires files to be seperated by spaces rather than commas

**Comment by YangHee-Min** [comment]
@jcohenadad Certain functions do not have the possibility to use the command `--help` to display the usage help display such as `sct_flatten_sagittal` as shown[ (here)](https://github.com/neuropoly/spinalcordtoolbox/blob/9101db2ba8d04409abe356b2cb5fe46b8fcdd95b/scripts/sct_flatten_sagittal.py#L129-L132). This being minor, yet still different, would it be desirable to change these to add the `--help` command to display the help?

**Comment by YangHee-Min** [comment]
`sct_image`: has `-i` flag that requires files to be seperated by spaces rather than commas

**Comment by jcohenadad** [comment]
> `sct_image`: has `-i` flag that requires files to be seperated by spaces rather than commas

good point! can you please add at the beginning of this issue (so we centralize all functions that need urgent changes). Thx

**Comment by jcohenadad** [comment]
> @jcohenadad Certain functions do not have the possibility to use the command `--help` to display the usage help display such as `sct_flatten_sagittal` as shown[ (here)](https://github.com/neuropoly/spinalcordtoolbox/blob/9101db2ba8d04409abe356b2cb5fe46b8fcdd95b/scripts/sct_flatten_sagittal.py#L129-L132). This being minor, yet still different, would it be desirable to change these to add the `--help` command to display the help?

with the current refactoring, we are adding "-h" to all functions. So let's continue doing that

**Comment by YangHee-Min** [comment]
@jcohenadad In the script for `sct_maths`, arguments `-mean`, `-rms` and `-std` have type `multiple_choice`, but seem to have a set of choices from the example as shown [(here)](https://github.com/neuropoly/spinalcordtoolbox/blob/9101db2ba8d04409abe356b2cb5fe46b8fcdd95b/scripts/sct_maths.py#L68-L82). In these arguments, does the user have the option to choose which ones to use or can things other than those letters be picked?

**Comment by jcohenadad** [comment]
> @jcohenadad In the script for `sct_maths`, arguments `-mean`, `-rms` and `-std` have type `multiple_choice`, but seem to have a set of choices from the example as shown [(here)](https://github.com/neuropoly/spinalcordtoolbox/blob/9101db2ba8d04409abe356b2cb5fe46b8fcdd95b/scripts/sct_maths.py#L68-L82). In these arguments, does the user have the option to choose which ones to use or can things other than those letters be picked?

only those letters can be chosen

**Comment by baxpr** [comment]
There's a problem with the recent update to sct_image.py introduced in commit 7abacb003

-keep-vol (and other) command line arguments were formerly specified in the 
argument parser as type_value=[[','], 'int']

The typespec is no longer present and now I get this error:

> sct_image -keep-vol 0 -i fmri.nii.gz -o fmri_0.nii.gz

--
Spinal Cord Toolbox (git-HEAD-7fad17a0db089cbf7cdcb635062f8fac65f174c1*)

Traceback (most recent call last):
  File "/opt/sct/scripts/sct_image.py", line 644, in <module>
    main()
  File "/opt/sct/scripts/sct_image.py", line 207, in main
    im_out = [remove_vol(im_in, index_vol, todo='keep')]
  File "/opt/sct/scripts/sct_image.py", line 493, in remove_vol
    data_out = data[:, :, :, index_vol]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
