### ISSUE TITLE
batch_processing.sh produces different results between Linux and OSX

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2356]
Commit: 211ccce931c0f803f28b5805fcf422df26781a74

**OSX 10.14.6 "Mojave" (kernel 18.7.0 Darwin)** 
~~~
t2/CSA:          78.57328415897263
mt/MTR(WM):      54.08675584008292
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      65.08261276857283
dmri/FA(CST_r):  0.787213481161308
dmri/FA(CST_l):  0.7615085077204085
~~~

**Linux Ubuntu 16.04LTS "xenial" (kernel 4.4.0-142-generic)**
~~~
t2/CSA:          78.65373921999341
mt/MTR(WM):      54.05848282071633
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      65.08261276857283
dmri/FA(CST_r):  0.7840597354468211
dmri/FA(CST_l):  0.763402117406603
~~~

It would be important to figure out the cause of these differences, so we can understand/address them.

**Comment by gmotzespina** [comment]
Slightly difference on MacOS Mojave `10.14.5`

```
# Display results (to easily compare integrity across SCT versions)
# ===========================================================================================
set +v
Started at: 07/27/19_03:26:43 PM
Ended at: 07/27/19_03:40:55 PM

t2/CSA:          78.61361668633236
mt/MTR(WM):      54.08599119468571
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      65.08261276857283
dmri/FA(CST_r):  0.7822916188609416
dmri/FA(CST_l):  0.7538832762138471
```

**Comment by jcohenadad** [comment]
@gmotzespina did you make sure to use commit 211ccce in the results you posted above?

**Comment by jcohenadad** [comment]
The difference comes from `sct_propseg`, which does not deliver the same output across OSs. Below is an example of propseg applied to `sct_testing_data/t2/t2.nii.gz` on OSX and Linux:

![anim](https://user-images.githubusercontent.com/2482071/62222528-87ae2200-b381-11e9-96e7-083dbab778e0.gif)

A simple solution would be to replace `sct_propseg` by `sct_deepseg_sc` in the batch processing, and to add a warning in the usage and course material about `sct_propseg` instabilities.

**Comment by jcohenadad** [comment]
Reopening this issue because even though https://github.com/neuropoly/spinalcordtoolbox/pull/2377 mitigates this issue, it does not completely solves it as there are still differences which might be caused by `sct_extract_metric`
