### ISSUE TITLE
Installation: fetch nipy from http instead of git

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2362]
In the [requirements](https://github.com/neuropoly/spinalcordtoolbox/blob/master/requirements.txt#L25), we have to install a specific branch of nipy because the master branch is currently broken (see https://github.com/nipy/nipy/pull/454). 

However, this requires user to have git installed, otherwise this line will fail. 

The proposed fix is to fetch the nipy.git file from http instead of using git.

**Comment by gmotzespina** [comment]
@jcohenadad [Here](https://github.com/neuropoly/spinalcordtoolbox/blob/7fb78e65a9d69851c3b52c6af0a5879498b8eabe/install_sct#L54) we are checking if git is installed, if not the script will fail from the beginning on. Should we still make the change to fetch the file from http ?

**Comment by jcohenadad** [comment]
hum... good point. However, ideally if we could drop the dependency to git for people using the stable release that would be better (some people can have hard time installing git...). So, if we can remove that dependency, then you can remove that check. Would you mind having a look into this?

**Comment by gmotzespina** [comment]
Sounds nice, I'll take a look at it.

**Comment by jcohenadad** [comment]
@gmotzespina any update on this issue? It would be nice to have it fixed before 4.0.0 release. Thanks!

**Comment by gmotzespina** [comment]
I haven't fixed it yet, when is the next release?

**Comment by jcohenadad** [comment]
hopefully 1-2 days

**Comment by gmotzespina** [comment]
@jcohenadad 
I've been doing some testing and installing it without git isn't that trivial as far as I know. 

The procedure I've been following is the following, 

1. Download nipy,

```sh
wget --no-check-certificate --content-disposition https://github.com/jcohenadad/nipy/tarball/master 
```
2. Extract the package,

```sh
tar -xzf jcohenadad-nipy-0.4.2-10-ga1ac782.tar.gz 
```

3. `cd` into the extracted package `jcohenadad-nipy-a1ac782`

4. Run,
```sh
python setup.py install
```
After running the previous steps I get the following errors,

```sh
________________________________________________________________________________
Could not find datasource "nipy/templates" in data path "/Users/gmartinez/dev/spinalcordtoolbox/venv/bin/../share/nipy:/Users/gmartinez/.nipy"; Is it possible you have not installed a data package?

You may need the package "nipy-templates"

You can download and install the package from:

http://nipy.org/data-packages/nipy-templates-0.2.tar.gz

Check the instructions in the ``doc/users/install_data.rst`` file in the nipy
source tree, or online at http://nipy.org/nipy/users/install_data.html

If you have the package, have you set the path to the package correctly?
________________________________________________________________________________
Could not find datasource "nipy/data" in data path "/Users/gmartinez/dev/spinalcordtoolbox/venv/bin/../share/nipy:/Users/gmartinez/.nipy"; Is it possible you have not installed a data package?

You may need the package "nipy-data"

You can download and install the package from:

http://nipy.org/data-packages/nipy-data-0.2.tar.gz

Check the instructions in the ``doc/users/install_data.rst`` file in the nipy
source tree, or online at http://nipy.org/nipy/users/install_data.html

If you have the package, have you set the path to the package correctly?
running build_scripts
running install_lib
copying build/lib.macosx-10.14-x86_64-3.7/nipy/labs/__config__.py -> /Users/gmartinez/dev/spinalcordtoolbox/venv/lib/python3.7/site-packages/nipy/labs
copying build/lib.macosx-10.14-x86_64-3.7/nipy/__config__.py -> /Users/gmartinez/dev/spinalcordtoolbox/venv/lib/python3.7/site-packages/nipy
copying build/lib.macosx-10.14-x86_64-3.7/nipy/COMMIT_INFO.txt -> /Users/gmartinez/dev/spinalcordtoolbox/venv/lib/python3.7/site-packages/nipy
byte-compiling /Users/gmartinez/dev/spinalcordtoolbox/venv/lib/python3.7/site-packages/nipy/labs/__config__.py to __config__.cpython-37.pyc
byte-compiling /Users/gmartinez/dev/spinalcordtoolbox/venv/lib/python3.7/site-packages/nipy/__config__.py to __config__.cpython-37.pyc
running install_scripts
changing mode of /Users/gmartinez/dev/spinalcordtoolbox/venv/bin/nipy_tsdiffana to 755
changing mode of /Users/gmartinez/dev/spinalcordtoolbox/venv/bin/nipy_4dto3d to 755
changing mode of /Users/gmartinez/dev/spinalcordtoolbox/venv/bin/nipy_3dto4d to 755
changing mode of /Users/gmartinez/dev/spinalcordtoolbox/venv/bin/nipy_4d_realign to 755
changing mode of /Users/gmartinez/dev/spinalcordtoolbox/venv/bin/nipy_diagnose to 755
running install_data
________________________________________________________________________________
Could not find datasource "nipy/templates" in data path "/Users/gmartinez/dev/spinalcordtoolbox/venv/bin/../share/nipy:/Users/gmartinez/.nipy"; Is it possible you have not installed a data package?

You may need the package "nipy-templates"

You can download and install the package from:

http://nipy.org/data-packages/nipy-templates-0.2.tar.gz

Check the instructions in the ``doc/users/install_data.rst`` file in the nipy
source tree, or online at http://nipy.org/nipy/users/install_data.html

If you have the package, have you set the path to the package correctly?
________________________________________________________________________________
Could not find datasource "nipy/data" in data path "/Users/gmartinez/dev/spinalcordtoolbox/venv/bin/../share/nipy:/Users/gmartinez/.nipy"; Is it possible you have not installed a data package?

You may need the package "nipy-data"

You can download and install the package from:

http://nipy.org/data-packages/nipy-data-0.2.tar.gz

Check the instructions in the ``doc/users/install_data.rst`` file in the nipy
source tree, or online at http://nipy.org/nipy/users/install_data.html

If you have the package, have you set the path to the package correctly?
```

I might be missing something, I think those errors might be because I'm not doing the installation on the right path. 

### Alternative proposal

What about if we check if git is installed and if it is not then we could install git manually on the script ? 

From: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git,

> Installing on Linux
> If you want to install the basic Git tools on Linux via a binary installer, you can generally do so through the package management tool that comes with your distribution. If you’re on Fedora (or any closely-related RPM-based distribution, such as RHEL or CentOS), you can use dnf:

> $ sudo dnf install git-all
> If you’re on a Debian-based distribution, such as Ubuntu, try apt:

> $ sudo apt install git-all
> For more options, there are instructions for installing on several different Unix distributions on the Git website, at https://git-scm.com/download/linux.

**Comment by zougloub** [comment]
Pip is smart enough so that:
```
pip install https://github.com/jcohenadad/nipy/tarball/master
```
is working.

Just putting the URL in requirements isn't working?

**Comment by gmotzespina** [comment]
@zougloub wow thanks, I haven't using pip `pip` with `tarball` let me give it a try!

**Comment by gmotzespina** [comment]
@zougloub It worked! Thanks a bunch.
