### ISSUE TITLE
Update, upload and test course material

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2369]
- [ ] Add new QC for functions (warp template, process seg...)
- [ ] Add sponsors
- [ ] single batch processing: change "" for defining the "open" command

**Comment by YangHee-Min** [comment]
@jcohenadad Where can we find the updated course material?

**Comment by jcohenadad** [comment]
for now, use London and let us know where it breaks
--
Julien Cohen-Adad, PhD
Associate Professor, Polytechnique Montreal
Associate Director, Functional Neuroimaging Unit, University of Montreal
Canada Research Chair in Quantitative Magnetic Resonance Imaging
Phone: 514 340 5121 (office: 2264);  Skype: jcohenadad
Web: www.neuro.polymtl.ca

**Comment by YangHee-Min** [comment]
First review of course london 2019 is done. Bugs #2380 and #2381 to be fixed and small change in batch_single_subject.sh on line 145 from:
```
sct_register_multimodal -i $SCT_DIR/data/PAM50/template/PAM50_t2.nii.gz -iseg $SCT_DIR/data/PAM50/template/PAM50_cord.nii.gz -d mt1.nii.gz -dseg mt1_seg.nii.gz -param step=1,type=seg,algo=centermass:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=3 -m mask_mt1.nii.gz -initwarp ../t2s/warp_template2t2s.nii.gzsct_warp_template -d t2s.nii.gz -w warp_template2t2s.nii.gz -qc ~/qc_singleSubj 
```
to:
```
sct_register_multimodal -i $SCT_DIR/data/PAM50/template/PAM50_t2.nii.gz -iseg $SCT_DIR/data/PAM50/template/PAM50_cord.nii.gz -d mt1.nii.gz -dseg mt1_seg.nii.gz -param step=1,type=seg,algo=centermass:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=3 -m mask_mt1.nii.gz -initwarp ../t2s/warp_template2t2s.nii.gz
sct_warp_template -d ../t2s/t2s.nii.gz -w ../t2s/warp_template2t2s.nii.gz -qc ~/qc_singleSubj
```
Indeed, `-initwarp` shouldn't be merged with command `sct_warp_template` as seen below:
`-initwarp ../t2s/warp_template2t2s.nii.gzsct_warp_template`

**Comment by jcohenadad** [comment]
note to [this comment](https://github.com/neuropoly/spinalcordtoolbox/issues/2369#issuecomment-517454086), the line "sct_warp_template" should be removed (because it is done 3 lines later).
