### ISSUE TITLE
Odd output file

### ISSUE THREAD

**Issue by YangHee-Min** [neuropoly/spinalcordtoolbox#2378]
### Description
When following the London course from 2019 (related to testing for #2369 ), I ran into some issues regarding `sct_compute_mtr`. Indeed, when I used command :
`sct_compute_mtr -mt0 mt0_reg.nii.gz -mt1 mt1.nii.gz`

within `~/sct_course-london19/single_subject/data/mt`, I get following output:
![Screen Shot 2019-08-01 at 12 32 04 PM](https://user-images.githubusercontent.com/50307272/62310866-75eb7e00-b458-11e9-992c-45cce8c86da0.png)

and the following message log: https://pastebin.com/AfHsahG1

which I believe is not the proper output. 

### Steps to Reproduce

0. Install SCT <release or git revision and platform, you can use the
   first lines of output of sct_check_dependencies>

1. Go to home directory with: `cd ~`

2. Use following command line to donwload sct_course: `sct_download_data -d course_london19`

3. `cd sct_course-london19/single_subject/data/mt`

4. `sct_deepseg_sc -i mt1.nii.gz -c t2 -qc ~/qc_singleSubj`

5. `sct_create_mask -i mt1.nii.gz -p centerline,mt1_seg.nii.gz -size 35mm -f cylinder -o mask_mt1.nii.gz
`

6. `sct_register_multimodal -i mt0.nii.gz -d mt1.nii.gz -dseg mt1_seg.nii.gz -param step=1,type=im,algo=slicereg,metric=CC -m mask_mt1.nii.gz -x spline -qc ~/qc_singleSubj`

7.  `sct_compute_mtr -mt0 mt0_reg.nii.gz -mt1 mt1.nii.gz`

8. Open the file with fsleyes with command: `fsleyes mt0_reg.nii.gz mt1.nii.gz ./mtr.nii.gz &`

**Comment by jcohenadad** [comment]
look at your image scaling. MTR is in percentage (0-100).

**Comment by YangHee-Min** [comment]
Never mind everything is ok

**Comment by jcohenadad** [comment]
If you were troubled by the FSLeyes results, others will be, therefore this information/warning should appear in the SCT course. (this is the whole point of you going through this course --> to collect user experience).

I will close this issue once the doc is updated.

**Comment by jcohenadad** [comment]
course updated
