### ISSUE TITLE
change multithreading line of bashrc

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#238]
put export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=X with X the maximum number of processor in the bashrc

**Comment by jcohenadad** [comment]
for OSX, you can get the number of processors using:

    sysctl hw.ncpu | awk '{print $2}'

**Comment by jcohenadad** [comment]
solution with python:
http://stackoverflow.com/questions/1006289/how-to-find-out-the-number-of-cpus-using-python
