### ISSUE TITLE
UnboundLocalError: local variable 'nii' referenced before assignment

### ISSUE THREAD

**Issue by YangHee-Min** [neuropoly/spinalcordtoolbox#2380]
### Description
When following the London course from 2019 (related to testing for #2369 ), I ran into some issues regarding `sct_maths`. 

When I used command:
`sct_maths -i t2s_seg.nii.gz -sub "t2s_gmseg.nii.gz" -o t2s_wmseg.nii.gz`

I got the following output: https://pastebin.com/GxkeA9VX

### Steps to Reproduce

0. Install SCT <release or git revision and platform, you can use the first lines of output of sct_check_dependencies>

1. `cd ~/sct_course-london19/single_subject/data/t2s`

2. `sct_deepseg_sc -i t2s.nii.gz -c t2s -qc ~/qc_singleSubj`

3. `sct_deepseg_gm -i t2s.nii.gz -qc ~/qc_singleSubj`

4. `sct_maths -i t2s_seg.nii.gz -sub t2s_gmseg.nii.gz -o t2s_wmseg.nii.gz`

**Comment by YangHee-Min** [comment]
From what I see, the line:
`ValueError: could not convert string to float: 't'`

would be cause by the fact that argument `-sub` is taken as a string rather than an element of a list. I believe a solution would be to set `nargs` for `-sub` and `-div` equal to 1.

**Comment by jcohenadad** [comment]
@YangHee-Min i've fixed that error in your branch, in this commit 36d50478dacfc29ab12c797c914e6b5d46804369, however i forgot to push those commits before merging this PR https://github.com/neuropoly/spinalcordtoolbox/pull/2371.

I'll take care of it.
