### ISSUE TITLE
Unrecognized arguments within internal sct_concat_transfo call

### ISSUE THREAD

**Issue by YangHee-Min** [neuropoly/spinalcordtoolbox#2381]
When following the London course from 2019 (related to testing for #2369 ), I ran into some issues regarding `sct_register_multimodal`.

When I used command:
`sct_register_multimodal -i ${SCT_DIR}/data/PAM50/template/PAM50_t2s.nii.gz -iseg ${SCT_DIR}/data/PAM50/template/PAM50_wm.nii.gz -d t2s.nii.gz -dseg t2s_wmseg.nii.gz -param step=1,type=seg,algo=rigid:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=3 -initwarp ../t2/warp_template2anat.nii.gz -initwarpinv ../t2/warp_anat2template.nii.gz -qc ~/qc_singleSubj
`
I get the following output: https://pastebin.com/q9Z6LQeS

I believe this is caused by [(this line) ](https://github.com/neuropoly/spinalcordtoolbox/blob/0d574377ad5900b21b7e1ab686fe5eab9b1c2219/scripts/sct_register_multimodal.py#L526-L529)due to the recent conversion of `sct_concat_transfo` from internal parser to argparse. Indeed, inverted files no longer have "-" in front of the name but are rather put in a different argument labeled "-winv".

### Steps to Reproduce
(If you did not download sct_course_london19): sct_download_data -d course_london19

1. cd ~/sct_course-london19/single_subject/data/t2
2. sct_propseg -i t2.nii.gz -c t2 -qc ~/qc_singleSubj
3. sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc ~/qc_singleSubj
4. sct_label_utils -i t2_seg_labeled.nii.gz -vert-body 3,9 -o t2_labels_vert.nii.gz
5. sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l t2_labels_vert.nii.gz -c t2 -qc ~/qc_singleSubj
6. cd ../t2s
7. sct_deepseg_sc -i t2s.nii.gz -c t2s -qc ~/qc_singleSubj
8. sct_deepseg_gm -i t2s.nii.gz -qc ~/qc_singleSubj
9. sct_maths -i t2s_seg.nii.gz -sub t2s_gmseg.nii.gz -o t2s_wmseg.nii.gz
10. sct_register_multimodal -i ${SCT_DIR}/data/PAM50/template/PAM50_t2s.nii.gz -iseg ${SCT_DIR}/data/PAM50/template/PAM50_wm.nii.gz -d t2s.nii.gz -dseg t2s_wmseg.nii.gz -param step=1,type=seg,algo=rigid:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=3 -initwarp ../t2/warp_template2anat.nii.gz -initwarpinv ../t2/warp_anat2template.nii.gz -qc ~/qc_singleSubj

**Comment by jcohenadad** [comment]
note: 
- the steps to reproduce is not complete (../t2/warp_template2anat.nii.gz needs to be generated)
- step 2 is useless
