### ISSUE TITLE
New argparse in sct_image.py doesn't handle integer arguments

### ISSUE THREAD

**Issue by baxpr** [neuropoly/spinalcordtoolbox#2395]
@jcohenadad @YangHee-Min Sorry, just realized I had commented on a closed issue. There's a problem with the recent update to sct_image.py introduced in commit 7abacb0

-keep-vol (and other) command line arguments were formerly specified in the
argument parser as type_value=[[','], 'int']

The typespec is no longer present and now I get this error:

sct_image -keep-vol 0 -i fmri.nii.gz -o fmri_0.nii.gz

--
Spinal Cord Toolbox (git-HEAD-7fad17a0db089cbf7cdcb635062f8fac65f174c1*)

Traceback (most recent call last):
File "/opt/sct/scripts/sct_image.py", line 644, in 
main()
File "/opt/sct/scripts/sct_image.py", line 207, in main
im_out = [remove_vol(im_in, index_vol, todo='keep')]
File "/opt/sct/scripts/sct_image.py", line 493, in remove_vol
data_out = data[:, :, :, index_vol]
IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices

**Comment by jcohenadad** [comment]
@baxpr sorry for this oversight and thank you for reporting this bug! 
@YangHee-Min thank you for addressing it with top priority
