### ISSUE TITLE
sct_apply_transfo changes affine matrix in header of output file

### ISSUE THREAD

**Issue by baxpr** [neuropoly/spinalcordtoolbox#2398]
# Description

When using sct_apply_transfo, the geometrical information (affine matrix) in the header of the output image doesn't quiiiiite match the given reference image. It looks like a small roundoff type of error, but it complicates verifying whether two images have the same geometry later.

### Steps to Reproduce

sct version: I'm working off a fork, but the code is identical to commit 567a67e except for some local changes in install_sct.

Command line:

    sct_apply_transfo -i source.nii.gz -x nn -w warp_source2reference.nii.gz -d reference.nii.gz -o source_warped.nii.gz

**Expected behavior:** 
I would expect the affine matrices of the reference and warped source images to be identical.

**Actual behavior:** 

Resulting affine matrices:

    $ fslhd reference.nii.gz | grep sto_xyz
    sto_xyz:1	-0.584032 -0.045876 0.095196 75.921539 
    sto_xyz:2	-0.043881 0.578534 0.698280 -78.563744 
    sto_xyz:3	0.017422 -0.080728 4.950085 44.482220 
    sto_xyz:4	0.000000 0.000000 0.000000 1.000000 

    $ fslhd source_warped.nii.gz | grep sto_xyz
    sto_xyz:1	-0.584032 -0.045875 0.095183 75.921539 
    sto_xyz:2	-0.043881 0.578534 0.698280 -78.563744 
    sto_xyz:3	0.017420 -0.080728 4.950085 44.482220 
    sto_xyz:4	0.000000 0.000000 0.000000 1.000000

**Comment by baxpr** [comment]
Test images and script:
https://www.dropbox.com/sh/vgx63yyp821xer7/AABCqVXAeYv73s56tOGKEsIVa?dl=0

**Comment by jcohenadad** [comment]
@baxpr thank you for reporting this issue and provide data for replicating the issue. We will definitely have a look at it ASAP!

**Comment by baxpr** [comment]
In case anyone else stumbles on this, my current workaround is to use numpy.allclose with tolerance 1e-3 to compare these affine matrices.
