### ISSUE TITLE
soft links do not always apply the changes in the python scripts

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#241]
this issue doesn't appear on all computer and may be related with permissions (/usr/local/ installation). It can also be caused by the creation of the link, that we do during the package creation and not during the installation.

This issue can be problematic for patches.

**Comment by jcohenadad** [comment]
fixed in commit 8f70f0271f09b8a6eaa56b2ca6a61c0a7074c879
