### ISSUE TITLE
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2443]
### Description

The function crashes during straightening. The segmentation looks OK: some irregularities on the derivatives, but no discontinuities.

Original post from user [here](http://forum.spinalcordmri.org/t/error-with-sct-smooth-spinalcord-v4-0-2/171/2).

Other notable issues which could be addressed in the same PR:
- the usage does not specify "nurbs" in -param algo_fitting, even though it seems to always use this algorithm regardless the input param. 
- When using -v 2, the straightening command does not pass the verbose info. The sct.run() should be replaced with python call.
- The [linear interpolation before running nurbs](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/core.py#L135) is dysfunctional, because given that the smoothing window is null, it will [return the intput](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/curve_fitting.py#L126) without interpolation. Instead, the function `numpy.interp` could be used if smooth=0.

### Steps to Reproduce

Download these data:
[T2_seg.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/3616531/T2_seg.nii.gz)

Run:
~~~
sct_smooth_spinalcord -i T2_seg.nii.gz -s T2_seg.nii.gz -smooth 0 0 8 -r 0 -v 2
~~~

SCT version: 4.0.2

**Comment by jcohenadad** [comment]
The error is caused by the NURBS routine, not outputting the same vector length between `x_centerline_fit` or `y_centerline_fit` and `z_ref`, here: https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/core.py#L137

**Comment by jcohenadad** [comment]
@benjamindeleener could that be a bug in this section? https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/nurbs.py#L420

**Comment by jcohenadad** [comment]
Doing further investigations via the debugger, I noticed a strange behaviour. The normal call in [this code](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/nurbs.py#L1071) produces:
```python
P = nurbs.getCourbe3D()
len(P[0])
240  # PROBLEMATIC
len(z)
241
```

However, when manually running the sub-routine, I get:
```python
courbe3D_bis, _ = nurbs.construct3D(nurbs.pointsControle, nurbs.degre, nurbs.precision)
len(courbe3D_bis[0])
241  # GOOD!
```

**Comment by benjamindeleener** [comment]
Pfiou that was a tricky one...

The issue was coming from a slight mistake in the reparametrization of the NURBS curve to make it uniform. This effect was not usually apparent but was accentuated by the segmentation inhomogeneities on the edges.

So the error comes from this line: https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/nurbs.py#L948

That we need to change for
```
distances_between_points = centerline.progressive_length[1:]
```

**Comment by jcohenadad** [comment]
> Pfiou that was a tricky one...

I knew it 😉 

Thanks a lot @benjamindeleener! I can do the change and create the PR at this point (and bug you again if there are any more problems 😊)

**Comment by benjamindeleener** [comment]
Great, let me know.
