### ISSUE TITLE
sct_antsSliceRegularizedRegistration: double free or corruption (fasttop): 0x0000000002b7f190

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#245]
see: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/c8908a6b/?limit=25

likely due to a parsing issue because mask is accessed with absolute path. 

Possible fix: copy the mask and access it locally.

**Comment by benjamindeleener** [comment]
fixed in #245
