### ISSUE TITLE
sct_dmri_moco : sct_antsSliceRegularizedRegistration command not robust 

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#247]
I put two images that can't be correctly corrected with sct_antsSliceRegularizedRegistration here:
/Volumes/folder_shared/Project_Moco/slice_reg_pb

In this example target iteralively averaged is worse than target initial.

I limited the number of iteration for target averaging to 10.. If not you can propagate an error.

**Comment by tanguyduval** [comment]
See slice Z=1

**Comment by jcohenadad** [comment]
solution:
~~~~
sct_create_mask -i target.nii -s 50
sct_register_multimodal -d target.nii -i dwi_averaged_groups_T0090.nii -p 10,SliceReg,0.5,MeanSquares -z 0 -m mask_target.nii 
~~~~
