### ISSUE TITLE
sct_create_mask

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#248]
Command:
----------------

    slevy/data/criugm/d_sp_pain_pilot2/dmri $ sct_create_mask -i dmri.nii.gz

Terminal output:
-----------------

   check existence of input files...
  OK: dmri.nii.gz

Input parameters:
  data ..................dmri.nii.gz
  method ................center

Create temporary folder...
mkdir tmp.150119120704/

Copying input data to tmp folder and convert to nii...
cp dmri.nii.gz tmp.150119120704/data.nii.gz
fslchfiletype NIFTI data

Get dimensions of data...
  208 x 42 x 6 x 104
WARNING in sct_create_mask: Input image is 4d but output mask will 3D.
export FSLOUTPUTTYPE=NIFTI; fslroi data data -0 1

Create line...
cp data.nii line.nii
sct_c3d line.nii -scale 0 -o line.nii
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 0
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 1
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 2
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 3
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 4
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 5

Create mask...
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 335, in <module>
    main()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 87, in main
    create_mask()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 216, in create_mask
    mask2d = create_mask2d(center, param.shape, param.size, nx, ny)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 273, in create_mask2d
    radius = round(float(size+1)/2)  # add 1 because the radius includes the center.
TypeError: cannot concatenate 'str' and 'int' objects

Other command (however, the mask is correctly created):
--------
    slevy/data/criugm/d_sp_pain_pilot2/dmri $ sct_create_mask -i dmri.nii.gz -f box -s 30

Terminal output:
-------
check existence of input files...
  OK: dmri.nii.gz

Input parameters:
  data ..................dmri.nii.gz
  method ................center

Create temporary folder...
mkdir tmp.150119120223/

Copying input data to tmp folder and convert to nii...
cp dmri.nii.gz tmp.150119120223/data.nii.gz
fslchfiletype NIFTI data

Get dimensions of data...
  208 x 42 x 6 x 104
WARNING in sct_create_mask: Input image is 4d but output mask will 3D.
export FSLOUTPUTTYPE=NIFTI; fslroi data data -0 1

Create line...
cp data.nii line.nii
sct_c3d line.nii -scale 0 -o line.nii
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 0
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 1
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 2
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 3
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 4
sct_ImageMath 3 line.nii SetOrGetPixel line.nii 1 104.0 21.0 5

Create mask...
fslmerge -z mask data_mask0 data_mask1 data_mask2 data_mask3 data_mask4 data_mask5 
export FSLOUTPUTTYPE=NIFTI; fslcpgeom data mask

Generate output files...
  File created: /Volumes/users_hd2-3/slevy/data/criugm/d_sp_pain_pilot2/dmri/mask_dmri.nii.gz

Remove temporary files...
rm -rf tmp.150119120223/

ERROR! 
rm: tmp.150119120223/: Directory not empty
Exit program.

Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 335, in <module>
    main()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 87, in main
    create_mask()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_create_mask", line 239, in create_mask
    sct.run('rm -rf '+path_tmp, param.verbose)
  File "/Users/slevy_local/spinalcordtoolbox/scripts/sct_utils.py", line 49, in run
    printv('\nERROR! \n'+output+'\nExit program.\n', 1, 'error')
  File "/Users/slevy_local/spinalcordtoolbox/scripts/sct_utils.py", line 338, in printv
    raise NameError('Error!')
NameError: Error!

**Comment by benjamindeleener** [comment]
Fixed in 5d57ac1dff9b06f6ce1f357b23af860f857ed441
