### ISSUE TITLE
Adjust deepseg_sc (again)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2488]
The recently-merged PR (https://github.com/neuropoly/spinalcordtoolbox/pull/2479), which consisted in finding the optimal threshold per contrast, by minimizing the STD of CSA across contrasts, might not have been the best decision. 

A few issues I noticed after merging this PR:
- Qualitatively, the T2 and MT1_on look under-segmented (see the [QC outputs](https://github.com/neuropoly/spinalcordtoolbox/pull/2479#issue-325498952))
- The sum of the GM and WM CSA compared to the full-cord CSA on the T2 is more consistent with a zero-threshold (78 vs. 74) vs. optimal threshold (61 vs. 76).

I suggest we revert the threshold to zero, until we find a better way to optimize the threshold.

**Comment by jcohenadad** [comment]
OK, after comparing the "old implementation" (before merging #2479, this commit: 4fd8290e341f744047f16483b92a99251709fae7) with the "new implementation" (bbcb7da3c37681033526beb30de20bd25c056782), I noticed that the threshold only has minimum effect on the output segmentation size, and that something else is driving the seg size. See below:

![old](https://user-images.githubusercontent.com/2482071/66784855-9b115980-eea9-11e9-8d33-f7e3fda6b1ed.png)
![new_thr0](https://user-images.githubusercontent.com/2482071/66784856-9ba9f000-eea9-11e9-9a39-12bc3288b8f5.png)
![new_thrOpt](https://user-images.githubusercontent.com/2482071/66784857-9ba9f000-eea9-11e9-90e7-04fb1dc5b8e6.png)

Further investigations needed...

**Comment by charleygros** [comment]
@jcohenadad: I think I found the reason for this issue: the binarisation after resampling.

`master`:
```python
    # Binarize the resampled image (except for soft segmentation, defined by threshold_seg=-1)
    if threshold_seg >= 0:
        logger.info("Binarizing the resampled segmentation...")
        im_seg_r.data = im_seg_r.data.astype(np.uint8)
```

Before #2479:
```python
    # binarize the resampled image to remove interpolation effects
    logger.info("Binarizing the segmentation to avoid interpolation effects...")
    thr = 0.0001 if contrast_type in ['t1', 'dwi'] else 0.5
    # TODO: optimize speed --> np.where is slow
    im_image_res_seg_downsamp.data[np.where(im_image_res_seg_downsamp.data >= thr)] = 1
    im_image_res_seg_downsamp.data[np.where(im_image_res_seg_downsamp.data < thr)] = 0
```

Suggestion of solution:
1. Change the code with:
```python
    # Binarize the resampled image (except for soft segmentation, defined by threshold_seg=-1)
    if threshold_seg >= 0:
        logger.info("Binarizing the resampled segmentation...")
        im_seg_r.data = (im_seg_r.data > 0.5).astype(np.uint8)
```
2. Re run your pipeline to fine-tune the thresholds and update them

**Comment by jcohenadad** [comment]
ah! yes of course! thank you @charleygros. I can work on this, no problem
