### ISSUE TITLE
universal method for extracting centerline using splines based on labels

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#249]
- generate an independent binary based on ITK method for joining points with spline (implemented in propseg)
- call this function within a new python script, that can be called: ''sct_get_centerline"
- add a flag to allow several methods in ''sct_get_centerline''
- add a flag to output real coordinates

**Comment by benjamindeleener** [comment]
try using this method for straighten_spinalcord

**Comment by benjamindeleener** [comment]
NEW approach:
- remove sct_get_centerline
- remove process "get centerline" in sct_process_segmentation
- create a function that takes as input either a full seg, or a seg+labels or only labels, and output a binary centerline and/or a txt file with float coordinates of centerline for each z.
  - this function will use spline interp.

**Comment by benjamindeleener** [comment]
Fixed with sct_get_centerline_from_labels
