### ISSUE TITLE
Cannot run SCT v4.0.2

### ISSUE THREAD

**Issue by Suradech164** [neuropoly/spinalcordtoolbox#2491]
Hello Everyone

I have just installed the lastest SCT version 4.0.2, however, the terminal still processes on the older version 4.0.0 beta. How to fix this? 

Thank you!

**Comment by jcohenadad** [comment]
Have you started a new terminal to initialize environment variables?

**Comment by Suradech164** [comment]
i did.

**Comment by Suradech164** [comment]
I did but and also restarted the mac.  Should I uninstall the older version before reinstalling new one? and how?

Thanks again.

**Comment by jcohenadad** [comment]
What is the output of: `more ~/.bashrc`?

**Comment by jcohenadad** [comment]
closing because no answer from user
