### ISSUE TITLE
Failed installation due to missing gcc on OSX Catalina

### ISSUE THREAD

**Issue by Suradech164** [neuropoly/spinalcordtoolbox#2492]
Hello Everyone,

I have trouble with installing 4.0.2 previously I did install in successfully, however, my SCT still was running the older version 4.0.0 beta 5.  

I have deleted the older sct versions and upgrade catalina IOS and reinstalled sct 4.0.2... however it failed... gcc installation failed as attached below...

Welcome to the SCT installer!

Checking requirements...
WARNING: "gcc" is not installed.
Do you want to install it now? (accepting to install "gcc" will also install "brew" in case it is not installed already)? [y]es/[n]o: y
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Warning: gcc 9.2.0_1 is already installed and up-to-date
To reinstall 9.2.0_1, run `brew reinstall gcc`

ERROR: Installation of "gcc" failed. Please contact SCT team for assistance.

Installation failed

Thank you again.

Hi, thanks for reporting an issue, please take some time to consider the applicable guidelines:
https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#reporting-a-bug-or-requesting-a-feature
(about how to suitably describe issues or requests) prior to deleting this blurb when about to submit the issue.

### Description

<Description of the issue>

### Steps to Reproduce

0. Install SCT <release or git revision and platform, you can use the
   first lines of output of sct_check_dependencies>

1. <First Step>

2. <Second Step>

3. <and so on...>

**Expected behavior:** <What you expect to happen>

**Actual behavior:** <What actually happens>

**Comment by jcohenadad** [comment]
@Suradech164 thank you for reporting this issue. I will need to upgrade to Catalina to be able to reproduce your error, but in the meantime, maybe we can work together and find a quick solution for you.

First of all, can you ran these commands and copy/paste the terminal output:
~~~
gcc
which gcc
ls -la ~/.*rc
sct_check_dependencies
~~~

**Comment by Suradech164** [comment]
Hello Julen

Attached results below:

Ohs-MacBook-Pro sct4.0.2 % gcc
which gcc
git
ls -la ~/.*rc
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/usr/bin/gcc
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status

grow, mark and tweak your common history
   branch    List, create, or delete branches
   commit    Record changes to the repository
   merge     Join two or more development histories together
   rebase    Reapply commits on top of another base tip
   reset     Reset current HEAD to the specified state
   switch    Switch branches
   tag       Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch     Download objects and refs from another repository
   pull      Fetch from and integrate with another repository or a local branch
   push      Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
-rw-r--r--  1 ohlaboratory  staff  1895 19 Oct 13:31 /Users/ohlaboratory/.bashrc
-rw-r--r--  1 ohlaboratory  staff  1424 19 Oct 10:55 /Users/ohlaboratory/.zshrc
ohlaboratory@Ohs-MacBook-Pro sct4.0.2 % sct_check_dependencies
zsh: command not found: sct_check_dependencies
Ohs-MacBook-Pro sct4.0.2 %

**Comment by jcohenadad** [comment]
what is the output of:
~~~
more /Users/ohlaboratory/.bashrc
~~~

**Comment by Suradech164** [comment]
Ohs-MacBook-Pro ~ % more /Users/ohlaboratory/.bashrc

# SPINALCORDTOOLBOX (installed on 2018-01-29 19:24:09)
export PATH=/Users/ohlaboratory/sct_3.1.0/bin:$PATH
#source /Users/ohlaboratory/sct_3.1.0/bin/sct_env


# SPINALCORDTOOLBOX (installed on 2018-01-31 00:28:32)
export PATH=/Users/ohlaboratory/sct/bin:$PATH
#source /Users/ohlaboratory/sct/bin/sct_env


# SPINALCORDTOOLBOX (installed on 2018-01-31 00:57:20)
export PATH=/Users/ohlaboratory/sct/bin:$PATH
#source /Users/ohlaboratory/sct/bin/sct_env


# SPINALCORDTOOLBOX (installed on 2019-03-28 19:09:02)
export PATH=/Users/ohlaboratory/sct/bin:$PATH
#source /Users/ohlaboratory/sct/bin/sct_env


# SPINALCORDTOOLBOX (installed on 2019-03-28 19:13:46)
export PATH=/Users/ohlaboratory/sct_4.0.0-beta.1/bin:$PATH
/Users/ohlaboratory/.bashrc

**Comment by jcohenadad** [comment]
ok, so it looks like we will have to deal with two things: 1) installation of gcc and 2) change your default shell for bash.

First, could you try to install Homebrew by running this command:
~~~
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
~~~

**Comment by Suradech164** [comment]
Thank you so much Julien for you help.

SCT 4.0.2 is working now!

**Comment by jcohenadad** [comment]
I'm glad it is working now, but could you please let me know what you did in order to have it working, so that I can help other users in case they run into the same issue?

**Comment by Suradech164** [comment]
I just installed homebrew that you told me and re-install 4.0.2.

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by jcohenadad** [comment]
@Suradech164 there is still the other issue, which might not be solved, about the wrong shell being run (i.e. your Terminal is looking for an older version of SCT). I just want to make sure that you are running the latest SCT version.

What is the output of:
~~~
sct_check_dependencies
~~~

**Comment by Suradech164** [comment]
oratory@Ohs-MacBook-Pro ~ % sct_check_dependencies


Spinal Cord Toolbox (4.0.2)

SCT info:
- version: 4.0.2
- path: /Users/ohlaboratory/sct_4.0.2
OS: osx (Darwin-19.0.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by SCT: 4
RAM: Primary memory available: 8.00 gigabytes
Check Python executable.............................[OK]
  Using bundled python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] at /Users/ohlaboratory/sct_4.0.2/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.17.3)
Check if cryptography is installed..................[OK] (2.8)
Check if dipy is installed..........................[OK] (1.0.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras is installed.........................[OK] (2.3.1)
Check if matplotlib is installed....................[OK] (3.1.1)
Check if nibabel is installed.......................[OK] (2.5.1)
Check if pandas is installed........................[OK] (0.25.2)
Check if psutil is installed........................[OK] (5.6.3)
Check if pyqt5 is installed.........................[OK]
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.22.0)
Check if scipy is installed.........................[OK] (1.3.1)
Check if scikit-image is installed..................[OK] (0.16.1)
Check if scikit-learn is installed..................[OK] (0.21.3)
Check if tensorflow is installed....................[OK] (2.0.0)
Check if xlrd is installed..........................[OK] (1.2.0)
Check if xlutils is installed.......................[OK]
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.36.1)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3[secure] is installed...............[OK] (1.25.6)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

ohlaboratory@Ohs-MacBook-Pro ~ %

**Comment by jcohenadad** [comment]
@Suradech164 cool! it looks like you are running the correct version. Don't hesitate if you have other issues.

**Comment by Suradech164** [comment]
thank you again for your help and prompt response! I appreciate it.
