### ISSUE TITLE
Freeze Python libraries for a given SCT version to ensure reproducibility of a previous version

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2496]
We should fix library versions in the file `requirements.txt` to make sure that one can reproduce previous SCT installations.

However, the development version should use the latest libraries (to make sure we are always up-to-date with Python's libraries).

To do this with minimum maintenance, we should find a way to automatically modify the `requirements.txt` file when preparing a new release. I'm sure good solutions exist out there...

**Comment by lrouhier** [comment]
There is a way to get a list with the version of every package in a virtual environment (pip freeze> requirements.txt) Is it a solution to have two  (one for dev and one for releases) requirements files?

**Comment by jcohenadad** [comment]
Having two requirements.txt file would indeed be a convenient solution. During install, we can check if source code is from package or from git, and choose the correct requirements.

**Comment by lrouhier** [comment]
the pip freeze command gives an output that looks like this (just a small extract) 

~~~

(base) marsalis:sct lurou_admin$ pip freeze >test.txt
(base) marsalis:sct lurou_admin$ cat test.txt
absl-py==0.7.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.6
anaconda-project==0.8.2
appnope==0.1.0
appscript==1.0.1
asn1crypto==0.24.0

~~~~~~

**Comment by jcohenadad** [comment]
the proposed workflow is:
- checkout release branch
- pip freeze
- update requirements.txt
- push
- confirm Travis passes
- publish release
