### ISSUE TITLE
sct_image -copy-header does not consider flag -o

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2505]
This is confusing behaviour and should be clarified. Maybe force new output if -o is used.

**Comment by jcohenadad** [comment]
note: this is an old issue, maybe it has been resolved since

**Comment by Drulex** [comment]
Current usage:
```
[...]

OPTIONAL ARGUMENTS:
  -h, --help            Show this help message and exit
  -o <file>             Output file. Example: data_pad.nii.gz

[...]

HEADER OPERATIONS:
  -copy-header <file>   Copy the header of the source image (specified in -i) to the destination image (specified here). Example: data_dest.nii.gz

[...]
```
Based on the usage above `-copy-header <file>` takes its own file parameter, thus the `-o` parameter is ignored. This is a sane behavior in my opinion considering that `-o` is optional.

This is part of a bigger problem that I noticed a lot in the codebase: the CLI interface is non-standard. There are 2 ways to approach this:
1. If `-o` is not compatible with `-copy-header`, then they should be in a mutually exclusive group in the parser which would prevent the user from combining the options.
2. `-copy-header` should be a `store_true` option as opposed to a `store` option and it should check that `-o` is provided and use that as output file.

I propose to go with 2.

**Comment by jcohenadad** [comment]
> I propose to go with 2.

+1
