### ISSUE TITLE
Enable spinal-level-based registration to the PAM50

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2509]
In projects where spinal (not vertebral) levels are known (example [here](https://github.com/sct-pipeline/exvivo-template/issues/1)), it would be desirable to have the option to register these data to the PAM50, which already has a spinal level atlas. 

A suggestion for implementation includes (based on @charleygros's ideas):
- For each PAM50/spinal_levels/spinal_levels_*.nii.gz, compute the center of mass of the distribution.
- Generate a single nifti file (could be called `PAM50_spinal_levels.nii.gz`) and create a voxel for each of the identified spinal level center of mass. The value of the level will be: 2 for spinal level 2, etc.
- Update the `PAM50` package to include this new file, upload to OSF+neuropoly website and update `sct_download_data` with the new URLs
- Refactor `sct_register_to_template` to add a new flag `-lspinal`, which will point to the file `PAM50_spinal_levels.nii.gz` for doing a z-based non-linear registration of spinal levels between the source and the dest (PAM50) images (step=0 of the algo).

**Comment by charleygros** [comment]
Fixed with #2513 .
