### ISSUE TITLE
sct_run_batch: crashes when pointing to non-local parameters or script 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2517]
When calling for example this:
~~~
sct_run_batch /users/bob/parameters.sh myscript.sh
~~~
the function would crash (error message saying that the file parameters cannot be found), whereas copying the file locally and running this:
~~~
sct_run_batch parameters.sh myscript.sh
~~~
works fine.

So there is something to fix in the way input path are handled in this script.

**Comment by valosekj** [comment]
I tried to solve it in #2518
