### ISSUE TITLE
Creation of extra points when using sct_straighten_spinalcord on disc label files

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2519]
### Description
When using sct_straighten_spinal cord on disc label files, the resulting image has a non-zero background as well as some points appearing around the correct label.
![Screen Shot 2019-11-11 at 9 58 04 AM](https://user-images.githubusercontent.com/22171999/68596799-d3d12e00-0469-11ea-8eff-01135b7590b4.png)
### Steps to Reproduce

0. Install SCT Spinal Cord Toolbox (git-master-8e790d825d9124cc80fd819c669e904f3c1d70b8)-MAC OSX Mojave

1. run sct_straighten_spinalcord -i labels_disc_all_posterior_order_r.nii.gz -s t2_seg_manual.nii.gz

**Expected behavior:** I expected the label to be cleanly translated. 

**Actual behavior:**  Some point appears next to what seems to be the correct label. The value of the label are changed as well. 

(data is located in Duke: /projects/ivado-medical-imaging/lucas_vertebral_labeling/20191111-issue/)

**Comment by lrouhier** [comment]
During an earlier discussion, an existing SCT function to retrieve the label was mentioned. If I'm not mistaken it is the function cubic_to_point located in sct_label_utils.py?

**Comment by charleygros** [comment]
> During an earlier discussion, an existing SCT function to retrieve the label was mentioned. If I'm not mistaken it is the function cubic_to_point located in sct_label_utils.py?

I think so too :+1:

**Comment by jcohenadad** [comment]
For the sake of clarity, I would separate the generation of straightening warping field and its application. So, it would be something like:
~~~
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg_manual.nii.gz
sct_apply_transfo -i labels_disc_all_posterior_order_r.nii.gz -d t2_straight.nii.gz -w warp_curve2straight.nii.gz -x label
~~~

Now, you notice the flag `-x label` which currently does not exist. We should implement it, as it would be useful at many places in SCT's code. How to implement it? I see two approaches:

Approach 1 (easier to implement):
- Extract coordinates of each label (using center of mass) as an int (`cubic_to_point()` can do that)
- Dilate (e.g. by 3x3x3)
- Apply sct_apply_transfo using nearest neighbor
- Extract discrete coordinates on the warped dilated labels
- save file

Approach 2 (more elegant):
- Extract coordinates of each label (using center of mass) as a float value
- Open warping field and extract vector fields in XYZ directions
- Apply translation of each label within Python (done in float)
- Round to get discrete coordinate
- save warped label file
 
Depending on your motivation, i let you choose the one you'd like to implement ;-)

**Comment by lrouhier** [comment]
I will look into it.

**Comment by jcohenadad** [comment]
@lrouhier if you go for approach 2, have a look at the method `msct_register.generate_warping_field()`. It is basically the same as what you want to do (but the other way around).

**Comment by lrouhier** [comment]
For approach 2: After investigation on the way the warping field is created, the displacement of each point is calculated within the destination space. However, to transfer points from the curve space to the straight space we will need to have the information on this transformation. 
I am currently looking for it. If I don't find it I will look at the first approach that you mentioned.

**Comment by jcohenadad** [comment]
> For approach 2: After investigation on the way the warping field is created, the displacement of each point is calculated within the destination space. However, to transfer points from the curve space to the straight space we will need to have the information on this transformation.

well, wether you go with approach 1 or 2, you will need the matrix+header of the destination space (straight) anyway, so i'm not sure i understand your limitation?

**Comment by lrouhier** [comment]
If I understood correctly the way ANTs is working this is what happens for each points :
* each point undergoes a first transformation to convert the coordinates from the original space to the destination space. (A → B) (step 1)
* B is then displaced by a certain vector. This vector is stored in the Matrix of the warping field at B's coordinates. (step 2)
This is what I am trying to replicate in the second approach. Even though step 2 is pretty straightforward, it is relying on step 1 which is what I am having a hard time figuring out. 

I am investigating how to reproduce step 1. I need to find the transformation that gives the correspondence between a point in the original space and a point in the destination space.
To give an example: points with coordinates 25,133,161 can't exist within a 50x71x206 image. However, it is in the safe zone define in straightening.py and should appear on the transformed image and should have a corresponding displacement within the destination space. 
 
This transformation and the way it i can find it with the warping field is what I fail to understand right now. This is what limits me. (step 1 is the same as shown on the code below)https://github.com/neuropoly/spinalcordtoolbox/blob/37729b0376f4394a9cb0e0dd0c075b1343fe015d/spinalcordtoolbox/straightening.py#L440-L455


For the first approach : 
step 1 and step 2 are performed by sct_apply_transfo (i don't need to find this transformation), I just need to work on the resulting image.

**Comment by jcohenadad** [comment]
I see. Coincidentally I’m currently struggling with the rigid transformation that you describe at step 1, in another issue https://github.com/neuropoly/spinalcordtoolbox/issues/2525.

One thing you can try to do, is compute the dot product between the src and dest qform (get_best_affine() from nibabel object that you get from img.hdr), and apply it to your src coordinate before applying the displacement vector (step 2). But I’m still struggling with that part ;-)

**Comment by lrouhier** [comment]
first approach with a basic implementation seems to work. I added a -label flag taking 0 or 1 as arguments. the workflow is the following:
*1 :retrieves present labels value (needed in step 6)
*2 :applying convolution filter to dilate label to 2x2x2
*3 :apply wrapping field to the image (sct_apply_transfo -i label.nii.gz -d straight_ref.nii.gz -w warp_curve2straight.nii.gz -x spline -label 1)
*4: retrieve existing points by looking at local maxima (which eliminates some of the points)
*5: group them by proximity to one another and get the coordinates of the center of mass.
*6: label this point from higher coordinates on the I-S axis to the lower with the value retrieved in label.nii.gz
Explanations :
The values of the points are changed when the transformation is applied. The background is not made of zero pixels (it is close however ). 

They also can be too close to one another to group them by value which what cubic_to_point is doing. I am afraid it will throw off the center of mass approximation in some cases.
 (e.g., points near label eleven can be close to 10.5 as can points close to label 10).
![Screen Shot 2019-11-21 at 9 06 53 AM](https://user-images.githubusercontent.com/22171999/69346944-a93d5d00-0c41-11ea-9096-e8844c679a9b.png)
![Screen Shot 2019-11-21 at 9 07 08 AM](https://user-images.githubusercontent.com/22171999/69346945-a9d5f380-0c41-11ea-9426-7c41955aebec.png)

The local maxima (skimage.feature.peak_local_max function) with an abs threshold of 0.1 seems to work.
Step 6 is needed regarding what I have observed with the changes in label value.

**Comment by jcohenadad** [comment]
- convolution: use sct_maths
- interp: use NN

**Comment by lrouhier** [comment]
That's done and seems to work perfectly. One question though: should we force the 'nn' interpolation with the -label flag?

**Comment by jcohenadad** [comment]
> That's done and seems to work perfectly. One question though: should we force the 'nn' interpolation with the -label flag?

excellent point (pun not intended)
