### ISSUE TITLE
test should have failed when file was added by mistake into /data/atlas

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#254]
see commit "matlab" from 2015-02-11

**Comment by jcohenadad** [comment]
the reason is that the atlas testing data are not generated by the test-- they should be.

**Comment by benjamindeleener** [comment]
in sct_extract_metric, only read the labels from the file info_labels, and NEVER use "ls".
also, in sct_warp_template, only warp the files that are listed in info_labels.

**Comment by slevyrosetti** [comment]
Fixed and tested on branch sl_extract_metric in commit #384173d.
