### ISSUE TITLE
index error when using set_label_vertebrae and sct_register_to_template

### ISSUE THREAD

**Issue by matthieufaillot** [neuropoly/spinalcordtoolbox#2561]
Hello

I have issues in using SCT first steps : 
I was able to successfully segment the spinal cord with deepseg but I am unable to run further steps that is _label vertebrae_ and _register to template_.
SCT 4.2.0 is running under macOS 10.14.6 2,6 GHz i7 16 Go RAM
Below are the error messages. They occurred for two patients, no effect of acquisition plane (T2 DRIVE sequences acquired in axial vs sagittal).
Thank you for your help
I apologize in advance if my question is irrelevant (I am new to using SCT and not really confident in using terminal) 
Matthieu

`sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc "$SCT_BP_QC_FOLDER"`

> Spinal Cord Toolbox (4.2.0)
> 
> Traceback (most recent call last):
>   File "/Users/faillot/sct_4.2.0/scripts/sct_label_vertebrae.py", line 427, in <module>
>     main()
>   File "/Users/faillot/sct_4.2.0/scripts/sct_label_vertebrae.py", line 189, in main
>     arguments = parser.parse(args)
>   File "/Users/faillot/sct_4.2.0/scripts/msct_parser.py", line 356, in parse
>     if arguments[index][0] == '-':
> IndexError: string index out of range

` sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l labels_vert.nii.gz -c t2 -qc "$SCT_BP_QC_FOLDER"`
> Spinal Cord Toolbox (4.2.0)
> 
> Traceback (most recent call last):
>   File "/Users/faillot/sct_4.2.0/scripts/sct_register_to_template.py", line 807, in <module>
>     main()
>   File "/Users/faillot/sct_4.2.0/scripts/sct_register_to_template.py", line 210, in main
>     arguments = parser.parse(args)
>   File "/Users/faillot/sct_4.2.0/scripts/msct_parser.py", line 356, in parse
>     if arguments[index][0] == '-':
> IndexError: string index out of range

**Comment by jcohenadad** [comment]
Hi @matthieufaillot did you copy/paste the syntax from the pdf course? If so, there might be issues with the formatting. Please try to copy/paste from the batch_processing.sh file instead.

**Comment by matthieufaillot** [comment]
Hi @jcohenadad 
thank you for your answer
No I copied from the batch_processing.sh opened with Xcode
ps  : I forgot to mention but the segmentation with deepseg worked fine

**Comment by jcohenadad** [comment]
What is you omit ~~~  -qc "$SCT_BP_QC_FOLDER"~~~

**Comment by matthieufaillot** [comment]
thank you!
I was able to run sct_label_vertebrae for two patients (but it seems I still have to work on  the labeling with manual steps...)

**Comment by jcohenadad** [comment]
ok, so your variable `SCT_BP_QC_FOLDER` likely had some issues. Make sure the variable is declared at the beginning of your script.
