### ISSUE TITLE
Illegal instruction when importing Keras/Tensorflow with CPU not supporting AVX

### ISSUE THREAD

**Issue by zgm0407** [neuropoly/spinalcordtoolbox#2562]
I run  sct_check_dependencies after launch sct_4.0.0 on Win10's docker DeskTop, it seemed something wrong. how can I resolve the problem?
### Description

~~~
sct@35acfd3d29fa:~/sct_4.0.0/bin$  sct_check_dependencies

--
Spinal Cord Toolbox (4.0.0)

SCT info:
- version: 4.0.0
- path: /home/sct/sct_4.0.0
OS: linux (Linux-4.9.184-linuxkit-x86_64-with-debian-buster-sid)
CPU cores: Available: 2, Used by SCT: 2
RAM: MemTotal:        2047012 kB
total        used        free      shared  buff/cache   available
Mem:           1999         348         167           0        1482        1465
Swap:          1023           2        1021
Check Python executable.............................[OK]
  Using bundled python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] at /home/sct/sct_4.0.0/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.17.0)
Check if cryptography is installed..................[OK] (2.7)
Check if dipy is installed..........................[OK] (0.16.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.9.0)
Check if Keras is installed.........................Illegal instruction
sct@35acfd3d29fa:~/sct_4.0.0/bin$
~~~

**Comment by jcohenadad** [comment]
Hi,
There might be incompatibilities with your CPU. Some info here:
- https://github.com/tensorflow/tensorflow/issues/17411
- https://github.com/keras-team/keras/issues/9630
- https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/

What is your hardware configuration (CPU type)?

Before digging too extensively, could you please try the following:
- Install SCT via virtual machine (instructions [here](https://github.com/neuropoly/spinalcordtoolbox#installation-in-virtual-machine-vm))
- Use another computer (to see if your issue is computer-specific)

**Comment by zgm0407** [comment]
I tried install SCT via virtual machine, but failed again.
SCT info:
- version: 4.2.0
- path: /home/brain/sct_4.2.0
OS: linux (Linux-3.16.0-4-amd64-x86_64-with-debian-8.0)
CPU cores: Available: 1, Used by SCT: 1
RAM: MemTotal:        4059052 kB
total       used       free     shared    buffers     cached
Mem:          3963       2748       1215         11         76       2350
-/+ buffers/cache:        320       3643
Swap:         1951          0       1951
Check Python executable.............................[OK]
  Using bundled python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] at /home/brain/sct_4.2.0/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.17.4)
Check if cryptography is installed..................[OK] (2.8)
Check if dipy is installed..........................[OK] (1.0.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras is installed........................../install_sct: line 680:  1647 Illegal instruction     sct_check_dependencies

Installation validation Failed!

Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum (create a new discussion):

http://forum.spinalcordmri.org/c/sct


Installation failed

brain@neurodebian:~/spinalcordtoolbox-4.2.0$

**Comment by zgm0407** [comment]
I tried install SCT via virtual machine, but failed again.
SCT info:
- version: 4.2.0
- path: /home/brain/sct_4.2.0
OS: linux (Linux-3.16.0-4-amd64-x86_64-with-debian-8.0)
CPU cores: Available: 1, Used by SCT: 1
RAM: MemTotal:        4059052 kB
total       used       free     shared    buffers     cached
Mem:          3963       2748       1215         11         76       2350
-/+ buffers/cache:        320       3643
Swap:         1951          0       1951
Check Python executable.............................[OK]
  Using bundled python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] at /home/brain/sct_4.2.0/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.17.4)
Check if cryptography is installed..................[OK] (2.8)
Check if dipy is installed..........................[OK] (1.0.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras is installed........................../install_sct: line 680:  1647 Illegal instruction     sct_check_dependencies

Installation validation Failed!

Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum (create a new discussion):

http://forum.spinalcordmri.org/c/sct


Installation failed

brain@neurodebian:~/spinalcordtoolbox-4.2.0$

**Comment by jcohenadad** [comment]
@zgm0407 likely related to [this issue](http://forum.spinalcordmri.org/t/unable-to-install-sct-due-to-tensorflow-fail/98/6). 

It is possible that your CPU version does not support AVX, which is used by TF v1.5 and higher, as explained [here](https://stackoverflow.com/questions/49092527/illegal-instructioncore-dumped-tensorflow).

Could you please try to downgrade to TF 1.5 to see if it works? Please run the following in your virtual machine environment (and then copy/paste your entire Terminal output):
~~~
source ${SCT_DIR}/python/etc/profile.d/conda.sh
conda activate venv_sct
python -c "import tensorflow as tf; print(tf.__version__)"
yes | pip uninstall tensorflow
pip install tensorflow==1.5
python -c "import tensorflow as tf; print(tf.__version__)"
~~~

**Comment by jcohenadad** [comment]
It would be nice to check if CPU supports AVX before installing SCT

**Comment by bcdarwin** [comment]
Maybe either depend on https://github.com/workhorsy/py-cpuinfo, which uses no command-line programs which might not be installed or other Python libraries, or read the code there to find out how to get OSX (/Windows) CPU info.

**Comment by jcohenadad** [comment]
right, the only thing is that ideally, we would do the check __before__ installing Python+SCT, as done [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/install_sct#L164). 

On the other hand, doing it in Python would be easier/cleaner.

**Comment by bcdarwin** [comment]
I guess there are three options:

- check using 'cat /proc/cpuinfo | grep ... ' on Linux and the equivalent on OSX at the beginning of the installer;
- check using py-cpuinfo as soon as conda is available and possibly exit from the installer with an error (a bit messy)
- check in `sct_check_dependencies` by detecting the Keras segfault and/or detecting AVX with Python

**Comment by jcohenadad** [comment]
ok, i think we should go for the 3rd one. The pros are:
- no refactoring of the install shell script (less friendly to read than python code)
- no need to deal with platform-dependent CPU-check functions
- users' report is centralized in the `sct_check_dependencies` (easier for us to assist users if all the info is spitted out from this script)

the only cons i see is:
- adds 1-2 minutes on the user side (has to wait for the install to complete)

**Comment by jcohenadad** [comment]
@zgm0407,

I'm following up on the issue you had while installing SCT, you experienced an `ERROR: Illegal instruction     (core dumped)` related to the incompatibility with Keras/Tensoflow. 

We have solved that issue in a pre-release, and we would like to ask users who have experienced that issue to make sure this solution works in most cases. 

Could you please go back to the computer that produced that error, and try the following (copy/paste the Terminal output):
```bash
git clone --branch=jca/2562-tensorflow-1.5 --depth=1 https://github.com/neuropoly/spinalcordtoolbox.git sct-tf1.5
cd sct-tf1.5/
yes | ./install_sct
```
Open a new Terminal and run (send us this terminal output if at least one test fails):
```bash
sct_testing
```

Thanks!

**Comment by ms-elphi** [comment]
Inside conda virtual env
first installed keras-application using pip
then install tensorflow again.
(downgrade not required)
it worked for me
