### ISSUE TITLE
Review of course material : permission denied on qc

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2573]
System: OSX Catalina
version: git-master-846d5d1bf50fe37d602b99b142a0c3032492e566

*Error*
After running 
`sct_propseg -i t2.nii.gz -c t2 -qc ~/qc_singleSubj`
the command to open the QC does not work (permission denied error)
~~~
(base) marsalis:t2 lurou_admin$ $open_cmd ~/qc_singleSubj/index.html
-bash: /Users/lurou_admin/qc_singleSubj/index.html: Permission denied
~~~

*suggestion* 
`open ~/qc_singleSubj/index.html` seems to work for me. Should we change it or is this error specific to my station ?

**Comment by jcohenadad** [comment]
what is the output of:
~~~
$open_cmd
~~~

if it is empty, it means you haven't followed the course properly ;-)     see page 25

**Comment by lrouhier** [comment]
Yep that was it ! Sorry about that ! I forgot the last command of page 25 !
