### ISSUE TITLE
Problem using open on Ubuntu

### ISSUE THREAD

**Issue by olix86** [neuropoly/spinalcordtoolbox#2574]
p.27 of sct course London

On a fresh ubuntu 18.04, running `open batch_single_subject.sh` doesn't work and returns 
`Couldn't get a file descriptor referring to the console`

Using `xdg-open` instead of `open` works and opens the file in the text editor

Edit : 

Looks like open is macOS specific : [link](https://unix.stackexchange.com/questions/253376/open-command-to-open-a-file-in-an-application)

**Comment by olix86** [comment]
Same using `xopen` at p.66

**Comment by jcohenadad** [comment]
thanks @olix86. Yes, this is the purpose of page 25 of the course material: define the generic `$open_cmd` command to accommodate both Linux and OSX. However, this is a bit cumbersome, so when convenient, I will simply remove the "open" command so people will double click on the file via their OS GUI instead (or they can use the Terminal command if they are familiar with it).
