### ISSUE TITLE
Manual C2-C3 identification : out of bound error

### ISSUE THREAD

**Issue by olix86** [neuropoly/spinalcordtoolbox#2576]
p.56 -> 

When navigating the slices (left/right arrows) to identify manually C2-C3, the viewer crashes with an out of bound error :

```
sct_label_utils -i t2.nii.gz -create-viewer 3 -o label_c2c3.nii.gz -msg "Click at the posterior tip of C2/C3 inter-vertebral disc"

--
Spinal Cord Toolbox (git-master-846d5d1bf50fe37d602b99b142a0c3032492e566)

Traceback (most recent call last):
  File "/home/olix86/sct/spinalcordtoolbox/gui/sagittal.py", line 89, in increment_vertical_nav
    self.sagittal.refresh()
  File "/home/olix86/sct/spinalcordtoolbox/gui/widgets.py", line 296, in refresh
    data = self._image.data[:, :, self._z]
IndexError: index 64 is out of bounds for axis 2 with size 64
Aborted (core dumped)
```

**Comment by lrouhier** [comment]
I think it comes from the fact that you've reached the edge of the 3D volume. 
One fix, if possible, would be to show which slice you are seeing and the max number you can go up to.

**Comment by olix86** [comment]
Yep the ideal would be to not be able to go out of bounds, but if that's not possible due to the viewer, displaying `x out of y slices` would be an alternative

**Comment by jcohenadad** [comment]
> the ideal would be to not be able to go out of bounds

that's definitely the way to go. Fairly easy to implement: just add a case [here](https://github.com/neuropoly/spinalcordtoolbox/blob/846d5d1bf50fe37d602b99b142a0c3032492e566/spinalcordtoolbox/gui/sagittal.py#L86). Anyone willing to take on that case is welcome to :-)
