### ISSUE TITLE
QC open command should be hidden if users don't have access to local browser

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2585]
For users running SCT under Docker in Windows via Xming, when launching a process with the flag `-qc`, the command will output a syntax to open this html report, using the default Linux program: `xdg-open`. The problem is that, even though the program is installed, it cannot find a default browser because there is no browser installed in the SCT Docker container, yielding the following error: 

~~~
$open_cmd index.html
Couldn't find a suitable web browser!
Set the BROWSER environment variable to your desired browser.
Warning: program returned non-zero exit code #1
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'index.html'
~~~

One solution would be to look interrogate the variable `BROWSER`, and if not defined, change the message for "Double click on the file: PATH/index.html"

**Comment by lrouhier** [comment]
I have implemented it in Branch lr/extra_test_for_docker. However, after installing a web browser on the docker, the variable BROWSER does not appear to be automatically set which could be a problem for Linux users... 
In any case, xdg-open won't work if the variable is not set.

**Comment by jcohenadad** [comment]
ok so let's drop this minor issue for now...

**Comment by jcohenadad** [comment]
reopening it because of https://github.com/neuropoly/spinalcordtoolbox/pull/2589
