### ISSUE TITLE
ValueError: operands could not be broadcast together with remapped shapes

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2596]
### Description

This error message has been [reported by a user](http://forum.spinalcordmri.org/t/operands-could-not-be-broadcast-together) when trying to run a segmentation.

### Steps to Reproduce

version: SCT v4.2.1
data: sct_testing/large: sub-issue2596_T1w.nii.gz
syntax + error:
~~~
sct_deepseg_sc -i sub-issue2596_T1w.nii.gz -c t1 -brain 1 -centerline cnn -r 0

--
Spinal Cord Toolbox (git-master-ca93f233e4647942e6c9982d5b794ac7854d3acc)

Config deepseg_sc:
  Centerline algorithm: cnn
  Brain in image: True
  Kernel dimension: 2d
  Contrast: t1
  Threshold: 0.15

Create temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20200207155635.173378-sfv3_fok)...
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
WARNING: To avoid intensity overflow due to convertion to uint8, intensity will be rescaled to the maximum quantization scale.
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 205, in <module>
    main()
  File "/Users/julien/code/sct/scripts/sct_deepseg_sc.py", line 189, in main
    threshold_seg=threshold, remove_temp_files=remove_temp_files, verbose=verbose)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/core.py", line 477, in deep_segmentation_spinalcord
    centerline_fname=file_ctr)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/core.py", line 97, in find_centerline
    brain_bool=brain_bool)
  File "/Users/julien/code/sct/spinalcordtoolbox/deepseg_sc/core.py", line 252, in heatmap
    data_im = np.pad(data_im, ((0, x_pad), (0, 0), (0, 0)), 'constant')
  File "<__array_function__ internals>", line 6, in pad
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 741, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 516, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 127, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2) and requested shape (4,2)
~~~

**Comment by charleygros** [comment]
I am able to reproduce this issue as well as #2597. I am investigating. Will keep you posted.

**Comment by charleygros** [comment]
Note: the following command (ie `-centerline svm`) does not work too.

```
sct_deepseg_sc -i sub-issue2596_T1w.nii.gz -c t1 -r 0
```

```
--
Spinal Cord Toolbox (git-cg/i2596-d96e1e6f7c3db945ff1b1557a50a667349218007)

Config deepseg_sc:
  Centerline algorithm: svm
  Brain in image: True
  Kernel dimension: 2d
  Contrast: t1
  Threshold: 0.15

Create temporary folder (/tmp/sct-20200210143320.040402-ivz_lj16)...
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
Remove temporary files...
rm -rf /tmp/sct-20200210143357.272870-iqmz1pmc
Cropping the image around the spinal cord...
Traceback (most recent call last):
  File "/home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 205, in <module>
    main()
  File "/home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 189, in main
    threshold_seg=threshold, remove_temp_files=remove_temp_files, verbose=verbose)
  File "/home/charley/spinalcordtoolbox/spinalcordtoolbox/deepseg_sc/core.py", line 488, in deep_segmentation_spinalcord
    crop_size=crop_size)
  File "/home/charley/spinalcordtoolbox/spinalcordtoolbox/deepseg_sc/core.py", line 175, in crop_image_around_centerline
    x_shape, y_shape = data_in[x_start:x_end, y_start:y_end, zz].shape
ValueError: too many values to unpack (expected 2)
```

**Comment by charleygros** [comment]
Potential source of bug: the input image (check [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/core.py#L458)) is 4D: `(352, 480, 256, 1)`.

**Comment by charleygros** [comment]
To split the data (`sct_image -split t`) before sending it to `sct_deepseg_sc` solves the issue (the automatic results are not satisfying though, neither with `svm` nor `cnn`, but okay with `viewer`).

@jcohenadad : I am not sure of the best way to go: if we detect a 4D image as input of the function, do we want:
- to stop the process, ask the user to send a 3D image, suggest the use of `sct_image -split t`.
- OR to split the data, take the first 3D array (along t), run process, re-construct the 4D image at the end of the function.

**Comment by jcohenadad** [comment]
I would go with the first approach. This NIFTI file is obviously corrupted (dim0=4 and dim4=1, which is inconsistent), so we should let the user know that he has to fix his pipeline before using SCT (or any other software). I would do the following:
- Do the check at this line: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg_sc.py#L179
- Call `sct_utils.check_if_3d()`
- Modify `check_if_3d()` because currently, it only checks if dim4=1, which in this case would wrongly come up as a "3D data". So, we should:
  - make the test more sensitive by testing for `dim0=3`
  - printout the image dimension in case the test fails, so users can copy/paste their output and it will be easier for us to debug/instruct.

**Comment by charleygros** [comment]
Sounds great!
The only thing I can think of: The function is robust to 1-slice images --> It would be good to keep this feature, ie not be rejected by `check_if_3d()`.
When I split a 3D image with `sct_image -split` --> the output still has `dim0=3` --> Just wondering if it will always be the case!? or if we want to accept `dim0=2` as well!?

**Comment by jcohenadad** [comment]
> if we want to accept dim0=2 as well!?

yes we want 😊
