### ISSUE TITLE
Update parameter_template.sh in shell/

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2609]
To look like this one:
https://github.com/sct-pipeline/spine-generic/blob/master/processing/parameters_template.sh

To "force" users to copy parameters.sh in their working directory

**Comment by cfhammill** [comment]
This shouldn't be necessary given https://github.com/neuropoly/spinalcordtoolbox/pull/2658

**Comment by jcohenadad** [comment]
@cfhammill you could add "fixes #2609" in your PR
