### ISSUE TITLE
sct_run_batch: add flag to decide to use GNU parallel (or not)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2610]

**Comment by PaulBautin** [comment]
Hi,
I'm new to the project. This would be my first contribution, just want to check if this is the right process. I have added a flag to sct_run_batch but have left it optional. Should I change the information to encourage the utilisation of this option?

**Comment by jcohenadad** [comment]
Thanks a lot for your contribution @PaulBautin!
Please open a pull request so we can discuss/merge your changes to the master branch. More info on the [contribution guidelines](https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#contributing-to-sct-pull-request)
