### ISSUE TITLE
Check data type before running morphological operation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2611]
To output a clearer message to the user. 

See: http://forum.spinalcordmri.org/t/problem-with-latest-version-installation/311/25?u=jcohenadad

**Comment by jcohenadad** [comment]
I've just realized that we are actually using `grey_erosion`, which __does__ accept non-binary data.

**Comment by PaulBautin** [comment]
@jcohenadad, I see you've corrected the "typeError" in convert_list_str(). I've only added a correction to the help instruction (greyscale or binary image). Should I do a pull request for such a little modification.

**Comment by jcohenadad** [comment]
> @jcohenadad, I see you've corrected the "typeError" in convert_list_str(). 

it would be helpful if you could add a bit of context: when did i correct it? pls add a hyperlink to the modification you are referring to

I've only added a correction to the help instruction (greyscale or binary image). Should I do a pull request for such a little modification.

every modification to master requires a PR. That being said, there is currently a PR dealing with `sct_maths` #2616 so you might want to simply push on the working branch
