### ISSUE TITLE
Parser error generation broken in `sct_image`

### ISSUE THREAD

**Issue by cfhammill** [neuropoly/spinalcordtoolbox#2620]
In, for example, `sct_image -mcs` the script checks that there are in fact multiple input files. 

https://github.com/neuropoly/spinalcordtoolbox/blob/jca/fsl-warp/scripts/sct_image.py#L227

triggering this with

```bash
sct_image -i t2.nii.gz -mcs
```

Throws the following error

```
--
Spinal Cord Toolbox (git-HEAD-4826d21b59e2abe9cc35a3e63e37d25f9f2b332f*)

Traceback (most recent call last):
  File "/home/chammill/Documents/spinalcordtoolbox/scripts/sct_image.py", line 684, in <module>
    main()
  File "/home/chammill/Documents/spinalcordtoolbox/scripts/sct_image.py", line 232, in main
    sct.printv(parser.usage.generate(error='ERROR: -mcs input need to be a multi-component image'))
AttributeError: 'NoneType' object has no attribute 'generate'
```

with 4826d21

I think this is a trivial switch from

```python
parser.usage.generate(error="
```

to

```python
parser.error("
```

which generates error messages and prints the usage.

If anyone can reproduce, I'll `grep` the scripts directory for instances of this pattern and replace them with the new version.

**Comment by jcohenadad** [comment]
I can reproduce with d8d887c155dec9450da37a5ee4f02de3cf6cdca5. Thank you for reporting this bug @cfhammill 👍 

And yes, I agree about the proposed solution.

**Comment by cfhammill** [comment]
Great, thanks @jcohenadad
