### ISSUE TITLE
Centralize deep-learning segmentation tools into a single entry point and module

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2626]
Currently, deep learning tools include `sct_deepseg_sc`, `sct_deepseg_lesion` and `sct_deepseg_gm`. Each have their entry point (i.e. CLI function) and some of the modules are not shared (e.g., deepseg_gm and deepseg_sc use different modules for preprocessing and running the segmentation). 

Given the increasing need to (i) train models specific to other structures (e.g., CSF #2277, [mouse spinal cord](http://forum.spinalcordmri.org/t/segmetation-centerline-errors/352)), (ii) switch to Pytorch #2305 and (iii) centralize the code for easier maintenance, it would be nice to start implementing a prototype.

A suggestion would be to create a CLI called `sct_deepseg`, which would take an argument to point to the model, e.g., `-m {csf, cord, graymatter, mouse-t1}`.

A possibility would be to get rid of `-c`, if users specify the contrast directly in the model name, e.g. `-m cord-t2`

**Comment by olix86** [comment]
What about something like 
```
sct_deepseg lesion -i input_file <arguments specific to deepseg_lesion>
```

This could be done using [subparsers ](https://docs.python.org/3/library/argparse.html#sub-commands) since they share some arguments  but other arguments are unique to each command, which would be tricky to handle with a single parser

**Comment by jcohenadad** [comment]
@olix86 yes, good idea. How about the strategy to target models? e.g., there could be various "lesion" models. Or were you thinking of specifying the lesion model inside `<arguments specific to deepseg_lesion>`?

**Comment by olix86** [comment]
> Or were you thinking of specifying the lesion model inside <arguments specific to deepseg_lesion>?

Yes, I think that's how it's currently done in `deepseg_gm` which has multiple models, we could keep it that way since models will probably be task specific

**Comment by charleygros** [comment]
That would be great indeed!

I am simply hesitant at this stage because the implementation of `sct_deepseg_sc` & `sct_deepseg_lesion` is currently very different of `sct_deepseg_gm`, eg centerline detection vs no centerline detection, crop vs no crop, parameters very different between functions, different preprocessing, different postprocessing etc.

When I go through the code, I can't see much code that could be easily shared at this point.

This could be largely improved / easier when we will move the recent developments of IVADOmed to SCT since the overall pipeline of IVADOmed is similar to `sct_deepseg_gm` --> which would allow us to unify the `_gm`, `_sc`, `_lesion` more easily at that moment.

**Comment by charleygros** [comment]
Also, what about `sct_propseg` --> do we want to include it via something like:
```
sct_seg sc -i input_file -m propseg
```

**Comment by jcohenadad** [comment]
@charleygros i completely forgot to specify the most important aspect in the description above, but the **main** purpose of this refactoring is to actually bring the ivadomed code into production. 

So, this `sct_deepseg` would be a prototype version of what we discussed at the last ivadomed meeting. I wasn't planning on directly following deepseg_sc or deepseg_gm, but starting "from scratch" a new CLI, that would call ivadomed modules. Of course we should borrow what's already existing in deepseg_sc/gm, but let's start thinking of an algorithm that could accommodate all the different scenario (cropping, centerline detection, etc.). 

> Also, what about sct_propseg --> do we want to include it via something like:
sct_seg sc -i input_file -m propseg

hum, i would leave propseg out of this refactoring for now. This is really about bring the ivadomed dev into SCT.

**Comment by charleygros** [comment]
> The **main** purpose of this refactoring is to actually bring the ivadomed code into production.

>  let's start thinking of an algorithm that could accommodate all the different scenario (cropping, centerline detection, etc.)

Makes so much more sense :-) Thank you for the clarification!

**Comment by jcohenadad** [comment]
I can start working on a CLI. @charleygros and @olix86 could you please let me know what would be the API to call for the inference?

Also, if you could train a model for the [data provided by the user](http://forum.spinalcordmri.org/t/segmetation-centerline-errors/352/7?u=jcohenadad) that would be great. More questions will probably come up along the way (how to document model training, etc.). Thanks!

**Comment by charleygros** [comment]
At the moment, we do the inference on the testing set by running `cmd_test` from `ivadomed.main`, [here](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L611).
Which is not made to be called to run a one subject segmentation: there is a lot of options that would not be needed, evaluations tools, debug tools etc.

I have opened an [issue](https://github.com/neuropoly/ivado-medical-imaging/issues/154) on the GH `ivadomed` repo' to address this point. Will try to have a PR ready for the next SCT meeting.
