### ISSUE TITLE
Fit centerline across all slices with input segmentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2629]
When running `sct_create_mask -p CENTERLINE`, if the centerline has some slices that are missing (i.e., empty slice), then the mask will also be missing for those slices, which could be problematic when the mask is subsequently used for `sct_dmri_moco`, where all slices need to have a non-zero mask.

To prevent that, we could have an additional option in `sct_get_centerline -m` where users could input the segmentation, and the output would be the segmentation fitted (e.g. bspline, etc.) for all slices.

**Comment by PaulBautin** [comment]
I've added flag -m that has for argument the user choice of centerline fitting method. This option takes as input the segmentation and outputs the segmentation fitted. It uses the same function as methods Optic and viewer : `get_Centerline`.
How come there are empty slices? Should I worry about the output of the new option having empty slices?

**Comment by jcohenadad** [comment]
> I've added flag -m that has for argument the user choice of centerline fitting method. This option takes as input the segmentation and outputs the segmentation fitted. It uses the same function as methods Optic and viewer : `get_Centerline`.

great! could you please open a PR so we can review (create a branch within SCT repos, not your GH account)

> How come there are empty slices? 

e.g. the segmentation algorithm could output empty slice if the spinal cord is not visible (e.g. artifact, pathology)

> Should I worry about the output of the new option having empty slices?

yes: the purpose of this issue is precisely to ensure that the output has a centerline for all slices of the image
