### ISSUE TITLE
Centerline tests failing on Ubuntu 18.04 via WSL

### ISSUE THREAD

**Issue by cfhammill** [neuropoly/spinalcordtoolbox#2644]
I'm getting test failures on the current master (266bfc88) ( on Ubuntu 18.04 via WSL)

```
sct_download_data -d sct_testing_data
pytest > test-out.txt
```

Relevant failures are in `test_get_centerline_polyfit[img_ctl4-expected4-params4]` and `test_get_centerline_polyfit[img_ctl7-expected7-params7]`

```
=================================== FAILURES ===================================
___________ test_get_centerline_polyfit[img_ctl4-expected4-params4] ____________

img_ctl = (<spinalcordtoolbox.image.Image object at 0x7fa7270d9240>, <spinalcordtoolbox.image.Image object at 0x7fa7270d9320>, a...8, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]], dtype=uint16))
expected = {'laplacian': 0.5, 'median': 0, 'norm': 2, 'rmse': 0.3}, params = {}

    @pytest.mark.parametrize('img_ctl,expected,params', im_centerlines)
    def test_get_centerline_polyfit(img_ctl, expected, params):
        """Test centerline fitting using polyfit"""
        img, img_sub = [img_ctl[0].copy(), img_ctl[1].copy()]
        img_out, arr_out, arr_deriv_out, fit_results = get_centerline(
            img_sub, ParamCenterline(algo_fitting='polyfit', minmax=False), verbose=VERBOSE)
        assert np.median(find_and_sort_coord(img) - find_and_sort_coord(img_out)) == expected['median']
        assert np.max(np.absolute(np.diff(arr_deriv_out))) < expected['laplacian']
        # check arr_out only if input orientation is RPI (because the output array is always in RPI)
        if img.orientation == 'RPI':
>           assert np.linalg.norm(find_and_sort_coord(img) - arr_out) < expected['norm']
E           AssertionError: assert 2.010519806545792 < 2
E            +  where 2.010519806545792 = <function norm at 0x7fa7392b8620>((array([[21., 21., 21., 21., 20., 20., 20., 20., 19., 19., 19., 19., 18.,\n        18., 18., 17., 17., 17., 17., 16., 16...28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,\n        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]]) - array([[21.1806221 , 21.00112842, 20.80636192, 20.59788428, 20.37714865,\n        20.14550338, 19.9041958 , 19.65437592...    , 42.        , 43.        , 44.        ,\n        45.        , 46.        , 47.        , 48.        , 49.        ]])))
E            +    where <function norm at 0x7fa7392b8620> = <module 'numpy.linalg' from '/home/chammill/documents/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/numpy/linalg/__init__.py'>.norm
E            +      where <module 'numpy.linalg' from '/home/chammill/documents/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/numpy/linalg/__init__.py'> = np.linalg
E            +    and   array([[21., 21., 21., 21., 20., 20., 20., 20., 19., 19., 19., 19., 18.,\n        18., 18., 17., 17., 17., 17., 16., 16...28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,\n        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]]) = find_and_sort_coord(<spinalcordtoolbox.image.Image object at 0x7fa707274048>)

unit_testing/test_centerline.py:111: AssertionError
___________ test_get_centerline_polyfit[img_ctl7-expected7-params7] ____________

img_ctl = (<spinalcordtoolbox.image.Image object at 0x7fa7270d96d8>, <spinalcordtoolbox.image.Image object at 0x7fa7270d97b8>, a...8, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]], dtype=uint16))
expected = {'laplacian': 0.5, 'median': 0, 'norm': 3.1, 'rmse': 0.3}
params = {}

    @pytest.mark.parametrize('img_ctl,expected,params', im_centerlines)
    def test_get_centerline_polyfit(img_ctl, expected, params):
        """Test centerline fitting using polyfit"""
        img, img_sub = [img_ctl[0].copy(), img_ctl[1].copy()]
        img_out, arr_out, arr_deriv_out, fit_results = get_centerline(
            img_sub, ParamCenterline(algo_fitting='polyfit', minmax=False), verbose=VERBOSE)
        assert np.median(find_and_sort_coord(img) - find_and_sort_coord(img_out)) == expected['median']
        assert np.max(np.absolute(np.diff(arr_deriv_out))) < expected['laplacian']
        # check arr_out only if input orientation is RPI (because the output array is always in RPI)
        if img.orientation == 'RPI':
>           assert np.linalg.norm(find_and_sort_coord(img) - arr_out) < expected['norm']
E           AssertionError: assert 3.5464013556676113 < 3.1
E            +  where 3.5464013556676113 = <function norm at 0x7fa7392b8620>((array([[21., 21., 21., 21., 20., 20., 20., 20., 19., 19., 19., 19., 18.,\n        18., 18., 17., 17., 17., 17., 16., 16...28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,\n        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]]) - array([[20.97482517, 20.89974339, 20.76859328, 20.59161484, 20.37794351,\n        20.13566434, 19.87186609, 19.59269547...    , 42.        , 43.        , 44.        ,\n        45.        , 46.        , 47.        , 48.        , 49.        ]])))
E            +    where <function norm at 0x7fa7392b8620> = <module 'numpy.linalg' from '/home/chammill/documents/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/numpy/linalg/__init__.py'>.norm
E            +      where <module 'numpy.linalg' from '/home/chammill/documents/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/numpy/linalg/__init__.py'> = np.linalg
E            +    and   array([[21., 21., 21., 21., 20., 20., 20., 20., 19., 19., 19., 19., 18.,\n        18., 18., 17., 17., 17., 17., 16., 16...28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,\n        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]]) = find_and_sort_coord(<spinalcordtoolbox.image.Image object at 0x7fa70716cc18>)

unit_testing/test_centerline.py:111: AssertionError
```

Full output attached.

[test-out.txt](https://github.com/neuropoly/spinalcordtoolbox/files/4399585/test-out.txt)

As noted by @jcohenadad over slack, this appears to be a legitimate numerical issue, not a simple missing file problem (`AssertionError: assert 2.010519806545792 < 2` and  `AssertionError: assert 3.5464013556676113 < 3.1`)

**Comment by cfhammill** [comment]
@PaulBautin and @alexfoias do either of you reproduce this?

**Comment by jcohenadad** [comment]
well, that's concerning: i was not able to reproduce the testing error but i got other ones 😅

~~~
=================================== FAILURES ===================================
________________ test_compute_shape[im_seg3-expected3-params3] _________________

im_seg = <spinalcordtoolbox.image.Image object at 0x142b559b0>
expected = {'angle_AP': 0.0, 'angle_RL': 0.0, 'area': 197.0, 'diameter_AP': 10.0, ...}
params = {'angle_corr': False}

    @pytest.mark.parametrize('im_seg,expected,params', im_segs)
    def test_compute_shape(im_seg, expected, params):
        metrics, fit_results = process_seg.compute_shape(im_seg,
                                                         angle_correction=params['angle_corr'],
                                                         param_centerline=ParamCenterline(),
                                                         verbose=VERBOSE)
        for key in expected.keys():
            # fetch obtained_value
            if 'slice' in params:
                obtained_value = float(metrics['area'].data[params['slice']])
            else:
                if key == 'length':
                    # when computing length, sums values across slices
                    obtained_value = metrics[key].data.sum()
                else:
                    # otherwise, average across slices
                    obtained_value = metrics[key].data.mean()
            # fetch expected_value
            if expected[key] is np.nan:
                assert math.isnan(obtained_value)
                break
            else:
                expected_value = pytest.approx(expected[key], rel=0.05)
>           assert obtained_value == expected_value
E           assert 25.992865498716874 == 10.0 ± 5.0e-01
E             -25.992865498716874
E             +10.0 ± 5.0e-01

unit_testing/test_process_seg.py:137: AssertionError
~~~

Full output: [test-out.txt](https://github.com/neuropoly/spinalcordtoolbox/files/4404309/test-out.txt)

Using commit 266bfc88d6eb6e96a2c2f1ec88c2e185c6f88e09 on my OSX Mojave.

**Comment by jcohenadad** [comment]
The test is failing for all OSs ([see recent build](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/668841921?utm_source=github_status&utm_medium=notification)), so I've renamed the issue

**Comment by cfhammill** [comment]
I'm going to start investigating whether there are platform dependent differences in numpy's `polyfit` function as suggested by @jcohenadad over slack. And we'll see where that line of research goes. This appears to be exclusively a WSL issue for now, reverting the issue name to be specific.

**Comment by cfhammill** [comment]
So I've been investigating this issue. So presently two parameterizations of one test are failing.
`test_get_centerline_polyfit` (https://github.com/neuropoly/spinalcordtoolbox/blob/master/unit_testing/test_centerline.py#L102). 

The tests that are failing are 4 and 7 with test data 

```
dummy_centerline(size_arr=(30, 20, 50), subsampling=1) # 4
dummy_centerline(size_arr=(30, 20, 50), subsampling=5) # 7
```

Both are failing on the error norm test, the error tolerances are

```
2   # 4
3.1 # 7
```
Parameterization 4 only misses by 0.01 but test 7 misses by 0.44. 

I investigated where the errors were occurring in parameterization 7, the centerline fit is perfect for S-I and A-P axes, making (generally small) errors on the L-R axis. The errors are (rounded to two decimal places):

```
[ 0.03,  0.1 ,  0.23,  0.41, -0.38, -0.14,  0.13,  0.41, -0.3 ,
-0.01,  0.29,  0.58, -0.12,  0.17,  0.45, -0.28, -0.01,  0.26,
 0.52, -0.23,  0.02,  0.27, -0.49, -0.24,  0.01,  0.27, -0.47,
 -0.21,  0.07, -0.65, -0.35, -0.05, -0.74, -0.42, -0.09,  0.25,
 -0.41, -0.07,  0.26, -0.41, -0.1 ,  0.2 , -0.54, -0.3 , -0.12,
  0.02, -0.92, -0.93, -1.04, -2.26]
```

Error seems to be large only for the last four (most inferior) coordinates.

The polyfit algo still seems like the most likely candidate. The tests (even on non-WSL) do warn that the model is rank deficient when generating the dummy data. From the numpy docs https://docs.scipy.org/doc/numpy/reference/generated/numpy.polyfit.html:

---

polyfit issues a RankWarning when the least-squares fit is badly conditioned. This implies that the best fit is not well-defined due to numerical error. The results may be improved by lowering the polynomial degree or by replacing x by x - x.mean(). The rcond parameter can also be set to a value smaller than its default, but the resulting fit may be spurious: including contributions from the small singular values can add numerical noise to the result.

---

So the problem could be that we're generating a centerline in the dummy data that has a degenerate solution, leading to platform dependent differences in fit. This could potentially be fixed by adding a small amount of noise to the coordinates in the dummy data.

**Comment by jcohenadad** [comment]
> So the problem could be that we're generating a centerline in the dummy data that has a degenerate solution, leading to platform dependent differences in fit. This could potentially be fixed by adding a small amount of noise to the coordinates in the dummy data.

very interesting. Thanks for the investigations @cfhammill! I am not sure adding noise will necessarily solve the problem (i could be wrong...). The problem seems to come from a bad conditioning of the fit, so maybe we could simply reduce the order? By default, order is "degree=5", which is indeed huge for the very small number of points (n=9 for the first dummy centerlines)

**Comment by cfhammill** [comment]
I tried changing the polynomial degree and unfortunately it didn't fix the problem. No degree I checked (3-6) had fewer failures than the 5th degree polynomial. I'll try adding a small variance to the coordinates in the dummy data generator and see if that helps.

**Comment by cfhammill** [comment]
Adding a small normal noise doesn't work because you'd have to add enough noise to result in a shift of at least one pixel, which is enough noise to throw the other params out of order. In the dummy data generator, the coordinates appear to follow a line but are then fit with a 3rd degree polynomial. So maybe fitting a 5th degree polynomial that is the problem after all.

**Comment by jcohenadad** [comment]
Yes, I also think that the high order for such a small amount of points is the problem. Could you try maybe with only 2nd order? If the test still doesn't pass we could maybe add some tolerance on the equality assertion

**Comment by cfhammill** [comment]
I tried 2nd order with no luck, there are at least 3 failures in that case. We could loosen the error norm requirement enough to make the WSL tests pass. I was worried that the test failure for # 7 was a bit large, but I now realize it's only an extra absolute error of ~0.65 voxels, which maybe isn't enough to worry about, especially given that at least one voxel has an absolute error of 2.26.

**Comment by jcohenadad** [comment]
> We could loosen the error norm requirement enough to make the WSL tests pass. 

agreed!

> I was worried that the test failure for # 7 was a bit large, but I now realize it's only an extra absolute error of ~0.65 voxels, which maybe isn't enough to worry about, especially given that at least one voxel has an absolute error of 2.26.

indeed, no need to worry too much
