### ISSUE TITLE
Migrate sct_run_batch to python

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2655]
A user recently bumped into the following issues (with commit 30d84aa74598b6ccd3c768520222e07c67f14ac3)

- With GNU parallel, the following error message would appear:
![unnamed](https://user-images.githubusercontent.com/2482071/78464381-e1a47b80-76b6-11ea-9567-622519d10b5d.png).
So there might be something specific with OS (Linux 18.04) and version of Parallel.

- if user tried to use -s (sequentially processing argument), it gave him an error, because argument was not used properly. Usage needs to be clarified:
![unnamed-1](https://user-images.githubusercontent.com/2482071/78464401-2c25f800-76b7-11ea-87ff-d66c89776799.png)

- When calling help, it complains about wrong number of parameters:
~~~
julien-macbook:~/code/sct $ sct_run_batch -h
Wrong number of input parameters.
~~~

- Usage shows the following example syntax:
```
Correct usage ./sct_run_batch.sh <parameters.sh> <process_data.sh>
```
And `sct_run_batch.sh` should be replaced for `sct_run_batch` (otherwise it won't work)

**Comment by cfhammill** [comment]
This looks to be a few issues. First the incorrect number of arguments

On ubuntu 18.04 under WSL I get the following:

```
sct_run_batch -h
```
```
Wrong number of input parameters.
This function runs a batch script across multiple subjects that are
  present in a source folder (as defined in the file parameters.sh). If
  GNU parallel is installed, it will used by distributing subjects across the
  available CPU cores. For more information about the file parameters.sh,
  see the example file: /home/chammill/documents/spinalcordtoolbox/shell/parameters_example.sh.
```

This appears to be the correct behaviour according to the code https://github.com/neuropoly/spinalcordtoolbox/blob/master/shell/sct_run_batch.sh#L75. This line checks that there are exactly two or three arguments or throws incorrect number of arguments. This check was added 18 days ago according to git blame. 

I suspect that the use of getopts is slightly broken. Right now the relevant code is

```bash
if [ "$#" -ne 2 -a "$#" -ne 3 ]; then
    echo "Wrong number of input parameters."
    usage
 fi

# getopts processes flag input parmaeters
use_parallel=true
while getopts "sh" opt "$3"; do
  case $opt in
    s)  use_parallel=false;;
    h)  echo "help instruction:"; usage;;
    *)  echo "incorrect flag entered:"; usage;;
  esac
done
```

We could modify this to allow the case of one argument if it's the `-h` flag

```bash
# getopts processes flag input flags
use_parallel=true
while getopts "sh" opt; do
  case $opt in
    s)  use_parallel=false;;
    h)  echo "help instruction:"; usage;;
    *)  echo "incorrect flag entered:"; usage;;
  esac
done
shift "$(($OPTIND -1))"

if [ "$#" -ne 1 -a "$#" -ne 2 ]; then
    echo "Wrong number of input parameters."
    usage
 fi
```

What do you think @PaulBautin?

Will investigate the parallel issue now.

**Comment by jcohenadad** [comment]
@cfhammill i'm thinking: maybe it would be a good time to convert `sct_run_batch` into a python function?  We can do that same thing (more easily) with Python, and replace parallel with python's multiprocessing module (so we kill two birds with one stone)

**Comment by cfhammill** [comment]
Seems reasonable to me, argparse is much cleaner than getopts. Although it's a bit of work and validation. I suspect fixing this issue isn't too much more work. Do you want me to take that on?

The parser issue is also responsible for the `-s` file doesn't exist problem. The getopts code doesn't shift, so the parameters file gets set to the first argument which in that case is `-s`

Still haven't figure out the invalid option `-` issue

**Comment by jcohenadad** [comment]
> Seems reasonable to me, argparse is much cleaner than getopts. Although it's a bit of work and validation. I suspect fixing this issue isn't too much more work. Do you want me to take that on?

Yes it would be great. The collaborator who reported that issue found a workaround (he does not use parallel processing) so we can drop the issue's priority. I think it will be better time investment to move to a Python script right away.

**Comment by cfhammill** [comment]
Sounds good. I think the `-` issue is unrelated to `sct_run_batch`, I think it's a buggy parallel install:

https://unix.stackexchange.com/questions/512332/gnu-parallel-facing-silent-exit-and-invalid-option-error

I'll change the issue name to reflect the new purpose.
