### ISSUE TITLE
Generate interleaved DWI synthetic data 

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#2678]
We discussed that having of synthetic DWI data would be nice for performance testing of `sct_dmri_moco` with [-interleaved](https://github.com/neuropoly/spinalcordtoolbox/pull/2664) option. 

Possible solution:
- take some existing DWI data acquired by NON-interleaved acquisition (e.g. [here](https://openneuro.org/datasets/ds001919/versions/1.0.4))?
- apply random TxTy slicewise shift with regularization on every DWI volume to simulate interleaved acquisition

**Comment by jcohenadad** [comment]
I would go with pure synthetic dataset. E.g., create a multiple volumes with dummy segmentation (code [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/testing/create_test_data.py#L110)). This segmentation would be slightly modified (by modifying scalars to polynomial function defining the centerline)  factor changed) across volumes, as to simulate non-linear motion (slicewise regularized thanks to the polynomial function). Having the ground truth, it is possible to assess the quality of registration.

**Comment by valosekj** [comment]
Thanks for feedback. I am digging into it.
