### ISSUE TITLE
test_many_qc: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#2683]
Found [by travis](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/682023340), this is an intermittent bug. It happened on one of the scheduled trial [rebuilds](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/682023338) even though all the previous scheduled builds on the same branch/commit and even the other jobs in the same build passed.

```
=================================== FAILURES ===================================

_________________________________ test_many_qc _________________________________

multiprocessing.pool.RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/home/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 119, in worker

    result = (True, func(*args, **kwds))

  File "/home/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar

    return list(map(*args))

  File "/home/travis/build/neuropoly/spinalcordtoolbox/unit_testing/test_qc_parallel.py", line 21, in gen_qc

    process = "sct_deepseg_gm")

  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 673, in generate_qc

    angle_line=angle_line

  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 545, in add_entry

    layout(qcslice)

  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 332, in wrapped_f

    self.qc_report.update_description_file(img.shape)

  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 483, in update_description_file

    self._update_html_assets(get_json_data_from_path(path_json))

  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 683, in get_json_data_from_path

    results.append(json.load(fjson))

  File "/home/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 299, in load

    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

  File "/home/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 354, in loads

    return _default_decoder.decode(s)

  File "/home/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/home/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"""

The above exception was the direct cause of the following exception:

    def test_many_qc():

        """Test many qc images can be made in parallel"""

        if multiprocessing.cpu_count() < 2:

            pytest.skip("Can't test parallel behaviour")

    

        # install: sct_download_data -d sct_testing_data

        with multiprocessing.Pool(2) as p:

>           p.map(gen_qc, range(5))

unit_testing/test_qc_parallel.py:32: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py:266: in map

    return self._map_async(func, iterable, mapstar, chunksize).get()

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.MapResult object at 0x7f8190224748>, timeout = None

    def get(self, timeout=None):

        self.wait(timeout)

        if not self.ready():

            raise TimeoutError

        if self._success:

            return self._value

        else:

>           raise self._value

E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py:644: JSONDecodeError

----------------------------- Captured stdout call -----------------------------
```

My first guess, given that `multiprocessing` is involved, that it's some thread-safety issue.

Here's the original log, in case Travis loses it:
[log.txt](https://github.com/neuropoly/spinalcordtoolbox/files/4567109/log.txt)

**Comment by cfhammill** [comment]
@kousu, did you restart the build, I can't see the fail anywhere. That being said I'm not super shocked. We recently removed a directory exists check: https://github.com/neuropoly/spinalcordtoolbox/pull/2628 to overcome a related issue. It might have been over optimistic to assume we could get away with this.

You mention you think it's a thread safety problem, do you mean in `multiprocessing` itself? Because as far as I know none of our code uses threading, just multiple processes. 

My guess is one of the other processes writes to the JSON file while this process is trying to read it causing the first to real non-valid JSON and failing. I'm guessing from this chunk of the backtrace:

```
  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 483, in update_description_file

    self._update_html_assets(get_json_data_from_path(path_json))

  File "/home/travis/build/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 683, in get_json_data_from_path

    results.append(json.load(fjson))
```

**Comment by kousu** [comment]
I think Travis did, because it's marked "cron"! I wish Travis wouldn't overwrite old build logs like that; that's why I attached the log above.

I know `multiprocessing` isn't technically threading but that's the only reason I could see this happening. One process writing a file too slowly for another to read is just like one thread writing too slowly to a shared value.

**Comment by cfhammill** [comment]
Fair enough, I think I'll wait to see this again before investing too much time reproducing.

**Comment by kousu** [comment]
Here's another case: https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/685735623 from https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/685735618:

![Screenshot_2020-05-11 Build #13102 - neuropoly spinalcordtoolbox - Travis CI](https://user-images.githubusercontent.com/987487/81589852-e29c8d00-9387-11ea-81d5-112213a4052c.png)


archive of the [log.txt](https://github.com/neuropoly/spinalcordtoolbox/files/4611016/log.txt) in case Travis overwrites it.

**Comment by cfhammill** [comment]
Darn, ok I can see if I can resolve it

**Comment by cfhammill** [comment]
I can't reproduce on my machine (100+ runs, using a my HDD instead of my SSD in case drive speed mattered, and upping the pool size to increase the risk of hitting this). So I may need to debug blind. The error occurs at

https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/reports/qc.py#L481

The JSON is dumped to a file in the QC directory, and then that file and any other json files in that directory are read in. I think having the json reader:

https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/reports/qc.py#L677

retry, let's say 3 times, with a quarter second pause in between might be enough to fix it. Not sure if anyone has ideas for a more robust solution.

I'll implement it quickly and open a PR.

**Comment by kousu** [comment]
Another example: https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/690662247 

[log.txt](https://github.com/neuropoly/spinalcordtoolbox/files/4679422/log.txt)

**Comment by kousu** [comment]
> I can't reproduce on my machine (100+ runs, using a my HDD instead of my SSD in case drive speed mattered, and upping the pool size to increase the risk of hitting this). So I may need to debug blind.

Wow. 100+ tries. Thanks for grinding through that. I'm sorry it didn't produce any helpful information.


> retry, let's say 3 times, with a quarter second pause in between might be enough to fix it. Not sure if anyone has ideas for a more robust solution.
> 
> I'll implement it quickly and open a PR.

Thanks, I'll look at it! Sorry this fell off my radar.

**Comment by kousu** [comment]
I figured out how to reproduce it!

It's crashing when the reader is faster than the writer (specifically, the reader from *one of* the many generate_qc() processes starts reading the .json that a different generate_qc() process is in the middle of json.dumps()'ing). So I intentionally slowed down that part:

```
diff --git a/spinalcordtoolbox/reports/qc.py b/spinalcordtoolbox/reports/qc.py
index 297a342b..799df0ff 100644
--- a/spinalcordtoolbox/reports/qc.py
+++ b/spinalcordtoolbox/reports/qc.py
@@ -479,7 +479,14 @@ class QcReport(object):
             os.makedirs(path_json, exist_ok = True)
         # Create json file
         with open(self.qc_params.qc_results, 'w+') as qc_file:
-            json.dump(output, qc_file, indent=1)
+            qc_file_mem = io.StringIO()
+            json.dump(output, qc_file_mem, indent=1)
+            qc_file_mem.seek(0)
+            while True:
+                import time; time.sleep(.01) # be slow
+                chunk = qc_file_mem.read(128)
+                if not chunk: break
+                qc_file.write(chunk)
```

with this patch, I get the error every time

<details><summary>log</summary>

```
$ pytest unit_testing/test_qc_parallel.py 
================================================================ test session starts =================================================================
platform linux -- Python 3.6.10, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/bin/python
cachedir: .pytest_cache
rootdir: /home/kousu/src/neuropoly/spinalcordtoolbox, inifile: setup.cfg
plugins: cov-2.8.1
collected 1 item                                                                                                                                     

unit_testing/test_qc_parallel.py::test_many_qc FAILED                                                                                          [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_many_qc ____________________________________________________________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/unit_testing/test_qc_parallel.py", line 21, in gen_qc
    process = "sct_deepseg_gm")
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 680, in generate_qc
    angle_line=angle_line
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 552, in add_entry
    layout(qcslice)
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 332, in wrapped_f
    self.qc_report.update_description_file(img.shape)
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 490, in update_description_file
    self._update_html_assets(get_json_data_from_path(path_json))
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/spinalcordtoolbox/reports/qc.py", line 690, in get_json_data_from_path
    results.append(json.load(fjson))
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

    def test_many_qc():
        """Test many qc images can be made in parallel"""
        if multiprocessing.cpu_count() < 2:
            pytest.skip("Can't test parallel behaviour")
    
        # install: sct_download_data -d sct_testing_data
        with multiprocessing.Pool(2) as p:
>           p.map(gen_qc, range(5))

unit_testing/test_qc_parallel.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py:266: in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.MapResult object at 0x7efe1a4e1dd8>, timeout = None

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

python/envs/venv_sct/lib/python3.6/multiprocessing/pool.py:644: JSONDecodeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
Successfully generated the QC results in /tmp/qc/_json/qc_2020_05_25_222736.600033.json
Use the following command to see the results in a browser:
xdg-open "/tmp/qc/index.html"
Successfully generated the QC results in /tmp/qc/_json/qc_2020_05_25_222737.136931.json
Use the following command to see the results in a browser:
xdg-open "/tmp/qc/index.html"
Successfully generated the QC results in /tmp/qc/_json/qc_2020_05_25_222737.301873.json
Use the following command to see the results in a browser:
xdg-open "/tmp/qc/index.html"
Successfully generated the QC results in /tmp/qc/_json/qc_2020_05_25_222737.719791.json
Use the following command to see the results in a browser:
xdg-open "/tmp/qc/index.html"
============================================================== short test summary info ===============================================================
FAILED unit_testing/test_qc_parallel.py::test_many_qc - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
================================================================= 1 failed in 2.58s ==================================================================
```

</details>

**Comment by kousu** [comment]
I'm glad we fixed this! I was all proud of #2731 though worried that I couldn't properly test it until the nightly build kicked in, but still pretty confident about it, but and then I got an email saying I broke the build.

But I didn't, it was just this bug again.

**Comment by jcohenadad** [comment]
just re-encountered this bug on compute canada, when running 9 parallel instances of 32-job each:
~~~
*** Generate Quality Control (QC) html report ***
Resample images to 0.6x0.6 mm
QcImage: layout with Axial slice
Compute center of mass at each slice
Traceback (most recent call last):
  File "/home/jcohen/sct/scripts/sct_deepseg_sc.py", line 208, in <module>
    main()
  File "/home/jcohen/sct/scripts/sct_deepseg_sc.py", line 202, in main
    dataset=qc_dataset, subject=qc_subject, process='sct_deepseg_sc')
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 719, in generate_qc
    angle_line=angle_line
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 578, in add_entry
    layout(qcslice)
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 351, in wrapped_f
    self.qc_report.update_description_file(img.shape)
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 512, in update_description_file
    self._update_html_assets(get_json_data_from_path(path_json))
  File "/home/jcohen/sct/spinalcordtoolbox/reports/qc.py", line 729, in get_json_data_from_path
    results.append(json.load(fjson))
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jcohen/sct/python/envs/venv_sct/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~~~

**Comment by kousu** [comment]
Ah...hm. That's weird.

My first guess is that ComputeCanada's filesystem is a bit weird. [They use](https://docs.computecanada.ca/wiki/Data_management_at_Niagara#Performance) [GPFS](https://en.wikipedia.org/wiki/GPFS); however supposedly GPFS supports

> Distributed locking. This allows for full POSIX filesystem semantics, including locking for exclusive file access.

so it shouldn't be that.

So maybe my fix was subtly incorrect?

Locking is hard to get right. It's a lot easier to get map-reduce algorithms correct, where the data only goes in one direction and can't interfere with itself. I sketched this out at the bottom of https://github.com/neuropoly/spinalcordtoolbox/pull/2736#issue-422972362.

**Comment by jcohenadad** [comment]
wait... i might have caused this by running processes on the same subjects in parallel. i’m rerunning the pipeline right now, and post results shortly.

**Comment by kousu** [comment]
That should be okay! The point of the fix we put in was to allow exactly that.

Possible issues:
1. I used `flock()` not `fcntl()` (confusingly, in python they're in the same module), and https://stackoverflow.com/a/22411531 suggests

> `fcntl()` locks are the most reliable
> Across architectures, they have the best chance of working right on e.g. shared filesystems -- NFS and CIFS mounts, for example.

So maybe GPFS doesn't fully support `flock()`. I googled around and it's surprisingly hard to find information about GPFS, but both [NFS](https://manpages.debian.org/buster/nfs-common/nfs.5.en.html) and [LustreFS](https://wiki.lustre.org/Mounting_a_Lustre_File_System_on_Client_Nodes), similar filesystems have to be specially configured to support locking, and I bet there's subtle details there.

2. I made it lock the _directory_, which should be fine in theory, but judging from all the subtle bugs locking has run into over the years I would not be surprised if locking a directory over a distributed filesystem is just not going to work.

I think I recall deciding to use `flock()` over `fcntl()` specifically because `fcntl()` wouldn't let me lock a directory. We can try having it lock a file named ".lock" instead (which is the conventional thing to do, I was just trying to be "*efficient*") and using `fcntl()` to do it. If that clears it up then it's because GPFS doesn't fully support locking.

But rewriting the thing to do map-reduce is better.

**Comment by jcohenadad** [comment]
> wait... i might have caused this by running processes on the same subjects in parallel. i’m rerunning the pipeline right now, and post results shortly.

indeed, no more error. Note that compute canada's scratch had some issues for the past few days, so errors might be related to that. I think it is safe to close (until next time 😉 )
