### ISSUE TITLE
CI for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#2691]
Following #2313 and given that @cfhammill has been working on getting us fully working on Windows 10 -- via WSL -- we should add WSL to Travis.

**Comment by cfhammill** [comment]
The work is being done by @lrouhier, I just noticed some numerical instability. At any rate, windows is in beta at the moment https://docs.travis-ci.com/user/reference/windows/, the installed package lists WSL, but I have no idea what that means. The default shell is git-bash, with the chocolatey package manager providing a very minimal package set. Not sure how to open a WSL subshell, and what distro(s) are available via WSL. I'll investigate a bit more

**Comment by lrouhier** [comment]
This [link](https://docs.microsoft.com/en-us/windows/wsl/install-manual) gives you the official command-line installation for the various Linux distros available in WSL. I gave the users instructions for installing Ubuntu 18.04 LTS.  I don't know if travis will open a PowerShell or directly the ubuntu 'VM'...
