### ISSUE TITLE
CI for MacOS Catalina

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#2692]
As in #2313 and #2691 , we should be testing macOS Catalina (10.15) in CI. Travis doesn't support it as of this writing, but when it does we should turn it on.

**Comment by kousu** [comment]
This could be done with Github Actions; but on the flipside Github Actions *only* supports `macos-latest` -- so, currently, 10.15 -- and nothing else.

But that reflect's Apple's policy of aggressively forcing updates on their users. Maybe it's not unreasonable for us to follow that, and *instead* of testing 10.12, 10.13, 10.14, **only* test 10.15.

**Comment by jcohenadad** [comment]
> But that reflect's Apple's policy of aggressively forcing updates on their users. Maybe it's not unreasonable for us to follow that, and instead of testing 10.12, 10.13, 10.14, *only test 10.15.

Hum... the reality is that many of our users do not follow Apple's policy so i would be inclined to continue testing for "old" releases

**Comment by jcohenadad** [comment]
@kousu looks like catalina on travis is out: https://docs.travis-ci.com/user/reference/osx/
