### ISSUE TITLE
add information about SCT version in info_label, and send error if not compatible with current version

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#270]
to avoid users who warped 3 months ago and are now using a new versino of sct_extract_metric that is not compatible

**Comment by jcohenadad** [comment]
i have added the date in info_label (84da1943fdf9d220a22f713f5f7be8e8334be55d). 
at this point, no need to modify sct_extract_metric as long as we can track down the date of generation.
we can anticipate that the number of files in labels will not change in the futur.
