### ISSUE TITLE
Generate QC feature for disc labeling

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/spinalcordtoolbox#2703]
The idea is to implement QC feature for disc labeling based on [sct_qc.py](https://github.com/neuropoly/spinalcordtoolbox/blob/4c2aca38d2536e202d58b9be646652a0f4280b6a/scripts/sct_qc.py) and [qc.py](https://github.com/neuropoly/spinalcordtoolbox/blob/637d0f2a0ff476389257309a69adc64cad36926c/spinalcordtoolbox/reports/qc.py).

**Comment by jcohenadad** [comment]
great! We need to be aware of the potential overlap with the already-existing QC for vertebral labeling. I guess we should see this QC as an intermediate step for `sct_label_vertebrae`, or as a specific test for the soon-to-come disc detection module #2679

**Comment by lrouhier** [comment]
This is a great idea. I think the issue with the current QC is that it is using the labeled segmentation so you get a good idea of the IS position of each disc but you don't have information about the A-P position.  
I see two problems with it which is the position of the label: 
- as we predict on the straighten image all labels are not seen on the medium slice because of the application of the inverse wrapping field. (straight_2_curve) 
- The labels are single points so of course small and hard to see. One option could be to dilate the label file. 
Both of these can maybe get fixed by using dilatation?

**Comment by jcohenadad** [comment]
> * as we predict on the straighten image all labels are not seen on the medium slice because of the application of the inverse wrapping field. (straight_2_curve)

did you mean the "medial" slice (i.e. middle slice in the RL direction)? if that's what you meant, then we can simply project labels in the RL direction on the displayed sagittal slice in the QC report

> * The labels are single points so of course small and hard to see. One option could be to dilate the label file.

not a problem, the coordinate is used to create a Qt object (could be a bit dot with size 10 for example). We would also add the label name next to it, as already done for the QC vertebral labeling

**Comment by lrouhier** [comment]
> did you mean the "medial" slice (i.e. middle slice in the RL direction)? if that's what you meant, then we can simply project labels in the RL direction on the displayed sagittal slice in the QC report

Sorry, yes I meant the medial slice. 

> not a problem, the coordinate is used to create a Qt object (could be a bit dot with size 10 for example). We would also add the label name next to it, as already done for the QC vertebral labeling

You mean something like we can see in `sct_label_utils` with the `-create-viewer` option?

**Comment by jcohenadad** [comment]
> You mean something like we can see in sct_label_utils with the -create-viewer option?

yes exactly

**Comment by alexfoias** [comment]
@jcohenadad so the idea is to add the process`sct_label_utils` in sagittal slice in  [sct_qc.py](https://github.com/neuropoly/spinalcordtoolbox/blob/4c2aca38d2536e202d58b9be646652a0f4280b6a/scripts/sct_qc.py) and [qc.py](https://github.com/neuropoly/spinalcordtoolbox/blob/637d0f2a0ff476389257309a69adc64cad36926c/spinalcordtoolbox/reports/qc.py) that would be rendered in the QC report ?

**Comment by jcohenadad** [comment]
> @jcohenadad so the idea is to add the process`sct_label_utils` in sagittal slice in [sct_qc.py](https://github.com/neuropoly/spinalcordtoolbox/blob/4c2aca38d2536e202d58b9be646652a0f4280b6a/scripts/sct_qc.py) and [qc.py](https://github.com/neuropoly/spinalcordtoolbox/blob/637d0f2a0ff476389257309a69adc64cad36926c/spinalcordtoolbox/reports/qc.py) that would be rendered in the QC report ?

No. The idea is to display the disc labels, similarly to label_vertebral qc

**Comment by alexfoias** [comment]
Opened branch here: https://github.com/neuropoly/spinalcordtoolbox/tree/af/qc_label
