### ISSUE TITLE
sct_process_segmentation producing incorrect line connections in QC figures

### ISSUE THREAD

**Issue by zgm0407** [neuropoly/spinalcordtoolbox#2713]
Hi, thanks for reporting an issue, please take some time to consider the applicable guidelines:
https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#reporting-a-bug-or-requesting-a-feature
(about how to suitably describe issues or requests) prior to deleting this blurb when about to submit the issue.

### Description
![2020-05-16 21-06-32屏幕截图](https://user-images.githubusercontent.com/58411463/82120546-97381380-97b9-11ea-9b10-af2c2a4c640c.png)
Something seems wrong in the qc figures when I run program as follow:
sct_process_segmentation -i t2_seg.nii.gz -vert 3:7 -perslice 1 -o t2_csa_slice.csv -qc "/home/zmz/test
<Description of the issue>

### Steps to Reproduce

0. Install SCT <release or git revision and platform, you can use the
   first lines of output of sct_check_dependencies>

1. <First Step>

2. <Second Step>

3. <and so on...>

**Expected behavior:** <What you expect to happen>

**Actual behavior:** <What actually happens>

**Comment by jcohenadad** [comment]
Wow! This is definitely a bug. @zgm0407 could you please upload your t2_seg.nii.gz image so I can try to reproduce. You can drag and drop.

**Comment by zgm0407** [comment]
[
[t2_seg.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/4639779/t2_seg.nii.gz)
](url)

**Comment by zgm0407** [comment]
[t2_seg_labeled.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/4639784/t2_seg_labeled.nii.gz)
[t2_labels_vert.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/4639789/t2_labels_vert.nii.gz)

**Comment by jcohenadad** [comment]
@zgm0407 thank you for the images, I can reproduce the bug using the following command:
~~~
sct_process_segmentation -i t2_seg.nii.gz -vert 3:7 -vertfile t2_seg_labeled.nii.gz -perslice 1 -o t2_csa_slice.csv -qc qc
~~~

**Comment by cfhammill** [comment]
So I think this one is just an ordering bug, the dots appear to be connected in an order that doesn't match the slice index. All the points are in the right place, but the connecting lines are wrong.

I recreated the CSA figure by reading in the csv and plotting:

![image](https://user-images.githubusercontent.com/7467038/82510823-949b2e00-9ad9-11ea-995d-b7b17ba166be.png)

so I'm going to investigate the plot code and see if perhaps the code (I assume pandas) is reordering the data.

**Comment by jcohenadad** [comment]
that makes sense, thank you @cfhammill 

@zgm0407 unrelated to this bug: the relatively thick slices (3.3mm) makes the segmentation and output CSA unreliable (e.g. abnormally small cord around slices 220). I would strongly suggest you resample your input image to an isotropic resolution (e.g. 0.7mm iso) before running the segmentation and then process seg. You could do it with the following command:
~~~
sct_resample -i t2.nii.gz -mm 0.7x0.7x0.7
~~~

**Comment by cfhammill** [comment]
Sorting the lists into arrays by z coordinate appears to resolve the problem:

![image](https://user-images.githubusercontent.com/7467038/82512045-eee9be00-9adc-11ea-9c18-8c48f9feeeab.png)

Are we ok with this solution or should I try to dig in to why the lists are getting out of order in the first place?

**Comment by jcohenadad** [comment]
i'm quite confident, so you can go ahead with a PR. Thanks!

**Comment by zgm0407** [comment]
> that makes sense, thank you @cfhammill
> 
> @zgm0407 unrelated to this bug: the relatively thick slices (3.3mm) makes the segmentation and output CSA unreliable (e.g. abnormally small cord around slices 220). I would strongly suggest you resample your input image to an isotropic resolution (e.g. 0.7mm iso) before running the segmentation and then process seg. You could do it with the following command:
> 
> ```
> sct_resample -i t2.nii.gz -mm 0.7x0.7x0.7
> ```
amazing!thanks a lot.
