### ISSUE TITLE
add a "test_sct_fmri_compute_tsnr" in /test

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#272]

**Comment by SaraDupont** [comment]
If the test script is OK, this issue can be closed (didn't test it on travis, should I ?)

**Comment by jcohenadad** [comment]
yes please, test in on Travis-- thanks!

**Comment by SaraDupont** [comment]
I just committed a new version of sct_fmri_compute_tsnr.py and its test on master and included it in test_all.py, the test on Travis is OK (Build #955).
