### ISSUE TITLE
sct_dmri_moco returns negative output intensity

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#2720]
When run `sct_dmri_moco` on some dataset, output volume after moco has negative min intensity:

```
$ sct_dmri_moco -i example_data.nii.gz -bvec example_data.bvecs
$ fslstats example_data.nii.gz -R
0.000000 3636.000000
$ fslstats example_data_moco.nii.gz -R
-31.496948 3623.006592 
```

It is not probably factual problem which would influence output image but when compare original and corrected images e.g. in FSLeyes, it is necessary to set min intensity value to zero to have same intensity scaling between these two images. Maybe, we could consider thresholding of output image.

(N.B. also max intensity is changed - probably not problem)

**Comment by jcohenadad** [comment]
Negative intensity is not a bug, and is expected from the (default) spline interpolation. To avoid negative values, you could use linear (or NN) interpolation. So nothing to worry about here.
