### ISSUE TITLE
Disable progress bar when running sct_run_batch

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2724]
When running `sct_run_batch`, log files are created and include pollution from progress bars, example below: 
~~~
Time to generate centerline: 50.0 ms

  0%|          | 0/181 [00:00<?, ?it/s]
  1%|          | 1/181 [00:00<00:28,  6.27it/s]
  2%|▏         | 3/181 [00:00<00:25,  7.09it/s]
  3%|▎         | 5/181 [00:00<00:22,  7.74it/s]
  3%|▎         | 6/181 [00:00<00:22,  7.88it/s]
  4%|▍         | 7/181 [00:00<00:20,  8.29it/s]
  4%|▍         | 8/181 [00:00<00:20,  8.53it/s]
  5%|▍         | 9/181 [00:01<00:20,  8.22it/s]
  6%|▌         | 10/181 [00:01<00:20,  8.48it/s]
  6%|▌         | 11/181 [00:01<00:19,  8.70it/s]
  7%|▋         | 12/181 [00:01<00:18,  9.03it/s]
  8%|▊         | 14/181 [00:01<00:17,  9.39it/s]
  8%|▊         | 15/181 [00:01<00:17,  9.53it/s]
  9%|▉         | 17/181 [00:01<00:16,  9.72it/s]
 10%|█         | 19/181 [00:02<00:16,  9.75it/s]
 11%|█         | 20/181 [00:02<00:16,  9.59it/s]
 12%|█▏        | 21/181 [00:02<00:17,  9.06it/s]
 12%|█▏        | 22/181 [00:02<00:17,  8.87it/s]
 13%|█▎        | 24/181 [00:02<00:16,  9.34it/s]
 14%|█▍        | 26/181 [00:02<00:16,  9.56it/s]
 15%|█▍        | 27/181 [00:02<00:15,  9.68it/s]
 16%|█▌        | 29/181 [00:03<00:15,  9.97it/s]
 17%|█▋        | 31/181 [00:03<00:14, 10.30it/s]
 18%|█▊        | 33/181 [00:03<00:14, 10.46it/s]
 19%|█▉        | 35/181 [00:03<00:13, 10.70it/s]
 20%|██        | 37/181 [00:03<00:13, 10.47it/s]
 22%|██▏       | 39/181 [00:03<00:12, 11.33it/s]
 23%|██▎       | 41/181 [00:04<00:11, 12.02it/s]
 24%|██▍       | 43/181 [00:04<00:10, 12.60it/s]
~~~

It would be nice to disable progress bars when running this script.

**Comment by cfhammill** [comment]
@jcohenadad, what script were you running that generated the progress bars? I'll try to track down what commands are creating them and see if they can be disabled globally. Hopefully it can be disabled with an environment variable, otherwise it may be up to the individual script's author.

**Comment by jcohenadad** [comment]
Quite a lot of scripts are involved. I can think of straighten_spinalcord, deepseg_gm. They all use tqdm. Indeed, having a global config solution would be awesome.

**Comment by kousu** [comment]
It'll probably need to be done by adding an environment variable per script! For pip there was PIP_PROGRESS_BAR=off, for example.

I want to do this for install_sct's download() as well.
-- 
kousu

**Comment by cfhammill** [comment]
Proposal: Add `sct_progress_bar` to `utils.py` which is a thin wrapper around `tqdm`, the wrapper will check the environment variable `SCT_PROGRESS_BAR`, if it is set to `off`, `no`, or `false` it will disable the progress bars. `sct_run_batch.py` will internally set this to `off`.

**Comment by cfhammill** [comment]
I implemented this, it works for `sct_download_data` so @kousu I bet it would work for the downloads in `install_sct`.
