### ISSUE TITLE
Deprecate sct_pipeline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2730]
It has been replaced by `sct_run_batch`. There is no point in maintaining `sct_pipeline`.

**Comment by cfhammill** [comment]
Do we have a standard operating procedure for deprecation? My usual policy is issue a deprecation warning with an explicit version code for when the function will be deleted.

**Comment by jcohenadad** [comment]
since `sct_pipeline` is already broken, v4.3 gives me: 
~~~
julien-macbook:~ $ sct_pipeline
Traceback (most recent call last):
  File "/Users/julien/code/sct/scripts/sct_pipeline.py", line 48, in <module>
    import sys, io, os, types, copy, copy_reg, time, itertools, glob, importlib, pickle
ModuleNotFoundError: No module named 'copy_reg'
~~~

i wouldn't worry about a deprecation message (in this case), although in general i agree with @cfhammill this is good practice

**Comment by cfhammill** [comment]
Should we just delete it then? Happy to add this to #2732, or do it as a separate PR after.

**Comment by jcohenadad** [comment]
@cfhammill sorry i'm seeing this late, i guess this will be another pr then 😊

**Comment by cfhammill** [comment]
Looks like `sct_pipeline` was already removed as part of #2759
