### ISSUE TITLE
API documentation: internal vs external code

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2742]
I am in the process of working on API improvements for the project. To get familiar with the API I decided to revive the RTD API documentation and update it.

I noticed that some API modules have multiple files, sometimes with similar names (for example `core.py`) and I was wondering if there is some type of convention to separate internal code vs external code.

I understand that everything called from `/scripts/sct_*` should be documented as those scripts are consuming the API, however I am wondering if there is some code in `/spinalcordtoolbox` that is not meant to be included in the external API docs.

Relates to #1656

**Comment by jcohenadad** [comment]
I *think* that everything under `/spinalcordtoolbox` can be exposed in the API documentation. Some related thoughts:
- Some methods names use prefix `_` to explicitly tag them as private (i think this is python's convention), so these might not need to be exposed, but AFAIR sphinx can be configured to ignore those;
- Re: files `core.py`: we started off this convention, as a way to refer to the "main" file of each sub-package (e.g. `deepseg_sc`). These usually include the main API called by the CLI (e.g. "segment_file(), label_vertebrae() )  but i'm still not sure if this is good practice. If you have any suggestions/comments, i would love to hear them;
- Some functions will be deprecated/replaced. As you know, we are actively working on `sct_deepseg`, which purpose is to replace all the other "deepseg" APIs. So i'm not saying we should not include all the latter APIs in the doc as of now, but we should minimize the amount of work/refactoring on these functions, as they will be deprecated at some point.
- RTD organization: what i envision is a "user" (installation, getting started, CLI documentation, etc.) and a "developer" section (API doc, contributing, etc.). Does that make sense?

**Comment by Drulex** [comment]
> Some methods names use prefix _ to explicitly tag them as private (i think this is python's convention), so these might not need to be exposed, but AFAIR sphinx can be configured to ignore those;

:+1: Looks like this is the default behavior.

> Re: files core.py: we started off this convention, as a way to refer to the "main" file of each sub-package (e.g. deepseg_sc). These usually include the main API called by the CLI (e.g. "segment_file(), label_vertebrae() ) but i'm still not sure if this is good practice. If you have any suggestions/comments, i would love to hear them;

Personally I don't think that having the "main" or "public" functions of an API in a `core.py` file is a bad practice in itself. What I think is important is that the submodule code is organized in a logical and intuitive way.

For example, as an external developer wanting to use the `sct` API for segmentation I would expect to write something like this:
```
from spinalcordtoolbox.deepseg.core import do_segmentation
from spinalcordtoolbox.deepseg.models import model_a

result = do_segmentation(input=my_input, model=model_a)
```
But if the segmentation submodule is simple I would also find it acceptable to write:
```
from spinalcordtoolbox.deepseg import *

# from deepseg namespace, but I don't need to read 10 pages to figure it out
result = do_segmentation(input=my_file, model=model_a)
```

The most important part is that the API code is written as proper library code (no printing to terminal, no changing user environment, low-level interface, etc) which makes it portable and easier to test.

> Some functions will be deprecated/replaced. As you know, we are actively working on sct_deepseg, which purpose is to replace all the other "deepseg" APIs. So i'm not saying we should not include all the latter APIs in the doc as of now, but we should minimize the amount of work/refactoring on these functions, as they will be deprecated at some point.

:+1: Ok no problem. Although I never used it, I heard of the existent of a `deprecated`  [decorator](https://pypi.org/project/Deprecated/)

> RTD organization: what i envision is a "user" (installation, getting started, CLI documentation, etc.) and a "developer" section (API doc, contributing, etc.). Does that make sense?

Yes absolutely

Utilmately what I want to avoid is for the doc to be bloated with hundreds of "internal" helper functions or supporting code not useful for the API consumer.
