### ISSUE TITLE
sct_deepseg: implement compatibility with 2-steps pipeline

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#2744]
### Current workflow:
```
sct_deepseg -i image.nii.gz -m modelZ
```
1. Get model's path (already installed or download it): [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg.py#L143). Models being listed [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/models.py#L20).
2. Call `segment_nifti` [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/core.py#L88) which returns the name of the produced segmentation.

### Issue:
The current implementation only allows to run **one** model. In some cases, we would like to cascade more than one model. For example: 
- model 1: input: image, output: cord segmentation
- model 2: input: image + cord segmentation, output: lesion segmentation. 

How can we refactor the code to enable this feature?

### Proposition
1. Convert the URL of the model location to a list, [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/models.py#L22)
2. When installing the model [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg.py#L151), follow: "pipeline/model_stepX", compatible with 1-step or N-step approaches. Example:
```
t2_tumor/
    model_detection/  # step 1, first URL in the list
        model_detection.onnx
        model_detection.json
    model_segmentation/  # step 2, second URL in the list
        model_segmentation.onnx
        model_segmentation.json
```
3. So we will have a list of [path_model](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg.py#L154) eg `["t2_tumor/model_detection", "t2_tumor/model_segmentation"]`. Warning: the order of the models in this list matters. It allows, for each iteration (ie each model), to load the model and metadata (json file) that are specific for this step.
4. We loop across this list of `path_model` and call `segment_nifti`, [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg.py#L160). After running the first model, we add the first_model_output to `segment_nifti` inputs (in [params](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/core.py#L94) or as an additional parameter to be defined, eg fname_roi).
5. The additional input (ie the output of the first step) is used by `segment_volume` ([here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/core.py#L97)) to perform the second step of the pipeline: eg via `fname_roi` parameter [here](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/utils.py#L343).

**Comment by jcohenadad** [comment]
@charleygros i've slightly rewritten your text above as I understood it, please let me know if I misinterpreted.

In general, I am aligned with your suggestion. I just have a couple of minor comments:

**About model installations**
Given that we might have multiple tasks that will use the same model (e.g.: lesion segmentation relies on [segment cord, segment lesion], tumor segmentation relies on [segment cord, segment lesion]), to avoid having to physically install the same model twice at different locations (which is what you seem to suggest), we could instead install each model in its own separate folder, regardless the task. So it would look like this:
~~~
models/
  |- segment_cord
  |- segment_lesion
  |- segment_tumor
~~~

Then, upon calling `sct_deepseg -m lesion`,  we can easily figure out, based on the list-based model definition (i.e. task "lesion" relies on models [segment cord, segment_lesion]) that each models is installed and can be used in the specified order.

**Comment by charleygros** [comment]
Something I forgot to mention: the addition of a parameter to `sct_deepseg` where we could provide a `fname_roi`in case the first step fails.

**Comment by charleygros** [comment]
I would agree for the lesion-case but not too sure for the tumour-case as the two-steps have been optimised / designed and trained together.

For the tumor: the segment_sc model is likely to perform poorly on tumor data --> a specific model is needed.

For the MS lesions: the segment_sc is fine.

At the end, I think the structure could look like this:
```
models/
  |- segment_cord/
  |- lesion/
      |- detect_lesion/
      |- segment_lesion/
  |- tumor/
      |- detect_sc/
      |- segment_tumor/
```

For the tumor: (1) `tumor/detect_sc/`, (2) `tumor/segment_tumor/`.
For the MS lesions: (1) `segment_sc/`, (2) `lesion/detect_lesion/`, (3) `lesion/segment_lesion`.

**Comment by jcohenadad** [comment]
@charleygros, what i wrote [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2744#issuecomment-643365707) was just an illustration of the concept, not an actual suggestion for the specific tasks of lesion/tumor segmentation. I should have called them "task 1" and "task 2". 

my suggestion was that, after 2 years we might end up with 35 tasks, and some of these tasks will share some models, so instead of duplicating the model inside "task i" and "task j", then let's install all one-step models under a flat directory: 
~~~
models/
  |- model1/
  |-model2/
  |-...
  |-modeln/
~~~
and each task would then use the required models (1, 2 or more), in the order specified.

**Comment by charleygros** [comment]
Oh! My bad.. 
Yes 100.17% agree!

**Comment by jcohenadad** [comment]
Here would be the possible scenario:
~~~
# existing models: the task "segment-cord" will use models: [findcord, segmentcord]
sct_deepseg -task segment-cord
# to replace first model by another official model:
sct_deepseg -model findcord_another segmentcord 
# to replace first model by a custom local model:
sct_deepseg -model path_to_my_model/ segmentcord 
~~~

So to make it work, we will need to refactor `sct_deepseg/models.py`:
~~~
MODELS = {
    'findcord':
        {'url': 'https://osf.io/v9hs8/download?version=4',
         'description': 'Cord segmentation on T2*-weighted contrast.',
         'default': True},
    'segmentcord':
        {'url': 'https://osf.io/v9hs8/download?version=4',
         'description': 'Cord segmentation on T2*-weighted contrast.',
         'default': True},
}

TASKS = {
    'segment-cord': ['findcord', 'segmentcord']
}
