### ISSUE TITLE
Using requirements-freeze should be platform-specific

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2745]
While trying to create a new release (4.3), i noticed that the (now) extensive cross-platform testing was crashing when using a requirement-freeze file, because the latter was created on a single platform (ubuntu 18.04), and our requirement currently includes platform-specific packages, such as [pytorch](https://github.com/neuropoly/spinalcordtoolbox/blob/master/requirements.txt#L26). So we need to re-think our logic for the requirements-freeze.

Possibly-related to that: all those tests crashing: https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/697796842

I mentioned "possibly", because I am surprised that **all** those tests are crashing. If it was related to the requirement-freeze issue discussed above, I would expect to see at least a few tests pass.

**Comment by Drulex** [comment]
I believe it has to do with `requirements-freeze.txt` not having the platform specific checks as `requirements.txt` does.

I can get around the issue by adding the platform checks:
```
diff --git a/requirements-freeze.txt b/requirements-freeze.txt
index e6c70cd3..bab9e587 100644
--- a/requirements-freeze.txt
+++ b/requirements-freeze.txt
@@ -76,8 +76,16 @@ tensorflow==1.5.0
 tensorflow-tensorboard==1.5.1
 threadpoolctl==2.1.0
 tifffile==2020.6.3
-torch==1.5.0+cpu
-torchvision==0.6.0+cpu
+tensorflow==1.5.0
+# PyTorch's Linux/Windows distribution is very large due to its GPU support,
+# but we only need that for training models. For users, use the CPU-only version
+# (only available directly from the PyTorch project).
+# The OS X version has never had GPU support, so doesn't need the workaround.
+-f https://download.pytorch.org/whl/cpu/torch_stable.html
+torch==1.5.0+cpu; sys_platform != "darwin"
+torch==1.5.0; sys_platform == "darwin"
+torchvision==0.6.0+cpu; sys_platform != "darwin"
+torchvision==0.6.0; sys_platform == "darwin"
 tqdm==4.46.1
 transforms3d==0.3.1
 typing-extensions==3.7.4.2
```

**Comment by jcohenadad** [comment]
That makes sense. The problem is the way we generate the requirements-freeze: it is done manually on one platform. Is there a way we can automatize the generation of this file for the preparation of each new release?

**Comment by Drulex** [comment]
To my knowledge, if you have custom stuff in the `requirements.txt` (such as the custom urls and platform checks) I think these need to be merged manually into the generated `requirements-freeze.txt` (unless you have one `requirements-freeze.txt` per platform).

We could add this step to the pre-release checklist.

**Comment by jcohenadad** [comment]
> To my knowledge, if you have custom stuff in the `requirements.txt` (such as the custom urls and platform checks) these need to be merged manually into the generated `requirements-freeze.txt` (unless you have one `requirements-freeze.txt` per platform).
> 
> We could add this step to the pre-release checklist.

ok i've added those in 9ea4c9b3a6a0c0aab75b45bfbf060820cf0f2ce4, let's wait for travis

**Comment by jcohenadad** [comment]
looking good now: https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/698564142

**Comment by jcohenadad** [comment]
info added in the wiki/versioning checklist, so i guess we can close
