### ISSUE TITLE
"Uninstalling numpy-1.19.0"

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#2750]
On [the most recent release](https://github.com/neuropoly/spinalcordtoolbox/releases/tag/4.3), `install_sct` gives this funny message:

```
Installing Python dependencies...

Collecting numpy
  Downloading numpy-1.19.0-cp36-cp36m-manylinux2010_x86_64.whl (14.6 MB)
     |████████████████████████████████| 14.6 MB 67 kB/s 
Installing collected packages: numpy
Successfully installed numpy-1.19.0

Using requirements-freeze.txt (release installation)

Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
[...]
Installing collected packages: six, absl-py, attrs, pytz, python-dateutil, numpy, pandas, pyparsing, packaging, nibabel, docopt, num2words, bids-validator, scipy, patsy, SQLAlchemy, pybids, bids-neuropoly, html5lib, bleach, cachetools, pycparser, cffi, chardet, colored, coverage, cryptography, cycler, decorator, h5py, dipy, future, futures, pyasn1, pyasn1-modules, rsa, google-auth, idna, urllib3, requests, oauthlib, requests-oauthlib, google-auth-oauthlib, grpcio, Pillow, imageio, zipp, importlib-metadata, tifffile, networkx, PyWavelets, kiwisolver, matplotlib, scikit-image, seaborn, typing-extensions, protobuf, onnx, onnxruntime, torch, torchvision, tqdm, pluggy, py, more-itertools, wcwidth, pytest, Werkzeug, Markdown, tensorboard-plugin-wit, tensorboard, joblib, threadpoolctl, scikit-learn, ivadomed, PyYAML, Keras, pyOpenSSL, PyQt5-sip, PyQt5, pytest-cov, raven, requirements-parser, tensorflow-tensorboard, tensorflow, transforms3d, xlwt
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.0
    Uninstalling numpy-1.19.0:
      Successfully uninstalled numpy-1.19.0
```

It doesn't hurt the functioning, but it makes the installer undo its own work.

**Comment by kousu** [comment]
This is because

https://github.com/neuropoly/spinalcordtoolbox/blob/a4f9b8612cf5f424f508ce51a305f7d6faad0c7e/install_sct#L532

does not version-pin numpy, which is then of course superseded by the version in requirements-freeze.txt.

Can we just drop that line? I recall a mention in an older version of that pre-installing numpy was necessary for version conflict reasons; but we're not using it anymore, since the installer just undoes it, and all the tests pass.

**Comment by routrohan** [comment]
Can I take it up?

**Comment by routrohan** [comment]
I'm sorry but I'm having some trouble in pushing to the repo, it seems I might not have certain access rights. This is what I'm getting : 

![repo](https://user-images.githubusercontent.com/32121879/85429290-2811c400-b59c-11ea-8c5e-51d9a1b5b65a.png)

**Comment by jcohenadad** [comment]
@routrohan external contributors are required to fork the repository and suggest changes via a pull request, more details in https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#contributing-to-sct-pull-request

thanks!
