### ISSUE TITLE
Point to local sct_testing_data for unit tests

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2755]
Currently, almost all unit tests (except one: `test_segment_nifti()`) assume that `sct_testing_data` is located under `__sct_dir__`, which is not convenient if these data are installed outside of SCT_DIR. 

In some cases, developers might want to go to a temp folder, download test data and run pytest from there, which would fail.

A suggestion would be to get rid of the `__sct_dir__` and assume that `sct_testing_data` is installed in the current folder.

**Comment by cfhammill** [comment]
I believe this one was resolved in #2804
