### ISSUE TITLE
Parser: automatically display the default value in the help

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#2756]
**Justification:**
We are currently adding manually the default value for each argument in the "description" entry, [see example](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L111).

To automatically display this value in the help would reduce the maintenance load and reduce the developer errors.
Also, it would fill the gaps where default values are not displayed in the help, [see example](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_crop_image.py#L83).

**Describe the solution you'd like**
[ArgumentDefaultHelpFormatte](https://docs.python.org/3/library/argparse.html#formatter-class)r could be a good solution. As recommended [here](https://stackoverflow.com/a/12151325).

**Comment by cfhammill** [comment]
I think this one is pretty simple. https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/utils.py#L68, switch 

```python

class SmartFormatter(argparse.HelpFormatter):
```

to

```python
class SmartFormatter(argparse.ArgumentDefaultsHelpFormatter):
```

Worked in a few cases that I checked. It somewhat irritatingly adds (default: None) everywhere without a default even when that doesn't really make sense (e.g. a required arg). But it can probably be fixed.

**Comment by joshuacwnewton** [comment]
> It somewhat irritatingly adds (default: None) everywhere without a default even when that doesn't really make sense (e.g. a required arg)

I believe the reason that `default: None` shows up for our required args is because we use keyword args for everything, so our required args are still quote-unquote `OPTIONAL`, see below. (This came up before in a different context, as well!)

```python
# argparse.py

class ArgumentDefaultsHelpFormatter(HelpFormatter):
    """Help message formatter which adds default values to argument help.

    Only the name of this class is considered a public API. All the methods
    provided by the class are considered an implementation detail.
    """

    def _get_help_string(self, action):
        help = action.help
        if '%(default)' not in action.help:
            if action.default is not SUPPRESS:
                defaulting_nargs = [OPTIONAL, ZERO_OR_MORE]
                if action.option_strings or action.nargs in defaulting_nargs:
                    help += ' (default: %(default)s)'
        return help
```



Because the only thing that `argparse.ArgumentsDefaultHelpFormatter` does is modify `_get_help_string`, it seems simple enough to come up with a tidy tweak for this for our purposes. I'll start on this now.
