### ISSUE TITLE
Different results between centos7 and OSX

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2769]
While analyzing the single-subject spine-generic dataset, i noticed that the output segmentation from propseg (https://github.com/spine-generic/spine-generic/blob/d1fdd4641b7835f810e5c6eb97a9c92a5968cdd0/processing/process_data.sh#L257) produces slightly different segmentations on centos7 (compute canada) and OSX:
![Screen Shot 2020-07-04 at 5 29 58 PM](https://user-images.githubusercontent.com/2482071/86521283-a08a4780-be1c-11ea-98fc-a5157a312fc6.png)

Beyond the issue of reproducibility, this behaviour is problematic because from this segmentation, a mask is created, and subsequently used in the pipeline. Now, if down the line a manual correction needs to be done, the dataset is updated and this new dataset will now depend on the OS that the first pipeline was run on, making the whole pipeline platform-dependent.

A workaround would be to switch to `sct_deepseg` in pipelines that require cross-platform reproducibility.

Before concluding this, same cross-platform behaviour for `sct_deepseg` needs to be demonstrated.

**Comment by jcohenadad** [comment]
Also, integrity testing across platforms should test for this.

**Comment by jcohenadad** [comment]
Dice is "relatively" low, therefore the inter-OS differences are missed:
https://github.com/neuropoly/spinalcordtoolbox/blob/c470421e32ee25f2b73de843fe5b11d05e316cf1/testing/test_sct_propseg.py#L29

It should be put to 1.0 for a sensitive test. However, Travis will inevitably fail for this test, then. Any reason propseg would produce different results between OSs? Is the latest compiled version using the same source accross OSs? @zougloub I vaguely remember you looked into this a few years ago

**Comment by cfhammill** [comment]
If this is a wontfix and mentioned in two merged PRs, should we close?

**Comment by jcohenadad** [comment]
thanks for the follow-up @cfhammill 

actually, this has now been fixed by #115.
