### ISSUE TITLE
poly=0 has no effect on the motion correction

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2779]
As [reported by a user](http://forum.spinalcordmri.org/t/sct-fmri-moco-with-poly-0/427), when using `sct_fmri_moco` with options `-param poly=0`, the estimated motions are 0.0 for both Tx and Ty, resulting in no effective correction. 

To reproduce:
SCT version 38a282d52f1e3bb19f3592ab4d98f3ee5e168f0a on macOS
~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/fmri
sct_fmri_moco -i fmri.nii.gz -param poly=0
~~~

<details><summary>Example of Tx output</summary>

~~~
cat moco_params.tsv
X	Y
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
0.0	0.0
~~~

</details>

The following needs to be investigated/fixed:
- [ ] Check if this also applies to `sct_dmri_moco`

Unrelated issues that could be fixed in the same PR:
- [ ] Removed duplicated .nii and .nii.gz files being created in the tmp folder

**Comment by jcohenadad** [comment]
I've investigated various options for `isct_antsSliceRegularizedRegistration` and it seems to be a bug. I will report to ANTs developers, and in the meantime we could replace this case by a slice-wise registration (with `isct_antsRegistration -d 2`).

**Comment by jcohenadad** [comment]
Issue opened here: https://github.com/ANTsX/ANTs/issues/1040

**Comment by cfhammill** [comment]
Is this behaviour incorrect? I'm probably misunderstanding, but if ANTs is computing a zero degree polynomial to represent the motion, isn't that a constant, and if each slice/volume is shifted by a constant translation won't it have no impact on the cost function?

**Comment by jcohenadad** [comment]
> Is this behaviour incorrect? I'm probably misunderstanding, but if ANTs is computing a zero degree polynomial to represent the motion, isn't that a constant, and if each slice/volume is shifted by a constant translation won't it have no impact on the cost function?

the usage says:
~~~
     -p, --polydegree 
          degree of polynomial - up to zDimension-2. Controls the polynomial degree. 0 
          means no regularization. This may be a vector denoted by 2x2x1 for a 3-parameter 
          transform ( e.g. rigid ). This would regularize the translation by 2nd degree 
          polynomial and the rotation by a linear function. 
~~~

so, without regularization, i would expect each slice to be treated independently (not with a constant regularization)

**Comment by jcohenadad** [comment]
This issue has been fixed by the ANTs team https://github.com/ANTsX/ANTs/pull/1047. So we need to generate new binaries. @kousu what is the procedure now with the new binary generation pipeline that you put in place?

**Comment by kousu** [comment]
Procedure sketchily documented here: https://github.com/neuropoly/spinalcordtoolbox/issues/2669#issuecomment-665153804

Anyway I did the merge and the build is currently baking https://github.com/kousu/ANTs/pull/5/checks. It will be done in about an hour.

**Comment by kousu** [comment]
New binaries on https://github.com/kousu/ANTs/releases/tag/refs%2Fheads%2Fmatrix-build-185966584

**Comment by kousu** [comment]
I am glad that worked! It took a lot of time to figure out the build script the first time but now getting new binaries is a < 2hr process instead of a terrifying multi-day dev-environment-setup retesting situation.
