### ISSUE TITLE
Check for space character " " in directory trees

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2785]
To avoid having to support these scenarios (not the first time this is happening):
http://forum.spinalcordmri.org/t/installation-failed-write-permission/429/4?u=jcohenadad

**Comment by cfhammill** [comment]
A very simple but non-robust solution would be to compute how large the installed SCT directory is on each OS, then put a check that the requested install location has that much space plus some safety factor (e.g. +20%). This unfortunately would require manual curation as the install direction will likely grow over time as sct acquires new dependencies. I can't think of a robust way to keep the install size up to date. 

Probably not worth the effort but me and @kousu could probably come up with a way to use the github API to PR the updated sizes to each branch after successful CI tests.

**Comment by jcohenadad** [comment]
@cfhammill sorry for the confusion-- by "space", i meant the character space " ". E.g., paths like:
`sct_xxx -i my path with space/file with space.nii.gz`

**Comment by cfhammill** [comment]
My fault, I should have read the forum post!

**Comment by kousu** [comment]
On August 16, 2020 4:07:44 PM EDT, Julien Cohen-Adad <notifications@github.com> wrote:
>@cfhammill sorry for the confusion-- by "space", i meant the character
>space " ". E.g., paths like:
>`sct_xxx -i my path with space/file with space.nii.gz`

You don't need to do this. Just quote every variable with double quotes, even ones used as part of the command.

And you can do things like
ls "${SCT_DIR}"/subdir/"${SECTION}".
that evaluates to a single string.

You can even nest double quotes in shell! Go wild!

See more https://sipb.mit.edu/doc/safe-shell/

It would be good to integrate shellcheck into our CI.

-- 
kousu
