### ISSUE TITLE
Zip results folder after finishing script

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2789]
When running `sct_run_batch` in a cluster, it would be convenient to create a single zip archive of `results/`, `qc/` and `log/`, for convenient copy to local station. 

The archive could be called `results_YYMMDDHHMMSS.zip`

**Comment by PaulBautin** [comment]
Should the cluster name be entered as a variable in sct_run_batch? i'm thinking of using scp to transfer the newly created zip file to local station.

**Comment by jcohenadad** [comment]
> Should the cluster name be entered as a variable in sct_run_batch? i'm thinking of using scp to transfer the newly created zip file to local station.

i don't see the advantage in doing that (the hostname is already recorded in `sct_run_batch` log)
