### ISSUE TITLE
sct_run_batch saves processed data in home dir

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#2790]
When run:

```
sct_run_batch -jobs -1 -path-data data-multi-subject-master -path-output data-multi-subject-master_results/ -continue-on-error 1 -task /usr/local/lib/spine-generic/process_data.sh

--
Spinal Cord Toolbox (git-master-46d3e00454cda72b6f0c6a9e50f6d24a94650070)

sct_run_batch arguments were:
batch_log: sct_run_batch_log.txt
config: null
continue_on_error: 1
email_from: null
email_host: smtp.gmail.com:587
email_to: null
exclude: null
exclude_list: null
include: null
include_list: null
itk_threads: 1
jobs: -1
path_data: data-multi-subject-master
path_output: data-multi-subject-master_results/
path_segmanual: .
subject_prefix: sub-
task: /usr/local/lib/spine-generic/process_data.sh
task_args: ''
```

Processed MRI data are saved into home directory (`~/`). Into `/results` folder are saved only *csv files.

**Comment by jcohenadad** [comment]
@valosekj i'm not sure which version of spine-generic/process_data you are using, but the latest SCT commit (35dd7529de57bca8d8a230ebc8d8c5cccc9a49cf), (you are using the older version 46d3e00454cda72b6f0c6a9e50f6d24a94650070) introduced the variable `PATH_DATA_PROCESSED` to output process data, so there might be a conflict with the versions you are running.

could you please update SCT & spine-generic and re-run?

**Comment by valosekj** [comment]
I updated SCT and spine-generic approximately 8 hours ago before I started analysis.
But sure, I will update them to current versions and re-run.

**Comment by valosekj** [comment]
With the latest SCT commit (https://github.com/neuropoly/spinalcordtoolbox/commit/35dd7529de57bca8d8a230ebc8d8c5cccc9a49cf) it looks fine 👍 processed data are saved under `data_processed/`. Thanks
