### ISSUE TITLE
ATLAS: Cuneatus starts around T4.. and is much bigger at C1

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#280]

**Comment by benjamindeleener** [comment]
@tanguyduval : Not clear, please add snapshots and more info.

**Comment by tanguyduval** [comment]
No snapshots - Blanche should find atlases at T3 C4 C1.

**Comment by joshuacwnewton** [comment]
Considering the atlas/template has evolved quite a bit (i.e. MNI-Poly-AMU -> PAM50), my instinct is that this issue is no longer relevant. Would you be able to confirm, @jcohenadad? (Thanks much!)

**Comment by jcohenadad** [comment]
i confirm-- this issue is no more relevant
