### ISSUE TITLE
Use proper logging instead of printing to terminal

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2809]
While working on #2547 , I noticed that a lot of what should be low-level code is printing to the terminal. I then looked into already modularization code to notice that API code is importing `sct_utils` (that lives in `scripts/`)  to use `printv()`. This is bad because:

- Layering violation: low-level api  code should not be aware/depend on higher-level application code. A developer should be able to take the API and develop their own application on top of it. Also it can lead to circular dependencies.
- API code should not print to the terminal: for the same reason that you don't want an imported package/library to unexpectedly start printing stuff to the terminal. 

Alternatives are:
- Use the `logging` library. This is more powerful, flexible and can be called from anywhere. We could create a `console` handler with a formatting identical to the `printv()` function and redirect all messages of a certain level (e.g. `INFO`) to the terminal.
- Inject a logging dependency into low-level code. This dependency would take care of the printing/logging and is a more flexible way for the API consumer to control how stuff is logged. For example, a first (side-effect free) step we could pass the `printv()` function to all the low-level API functions that need it, thus removing the `import sct_utils` dependency.

**Comment by Drulex** [comment]
FYI @jcohenadad @zougloub

**Comment by jcohenadad** [comment]
The team is now aware of this problem, see this updated [wiki page](https://github.com/neuropoly/spinalcordtoolbox/wiki/logging). Unfortunately there was no time to fix this problem everywhere in the code, but yes, i agree, it should be done.

Do you agree with the suggestion in the wiki?

**Comment by Drulex** [comment]
Woops sorry I didn't see that :sweat: . I will replace the calls to `printv()` with logger as instructed on the page.

Yes it looks fine, I propose to keep this open until all `printv()` have been fixed in the API. It will make it easier for the next person who searches this topic (I couldn't find a related issue).

**Comment by jcohenadad** [comment]
related to that, i suggest the following initialization before calling the main() in the CLI scripts:
````python
if __name__ == '__main__':
    arguments = get_parser().parse_args()
    sct.init_sct(log_level=2 if arguments.v else 1)
    main(arguments)
````

Of course, that implies to declare `-v` with `action=store_true` in the parser. Are you OK with that convention @Drulex ? if so i'll update the wiki

**Comment by Drulex** [comment]
Yes sure. You could also add `v`s to increase verbosity if there are multiple levels. e.g: `-v` -> `verbosity=1`, `-vv` -> `verbosity=2`, etc.

**Comment by jcohenadad** [comment]
> Yes sure. You could also add `v`s to increase verbosity if there are multiple levels. e.g: `-v` -> `verbosity=1`, `-vv` -> `verbosity=2`, etc.

i think for now, we can simply use logging.info() as the default, and logging.debug() if -v. I suggest we don't complicate things at this point where SCT's code is already messy regarding that aspect.
