### ISSUE TITLE
in binaries and other files, change "version" for "date"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#282]
having several versions for each script/file/function is confusing for the user (because of the SCT version). Better to use the date.

Example:

replace:
~~~~
sct_crop_image - Version 0.3
Author : Benjamin De Leener - NeuroPoly lab <www.neuropoly.info>
~~~~

by:
~~~~
sct_crop_image
Author : Benjamin De Leener - NeuroPoly lab <www.neuropoly.info>
modified: 2015-03-24
~~~~

**Comment by benjamindeleener** [comment]
fixed for sct_crop_image. Need to be done for all the binary script

**Comment by jcohenadad** [comment]
by the way: now use www.neuro.polymtl.ca  ;-)
