### ISSUE TITLE
Display Changelog in the RTD documentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2822]
Now that we are moving our documentation to RTD, it would be nice to centralize everything there, including the CHANGES.md file. As of now, only a link to the .md file is included in the doc:
https://github.com/neuropoly/spinalcordtoolbox/pull/2814/files#diff-c0554a20ae9c2b0fc1f14ef9c35baec5R38

The suggestion would be to add an entry in the "DEVELOPER SECTION", with a new heading: "Changelog"

**Comment by alexfoias** [comment]
I want to work on this issue. I checked the website, but it seems like this issue is obsolete.
@jcohenadad Could you please confirm that we still have to implement it ?

**Comment by jcohenadad** [comment]
already implemented: https://spinalcordtoolbox.com/en/latest/dev_section/CHANGES.html
