### ISSUE TITLE
sct_run_batch config file unnecessary keys

### ISSUE THREAD

**Issue by PaulBautin** [neuropoly/spinalcordtoolbox#2825]
**Feature justification: Is your feature request related to a problem? Please describe.**
When running `sct_run_batch -config config.yaml`, many unknown keys are displayed due to other variables in the yml config file.

**Describe the solution you'd like**
Could a verbose flag, allow the suppression of these unnecessary comments? 

**Describe alternatives you've considered**
An alternative would be to ask user to create a yaml file specific to sct_run_batch.

**ERROR:**
config file: [config.zip](https://github.com/neuropoly/spinalcordtoolbox/files/5016142/config.zip)
To reproduce you do not need any data or script, yaml file is read and comment is displayed before process.

sct_run_batch -config config.yaml

--
Spinal Cord Toolbox (git-master-7dfb515728f5ba702df1dabdd9a33f00c085e224)

configuring
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "PATH_SEGMANUAL" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "transfo" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "stats" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "PATH_ORIGINAL_RESULTS" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "PATH_ORIGINAL_CSV" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "FILES_SEGMANUAL" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "PATH_DESTINATION_RESULTS" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "n_transfo" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "rescaling" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))
/home/paul/github/spinalcordtoolbox/scripts/sct_run_batch.py:250: UserWarning: Unknown key "contrast" found in your configuration file, ignoring.
  'Unknown key "{}" found in your configuration file, ignoring.'.format(k)))

**Comment by cfhammill** [comment]
Hi Paul,

The config option provided by `sct_run_batch` is supposed to be specifically for `sct_run_batch`, not the script it runs. If the script  itself supports a config you can pass it with

```yaml
script_args: --config script_config.yaml
```

**Comment by jcohenadad** [comment]
I think we can close the issue as it is related to a wrong usage

**Comment by PaulBautin** [comment]
Thanks @cfhammill, it works good!
