### ISSUE TITLE
Transfer the remaining documentation from sourceforge

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2829]
With the new RTD documentation, the old documentation material needs to be ported from [sourceforge](https://sourceforge.net/p/spinalcordtoolbox/wiki/Home/).

However, not _all_ the material needs to be ported:
- Some is old/obsolete and needs to be deleted
- Some will be ported in RTD
- Some will be incorporated in SCT course

**Comment by joshuacwnewton** [comment]
I'm very interested in working on this (as well as the organization of SCT's documentation in general, as brought up in the last lab meeting). :slightly_smiling_face:

**Comment by jcohenadad** [comment]
What is in sourceforge that would be relevant to port on the RTD:

- sct_propseg: 
  - would be nice to include the image shown [here](https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_propseg/) in the docstrings of the CLI so it renders on [RTD](https://spinalcordtoolbox.com/en/latest/user_section/command-line.html#sct-propseg)
  - add the refs
  - tips and tricks: https://sourceforge.net/p/spinalcordtoolbox/wiki/correction_PropSeg/
- sct_registration_multimodal:
  - https://sourceforge.net/p/spinalcordtoolbox/wiki/registration_tricks/
- PAM50 template + spinal levels + white matter template
  - https://sourceforge.net/p/spinalcordtoolbox/wiki/Spinal_levels/
  - more info in SCT course
- sct_dmri_separate_b0_and_dwi
  - pretty pic: https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_dmri_separate_b0_and_dwi/
