### ISSUE TITLE
msct_parser doesn't show arguments of type 'multiple_choice' in the example

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#283]
![doc_asman](https://cloud.githubusercontent.com/assets/5857909/6811824/206bbef2-d241-11e4-8420-c559b533bfd7.png)

In sct_asman doc (on branch sd_graymatterseg_new) : 
Here -model is a mandatory argument of type 'multiple_choice', it should appear in the example command line.

**Comment by benjamindeleener** [comment]
fixed on master
