### ISSUE TITLE
sct_fmri_moco  0 value, no correction

### ISSUE THREAD

**Issue by CarolineLndl** [neuropoly/spinalcordtoolbox#2831]
Hi, I'm having some problems with the fmri_moco function (sct V4.3 ) 
All outputs are generated but correction did not take place.  The time series are the same as before MOCO and the .tsv file has only 0 values. Do you know where this weed might have come from?
I use it on Ubuntu 16.04.5 Xenial LTS, with Jupiter Lab Notebook (Python 3.7), 

My code:
```
params_moco = 'poly=0,smooth=1,metric=MeanSquares,gradStep=1,sampling=0.2 
param_group = 1 # Group nvols successive volumes of fMRI for more robustness. Default value = 1
sct.run('sct_fmri_moco -i {} -m {} -param {} -ofolder {} -g {} -r 1'.format(Func_stc_sc, func_stc_sc_mask, params_moco, MOCO_folder, param_group))
```

Nb : I check with exactly the same images and code on Mac (v 10.15.6 ) with Jupiter Notebook (Python 3.7) and everything works fine ! Another difference between the two is that on Mac, the input_T00XX.nii files are generated in the input folder (not in a tmp folder) but not on Ubuntu.

I don't really understand where the problem comes from
Perhaps you have some suggestions?

Thank you for your help

**Comment by jcohenadad** [comment]
Hi @CarolineLndl 

Thank you for reporting feedback. Please note that this issue has already been raised in the forum: https://forum.spinalcordmri.org/t/sct-fmri-moco-with-poly-0/427

Then, an issue was opened here: https://github.com/neuropoly/spinalcordtoolbox/issues/2779, and has been fixed a few days ago, details here: https://github.com/neuropoly/spinalcordtoolbox/pull/2821

The changes are already available in the master branch, or if you prefer to wait for a stable release, there should be one in 1-2 weeks.
