### ISSUE TITLE
Fetching version.txt from site-package does not work for RTD

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2832]
Context: https://github.com/neuropoly/spinalcordtoolbox/pull/2814#discussion_r466113927

In `spinalcordtoolbox.utils`, the version is fetched using `os.path.join(__sct_dir__, 'version.txt')`, which, for a pip-installed package, is pointing to `envs/sct-env/lib/python3.6/site-packages/version.txt`, but the file does not exist there.

A solution (anticipating a `pip install spinalcordtoolbox` in the long term) would be to:
- move `version.txt` inside `spinalcordtoolbox/`, so it is automatically copied with pip install
- edit `spinalcordtoolbox.utils` to point to this new location

**Comment by jcohenadad** [comment]
What I don't understand is: what is the purpose of having a `MANIFEST.in` (where version.txt is listed) file if we don't use it to include the files in the package?

**Comment by kousu** [comment]
I know from scavenging github that the pypa core devs want to recommend https://pypi.org/project/setuptools-scm/ for getting a version-plus-git-revision out of your codebase. In https://github.com/shimming-toolbox/shimming-toolbox-py/pull/19 I went with a different option, also suggested [here](https://packaging.python.org/guides/single-sourcing-package-version/).

**Comment by kousu** [comment]
> What I don't understand is: what is the purpose of having a `MANIFEST.in` (where version.txt is listed) file if we don't use it to include the files in the package?

MANIFEST.in is meant to collect additional files:

https://packaging.python.org/guides/using-manifest-in/#using-manifest-in

> The following files are included in a source distribution by default:
> [...]
> all Python source files implied by the py_modules and packages setup() arguments
> README.md
> [...]

Hmm. version.txt should have been included as written. If you move it under spinalcordtoolbox/ it will no longer be covered by MANIFEST.in. If it wasn't there's a different issue.

But also: I'd vote to toss it out and use a more canonical solution.

**Comment by jcohenadad** [comment]
@kousu yup! whatever you recommend is fine by me. pls take over my branch

**Comment by jcohenadad** [comment]
> Hmm. version.txt should have been included as written. If you move it under spinalcordtoolbox/ it will no longer be covered by MANIFEST.in. If it wasn't there's a different issue.

by moving version.txt i also updated the path in MANIFEST.in (and anywhere else in the code) https://github.com/neuropoly/spinalcordtoolbox/pull/2833
