### ISSUE TITLE
Some scripts are incorrectly calling generate_output_file (`squeeze_data` is set by verbose parameter)

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2851]
### Description

In some calls to `sct_utils.generate_output_file`, verbose is specified as a positional arg rather than a keyword arg. This is a problem, because this is actually setting `squeeze_data` instead. 

This can cause bugs when `verbose==False`, because it inadvertently sets `squeeze_data` to False. See below for an example of such a bug:

<details>
<summary> Original issue description hidden. Click to show </summary>

### Original description

While working on #2676, I noticed this bug. Modiying this line here to use the `-v` option:

https://github.com/neuropoly/spinalcordtoolbox/blob/bf3de687c20ac86717de3584296af1931e247784/testing/test_sct_dmri_separate_b0_and_dwi.py#L24

With `True`, `1`, `2`, etc. tests pass successfully:

```bash
Will run through the following tests:
- in parallel with 1 jobs: sct_dmri_separate_b0_and_dwi
Checking sct_dmri_separate_b0_and_dwi...............[OK]
status: [0]
Finished! Elapsed time: 3s
```

With `False`/`0`, tests give a warning because of an extra dimension in the output image:

```bash
Checking sct_dmri_separate_b0_and_dwi...............[WARNING]
   
   ====================================================================================================
   sct_dmri_separate_b0_and_dwi -i dmri/dmri.nii.gz -bvec dmri/bvecs.txt -a 1 -r 0
   ====================================================================================================
   
   
   --
   Spinal Cord Toolbox (git-jn/2676-change-verbosity-c8d4c656f96f9c9b3627381cd09285d22b0d1b61*)
   
   sct_convert -i /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri/dmri.nii.gz -o /tmp/sct-20200818101936.565183-dmri_separate-h4ctjg0v/dmri.nii
   
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0.nii.gz
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi.nii.gz
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0_mean.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_b0_mean.nii.gz
   WARNING: File /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi_mean.nii.gz already exists. Deleting it...
   File created: /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/dmri_dwi_mean.nii.gz
   
   ====================================================================================================
   INTEGRITY TESTING
   ====================================================================================================
   
   Checking DWI
   --> PASSED
   
   Checking b=0
   operands could not be broadcast together with shapes (40,42,5) (40,42,5,1) 
status: [99]
Failures: sct_dmri_separate_b0_and_dwi
Finished! Elapsed time: 3s
```

I'm not sure why verbosity would have an effect like this, but I am investigating the cause.

</details>

**Comment by joshuacwnewton** [comment]
I've narrowed down the issue to this line:

**Comment by joshuacwnewton** [comment]
I've narrowed down the issue to this line: 

https://github.com/neuropoly/spinalcordtoolbox/blob/bf3de687c20ac86717de3584296af1931e247784/scripts/sct_dmri_separate_b0_and_dwi.py#L210

Manually setting `verbose=True` here fixes the issue. So, it looks like the problem lies with `sct.generate_output_files` and not `sct_dmri_separate_b0_and_dwi`. I'll see if I can narrow it down further.

**Comment by joshuacwnewton** [comment]
Aha! The issue is, `verbose` wasn't actually setting verbose here. Take a look at the function signature:

https://github.com/neuropoly/spinalcordtoolbox/blob/bf3de687c20ac86717de3584296af1931e247784/scripts/sct_utils.py#L708

4 input arguments, but only 3 were passed (see above). So, verbose was actually setting `squeeze_data`, which makes given that the output shape changes.

I'll create a quick PR for this so that verbosity is explicitly set as a kwarg in these calls.

**Comment by joshuacwnewton** [comment]
It looks like many scripts are also accidentally setting `squeeze_data` with their verbosity parameter. I'll make sure my PR fixes all instances of this.

**Comment by jcohenadad** [comment]
wow! great catch @joshuacwnewton 🎉 
that reinforces the idea of
- getting rid of the verbose flag #2853 
- try to use explicit argument names (e.g. `key=value` instead of `value`) whenever possible
