### ISSUE TITLE
Organize SCT development documentation between ReadTheDocs, GitHub Wiki, and DokuWiki

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2856]
> **Note:** This issue follows discussion from the 2020-08-06 NeuroPoly lab meeting **[Add link if meeting minutes can be public]**

### Description

Documentation related to SCT usage/development is currently spread across three sources: [ReadTheDocs (`spinalcordtoolbox.com`)](https://spinalcordtoolbox.com/en/latest/), the [GitHub Wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki), and NeuroPoly's [DokuWiki](https://www.neuro.polymtl.ca/tips_and_tricks). Legacy sources also include a [SourceForge Wiki](https://sourceforge.net/p/spinalcordtoolbox/wiki/) and older revisions of `README.md` (see #2814), but SCT is moving away from both.

There is still some overlap between these sources, where certain information is in multiple places at once. I believe It could be better for each category of information to only have 1 home (i.e. having a single source of truth for each category). So, this issue is meant to discuss what kinds of information should go in each source, and to identify any pages that should be moved.

### Existing documentation structure

|  | SCT ReadTheDocs | SCT GitHub Wiki | NeuroPoly DokuWiki (Tips and Tricks page) |
|-|-|-|-|
| Audience | SCT users _(of CLI scripts and `spinalcordtoolbox` package)_ | SCT contributors | NeuroPoly lab members |
| Content Types | <ul> <li>Theory (e.g. coordinate systems, templates)</li> <li>Installation</li> <li>CLI script usage</li> <li>spinalcordtoolbox Python API</li> <li>Links to past workshops</li> <li>**Contributing guide** _(Move to GH Wiki?)_</li> <li>**Development notes** _(Move to GH Wiki?)_</li> </ul> | <ul> <li>Installation (for development)</li> <li>Testing</li> <li>Git/GitHub usage (branches, releases)</li> <li>**Programming: general Python tips** _(Move to DokuWiki?)_ <li>Programming: module-specific conventions</li> <li>Notes about SCT's project/directory structure</li> <li>Notes about building/distributing SCT (e.g. ANTs binaries)</li> <li>Project management (ongoing SCT contributor roles/tasks)</li> <li>**Installation for Win10/WSL** _(Move to RTD?)_ <li>**How to use internal research tools, e.g. Compute Canada** _(Move to DokuWiki?)_</li> </ul> | <ul> <li>Git/GitHub usage (introductory tips)</li> <li>Python usage (general style tips)</li> <li>How to use internal research tools, e.g. Compute Canada</li> <li>... and many more software tools, e.g. Docker, FSL, ANTs, OpenNeuro, etc.</li> </ul> |

### Suggestions

The biggest suggestion I want to make here is **moving the Contributing guide to the GitHub Wiki** instead of on RTD/`spinalcordtoolbox.com`. Since the GH Wiki is where most of our contributor information already exists, I think moving the guide could be helpful for consolidating all of the contributor-focused information in one place. Then, on `spinalcordtoolbox.com`, we could replace that page with a note that says something like "Interested in contributing to SCT? Check out our project wiki! [link]"  

For an example of a big project that does this, check out [AngularJS](https://github.com/angular/angular.js/wiki) (also, see #2855 for a related idea on how this could be organized.)

**Comment by joshuacwnewton** [comment]
@jcohenadad @cfhammill @kousu @Drulex Interested in your feedback considering these are pages that we'll all refer to many times in the past/present/future.

**Comment by Drulex** [comment]
I agree with your suggestion to move the contribution stuff to github @joshuacwnewton. RTD is for the consumers of the software and API. Github wiki is mainly for contributors of the project.

**Comment by jcohenadad** [comment]
I could be sold on centralizing the developer material under the wiki. Some thoughts:

Pros:
- the wiki is easier to edit (no need to go through a PR)
- developers are "already" on github

Cons:
- the API doc _needs_ to stay in RTD (because of the automatic formatting), and developers need it.

Additional info:
- another project led by the lab centralizes dev info under its wiki: https://github.com/qMRLab/qMRLab/wiki

Additional note:
- this whole discussion started with something even bigger: the high developer material duplication between many other python projects in the lab: 
  - https://shimming-toolbox.org/en/latest/3_contributing/CONTRIBUTING.html
  - https://github.com/neuropoly/axondeepseg/blob/master/CONTRIBUTING.rst
  - https://ivadomed.org/en/latest/contributing.html
  - https://spinalcordtoolbox.com/en/latest/dev_section/CONTRIBUTING.html
- the list above does not include all the wiki material, which is also highly duplicated...
- it would be fantastic to find a mechanism to only deal with one source (with minor alterations that are project-specific). I don't have any good idea here... 🤔

**Comment by joshuacwnewton** [comment]
> Cons:
> * the API doc needs to stay in RTD (because of the automatic formatting), and developers need it.

Is this a "Con" necessarily? I think the API stuff staying on RTD (as you mention) actually makes the most sense, because in my head I'm thinking of 2 types of developers:
1. Developers who are contributing to SCT
2. Developers who are just using the Python API (I group them in with "users" in my head)

The API page is for 2., while the GitHub Wiki is for 1., so no need to move? 🙂

**Comment by joshuacwnewton** [comment]
> this whole discussion started with something even bigger: the high developer material duplication between many other python projects in the lab:

Good point! The natural suggestion that comes to mind would be to migrate GitHub Wiki content to the DokuWiki, just because the DokuWiki is the one place that unifies the NeuroPoly lab. 
```
* People
* Research
* Publications
* Open source development
    * Contributing guide
* Facilities
* Collaborations
* Links
* Contact
* Job opportunities
* Tips & Tricks
* Internal Resources
```
Essentially expanding the previous `Downloads` section to an `Open source development` section or similar. The only trouble there is, if we have project-specific details for many projects, the structure of the DokuWiki could get complex quite quickly, with many nested pages. So, it could become tricky to navigate.

**Comment by jcohenadad** [comment]
> Essentially expanding the previous Downloads section to an Open source development section or similar. The only trouble there is, if we have project-specific details for many projects, the structure of the DokuWiki could get complex quite quickly, with many nested pages. So, it could become tricky to navigate.

Agreed. And the dokuwiki is not as nice as github/markdown. So let's focus on moving this material to the github wiki, and find a way to "easily diff" across project's wikis so that when one wiki gets updated with useful material that could benefit all projects, there is an easy mechanism to update the other wikis (is that a realistic wish?)

**Comment by joshuacwnewton** [comment]
> Agreed. And the dokuwiki is not as nice as github/markdown. So let's focus on moving this material to the github wiki, and find a way to "easily diff" across project's wikis so that when one wiki gets updated with useful material that could benefit all projects, there is an easy mechanism to update the other wikis (is that a realistic wish?)

On second thought, with today's meeting, and discussion of onboarding for new students, I was curious about the DokuWiki again. So, I've created a "first draft" of a centralized Contributing guide on the DokuWiki, to be potentially used for all the projects.

* [NeuroPoly Contributing Guide](https://www.neuro.polymtl.ca/open_source/contributing) with most of the information from `CONTRIBUTING.rst`.
* Reference from [the SCT GitHub Wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki/Contributing)

I'm flexible about this of course! This was mostly just to demonstrate the idea. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
I think the core of this issue (overlap between documentation sources) has been addressed.

There is still work to be done to align NeuroPoly projects (e.g. common contributing docs, issue/PR labels, etc.) but that's a much bigger effort beyond the scope of this SCT issue.
