### ISSUE TITLE
Consider both config file and additional flags

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2860]
From: https://github.com/sct-pipeline/csa-atrophy/pull/57#issue-473366862

> It seems that sct_run_batch does not iterate throught the include_list when flag -config is also called. Therefore, i have included the creation of a config_file in run_all.py.

@cfhammill do you confirm? If so, it would be nice to be able to use both a config file, and also set up flags (and, as mentioned in the usage, if the same flag is listed in the config file, it supersedes the flag).

**Comment by PaulBautin** [comment]
No problem with sct_run_batch. The trick was to write a subject list with no brackets and no commas.

**Comment by jcohenadad** [comment]
^ justifying https://github.com/neuropoly/spinalcordtoolbox/issues/2854
