### ISSUE TITLE
Refactor sct_label_utils core logic in API

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2870]
Seems like this script contains lots of useful/re-use-able core logic that could be moved to its own API module.

```
$ grep 'sct_label_utils' scripts/*.py 
scripts/sct_apply_transfo.py:            sct.run(['sct_label_utils',
scripts/sct_create_mask.py:        status, output = sct.run(['sct_label_utils', '-i', 'point_RPI.nii', '-display'], verbose=param.verbose)
scripts/sct_create_mask.py:    cmd = ['sct_label_utils', '-i', 'line.nii', '-o', 'line.nii', '-create-add']
scripts/sct_label_utils.py:                    path_qc=os.path.abspath(path_qc), dataset=qc_dataset, subject=qc_subject, process='sct_label_utils')
scripts/sct_label_vertebrae.py:from sct_label_utils import ProcessLabels
scripts/sct_label_vertebrae.py:                      description='Initialize vertebral labeling by providing a nifti file that has a single disc label. An example of such file is a single voxel with value "3", which would be located at the posterior tip of C2-C3 disc. Such label file can be created using: sct_label_utils -i IMAGE_REF -create-viewer 3 ; or by using the Python module "detect_c2c3" implemented in "spinalcordtoolbox/vertebrae/detect_c2c3.py".',
scripts/sct_label_vertebrae.py:                sct.printv('Automatic C2-C3 detection failed. Please provide manual label with sct_label_utils', 1, 'error')
scripts/sct_qc.py:                                 'sct_detect_pmj', 'sct_label_utils', 'sct_get_centerline'),
scripts/sct_register_to_template.py:import sct_label_utils
scripts/sct_register_to_template.py:        sct_label_utils.main(args=['-i', ftmp_template_label_, '-vert-body', '0', '-o', ftmp_template_label])
scripts/sct_register_to_template.py:            sct.run(['sct_label_utils', '-i', ftmp_template_label, '-o', ftmp_template_label, '-remove-reference', ftmp_label])
scripts/sct_register_to_template.py:        sct.run(['sct_label_utils', '-i', ftmp_template_label, '-o', ftmp_template_label, '-remove-reference', ftmp_label])
scripts/sct_register_to_template.py:    processor = sct_label_utils.ProcessLabels(fname_labels)
scripts/sct_register_to_template.py:    sct.run(['sct_label_utils', '-i', fname_dest, '-create', label_new_list, '-v', '1', '-o', fname_output])
scripts/sct_testing.py:        'sct_label_utils',
```

Motivated by current refactor of `sct_register_to_template()` which uses it a lot. Also subprocess calls are useless (in this case) and add overhead + violate layering principles.

**Comment by Drulex** [comment]
@jcohenadad : in the `sct_label_utils` script, the argument parser is written in a way that allows the user to pass multiple optional arguments in combination, but the the processing code is written in a way that allows only one type of label processing be be performed:

https://github.com/neuropoly/spinalcordtoolbox/blob/c7ec03543192a110e3e3177ae7c4ecefb97600cf/scripts/sct_label_utils.py#L812-L873

This is probably because the script is legacy, that's ok I am planning on updating it, but I am not sure about certain things:
- Should the script support combination of label functions (daisy-chaining multiple label functions) on an input image? Right now if the user combines two actions (e.g. `-add` and `-create-add`) only the first action to be evaluated in the `if/elif` will be executed (in this case `-add`). Also the argument parser doesn't complain and the `-created-add` is silently ignored.
- Is there a specific script that I should use as template for writing the argument parser?

**Comment by jcohenadad** [comment]
> Should the script support combination of label functions (daisy-chaining multiple label functions) on an input image?

There is no need for it. As you rightfully noticed, for legacy reasons, we thought this script _could_ use daisy-chaining, but after several years of usage, we realize now that there is no need for it. 

So far, the only function that would dramatically benefit from daisy-chaining is `sct_maths`, where several operations (add, mul, dilate, etc.) could be applied to an input image, without having to launch the script several times (as it currently done in many pipelines).

> Is there a specific script that I should use as template for writing the argument parser?

I assume the fact that daisy-chaining is of the table, a template example is no more required?

**Comment by Drulex** [comment]
> I assume the fact that daisy-chaining is of the table, a template example is no more required?

Indeed, I was just wondering if there are any `sct` specific guidelines or style to follow. Looking at different scripts it's not exactly pure POSIX. Options seem preferred over positional arguments for example.

I will propose something that follows the current style while trying to minimize breaking compatibility with the current `sct_utils.py` script.

**Comment by jcohenadad** [comment]
> Indeed, I was just wondering if there are any `sct` specific guidelines or style to follow. Looking at different scripts it's not exactly pure POSIX. 

There is one [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming:-Code-style#cli-conventions) but it might not be up-to-date (also, i realize we should merge [this other page](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Dash-for-flags) there).

> Options seem preferred over positional arguments for example.

Indeed, this is currently the consensus. We could open a discussion issue on this
