### ISSUE TITLE
batch_processing.sh: FileNotFoundError: No such file or directory: 'mt1_crop.json'

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2883]
### Description

`./batch_processing.sh` now fails as a result of #2875.

I believe the cause is that `sct_example_data` was not updated to include the relevant `json` sidecar files. (Only `sct_testing_data` was updated, in https://github.com/neuropoly/spinalcordtoolbox/pull/2875/commits/b6d99e015e80aa9f497ee256a64b98b12d5a43c8.)

### Steps to Reproduce

* Check out a recent revision on `master`.
* Run `./batch_processing.sh`. Result:

```bash
# Compute MTsat
# Tips: Check your TR and Flip Angle from the Dicom data
sct_compute_mtsat -mt mt1_crop.nii.gz -pd mt0_reg.nii.gz -t1 t1w_reg.nii.gz -trmt 30 -trpd 30 -trt1 15 -famt 9 -fapd 9 -fat1 15
Traceback (most recent call last):
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_compute_mtsat.py", line 221, in <module>
    main(sys.argv[1:])
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_compute_mtsat.py", line 179, in main
    parser = get_parser(argv)
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_compute_mtsat.py", line 74, in get_parser
    get_json_file_name(parser.parse_known_args(argv)[0].mt, check_exist=True), 'RepetitionTime')
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_compute_mtsat.py", line 170, in fetch_metadata
    with open(fname_json) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mt1_crop.json'
```

**Comment by joshuacwnewton** [comment]
A side question: Why do we have separate `sct_testing_data` and `sct_example_data`? Is there a reason they can't be combined, considering that they are used for similar purposes? That way, in the future for similar changes, we only have to update one dataset.

**Comment by jcohenadad** [comment]
> I believe the cause is that sct_example_data was not updated to include the relevant json sidecar files. (Only sct_testing_data was updated, in b6d99e0.)

thanks for catching that!  this is actually a bug, because this change was supposed to provide cross-compatibility, ie: if the arguments are given (-trmt, -trpd, etc.), it should _not_ require the json file. 

> A side question: Why do we have separate sct_testing_data and sct_example_data? Is there a reason they can't be combined into a single dataset used for both sct_testing and batch_processing?

only reason is that `sct_testing_data` is smaller, and tests are run faster (smaller images, faster processing)
