### ISSUE TITLE
Indicate default values

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2884]
would be useful to indicate what are the default values, E.g.:
~~~
  -continue-on-error {0,1}     Whether the batch processing should continue if a subject fails.
~~~

**Comment by joshuacwnewton** [comment]
I think this might be a duplicate of #2756.

**Comment by jcohenadad** [comment]
it is-- i just opened the issue quickly without checking before (i was in the middle of something and didn't have time to do a thorough check)-- so yes, let's implement #2756 sooner rather than later (this would be a very useful feature)

**Comment by joshuacwnewton** [comment]
No worries about duplicates! The reason is very understandable, you do so much! :)
