### ISSUE TITLE
Non-scripts added to PATH

### ISSUE THREAD

**Issue by cfhammill** [neuropoly/spinalcordtoolbox#2890]
It looks like 5 python files living in the scripts directory aren't really scripts, but they get added to `PATH` by `pip` anyway.

- isct_get_fractional_volume
- msct_base_classes
- msct_gmseg_utils
- msct_parser
- sct_utils

**Comment by joshuacwnewton** [comment]
What installation are you experiencing this under? My current install of SCT is

```
-e git+https://github.com/neuropoly/spinalcordtoolbox.git@c9c7cb3abce38f54f329b3aeb827c38591d0cbd8#egg=spinalcordtoolbox
```

And I don't have those in my `PATH`. AFAIK, we manually specify every script to avoid this problem, too:

https://github.com/neuropoly/spinalcordtoolbox/blob/c9c7cb3abce38f54f329b3aeb827c38591d0cbd8/setup.py#L55-L114

**Comment by joshuacwnewton** [comment]
You raise a good point, though, considering we're treating the `scripts/` directory as a home for, well, console scripts. Regardless of whether they get added to `PATH`, I'm curious why non-scripts are there at all. It might be good to move/refactor this functionality on a case-by-case basis anyway.

#### isct_get_fractional_volume

A quick project-wide search shows that this is only used by one Python 2 script (`dev/atlas/validate_atlas/plot_abs_error_vs_fractional_volume`). Perhaps it should also be moved to `dev`? 

#### msct_base_classes

I can't find any usages of this.

#### msct_gmseg_utils

I can't find any usages of this either.

#### msct_parser

In theory, this shouldn't be needed once the argparse conversion is complete. I can take a look at this after #2842 is merged, before #1548 is closed.)

#### sct_utils

I think this functionality could be refactored into `spinalcordtoolbox/utils.py`. I'm not sure why we have two `utils` modules in the first place, actually.

_(As an aside, there are definitely [opinionated articles](https://breadcrumbscollector.tech/stop-naming-your-python-modules-utils/) out there about whether or not to even use `utils.py`.)_

**Comment by jcohenadad** [comment]
+1: all those scripts should not be exposed to the user

**Comment by cfhammill** [comment]
I was on master, perhaps it was because I'm in the virtual environment - or it is because I haven't deleted my sct `bin` directory since the scripts were explicitly listed. I think it's probably the latter.

**Comment by jcohenadad** [comment]
> or it is because I haven't deleted my sct bin directory since the scripts were explicitly listed

this happened to me several times 😅

**Comment by cfhammill** [comment]
This is related to https://github.com/neuropoly/spinalcordtoolbox/issues/2721

I think we should take the same approach and wait for the pip install to finalize.
