### ISSUE TITLE
Refactor functions from scripts/sct_utils.py into spinalcordtoolbox/utils.py

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2898]
### Description

> **Note**: Continuation of discussion from https://github.com/neuropoly/spinalcordtoolbox/issues/2627#issuecomment-596239336 and https://github.com/neuropoly/spinalcordtoolbox/issues/2890#issuecomment-692213618. 
> I believe this is already an ongoing effort -- this issue simply provides a centralized place for design discussion.

Currently we have two places we put assorted utility functions: `scripts/sct_utils.py` and `spinalcordtoolbox/utils.py`. In many cases, this functionality overlaps in theme (for example, file/directory-related functions are present in both). 

The `scripts/` directory is meant for CLI scripts, but `sct_utils.py` isn't actually a script. So, `spinalcordtoolbox/utils.py` seems like the more appropriate place for these functions. This would also match the organization encouraged by the ongoing Python API refactor, and potentially prevent issues like #2627.

### Alternatives

Some food for thought: It's possible that we should avoid having any sort of `utils.py` file at all. Instead, it may be better to be more specific about the role of each of these functions and group them thematically. See also this opinionated article: [Stop Naming Your Python Modules Utils](https://breadcrumbscollector.tech/stop-naming-your-python-modules-utils/) and its comments section.

__edit__: hijacked description by @Drulex for visibility
### Objectives
- [x]  Decouple logic in `sct_utils.py` into proper layers:
   - [x] API code should __not__ import `sct_utils.py`, instead it should import from other API modules. This avoids circular dependencies and other hidden problems such as #2922. 
   - [x] `sct_utils.py`, if it still exists, should only contain high-level utilities for other scripts (not for API modules) and only if those utilities don't belong in other scripts.
- [x] Remove unused/dead code
- [x] Cleanup imports as per PEP8
- [x] Utilities that belong in other modules should be moved from `sct.utils` to the appropriate module.
- [x] `spinalcordtoolbox.utils` can be further modularized if necessary (e.g `sct.utils.fs`, `sct.utils.shell`, `sct.utils.sys`, etc).

**Comment by jcohenadad** [comment]
@joshuacwnewton thank you for opening up this issue. The article [you mentioned above](https://breadcrumbscollector.tech/stop-naming-your-python-modules-utils/) makes fair points, and I was indeed anticipating that `utils` would become a dump for many un-related functions at some point, so yes: I'm open to alternatives.

**Comment by Drulex** [comment]
+1. There is a lot of API code that imports stuff from `sct_utils.py` which is a big no no.

**Comment by Drulex** [comment]
I added this to my backlog, but feel free to re-assign if you want @joshuacwnewton.

**Comment by Drulex** [comment]
Since the code from `sct_utils` is called from everywhere I will attack it chunk by chunk, making multiple PRs with isolated changes to avoid conflicts.
