### ISSUE TITLE
spinalcordtoolbox/gui/cli.py: CLI script hiding in the SCT Python API

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2904]
### Description

We store CLI scripts in the `scripts/` folder. However, there is another CLI script hidden away in `spinalcordtoolbox/gui/` called [`cli.py`](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/gui/cli.py). The purpose of this script is to manually label either a sagittal or centerline image. 

https://github.com/neuropoly/spinalcordtoolbox/blob/432bbc681d8f7fdb27d007f0f782eaf0285582be/spinalcordtoolbox/gui/cli.py#L62-L63

Some of this functionality is mirrored in the `-create-viewer` process in `sct_label_utils`, though:

https://github.com/neuropoly/spinalcordtoolbox/blob/432bbc681d8f7fdb27d007f0f782eaf0285582be/scripts/sct_label_utils.py#L737-L742

That argument results in a call to this `sct_label_utils` function, which is almost identical to `spinalcordtoolbox/gui/cli.py`, but with just `launch_sagittal_dialog` and not `launch_centerline_dialog`:

https://github.com/neuropoly/spinalcordtoolbox/blob/432bbc681d8f7fdb27d007f0f782eaf0285582be/scripts/sct_label_utils.py#L637-L650

We should handle this redundancy somehow, either by:

* Adding the missing `launch_centerline_dialog` functionality to `sct_label_utils`
* Removing `spinalcordtoolbox/gui/cli.py` if the extra functionality is not needed.

**Comment by Drulex** [comment]
I think we can just delete `cli.py`. It is not used anywhere and the last commit was 2 years ago. I think @jcohenadad gave the verbal ok during one of the dev meetings.

**Comment by jcohenadad** [comment]
now you have my written ok 😊
