### ISSUE TITLE
Argument error in sct_label_utils

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#2905]
### Description of the issue
The script `sct_label_utils` fails when using it. As shown below, the script raises an Argument error on one of the parameter of the function, even if it is not used.

### Steps to Reproduce

0. Install SCT <release or git revision and platform, you can use the
   first lines of output of sct_check_dependencies>

1. On any image, try the following command:
```
sct_label_utils -i input_image -o output_image -create-viewer 1,2,3
```

**Expected behavior:** <What you expect to happen>
A GUI opens to perform manual labeling.

**Actual behavior:** <What actually happens>
An Argument error on `remove_symm` occurs.
```
--
Spinal Cord Toolbox (git-master-432bbc681d8f7fdb27d007f0f782eaf0285582be)

Traceback (most recent call last):
  File "/Users/benjamindeleener/code/spinalcordtoolbox/scripts/sct_label_utils.py", line 945, in <module>
    main()
  File "/Users/benjamindeleener/code/spinalcordtoolbox/scripts/sct_label_utils.py", line 897, in main
    elif arguments.remove_symm is not None:
AttributeError: 'Namespace' object has no attribute 'remove_symm'
```

Easy fix: it's a spelling mistake between the parser and the main function.

**Comment by Drulex** [comment]
This module has been refactored in https://github.com/neuropoly/spinalcordtoolbox/pull/2887. The error doesn't exist in the refactored version.
