### ISSUE TITLE
Deprecate sct_concat_transfo.py and refactor callers

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2912]
Needed by #2873

**Comment by Drulex** [comment]
Looks like this is a light wrapper for the `isct_ComposeMultiTransform` binary. Is `sct_concat_transfo.py` still relevant to users @jcohenadad? If not I would suggest getting rid of the indirection and make the calls to `isct_ComposeMultiTransform` directly in the scripts (right now it's only used in `sct_register_to_template.py`).

Ideally the functionality of `isct_ComposeMultiTransform` should move to the API, but for that we need #2007 which is something for later. It may not be worth to touch at `sct_concat_transfo.py` at all until then.

**Comment by jcohenadad** [comment]
> Is sct_concat_transfo.py still relevant to users @jcohenadad?

i don't think users often use that functionality, but they could (and we advertise it). Eg: if they use a 3rd party software to perform a registration (eg FSL), and the SCT to perform another registration, they will want to concatenate those transformations. But, that being said, SCT's batch_processing script does not feature this CLI. I was curious and also looked at our [script repository](https://github.com/search?q=org%3Asct-pipeline+sct_concat_transfo), and did not notice any usage of sct_concat_transfo.  To be even more confident, i've searched it in our [user forum](https://forum.spinalcordmri.org/search?q=sct_concat_transfo%20category%3A8), and the term only appears during sct_testing. So i think it is fair to assume that the function is not used, and if one day a user needs it, we can advise them to use `isct_ComposeMultiTransform`.

**Comment by jcohenadad** [comment]
@Drulex considering [this user feedback](https://forum.spinalcordmri.org/t/sct-concat-transfo-in-or-not-in-sct-v5-0-1/600/4?u=jcohenadad) (he is probably not the only one), should we consider putting back this CLI?

**Comment by Drulex** [comment]
> @Drulex considering [this user feedback](https://forum.spinalcordmri.org/t/sct-concat-transfo-in-or-not-in-sct-v5-0-1/600/4?u=jcohenadad) (he is probably not the only one), should we consider putting back this CLI?

I don't see a problem with keeping the `sct_concat_transfo.py` script as a light wrapper for `isct_ComposeMultiTransform`. The codebase has already been refactored to remove the indirection and call `isct_ComposeMultiTransform`, at this point the script would only be there for user convenience.

**Comment by jcohenadad** [comment]
cool, so let's put it back then. Do you mind doing it? thanks!

**Comment by Drulex** [comment]
> cool, so let's put it back then. Do you mind doing it? thanks!

Yes sure.

**Comment by joshuacwnewton** [comment]
Closing, as `sct_concat_transo` has been restored.
