### ISSUE TITLE
Clean up GitHub Issue/PR labels to match other NeuroPoly projects

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2915]
> **Note:** This is mostly for to-do tracking so that already ongoing work is properly documented. 

Each NeuroPoly project has a slightly different approach to issue/PR labeling. _(SCT's current guidelines are on the [**Contributing: Labelling issues and pull requests**](https://github.com/neuropoly/spinalcordtoolbox/wiki/Contributing%3A-Labelling-issues-and-pull-requests) page.)_

There is some ongoing Slack discussion between projects to settle on a unified label convention for all the projects. The checklist below provides some ideas/tasks for work to do in the SCT repo to bring the labels more in line with other projects.

- Category labels (dark purple, white text)
    - [x] Add `category:` to the description of **Category** labels for easier filtering 
    - [x] Convert the `meta` label into a `git/github` category label
    - [x] Convert the `travis` label into a `CI` category label (to include GitHub Actions)
    - [x] Add a `refactoring` label to distinguish code structure changes from `enhancement` changes
        - [x] Relabel any `enhancement` refactors to `refactoring`.
- Context labels (light purple, dark text)
    - [x] Add `context:` to the descriptions for easier filtering, and to match [ADS labels](https://github.com/neuropoly/axondeepseg/labels?q=context%3A)
    - [x] Create new labels for `spinalcordtoolbox` API sections
- [x] Remove `card:` labels, because they are rarely used
    - [x] Turn `card:DESIGN DISCUSSION` into it's own label, perhaps `needs-discussion`, because this one is used!
- [x] Remove `fix:` labels, because they are rarely used
- [x] Update the Wiki with new guidelines

**Comment by jcohenadad** [comment]
Oftentimes I'm not sure which label to use when it is about refactoring, removing stuff. Eg #2914 
Should we rename "enhancement" as "refactoring"? and include enhancement in refactoring?

**Comment by joshuacwnewton** [comment]
@jcohenadad AxonDeepSeg uses this description for their [`enhancement` category](https://github.com/neuropoly/spinalcordtoolbox/labels?q=enhancement):

> category: the change expands an existing functionality or refactoring

So, your intuition is correct. :smile:

**Comment by joshuacwnewton** [comment]
My one question: is there an "enhancement" that wouldn't fall under refactoring? 

I guess an improvement that couldn't be labelled `refactoring` would just be labelled `feature` instead, so I think this makes sense to me.

**Comment by jcohenadad** [comment]
> So, your intuition is on-point. Perhaps the name for the label could be clearer, though, as you point out.

actually, i was the one who edited the ADS label description this morning 😉 ; then i let Marie-Hélène know that she should contact you so we can harmonize this across projects

**Comment by joshuacwnewton** [comment]
@jcohenadad On second thought, looking at the issues tagged with `enhancement`, there are a lot that wouldn't fit into `refactoring`. So, I think this should actually be 2 categories.

* `enhancement`: Makes an improvement to an existing feature (including performance improvements)
* `refactoring`: Improves the structure/organization without changing functionality

The difference being "does the user notice a change in results/functionality". If yes, `enhancement`, if no, `refactoring`.

**Comment by joshuacwnewton** [comment]
Also, on the topic of category changes, I think there are a few other categories that could be added:

* `documentation-internal`: To differentiate between <readthedocs/sourceforge/courses> issues and <internal dev docs/github wiki> issues
* `git/github`: Replaces the `meta` label, which wasn't a category, but probably should have been.
* `CI`: Replaces the `travis` label, which wasn't a category, but probably should have been. This also allows us to include GitHub Actions and not just Travis.

**Comment by joshuacwnewton** [comment]
I have removed 3 labels:
* `regression`: A subset of `bug` that had hardly been used.
* `question`: Only 1 user has ever asked a question using an issue. For SCT, our users will typically ask on [spinalcordmri.org forum](https://forum.spinalcordmri.org/), so this label is not as useful in our case.
* `help wanted`: No open issues had this label, and previously, it had only been used on issues from 2014. This could be revived if we begin to see contributions from the developer community, but even in that case, `good first issue` serves a similar purpose for onboarding.

**Comment by joshuacwnewton** [comment]
I have modified the wiki page ([**Labelling issues and pull requests**](https://github.com/neuropoly/spinalcordtoolbox/wiki/Contributing%3A-Labelling-issues-and-pull-requests)) to reflect the recent changes. 

The page now covers all of the labels in the project (with updated filtering links).

**Comment by joshuacwnewton** [comment]
I'm wondering if `testing` should not be a category label (dark purple), but instead a context label (light purple).

The reason I think this is, `testing` is often combined with other categories. For example, I see `enhancement` + `testing` a lot (an improvement to a test) and `bug` + `testing` (an error in a test). That's why I think it might be better suited to a context label.

**Comment by jcohenadad** [comment]
> I'm wondering if `testing` should not be a category label (dark purple), but instead a context label (light purple).
> 
> The reason I think this is, `testing` is often combined with other categories. For example, I see `enhancement` + `testing` a lot (an improvement to a test) and `bug` + `testing` (an error in a test). That's why I think it might be better suited to a context label.
> 
> I've changed it for now, but this is easily reversible, so let me know if it doesn't fit well.

that makes perfect sense to me. +1

**Comment by joshuacwnewton** [comment]
I've done all that I was hoping to do on SCT's end of things, so I'm closing this. But, further discussion should be had between maintainers of different NeuroPoly projects to coordinate differences in labelling choices. 

I'll stay in contact with @mariehbourget regarding ADS and we can go from there. :)

**Comment by jcohenadad** [comment]
Thank you @joshuacwnewton! tagging @po09i and @charleygros @andreanne-lemay so we can also port these awesome initiatives to shimming-toolbox and ivadomed
