### ISSUE TITLE
Wrong usage of arguments from parser

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2926]
While investigating #2925 I found the root cause to be the following (line 116):

https://github.com/neuropoly/spinalcordtoolbox/blob/c6e489e764ff54244bb5c6abc3a010c6412d520e/scripts/sct_fmri_compute_tsnr.py#L114-L119

`parse_args()` converts argument strings to objects and assign them as attributes of the namespace, therefore the check should be `if arguments.o is not None:` instead. At the moment this piece of code will always run the `else` clause.

We should check for other similar hidden bugs.

**Comment by joshuacwnewton** [comment]
Ah, shoot, that's on me. Thank you for catching this. I'll take this on. :)

**Comment by Drulex** [comment]
Ok @joshuacwnewton  thanks a lot. See below notes I had gathered so far:

https://github.com/neuropoly/spinalcordtoolbox/blob/c6e489e764ff54244bb5c6abc3a010c6412d520e/scripts/sct_dice_coefficient.py#L128

https://github.com/neuropoly/spinalcordtoolbox/blob/c6e489e764ff54244bb5c6abc3a010c6412d520e/scripts/sct_image.py#L322

https://github.com/neuropoly/spinalcordtoolbox/blob/c6e489e764ff54244bb5c6abc3a010c6412d520e/scripts/sct_maths.py#L256

Also a non-standard usage: https://github.com/neuropoly/spinalcordtoolbox/blob/c6e489e764ff54244bb5c6abc3a010c6412d520e/scripts/sct_deepseg.py#L118-L155
