### ISSUE TITLE
Documentation showing error.

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2927]
https://spinalcordtoolbox.com/en/latest/user_section/command-line.html#sct-register-to-template 
Shows an error text and not the actual documentation.

**Comment by jcohenadad** [comment]
oopsi 😬 , thanks for catching that (and for reporting it!) @lrouhier !

**Comment by joshuacwnewton** [comment]
My apologies. This has to do with one of my changes during the argparse conversion, see: https://github.com/neuropoly/spinalcordtoolbox/pull/2842/commits/4e97be6af8af5498da04fb50c51b497c7748eae9.

The SCT course Slideshare links were replaced with iCloud links, but the iCloud links contain the `%` character. Apparently `argparse` throws a bit of a fit with `%` in help description strings, see also [[link 1]](https://thomas-cokelaer.info/blog/2014/03/python-argparse-issues-with-the-help-argument-typeerror-o-format-a-number-is-required-not-dict/), [[link 2]](https://stackoverflow.com/questions/21168120/python-argparse-errors-with-in-help-string).

I'll start on this ASAP.

**Comment by jcohenadad** [comment]
wow! that's an evil bug 🐞 

another incentive to move away from icloud for SCT course (i'm already salivating at our future datalad-like SCT course 😛)
