### ISSUE TITLE
sct_utils: display_viewer_syntax is printing incorrect commands

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2929]
### Description

`sct_utils` has a function `display_viewer_syntax`

https://github.com/neuropoly/spinalcordtoolbox/blob/c3054eb25ab9befc920446be8282bac05ccfb2a4/scripts/sct_utils.py#L329-L332

It can output, for example, a `fsleyes` command. e.g. if I run:

```bash
sct_label_vertebrae -i t2/t2.nii.gz -s t2/t2_seg-manual.nii.gz -c t2 -initfile t2/init_label_vertebrae.txt -t template -qc testing-qc
```

I get the following output:

```bash
Done! To view results, type:
fsleyes /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/t2/t2.nii.gz -a 100.0 t2_seg-manual_labeled.nii.gz -cm subcortical -a 50.0 &
```

When I try to run this, `FSLEyes` tells me `unrecognized arguments: t2_seg-manual_labeled.nii.gz`. 

### Possible cause
<details>
<summary>EDIT: This is incorrect. Please disregard.</summary>

I think there are a couple things wrong with that command:

* Misplaced `&` character (at the end instead of the middle)
* `fsleyes` appears only once
* `t2_seg-manual_labeled.nii.gz` should use the absolute path

So, I think the proper command that should have been outputted is:

```bash
fsleyes /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/t2/t2.nii.gz -a 100.0 & fsleyes /home/joshua/Repos/spinalcordtoolbox/sct_testing_data/t2_seg-manual_labeled.nii.gz -cm subcortical -a 50.0
```

I believe this is a problem with the `display_viewer_syntax` function and not necessarily `sct_label_vertebrae`, i.e. this issue is probably appearing in the output of other scripts, too.

</details>

**Comment by Drulex** [comment]
I am fairly sure that the `&` is used to send the job in the background. The proposed command doesn't really make sense, it would run 2 instances of `fsleyes`, one in the background and one in the foreground.

The error you have is probably due to `t2_seg-manual_labeled.nii.gz` missing. It should be created in the working directory by `sct_label_vertebrae` script when you run it.

Can you try from a clean directory to check if the files are created properly?

For example:
```sh
sct_label_vertebrae -i ../sct_testing_data/t2/t2.nii.gz -s ../sct_testing_data/t2/t2_seg-manual.nii.gz -c t2 -initfile ../sct_testing_data/t2/init_label_vertebrae.txt -t ../sct_testing_data/template -qc testing-qc
```
Creates the following files:
```sh
ls -lah
total 3.4M
drwxr-xr-x  3 drulex drulex 4.0K Sep 29 07:51 .
drwxr-xr-x 29 drulex drulex  20K Sep 29 07:45 ..
-rw-r--r--  1 drulex drulex   80 Sep 29 07:51 straightening.cache
-rw-r--r--  1 drulex drulex 1.2M Sep 29 07:51 straight_ref.nii.gz
-rw-r--r--  1 drulex drulex 6.1K Sep 29 07:51 t2_seg-manual_labeled_discs.nii.gz
-rw-r--r--  1 drulex drulex 9.8K Sep 29 07:51 t2_seg-manual_labeled.nii.gz
drwxr-xr-x  5 drulex drulex 4.0K Sep 29 07:51 testing-qc
-rw-r--r--  1 drulex drulex 1.1M Sep 29 07:51 warp_curve2straight.nii.gz
-rw-r--r--  1 drulex drulex 1.2M Sep 29 07:51 warp_straight2curve.nii.gz
```

The `fsleyes` command works as expected in this case.

**Comment by joshuacwnewton** [comment]
My apologies! You're absolutely right. This was 100% an error and a misunderstanding on my part. Thank you for the clarification. :)

I had not executed the `fsleyes` command in the same working directory as where `t2_seg-manual_labeled.nii.gz` was output. So, perhaps the absolute path could be helpful here. But, everything else is working as intended, so I'll close this.

**Comment by jcohenadad** [comment]
> I am fairly sure that the & is used to send the job in the background. 

indeed, that's the purpose of the "&" (it's common to have several fsleyes windows opened when processing data)
