### ISSUE TITLE
Issue with generate_output_file (shutil.move: OSError: [Errno 18] Invalid cross-device link)

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2938]
### Description

[A user is reporting this issue on spinalcordmri.org](https://forum.spinalcordmri.org/t/registration-error-v-4-3/521). At first glance, it looks like they are using SCT across multiple different filesystems, which might be causing issues when we call `shutil.move`. 

I am still gathering information, but preliminary searching leads me to believe a fix might be needed on our end, because the issue seems very similar to https://github.com/ewels/MultiQC/issues/806, which suggests:

> `shutil.move` command doesn't work correctly if source and dest are in different file systems

There is some very useful analysis in this comment here: https://github.com/ewels/MultiQC/issues/806#issuecomment-601113985, and they were able to implement a fix here: https://github.com/ewels/MultiQC/pull/1130

I'm creating this issue in advance so that we can discuss, and to be able to quickly let the user know we are addressing their issue if need be.

### Steps to Reproduce

> TODO: Update based on response from user to [these questions](https://forum.spinalcordmri.org/t/registration-error-v-4-3/521/2?u=joshuacwnewton).

**Expected behavior:** Temporary files are copied successfully.

**Actual behavior:** Throws the following error:

<details>
<summary> Long console output hidden, click to show </summary>

```
Generate output files…
WARNING: File PAM50_t1_reg.nii.gz already exists. Deleting it…
File created: PAM50_t1_reg.nii.gz
WARNING: File subj01_eddy_fa_crop_reg.nii already exists. Deleting it…
Traceback (most recent call last):
File “/home/jnavas/sct_4.3/python/envs/venv_sct/lib/python3.6/shutil.py”, line 550, in move
os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: ‘/tmp/sct-20201006165629.329375-register-cws9p3au/dest_reg.nii’ -> ‘subj1_eddy_fa_crop_reg.nii’

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/home/jnavas/sct_4.3/scripts/sct_register_multimodal.py”, line 372, in
main()
File “/home/jnavas/sct_4.3/scripts/sct_register_multimodal.py”, line 348, in main
path_out=path_out)
File “/home/jnavas/sct_4.3/scripts/msct_register.py”, line 338, in register_wrapper
os.path.join(path_tmp, “dest_reg.nii”), os.path.join(path_out, file_out_inv + ext_dest), param.verbose)
File “/home/jnavas/sct_4.3/scripts/sct_utils.py”, line 749, in generate_output_file
shutil.move(fname_in, fname_out)
File “/home/jnavas/sct_4.3/python/envs/venv_sct/lib/python3.6/shutil.py”, line 564, in move
copy_function(src, real_dst)
File “/home/jnavas/sct_4.3/python/envs/venv_sct/lib/python3.6/shutil.py”, line 264, in copy2
copystat(src, dst, follow_symlinks=follow_symlinks)
File “/home/jnavas/sct_4.3/python/envs/venv_sct/lib/python3.6/shutil.py”, line 205, in copystat
follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by jcohenadad** [comment]
> I am still gathering information, but preliminary searching leads me to believe a fix might be needed on our end, because the issue seems very similar to ewels/MultiQC#806, which suggests:

I agree, it should be our responsibility to not assume that /tmp has write permission (IIUC the problem)

**Comment by joshuacwnewton** [comment]
The user has reported two things:

* "the /media/Data/ is a shared Server of my Insitute."
* "The script runs without errors on my local folder. So the problem was solved."

I no longer think that this is urgent, because this use-case (running script on one filesystem but accessing data on another) seems uncommon for our users, and the error itself is supposed to have been fixed with Python3 (see: [this stackoverflow comment chain](https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link/43967659#43967659)). Closing for now.
