### ISSUE TITLE
it would be nice to be able to have multiple choices with integer

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#294]
currently ALL our code has "if verbose:" statements, so it would be easier to allow that in the parser.

**Comment by jcohenadad** [comment]
for now, could be fixed by addind int() when retrieving arguments. E.g. for verbose.

**Comment by joshuacwnewton** [comment]
Closing, as this issue has been superseded by #2676. (As well as the conversion to `argparse` by #1548.)
