### ISSUE TITLE
Remove tests for scripts that do not exist anymore

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2948]
There are a number of tests in `testing/` that point to scripts that no longer exist:

* `test_sct_convert_binary_to_trilinear.py` (should this be `test_isct_convert_binary_to_trilinear`?)
* `test_sct_documentation.py`
* `test_sct_orientation.py`
* `test_sct_register_graymatter.py`

I presume these are no longer needed and can be removed (at least the last three, anyway)?

**Comment by GSantos23** [comment]
Hi, I would like to work in this one. Could you assign me this?

**Comment by jcohenadad** [comment]
Hi @GSantos23 👋   Thank you for your willingness to help. Yes, you are more than welcome to work on this one.

**Comment by GSantos23** [comment]
Hi guys, before doing the pull request I want to confirm if the file test_sct_convert_binary_to_linear.py have to be removed.

**Comment by joshuacwnewton** [comment]
@GSantos23 Yes, it can be removed. Also, there is a line in `sct_testing` that should be removed as well:

https://github.com/neuropoly/spinalcordtoolbox/blob/d94f602fe0b9466e656122f1bc554860002918ef/scripts/sct_testing.py#L410

Out of curiosity, are you participating in Hacktoberfest? If so, thank you for stopping by! :)

**Comment by GSantos23** [comment]
Hi @joshuacwnewton,, yes I am participating on Hacktoberfest.

I will do those changes as well.

Sorry for the late reply.

**Comment by joshuacwnewton** [comment]
> Sorry for the late reply.

No worries! We are all working asynchronously, so delays like that are normal. :)
