### ISSUE TITLE
Documentation: broken link to WSL doc

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2950]
Here: https://spinalcordtoolbox.com/en/latest/user_section/installation.html#install-on-windows-10-with-wsl

this link is broken: https://github.com/neuropoly/spinalcordtoolbox/wiki/SCT-on-Windows-10:-Installation-instruction-for-SCT-on-Windows-subsytem-for-linux

that's the good link: https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc:-SCT-on-Windows-10,-Installation-instruction-for-SCT-on-Windows-subsytem-for-linux

**Comment by joshuacwnewton** [comment]
Linking to the dev Wiki is tricky because the Wiki gets updated much more frequently than RTD (which has a slower update process).

If this info is meant for our users, I think it would be a good idea for the information to move to RTD (instead of living in the dev Wiki).

**Comment by jcohenadad** [comment]
> If this info is meant for our users, I think it would be a good idea for the information to move to RTD (instead of living in the dev Wiki).

👍
