### ISSUE TITLE
test_deepseg_gm error when moving import to top of file

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2954]
While doing some refactoring work I noticed the following: if the import below is moved at the top of the file instead of being lazily loaded, `test_deepseg_gm` will fail, but only if run in parallel with `test_deepseg_lesion.py`.

diff:
``` diff
diff --git a/spinalcordtoolbox/deepseg_lesion/core.py b/spinalcordtoolbox/deepseg_lesion/core.py
index 8bf1737b..c7bdd41b 100644
--- a/spinalcordtoolbox/deepseg_lesion/core.py
+++ b/spinalcordtoolbox/deepseg_lesion/core.py
@@ -13,7 +13,7 @@ from spinalcordtoolbox.image import Image, add_suffix, zeros_like, empty_like
 from spinalcordtoolbox.deepseg_sc.core import find_centerline, crop_image_around_centerline, uncrop_image, _normalize_data
 from spinalcordtoolbox import resampling
 from spinalcordtoolbox.utils import sct_dir_local_path, TempFolder
-
+from spinalcordtoolbox.deepseg_sc.cnn_models_3d import load_trained_model
 
 logger = logging.getLogger(__name__)
 
@@ -78,7 +78,6 @@ def apply_intensity_normalization(img, contrast):
 
 
 def segment_3d(model_fname, contrast_type, im):
-    from spinalcordtoolbox.deepseg_sc.cnn_models_3d import load_trained_model
     """Perform segmentation with 3D convolutions."""
     dct_patch_3d = {'t2': {'size': (48, 48, 48), 'mean': 871.309, 'std': 557.916},
                     't2_ax': {'size': (48, 48, 48), 'mean': 835.592, 'std': 528.386},

```

To reproduce: 
1. Move the `from spinalcordtoolbox.deepseg_sc.cnn_models_3d import load_trained_model` at the top of `spinalcordtoolbox/deepseg_lesion/core.py` (see diff above)
2. from the `venv` run `pytest unit_testing/test_deepseg_gm.py unit_testing/test_deepseg_lesion.py`

Error:
```
FAILED unit_testing/test_deepseg_gm.py::TestCore::test_segment_volume - ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 32, 200, 1), (None, 32, 200, 1), (None, 32, 200, 1), (None, 32, 200, 1), (None, 200, 200, 32), (None, 32, 200, 1)]
FAILED unit_testing/test_deepseg_gm.py::TestModel::test_create_model - ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 32, 200, 1), (None, 32, 200, 1), (None, 32, 200, 1), (None, 32, 200, 1), (None, 200, 200, 32), (None, 32, 200, 1)]
```

This does not occur if `test_deepseg_gm` is tested standalone (via `pytest unit_testing/test_deepseg_gm.py`)

**Comment by joshuacwnewton** [comment]
> `[(None, 32, 200, 1), (None, 32, 200, 1), (None, 32, 200, 1), (None, 32, 200, 1), (None, 200, 200, 32), (None, 32, 200, 1)]`

It looks like the 5th image is in a different format from the other images. (Assuming `H=32` and `W=200`, then some images are `(H, W, C)` and others are `(C, H, W)`.

Looking at `cnn_models_3d` (which we import from), there's a globally-scoped statement that changes the image data format for Keras's backend:

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L19

So, I think by doing the import earlier, this setting is invoked too early and messes up what `deepseg_gm` is trying to do.

**Comment by joshuacwnewton** [comment]
Interestingly, we use `"channels_first"` in some areas of SCT and `"channels_last"` in other areas, so we end up changing this in a few different places, e.g.:

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/unit_testing/test_deepseg_sc.py#L36

Because this is a global setting, there's potential for conflicts here.

**Comment by Drulex** [comment]
Good catch @joshuacwnewton. At first I suspected some kind of thread safety problem with `Keras` backend since this occurs only when the tests are run in parallel, but after adding some traces it appears that only one instance ok `keras.backend` is used. 

We are definitely calling `set_image_data_format()` twice with different values on the same backend during runtime. I am suspecting that the lazy import coincidentally masked this issue.

Maybe @charleygros or @jcohenadad know what the proper way to approach this?

**Comment by jcohenadad** [comment]
I would have to dig into it. Hopefully @charleygros or @perone have quick ideas.

Note that at some points these functions will be deprecated for `sct_deepseg` (the sooner the better)

**Comment by Drulex** [comment]
Out of curiosity I removed all references to `keras.backend.set_image_data_format()` and all the tests now pass. I'm thinking that either there is something wrong with the tests or the calls weren't necessary in the first place?

**Comment by joshuacwnewton** [comment]
> Out of curiosity I removed all references to `keras.backend.set_image_data_format()` and all the tests now pass. I'm thinking that either there is something wrong with the tests or the calls weren't necessary in the first place?

It looks like the `channels_last` call (https://github.com/neuropoly/spinalcordtoolbox/issues/2954#issuecomment-710082207) was needed only to undo the `channels_first` call (https://github.com/neuropoly/spinalcordtoolbox/issues/2954#issuecomment-710082175). _(You can trace from `test_deepseg_lesion` -> `deepseg_lesion.segment_3d` -> `cnn_models_3d.load_trained_model`.)_ So, I think if we can safely get rid of the `channels_first` call inside `cnn_models_3d`, then the `channels_last` call can go with it.

For the `channels_first` call, if I do a project-wide search for imports from `cnn_models_3d`, it looks like we only ever use `load_trained_model`, and the rest of the functions go unused. Maybe `K.set_image_data_format("channels_first")` was only relevant for a now-unused function?

**Comment by joshuacwnewton** [comment]
> For the `channels_first` call, if I do a project-wide search for imports from `cnn_models_3d`, it looks like we only ever use `load_trained_model`, and the rest of the functions go unused by SCT. So, maybe `K.set_image_data_format("channels_first")` is only relevant for a currently-unused function (e.g. `nn_architecture_seg_3d`).

@charleygros Could you clarify the purpose of the currently-unused functions (e.g. `nn_architecture_seg_3d`) in `cnn_models_3d.py`? Were they used in a training script somewhere outside of SCT to generate this model?

https://github.com/neuropoly/spinalcordtoolbox/blob/d9a8a88fb2e0a6462a46db572ed1e222fe1a4681/spinalcordtoolbox/deepseg_sc/core.py#L514-L515

**Comment by charleygros** [comment]
As said earlier, I am also suspecting the issue to come from `K.set_image_data_format()`.

We already had an issue very similar, see thread [here](https://github.com/neuropoly/spinalcordtoolbox/pull/2774#issuecomment-655229713).

**Comment by charleygros** [comment]
> @charleygros Could you clarify the purpose of the currently-unused functions (e.g. `nn_architecture_seg_3d`) in `cnn_models_3d.py`? Were they used in a training script somewhere outside of SCT to generate this model?

Correct: The architecture of the 3D Unet, used to trained the 3D models, is here as reference / documentation (we refer to it in the published paper: "the code is available at XX"). Unlike the 2D model ([here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/core.py#L344)), we are able to load the 3D model without referring to its architecture.

So.. in short: [nn_architecture_3d](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L33) is not used in the SCT rouine / scripts, but the `set_image_data_format()` ([here]([url](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L17)) is used when [loading](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L89) the 3D model.

**Comment by joshuacwnewton** [comment]
> Correct: The architecture of the 3D Unet, used to trained the 3D models, is here as reference / documentation (we refer to it in the published paper: "the code is available at XX"). Unlike the 2D model ([here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/core.py#L344)), we are able to load the 3D model without referring to its architecture.
> 
> So.. in short: [nn_architecture_3d](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L33) is not used in the SCT routine / scripts.

Thank you for the additional context!

I wonder if there might be a better place to store the architecture code such that it isn't impacted by changes in SCT. For example:

* The `dev/` folder.
* Its own repository. I notice we have, for example, [`vertebral-labeling-deep-learning`](https://github.com/neuropoly/vertebral-labeling-deep-learning)... would something like that be appropriate here? 

> I thought the `set_image_data_format()` ([here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L17)) was used / needed when [loading](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L89) the 3D model.

It's interesting to me, then, that the relevant test still passes even with the calls removed. Specifically, this test:

https://github.com/neuropoly/spinalcordtoolbox/blob/4776f1a1b01de5c06fb254f3ab852d95aa19414c/unit_testing/test_deepseg_sc.py#L21-L23

https://github.com/neuropoly/spinalcordtoolbox/blob/4776f1a1b01de5c06fb254f3ab852d95aa19414c/unit_testing/test_deepseg_sc.py#L28-L40

**Comment by joshuacwnewton** [comment]
I wanted to be more explicit about this, so I ran the test on both `master` and 4776f1a (most recent commit in #2955). I set a breakpoint in `segment_3d` and ran `model.summary()`.The model loading appears to be identical in both cases.

<details>
<summary> Output for both 4776f1a and `master`, click to show </summary>

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 1, 64, 64, 48 0                                            
__________________________________________________________________________________________________
conv3d_1 (Conv3D)               (None, 24, 64, 64, 4 672         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 24, 64, 64, 4 96          conv3d_1[0][0]                   
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 24, 64, 64, 4 0           batch_normalization_1[0][0]      
__________________________________________________________________________________________________
conv3d_2 (Conv3D)               (None, 48, 64, 64, 4 31152       activation_1[0][0]               
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 48, 64, 64, 4 192         conv3d_2[0][0]                   
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 48, 64, 64, 4 0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
max_pooling3d_1 (MaxPooling3D)  (None, 48, 32, 32, 2 0           activation_2[0][0]               
__________________________________________________________________________________________________
conv3d_3 (Conv3D)               (None, 48, 32, 32, 2 62256       max_pooling3d_1[0][0]            
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 48, 32, 32, 2 192         conv3d_3[0][0]                   
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 48, 32, 32, 2 0           batch_normalization_3[0][0]      
__________________________________________________________________________________________________
conv3d_4 (Conv3D)               (None, 96, 32, 32, 2 124512      activation_3[0][0]               
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 96, 32, 32, 2 384         conv3d_4[0][0]                   
__________________________________________________________________________________________________
activation_4 (Activation)       (None, 96, 32, 32, 2 0           batch_normalization_4[0][0]      
__________________________________________________________________________________________________
up_sampling3d_1 (UpSampling3D)  (None, 96, 64, 64, 4 0           activation_4[0][0]               
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 144, 64, 64,  0           up_sampling3d_1[0][0]            
                                                                 activation_2[0][0]               
__________________________________________________________________________________________________
conv3d_5 (Conv3D)               (None, 48, 64, 64, 4 186672      concatenate_1[0][0]              
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, 48, 64, 64, 4 192         conv3d_5[0][0]                   
__________________________________________________________________________________________________
activation_5 (Activation)       (None, 48, 64, 64, 4 0           batch_normalization_5[0][0]      
__________________________________________________________________________________________________
conv3d_6 (Conv3D)               (None, 48, 64, 64, 4 62256       activation_5[0][0]               
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, 48, 64, 64, 4 192         conv3d_6[0][0]                   
__________________________________________________________________________________________________
activation_6 (Activation)       (None, 48, 64, 64, 4 0           batch_normalization_6[0][0]      
__________________________________________________________________________________________________
conv3d_7 (Conv3D)               (None, 1, 64, 64, 48 49          activation_6[0][0]               
__________________________________________________________________________________________________
activation_7 (Activation)       (None, 1, 64, 64, 48 0           conv3d_7[0][0]                   
==================================================================================================
Total params: 468,817
Trainable params: 468,193
Non-trainable params: 624
__________________________________________________________________________________________________
```

</details>

I'm not sure what's going on in Keras's backend, especially considering the shift from `keras` to `tensorflow.keras` makes it tricky to find relevant documentation these days. Perhaps the setting was somehow saved when the model was serialized to `.h5`, for example.

**Comment by charleygros** [comment]
> Its own repository. I notice we have, for example, neuropoly/vertebral-labeling-deep-learning... would something like that be appropriate here?

Yes.. that would have been ideal.. but now it is "written in the Elsevier stone", not sure what's best.
I hope we won't have this issue in the future when using `ivadomed` and properly referring to software release in papers.

> I wanted to be more explicit about this, so I ran the test on both `master` and [4776f1a](https://github.com/neuropoly/spinalcordtoolbox/commit/4776f1a1b01de5c06fb254f3ab852d95aa19414c) (most recent commit in #2955). I set a breakpoint in `segment_3d` and ran `model.summary()`.The model loading appears to be identical with and without the calls to `set_image_data_format`.

If the performance on the test data are identifcal with and without the call to `set_image_data_format`: what about removing [this call](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/cnn_models_3d.py#L17)? or am I missing something about this issue?

**Comment by joshuacwnewton** [comment]
> If the performance on the test data are identifcal with and without the call to set_image_data_format: what about removing this call? or am I missing something about this issue?

That is exactly what @Drulex has done in #2955 (see 179ce7af631b89e5ddd508c138eb7a9558ff4272). I just wanted to verify that it was safe to do so before merging that PR. :smile:

**Comment by charleygros** [comment]
> I just wanted to double-check that it was safe to do so before merging that PR. smile

Sounds all safe :-) Thanks @joshuacwnewton
