### ISSUE TITLE
Broken link on documentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2964]
there: https://spinalcordtoolbox.com/en/latest/user_section/installation.html#install-with-docker

this link is broken: https://github.com/neuropoly/spinalcordtoolbox/wiki/testing#run-docker-image

**Comment by joshuacwnewton** [comment]
Like #2950, I think that if this is advice our users are relying on, it should go on RTD rather than the dev Wiki.

I can migrate the information as was done in #2952, and we can discuss any modifications to the install steps in that PR if that sounds alright.

**Comment by jcohenadad** [comment]
> I can migrate the information (similar to what is done in #2952), and we can discuss any modifications to the install steps in that PR if that sounds alright.

that sounds right, but we might want to just get rid of it, or simplify it to only support installation of "fresh" SCT, not via dockerhub, as explained in #2965

**Comment by joshuacwnewton** [comment]
> or simplify it to only support installation of "fresh" SCT, not via dockerhub, as explained in #2965

Ah! As far as I can see, DockerHub isn't mentioned in https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Docker-(Installing-SCT,-using-GUI), only the fresh install?

Or, are you referring to https://github.com/neuropoly/sct_docker?

**Comment by jcohenadad** [comment]
> Or, are you referring to https://github.com/neuropoly/sct_docker?

yup! some users apparently end up there, and install these stale versions of SCT. We should make a stop to that.
