### ISSUE TITLE
sct_label_vertebrae -discfile: top disc missing

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2967]
### Context

I have a file called `sub-XXX_labels-disc-manual` which includes disc labels, located posteriorly. I would like to project each disc label inside the spinal cord (orthogonally to the SC centerline). In order to do so, I run the function:
```
sct_label_vertebrae -i sub-XXX -s sub-XXX_seg -discfile sub-XXX_labels-disc-manual
```

### Problem

A disc label which was present in `sub-XXX_labels-disc-manual` is missing in the output file `sub-XXX_seg_labeled-disc`. The top label is missing. See below for a dilated example on sub-amu02 from [spine generic/multi-subject](https://github.com/spine-generic/data-multi-subject/releases/tag/r20201001) ).
![image](https://user-images.githubusercontent.com/22171999/97181176-60efbe80-1771-11eb-8d76-379eb207d128.png)

The file produced by the command includes sub-XXX_seg_labeled-disc, this file contains the label for each disc in the middle of the spinal cord.  However, it is missing the first disc from "sub-XXX_labels-disc-manual". The image below shows the `label_disc_manual` file((red/yellow) and the `seg_labeled-disc`  file ((blue/green) overlaid on the same image. Labels have been dilated for better visual. Subject is sub-amu02 from [spine generic/multi-subject](https://github.com/spine-generic/data-multi-subject/releases/tag/r20201001).
![image](https://user-images.githubusercontent.com/22171999/97182373-d7d98700-1772-11eb-8326-ba5b9ba0f3f7.png)

As seen on the image the first disc (in dark red in `labeled_disc_manual`) is not present in `seg_labeled-disc` (no blue point near this position).  

I think that this is due to the fact that the labeled segmentation is "cut" at the IS coordinates of the "top" disc. [`label_disc`
](https://github.com/neuropoly/spinalcordtoolbox/blob/d9a8a88fb2e0a6462a46db572ed1e222fe1a4681/spinalcordtoolbox/vertebrae/core.py#L518) is using the transition between level on the `sub-XXX_seg_labeled` file (shown below) to place the label for the disc.
![image](https://user-images.githubusercontent.com/22171999/97182803-5f26fa80-1773-11eb-81d3-831d3dd1ed26.png)

The transition at the top (3-->0) does not seem to be detected which is what causes the issue.   

### To reproduce

Data: 47a3bdcddeef8da0e5f19d15e9b1464bccf67b12
SCT version: 9a928bf254ade9a4933605e74a66225262b32169
Code:
~~~
# segment cord
sct_deepseg_sc -i ~/code/spine-generic/data-multi-subject/sub-amu/anat/sub-amu02_T2w.nii.gz -o sub-amu02_T2w_seg.nii.gz -c t2
# label vertebrae, with discfile as input
sct_label_vertebrae -i ~/code/spine-generic/data-multi-subject/sub-amu02/anat/sub-amu02_T2w.nii.gz -s sub-amu02_T2w_seg.nii.gz -discfile ~/code/spine-generic/data-multi-subject/derivatives/labels/sub-amu02/anat/sub-amu02_T2w_labels-disc-manual.nii.gz -c t2
~~~

**Expected result:**
the file `sub-amu02_T2w_seg_labeled_discs.nii.gz` shows all the labels present in `sub-amu02_T2w_labels-disc-manual.nii.gz`.

**Actual result:**
The file `sub-amu02_T2w_seg_labeled_discs.nii.gz` is missing the top label (value: 3)

**Comment by jcohenadad** [comment]
@lrouhier do you want to look into this?

**Comment by lrouhier** [comment]
Yes I will, let me assign it to me.

**Comment by lrouhier** [comment]
Investigation update: I think that I understand what is happening. 
 It has something to do with this [line](https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/spinalcordtoolbox/vertebrae/core.py#L540). Basically we go through each slice in the `sub-XXX_seg_labeled` image from bottom to top. 
On each slice, we check if it is empty or not. 
* If it is *not empty* we compare its value with the slice below and if the value is different we create a label at this level. 
* *if the slice is empty*, nothing happens. At the top, the segmentation is empty (see explanation below), so the algorithm does not detect the last transition ((a>0)-->0) because it does not compare the value of the empty slice with the previous one. 

The top of the "sub-xxx_seg_labeled" image is always empty. This is due to [this part of the code](https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/spinalcordtoolbox/vertebrae/core.py#L485-L492). It creates the labeled segmentation (`sub-XX_seg_labeled`) based on the value of the disc "above" (in the IS direction). Once there are no more disc above, it adds empty slices so that the `sub-XXX_seg_labeled` dimension matches the `sub-XXX_seg` dimension.  

This is my understanding of the problem. I am not too sure how to fix that.

**Comment by jcohenadad** [comment]
I'll take care of it

**Comment by jcohenadad** [comment]
After discussing with @lrouhier , we decided to opt for the systematic additional of the top label. 

Cons:
- if vertebral level is partially covered, the disc value will be wrong (ie: at the middle of the vertebrae). However, this cons is mitigated by:
  - very few people are using this disc-label output
  - in the near future, the disc-label will be more "trusted", after #2679

@lrouhier will implement that slight modification in the behaviour of disc file computation.
