### ISSUE TITLE
smooth centerline not perfect at edge

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#297]
Data: 
~~~~
git clone https://github.com/neuropoly/sct_example_data.git
~~~~

Syntax:
~~~~
sct_straighten_spinalcord -i t2.nii.gz -c t2_seg.nii.gz -v 3
~~~~

Output:
![screen shot 2015-04-01 at 20 27 46](https://cloud.githubusercontent.com/assets/2482071/6956781/39694286-d8c1-11e4-91d8-cf97860783ed.png)

**Comment by benjamindeleener** [comment]
Using NURBS for fitting:
![screen shot 2015-04-08 at 16 46 21](https://cloud.githubusercontent.com/assets/7757117/7055122/1cdeecc6-de0f-11e4-99b1-4d50a9c32452.png)
