### ISSUE TITLE
Enable autobuilding RTD on PRs + fail on warning

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2973]
Something I find myself doing often is manually going into RTD to activate a build for a branch I'm on (so I can link it in the PR and demonstrate to reviewers what my doc changes look like). A really simple example is #2974 just now. 

Cumulatively, this is time consuming, but it can be done automatically in RTD. See: [Autobuild docs for pull requests](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html). Some other benefits:

* If we combine this with enabling RTD to fail on Sphinx warnings, this could also help to prevent the numerous Sphinx issues that have slipped by over the past months, because RTD/Sphinx would effectively become part of our CI test suite.
    * This would be done in `.readthedocs.yml` with [`sphinx.fail-on-warning`](https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning) set.
* Seeing documentation in the pull request CI GUI could also help remind us to update documentation with code changes, which might help prevent the docs from falling out of date. (Especially in context of #2857.)

**Comment by joshuacwnewton** [comment]
I've turned this on, and it now appears on pull requests. 

It was very simple change (Go to `Admin` > `Advanced settings`, Enable the `Build pull requests for this project` option) so if this is not wanted, it can be easily reverted.

**Comment by jcohenadad** [comment]
wow! cool! very convenient to have the doc automatically built and accessible via the "details" hyperlink:
![image](https://user-images.githubusercontent.com/2482071/97515756-1b491680-1968-11eb-979d-32e0e09e2aa2.png)

awesome discovery @joshuacwnewton 💯
