### ISSUE TITLE
Possibly erroneous call to sct_math in sct_label_vertebrae

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2976]
`sct_label_vertebrae` makes the following subprocess call:

https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/scripts/sct_label_vertebrae.py#L409

But the argument to `denoise` is `h=0.05` which doesn't really makes sense given the description of the argument:

https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/scripts/sct_maths.py#L195-L202

I am wondering if the code is silently failing given that `denoise` has default values for `p` and `b`, thus the `h=0.05` is completely ignored:

https://github.com/neuropoly/spinalcordtoolbox/blob/5743157e5c011529ca8e566e5f4e3dc554901958/scripts/sct_maths.py#L366-L375

In the scope of #2975

**Comment by jcohenadad** [comment]
wow! thank you for catching that @Drulex. My suggestion would be to simply get rid of the denoising chunk of the code in `sct_label_vertebrae`, given that we don't use it at all
