### ISSUE TITLE
CI cron job build is too long

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2979]
https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/739373848

https://github.com/neuropoly/spinalcordtoolbox/issues/2923#issuecomment-718318654

I'm not arguing the necessity to build on 14 different platforms, but this runs for 4-5 hours daily and sucks up all the build resources. We should at least consider moving it in the middle of the night.

**Comment by Drulex** [comment]
Other ideas welcome.

**Comment by joshuacwnewton** [comment]
From Travis's [Cron jobs](https://docs.travis-ci.com/user/cron-jobs/) page:

> Cron jobs can run `daily`, `weekly` or `monthly`, which in practice means up to an hour after the selected time span, and you cannot set them to run at a specific time.

Not being able to set a specific time is a bit awkward, but from what I can tell, the time when you first create the job is the time it will always run at each day. So, someone would have to stay up and create a new cron job for that time. :P

There's also this option to consider, too:

![Screenshot from 2020-10-29 08-50-38](https://user-images.githubusercontent.com/16181459/97576331-6b55c680-19c4-11eb-9a5a-6b80851553ec.png)

**Comment by Drulex** [comment]
> Cron jobs can run `daily`, `weekly` or `monthly`, which in practice means up to an hour after the selected time span, and you cannot set them to run at a specific time.

:scream:

**Comment by joshuacwnewton** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/8705. I can volunteer to stay up and set the cron job. :p

How does 3AM Eastern sound?

**Comment by Drulex** [comment]
> See also: [travis-ci/travis-ci#8705](https://github.com/travis-ci/travis-ci/issues/8705). I can volunteer to stay up and set the cron job. :p
> 
> How does 3AM Eastern sound?

This is a great sacrifice sir :1st_place_medal: 

Let's hope it works!
(better make sure in advance that you have the correct permissions)

**Comment by joshuacwnewton** [comment]
![cron-night](https://user-images.githubusercontent.com/16181459/97671011-aa2b6100-1a44-11eb-8130-1d795bd288cb.PNG)

😴 🛌

**Comment by Drulex** [comment]
Great thanks a lot @joshuacwnewton! Can't believe we actually needed to do that.

**Comment by Drulex** [comment]
I was going to close this, but with the recent migration to Travis-ci.com (https://github.com/neuropoly/spinalcordtoolbox/issues/3057) I was wondering if the cron job is still configured correctly.

According to Travis the next scheduled job is... 3 days ago? :confused: 

![image](https://user-images.githubusercontent.com/7751484/100767896-46d87a00-33c8-11eb-856c-1401717ff562.png)

**Comment by joshuacwnewton** [comment]
Good catch, @Drulex. I hope this doesn't mean another late night! :laughing: 

Although if we end up migrating to GitHub Actions, then perhaps this won't be necessary.

**Comment by Drulex** [comment]
Looks like cron isn't running on Travis... I can try to schedule it this evening.

**Comment by joshuacwnewton** [comment]
Thanks so much, @Drulex!

![Screenshot from 2020-12-05 10-28-58](https://user-images.githubusercontent.com/16181459/101247002-b6aa7580-36e4-11eb-9730-003b38c65bdf.png)

Closing, now that this has been handled. :smile:
