### ISSUE TITLE
Clean-up outdated WIP pull requests

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2984]
While not a _huge_ deal, this is one of those little housekeeping things that I think would be nice to look into. (Similar to #2942)

There are a handful of old PRs that have diverged quite a bit from master. (See the ones marked `priority: LOW`) Each PR has the following message: 

> This PR is based on an old branch which was started by [author]. As I am cleaning up the stale branches, I'm opening this PR because the branch contains useful work that should not be discarded forever. One day someone will take over this PR hopefully...

Untangling the work done in these PRs looks to be... challenging, to say the least. My sense is that it would take more effort to revive them than it would to simply start over. Also, in many cases, the functionality was implemented elsewhere. (e.g. binarize from `imgproc` in #2556 found its way into `math`, I think.) So, I think it's justifiable to close some/all of them.

**Comment by joshuacwnewton** [comment]
I think that all of these pull-requests should be closed. _(Reason: I think that the PRs have become so out of date with `master` that the conflicts are too severe to resolve. And, I think it would make more sense to start fresh than to try and salvage the commits through rebasing/merging.)_

But, also I think I want to still try and document the work from these PRs, by doing the following:

1. Open issues to document whatever problem the PRs were trying to fix. (In some cases, no issue was ever opened.)
2. Modify the PRs to make the changes more readable.
    * All of the PRs currently show "wants to merge 5000-6000 commits" which makes it impossible to see what the work done is.
    * My plan is to make base branches that contain the old commit history, so that only the new commits show. These would be temporary, and used just to show the changes in GitHub's UI. They would be deleted immediately after the PRs are closed.
    * I have tried this out on #1913:

Before: 

![Screenshot from 2020-12-03 17-52-03](https://user-images.githubusercontent.com/16181459/101099033-f44ab980-3591-11eb-94fe-00b0d69b4134.png)

After: (Now the changes are actually readable)

![Screenshot from 2020-12-03 17-59-57](https://user-images.githubusercontent.com/16181459/101099034-f6ad1380-3591-11eb-9f7e-99d5b534a946.png)

**Comment by joshuacwnewton** [comment]
If this plan sounds OK, @jcohenadad, then I can go ahead and clean up these PRs. :)

**Comment by jcohenadad** [comment]
Thank you so much for looking into it @joshuacwnewton

**Comment by joshuacwnewton** [comment]
I'm closing this issue, as all of the WIP pull requests have been cleaned up.

I have opened new issues for the first 4 PRs, as they were unfinished enhancements that were missing open issues.

* #1913 ==> #3077 
* #2328 ==> #3078 
* #2552 ==> #3079 
* #2553 ==> #3080 

I have closed the remaining 4 PRs outright. I did this because the work from each had ended up implemented in other PRs. (Check #2554, #2555, #2556, and #2557 for the justification for closing each PR.)
