### ISSUE TITLE
sct_label_utils: compute_mean_square_error should gives missing label.

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2986]
## Context

I am using `sct_label_utils -i <image> -MSE <REF>` .
My image was missing a label compared to the ref. Therefore the function was exiting early (see [here] )(https://github.com/neuropoly/spinalcordtoolbox/blob/9a928bf254ade9a4933605e74a66225262b32169/spinalcordtoolbox/labels.py#L283)

## Issue

While digging to try and see what was happening I stumbled upon these [these lines](https://github.com/neuropoly/spinalcordtoolbox/blob/9a928bf254ade9a4933605e74a66225262b32169/spinalcordtoolbox/labels.py#L291-L297) which seems strange. 

for example [here](https://github.com/neuropoly/spinalcordtoolbox/blob/9a928bf254ade9a4933605e74a66225262b32169/spinalcordtoolbox/labels.py#L293) we check if `np.round(coord.value)`  is this [list](https://github.com/neuropoly/spinalcordtoolbox/blob/9a928bf254ade9a4933605e74a66225262b32169/spinalcordtoolbox/labels.py#L287) which is defined from `coordinates_input`. However, `coord` is also an element from coordinates input. see [here](https://github.com/neuropoly/spinalcordtoolbox/blob/9a928bf254ade9a4933605e74a66225262b32169/spinalcordtoolbox/labels.py#L291)
It seems to perform the wrong comparison to find if there is a label mismatch.

It could also be of interest to output the MSE even if there is a missing (while warning the user about the missing label).

**Comment by Drulex** [comment]
I may have introduced a regression in #2887. Will investigate.

**Comment by lrouhier** [comment]
Don't worry I will take care of that!
