### ISSUE TITLE
Should importing spinalcordtoolbox implicitily expose sub-packages and/or modules.

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2989]
I previously proposed the following:

1. Importing a sub-package should implicitly expose all modules in that sub-package. This is done by importing the relevant modules in the sub-pacakge's `__init__.py` file:
   - Motivation: https://github.com/neuropoly/spinalcordtoolbox/issues/2951#issuecomment-710053812
   - Implementation: https://github.com/neuropoly/spinalcordtoolbox/pull/2955/commits/f65df321b078b939e5de66755ca0561fe773ed82 (already merged)

This allows to do:
```python
import spinalcordtoolbox.deepseg as deepseg

# implicit access to the modules inside deepseg sub-package
deepseg.models.do_something()
deepseg.core.do_something()
```
Instead of:
```python
import spinalcordtoolbox.deepseg as deepseg
import spinalcordtoolbox.deepseg.models
import spinalcordtoolbox.deepseg.core

deepseg.models.do_something()
deepseg.core.do_something()
```

2. Same concept as 1, but applied to the package: importing the `spinalcordtoolbox` package should implicitly expose all modules (not sub-packages):
   - Motivation: same as 1: convenience.
   - Implementation: https://github.com/neuropoly/spinalcordtoolbox/pull/2966/commits/d93d7ac432b9866dccd87390d249476195945ae2 (pending)

This allows to do:
```python
import spinalcordtoolbox as sct
sct.labels.do_something()
sct.resampling.do_something()
```

Instead of:
```python
import spinalcordtoolbox.labels as labels
import spinalcordtoolbox.resampling as resampler
labels.do_something()
resampler.do_something()
```

But does not allow:
```python
import spinalcordtoolbox as sct
sct.deepseg.do_something() # `deepseg` is a sub-package, it requires explicit import 
```

I may have been quick with the decision so this issue is created so that we can discuss the pros and cons of this approach.
- @joshuacwnewton is proposing that sub-packages should also be exposed implicitly (https://github.com/neuropoly/spinalcordtoolbox/pull/2966#discussion_r515355970) which I had not done initially simply due to the fact that sub-packages may be significantly heavier than a module.
- @zougloub probably has an opinion on this, can you share?

**Comment by Drulex** [comment]
My main motivation was convenience and simplifying the code, but I had not considered the performance trade-offs. I will do a quick benchmark to compare.

**Comment by Drulex** [comment]
```
# time to import spinalcordtoolbox
(venv_sct) ➜  spinalcordtoolbox git:(master) git checkout master
(venv_sct) ➜  spinalcordtoolbox git:(master) time python -c 'import spinalcordtoolbox as sct'
python -c 'import spinalcordtoolbox as sct'  0.06s user 0.02s system 100% cpu 0.078 total
(venv_sct) ➜  spinalcordtoolbox git:(master) git checkout aj/2963-fix-api-importing-scripts
Switched to branch 'aj/2963-fix-api-importing-scripts'
(venv_sct) ➜  spinalcordtoolbox git:(aj/2963-fix-api-importing-scripts) time python -c 'import spinalcordtoolbox as sct'
python -c 'import spinalcordtoolbox as sct'  2.05s user 1.62s system 319% cpu 1.150 total

# time to launch sct_image -h
(venv_sct) ➜  spinalcordtoolbox git:(master) git checkout master
(venv_sct) ➜  spinalcordtoolbox git:(master) time sct_image -h 
[...]
sct_image -h  1.40s user 1.64s system 623% cpu 0.488 total
(venv_sct) ➜  spinalcordtoolbox git:(master) git checkout aj/2963-fix-api-importing-scripts
Switched to branch 'aj/2963-fix-api-importing-scripts'
(venv_sct) ➜  spinalcordtoolbox git:(aj/2963-fix-api-importing-scripts) time sct_image -h 
[...]
sct_image -h  4.08s user 3.46s system 338% cpu 2.226 total
```

^ There is definitely a performance hit on load time :grimacing:

**Comment by jcohenadad** [comment]
@Drulex to be sure I understand this performance comparison, is `master` doing "1" in https://github.com/neuropoly/spinalcordtoolbox/issues/2989#issue-734522312, while `aj/2963-fix-api-importing-scripts` is doing "2", but not the following (ie: exposing sub-packages implicitly):
~~~
import spinalcordtoolbox as sct
sct.deepseg.do_something()
~~~

And this performance test is a suggestion that if we go with exposing sub-packages implicitly, the performance will be even worse than what you've tested in https://github.com/neuropoly/spinalcordtoolbox/issues/2989#issuecomment-720517870 (suggesting we should not do that).

To me, going from 2.05s to 3.46s (in this example) is already a serious hit. Are we all OK with that? Are the benefits worth the cost?

Another consideration: as SCT becomes "cleaner" in terms of getting rid of circular imports, etc., is it reasonable to anticipate that the "3.46s" will likely drop significantly in the near future, so even though there is a hit in loading time right now, we should still do the change in d93d7ac because (i) cleaner code and (ii) performance will increase in the near future with the ongoing refactoring.

**Comment by joshuacwnewton** [comment]
> * @joshuacwnewton is proposing that sub-packages should also be exposed implicitly ([#2966 (comment)](https://github.com/neuropoly/spinalcordtoolbox/pull/2966#discussion_r515355970)) which I had not done initially simply due to the fact that sub-packages may be significantly heavier than a module.

My main reason for proposing this is that, from a user perspective, it's not entirely clear which parts of SCT belong to subpackages, and which parts belong to modules. If you look on the [Python API](https://spinalcordtoolbox.com/en/latest/dev_section/api.html) page of our documentation, the table of contents lists both subpackages and modules together without differentiating between them. _Everything_ (modules and subpackages) is combined under one big umbrella of  "SCT's Python API" so to speak.

So, if I were using the `spinalcordtoolbox` package in a new project, I would expect to be able to import all of these things in a consistent way, and would be caught off guard when `import spinalcordtoolbox as sct` leaves out some "hidden" subpackages. 

This is (I think) different than other projects such as `numpy`, where there is clearer separation between the core package and subpackages like `f2py`, [see this StackOverflow answer](https://stackoverflow.com/a/22622968).

**Comment by joshuacwnewton** [comment]
If it's not too much trouble, @Drulex, could you expand your performance comparison to include all 3? So:

1. Not exposing modules/subpackages (`master`)
2. Exposing just modules (`aj/2963-fix-api-importing-scripts`)
3. Exposing modules and subpackages (`proposed`)

I'm curious how much of an extra hit it is to go from 2. to 3.

**Comment by Drulex** [comment]
> @Drulex to be sure I understand this performance comparison, is `master` doing "1" in [#2989 (comment)](https://github.com/neuropoly/spinalcordtoolbox/issues/2989#issue-734522312), while `aj/2963-fix-api-importing-scripts` is doing "2", but not the following (ie: exposing sub-packages implicitly):

Correct

> And this performance test is a suggestion that if we go with exposing sub-packages implicitly, the performance will be even worse than what you've tested in #2989 (comment) (suggesting we should not do that).

Yes it can only increase load time.

> To me, going from 2.05s to 3.46s (in this example) is already a serious hit. Are we all OK with that? Are the benefits worth the cost?

I agree this is a serious hit. The benefits are purely for the developer experience and probably not worth it now that I benchmarked it. Sorry for not evaluating earlier..

> Another consideration: as SCT becomes "cleaner" in terms of getting rid of circular imports, etc., is it reasonable to anticipate that the "3.46s" will likely drop significantly in the near future, so even though there is a hit in loading time right now, we should still do the change in d93d7ac because (i) cleaner code and (ii) performance will increase in the near future with the ongoing refactoring.

This specific change (implicit imports) only adds value to developers while increasing load time for end-users. Other refactoring efforts will generally result in a cleaner architecture with proper separation of concerns which would ensure that code only imports what it needs, thus reducing load time (this benefits both developers and end-users). Now that I see the performance hit I don't think this proposed change is worth it, especially considering that the user base are people using the scripts and not the API (that is the case today at least).

**Comment by Drulex** [comment]
> I'm curious how much of an extra hit it is to go from 2. to 3.

With `import spinalcordtoolbox` importing everything including sub-packages:
```
python -c 'import spinalcordtoolbox as sct'  3.09s user 1.75s system 219% cpu 2.201 total
```

**Comment by jcohenadad** [comment]
on the topic of loading time, I also noticed a large difference when running a Terminal command the first time, vs. subsequent times, e.g.:
First time:
~~~
real	0m1.310s
user	0m1.727s
sys	0m0.531s

~~~
2nd time (3rd, 4th, etc. are on the same range):
~~~
real	0m0.487s
user	0m1.260s
sys	0m0.302s
~~~

This is likely due to the OS keeping the imports somewhere in the RAM (even when closing the Terminal and re-opening a new one), at least this is the behaviour on macOs Catalina. It makes me wonder if, with the proposed refactoring (import everything), the first CLI call would be *very* long, but the subsequent ones would be rather short (possibly as short as now?). If that's the case, then this is not as bad considering that users typically run more than one SCT command during an analysis session.

**Comment by Drulex** [comment]
I don't think this is behavior that we can rely on. Running different scripts launches different processes so nothing guarantees that any "shareable" memory would be kept between processes.

**Comment by joshuacwnewton** [comment]
I agree with reverting the change and simply sticking to 1.

> This allows to do:
> 
> ```python
> import spinalcordtoolbox.deepseg as deepseg
> 
> # implicit access to the modules inside deepseg sub-package
> deepseg.models.do_something()
> deepseg.core.do_something()
> ```

As an added benedit, the import syntax from 1. is the same regardless of whether it's a subpackage or module, so it satisfies all of the concerns I brought up in https://github.com/neuropoly/spinalcordtoolbox/issues/2989#issuecomment-720531804.

**Comment by Drulex** [comment]
Actually...
```
(venv_sct) ➜  spinalcordtoolbox git:(master) git reset origin/master --hard
HEAD is now at 340278fc Pin h5py~=2.10.0 as a workaround for upstream Keras/TensorFlow issues (#2988)
(venv_sct) ➜  spinalcordtoolbox git:(master) time python -c 'import spinalcordtoolbox.deepseg as deepseg'
python -c 'import spinalcordtoolbox.deepseg as deepseg'  2.38s user 1.71s system 271% cpu 1.508 total

# one commit before point 1 was merged
(venv_sct) ➜  spinalcordtoolbox git:(master) git checkout c8eaa4a2         
HEAD is now at c8eaa4a2 Update references (#2968) 
(venv_sct) ➜  spinalcordtoolbox git:(c8eaa4a2) time python -c 'import spinalcordtoolbox.deepseg as deepseg'
python -c 'import spinalcordtoolbox.deepseg as deepseg'  0.06s user 0.03s system 100% cpu 0.087 total
```

I hadn't tried it before, but it looks like https://github.com/neuropoly/spinalcordtoolbox/commit/f65df321b078b939e5de66755ca0561fe773ed82 did introduce a performance hit as well.

**Comment by Drulex** [comment]
Reverted all implicit imports for performance reasons. Closing this.
