### ISSUE TITLE
prop_seg: compatibility issue

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#299]
`sct_propseg.py -i spgr20crop.nii.gz -t t1 -init-centerline spgr20crop_cord_centerline.nii.gz -v 1`

output
--------
Check file existence...
  OK: spgr20crop.nii.gz
Check file existence...
  OK: spgr20crop_cord_centerline.nii.gz
isct_propseg -i spgr20crop.nii.gz -t t1 -o ./ -verbose -init-centerline spgr20crop_cord_centerline.nii.gz

Done!
Type the following command in the terminal to see the results:
fslview spgr20crop.nii.gz ./spgr20crop_seg.nii.gz -l Red -b 0,1 -t 0.7 &

`isct_propseg -i spgr20crop.nii.gz -t t1 -init-centerline spgr20crop_cord_centerline.nii.gz -verbose`

output
---------
Initialization - using given centerline
dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
  Referenced from: /Users/slevy_local/spinalcordtoolbox/bin/osx/isct_propseg
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___sincos_stret
  Referenced from: /Users/slevy_local/spinalcordtoolbox/bin/osx/isct_propseg
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

(data: slevy/data/criugm/errsm_35/mtv_tr40)

`uname -a`
Darwin pass.neuro.polymtl.ca 12.2.1 Darwin Kernel Version 12.2.1: Thu Oct 18 12:13:47 PDT 2012; root:xnu-2050.20.9~1/RELEASE_X86_64 x86_64

**Comment by slevyrosetti** [comment]
OSX 10.8.2

**Comment by benjamindeleener** [comment]
TO DO: compile on Evans
