### ISSUE TITLE
Some models in sct_deepseg cannot be run in standalone

### ISSUE THREAD

**Issue by andreanne-lemay** [neuropoly/spinalcordtoolbox#2994]
There are currently tasks and models available on sct_deepseg. One task can require multiple models (e.g., `seg_tumor_t2` task will use two models: `findcord_tumor` and `t2_tumor`). Some models are not standalone and raise an error when used alone (e.g. `t2_tumor`: see image).

![image](https://user-images.githubusercontent.com/49137243/98041078-5bd4e400-1def-11eb-8c7a-dd854be09dde.png)

Possible solutions:
- To avoid confusion, models that can't be used alone could be excluded from the list of models and it would be impossible to call them. 
- Another option would be to call the task `seg_tumor_t2` when the model `t2_tumor` is called. In this case, we might want to get rid of tasks and only keep models (since models and tasks can get confusing for the user).

**Comment by jcohenadad** [comment]
another solution:
- do not expose the "-models"
