### ISSUE TITLE
Introduce flag to list labels

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3003]
With the proposed changed in https://github.com/neuropoly/spinalcordtoolbox/pull/3000, labels ID will not be listed automatically when running the usage of `sct_extract_metric`. 

A solution would be to introduce a flag, e.g. `list-labels`, which would list labels in the file "info_label.txt", which located in the folder specified by `-f`.

**Comment by joshuacwnewton** [comment]
I tried out the proposed solution, but it feels a little strange to me. Currently, `sct_extract_metric` has `-i` as a mandatory input. So, we would have to call:

```
sct_extract_metric -i input-file.nii.gz -list-labels
```

I wonder, is it unreasonable to simply ask the user to inspect the `info_label.txt` file themselves?

**Comment by jcohenadad** [comment]
> I tried out the proposed solution, but it feels a little strange to me. Currently, sct_extract_metric has -i as a mandatory input.

oopsi... indeed, that's not cool. How about making -i non-mandatory?

> I wonder, is it unreasonable to simply ask the user to inspect the info_label.txt file themselves?

some of our users don't know how to use the terminal, don't know where SCT is installed, wouldn't easily find this file, etc. Also, knowing the label IDs is mandatory in order to properly use this function, so it is cumbersome to have to open the file manually in order to know those IDs.
