### ISSUE TITLE
Add macOs 10.15 in Travis

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3016]
Now that 10.15 (catalina) is [available on Travis](https://docs.travis-ci.com/user/reference/osx/#macos-version), we should add it to our CI

**Comment by joshuacwnewton** [comment]
Closing as this is a duplicate of #2692 and possibly also #1677 (see https://github.com/neuropoly/spinalcordtoolbox/issues/1677#issuecomment-708049397).

(Also, I'm going to self-assign #2692 and work on this right now. :tada:)
