### ISSUE TITLE
Automatic detection failed in sct_label_vertebrae

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/spinalcordtoolbox#3025]
### Description

Automatic detection of vertabrae failed using the file sub-1000032.T1w_seg.nii.gz with sct_label_vertebrae. The data is from Ukbiobank. Right now, the gradient distortion correction isn't applied on these images, but the segmentation of the spinal cord worked for the T1w image.
Here is the segmentation of the T1w image:

![sub-1000032_T1w_RPI_r_seg](https://user-images.githubusercontent.com/71230552/98590081-443ca600-229c-11eb-9c6e-ad82bcf1cff4.PNG)
![sub-1000032_T1w_RPI_r_seg_qc](https://user-images.githubusercontent.com/71230552/98590159-67ffec00-229c-11eb-995e-e7dfb74df7b9.PNG)

### Steps to Reproduce
DATA: 
[sub-1000032_T1w.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/5513149/sub-1000032_T1w.nii.gz)
[sub-1000032_T1w_seg.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/5513127/sub-1000032_T1w_seg.nii.gz)

0. Install SCT v5.0.0

1. Run
~~~
sct_label_vertebrae -i sub-1000032_T1w.nii.gz -s sub-1000032_T1w_seg.nii.gz -c t1
~~~

**Expected behavior:** 

That the automatic vertebrae labeling would work and create  sub-100032_labeled.nii.gz

**Actual behavior:** 

![erreur_labeling_sub-1000032_T1w_seg](https://user-images.githubusercontent.com/71230552/98589855-ef009480-229b-11eb-9c33-8b9c8000b3fe.PNG)

**Comment by jcohenadad** [comment]
@sandrinebedard it failed because there is nothing to detect 😉 .

The algorithm is supposed to find C2-C3 disc, which is not visible in your image. 

as discussed you need to use the distorted (raw, uncropped) image
