### ISSUE TITLE
SCT will not install correctly on macOS due to libomp dependency of onnxruntime v1.5.1

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3033]
### Context

https://forum.spinalcordmri.org/t/installation-validation-failed-installation-failed/570

### Description

SCT depends on `ivadomed`, which depends on `onnxruntime`, which (as of version `1.5.1`) depends on `libomp`. We encountered this in #2930 and fixed it in our CI by installing `libomp` as part of the config.

https://github.com/neuropoly/spinalcordtoolbox/blob/5eae6da1e97a42cfaf8780a18fa61ecf3c95d6f1/.travis.yml#L106-L109

The problem with this solution is that it requires users to install `libomp` on their end, too.

However, separately, the `ivadomed` team fixed this in `v2.5.0` using a different solution: pinning `onnxruntime==1.4.0`. But, SCT currently uses 2.4.0:

https://github.com/neuropoly/spinalcordtoolbox/blob/5eae6da1e97a42cfaf8780a18fa61ecf3c95d6f1/requirements.txt#L7

If we upgrade `ivadomed` (or even just pin `onnxruntime==1.4.0` ourselves), then the `libomp` fixes won't be required, and users can install SCT without hassle.

**Comment by dyt811** [comment]
@joshuacwnewton both @konaian and I tried installing newer version of onnxruntime 1.7.0 on BigSur and 10.14 and did not run into this `libomp` issue. Is this macOS 10.15 specific Could you confirm this is still the case? Otherwise, I think IvadoMed are ready to move to 1.7.0.

**Comment by joshuacwnewton** [comment]
Oh, what an excellent observation, @dyt811!

On my MacOS 10.15 VM, I can confirm that I receive the error with `onnxruntime=1.5.1`, but it indeed goes away with `onnxruntime==1.7.0`.

Looking into recent updates, https://github.com/microsoft/onnxruntime/pull/6718#issue-574596731 shows that they removed openmp as a requirement. So, I believe we can go ahead an unpin for both ivadomed and SCT. :smile:
