### ISSUE TITLE
argument -append: invalid choice: '1' (choose from 0, 1) in sct_process_segmentation

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/spinalcordtoolbox#3038]
### Description

While using sct_process_segmentation, the parameter -append does not recognize 0 or 1, I think it is because 0 and 1 are recognized as string in the input and not as integrers. This was not an issue in anterior versions of SCT.
![image](https://user-images.githubusercontent.com/71230552/98969982-6bce8100-24dd-11eb-8765-ad46da25f4d0.png)

### Steps to Reproduce

0. SCT v5.0.0

1. Run sct_process_segmentation on an image with the parameter 
~~~
-append 1
~~~

**Expected behavior:**

Writing '1' or '0' in the shell as an argument of -append should be a valid choice.

**Actual behavior:** 
(see screnshot above)

**Comment by jcohenadad** [comment]
thank you for reporting this bug, @sandrinebedard. It might be caused by a regression when @joshuacwnewton refactored the parser?

**Comment by joshuacwnewton** [comment]
You're absolutely right, @jcohenadad. The fix is simple, I'll open a PR right now and we can include it in `5.0.1`.

**Comment by joshuacwnewton** [comment]
Hi @sandrinebedard. [v5.0.1](https://github.com/neuropoly/spinalcordtoolbox/releases/tag/5.0.1) has been released with a fix for this issue included. 

Thank you again for reporting this issue, and for helping to improve the quality of SCT. :slightly_smiling_face:
