### ISSUE TITLE
Unreproducible results of batch_processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3044]
using 4b767adcbc81bc47130e60e3b431be9e9c9bf006, the MTR and FA results vary across trials, e.g. on macOs catalina:

trial 1 (obtained by @jcohenadad)
~~~
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.38138174885682
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088246
dmri/FA(CST_r):  0.7756265293435963
dmri/FA(CST_l):  0.7800112348643411
~~~

trial 2 (obtained by @joshuacwnewton )
~~~
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.414474990448184
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088243
dmri/FA(CST_r):  0.7745714667941417
dmri/FA(CST_l):  0.7812543001110186
~~~

there is likely something fishy with `sct_extract_metric`. Further investigations needed.

**Comment by joshuacwnewton** [comment]
Note: The runs shown above are done on our personal machines if I'm not mistaken. (As well, I'm running Catalina using [`macOS-Simple-KVM`](https://github.com/foxlet/macOS-Simple-KVM), not Apple hardware.)

To me, this seems like another reason for running `batch_processing.sh` through our CI. (See also: #2888.) Having stable, consistent builds would go a long way towards identifying the cause of differences like this. (Code changes vs. hardware, etc.)

**Comment by joshuacwnewton** [comment]
I have another concerning observation: `mt/MTR(WM)` seems to vary slightly even between runs on a single system.

<details>
<summary> pop-os Run 1 </summary>

```
~~~
Version:         git-jn/v5.0.1-4b767adcbc81bc47130e60e3b431be9e9c9bf006
Ran on:          Linux pop-os 5.8.0-7625-generic
Duration:        0hrs 17min 43sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.38365862512906
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088246
dmri/FA(CST_r):  0.775626536503328
dmri/FA(CST_l):  0.7800112277757334
~~~
```

</details>

<details>
<summary> pop-os Run 2 </summary>

```
~~~
Version:         git-release-625e218bec6a5fc1e47b121759ad3eeef8a7dd48
Ran on:          Linux pop-os 5.8.0-7625-generic
Duration:        0hrs 14min 30sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.38065117804087
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088246
dmri/FA(CST_r):  0.775626536503328
dmri/FA(CST_l):  0.7800112277757334
~~~
```
</details>

<details>
<summary> pop-os Run 3</summary>

```
~~~
Version:         git-master-c880c9d10703656297e534b6d25ef53f6923702f
Ran on:          Linux pop-os 5.8.0-7625-generic
Duration:        0hrs 13min 29sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.380927343852676
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088246
dmri/FA(CST_r):  0.775626536503328
dmri/FA(CST_l):  0.7800112277757334
~~~
```
</details>

(`54.38365862512906` vs. `54.38065117804087` vs. `54.380927343852676`)

<details>
<summary> macOS Catalina Run 1 </summary>

```
~~~
Version:         git-master-4b767adcbc81bc47130e60e3b431be9e9c9bf006
Ran on:          Darwin Joshuas-iMac.local 19.6.0
Duration:        0hrs 40min 31sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.414474990448184
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088243
dmri/FA(CST_r):  0.7745714667941417
dmri/FA(CST_l):  0.7812543001110186
~~~
```
</details>

<details>
<summary> macOS Catalina Run 2 </summary>

```
~~~
Version:         git-master-4b767adcbc81bc47130e60e3b431be9e9c9bf006
Ran on:          Darwin Joshuas-iMac.local 19.6.0
Duration:        0hrs 38min 24sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.41884120886879
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088243
dmri/FA(CST_r):  0.7745714667941417
dmri/FA(CST_l):  0.7812543001110186
~~~
```
</details>

(`54.414474990448184` vs. `54.41884120886879`)

**Comment by jcohenadad** [comment]
When re-running `sct_extract_metric` several times, results are stable:

[mtr_in_wm.xlsx](https://github.com/neuropoly/spinalcordtoolbox/files/5547246/mtr_in_wm.xlsx)

So I don't think the problem of unreproducibility comes from `sct_extract_metric`. I suspect the problem comes from a slightly different registration result, so the issue would be on the ANTs parameters. We already had a similar issue in the past, which was related to the parametrization of the sampling density for this binary [`antsSliceRegularizedRegistration`](https://github.com/ANTsX/ANTs/issues/976). Given that registration in the `batch_processing.sh` script uses algo=slicereg, it is possible that this randomization problem still exists (or was re-introduced?):

https://github.com/neuropoly/spinalcordtoolbox/blob/fc1879ea9aa2862c7c888d2454ae62bccde861d2/batch_processing.sh#L159

**Comment by jcohenadad** [comment]
Subsequent tests: running the `sct_register_multimodal` command twice as mentioned in the comment above https://github.com/neuropoly/spinalcordtoolbox/issues/3044#issuecomment-728134829, does indeed produce different warping fields:

![Screen Shot 2020-11-16 at 2 44 14 PM](https://user-images.githubusercontent.com/2482071/99300281-61ccbb00-281a-11eb-8606-4a20d42169a1.png)

**Comment by jcohenadad** [comment]
OK, the fact that results vary from trial to trial is perfectly normal, considering that by default, our registration method is set to work with sampling density "Regular":
https://github.com/neuropoly/spinalcordtoolbox/blob/fc1879ea9aa2862c7c888d2454ae62bccde861d2/spinalcordtoolbox/registration/register.py#L164

Results were reproducible in the past, e.g. between [4.2.2](https://github.com/neuropoly/spinalcordtoolbox/releases/tag/4.2.2) and [4.2.1](https://github.com/neuropoly/spinalcordtoolbox/releases/tag/4.2.1), before ANTs changed the behaviour of this sampling density feature. Now the question is: do we want to keep this randomization?

In terms of performance, the randomization is good for the quality of the registration, and the sparse sampling is also much faster. More discussion [here](https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues).

**Comment by jcohenadad** [comment]
Bingo! When changing "Regular, 0.2" to "None", effectively removing the sparse sampling and any randomization, the warping fields become identical across runs:

![Screen Shot 2020-11-16 at 3 14 00 PM](https://user-images.githubusercontent.com/2482071/99303250-99d5fd00-281e-11eb-8747-2180c2ab9dde.png)

Also interestingly, computation time did not increase (at least for this _very small_ dataset).

**Comment by jcohenadad** [comment]
So, given how important reproducibility is in neuroimaging, maybe we should consider adding a parameter to `sct_register_multimodal` for setting the sampling density strategy, and set the default value to "None" (ie: reproducible).
