### ISSUE TITLE
Python API documentation page needs to be updated following recent refactors

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3056]
We use [automodule + manually listed module entries](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/dev_section/api.rst) for our Sphinx-generated API documentation. These need to be updated whenever there are changes to module structure. 

Right now, the documentation isn't quite correct (e.g. [`spinalcordtoolbox.utils`](https://spinalcordtoolbox.com/en/stable/dev_section/api.html#module-spinalcordtoolbox.utils)), so I think this might have been missed with recent refactors (`labels.py` as well as, `utils.py` becoming `utils/fs.py`, `utils/shell.py`, `utils/sys.py`).

**Comment by Drulex** [comment]
I'm not sure if `spinalcordtoolbox.utils` should be part of the public facing API. It's a collection of a lot of stuff, most of which is not directly relevant for people wanting to build on top of `spinalcordtoolbox`. I would propose to keep this internal what do you think @joshuacwnewton ?

**Comment by joshuacwnewton** [comment]
I think that makes sense! And if we find that something in `utils` turns out to be useful for the public-facing API, this will nudge us to move it out of `utils`, which I think is probably a good thing. :sweat_smile:
