### ISSUE TITLE
for step #0, find transformation based on header only without using antsRegistration

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#306]
for faster processing...

**Comment by benjamindeleener** [comment]
Using python registration is possible! I think @SaraDupont made some affine registration between 2D images. Probably possible using numpy and scipy.

Here are some interesting links:
https://github.com/pyimreg/python-register
http://scipy-lectures.github.io/advanced/image_processing/

**Comment by SaraDupont** [comment]
The affine registration I did was using ants, I did rigid registration using scipy to find the transformation that minimize a L0-norm but it was not optimal...

**Comment by jcohenadad** [comment]
actually we don't need any optimization. Just a simple rigid transformation based on the headers.

**Comment by SaraDupont** [comment]
I think the easiest way to do that would be using scikit-image : 
http://scikit-image.org/docs/stable/auto_examples/applications/plot_geometric.html#example-applications-plot-geometric-py

**Comment by jcohenadad** [comment]
not sure about that... you will have to re-interpret nifti headers, which can be a nightmare.

**Comment by jcohenadad** [comment]
no need for this...
