### ISSUE TITLE
Add tqdm progress bars to SCT scripts

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3080]
>  **Note**: This issue has been created to document an old WIP pull request that had become stale. No issue had been opened for that PR, so this issue is to discuss whether it's worth starting fresh and continuing that work.

Before it was closed, PR #2553 aimed to add tqdm progress bars to SCT scripts. #2724 seems to have similar motivations. (SCT's progress bars being noisy in logs.)

(There is also one other commit in that PR related to setting log levels, but logging is now handled by `init_sct`, so I believe that work is outdated.)

Would tqdm still be useful for SCT?

**Comment by joshuacwnewton** [comment]
Thank you for the additional context! I see it is used throughout SCT, too. I suppose this issue is no longer needed, then?

**Comment by jcohenadad** [comment]
Indeed, we can probably close.
