### ISSUE TITLE
Initialization steps (arg passing, init_sct, main) not consistent between CLI scripts

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3085]
### `main()` vs. `main(args)`

Historically, CLI scripts have parsed args implicitly using `sys.argv`. However, we've started to write tests that involve calls to a CLI script's `main` function. So, scripts have been tweaked on a case-by-case basis to accept args (`main()` -> `main(args)`).

Right now, some of our scripts can be called using `main(args)`, while others can't and still require `subprocess`. This has presented a roadblock in new PRs where it is unclear what changes need to be done, e.g. https://github.com/neuropoly/spinalcordtoolbox/pull/3081#discussion_r537582769.

### Other initialization steps

Beyond this, there are little differences in the initialization steps across our CLI scripts as a whole, resulting in inconsistent behavior between scripts. For example, compare `sct_propseg` to `sct_deepseg`:

https://github.com/neuropoly/spinalcordtoolbox/blob/dc97d42730d7e603f83e54c68f242ad2bef7189b/spinalcordtoolbox/scripts/sct_propseg.py#L671-L676

https://github.com/neuropoly/spinalcordtoolbox/blob/dc97d42730d7e603f83e54c68f242ad2bef7189b/spinalcordtoolbox/scripts/sct_deepseg.py#L224-L226

Here, `sct_propseg` accepts parsed args (i.e. a namespace/dict), while `sct_deepseg` accepts unparsed args (i.e. a list of arg-value pairs). The exit behavior is different, too. And, this is just one example.

I think it might be useful to settle on a single convention, document it in the dev wiki, then apply it to each script. That way, we can expect predictable behavior from each script, e.g. when we're writing tests.

**Comment by joshuacwnewton** [comment]
Looking at a few of our scripts, here the simplest and most explicit convention I've seen:

```python
if __name__ == '__main__':
    init_sct()
    main(sys.argv[1:])

def main(args=None):
    parser = get_parser()
    args = parser.parse_args(args if args else ['--help'])
```

But, if anyone has any other suggestions, feel free to share. :slightly_smiling_face:

**Comment by jcohenadad** [comment]
@joshuacwnewton thank you so much for initiating this!

Few comments:
- We should probably also advise to update the logger level
- I'm not the best person to advise on best practice 😅  but i would suggest to change the input param from "args" to "argv", so there is no overwriting of the variable args to another type.

```python
def main(argv=None):
    # Get parser arguments
    parser = get_parser()
    args = parser.parse_args(argv if argv else ['--help'])
    arguments = parser.parse_args(args=args)
    # Update log level
    init_sct(log_level=cropper.verbose, update=True)
```

**Comment by joshuacwnewton** [comment]
> - We should probably also advise to update the logger level

That's a good point. 

Right now, in many places our existing behavior is to call `init_sct` twice. e.g. for `sct_analyze_lesion`, we do it once in the `if __name__ == "__main__"` block:

https://github.com/neuropoly/spinalcordtoolbox/blob/e07cd93cdd9f856b326f81efdd470d10ea642af2/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L576-L578

And then once again after argument parsing:

https://github.com/neuropoly/spinalcordtoolbox/blob/e07cd93cdd9f856b326f81efdd470d10ea642af2/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L550-L552

That seems to match how `init_sct` was designed, but I find the design to be a little strange. Passing `update=True` actually disables behavior within `init_sct`! So, I wonder if updating the global logging level should just be separated into a new function. Calling `init_sct(update=True)` is essentially like calling an entirely separate function, anyway, considering how the behavior changes! :sweat_smile:

**Comment by joshuacwnewton** [comment]
I've created a new page on the Wiki called [CLI script conventions](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)) and summarized the proposed changes in the [Structure](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)#structure) subsection. I'll be refactoring based on these recommendations.

(I also moved the bulk of the argparse material from the [Documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) page in to this new page. I think the doc recommendations are a lot easier to read, now.)

**Comment by jcohenadad** [comment]
@joshuacwnewton should we get rid of this: https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Code-style#cli-conventions ?

**Comment by joshuacwnewton** [comment]
Oh! I hadn't realized that was there, thank you for pointing it out. There are some details in that section that didn't get included on the new page. So, I'll transfer them over then get rid of that section. :smile:
