### ISSUE TITLE
sct_propseg should return segmentation file going no further then the value of "up" of "down"

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#309]
Propseg return segmentation that goes beyond the values of up and down

**Comment by tanguymagnan** [comment]
When specifying up and down the results are not the same at the bottom and the top of the image.
If "up" is specified, the segmentation will slowly vanish going beyond the "up" value.
If "down" is specified, the segmentation will slowly vanish but the last slice with non zero value will be the "down" value

**Comment by benjamindeleener** [comment]
Furthermore, the -init-centerline overrides the -up and -down options but it shouldn't.
See related post here: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/fd94451c/

**Comment by benjamindeleener** [comment]
This issue is now normally fixed. A cropping is done after the segmentation to be sure that the segmentation does not go above or below flags.
