### ISSUE TITLE
ANTs based tools don't set sform

### ISSUE THREAD

**Issue by cfhammill** [neuropoly/spinalcordtoolbox#3097]
Related to #2858 it appears that ANTs based programs fail to set the sform field in the NIfTI headers. For the first example we'll look at `sct_register_multimodal` which uses ANTs under the hood.

```
sct_download_data -d course_london19/
cd course_london19/multi_subject/data/sub-01/anat/
sct_register_multimodal \
  -i sub-01_acq-MTon_MTS.nii.gz \
  -d sub-01_acq-MToff_MTS.nii.gz \
  -param step=1,type=im,algo=rigid,slicewise=1,metric=CC \
  -x spline
```

Then in python check that both input images and the transformation have valid sforms

```python
s = Image("sub-01_acq-MTon_MTS.nii.gz")
t = Image("sub-01_acq-MToff_MTS.nii.gz")
x = Image("warp_sub-01_acq-MToff_MTS2sub-01_acq-MTon_MTS.nii.gz")
print(s.hdr.get_sform())
print(t.hdr.get_sform())
print(x.hdr.get_sform())
```

gives

```
[[ 8.98437500e-01  6.13959088e-08  3.44130327e-04 -1.14131424e+02]
 [-1.00533734e-05  8.86628509e-01  8.08007956e-01 -1.22961884e+02]
 [-6.10132338e-05 -1.45188943e-01  4.93427992e+00 -1.73513947e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[ 8.98437500e-01  6.13959088e-08  3.44130327e-04 -1.14131424e+02]
 [-1.00533734e-05  8.86628509e-01  8.08007956e-01 -1.22961884e+02]
 [-6.10132338e-05 -1.45188943e-01  4.93427992e+00 -1.73513947e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
```

The last of which is not a valid affine matrix, the 1 is added by nibabel, because the sform field holds only 12 float numbers, the last row `0 0 0 1` is added automatically. So this is I believe the output when the sform is left uninitialized.

To demonstrate this issue effects more than just `sct_register_multimodal` we can fix the header and check that it gets fixed.

```python
from spinalcordtoolbox.image import Image
x = Image("warp_sub-01_acq-MToff_MTS2sub-01_acq-MTon_MTS.nii.gz")
x.hdr.set_sform(x.hdr.get_qform())
print(x.hdr.get_sform())

x.save("warp_header_fixed.nii.gz")
```

prints the correct

```
[[ 8.98437500e-01  6.13952693e-08  3.44130327e-04 -1.14131424e+02]
 [-1.00533725e-05  8.86628509e-01  8.08007956e-01 -1.22961884e+02]
 [-6.10132338e-05 -1.45188943e-01  4.93427992e+00 -1.73513947e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```

but then if we apply the the fixed transformation using `isct_antsApplyTransforms` which is our vendored binary of the associated ANTs program

```
isct_antsApplyTransforms -i sub-01_acq-MTon_MTS.nii.gz \
  -r sub-01_acq-MToff_MTS_reg.nii.gz \
  -t warp_header_fixed.nii.gz \
  -d 3 \
  -o sub_warped.nii.gz
```

then check the sform of the warped file 

```python
from spinalcordtoolbox.image import Image
d = Image("sub_warped.nii.gz")
print(d.hdr.get_sform())
```

we get

```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
```

So it appears that some, if not all, ANTs programs do not initialize the sform field. This makes it challenging to insist on qform and sform matching, although it seems likely that we can special case this situation so that uninitialized sforms are corrected by `Image`.

**Comment by joshuacwnewton** [comment]
Would this be something to report on https://github.com/ANTsX/ANTs?

**Comment by jcohenadad** [comment]
> Would this be something to report on https://github.com/ANTsX/ANTs?

https://github.com/ANTsX/ANTs/issues/333  🙂

**Comment by cfhammill** [comment]
So the real issue is that we appear to have at least one program in sct that uses the sform, so our plan to require sform = qform is made challenging by the fact that ANTs outputs don't satisfying this requirement (that's why #2858 has been on hold). This issue was to prove the problem was due to ANTs and not issues with the dummy data. We can close this and move the conversation back to the PR

**Comment by joshuacwnewton** [comment]
> So the real issue is that we appear to have at least one program in sct that uses the sform, so our plan to require sform = qform is made challenging by the fact that ANTs outputs don't satisfying this requirement

As an update: @jcohenadad reduced the scope of #2858 so that we only require sform = qform in `sct_straighten_spinalcord` for now. 

> We can close this and move the conversation back to the PR

Done. :slightly_smiling_face:
