### ISSUE TITLE
install_sct: homebrew's installer is now in bash

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#3105]
Us:

https://github.com/neuropoly/spinalcordtoolbox/blob/11249f7b9eab4791cd1834c537cfafd1379bac02/install_sct#L173

but that link (currently pointed at https://github.com/Homebrew/install/blob/e141d766960553367441362490e42a2fead644c6/install) suggests

> Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
> Bash. Please migrate to the following command:
>  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

Why do we even have this again? In order to be able to install gcc? Which is because some the dependencies of our dependencies don't have macOS .whls? Seems like these are the historical context? #2404, #2410, #2577.

Anyway I'm going to do this migration but then we should talk about getting rid of it entirely if we can.

**Comment by kousu** [comment]
Shouldn't we be using `xcode-select --install` on macOS?

**Comment by jcohenadad** [comment]
> Shouldn't we be using `xcode-select --install` on macOS?

you're probably right. I'm not 100% sure if the syntax works for all macOs (past, present and future), which is why (I think) I was suggesting to use Homebrew. 
Examples in the forum where xcode-select was successfully used: https://forum.spinalcordmri.org/t/installation-validation-failed-installation-failed/570/9

**Comment by joshuacwnewton** [comment]
> Why do we even have this again? In order to be able to install gcc?

Yes, exactly. :slightly_smiling_face: 

There is more relevant discussion/context about whether we should be touching `gcc` in #3049, starting from https://github.com/neuropoly/spinalcordtoolbox/issues/3049#issuecomment-728980021.
