### ISSUE TITLE
Link between Specific references and SCT functions

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#3118]
**Feature justification: Is your feature request related to a problem? Please describe.**

Reference [page](https://spinalcordtoolbox.com/en/stable/overview/references.html#references) of RTD states:
```
If you use SCT in your research or as part of your developments, please always cite the main reference. If you use specific tools such as sct_deepseg_sc or the PAM50 template, please also cite the specific articles listed in specific references.
```

But in the section [Specific References](https://spinalcordtoolbox.com/en/stable/overview/references.html#specific-references): it is maybe not clear enough which paper refers to which SCT function.

**Describe the solution you'd like**

It would be nice to make this link clearer: via a table (SCT function // Paper to cite)? or a simple mention (please cite this article if you used sct_*)

**Comment by jcohenadad** [comment]
> via a table

i like that!
