### ISSUE TITLE
Auto-help in sct scripts should return an error

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#3137]
It looks like after #3091 every script has the glitch that being run without arguments returns 0 ("no error"), because they all have this line in them:

```
arguments = parser.parse_args(argv if argv else ['--help'])
```

For some scripts it's truly not an error to be called with no args (like `sct_check_requirements`), but for others it is.

We need this behaviour for correct shell scripting with them:

```
$ ./script -h; echo $?
usage: script [-h]

optional arguments:
  -h, --help  show this help message and exit
0
$ ./script; echo $?
usage: script [-h]

optional arguments:
  -h, --help  show this help message and exit
2
```

_Originally posted by @kousu in https://github.com/neuropoly/spinalcordtoolbox/pull/3091#issuecomment-751946174_

**Comment by kousu** [comment]
I'm trying to figure out what to do about it.

1. `add_help=None` + `.add_argument("-h", "--help", ...)` seems to be entirely redundant. Just dropping both gives the same behaviour.
2. `optional = parser.add_argument_group("\nOPTIONAL ARGUMENTS")` is redundant; all it does is replace "optional arguments" with "OPTIONAL ARGUMENTS" in the help. I guess that was on purpose at some point?
2. With those removed I can see that while argparse is smart enough to return an error code to the shell, it doesn't print the help like you wanted it to:
    ```
    #!/usr/bin/env python3

    import sys, os
    import argparse

    def main(argv=None):
        parser = argparse.ArgumentParser(
            description='Check the installation and environment variables of the toolbox and its dependencies.',
        )
        parser.add_argument(
            '-complete',
            help="Complete test.",
            action="store_true")
        parser.add_argument(
            "-short",
            help="Short test. Only shows SCT version, CPU cores and RAM available.",
            action="store_true")

        arguments = parser.parse_args(sys.argv)
        print(arguments)

    if __name__ == '__main__':
      main(sys.argv)
    ```

    ```
    [kousu@requiem spinalcordtoolbox]$ ./args.py; echo $?
    usage: args.py [-h] [-complete] [-short]
    args.py: error: unrecognized arguments: ./args.py
    2

    [kousu@requiem spinalcordtoolbox]$ ./args.py -h; echo $?
    usage: args.py [-h] [-complete] [-short]

    Check the installation and environment variables of the toolbox and its dependencies.

    optional arguments:
      -h, --help  show this help message and exit
      -complete   Complete test.
      -short      Short test. Only shows SCT version, CPU cores and RAM available.
    0
    ```

so that's a change to the output; an error != automatic help.

I found two solutions: https://stackoverflow.com/questions/4042452/display-help-message-with-python-argparse-when-script-is-called-without-any-argu

1. Override `error()`
    ```
    #!/usr/bin/env python3

    import sys, os
    import argparse

    class AutoHelpParser(argparse.ArgumentParser):
      # https://stackoverflow.com/a/4042861
      def error(self, message):
          #sys.stderr.write(f'{os.path.basename(__file__)}: error: {message}\n')
          self.print_help(sys.stderr)
          sys.exit(2)

    def main(argv=None):
        parser = AutoHelpParser(
            description='Check the installation and environment variables of the toolbox and its dependencies.',
        )
        parser.add_argument(
            '-complete',
            help="Complete test.",
            action="store_true")
        parser.add_argument(
            "-short",
            help="Short test. Only shows SCT version, CPU cores and RAM available.",
            action="store_true")

        arguments = parser.parse_args(sys.argv)
        print(arguments)

    if __name__ == '__main__':
      main(sys.argv)
    ```

    ```
    [kousu@requiem spinalcordtoolbox]$ python3 args.py -h; echo $?
    usage: args.py [-h] [-complete] [-short]

    Check the installation and environment variables of the toolbox and its dependencies.

    optional arguments:
    -h, --help  show this help message and exit
    -complete   Complete test.
    -short      Short test. Only shows SCT version, CPU cores and RAM available.
    0
    [kousu@requiem spinalcordtoolbox]$ python3 args.py; echo $?
    usage: args.py [-h] [-complete] [-short]

    Check the installation and environment variables of the toolbox and its dependencies.

    optional arguments:
    -h, --help  show this help message and exit
    -complete   Complete test.
    -short      Short test. Only shows SCT version, CPU cores and RAM available.
    2
    ```
    `
2. you're supposed to be able to do https://docs.python.org/3/library/argparse.html#exit-on-error
    ```
    try:
      arguments = parser.parse_args(sys.argv)
    except argparse.ArgumentError:
      parser.print_help(sys.stderr)
      sys.exit(2)
    ``` 
    But:
    1. Only python3.9+ and by setting a special flag
    3. it doesn't seem to actually ever raise `ArgumentError`
    If you want to try to figure this one out here's my WIP code:
    ```
    #!/usr/bin/env python3

    import sys, os
    import argparse

    def main(argv=None):
        parser = argparse.ArgumentParser(
            description='Check the installation and environment variables of the toolbox and its dependencies.',
            exit_on_error=False
        )
        parser.add_argument(
            '-complete',
            help="Complete test.",
            action="store_true")
        parser.add_argument(
            "-short",
            help="Short test. Only shows SCT version, CPU cores and RAM available.",
            action="store_true")

        try:
          arguments = parser.parse_args(sys.argv)
        except argparse.ArgumentError:
          parser.print_help(sys.stderr)
          sys.exit(244)

        print(arguments)

    if __name__ == '__main__':
      main(sys.argv)
    ```

I think, given that we want like 57 scripts to all share this behaviour, we should go with option 1, using that little stub class for all our parsers to inherit from.

**Comment by kousu** [comment]
We also could override [`print_usage()`](https://github.com/python/cpython/blob/c56988b88fecf6dc70f039704fda6051a0754db1/Lib/argparse.py#L2540-L2543) which is what `error()` calls by default:

```
#!/usr/bin/env python3

import sys, os
import argparse


class AutohelpParser(argparse.ArgumentParser):
    def print_usage(self, file=None):
        super().print_help(file=file)
        print("", file=file)

def main(argv=None):
    parser = AutohelpParser(
        description='Check the installation and environment variables of the toolbox and its dependencies.',
    )
    parser.add_argument(
        '-complete',
        help="Complete test.",
        action="store_true")
    parser.add_argument(
        "-short",
        help="Short test. Only shows SCT version, CPU cores and RAM available.",
        action="store_true")

    arguments = parser.parse_args(sys.argv)
    print(arguments)

if __name__ == '__main__':
  main(sys.argv)
```

```
[kousu@requiem spinalcordtoolbox]$ python3 args.py; echo $?
usage: args.py [-h] [-complete] [-short]

Check the installation and environment variables of the toolbox and its dependencies.

optional arguments:
  -h, --help  show this help message and exit
  -complete   Complete test.
  -short      Short test. Only shows SCT version, CPU cores and RAM available.

args.py: error: unrecognized arguments: args.py
2
[kousu@requiem spinalcordtoolbox]$ python3 args.py -h; echo $?
usage: args.py [-h] [-complete] [-short]

Check the installation and environment variables of the toolbox and its dependencies.

optional arguments:
  -h, --help  show this help message and exit
  -complete   Complete test.
  -short      Short test. Only shows SCT version, CPU cores and RAM available.
0
```

This puts the error message at the bottom, which is maybe more obvious to users?

**Comment by kousu** [comment]
@jcohenadad preferences?

**Comment by jcohenadad** [comment]
> optional = parser.add_argument_group("\nOPTIONAL ARGUMENTS") is redundant; all it does is replace "optional arguments" with "OPTIONAL ARGUMENTS" in the help. I guess that was on purpose at some point?

In some CLI scripts, we have more "optional" group names, e.g. "Advanced params", "Input/Output", etc.

> @jcohenadad preferences?

I'm not sure what all implications are, but option 3 "override print_usage()" seems minimally invasive and works not only for py39. @kousu @joshuacwnewton what are your preferences?

**Comment by joshuacwnewton** [comment]
> I'm trying to figure out what to do about it.
> 
>   1. `add_help=None` + `.add_argument("-h", "--help", ...)` seems to be entirely redundant. Just dropping both gives the same behaviour.
> 
>   2. `optional = parser.add_argument_group("\nOPTIONAL ARGUMENTS")` is redundant; all it does is replace "optional arguments" with "OPTIONAL ARGUMENTS" in the help. I guess that was on purpose at some point?
>
>   3. With those removed I can see that while argparse is smart enough to return an error code to the shell, it doesn't print the help like you wanted it to:

Unfortunately, it's not so simple to remove these two things. They're workarounds that stem from our decision to use a single dash for every argument. Check out the notes on [Argument Groups](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)#argument-groups) and [`add_help=None`](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)#add_helpnone) in the dev Wiki for a more in-depth explanation.

Case in point: If you were to try adding a mandatory argument to the demo parsers in https://github.com/neuropoly/spinalcordtoolbox/issues/3137#issuecomment-751956210 and https://github.com/neuropoly/spinalcordtoolbox/issues/3137#issuecomment-751958254, I think you'd run into [this argparse annoyance](https://stackoverflow.com/questions/24180527/argparse-required-arguments-listed-under-optional-arguments).

**Comment by joshuacwnewton** [comment]
A side observation: Regardless of which function we override, subclassing `ArgumentParser` would be a welcome change, because if we're importing a parser, we would be able to centralize other steps, too. These are currently [copied and pasted across every script](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)#argparse-initialization):

* Setting `formatter_class`and `prog`
* Setting `add_help` and adding argument groups
* Adding `-v` and `-r` arguments.

I've felt icky manually editing script by script to make the same changes over and over (thus causing conflicts for pretty much every open PR), so I'm happy to see this.

**Comment by kousu** [comment]
> To add onto what @jcohenadad has said, it's not so simple to remove these two things, I think. They're workarounds that stem from our decision to use a single dash for every argument.

Oookay, gotcha. We can leave that as is then.

> I'm not sure what all implications are, but option 3 "override print_usage()" seems minimally invasive and works not only for py39. @kousu @joshuacwnewton what are your preferences?

I lean slightly to option 1, which prints the error and then the help. instead of printing the help and then the error, but it's not a big deal either way. Option 1 works on python3.6 just as well.

**Comment by kousu** [comment]
If you pull all the quirks into a base class, would it make sense to move all the workarounds from [the wiki](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-CLI-script-conventions-(structure,-argparse)#add_helpnone) into comments on it?

**Comment by joshuacwnewton** [comment]
Exactly. The reason I hadn't done that already was because I would have been copying and pasting the same comments all over the scripts... :sweat_smile: 

Doing that will hopefully make the quirks less confusing on a first readthrough of the codebase. (This has tripped up at least me, you, and Chris so far.)
