### ISSUE TITLE
Tensorboard version mismatch between requirements.txt and actual installed version

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3145]
In #3041, the version of tensorboard was pinned to `1.14.0`.

https://github.com/neuropoly/spinalcordtoolbox/blob/d64af23b69dbc396322cdc963a90a899b73736e0/requirements.txt#L43

Also in #3041, tensorboard gets reinstalled, which was as part of a fix for #3035. (See https://github.com/neuropoly/spinalcordtoolbox/pull/3034#discussion_r527004400 for rationale.) 

https://github.com/neuropoly/spinalcordtoolbox/blob/d64af23b69dbc396322cdc963a90a899b73736e0/install_sct#L614-L620

But because we simply specify `pip install tensorboard`, the newest version (`2.4.0`) gets installed , and we get this warning:

```
Check if tensorboard (1.14.0) is installed..........[WARNING] (2.4.0 != 1.14.0 mandated version))
```

**Comment by joshuacwnewton** [comment]
@lrouhier @andreanne-lemay Could you clarify why we needed to pin tensorboard to 1.14.0?

**Comment by jcohenadad** [comment]
@charleygros maybe also has a clue?

**Comment by lrouhier** [comment]
Hi, I know we pinned it in the requirements but I am pretty sure it is not needed because, in any case, we use the 2.4.0 due to what was in #3041 and #3082 ... We don't pin it in Ivadomed so I am pretty sure you can remove that from the requirements :)
I think it came from one of the tests we were doing at the time to try and determine where the tensorboard issue was coming from.

**Comment by joshuacwnewton** [comment]
Thanks for the input, @lrouhier. Glad to hear that it is not a hard requirement for anything. :smile:

**Comment by jcohenadad** [comment]
We might want to fix it before releasing 5.1.0, just to avoid this ugly warning after installing SCT:
~~~
[...]
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.2)
Check if pytest_console_scripts is installed........[OK]
Check if pytest-xdist is installed..................[OK] (2.2.0)
Check if tensorboard (1.14.0) is installed..........[WARNING] (2.4.1 != 1.14.0 mandated version))
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
[...]
~~~

**Comment by joshuacwnewton** [comment]
Good thinking. The fix is dead-simple, too. :smile:

**Comment by kousu** [comment]
According to https://patch-diff.githubusercontent.com/raw/neuropoly/spinalcordtoolbox/pull/3041.diff, #3041 put in two attempts to control the version of tensorboard in play.

```diff
diff --git a/install_sct b/install_sct
index 956f00cf98..8ded9e9d82 100755
--- a/install_sct
+++ b/install_sct
@@ -538,6 +538,10 @@ else
   # Not a package
   print info "Using requirements.txt (git installation)"
   pip install -r requirements.txt
+  yes | pip uninstall tensorflow-tensorboard
+  yes | pip uninstall tensorboard
+  pip install tensorboard
+
 fi
 if [[ $? != 0 ]]; then
   die "Failed running pip install: $?"
diff --git a/requirements.txt b/requirements.txt
index d9e5b31d94..d512506991 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -4,8 +4,8 @@ futures
 # h5py is pinned to minor than 3 due to issues with Keras/TF
 # https://github.com/tensorflow/tensorflow/issues/44467
 h5py~=2.10.0
-ivadomed==2.4.0
 Keras==2.1.5
+ivadomed==2.6.0
 matplotlib
 nibabel
 numpy
@@ -40,3 +40,4 @@ transforms3d
 urllib3[secure]
 pytest_console_scripts
 pytest-xdist
+tensorboard==1.14.0
```

So, just an oversight that slipped through review on that. I'll approve the fixup PR now :)
