### ISSUE TITLE
Remove Travis

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#3150]
We're migrating to Github Actions in #3125. Personally, I want to keep Travis alive for a little while, but in not too long -- let's say by the end of Februrary? -- we should remove our repos from travis-ci.com's UI and delete:

* .travis.yml
* .travis.sh
* maybe: util/dockerize.sh -- though this isn't Travis specific, and I'm proud of it, we only use it for Travis

_Originally posted by @kousu in https://github.com/neuropoly/spinalcordtoolbox/pull/3125#discussion_r551067762_

We should have these transition periods:

0. Only Travis
1. Travis + Actions
2. Travis [non-mandatory] + Actions
3. Only Actions

That way there won't be too many surprises. @joshuacwnewton [figured out](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks) that for the intermediate stage, just go to https://github.com/neuropoly/spinalcordtoolbox/settings/branch_protection_rules/12845205 and turn off/on the different checks; hopefully disabling the Travis check still means Travis runs, just that it doesn't block:

![2020-12-28-141200_911x219_scrot](https://user-images.githubusercontent.com/987487/103237787-b170cd00-4916-11eb-95b7-08f94c458e9c.png)

_Originally posted by @kousu in https://github.com/neuropoly/spinalcordtoolbox/issues/3071#issuecomment-751832655_

**Comment by joshuacwnewton** [comment]
Note to self: When removing `.travis.yml`, also remove @kousu's `travis.sh` and `dockerize.sh` scripts. Since GitHub Actions has nicer WSL support, I don't think these are needed anymore.

See: https://github.com/neuropoly/spinalcordtoolbox/pull/3144#issuecomment-811250407

**Comment by joshuacwnewton** [comment]
Note to self: Also remove the Travis banner from our documentation -- it currently shows "build: Failing" which is a bit ugly. :sweat_smile:
