### ISSUE TITLE
Add the possibility to use custom model

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3155]
### Description

After training a new model with [ivadomed](http://ivadomed.org/), it would be great to be able to use it directly with `sct_deepseg`.

However, it is unclear how to do it. As of SCT version 5.0.1dev (3dfd4f81f9e4364dab4d94894ea687a625dbdea5), the usage specifies the following:
~~~
  -task <str>           Task to perform. It could either be a pre-installed task, task that could be installed, or a custom task. To list
                        available tasks, run: sct_deepseg -list-tasks
  -list-tasks           Display a list of tasks that can be achieved. (default: False)
  -install-task {seg_sc_t2star,seg_mice_sc,seg_mice_gm,seg_tumor_t2,seg_tumor-edema-cavity_t1-t2}
                        Install models that are required for specified task.
~~~

under "-task", it says that we could choose a "custom task", but how to achieve it is unclear: should "-task" point to the .pt model file? Something else?

This issue is somewhat related to #2996, which removed the possibility to point to models. But what is the proposed alternative if someone wants to use a custom model?

@charleygros @andreanne-lemay any thoughts?

**Comment by charleygros** [comment]
Mmmm yep.. this is currently not straightforward.
You will need to go in the code and add [some lines](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/models.py#L77) :/

To add a flag `model` would be going backwards..
Could we ask the user to dump their custom model in `sct-dev/data/deepseg_models`? eg `sct-dev/data/deepseg_models/custom_model` (following the correct folder format) and to input (somehow) a dictionary that would be used [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg/models.py#L78).. so something like:
```python
    'custom_model':
        { 'models': ['custom_model1']},
```

**Comment by andreanne-lemay** [comment]
We could probably do the same thing we did with models, but with task instead. If we want to use a custom task, we put the path to the packaged ivadomed model:

`sct_deepseg -i img.nii.gz -task path/to/ivadomed-model/custom`

This would probably be more user friendly than moving the file. Let me know your thoughts.

**Comment by charleygros** [comment]
Agree with @andreanne-lemay ! I think it will only work with one-step approach (ie no cascade). But I think it is fine: the user can use the output of the first custom model to run the second step.

**Comment by andreanne-lemay** [comment]
Yes indeed, I think it is a reasonable compromise. I'll add this to my to-do list.

**Comment by jcohenadad** [comment]
> Agree with @andreanne-lemay ! I think it will only work with one-step approach (ie no cascade).

We could also envision `-task` allowing more than one input (e.g.: -task model1 model2)

**Comment by andreanne-lemay** [comment]
> 
> We could also envision `-task` allowing more than one input (e.g.: -task model1 model2)

True, I'll try to generalize it to multiple models as well.
