### ISSUE TITLE
Funky visual bug on the QC report for vertebral labeling

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3173]
The "funky" looks like this:
![104671956-d1d9af00-56ac-11eb-9fa0-e4ca6ee25ccc](https://user-images.githubusercontent.com/2482071/104676128-c8544500-56b4-11eb-8205-3163bbafdd53.png)

More details about how to reproduce this bug: https://github.com/neuropoly/ukbiobank-spinalcord-csa/issues/20#issuecomment-760603448

**Comment by joshuacwnewton** [comment]
@sandrinebedard shared a follow-up comment (https://github.com/neuropoly/ukbiobank-spinalcord-csa/issues/20#issuecomment-760631578), so I'm reposting that here:

> Hummm, I looked on FSLeyes at the results and same thing appeared! But I found the problem, it was the interpolation causing this while applying the transformation to the labeling. Adding `-n NearestNeighbor` to `isct_antsApplyTransforms` did the trick to keep the labeling! All good now, not a visual bug in the QC!

Closing this as it was not a visual bug. :slightly_smiling_face:
