### ISSUE TITLE
Unit tests in test_cli.py don't work as expected

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#3186]
### Description

Context: https://github.com/neuropoly/spinalcordtoolbox/pull/3181#issuecomment-763855531 and https://github.com/neuropoly/spinalcordtoolbox/pull/3181#issuecomment-763871322

### Steps to Reproduce

- Bypass the `main` function of any cli script and return something else than 2.
- Run `pytest unit_testing/cli/test_cli.py::test_scripts_with_no_args_as_subprocess` and notice that unit test passes even if the script called without argument returns something other than 2.

**Expected behavior:** <What you expect to happen>
Unit test should fail

**Comment by Drulex** [comment]
@kousu is it possible that in this line you meant to pass `scripts_to_test` instead of `scripts_without_callable_main`?

https://github.com/neuropoly/spinalcordtoolbox/blob/073bac3b0307fb90ebc49c98c09058044fa20bea/unit_testing/cli/test_cli.py#L38

**Comment by joshuacwnewton** [comment]
@Drulex Small heads up -- I wrote this one. (It's a little confusing because I took over that PR.)

`scripts_to_test` is the larger group, but it gets split into 2 subgroups:
* scripts_with_callable_main: Use `sct_script.main()` to test these
* scripts_without_callable_main: Use subprocess (i.e. `pytest_console_scripts`) to test.

**Comment by Drulex** [comment]
> @Drulex Small heads up -- I wrote this one. (It's a little confusing because I took over that PR.)
> 
> `scripts_to_test` is the larger group, but it gets split into 2 subgroups:
> 
>     * scripts_with_callable_main: Use `sct_script.main()` to test these
> 
>     * scripts_without_callable_main: Use subprocess (i.e. `pytest_console_scripts`) to test.

I don't understand, am I calling it wrong? It's only testing 2 scripts. See below:

```
 $  pytest unit_testing/cli/test_cli.py::test_scripts_with_no_args_as_subprocess -o log_cli=True

---------------------------------------------------------------------------------------------------------------------------------- live log sessionstart ----------------------------------------------------------------------------------------------------------------------------------
WARNING  spinalcordtoolbox.download:download.py:141 Removing existing destination folder 'sct_testing_data'
INFO     spinalcordtoolbox.download:download.py:41 Trying URL: https://github.com/sct-data/sct_testing_data/releases/download/r20210114/sct_testing_data-r20210114.zip
INFO     spinalcordtoolbox.download:download.py:62 Downloading: sct_testing_data-r20210114.zip
Status: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.17M/7.17M [00:00<00:00, 20.7MB/s]
INFO     spinalcordtoolbox.utils.fs:fs.py:26 Creating temporary folder (/tmp/sct-20210125153846.979744-h8xu6_38)
INFO     spinalcordtoolbox.download:download.py:88 Unzip data to: /tmp/sct-20210125153846.979744-h8xu6_38
INFO     spinalcordtoolbox.download:download.py:201 Removing temporary folders...
Done!

=================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.6.12, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/drulex/work/exmakhina/neuropoly/spinalcordtoolbox, configfile: setup.cfg
plugins: forked-1.3.0, cov-2.11.1, console-scripts-1.1.0, parallel-0.1.0
collected 2 items                                                                                                                                                                                                                                                                         

unit_testing/cli/test_cli.py::test_scripts_with_no_args_as_subprocess[subprocess-isct_convert_binary_to_trilinear] PASSED                                                                                                                                                           [ 50%]
unit_testing/cli/test_cli.py::test_scripts_with_no_args_as_subprocess[subprocess-isct_minc2volume-viewer] PASSED                                                                                                                                                                    [100%]

==================================================================================================================================== 2 passed in 0.71s ====================================================================================================================================
```

**Comment by joshuacwnewton** [comment]
It's supposed to test only 2 scripts, because those 2 scripts don't let you call them via `main()`. The remaining scripts should be tested using the other test:

https://github.com/neuropoly/spinalcordtoolbox/blob/073bac3b0307fb90ebc49c98c09058044fa20bea/unit_testing/cli/test_cli.py#L25

**Comment by Drulex** [comment]
Ah ok I understand. Let me rework my repro steps, because it definitely failed to catch the bug mentioned here https://github.com/neuropoly/spinalcordtoolbox/pull/3181#issuecomment-763871322. The problem may be somewhere else.

**Comment by Drulex** [comment]
Closing because I can't reproduce.
