### ISSUE TITLE
Enable to interactively assess QC on a per-subject basis and export file listing subjects to correct

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3187]
Currently, the QC report enables to go through subjects and verify the quality of segmentation, etc.

If segmentations are bad, the user manually note (eg on a piece of paper) what subjects were problematic, and then generate e.g. a YAML file that lists those subjects. This should ideally be automatized as follows:
- During QC, the user could press "space" for ✅ , and "space space" for ❌ 
- At any moment, the user can press a button that would write a file listing the subjects that warrant correction

**Comment by kousu** [comment]
This is a web UI task, because our QC reports are interactive web apps.

I think adding the UI, and keyboard shortcuts, for marking should be easy.

The hard thing is extracting the data. We need to produce a .yml file listing the corrected. Web browsers can't usually get out of their sandbox. However, there is [this experimental API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) which breaks the sandbox a bit, and that is probably good enough since it's not like our QC reports need to go out to hundreds of users on unusual platforms?

I don't know what the .yml format we need specifically is. Is it defined in our codebase somewhere?

**Comment by jcohenadad** [comment]
> I don't know what the .yml format we need specifically is. Is it defined in our codebase somewhere?

Something like the one described [here](https://spine-generic.readthedocs.io/en/latest/analysis-pipeline.html#segmentation-and-vertebral-labeling)

**Comment by Drulex** [comment]
As discussed in the meeting, a preliminary idea would be to have a (lightweight) backend to serve the page and expose a few endpoints so that the user can make the appropriate requests and generate the results file.

**Comment by Drulex** [comment]
Started to look at this, I think we can probably get away without a backend and use javascript to create the `yaml` and expose it for download to the user.

@jcohenadad it would be useful if you or someone else can do a (very quick) demo showing the flow of how someone goes through the qc report and where the icons/buttons should appear, etc.

**Comment by jcohenadad** [comment]
> @jcohenadad it would be useful if you or someone else can do a (very quick) demo showing the flow of how someone goes through the qc report and where the icons/buttons should appear, etc.

https://www.dropbox.com/s/nujin241fttmzpd/20210225_qc_pass-fail.mov?dl=0

**Comment by jcohenadad** [comment]
> @jcohenadad it would be useful if you or someone else can do a (very quick) demo showing the flow of how someone goes through the qc report and where the icons/buttons should appear, etc.

https://www.dropbox.com/s/nujin241fttmzpd/20210225_qc_pass-fail.mov?dl=0

**Comment by Drulex** [comment]
> > @jcohenadad it would be useful if you or someone else can do a (very quick) demo showing the flow of how someone goes through the qc report and where the icons/buttons should appear, etc.
> 
> https://www.dropbox.com/s/nujin241fttmzpd/20210225_qc_pass-fail.mov?dl=0

Excellent makes perfect sense.

**Comment by joshuacwnewton** [comment]
> My only comment is that we could potentially use a different key than `Space` since it may already be a keyboard shortcut (for example in Firefox it scrolls down the screen: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly).

This might be a relevant read: https://sashika.medium.com/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee

> **Letters only shortcuts**
> There’s a very good option to spare yourself headache of selecting modifiers and avoid mixing them up with the native browser and OS shortcuts. Letters. One or two letter shortcuts are simpler and easier to remember, they won’t interfere with OS or browser.
