### ISSUE TITLE
NewConnectionError for PyTorch whl -f link

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3190]
Opening this issue to track research on a user issue from the forum. https://forum.spinalcordmri.org/t/installation-failed-in-ubuntu/610

### Issue description

```python
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe056f410f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0566fd860>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0566fd908>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0566fdda0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0566fda90>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch_stable.html
Collecting torch==1.5.0+cpu
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe0566f6d30>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch-1.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe056708908>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch-1.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe056708b38>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch-1.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe056708438>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch-1.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe056708cf8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /whl/cpu/torch-1.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/cpu/torch-1.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe05668d278>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

Error relates to the  -f link in `requirements.txt`. (Relevant context is in https://github.com/neuropoly/spinalcordtoolbox/issues/1526#issuecomment-674330466.)

https://github.com/neuropoly/spinalcordtoolbox/blob/b64cad3c846fd6bd7a557688b67b80fe0b2c6dc2/requirements.txt#L26

### Possible causes

There are reports of similar errors from [China](https://github.com/rusty1s/pytorch_geometric/issues/1995#issuecomment-759147599) and [Bulgaria/Russia](https://discuss.pytorch.org/t/pip-cant-download-pytorch-previous-downloads-page-doesnt-work-either/19706/4), but neither report is an exact match.

**Comment by joshuacwnewton** [comment]
I don't have a good explanation for this error. The user is able to navigate to the `torch_stable.html` wheel mirror in their browser, yet can't connect via `pip`. The only similar report I could find was [here](https://discuss.pytorch.org/t/pip-cant-download-pytorch-previous-downloads-page-doesnt-work-either/19706/2):

> Update: firefox fails, pip fails, wget fails, chromium works for some reason.
> 
> The only thing I can guess, is that they filter requests in some way by user-agent AND location, so firefox-bulgaria is filtered, while chrome-bulgaria and firefox-russia are not.

Because I am not sure of the cause, [I have instructed them](https://forum.spinalcordmri.org/t/installation-failed-in-ubuntu/610/5?u=joshuacwnewton) to download the wheels via their browser, then manually install them.

**Comment by kousu** [comment]
This is one of the reasons [against developers distributing their own software](https://drewdevault.com/2019/12/09/Developers-shouldnt-distribute.html). Even though sometimes it happens (even this week: https://lwn.net/SubscriberLink/842319/8adb13e08d0302bd/, https://lwn.net/Articles/843313/), it leaves you us and our users at the whims and resources of upstream. We had a different problem with them a month or so ago: https://github.com/neuropoly/spinalcordtoolbox/issues/3107

**Comment by kousu** [comment]
[soapbox]

torch also [vendors protobuf](https://github.com/pytorch/pytorch/issues/43140) which means you can't use that yourself safely. You can maybe version-pin to the same protobuf they have and hope that works but it still means loading redundant code twice, and just because the version number is the same doesn't actually prove it's compatible; it might have been compiled with different compilers with different compiler options. And similarly, they [implicitly pin to python3.6](https://stackoverflow.com/a/59730344/2898673) apparently? But they don't mark that in their setup.py?

I think the underlying issue here is that torch is facebook's project, and they can afford to do factory-scale data processing, stamping out identical Ubuntu machines to run their code on; we are user-facing, and we need to deal with the diversity of user systems (which I am in *full* support of. diversity is a strength) which means we run into oversights in their project that, for them, aren't bugs because why would you ever try to run torch on something that isn't Ubuntu, silly rabbits?

[/soapbox]

**Comment by kousu** [comment]
Thanks for finding a workaround in the meantime, @joshuacwnewton.

**Comment by kousu** [comment]
Oh this is related to https://github.com/pytorch/pytorch/issues/26340 btw

**Comment by joshuacwnewton** [comment]
Update: The user was able to move past the connection issues with the PyTorch link using the workaround in https://github.com/neuropoly/spinalcordtoolbox/issues/3190#issuecomment-765518794.

However, they have now run into a similar issue, only [for `sct_download_data`](https://forum.spinalcordmri.org/t/installation-failed-in-ubuntu/610/6?u=joshuacwnewton). Remarkably, it failed for both the osf.io link and the neuro.polymtl.ca mirror.

```python
Trying URL: https://osf.io/cs6zt/?action=download
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by ‘ProtocolError(‘Connection aborted.’, OSError(0, ‘Error’))’: /cs6zt/?action=download
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by ‘ProtocolError(‘Connection aborted.’, OSError(0, ‘Error’))’: /cs6zt/?action=download
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by ‘ProtocolError(‘Connection aborted.’, OSError(0, ‘Error’))’: /cs6zt/?action=download
Link download error, trying next mirror (error was: HTTPSConnectionPool(host=‘osf.io’, port=443): Max retries exceeded with url: /cs6zt/?action=download (Caused by ProtocolError(‘Connection aborted.’, OSError(0, ‘Error’))))
Trying URL: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz
Link download error, trying next mirror (error was: 403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz)
Traceback (most recent call last):
File “/home/user/sct_dev/spinalcordtoolbox/scripts/sct_download_data.py”, line 165, in
main(sys.argv[1:])
File “/home/user/sct_dev/spinalcordtoolbox/scripts/sct_download_data.py”, line 158, in main
install_data(url, dest_folder, keep=arguments.k)
File “/home/user/sct_dev/spinalcordtoolbox/download.py”, line 145, in install_data
tmp_file = download_data(url)
File “/home/user/sct_dev/spinalcordtoolbox/download.py”, line 81, in download_data
raise Exception(‘Download error’, exceptions)
Exception: (‘Download error’, [ConnectionError(MaxRetryError(“HTTPSConnectionPool(host=‘osf.io’, port=443): Max retries exceeded with url: /cs6zt/?action=download (Caused by ProtocolError(‘Connection aborted.’, OSError(0, ‘Error’)))”,),), HTTPError(‘403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200801_sct_binaries_linux.tar.gz’,)])
```

At this point, given that they've had issues in multiple different contexts, this seems like more of a problem with the user's connection than anything else.

**Comment by joshuacwnewton** [comment]
The user [has explained](https://forum.spinalcordmri.org/t/installation-failed-in-ubuntu/610/6) that they live in Iran, and that they need to use a VPN to access many services. So, because the problem is limited to their connection specifically, I will be closing this issue and helping them directly on the forum.
