### ISSUE TITLE
New aggregate_slicewise.py check causes error in batch_processing.sh

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3202]
### Description

[One of the commands](https://github.com/neuropoly/spinalcordtoolbox/pull/3198/checks?check_run_id=1802242428) in `batch_processing.sh` failed the new check added in #3120. 

```python
--
Spinal Cord Toolbox (git-jn/2888-test-batch_processing.sh-881b504ab2ea7140375186c54e2e9b8bb3f5ab51*)

sct_extract_metric -i mtr.nii.gz -method map -o mtr_in_wm.csv -l 51 -vert 2:5
--

ValueError: Shape mismatch between vertfile [22] and metric [61]). Please verify that your vertfile has the same number of slices as your input image.
```

This is my mistake -- the new check is comparing the wrong dimension:

https://github.com/neuropoly/spinalcordtoolbox/blob/49ed68e029886661ad93546f5c0cd981839a6541/spinalcordtoolbox/aggregate_slicewise.py#L237

`[0]` does not refer to the proper slice index for 3D RPI data. Changing to `[-1]` will properly fetch slices from the last dimension of the `Metric()`. 

### Postmortem

This slipped through because tests in `test_aggregate_slicewise.py` use only 1D `Metric()` data.

https://github.com/neuropoly/spinalcordtoolbox/blob/49ed68e029886661ad93546f5c0cd981839a6541/unit_testing/test_aggregate_slicewise.py#L25-L32

Because of this, I falsely assumed all metrics were 1D, however `mtr.nii.gz` is a 3D metric. So, we should include a dummy 3D metric in there as well.

**Comment by jcohenadad** [comment]
wow, great catch-- thankfully we have better functional testing with the batch_processing now script 😅
