### ISSUE TITLE
new parser: doesn't manage correctly default value

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#321]
Example
----------
Nor
`parser.add_option("-s", "file", "segmentation", False, "spgr10_crop_seg.nii.gz", default_value='')`
neither
`parser.add_option("-s", "file", "segmentation", False, "spgr10_crop_seg.nii.gz", default_value=[])`
neither
`parser.add_option("-s", "file", "segmentation", False, "spgr10_crop_seg.nii.gz", default_value=0)`
work if we don't specifiy something in -s flag, although it is defined as an optional flag.

**Comment by benjamindeleener** [comment]
This is not really an issue actually, because you shouldn't be allowed to take a empty value for an input file... I would say that no default value should be available for "file", "image_nifti" and "directory" options
