### ISSUE TITLE
Maximum bandwidth reached for sct-data organization, dealing with binaries, data and models

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3214]
Due to the recent changes in GitHub's price plan and policies, I received an email mentioning that our BW limit was reached for the https://github.com/sct-data organization, which is a problem because if the download service is interrupted this could disrupt SCT installation and CI. 

As of today, this is our quota and usage:
![image](https://user-images.githubusercontent.com/2482071/107383252-cff1e880-6abe-11eb-9dc9-b598fb1bb4ac.png)

It looks like this quota resets every month. We should probably chip in some $$ in order to make sure our plan fits our requirements.

Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2959 https://github.com/neuropoly/spinalcordtoolbox/issues/2746 https://github.com/neuropoly/spinalcordtoolbox/issues/1526

**Comment by jcohenadad** [comment]
Looking at the plans, it seems like a $5/month would leave us stress-free:

![image](https://user-images.githubusercontent.com/2482071/107383862-6c1bef80-6abf-11eb-97d3-0785a50ce879.png)

We are currently using <2GB/month, and $5/month gives us 50GB/month.

**Comment by joshuacwnewton** [comment]
I did a quick search: https://github.com/search?q=org%3Asct-data+lfs&type=code

It seems like this issue is specific to the [`sct-data/exvivo-template`](https://github.com/sct-data/exvivo-template) repo, rather than SCT as a whole. Tagging @charleygros due to https://github.com/sct-data/exvivo-template/commit/ff82cc7ac317bc5380e9aa90e824c2bb34dfbcea.

**Comment by Drulex** [comment]
> I did a quick search: https://github.com/search?q=org%3Asct-data+lfs&type=code
> 
> It seems like this issue is specific to the [`sct-data/exvivo-template`](https://github.com/sct-data/exvivo-template) repo, rather than SCT as a whole. Tagging @charleygros due to [sct-data/exvivo-template@ff82cc7](https://github.com/sct-data/exvivo-template/commit/ff82cc7ac317bc5380e9aa90e824c2bb34dfbcea).

Indeed @joshuacwnewton is right. I guess that `lfs` was used to work around the 100MB file size limitation that `template.nii.gz` exceeds.
```console
$  git-lfs ls-files -s
f23c66e5bb - template/label_spinalsegments.nii.gz (2.2 MB)
b28c34c8c0 - template/map_greymatter.nii.gz (21 MB)
77b89929e8 - template/mask_spinalcord.nii.gz (3.2 MB)
f888bb15b6 - template/mask_spinalsegments.nii.gz (3.2 MB)
97e770fa59 - template/template.nii.gz (122 MB)

$  git-lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                                    
error: failed to fetch some objects from 'https://github.com/sct-data/exvivo-template.git/info/lfs'
```

It's unfortunate that Github charges for bandwidth, otherwise it would be a no-brainer to use `github lfs`, it seems well integrated.

**Comment by jcohenadad** [comment]
Thank you for catching this @joshuacwnewton ! I'll pay per use for this repository, if needed. The quota will be reset in 2 days so we can wait.

**Comment by jcohenadad** [comment]
Reopening because the issue came up again: https://github.com/sct-data/exvivo-template/issues/1

**Comment by joshuacwnewton** [comment]
@jcohenadad I notice that `ghsplit` was applied here: https://github.com/sct-data/exvivo-template/pull/2.

Can this issue be closed, then?

**Comment by jcohenadad** [comment]
ah! yes I think so. Thank you for the follow up 🙏
