### ISSUE TITLE
The size of the label is wrong when using -method map

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3216]
### Description

When using `sct_extract_metric -method map`, the column "Size [vox]" does not represent the correct size of the region.

This issue was reported by a user on [the forum](https://forum.spinalcordmri.org/t/measuring-involvement-of-corticospinal-tract/626/6?u=jcohenadad).
 
### Steps to Reproduce

```bash
sct_download_data -d sct_testing_data
cd sct_testing_data/mt
sct_extract_metric -i mtr.nii.gz -l 51,52 -perslice 0 -method map -o map.csv
sct_extract_metric -i mtr.nii.gz -l 51,52 -perslice 0 -method wa -o wa.csv
cat map.csv wa.csv
```

The result is:
**map.csv**
|Timestamp          |SCT Version                                        |Filename                                    |Slice (I->S)|VertLevel|Label         |Size [vox]        |MAP()             |STD()             |
|-------------------|---------------------------------------------------|--------------------------------------------|------------|---------|--------------|------------------|------------------|------------------|
|2021-02-10 11:57:30|git-master-92f004872deccb6ef1d1411751f8cffea14d5f51|/Users/julien/sct_testing_data/mt/mtr.nii.gz|0:4         |         |white matter  |331.1098567905528 |34.2645214894471  |11.457341402914249|
|2021-02-10 11:57:30|git-master-92f004872deccb6ef1d1411751f8cffea14d5f51|/Users/julien/sct_testing_data/mt/mtr.nii.gz|0:4         |         |dorsal columns|331.1098567905528 |35.2217919776565  |6.378461578742057 |

**wa.csv**
|Timestamp          |SCT Version                                        |Filename                                    |Slice (I->S)|VertLevel|Label         |Size [vox]        |WA()              |STD()             |
|-------------------|---------------------------------------------------|--------------------------------------------|------------|---------|--------------|------------------|------------------|------------------|
|2021-02-10 11:57:31|git-master-92f004872deccb6ef1d1411751f8cffea14d5f51|/Users/julien/sct_testing_data/mt/mtr.nii.gz|0:4         |         |white matter  |176.1532667399286 |32.640416229403456|11.457341402914249|
|2021-02-10 11:57:31|git-master-92f004872deccb6ef1d1411751f8cffea14d5f51|/Users/julien/sct_testing_data/mt/mtr.nii.gz|0:4         |         |dorsal columns|56.399586817478315|33.98187784327265 |6.378461578742057 |

As can be noticed, the WM and GM show the same wrong size for the "map" method (331.10),  whereas the size is correct for the "wa" method.

I suspect something fishy in [aggregate_slicewise.py](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/aggregate_slicewise.py)

**Comment by joshuacwnewton** [comment]
_(**Note:** This issue also affects `-method ml`, as it uses the same methods as `-method map` to generate its mask.)_

### Cause

The calculation for `Size [vox]` uses data from the `mask` Metric object:

https://github.com/neuropoly/spinalcordtoolbox/blob/74f068df9042e6cce8473e67f1a3fe60ddadac70/spinalcordtoolbox/aggregate_slicewise.py#L300-L303

For the affected methods, `mask` is generated this way:

https://github.com/neuropoly/spinalcordtoolbox/blob/74f068df9042e6cce8473e67f1a3fe60ddadac70/spinalcordtoolbox/aggregate_slicewise.py#L416-L421

Above, in line 420, `labels_sum` is modified to include extra labels. Its size goes from `(40, 40, 5, 1)` to `(40, 40, 5, 8)`. 

In other words, `(:, :, :, 0)` is the label we want, while `(:, :, :, 1:)` contains additional labels. So, the `Size [vox]` calculation is incorrectly including data from other labels, too.

### Verification

If we modify the slicegroup to only take the first label, the expected sizes will be output.

```diff
- mask_slicegroup = mask.data[..., slicegroup, :] 
+ mask_slicegroup = mask.data[..., slicegroup, 0] 
 agg_metric[slicegroup]['Label'] = mask.label 
 # Add volume fraction 
 agg_metric[slicegroup]['Size [vox]'] = np.sum(mask_slicegroup.flatten()) 
```

The thing is, I'm not certain that this change if valid for all usage of `aggregate_per_slice_or_level()`. 

Perhaps in some cases, we want `mask_slicegroup = mask.data[..., slicegroup, :]`. I am not intimately familiar with all of the use cases, so I will try and investigate more.

**Comment by jcohenadad** [comment]
@joshuacwnewton this is brilliant-- thank you so much for looking into this!!! 🙏
