### ISSUE TITLE
qform/sform mismatch check should add tolerance on precision

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3251]
### Description

I am getting a `ValueError: Image sform does not match qform` on an image, even though the qform/sform _seem_ to match:
```
qform_code	1
qto_xyz:1	-0.000000 -0.003254 -0.899995 36.800907 
qto_xyz:2	-0.932292 -0.000000 0.000000 214.219025 
qto_xyz:3	0.000000 -0.932286 0.003142 122.887390 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_code	1
sto_xyz:1	-0.000000 -0.003254 -0.899995 36.800907 
sto_xyz:2	-0.932292 0.000000 -0.000000 214.219025 
sto_xyz:3	-0.000000 -0.932286 0.003142 122.887390 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
```

So, I suspect it is a precision problem. 

[UPDATE]: Indeed, after checking the qform/sform with higher precision, directly from nibabel, I notice differences:
~~~
>>> nib.get_qform()
array([[-6.13306584e-08, -3.25428327e-03, -8.99994553e-01,
         3.68009071e+01],
       [-9.32291687e-01, -6.13306584e-08,  5.94133867e-08,
         2.14219025e+02],
       [ 6.15451159e-08, -9.32286007e-01,  3.14156514e-03,
         1.22887390e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
>>> nib.get_sform()
array([[-6.67520835e-13, -3.25425435e-03, -8.99994552e-01,     <-- here! 
         3.68009071e+01],
       [-9.32291687e-01,  1.91215821e-10, -0.00000000e+00,   <-- and here! 
         2.14219025e+02],
       [-1.91214891e-10, -9.32286024e-01,  3.14158620e-03,   <-- and here! 
         1.22887390e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
~~~

<details><summary>Syntax & Error</summary>

```console
sct_straighten_spinalcord -i t2_anonymized.nii -s t2_seg.nii 

--
Spinal Cord Toolbox (git-jca/3229-regtemplate-label-3834ce30b4df3cc0be861edf78c2f69acd693ac4)

sct_straighten_spinalcord -i t2_anonymized.nii -s t2_seg.nii
--

Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20210225183203.766637-straighten_spinalcord-ob15lea2)
Copy files to tmp folder...
Image /Users/julien/Desktop/20210225_Unable_to_warp_to_SC_template/t2_anonymized.nii has different qform and sform matrices. This can produce incorrect results. Consider setting the two matrices to be equal by running:
sct_image -i /Users/julien/Desktop/20210225_Unable_to_warp_to_SC_template/t2_anonymized.nii -set-sform-to-qform -o /Users/julien/Desktop/20210225_Unable_to_warp_to_SC_template/t2_anonymized_same-affine.nii.
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 279, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 262, in main
    fname_straight = sc_straight.straighten()
  File "/Users/julien/code/sct/spinalcordtoolbox/straightening.py", line 107, in straighten
    Image(fname_anat, check_sform=True).save(os.path.join(path_tmp, "data.nii"))
  File "/Users/julien/code/sct/spinalcordtoolbox/image.py", line 310, in __init__
    raise ValueError("Image sform does not match qform")
ValueError: Image sform does not match qform
```

</details>

### Steps to Reproduce

0. Install SCT 99f7f9413a7ce2536273b85611aaf8601a96c8da

1. Download these data: [Archive.zip](https://github.com/neuropoly/spinalcordtoolbox/files/6046323/Archive.zip)

2. Run: 
  ```
   sct_straighten_spinalcord -i t2_anonymized.nii -s t2_seg.nii 
   ```

### Notes

- I edited the data to put all voxels to zero for privacy reasons (because these data have been shared by a user).
- When running `sct_image -i t2.nii -set-sform-to-qform -o t2_qform.nii`, the issue goes away.

**Comment by joshuacwnewton** [comment]
The relevant check:

https://github.com/neuropoly/spinalcordtoolbox/blob/99f7f9413a7ce2536273b85611aaf8601a96c8da/spinalcordtoolbox/image.py#L243

[`np.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) works in the following way:

> If the following equation is element-wise True, then allclose returns True.
>```python
> absolute(a - b) <= (atol + rtol * absolute(b))  # Defaults: rtol=1e-05, atol=1e-08
>```

The default values do indeed seem too sensitive. Taking one difference you noticed, `3.14156514e-03` vs. `3.14158620e-03`, the absolute difference is 2.1e-08, which would trip up the `atol` of 1e-08.

**Comment by jcohenadad** [comment]
Thank you for looking into this-- Yes, I suggest we reduce the sensitivity. Even if they are not _perfectly_ matched, the consequences of mismatch at 10^-3 would be unnoticeable for the straightening algorithm (for which the check was introduced in the first place)
