### ISSUE TITLE
Dice coefficient of 1 if images have the same name in sct_dice_coefficient

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/spinalcordtoolbox#3256]
### Description

When running `sct_dice_coefficient` for two images with the same name, the dice coefficient is 1 and should not be. When I changed the name of one of the input images, the dice coefficient was of 0.927226.
Both images have the same name because the purpose for me was to compare manual segmentations performed by different people so both segmentations have the name `sub-1003396_T2w_seg-manual.nii.gz` in the case below.

### Steps to Reproduce

0. Install SCT 5.1.0

1. Run `sct_dice_coefficient`with same filename for flags `-i` and `-d`:
~~~
sct_dice_coefficient -i derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz -d results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz
~~~
2. Change name of one of the input files:
~~~
sct_dice_coefficient -i derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz -d results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg.nii.gz
~~~

**Expected behavior:** 
Output of step 2 (different image names):
```console
(base) sabeda@DESKTOP-JQ8A4UV:/mnt/c/Users/sb199/Projet3_data/ground_truth_manual_seg$ sct_dice_coefficient -i derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz -d results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg.nii.gz

--
Spinal Cord Toolbox (5.1.0)

sct_dice_coefficient -i derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz -d results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg.nii.gz
--

Creating temporary folder (/tmp/sct-20210228172716.009391-co4fmbgi)
cp derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz /tmp/sct-20210228172716.009391-co4fmbgi
cp results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg.nii.gz /tmp/sct-20210228172716.009391-co4fmbgi
File /tmp/sct-20210228172716.009391-co4fmbgi/sub-1003396_T2w_seg.nii.gz already exists. Will overwrite it.
/home/sabeda/sct_5.1.0/bin/isct_dice_coefficient sub-1003396_T2w_seg-manual.nii.gz sub-1003396_T2w_seg.nii.gz # in /tmp/sct-20210228172716.009391-co4fmbgi
rm -rf /tmp/sct-20210228172716.009391-co4fmbgi
3D Dice coefficient = 0.927226
```
**Actual behavior:** 
Ouput of step 1(same image name):

```console
(base) sabeda@DESKTOP-JQ8A4UV:/mnt/c/Users/sb199/Projet3_data/ground_truth_manual_seg$ sct_dice_coefficient -i derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz -d results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz

--
Spinal Cord Toolbox (5.1.0)

sct_dice_coefficient -i derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz -d results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz
--

Creating temporary folder (/tmp/sct-20210228172349.043346-4r8fpeu1)
cp derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz /tmp/sct-20210228172349.043346-4r8fpeu1
cp results_seg/bedard_sandrine/derivatives/labels/sub-1003396/anat/sub-1003396_T2w_seg-manual.nii.gz /tmp/sct-20210228172349.043346-4r8fpeu1
File /tmp/sct-20210228172349.043346-4r8fpeu1/sub-1003396_T2w_seg-manual.nii.gz already exists. Will overwrite it.
/home/sabeda/sct_5.1.0/bin/isct_dice_coefficient sub-1003396_T2w_seg-manual.nii.gz sub-1003396_T2w_seg-manual.nii.gz # in /tmp/sct-20210228172349.043346-4r8fpeu1
rm -rf /tmp/sct-20210228172349.043346-4r8fpeu1
3D Dice coefficient = 1
```
Input segmentation of `-i` :
![image](https://user-images.githubusercontent.com/71230552/109436028-7c065f80-79eb-11eb-8c30-5a5a8972fe28.png)
Input segmentation of `-d`:
![image](https://user-images.githubusercontent.com/71230552/109436054-a3f5c300-79eb-11eb-8784-44e146bd4686.png)

**Comment by jcohenadad** [comment]
@sandrinebedard I'm not sure I understand what the problem is. Under "Actual behavior: Ouput of step 1(same image name):", I would indeed expect to see a Dice of 1 (because the same segmentation is input in -i and -d).

**Comment by sandrinebedard** [comment]
@jcohenadad  It is actually not the same segmentation, sorry if that was not clear (the complete path is not the same). It would be in the case I performed the segmentation manually and an other person performed the same segmentation and we want to compare them. The input of `-i` and `-d` corresponds to the images I included for Actual behavior and for Expected behavior, only the name changed. Is that clearer?

**Comment by jcohenadad** [comment]
> The input of -i and -d corresponds to the images I included for Actual behavior and for Expected behavior, only the name changed. Is that clearer?

👍  cristal clear. Indeed, it's a pretty serious (and easy to fix) bug. Thank you for reporting it!
