### ISSUE TITLE
Better performance of deepseg seg_mice_gm-wm_dwi model if A-P orientation is wrong

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3279]
### Description

While working on a user's forum issue https://forum.spinalcordmri.org/t/registration-to-t1-ex-vivo-template-error/644/6, I noticed that `sct_deepseg`'s model `seg_mice_gm-wm_dwi` performs better if the image is (wrongly) flipped in the A-P direction. 

See below with the correct orientation, ie: we clearly see the dorsal horns pointing towards "A" whereas it should be "P":

https://user-images.githubusercontent.com/2482071/111055346-f64ecf00-8442-11eb-84af-a0a02f35bd18.mov

However, when fixing the wrong orientation of the image using the following function:
~~~
sct_image -i dwi_1500.nii.gz -setorient-data PSL -o dwi_1500_orient.nii.gz
~~~

Even though the image is now correctly oriented, the segmentation performance is largely decreased:

https://user-images.githubusercontent.com/2482071/111055362-1d0d0580-8443-11eb-892f-74a395698f0b.mov

Which makes me wonder if the model may have been trained on flipped data? (ie: A-P were mislabeled). @charleygros

**Comment by charleygros** [comment]
> Which makes me wonder if the model may have been trained on flipped data? (ie: A-P were mislabeled). @charleygros

That's.... possible!!
What I'm gonna do: (1) flip the dataset, (2) retrain a model on this flip data, (3) compare the results, (4) make a call. Keep you posted.

**Comment by jcohenadad** [comment]
i was about to suggest you wait for the data to be RPI (instead of LPI) but since the template is RL symmetric that shouldn’t change anything

**Comment by charleygros** [comment]
> 
> 
> i was about to suggest you wait for the data to be RPI (instead of LPI) but since the template is RL symmetric that shouldn’t change anything

Good point! But I think these data are not RL symmetric (while the template has been RL symmetrised).

**Comment by jcohenadad** [comment]
> > i was about to suggest you wait for the data to be RPI (instead of LPI) but since the template is RL symmetric that shouldn’t change anything
> 
> Good point! But I think these data are not RL symmetric (while the template has been RL symmetrised).

ah! indeed. But data augmentation probably includes RL flip?

**Comment by charleygros** [comment]
> data augmentation probably includes RL flip?

Yess!!
