### ISSUE TITLE
sct_orientation documentation indicates the default output fname as None instead of fname_in_new_orientation

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#328]
![screen shot 2015-04-17 at 2 11 49 pm](https://cloud.githubusercontent.com/assets/5857909/7208073/07239112-e50c-11e4-9978-8aa05b28a586.png)

Actually the fname out is 'inputed_fname_new_orientation.nii.gz'

**Comment by benjamindeleener** [comment]
Fixed in commit 4f493b8f3057aa3d3bea8d491a174820d3685992
