### ISSUE TITLE
Add entry to download exvivo template

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3280]
### Context

@charleygros created [this exvivo template](https://github.com/sct-data/exvivo-template), which is notably used by our collaborators in Australia (see [user forum](https://forum.spinalcordmri.org/t/registration-to-t1-ex-vivo-template-error/644/6)).

Currently there is no instructions as to how to download this template.

### Suggestion

Add an entry to `sct_download_data` to install this template.

Note: this template should ideally be installed under `$SCT_DIR/data/`. It would be cleaner IMHO.

I've added the label "priority" because currently the installation requires users to install https://github.com/Drulex/ghsplit/, which for some users is a complicated series of steps.

**Comment by charleygros** [comment]
> Note: this template should ideally be installed under `$SCT_DIR/data/`. It would be cleaner IMHO.

Do we want to force this?
Currently only the mandatory data are automatically installed in this folder (eg PAM50). But I don't think we want to install this template by default, do we?

**Comment by jcohenadad** [comment]
> Do we want to force this?

one pros: we control the version. E.g. of scenario:
- template v1 is installed by user
- we fix a bug and release v2
- we tell users to download v2
- user download v2 at an obscure location and forgets about it
- user still uses v1
- users has issues, posts on forum, tells us they are using v2, we have trouble debugging

> Currently only the mandatory data are automatically installed in this folder (eg PAM50). But I don't think we want to install this template by default, do we?

correct, we don't. The idea here is just to control the download location. Similarly than sct_deepseg models

**Comment by charleygros** [comment]
> one pros: we control the version. E.g. of scenario:

I agree, [issue ](https://github.com/neuropoly/spinalcordtoolbox/issues/3312)opened.
