### ISSUE TITLE
Wrong estimation of orientation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3281]
### Description

While working on this forum issue, I noticed a strange behaviour for the following dataset: [dwi_1500_orient_b0_mean_orient-wrong_gmseg_manual.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/6137029/dwi_1500_orient_b0_mean_orient-wrong_gmseg_manual.nii.gz)

The output of
```console
sct_image -i dwi_1500_orient_b0_mean_orient-wrong_gmseg_manual.nii.gz -getorient 
```
gives `RPI` orientation, while the output of:
```console
fslhd dwi_1500_orient_b0_mean_orient-wrong_gmseg_manual.nii.gz
```
gives `ASL`:
```
qform_xorient	Anterior-to-Posterior
qform_yorient	Superior-to-Inferior
qform_zorient	Left-to-Right
```

**Comment by jcohenadad** [comment]
A particularity of this file is that the qform_code=2, which is incorrect. Also see https://github.com/neuropoly/spinalcordtoolbox/issues/2454

**Comment by joshuacwnewton** [comment]
Ah! This issue might be the same as #3311. ("RPI" is reported both times by `-getorient`)

**Comment by jcohenadad** [comment]
> Ah! This issue might be the same as #3311. ("RPI" is reported both times by `-getorient`)

oops! yes you're right 😅 
closing because duplicate of https://github.com/neuropoly/spinalcordtoolbox/issues/3311
