### ISSUE TITLE
image.convert function is called incorrectly, causing error during registration

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3282]
A user on the forum is reporting an error: https://forum.spinalcordmri.org/t/register-template-to-mt1/654

The bug is from this line of code:

https://github.com/neuropoly/spinalcordtoolbox/blob/0b7be07b7e64a57a303824e85930fbceb8b890f0/spinalcordtoolbox/registration/register.py#L373

The usage of this function doesn't match its parameters:

https://github.com/neuropoly/spinalcordtoolbox/blob/0b7be07b7e64a57a303824e85930fbceb8b890f0/spinalcordtoolbox/image.py#L1341-L1348

I believe `image.convert` came about in #2871/#2812. I'll dig into that and find out what the correct usage should be.

**Comment by joshuacwnewton** [comment]
Ah, I see what happened. There were multiple functions named `convert` in SCT:

* `image.convert` 
* `sct_convert.convert`

When sct_image was refactored in #2812, the function `sct_convert.convert` was mistaken for `image.convert`.

**Comment by joshuacwnewton** [comment]
These two functions basically identical. Because scripts should be importing from API (`image.convert`) and not the CLI (`sct_convert.convert`), I'm going to remove `sct_convert.convert` and replace with `image.convert`, so that this mistake won't happen again in the future.

**Comment by Drulex** [comment]
Woops this would be my fault.

> The two functions are basically identical. sct_convert.convert simply adds file I/O to image.convert, which doesn't really justify a function.

The initial motivation to keep `sct_convert.convert()` was to maintain backwards compatibility while using the refactored `image.convert()` API internally until we are ready to break the interface.
