### ISSUE TITLE
Lintly fails for PRs from forks because GH disables write permissions for GITHUB_TOKEN

### ISSUE THREAD

**Issue by claragiroux** [neuropoly/spinalcordtoolbox#3286]
I'm having a git client error when running lint_job in PR #3275  

https://github.com/neuropoly/spinalcordtoolbox/runs/2114260881?check_suite_focus=true

Is it a permission issue or an issue in the PR?

```
Run flake8 | lintly --use-checks --fail-on new --exit-zero --no-post-status --commit-sha 7936f2f180930706eb20a64df5efbbbd509a7b8b
  flake8 | lintly --use-checks --fail-on new --exit-zero --no-post-status --commit-sha 7936f2f180930706eb20a64df5efbbbd509a7b8b
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
    LINTLY_API_KEY: ***
[...]
./documentation/source/conf.py:98:1: E265 block comment should start with '# '
./documentation/source/conf.py:177:1: W391 blank line at end of file

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/bin/lintly", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/lintly/cli.py", line 74, in main
    build.execute()
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/lintly/builds.py", line 82, in execute
    self.submit_to_pr(patch)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/lintly/builds.py", line 145, in submit_to_pr
    self.git_client.create_check_run(
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/lintly/backends/github.py", line 249, in create_check_run
    response = client.post(url, data, headers={'Accept': GITHUB_CHECKS_HEADER})
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/lintly/backends/github.py", line 81, in post
    return self._do_request('post', url, json.dumps(data), headers)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/lintly/backends/github.py", line 113, in _do_request
    raise GitClientError(response.content, status_code=response.status_code)
lintly.backends.errors.GitClientError: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"}'
Error: Process completed with exit code 1.
```

**Comment by joshuacwnewton** [comment]
Ah, I notice that PR is from a fork. That might have something to do with it.

**Comment by joshuacwnewton** [comment]
Ahh. I believe this is because I used the following token as an API key:

https://github.com/neuropoly/spinalcordtoolbox/blob/0b7be07b7e64a57a303824e85930fbceb8b890f0/.github/workflows/lint_code.yml#L20

Documentation on [`GITHUB_TOKEN`](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) shows that permissions change when working from a forked repo. So, this should be replaced by a personal access token that has the necessary permissions.

**Comment by joshuacwnewton** [comment]
Ack, that doesn't actually work. From [Using encrypted secrets in a workflow](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow):

> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

**Comment by joshuacwnewton** [comment]
Ah, wait. It turns out the documentation I linked is outdated. This [more recent post](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) from GitHub shows that you can pass secrets to Fork Pull Request Workflows.

**Comment by joshuacwnewton** [comment]
It looks like this is intentionally disabled for security reasons. There doesn't seem to be anything we can do here. See: https://github.community/t/token-permissions-for-forks-once-again/16468

> I understand why forked repos has the read-only permissions, but it is effectively blocks any linters, checkers and audit tools to be implemented as a Github Actions; for example, it’s disallowed to post any data to the Checks API, therefore, it is impossible to create a linter which will validate pull requests from the forked repositories.

We could switch to another linter, but we would have to lose out on annotations. Hrm...

**Comment by joshuacwnewton** [comment]
@claragiroux As an aside, linting isn't a hard requirement for PRs. So, even though it shows a failure, you can continue as normal if you'd like. :slightly_smiling_face: 

But, if you do want linting, someone would need to give you permissions to create branches in the `neuropoly/spinalcordtoolbox` repo, and then you would need to re-open a PR on a new branch. (For now, at least.)

**Comment by jcohenadad** [comment]
> someone would need to give you permissions to create branches

i've just added @claragiroux with write permission

**Comment by claragiroux** [comment]
Thanks for the help! It works now with permission and when I create a branch directly in the sct repo!
