### ISSUE TITLE
Metavar.int gives str instead of int

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3298]
### Description

While working on , I introduced a parameter which was supposed to be an int, but it ended up being treated as a str. I declared it in argparse with `metavar=Metavar.int`:

https://github.com/neuropoly/spinalcordtoolbox/blob/6d70ad82fbd9ba7961fc1ef7fbb7ebca70ac6fc7/spinalcordtoolbox/utils/shell.py#L191

In the future, we should fix this, because it introduces confusion for developers.

**UPDATE 2021-03-17 11:36:17:**  My bad, I should have added "type" there:
~~~
        metavar=Metavar.int,
        type=int,
~~~

I thought that only specifying metavar was sufficient...

**Comment by joshuacwnewton** [comment]
> UPDATE 2021-03-17 11:36:17: My bad, I should have added "type" there:
>
>        metavar=Metavar.int,
>        type=int,
>
> I thought that only specifying metavar was sufficient...

It's not the most straightforward, heh. :sweat_smile: 

I've added a note about this in the [Argparse page](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Argparse-usage-in-CLI-scripts#metavar-vs-type) of the internal dev docs.
