### ISSUE TITLE
Update `neuropoly/spinal-cord-toolbox` team with current active contributors

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3324]
Right now, the current [Spinal Cord Toolbox](https://github.com/orgs/neuropoly/teams/spinal-cord-toolbox) team doesn't have all of SCT's current devs. It also has people who haven't contributed in some time. So, it's not very useful to ping the team @neuropoly/spinal-cord-toolbox or request reviews from the team.

Setting this up has a handful of benefits. For example, it would make it easier for contributors to request reviews, especially external contributors who don't know the names of the people they should be requesting reviews from. And, we wouldn't have to ping individuals one by one (and risk forgetting someone).

Relevant links:
* https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams
* https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team (Has some interesting info about automated code review assignment, too.)

**Comment by joshuacwnewton** [comment]
I have learned a few things while trying to solve this problem:

* I can't edit the `neuropoly/spinal-cord-toolbox` team, because it requires permissions at the Neuropoly org level.
* However, I _can_ request to create a child team underneath `neuropoly/spinal-cord-toolbox`
* People who are a part of the parent team have edit access to child teams, so I don't need to bug people with org-level permissions. :tada: 
* This child team can then be used for requesting reviews

![Screenshot from 2021-04-30 11-43-28](https://user-images.githubusercontent.com/16181459/116720880-af914600-a9aa-11eb-9f4d-1cfc93b6a7f0.png)

Based on previous Slack discussions, this is my current understanding for people who are available (in some capacity) to review SCT PRs:

* @kousu 
* @Drulex 
* @ahill187 
* @jcohenadad 
* @joshuacwnewton 

Is there anyone I'm missing?

**Comment by joshuacwnewton** [comment]
Hrm, slight snag. While trying to add @jcohenadad to the new team, I see this:

<details>

![Screenshot from 2021-04-30 12-02-42](https://user-images.githubusercontent.com/16181459/116722213-211dc400-a9ac-11eb-9249-650abbf45aed.png)
</details>

This is a bit odd... Does Julien not already have access to these repos? And, why would adding Julien to a child team grant access?

Also, for @Drulex and @ahill187, I can't add them because they are not part of the Neuropoly org.

<details>

![Screenshot from 2021-04-30 12-05-00](https://user-images.githubusercontent.com/16181459/116722390-532f2600-a9ac-11eb-9f35-17484a1a93b6.png)
</details>

I'm not sure I understand the current state of permissions within the Neuropoly org anymore. :sweat_smile:

**Comment by alexfoias** [comment]
@joshuacwnewton hmmm maybe because @jcohenadad is the owner ?

**Comment by alexfoias** [comment]
I was able to add @jcohenadad to the new team

**Comment by alexfoias** [comment]
@joshuacwnewton I made you team maintener in the spinal-cord-toolbox team.  I think this way you can add other people by yourself.

**Comment by jcohenadad** [comment]
> Is there anyone I'm missing?

looks good so far-- depending on the project/code/scope we could also add students, eg @charleygros and also @sandrinebedard who is getting increasingly familiar with the codebase

**Comment by jcohenadad** [comment]
Also, is that a good moment to maybe consider moving sct to its own organization?

**Comment by joshuacwnewton** [comment]
> looks good so far-- depending on the project/code/scope we could also add students, eg @charleygros and also @sandrinebedard who is getting increasingly familiar with the codebase

Good point! It would definitely be good experience, too. 

The only tricky thing is @neuropoly/sct-reviewers is a sort of catch-all that can be used for all SCT PRs. If the students are more case-by-case basis reviewers, then it might be a bit noisy for them. 

> Also, is that a good moment to maybe consider moving sct to its [own organization](https://github.com/spinalcordtoolbox)?

Good point. I'll respond in https://github.com/neuropoly/spinalcordtoolbox/issues/3096. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
> If we move to the spinalcordtoolbox org, we could do something like @spinalcordtoolbox/developers and @spinalcordtoolbox/researchers. This way, reviews can be requested based on specific expertise.

On that note, I'm going to close this issue, as the main part of #3324 has been addressed.

Any future work can be handled as part of #3096, because an organization change would require remaking the teams anyway.
