### ISSUE TITLE
Write standalone script to calculate metrics for individual corticospinal tract labels

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3328]
A user on the forum [asked](https://forum.spinalcordmri.org/t/measure-data-for-corticospinal-tract/674):

> Is there a way to calculate metrics for medial 1/2 (blue) and lateral 1/2 (green) of the lateral corticospinal tracts separately -see figure for example?

Figure below:

![image](https://user-images.githubusercontent.com/16181459/113342095-09dfae00-92fc-11eb-959a-19dab95ed3bd.png)

**Comment by jcohenadad** [comment]
> Should an issue be created for this, or is it sufficient to provide a standalone script just for this user? 

it is sufficient to create a script. I have something super simple in mind:
- open PAM50/atlas/CST_label_right
- loop across Z
- get center of mass
- create a soft mask that goes through the center of mass:
  - oriented along Y
  - ones on the right, zeros on the left
  - at the interface: weight the line based on the X location of the centermass
- multiply the mask and its opposite with the CST_label_right
- do the same for CST_label_left
- save as four files
- edit info_label.txt
- zip the whole thing, upload on forum, and explain how to run sct_extract_metric with that

**Comment by joshuacwnewton** [comment]
Small update for accountability: I'm planning on working on this today. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
Here's what I've got so far, using the PAM50 template warped to our `sct_example_data` T2 image (using the steps from the course).

![lateral_cst_overlay](https://user-images.githubusercontent.com/16181459/114325951-90686c80-9b00-11eb-9ec9-8b4af0c1ea55.gif)

(The gif is 2 separate images, just to demonstrate the overlay between them.)

Once I've got the script cleaned up I'll share it + write an explanation for how to combine it with `sct_extract_metric`.

**Comment by jcohenadad** [comment]
Amazing @joshuacwnewton !!! it would be important to make it 4 different labels (sorry if this was not clear), ie: 
- right CST lateral
- right CST medial
- left CST lateral
- left CST medial

**Comment by joshuacwnewton** [comment]
Apologies for my unclear gif! It is 4 different labels, I just combined them in the FSLeyes view so I wouldn't have to make 2 gifs. :sweat_smile:

**Comment by jcohenadad** [comment]
> Apologies for my unclear gif! It is 4 different labels, I just combined them in the FSLeyes view so I wouldn't have to make 2 gifs. 😅

ah! cool, no worries. You know you can select other colors, right? (pink, etc.)

**Comment by joshuacwnewton** [comment]
> ah! cool, no worries. You know you can select other colors, right? (pink, etc.)

Yep! I just wanted to match the colours in the image provided by the user.

----

@jcohenadad Could you double-check that what I've created matches your expectations before I provide this to the user?

<details>
<summary> Source code for <code>split_labels.py</code> </summary>

```python
"""
A utility script for splitting a label image into lateral and medial halves using the center of mass of each slice.

Typical usage:
    python split_labels.py -dir label/atlas -i PAM50_atlas_04.nii.gz PAM50_atlas_05.nii.gz -label info_label.txt
"""

import sys
import math
import argparse

from spinalcordtoolbox.image import Image, zeros_like
from spinalcordtoolbox.utils import extract_fname
from spinalcordtoolbox import metadata

import numpy as np
from scipy.ndimage.measurements import center_of_mass


def split_labels(fname, root_dir):
    """Split label volume into medial and lateral halves using the center of mass of each slice."""
    im_in = Image(f"{root_dir}/{fname}").copy()

    orientation_old = im_in.orientation
    im_in.change_orientation("RPI")

    im_medial = zeros_like(im_in)
    im_lateral = zeros_like(im_in)

    for i in range(im_in.data.shape[-1]):
        slice_arr = im_in.data[..., i]
        if np.count_nonzero(slice_arr):  # Skip empty slices
            # Add 0.5 to center of mass to account for index-based geometry. Examples to demonstrate:
            #    1. If img=[0 1 1 0], COM is 1.5. To split the img, we want masks [1 1 0 0] + [0 0 1 1].
            #         So, what we're actually looking for is 2, so we can split it using img[:2] and img[2:]
            #    2. If img=[0 1 1 1 0], COM is 2. To split the img, we want masks [1 1 .5 0 0] + [0 0 .5 1 1].
            #         So, what we're actually looking for is 2.5, so the .5 can be used to weight the center index.
            #    3. If img=[0 1 1 2 0], COM is 2.25. To split the img, we want masks [1 1 .75 0 0] + [0 0 .25 1 1].
            #         So, what we're actually looking for is 2.75, to ensure center index is weighted to the right.
            x_ctr, _ = center_of_mass(slice_arr)
            x_ctr += 0.5

            # Get fractional and whole parts of center of mass
            x_frac, x_whole = math.modf(x_ctr)
            x_whole = int(x_whole)  # modf returns float (even for 'whole'), but int must be used for numpy indexing

            # Create lateral binary mask (e.g. [1 1 0 0 0])
            binary_mask_lateral = np.zeros_like(slice_arr)
            binary_mask_lateral[:x_whole, :] = 1.0

            # Create lateral soft mask (e.g. [1 1 .75 0 0]) by weighting the voxels at the interface
            soft_mask_lateral = binary_mask_lateral.copy()
            soft_mask_lateral[x_whole, :] = x_frac

            # Create medial soft mask (e.g. [0 0 .25 1 1]) by inverting lateral soft mask
            soft_mask_medial = np.ones_like(soft_mask_lateral) - soft_mask_lateral

            # Apply masks to get lateral/medial slices
            im_lateral.data[..., i] = soft_mask_lateral * slice_arr
            im_medial.data[..., i] = soft_mask_medial * slice_arr

    im_lateral.change_orientation(orientation_old)
    im_medial.change_orientation(orientation_old)

    path, file, ext = extract_fname(f"{root_dir}/{fname}")
    fname_lateral = f"{file}_lateral{ext}"
    fname_medial = f"{file}_medial{ext}"
    im_lateral.save(f"{path}/{fname_lateral}")
    im_medial.save(f"{path}/{fname_medial}")

    return fname_lateral, fname_medial


def edit_info_label(fname_label, fname_source, fname_lateral, fname_medial, root_dir):
    """Append entries for new lateral/medial labels to the end of the info_label.txt file."""
    label_file = metadata.InfoLabel()
    label_file.load(f"{root_dir}/{fname_label}", verify=False)
    labels = label_file._indiv_labels  # Just to have a shorter variable name for accessing the internal attribute

    for label in labels:
        if label[2] == fname_source:
            name_base = label[1]
            break
    else:
        raise ValueError(f"Input image file '{fname_source}' not in '{fname_label}'. Can't add lateral/medial entries.")

    labels.append((len(labels), f"{name_base} (lateral half)", fname_lateral))
    labels.append((len(labels), f"{name_base} (medial half)", fname_medial))

    label_file.save(f"{root_dir}/{fname_label}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("-dir", required=True,
                        help="Path to atlas directory where files are contained.")
    parser.add_argument("-i", nargs="+", required=True,
                        help="One or more filenames of label images to split.")
    parser.add_argument("-label", default="info_label.txt", required=False,
                        help="Filename of label file. (default: info_label.txt)")
    arguments = parser.parse_args(sys.argv[1:])

    for fname_in in arguments.i:
        fname_lateral, fname_medial = split_labels(fname_in, root_dir=arguments.dir)
        edit_info_label(arguments.label, fname_in, fname_lateral, fname_medial, root_dir=arguments.dir)
```

</details>

The usage would be something like:

```
$SCT_DIR/python/envs/venv_sct/bin/python split_labels.py -dir $SUBJECT_DIR/label/atlas -i PAM50_atlas_04.nii.gz PAM50_atlas_05.nii.gz -label info_label.txt
```

Finally, here is a zip containing the script as well as some sample files (before/after processing): [sample_results.zip](https://github.com/neuropoly/spinalcordtoolbox/files/6298441/sample_results.zip)

**Comment by jcohenadad** [comment]
Hey @joshuacwnewton i am currently testing your script. It is awesome! I tried running it on the PAM50 template directly. Few comments:

- The sum between the two medial/lateral labels is indeed equal to the value of the underlying label, so that's all good 👍 
  ![image](https://user-images.githubusercontent.com/2482071/114473055-79d61a00-9bc1-11eb-9d71-42d300a35ba7.png)

- the updated info_label file should add the entries under "# Combined labels", not under "# Keyword=IndivLabels". Why is that? because everything under "# Keyword=IndivLabels" is defined so that the sum of all labels inside a voxel in the spinal cord equals 1. This is a condition for Gaussian mixture models (methods maximum likelihood and maximum a posteriori), more info in the [SCT course](https://www.icloud.com/keynote/0th8lcatyVPkM_W14zpjynr5g#SCT%5FCourse%5F20200121) page 98 ("do not edit that part") as well as in usage of `sct_extract_metric` (under -method -wa). We should definitely add this info under https://spinalcordtoolbox.com/en/latest/overview/concepts/pam50.html#white-and-grey-matter-atlas-pam50-atlas!
  However, after writing this, I realized that it is _not_ possible to add these additional labels under "# Combined labels" because they are _de facto_ not combined labels. So, I see two possibilities:
  - Not create these composite label files under /atlas and instead create them locally. The user will then have to specify metric extraction using `-f ./PAM50_atlas_04_lateral.nii.gz`. 
  - Create them under /atlas (ie: source directory), replace PAM50_atlas_04.nii.gz and PAM50_atlas_05.nii.gz by each pair, and update info_label.txt to reflect the changes. This option is obviously more involved, so i would go for option 1.

**Comment by joshuacwnewton** [comment]
Thank you for taking the time to run `sct_extract_metric`, and my apologies for not having done that beforehand. :facepalm: 

> the updated info_label file should add the entries under "# Combined labels", not under "# Keyword=IndivLabels". Why is that? because everything under "# Keyword=IndivLabels" is defined so that the sum of all labels inside a voxel in the spinal cord equals 1. This is a condition for Gaussian mixture models (methods maximum likelihood and maximum a posteriori), more info in the SCT course page 98 ("do not edit that part") as well as in usage of sct_extract_metric (under -method -wa). We should definitely add this info under https://spinalcordtoolbox.com/en/latest/overview/concepts/pam50.html#white-and-grey-matter-atlas-pam50-atlas.

Thank you for sharing this extra context. I was definitely misunderstanding how `info_label.txt` should be used.

I also agree that it would be good to be clearer about this in the documentation. (If my naive edits to `info_label.txt` caused `sct_extract_metric` to fail, then I can imagine a user running into the same issue if they were to supply their own `info_label.txt` files.)

> Not create these composite label files under /atlas and instead create them locally. The user will then have to specify metric extraction using `-f ./PAM50_atlas_04_lateral.nii.gz`.

I like this idea. It would be simpler to explain this to the user, too.

**Comment by joshuacwnewton** [comment]
I have shared the script with the user [on the forum](https://forum.spinalcordmri.org/t/measure-data-for-corticospinal-tract/674/7?u=joshuacwnewton) (after modifying it to remove the `info_label.txt` parts). I will close this issue once the user responds.

**Comment by joshuacwnewton** [comment]
Closing as they have tested out the script and confirmed that it meets their needs.
