### ISSUE TITLE
sct_change_image_type doesn't work with type float16

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#333]
![screen shot 2015-04-17 at 4 40 50 pm](https://cloud.githubusercontent.com/assets/5857909/7210530/8d16995e-e520-11e4-9c94-30cc4bffed40.png)

**Comment by tanguymagnan** [comment]
It seems that nibabel nifti1 header does not support float16 type as numpy does... Not a code problem
