### ISSUE TITLE
Improve how the SCT project publicly markets itself - Testimonials

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3346]
Right now... 

* Our [README.md](https://github.com/neuropoly/spinalcordtoolbox/blob/master/README.md) and [main spinalcordtoolbox.com pages](https://spinalcordtoolbox.com/en/stable/) are quite bare. 
* The ["Introduction"](https://spinalcordtoolbox.com/en/stable/overview/introduction.html) and ["Overview"](https://spinalcordtoolbox.com/en/stable/overview/overview.html) material from the docs cover some of SCT's usefulness, but they're side pages, rather than front and centre.
* The closest thing we have to user testimonials is [a list of citations](https://spinalcordtoolbox.com/en/stable/overview/references.html#applications) at the bottom of the References page. These citations are tucked away and possibly easy to miss, despite being important accomplishments for SCT.

We could be doing a better job at communicating SCT's usefulness, it's value, and the ways it's been positively received by users. Here is some inspiration from other Python projects: 

* `scikit-learn`'s testimonials page: https://scikit-learn.org/stable/testimonials/testimonials.html.
* Some other testimonials pages include the ones from [`hypothesis`](https://hypothesis.readthedocs.io/en/latest/endorsements.html) and [`emcee`](https://emcee.readthedocs.io/en/stable/testimonials/).
* `dask`'s "Stories" page, showing real-world use-cases: https://stories.dask.org/en/latest/.

**Comment by jcohenadad** [comment]
Related to this, here are old SCT testimonials (when SCT was on sourceforge): https://sourceforge.net/projects/spinalcordtoolbox/reviews

**Comment by jcohenadad** [comment]
A suggestion to gather testimonials continuously is to have a google form available. Here is a prototype --> https://forms.gle/Cfos8bRJTtRNxeMt8

Feedback welcome

**Comment by joshuacwnewton** [comment]
> A suggestion to gather testimonials continuously is to have a google form available. Here is a prototype:
> point_right ‎ https://forms.gle/Cfos8bRJTtRNxeMt8
> 
> Feedback welcome.

This is nice! Short, but covers the important points. Thanks for taking the initiative here. :smile: 

I'm wondering, though: Do we want 1 form for both testimonials and feedback? Or do we want 2 separate forms, with each being shorter/more focused. (My guess is the shorter a form is, the better chance we have of someone fully completing it.)

1. **Testimonial form:** Would only really need the name/affiliation/testimonial boxes, and wouldn't necessarily need the survey-style questions. 
2. **Feedback form:** This would exclude the  "Your testimonial will appear on the website: https://spinalcordtoolbox.com/" part, which I think could scare people away who otherwise have valuable feedback.

**Comment by jcohenadad** [comment]
> Or do we want 2 separate forms, with each being even shorter/more focused

I know how horribly busy our users are-- if they see we are asking for two forms, they will be scared and only click on one of them (or none).  I made it very explicit that the feedback will not appear on the website.

**Comment by jcohenadad** [comment]
I've also added the country (found a way to get country dropdown thanks to [this link](‎https://www.howtodigitalstuff.com/import-multiple-answers-in-google-form/)), so on each testimonial we can add a little flag next to the affiliation. I think it will look cool and will show country diversity.

**Comment by kousu** [comment]
I'd rearrange the form to:

- Name
- Degree
- MD
- Affiliation
- Country
- OS
- Rating
- Testimonial
- Suggestions

That seems like it should warm people up more.

I like using the emojis to guide the eye to the topics, though I could see people thinking they're unprofessional.

And how about this rewording?

```diff
-❤️‎ ‎ ‎ Enter your testimonial here. For example, you could say why you like
-the software (performance, features, documentation, etc.), its support team,
-the course material, what you use SCT for, what kind of studies you are conducting, etc. *
+What you use SCT for? Do you have any in-progress studies where SCT has aided?
+Is it [well documented](https://spinalcordtoolbox.com/en/stable/user_section/getting-started.html),
+or do you get useful help from the [community forum](https://forum.spinalcordmri.org/c/sct/8),
+or does it integrate easily into your analyses? What else do you like about it?
+
+ Your testimonial may appear on the website: https://spinalcordtoolbox.com/ 
```

**Comment by jcohenadad** [comment]
Thank you so much for your suggestions @kousu -- i've implemented them (no hyperlinks though-- not possible in gform)

**Comment by jcohenadad** [comment]
An issue I am having with the [current RTD template](https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#topics-sidebars-and-rubrics) is that the block quotes are a bit boring:
![image](https://user-images.githubusercontent.com/2482071/115469208-36ebf600-a202-11eb-853b-693e84a2241e.png)

e.g. they do not look as nice as [this one](https://pythonhosted.org/sphinxjp.themes.basicstrap/sample.html#block-quotes), where a vertical bar is added:
![image](https://user-images.githubusercontent.com/2482071/115469189-2b98ca80-a202-11eb-9644-7df4faacd496.png)

**Comment by kousu** [comment]
grabbed this CSS out of that sample page:

```
blockquote {
        border-left: 5px solid #eee;
}
```

We can add this to our theme in here: https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/_static/css/custom.css

**Comment by jcohenadad** [comment]
> grabbed this CSS out of that sample page:

nice find @kousu ! I'll try it and see if it looks nicer than the admonition
