### ISSUE TITLE
crop template space before registration

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#343]

**Comment by jcohenadad** [comment]
First investigations: using the same parameters for registration and when cropping the template at levels that correspond to the top-bottom edges of the input T2 image, the process is faster (214s --> 180s) but the registration does not give same results:

![output_nwqrgp](https://cloud.githubusercontent.com/assets/2482071/7401019/c70cb6e4-ee8e-11e4-8fd8-a7df4ba315b6.gif)

**Comment by jcohenadad** [comment]
now using both cropping and subsampling along z (214s --> 134s). Even worse:

![t2_cropsub_orig](https://cloud.githubusercontent.com/assets/2482071/7401728/690b3498-ee94-11e4-96d1-e4cfab9023fb.gif)

**Comment by jcohenadad** [comment]
With crop and 4x subsampling (214s --> 100s):

![croped_subx4](https://cloud.githubusercontent.com/assets/2482071/7402125/747fb1a2-ee97-11e4-9929-aad45ee995c3.gif)

**Comment by jcohenadad** [comment]
okay, maybe that's the cause of the problem:

![screen shot 2015-04-29 at 17 49 10](https://cloud.githubusercontent.com/assets/2482071/7402215/1cd8535e-ee98-11e4-978d-e25f74193e2a.png)

**Comment by jcohenadad** [comment]
now solved with commit #09aeb68b30c8be806a20d1d918b28c40bce662d6

**Comment by jcohenadad** [comment]
other issue: the first step (slicereg) seems to shrink the cord:

![screen shot 2015-04-29 at 19 00 55](https://cloud.githubusercontent.com/assets/2482071/7403294/43632238-eea2-11e4-8b75-7f19a593d97c.png)

**Comment by jcohenadad** [comment]
OK! with this fix, results are now much better:

![croped_subx4_fixed](https://cloud.githubusercontent.com/assets/2482071/7403649/d18ddf46-eea5-11e4-8d67-1af0536ba429.gif)

**Comment by jcohenadad** [comment]
fixed in #78ed516ffca6d2c28aec25c65411bc5311e8c9dd
