### ISSUE TITLE
sct_crop_image does not advice the good output file to view

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#346]
sct_crop_image -i *_t2_crop_seg_mod.nii.gz -o t2_crop_seg_mod_crop.nii.gz -dim 2 -start 0 -end 495 -b 0
Cropping the following region:
Dimension 0: 0 51
Dimension 1: 0 385
Dimension 2: 0 495
[3]+  Done                    fslview *_t2_crop.nii.gz *_t2_crop_seg_mod.nii.gz -l Red -b 0,1 -t 0.7

**Comment by benjamindeleener** [comment]
not an issue. sct_crop_image does not display "fslview ...". It should.
