### ISSUE TITLE
Propseg fail for t2star image when using -init-mask or -init-centerline

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#351]
Gives a black image as output ... 
Data are in ``/Volumes/folder_shared/greymattersegmentation/data_testing/original_data/d_sp_pain_pilot/pilot2/t2star ``

**Comment by SaraDupont** [comment]
Using propseg with -init-mask on a MT image works fine (same place, pilot8/MTC1) and not for a T2*

**Comment by SaraDupont** [comment]
The T2* images were 4D (I did only dcm2nii), worked after doing an average multiecho

**Comment by benjamindeleener** [comment]
I close this issue because sct_propseg does not work on 4D data.
`sct_propseg` detects now if the input image is not 3D and stops if it is the case.
