### ISSUE TITLE
compute APW and LRW

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#356]
see http://www.ncbi.nlm.nih.gov/pubmed/20697420

**Comment by jcohenadad** [comment]
two possibilities:
* fit ellipse in Python and compute APW and LRW
* fit a VTK mesh (more complicated)

**Comment by tanguyduval** [comment]
Better solution:
Use the aera and the perimeter of the segmentation at each slice --> then
compute the eccentricity. Algo here:
http://stackoverflow.com/questions/1532168/what-are-the-second-moments-of-a-region

Then compute
(i) the two diameters of the ellipse a and b:
http://en.wikipedia.org/wiki/Eccentricity_(mathematics)
(ii) and the aera of the ellipse.

Two equations and two unknown parameters (a and b).. cqfd

2015-05-07 12:40 GMT-04:00 Julien Cohen-Adad <notifications@github.com>:

**Comment by benjamindeleener** [comment]
`sct_process_segmentation` has now the `-p shape` option, including the computation of AP and RL diameter of the cord
