### ISSUE TITLE
sct_align_vertebrae do not assign correctly the plans when levelling at same level

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#357]
![screenshot 2015-05-04 16 42 52](https://cloud.githubusercontent.com/assets/11425966/7462099/11bc207a-f27d-11e4-86ad-f1eb993d3bbe.png)

Red plans = template plans
Blue Plans = subject plans
Green plans = moved plan 

The antRegistration does not seem to assign plans by their values.

**Comment by jcohenadad** [comment]
function is not used anymore
