### ISSUE TITLE
sct_straighten_spinalcord: change of value gapxy can produce artefact

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#358]
data: T2 de errsm_16 (montreal_criugm)
gapxy = 50

Command: "sct_straighten_spinalcord -i data_RPI_crop_denoised.nii.gz -c seg_and_labels.nii.gz -a nurbs"

![screenshot 2015-05-04 17 47 43](https://cloud.githubusercontent.com/assets/11425966/7464021/c6874e6c-f28c-11e4-874e-6b9140b41709.png)
![screenshot 2015-05-04 17 48 35](https://cloud.githubusercontent.com/assets/11425966/7464022/c76ef8ac-f28c-11e4-80fb-db596399597e.png)

**Comment by benjamindeleener** [comment]
This issue is not longer relevant. Now with the use of labels all along the spinal cord, increasing the parameter gapxy does not produces artefacts.
