### ISSUE TITLE
test_all should check if the testing data exist or not

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#361]
When no testing data were download before, test_all just fails and doesn't say why. It should check if the testing data folder exists and suggest to use flag -d 1 if not. (works properly with -d 1)

FAIL:
![screen shot 2015-05-08 at 12 27 42 pm](https://cloud.githubusercontent.com/assets/5857909/7540725/db89a578-f57d-11e4-82ce-b5aa924ff791.png)

Testing folder was containing :
![screen shot 2015-05-08 at 12 27 55 pm](https://cloud.githubusercontent.com/assets/5857909/7540751/0d410d22-f57e-11e4-8fc1-e164e0c2fc5b.png)

Using -d 1 :
![screen shot 2015-05-08 at 12 28 13 pm](https://cloud.githubusercontent.com/assets/5857909/7540777/28f0e65a-f57e-11e4-98f6-8f22d43adc17.png)

**Comment by benjamindeleener** [comment]
Fixed in cf789565e037d190134829cfa4c87a2a7f1b646b
