### ISSUE TITLE
IndexError: index -6 is out of bounds for axis 0 with size 5

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#363]
Issue happens with nz and pz are small.

See https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/d3624a4a/

**Comment by tanguymagnan** [comment]
The window size is set to 80 which is too big in this case. The window size should be put as an argument so that the user can modify it if needed.

**Comment by jcohenadad** [comment]
yup! that's exactly it-- however the user should never see a bug-- that's our job to make it work in every case. 

i work on it now...

**Comment by jcohenadad** [comment]
actually that's not the pb-- there is a bug in the indexing of the padding window l.529 in msct_smooth
