### ISSUE TITLE
sct_register_to_template should allow to change the parameters of sct_straighten_spinalcord

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#364]

**Comment by tanguymagnan** [comment]
J'ai regardé et en effet le problème est du au fait que l'on fixe la taille de la fenêtre dans sct_straighten_spinalcord et qu'on ne peut pas la changer depuis sct_register_multimodal.

Il faudrait pouvoir passer l'argument ou bien l'ajuster en fonction de la taille du signal à smoother

**Comment by benjamindeleener** [comment]
Done: `-param-straighten <str>      Parameters for straightening (see sct_straighten_spinalcord).`
