### ISSUE TITLE
when specifying "-o" file name is not correct

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#374]
syntax:
sct_process_segmentation -i centerline_T2_mask_cyl_7.nii.gz -p centerline -o test_centerline.nii.gz

**Comment by jcohenadad** [comment]
this issue needs to be addressed with the new parser. I.e., making sure the output path and file are correct, exist, etc.

**Comment by jcohenadad** [comment]
we now use ofolder
