### ISSUE TITLE
sct_register_multimodal: algo rigid doesn't work on certain OS

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#379]
Same command, same data (/Volumes/slevy-4/data/criugm/d_sp_pain_pilot7/mtv_scan)

OS X 10.8.2 (pass)
***********
pass:/Volumes/slevy-4/data/criugm/d_sp_pain_pilot7/mtv_scan $ sct_register_multimodal -i spgr20crop.nii.gz -d spgr10crop.nii.gz -o spgr20to10.nii.gz -p step=1,type=im,algo=slicereg,metric=MeanSquares,gradStep=0.6,iter=15:step=2,type=im,algo=rigid,metric=MeanSquares
Check file existence...
  OK: spgr20crop.nii.gz
Check file existence...
  OK: spgr10crop.nii.gz

Input parameters:
  Source .............. spgr20crop.nii.gz
  Destination ......... spgr10crop.nii.gz
  Mask ................ 
  Output name ......... spgr20to10.nii.gz
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...

Check if destination data is RPI...

Create temporary folder...
mkdir tmp.150525164122

Copy files...
isct_c3d spgr20crop.nii.gz -o tmp.150525164122/src.nii
isct_c3d spgr10crop.nii.gz -o tmp.150525164122/dest.nii

Estimate transformation for step #0...
isct_antsRegistration --dimensionality 3 --transform syn[0.5,3,0] --metric MI[dest.nii,src.nii,1,32] --convergence 0 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output [step0,src.nii_regStep0.nii] --interpolation BSpline[3] 

Estimate transformation for step #1...
sct_apply_transfo -i src.nii -d dest.nii -w warp_forward_0.nii.gz -o src_reg.nii -x linear
export FSLOUTPUTTYPE=NIFTI; fslmaths src_reg.nii -thr 0.1 src_reg_th.nii
export FSLOUTPUTTYPE=NIFTI; fslmaths dest.nii -thr 0.1 dest_th.nii
sct_crop_image -i src_reg_th.nii -dim 2 -bmax -o tmp.nii
sct_crop_image -i dest_th.nii -dim 2 -bmax -o tmp.nii
sct_crop_image -i src_reg.nii -o src_reg_crop.nii -dim 2 -start 0 -end 13
sct_crop_image -i dest.nii -o dest_crop.nii -dim 2 -start 0 -end 13
isct_antsSliceRegularizedRegistration -t Translation[0.5] -m MeanSquares[dest_crop.nii,src_reg_crop.nii,1,4,Regular,0.2] -p 3 -i 15 -f 1 -s 0 -v 1 -o [step1,src_reg_crop.nii_regStep1.nii] 

Estimate transformation for step #2...
sct_apply_transfo -i src.nii -d dest.nii -w warp_forward_0.nii.gz,warp_forward_1.nii.gz -o src_reg.nii -x linear
isct_c3d dest.nii -pad 0x0x5vox 0x0x5vox 0 -o dest_pad.nii
isct_antsRegistration --dimensionality 3 --transform rigid[0.5] --metric MeanSquares[dest_pad.nii,src_reg.nii,1,4] --convergence 10 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output [step2,src_reg.nii_regStep2.nii] --interpolation BSpline[3] 
All_Command_lines_OK
Using double precision for computations.
number of levels = 1
fixed image: dest_pad.nii
moving image: src_reg.nii
Dimension = 3
Number of stages = 1
Use Histogram Matching false
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
Image metric = MeanSquares
Fixed image = Image (0x7fcbc901bd90)
RTTI typeinfo:   itk::Image<double, 3u>
Reference Count: 2
Modified Time: 604
Debug: Off
Object Name:
Observers:
none
Source: (none)
Source output name: (none)
Release Data: Off
Data Released: False
Global Release Data: Off
PipelineMTime: 0
UpdateMTime: 426
RealTimeStamp: 0 seconds
LargestPossibleRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [39, 40, 24]
BufferedRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [39, 40, 24]
RequestedRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [39, 40, 24]
Spacing: [0.911458, 0.911458, 5]
Origin: [-26.5733, 30.5851, -32.5206]
Direction:
0.993718 5.88326e-08 0.111916
0.0277402 -0.968794 -0.246309
-0.108423 -0.247866 0.962708

IndexToPointMatrix:
0.905732 5.36235e-08 0.559579
0.025284 -0.883016 -1.23155
-0.0988234 -0.22592 4.81354

PointToIndexMatrix:
1.09025 0.030435 -0.118956
6.41287e-08 -1.06291 -0.271945
0.0223832 -0.0492618 0.192542

Inverse Direction:
0.993718 0.0277402 -0.108423
5.84507e-08 -0.968794 -0.247866
0.111916 -0.246309 0.962708

PixelContainer:
ImportImageContainer (0x7fcbc901bc80)
RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
Reference Count: 1
Modified Time: 423
Debug: Off
Object Name:
Observers:
none
Pointer: 0x10c130000
Container manages memory: true
Size: 37440
Capacity: 37440

Moving image = Image (0x7fcbc901c1a0)
RTTI typeinfo:   itk::Image<double, 3u>
Reference Count: 2
Modified Time: 605
Debug: Off
Object Name:
Observers:
none
Source: (none)
Source output name: (none)
Release Data: Off
Data Released: False
Global Release Data: Off
PipelineMTime: 0
UpdateMTime: 602
RealTimeStamp: 0 seconds
LargestPossibleRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [39, 40, 14]
BufferedRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [39, 40, 14]
RequestedRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [39, 40, 14]
Spacing: [0.911458, 0.911458, 5]
Origin: [-23.7754, 24.4274, -8.45287]
Direction:
0.993718 5.88326e-08 0.111916
0.0277402 -0.968794 -0.246309
-0.108423 -0.247866 0.962708

IndexToPointMatrix:
0.905732 5.36235e-08 0.559579
0.025284 -0.883016 -1.23155
-0.0988234 -0.22592 4.81354

PointToIndexMatrix:
1.09025 0.030435 -0.118956
6.41287e-08 -1.06291 -0.271945
0.0223832 -0.0492618 0.192542

Inverse Direction:
0.993718 0.0277402 -0.108423
5.84507e-08 -0.968794 -0.247866
0.111916 -0.246309 0.962708

PixelContainer:
ImportImageContainer (0x7fcbc901c080)
RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
Reference Count: 1
Modified Time: 599
Debug: Off
Object Name:
Observers:
none
Pointer: 0x10c1c5000
Container manages memory: true
Size: 21840
Capacity: 21840

Weighting = 1
Sampling strategy = none
Number of bins = 32
Radius = 4
Sampling percentage  = 1
Transform = Rigid
Gradient step = 0.5
Update field sigma (voxel space) = 0
Total field sigma (voxel space) = 0
Update field time sigma = 0
Total field time sigma  = 0
Number of time indices = 0
Number of time point samples = 0
Registration using 1 total stages.

Stage 0
iterations = 10
convergence threshold = 1e-06
convergence window size = 10
number of levels = 1
Shrink factors (level 1 out of 1): [1, 1, 1]
smoothing sigmas per level: [0]
using the MeanSquares metric (weight = 1)
Using default NONE metricSamplingStrategy

*** Running rigid registration ***

dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
Referenced from: /Users/slevy_local/spinalcordtoolbox/bin/osx/isct_antsRegistration
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___sincos_stret
Referenced from: /Users/slevy_local/spinalcordtoolbox/bin/osx/isct_antsRegistration
Expected in: /usr/lib/libSystem.B.dylib

**********
OS X 10.9.5 (tatum)
**********

tatum:~/mtv_scan $ sct_register_multimodal -i spgr20crop.nii.gz -d spgr10crop.nii.gz -o spgr20to10.nii.gz -p step=1,type=im,algo=slicereg,metric=MeanSquares,gradStep=0.6,iter=15:step=2,type=im,algo=rigid,metric=MeanSquares

Check file existence...

  OK: spgr20crop.nii.gz

Check file existence...

  OK: spgr10crop.nii.gz

Input parameters:

  Source .............. spgr20crop.nii.gz

  Destination ......... spgr10crop.nii.gz

  Mask ................ 

  Output name ......... spgr20to10.nii.gz

  Remove temp files ... 1

  Verbose ............. 1

Check if input data are 3D...

Check if destination data is RPI...

Create temporary folder...

mkdir tmp.150525164824

Copy files...

isct_c3d spgr20crop.nii.gz -o tmp.150525164824/src.nii

isct_c3d spgr10crop.nii.gz -o tmp.150525164824/dest.nii

Estimate transformation for step #0...

isct_antsRegistration --dimensionality 3 --transform syn[0.5,3,0] --metric MI[dest.nii,src.nii,1,32] --convergence 0 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output [step0,src.nii_regStep0.nii] --interpolation BSpline[3] 

Estimate transformation for step #1...

sct_apply_transfo -i src.nii -d dest.nii -w warp_forward_0.nii.gz -o src_reg.nii -x linear

export FSLOUTPUTTYPE=NIFTI; fslmaths src_reg.nii -thr 0.1 src_reg_th.nii

export FSLOUTPUTTYPE=NIFTI; fslmaths dest.nii -thr 0.1 dest_th.nii

sct_crop_image -i src_reg_th.nii -dim 2 -bmax -o tmp.nii

sct_crop_image -i dest_th.nii -dim 2 -bmax -o tmp.nii

sct_crop_image -i src_reg.nii -o src_reg_crop.nii -dim 2 -start 0 -end 13

sct_crop_image -i dest.nii -o dest_crop.nii -dim 2 -start 0 -end 13

isct_antsSliceRegularizedRegistration -t Translation[0.5] -m MeanSquares[dest_crop.nii,src_reg_crop.nii,1,4,Regular,0.2] -p 3 -i 15 -f 1 -s 0 -v 1 -o [step1,src_reg_crop.nii_regStep1.nii] 

Estimate transformation for step #2...

sct_apply_transfo -i src.nii -d dest.nii -w warp_forward_0.nii.gz,warp_forward_1.nii.gz -o src_reg.nii -x linear

isct_c3d dest.nii -pad 0x0x5vox 0x0x5vox 0 -o dest_pad.nii

isct_antsRegistration --dimensionality 3 --transform rigid[0.5] --metric MeanSquares[dest_pad.nii,src_reg.nii,1,4] --convergence 10 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output [step2,src_reg.nii_regStep2.nii] --interpolation BSpline[3] 

Concatenate transformations...

sct_concat_transfo -w warp_forward_0.nii.gz,warp_forward_1.nii.gz,warp_forward_2.mat -d dest.nii -o warp_src2dest.nii.gz

sct_concat_transfo -w -warp_forward_2.mat,warp_inverse_1.nii.gz,warp_inverse_0.nii.gz -d dest.nii -o warp_dest2src.nii.gz

Apply transfo source --> dest...

sct_apply_transfo -i src.nii -o src_reg.nii -d dest.nii -w warp_src2dest.nii.gz -x linear

Apply transfo dest --> source...

sct_apply_transfo -i dest.nii -o dest_reg.nii -d src.nii -w warp_dest2src.nii.gz -x linear

Generate output files...

  WARNING: File spgr20to10.nii.gz already exists. Deleting it...

  File created: spgr20to10.nii.gz

  File created: warp_spgr20crop2spgr10crop.nii.gz

  File created: spgr10crop_reg.nii.gz

  File created: warp_spgr10crop2spgr20crop.nii.gz

Remove temporary files...

rm -rf tmp.150525164824

Finished! Elapsed time: 4s

To view results, type:

fslview spgr10crop.nii.gz spgr20to10.nii.gz &

fslview spgr20crop.nii.gz spgr10crop_reg.nii.gz &

**Comment by jcohenadad** [comment]
are you sure it's OS-related?  did you try on other stations? with other data?
maybe it's an over-writing file issue

**Comment by slevyrosetti** [comment]
First, it is not a problem of memory because we tried splitting into 2D slices and applying ANTS on each slice individually: the error remains the same (see below).

Command
*************
isct_antsRegistration --dimensionality 2 --transform Rigid[0.6] --metric MeanSquares[dest_z0013.nii,src_reg_z0013.nii,1,4] --convergence 15 --shrink-factors 1 --smoothing-sigmas 0mm --output [transform_0013] --interpolation BSpline[3]

Output
********
All_Command_lines_OK
Using double precision for computations.
  number of levels = 1
  fixed image: dest_z0013.nii
  moving image: src_reg_z0013.nii
Dimension = 2
Number of stages = 1
Use Histogram Matching false
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
   Image metric = MeanSquares
     Fixed image = Image (0x7ff0eb01ba40)
  RTTI typeinfo:   itk::Image<double, 2u>
  Reference Count: 2
  Modified Time: 608
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 426
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [39, 40]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [39, 40]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [39, 40]
  Spacing: [0.911458, 0.911458]
  Origin: [-16.5009, 8.41727]
  Direction: 
0.999611 6.07277e-08
0.0279047 -1

  IndexToPointMatrix: 
0.911103 5.53507e-08
0.025434 -0.911458

  PointToIndexMatrix: 
1.09757 6.66529e-08
0.0306274 -1.09714

  Inverse Direction: 
1.00039 6.07513e-08
0.0279156 -1

  PixelContainer: 
    ImportImageContainer (0x7ff0eb01b930)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 423
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7ff0ea839e00
      Container manages memory: true
      Size: 1560
      Capacity: 1560

     Moving image = Image (0x7ff0eb01bd70)
  RTTI typeinfo:   itk::Image<double, 2u>
  Reference Count: 2
  Modified Time: 609
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 606
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [39, 40]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [39, 40]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [39, 40]
  Spacing: [0.911458, 0.911458]
  Origin: [-16.5009, 8.41727]
  Direction: 
0.999611 6.07277e-08
0.0279047 -1

  IndexToPointMatrix: 
0.911103 5.53507e-08
0.025434 -0.911458

  PointToIndexMatrix: 
1.09757 6.66529e-08
0.0306274 -1.09714

  Inverse Direction: 
1.00039 6.07513e-08
0.0279156 -1

  PixelContainer: 
    ImportImageContainer (0x7ff0eb01b750)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 603
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7ff0ea83d000
      Container manages memory: true
      Size: 1560
      Capacity: 1560

     Weighting = 1
     Sampling strategy = none
     Number of bins = 32
     Radius = 4
     Sampling percentage  = 1
   Transform = Rigid
     Gradient step = 0.6
     Update field sigma (voxel space) = 0
     Total field sigma (voxel space) = 0
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 0
     Number of time point samples = 0
Registration using 1 total stages.

Stage 0
  iterations = 15
  convergence threshold = 1e-06
  convergence window size = 10
  number of levels = 1
  Shrink factors (level 1 out of 1): [1, 1]
  smoothing sigmas per level: [0]
  using the MeanSquares metric (weight = 1)
  Using default NONE metricSamplingStrategy 

*** Running rigid registration ***

dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
  Referenced from: /Users/slevy_local/spinalcordtoolbox/bin/osx/isct_antsRegistration
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___sincos_stret
  Referenced from: /Users/slevy_local/spinalcordtoolbox/bin/osx/isct_antsRegistration
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

**Comment by jcohenadad** [comment]
can you try re-compiling ANTs (the binaries are a couple of months old) and test it again?  Also please test it on ferguson.

If it continues failing we report on ANTs forum.
thanks

**Comment by jcohenadad** [comment]
re-check now with new binaries.

**Comment by slevyrosetti** [comment]
Works now with the new binaries.
