### ISSUE TITLE
installation of patches should be better...

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#387]
example:
- when installing patch_2.0.3, it should install patches 2.0.1 and 2.0.2
- the installer should work without connection is all the dependences are installed.
- the installer for dev should be integrated into user installer

**Comment by jcohenadad** [comment]
new solution for patches is to keep the previous patch and add files (and replace if necessary).
therefore there is no need during the installation of the package, to download all patches-- just the latest.

patch installer: add a flag to "force" installation even if current version is more recent.

**Comment by benjamindeleener** [comment]
internet connection issue fixed in fdda45c40745f74a8d2b203bc6e801ba836cface
patch_installer issue fixed in ce93b338f6f7acd1abf9358457891a8a681d6ec0

**Comment by benjamindeleener** [comment]
The error of connection should be displayed at the end of installation and a warning (for patch installation) should be display.

**Comment by benjamindeleener** [comment]
Patches are not used anymore with new installer.
