### ISSUE TITLE
smoothing_window has fixed points at edges

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#389]
![screen shot 2015-06-06 at 18 52 05](https://cloud.githubusercontent.com/assets/2482071/8021823/dd08b74c-0c7d-11e5-97bf-8ebd4a3ae03b.png)

this is due to the mirrored data.
this can cause problems when calculating derivatives at the edge.

**Comment by tanguymagnan** [comment]
This was a requiry of the function smoothing_window as we encountered problem at edges when not using mirror.
If one does not want fixed edges I think the best solution is to used the function lowpas from msct_smooth which filters with a lowpass butterworth filter of order 5.

![screenshot 2015-07-21 13 53 36](https://cloud.githubusercontent.com/assets/11425966/8827453/b3c0bf0a-305a-11e5-966f-7668c9e4e69a.png)
