### ISSUE TITLE
sct_resample output has black lines on first slice (z=0)

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#393]
original image voxel dimension: 0.46875x0.46875x15mm
wanted voxel dimension: 0.5x0.5x15mm

path to data: 
``/Volumes/folder_shared/greymattersegmentation/DATA_AMU15/all_data_3d_resampling_old_bad_res/G1_2/3d_data``

command: 
``sct_resample -i G1_2_im.nii.gz -f 0.9375x0.9375x1 -o G1_2_im_test_resample.nii.gz ``

original image:
![screen shot 2015-06-10 at 4 03 50 pm](https://cloud.githubusercontent.com/assets/5857909/8092785/5a25272e-0f8a-11e5-9529-19799a3eb01c.png)

Result image:
![screen shot 2015-06-10 at 4 03 59 pm](https://cloud.githubusercontent.com/assets/5857909/8092790/63f140da-0f8a-11e5-8e19-27d3a9fb43c9.png)

(c3d -resample-mm gives result worst)

**Comment by SaraDupont** [comment]
work around: padding with a black slice as first slice, resampling, croping.

**Comment by jcohenadad** [comment]
related to issue 493
