### ISSUE TITLE
Build execution command form parser

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#394]
In the context of the spinal tool box on the web:

We would like to be able to understand how we can execute a toolbox script by querying its parser. We think it would be possible if the execution script are rearranged slightly.

Right now it looks like that:

```python
import Parser
import sct

if __name__ == "__main__":
    # parser initialisation
    parser = Parser(__file__)
    ...
    # Building the command, do sanity check
    arguments = parser.parse(sys.argv[1:])
    cmd = ...
    ....
    # Run the command
    ...
    sct.run(cmd)
   ...
```
we would need somthing like that:

```python
def get_parser()
    # parser initialisation
    parser = Parser(__file__)
    ...
    return parser

def main(args = None)

    if not args:
        args = sys.argv[1:]

    parser = get_parser()
    # Building the command, do sanity check
    ...
    # Run the command
    ...

if __name__ == "__main__":
   main()
```

This has two important advantage:

We will be able to import the executable and get information about its input options with the get_parser() method.  This will be used to build the submission ui and execution script and will not need maintenance, unlike the actual json config files.

We will also be able to run the executable from python using the main([list_of_options]) method, if a proper list of options is provided. This can be use for debugging of course but it also has many other useful applications...

**Comment by ComtoisOlivier** [comment]
I implemented a new base class for scripts that contain 2 methods.
1. The main class that we will set all the correct parameters for the script's algo
2. The method get_parser that will return the script's parser

I implemented it this way in order to provide a template for future script (so that we don't forget to put the get_parser method each time we create a new script). I haven't pushed it to master yet but you can see it in the branch oc_issue_394

msct_base_classes contains the BaseScript class that serves as a template.
sct_propseg implements a child class of BaseScript and a way to use it.

**Comment by benjamindeleener** [comment]
Let's do a new class like this:

```
class Script(BaseScript):
    def __init__(self):
        super(Script, self).__init__()

    @staticmethod
    def get_parser():
        # Initialize the parser
        parser = Parser(__file__)
        parser.usage.set_description('''This program automatically detect the spinal cord in a MR image and output a centerline of the spinal cord.''')
        parser.add_option(name="-i",
                          type_value="file",
                          description="input image.",
                          mandatory=True,
                          example="t2.nii.gz")
        parser.add_option(name="-t",
                          type_value="multiple_choice",
                          description="type of image contrast, t2: cord dark / CSF bright ; t1: cord bright / CSF dark",
                          mandatory=True,
                          example=['t1', 't2'])
        parser.usage.addSection("General options")
        parser.add_option(name="-v",
                          type_value="multiple_choice",
                          description="1: display on, 0: display off (default)",
                          mandatory=False,
                          example=["0", "1"],
                          default_value="1")
        parser.add_option(name="-h",
                          type_value=None,
                          description="display this help",
                          mandatory=False)

        return parser
```

Then, the parser can be generated directly in the main method like this:
```
if __name__ == "__main__":
    parser = Script.get_parser()

    arguments = parser.parse(sys.argv[1:])

    input_image = Image(arguments["-i"])
    contrast_type = arguments["-t"]
```

and can also be retrived outside the script as it is a static method.

**Comment by benjamindeleener** [comment]
All the script from the toolbox will be refactored.
