### ISSUE TITLE
sct_apply_transfo --> if no output specified.... output is in tmp folder (and tmp isn't deleted)

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#402]
my command (input is 4D data):
`````

sct_apply_transfo -i AxCaliber_1.nii.gz -d AxCaliber_2_1.nii.gz -w warp_AxCaliber_1_1_RPI2AxCaliber_2_1.nii.gz
``````

files are here:
`````

/Volumes/folder_shared/BUGS/sct_apply_transfo
`````

**Comment by tanguyduval** [comment]
The problem is that sct_apply_transfo doesn't handle relative path in 4D data

**Comment by benjamindeleener** [comment]
@tanguymagnan is it fixed?

**Comment by tanguymagnan** [comment]
It is, but we are working on a new branch with Tanguy named issue 401 that
gathers all the small changes that we did for the regularized
registrations. We'll merge it today on master.

2015-07-14 18:28 GMT-04:00 Benjamin De Leener <notifications@github.com>:

> @tanguymagnan <https://github.com/tanguymagnan> is it fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neuropoly/spinalcordtoolbox/issues/402#issuecomment-121412112>
> .
>



-- 
Tanguy Magnan de Bornier
Second year student at the Ecole Centrale de Lille, France.
Ph.: 06.77.25.29.91
