### ISSUE TITLE
documentation on sct_register_multimodal

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#406]
Option mask (-m) --> is it a mask for source or destination?
Also refer to sct_create_mask in the documentatino.

**Comment by ComtoisOlivier** [comment]
I checked where the mask is applied and it is at the begining of the registration pipeline. I changed the -m description to : Spinal cord segmentation mask created with sct_create_mask to improve accuracy over region of interest. This mask will be used at all the stages of the registration.",

**Comment by tanguymagnan** [comment]
We should investigate more about how masks are used in ants. 
Looking at the help of antsRegistration, here is what is said about mask:
     -x, --masks [fixedImageMask,movingImageMask]
          Image masks to limit voxels considered by the metric. Two options are allowed 
          for mask specification: 1) Either the user specifies a single mask to be used 
          for all stages or 2) the user specifies a mask for each stage. With the latter 
          one can select to which stages masks are applied by supplying valid file names. 
          If the file does not exist, a mask will not be used for that stage. Note that we 
          handle the fixed and moving masks separately to enforce this constraint. 
While looking at the help of antsSliceRegularizedRegistration:
     -x, --mask mask-in-fixed-image-space.nii.gz
          Fixed image mask to limit voxels considered by the metric. 

It seems that with antsRegistration you can specify two masks -one for the moving image and one for the fixed image- whereas for slicereg you can only specify a mask for the fixed image. I think that logic dictates that in that case (for slicereg), same mask will be used for the moving image as it does not make any sense to select a region of interest for the fixed image and not for the moving image. However if we end up with the same mask for both fixed and moving images, then problems can occur if thy are not in the same physical space.
Maybe this is the problem that we had with masks and slicereg.

**Comment by benjamindeleener** [comment]
I close this issue as documentation has been improved, even if it useful information.
