### ISSUE TITLE
probabilist templates of WM and GM do not sum to 1 and tracts of atlas do no sum to 1

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#411]
I don't understand why the probabilist templates of WM and GM do not sum to 1 (each pixel is different from 1 even in the center). 
I get that when constructing it with all the subjects, it does not sum to 1 but shouldn't we correct this afterwards?

**Comment by tanguymagnan** [comment]
In the last version that was send to us by the people from marseille (from template 35 subjects generated for ISMRM) it does sum perfectly to 1 in the center. See screenshots that follows.

Old version:
![screenshot 2015-07-22 11 10 09](https://cloud.githubusercontent.com/assets/11425966/8828872/4a8c8d54-3062-11e5-8c1e-016da48972f3.png)


New version:
![screenshot 2015-07-22 11 01 23](https://cloud.githubusercontent.com/assets/11425966/8828906/63f8080e-3062-11e5-8f26-ac4394836be2.png)

**Comment by tanguymagnan** [comment]
It turns out that the sum of all tracts of the current atlas also do not sum to 1 (see screenshot).
![screenshot 2015-07-22 12 34 19](https://cloud.githubusercontent.com/assets/11425966/8831107/20153650-306e-11e5-89e1-f51d6c8c3c2b.png)

This does not come from the fact that the templates of WM and GM do not sum to 1. I actually generated a new atlas from the new template (the one that sums to 1) (branch: new_template_and_atlas), and the results are similar:
![screenshot 2015-07-22 12 40 33](https://cloud.githubusercontent.com/assets/11425966/8831187/ad307090-306e-11e5-9b42-80d302d8228f.png)

Thus i created a small matlab script divide_by_sum.m that creates new tracts that follows the relation:
new_tract_i = old_tract_i / sum_of_all_old_tract
That way the sum of the new tracts is one for each pixel:
![screenshot 2015-07-22 12 40 40](https://cloud.githubusercontent.com/assets/11425966/8831262/3545aa9a-306f-11e5-82f3-693fbc79485a.png)

**Comment by SaraDupont** [comment]
Issue remains with PAM50:
![2016-08-15_sum_tracts](https://cloud.githubusercontent.com/assets/5857909/17667781/5b5133f6-62d4-11e6-828e-d5204adc6d2a.png)

**Comment by jcohenadad** [comment]
fixed in https://github.com/neuropoly/spinalcordtoolbox/pull/1090
