### ISSUE TITLE
using setuptool and perhaps virtualenv instead of messing up with users bashrc.

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#416]
I realized last week that following the toolbox installation to the letter was messing up with my .bashrc and changing the default python link! That could have very undesirable effect on so many aspect for end user. I would almost count that installation procedure as a virus (but I am too polite to do so).

I would recommend distributing the toolbox with a setup.py file using the setuptools module to track dependency instead of forcing conda by default on all terminal. We could also recommend that the user set a virtual environment (using python's `virtualenv`) on its machine that would activate when running  `sct_activate` or some other activation method.    

The virtualenv part is also desirable since one would be able to install the toolbox without being a superuser.

**Comment by benjamindeleener** [comment]
`virtualenv`is not the way to install SCT. Indeed, SCT comes with an embedded python.
