### ISSUE TITLE
sct_straighten_spinalcord: bad concatenation of warping fields for straight2curve

### ISSUE THREAD

**Issue by tanguymagnan** [neuropoly/spinalcordtoolbox#418]
The display of the warping field is bad -problem at edges-. 

![screenshot 2015-07-22 16 08 00](https://cloud.githubusercontent.com/assets/11425966/8835940/a4d4ec38-308b-11e5-873e-d55398c95d4b.png)

This is due to a bad command when concatenating rigid and non-linear transfo:
isct_ComposeMultiTransform 3 tmp.straight2curve.nii.gz -R data_RPI_crop_normalized.nii.gz -i tmp.curve2straight_rigid.txt tmp.warp_straight2curve.nii.gz

If you invert the command such as: 
isct_ComposeMultiTransform 3 tmp.straight2curve.nii.gz -R data_RPI_crop_normalized.nii.gz tmp.warp_straight2curve.nii.gz -i tmp.curve2straight_rigid.txt 

here is the result for the display of the warping field: 
![screenshot 2015-07-22 16 10 36](https://cloud.githubusercontent.com/assets/11425966/8835998/029f6adc-308c-11e5-9923-703fa16a99bf.png)

N.B.: results are the same for the image afterwards

**Comment by tanguymagnan** [comment]
see issue 414 for same problem

**Comment by benjamindeleener** [comment]
I agree with that and I changed the order of transformation. This rule should be checked: should the affine transfo always be at the end of the list or just not at the beginning?
