### ISSUE TITLE
Template registration on example data (T2) is not correct

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#420]
![image](https://cloud.githubusercontent.com/assets/7757117/8881516/810994aa-320e-11e5-9313-db95fedcb33b.png)

Could be the steps that are not good, or the straightening that produces a wrong warping field...

**Comment by benjamindeleener** [comment]
On another subject, the registration went well so it is not completely related to the straightening:
![image](https://cloud.githubusercontent.com/assets/7757117/8885869/b4a0f268-3231-11e5-8f46-2505952a2a42.png)

My guess is that because we know are using only translation (xy) as a first step during the straightening, the deformation needed by the ANTs' landmark-based bspline method is bigger and the mesh size is not high enough to make it work properly at some points along the spinal cord, as you can see on the image below:

**Comment by benjamindeleener** [comment]
Using a pre-registration based on translation followed by rotation, the results are much better.

Results with only translation:
![image](https://cloud.githubusercontent.com/assets/7757117/8969106/51651724-360f-11e5-9340-a8a031ff8a11.png)

Results with translation + rotation:
![image](https://cloud.githubusercontent.com/assets/7757117/8969116/65431070-360f-11e5-8ae1-8bc83462e572.png)

However, the intervertebral disks seem to be wrongly oriented. They should be perpendicular to the spinal cord instead of perpendicular to the xy plane.

**Comment by benjamindeleener** [comment]
with gapxy=40 in sct_straighten_spinalcord: 192 sec (162 before)

![image](https://cloud.githubusercontent.com/assets/7757117/8969339/bb74741a-3610-11e5-9b20-c1422a1af17a.png)

**Comment by jcohenadad** [comment]
fixed
