### ISSUE TITLE
Creation new template

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#426]

**Comment by jcohenadad** [comment]
- Integration new straightening
- Merging branch template to branch master
- Send data to Vlad
- Registration T1-T2

**Comment by benjamindeleener** [comment]
@jcohenadad Should I integrate the new straightening to the new template. It should be better (I need to check everything anyway).

**Comment by jcohenadad** [comment]
yes!

**Comment by benjamindeleener** [comment]
Ok I will merge master into template. The branch template will be merged into master for release 3.0 (or before if necessary).

Started adding new data to the dataset for the template to reach 50 subjects, following directives from here: https://github.com/neuropoly/spinalcordtoolbox/tree/template/dev/template_preprocessing.
Data are (checked when processing is done):
- [ ] T2/errsm_36
- [ ] T2/errsm_37
- [ ] T2/errsm_43
- [ ] T2/errsm_44
- [ ] T2/AM
- [ ] T2/HB
- [ ] T2/PA (backup: 51 subjects)

- [ ] T1/errsm_36
- [ ] T1/errsm_37
- [ ] T1/errsm_43
- [ ] T1/errsm_44
- [ ] T1/AM
- [ ] T1/HB
- [ ] T1/PA (backup: 51 subjects)

After a quick check, some data are **not** properly pre-processed. For exemple, the centerline that are provided for errsm_32 and errsm_33 are completely wrong... I need to check all data and redo preprocessing when necessary.
- [ ] T2/errsm_02
- [ ] T2/errsm_04
- [ ] T2/errsm_05
- [ ] T2/errsm_09
- [ ] T2/errsm_10
- [ ] T2/errsm_11
- [ ] T2/errsm_12
- [ ] T2/errsm_13
- [ ] T2/errsm_14
- [ ] T2/errsm_16
- [ ] T2/errsm_17
- [ ] T2/errsm_18
- [ ] T2/errsm_21
- [ ] T2/errsm_22
- [ ] T2/errsm_23
- [ ] T2/errsm_24
- [ ] T2/errsm_25
- [ ] T2/errsm_30
- [ ] T2/errsm_31
- [ ] T2/errsm_32
- [ ] T2/errsm_33
- [ ] T2/1
- [ ] T2/ALT
- [ ] T2/JD
- [ ] T2/JW
- [ ] T2/MLL
- [ ] T2/MT
- [ ] T2/T045
- [ ] T2/T047
- [ ] T2/VC
- [ ] T2/VG
- [ ] T2/VP
- [ ] T2/pain_pilot_1
- [ ] T2/pain_pilot_2
- [ ] T2/pain_pilot_4
- [ ] T2/TM
- [ ] T2/errsm_20
- [ ] T2/pain_pilot_3
- [ ] T2/errsm_34
- [ ] T2/errsm_35
- [ ] T2/pain_pilot_7
- [ ] T2/errsm_03
- [ ] T2/FR
- [ ] T2/GB

- [ ] T1/errsm_02
- [ ] T1/errsm_04
- [ ] T1/errsm_05
- [ ] T1/errsm_09
- [ ] T1/errsm_10
- [ ] T1/errsm_11
- [ ] T1/errsm_12
- [ ] T1/errsm_13
- [ ] T1/errsm_14
- [ ] T1/errsm_16
- [ ] T1/errsm_17
- [ ] T1/errsm_18
- [ ] T1/errsm_21
- [ ] T1/errsm_22
- [ ] T1/errsm_23
- [ ] T1/errsm_24
- [ ] T1/errsm_25
- [ ] T1/errsm_30
- [ ] T1/errsm_31
- [ ] T1/errsm_32
- [ ] T1/errsm_33
- [ ] T1/1
- [ ] T1/ALT
- [ ] T1/JD
- [ ] T1/JW
- [ ] T1/MLL
- [ ] T1/MT
- [ ] T1/T045
- [ ] T1/T047
- [ ] T1/VC
- [ ] T1/VG
- [ ] T1/VP
- [ ] T1/pain_pilot_1
- [ ] T1/pain_pilot_2
- [ ] T1/pain_pilot_4
- [ ] T1/TM
- [ ] T1/errsm_20
- [ ] T1/pain_pilot_3
- [ ] T1/errsm_34
- [ ] T1/errsm_35
- [ ] T1/pain_pilot_7
- [ ] T1/errsm_03
- [ ] T1/FR
- [ ] T1/GB

**Comment by benjamindeleener** [comment]
The convertion of dicom to nifti for some Marseille data produces errors:

``
dcm2nii -o . -r N /Users/benjamindeleener/data/data_template/ED/01_0008_sc-tse-spc-1mm-3palliers-fov256-nopat-comp-sp-65/*.dcm
Chris Rorden's dcm2nii :: 4AUGUST2014 32bit BSD License
reading preferences file /Users/benjamindeleener/.dcm2nii/dcm2nii.ini
Data will be exported to ./
Validating 38 potential DICOM images.
Found 38 DICOM images.
Converting 38/38  volumes: 1
original-primary-m-norm-dis2d-comp-sp-composed_e01_0001.dcm->20130731_113349SCtsespc1mm3palliersfov256nopat3s008a1001.nii
An unhandled exception occurred at $000366A1 :
EConvertError : "1.3.12.2.1107.5.2.36.40146.2013073111552139282708168" is an invalid float
$000366A1
$0003662D
$0006210C
$0003E4A1
$0004290B
$00048388
$000487C7
$0005810C

/Users/benjamindeleener/code/spinalcordtoolbox/scripts/sct_utils.py, line 97
``

Path are correct.

**Comment by jcohenadad** [comment]
this works on my computer:
~~~
dcm2nii -o . /Volumes/data_shared/marseille/ED/01_0008_sc-tse-spc-1mm-3palliers-fov256-nopat-comp-sp-65/*.dcm
~~~

with version dcm2nii: ``Chris Rorden's dcm2nii :: 6 June 2013``

**Comment by benjamindeleener** [comment]
Even the newest version is not working...
```Chris Rorden's dcm2nii :: 1JUNE2015 32bit BSD License```

**Comment by benjamindeleener** [comment]
I posted my issue on NITRC forum: https://www.nitrc.org/forum/forum.php?thread_id=6020&forum_id=568

**Comment by benjamindeleener** [comment]
I finished updating data for the template pre-processing. Running ```preprocess_data_template.py``` took approximately 20 minutes.

I am now running ```pipeline_template.py```.

**Comment by benjamindeleener** [comment]
Approximation:
do_processing for T1 and T2 for one subject takes 14 min. So for 50 subjects: **12 hours**.

After that, I need to do:
```
create_cross('T1')
push_into_templace_space('T1')
average_levels('T1')
align_vertebrae('T1')

create_cross('T2')
push_into_templace_space('T2')
average_levels('T2')
align_vertebrae('T2')
```

**Comment by benjamindeleener** [comment]
```do_processing(T1)```took 5 hours approximately.

The results are very good, but not perfect. For exemple, errsm_32/T1
![image](https://cloud.githubusercontent.com/assets/7757117/10663354/bb466844-7888-11e5-9de3-bb52c26c0609.png)

**Comment by benjamindeleener** [comment]
For bspline_meshsize=5x5x30, the straightening results are very good but we can see some flaws around the spinal cord:
![image](https://cloud.githubusercontent.com/assets/7757117/10664189/420da184-788f-11e5-8309-04c87d80c17f.png)

Note: it took the same time as the other parameters.

**Comment by benjamindeleener** [comment]
The part ```do_processing()``` for both T1 and T2 contrast took 4 hours to compute (when run in two different terminal).

**Comment by benjamindeleener** [comment]
Pre-processing is almost done.
Several images have issues. I don't have time to pre-process everything again but for next round, here are the flaws:

- intensity normalization for T2w images is definitely not perfect. Some images have artifacts that lead to dark images. The mean intensity of images is not the same for all images. We need a better way to normalize the image intensity at a global scale.
- some subjects have issues and we need to remove them. For exemple, marseille/TM/T1/ had an issue with the stitching procedure. marseille/TM/T2/ has an intensity artifact. errsm_02 has really bad image quality.
- straightening with B-spline is not completely perfect. We need to find a better deformation model. Thin-plate deformation model has high potential.
- ...

**Comment by benjamindeleener** [comment]
I registered the T1w and T2w templates together. It worked fine and lasted for 6 hours. Registration is perfect in xy plane. We can still see vertebral levels differences between the two template, indicating that vertebral levels in template space should be the same for both contrasts.

By the way, as we have new subjects, we can remove subjects that have issues (errsm_02 -> bad contrast, TM -> stitching issue). New subjects are sct_001 and sct_002

**Comment by benjamindeleener** [comment]
The template generation is finished. The creation of T1w and T2w template on a machine with 32 hyperthreaded cores (16 physical cores) toke approximately 10 days.

Then, the computation of the final template (middle template between T1w and T2w template) took only 1h30min.

Results are extremely good:
![screen shot 2015-11-02 at 17 47 16](https://cloud.githubusercontent.com/assets/7757117/10896733/d6af5956-8189-11e5-8250-268cf748920a.png)
![screen shot 2015-11-02 at 17 47 26](https://cloud.githubusercontent.com/assets/7757117/10896732/d6abe42e-8189-11e5-9836-c8b9c73e9942.png)

**Comment by jcohenadad** [comment]
nice :+1:

**Comment by benjamindeleener** [comment]
To produce the segmentation of the template, I applied this command:
```
sct_propseg -i template_t2.nii.gz -t t2 -down 183 -up 972
mv template_t2_seg.nii.gz template_cord.nii.gz
fslview template_cord.nii.gz &
```

Then, I completed the segmentation manually from slice 113 to slice 182 and from slice 967 to slice 975 and I removed slice 976-977-978 because PropSeg could not segment the spinal cord accurately at these levels.

Vertebral levels were also done manually, from top of C1 vertebrae (label=1) to L1-L2 intervertebral disk (label=21). The labels file is called ```template_labels.nii.gz``` and can be produced with the following command:
```
sct_label_utils -i template_t2.nii.gz -o template_labels.nii.gz -t create -x 99,96,51,21:99,96,120,20:99,96,184,19:99,97,242,18:99,98,299,17:99,98,350,16:99,98,403,15:99,98,454,14:99,98,503,13:99,98,552,12:99,97,597,11:99,98,641,10:99,97,683,9:99,97,723,8:99,98,757,7:99,97,789,6:99,96,821,5:99,97,854,4:99,98,889,3:99,96,920,2:98,94,973,1
```

Then I used the following command to produce a segmentation with vertebral labeling:
```
sct_label_utils -i template_cord.nii.gz -t disks -o template_levels.nii.gz -r template_labels.nii.gz
```

Results can be visualized with this command:
```
fslview template_t1.nii.gz -b 0,3000 template_t2.nii.gz -b 0,3000 template_levels.nii.gz -l MGH-Cortical -b 0,21 &
```
![image](https://cloud.githubusercontent.com/assets/7757117/10899429/7330bf64-81a2-11e5-943c-137e86841f2d.png)
![image](https://cloud.githubusercontent.com/assets/7757117/10899438/7c559b14-81a2-11e5-80d0-bb28eacdde55.png)

These results have been sent to Aix-Marseille Université for registration of the T2*-weighted template and the gray/white matter atlas.

**Comment by benjamindeleener** [comment]
The landmarks were created manually and be be regenerated using the following command:
```
sct_label_utils -i MNI-Poly-AMU_T2.nii.gz -t create -o landmarks_center.nii.gz -x 99,97,17,21:99,96,88,20:99,96,155,19:99,97,215,18:99,97,273,17:99,98,326,16:99,98,379,15:99,98,432,14:99,98,481,13:99,98,530,12:99,97,577,11:99,97,620,10:99,97,663,9:99,97,702,8:99,97,740,7:99,97,773,6:99,96,805,5:99,97,836,4:99,97,871,3:99,97,905,2:99,96,938,1
```

**Comment by benjamindeleener** [comment]
The CSF segmentation (MNI-Poly-AMU_T2_CSF.nii.gz) was acquired using the following commands:
```
sct_propseg -i MNI-Poly-AMU_T2.nii.gz -t t2 -down 183 -up 972 -CSF
mv MNI-Poly-AMU_T2_CSF_seg.nii.gz MNI-Poly-AMU_T2_CSF.nii.gz
```

**Warning: the CSF segmentation is not perfect and does not cover the entire spinal cord (or at least the same region of the spinal cord segmentation. It needs to be corrected before use.**

**Comment by benjamindeleener** [comment]
TO DO:
- [ ] modify the info_label.txt to add T1w template and the intervertebral disks labels.
- [ ] check if it is working with sct_extract_metric

**Comment by benjamindeleener** [comment]
PAM50 is now in latest version of SCT.
