### ISSUE TITLE
"Modified on: " field should not depend on local update but on the effective modification 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#436]
For example, if a developer does a "git checkout", which updates the content of the file, then the parser thinks that the modification date is the date of the checkout.
Ideally, the modification should be based on the github repository (if possible).

**Comment by jcohenadad** [comment]
http://stackoverflow.com/questions/6795070/is-there-a-way-in-git-to-obtain-a-push-date-for-a-given-commit

**Comment by ComtoisOlivier** [comment]
Git hooks.
https://www.atlassian.com/git/tutorials/git-hooks/

Ill try that.

**Comment by jcohenadad** [comment]
could you please change:
~~~
Modified on  Mon Sep 28 16:33:53 2015 
~~~
for:
~~~
Modified on:  2015-09-28 16:33:53
~~~

**Comment by jcohenadad** [comment]
make sure to manage in case there is no modif.txt file

**Comment by jcohenadad** [comment]
let's change the approach since there is a problem with having developers manage their own motif.txt. How about this:
http://stackoverflow.com/questions/2179722/checking-out-old-file-with-original-create-modified-timestamps/2179876#2179876

**Comment by jcohenadad** [comment]
ok, after all, let's forget about modification date and just display version.txt.
