### ISSUE TITLE
check if versions of python module correspond to versions from requirements

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#438]
After each check, add a line that display the current version (for all modules).
if the module does not correspond to the requirements, print "WARNING" instead of "OK" and add a line that says: "Differs from requirements (XX)".

**Comment by ComtoisOlivier** [comment]
Fixed in f66ef99a815324ef8c0f659bb54096fddbebf6a5

![screen shot 2015-08-04 at 3 32 58 pm](https://cloud.githubusercontent.com/assets/5317821/9070732/598f3588-3abf-11e5-9be1-979fe6113d02.png)

**Comment by ComtoisOlivier** [comment]
Not fixed for Linux

**Comment by jcohenadad** [comment]
could you also add a line below each python test, that indicates the current version of the module?
thanks!

**Comment by jcohenadad** [comment]
do not use conda
~~~~
python
import blabla
blabla.__version__
~~~~
