### ISSUE TITLE
sct_dice_coefficient : -bin option doesn't work

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#439]
output : `Segmentation fault: 11`

**Comment by peristeri** [comment]
@SaraDupont Can you add the command + the data that caused the error?

**Comment by SaraDupont** [comment]
Command was: 
`sct_dice_coefficient -i image1.nii.gz -d image2.nii.gz -bin 1`
But I couldn't find data to reproduce this issue so I guess it's fixed !

**Comment by peristeri** [comment]
Cool.
