### ISSUE TITLE
recompile ANTs

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#448]

**Comment by ComtoisOlivier** [comment]
Do you need a documentation on how to compile ants?
Where should we compile it ( in masters)?

**Comment by benjamindeleener** [comment]
It is simply the recompilation of ANTs binaries to get updates, then integrate them into the toolbox in bin/ folder (and change their names to add ``isct_`` prefix.

We should create a script that compile ANTs, then copy the files automatically.

**Comment by ComtoisOlivier** [comment]
Alright ill pull to update and try to comp[ile it

**Comment by jcohenadad** [comment]
thanks! please do both on Debian and OSX

**Comment by ComtoisOlivier** [comment]
I compiled the ANTS binaries after synching with the repo. I added a bash script that will do the make + move/rename binaries. However, the paths are hardcoded and they need to be changed.

**Comment by ComtoisOlivier** [comment]
Ill need to do this on linux now

**Comment by benjamindeleener** [comment]
I already have a virtual machine with everything installed for compilation and so on. If you have the script that I can launch for updating the binaries, I can do it.

Can't we changed the path with SCT_DIR variable?

**Comment by ComtoisOlivier** [comment]
To use an environment variabnle in bash you can just use $SCT_DIR?

**Comment by benjamindeleener** [comment]
exactly, or maybe ``${SCT_DIR}``

**Comment by ComtoisOlivier** [comment]
Ok I have added the script build_ants_sct.sh in bin/osx and added the rest of the instructions to fetch ants [here](http://www.neuro.polymtl.ca/doku.php?id=internal_resources:list_of_software&#compiling_ants)

**Comment by benjamindeleener** [comment]
Done on branch dev.

The script in install/ folder does it.
I removed the script in bin/osx/.
