### ISSUE TITLE
include sct_segment_graymatter

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#453]
- merge to master
- create test
- testing on MT data (ask julien)
- (integrate into registration pipeline)

**Comment by SaraDupont** [comment]
Tried to segment gray matter on an MT image (from pain_pilot_8 : ```/Volumes/folder_shared/greymattersegmentation/supervised_gmseg_method/testing/2015-08-18_test_on_MT/pilot8```) with the current model: it gives a result (not so bad but clearly not good either, see below).  When looking at the PCA modes scatter plot with the model images (rounds) and the MT target image (triangles), the MT slices are outsiders ==> the model doesn't fit for them.
![modes_0_1](https://cloud.githubusercontent.com/assets/5857909/9336061/76e3e4da-45a5-11e5-9018-2214834005b8.png)

I see two options: 
    - Add intensity normalisation 
    - Create a new model with a dictionary of MT data (need manual gray matter segmentations...) 


![pilot8_mtc1_slice14_res_gmseg](https://cloud.githubusercontent.com/assets/5857909/9336103/bfdad270-45a5-11e5-9692-64f8a5ce41c5.png)
![pilot8_mtc1_slice14](https://cloud.githubusercontent.com/assets/5857909/9336104/c1a0ad00-45a5-11e5-8504-56144653c5b8.png)

**Comment by jcohenadad** [comment]
Sara, the MT images you will work with are slightly different, i.e., with larger frequency offset, therefore they will "look more similar" to a T2*w image. However, we need to anticipate that the contrast might still be a bit different. How about adding a flag to your function, which tells the average value in the WM, and the ratio between WM and GM. That way, we can rescale the template to fit any other image. Would that work? If so, would that be easy to implement?

**Comment by SaraDupont** [comment]
It shouldn't be too hard to implement, but I think we can make it simpler and automatic : a trivial linear normalization gives better results: 
![modes_0_1](https://cloud.githubusercontent.com/assets/5857909/9344185/c2364bec-45d4-11e5-95ba-0cb9489fcf0b.png)

Two options : 
   - trivial linear normalization with new_min=0, new_max = max of the dictionary mean image
   - linear normalization with new_min=average WM min in the dictionary images, new_max=average WM max in the dictionary images

The results of the two options are similar, it need to be tested on more than one subject, but the second one is probably more robust.

Do you already have some pilot data on which I could test the model ?

**Comment by jcohenadad** [comment]
agreed-- i've added some data under folder_shared/sdupont/sct_segmentation_graymatter

**Comment by SaraDupont** [comment]
OK, I'm working on it. Do you also have anatomic images to register the template (for the vertebral levels) ? (I found a T2 for errsm36 but not for the others)

**Comment by jcohenadad** [comment]
i've added t2+reg for 2 of the 3 datasets (one is missing)

**Comment by SaraDupont** [comment]
Thanks !

**Comment by SaraDupont** [comment]
I've tried to extract metric in the GM and WM on MT data using the labels of the registered template but I think that the registration of the template labels isn't good enough too extract metric in it : 
![bsp_100_001_slice34_mni-poly-amu_gm](https://cloud.githubusercontent.com/assets/5857909/9387200/80184c2e-472d-11e5-941a-c737252883f5.png)

Benjamin proposed another approach based on classification: the idea is that if we have an image like that : 
![idea_im](https://cloud.githubusercontent.com/assets/5857909/9387716/e2841c60-472f-11e5-9a6f-6367e400fafd.JPG)
Ideally we would have an histogram like this one : 
![idea_hist](https://cloud.githubusercontent.com/assets/5857909/9387726/f14ef288-472f-11e5-8324-ac67bf6901c1.JPG)
And use a classification method to get the mean intensity values in the WM and GM without being biased by the possible CSF contamination. 

I looked at the histogram of some images of our model template (T2*-w), they are not clearly bimodal or trimodal, but it could work : 

Without CSF in the cord segmentation:
![model_slice3_im](https://cloud.githubusercontent.com/assets/5857909/9387974/0f8099a4-4731-11e5-8a6c-462e22bfa0df.png)
![model_slice3_hist](https://cloud.githubusercontent.com/assets/5857909/9387978/115143be-4731-11e5-8993-a4f77bf0da71.png)


With CSF in the cord segmentation: 
![model_slice237_im](https://cloud.githubusercontent.com/assets/5857909/9387984/1ba4c17e-4731-11e5-9a3b-16273f7f1a7c.png)
![model_slice237_hist](https://cloud.githubusercontent.com/assets/5857909/9388008/202f8d50-4731-11e5-81ff-d1d7d1b8394e.png)

What do you think of trying this approach with gaussian mixture models ?

**Comment by jcohenadad** [comment]
i'm not a big fan of histograms in general. It might fail if data are too noisy or if there is a lesion.

how about starting with simply getting the average intensity in your spinal cord using the mask, and normalizing with the mean? (i.e., not more min/max, but just put the mean to 1 for instance)

**Comment by SaraDupont** [comment]
I'll try that
