### ISSUE TITLE
improve spinal cord detection

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#454]
- vesselness filter
- minimal path
- body symmetry
- (being able to put a weight for each method)

**Comment by jcohenadad** [comment]
Good ideas here:
https://www.ceremade.dauphine.fr/~cohen/recentpub2.html

**Comment by ComtoisOlivier** [comment]
Thank you!

2015-08-30 10:39 GMT-04:00 Julien Cohen-Adad <notifications@github.com>:

**Comment by benjamindeleener** [comment]
Fixed with the introduction of OptiC.
