### ISSUE TITLE
modify parser to reflect UI (e.g., adapt types)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#458]

**Comment by wpinaud** [comment]
![sctparser](https://cloud.githubusercontent.com/assets/11258860/9368344/b2218a3e-4690-11e5-87bc-7a8bce847809.jpg)

**Comment by joshuacwnewton** [comment]
Closing, as the displayed types in parser are now handled by `metavar=Metavar.<type>` following the conversion to `argparse` in #1548.
