### ISSUE TITLE
update batch_processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#476]

**Comment by SaraDupont** [comment]
Updated the registration of the template to the MT using the automatic WM/GM segmentation

**Comment by SaraDupont** [comment]
Replace ```sct_detect_spinalcord```by ```sct_get_centerline -method automatic/scad``` when its ready.

**Comment by jcohenadad** [comment]
@ComtoisOlivier: let's use "-method auto"
