### ISSUE TITLE
Weird error during template registration

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#478]
command : ```sct_register_to_template -i errsm_34_t2.nii.gz -s errsm_34_t2_seg.nii.gz -l errsm_34_t2_landmarks.nii.gz````

error: 
![reg_to_template_error](https://cloud.githubusercontent.com/assets/5857909/9479825/3cf740f2-4b4d-11e5-84cf-7b205d8ab79a.png)

the data are in ```/Volumes/folder_shared/greymattersegmentation/supervised_gmseg_method/testing/2015-08-25-gmseg_registration_pipeline/errsm_34````

and the functions i used to get the data from data_shared and process it are in the file ```batch_processing.sh```. 

I just merged dev on my branch (sd_graymatterseg_new) today. Is it that i extract the data wrong or is there an issue with ```sct_register_to_template```  ? 

The purpose of this was to register the template on the MT, see how the templates GM fit with the image, then segment the GM automatically on the T2star, use the result to register the template on the MT and see how it improves the registration of the template for the WM and GM.

**Comment by benjamindeleener** [comment]
It is probably a compilation error as suggested by your output: 
```
dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
```

Could you try on another computer with a more recent OS? We probably just need to compile ANTs again. If you want, you can try to do it by following this procedure:
- Clone repository from here: https://github.com/benjamindeleener/ANTs
- Then, go into install folder of the toolbox and type the following command (it may take some times, several minutes):
```
python compile_ants.py -a <path_containing_ANTs_folder> -s osx -f ANTSLandmarksBSplineTransform
```

Then, try again running again sct_register_to_template.

**Comment by SaraDupont** [comment]
I tried to recompile, it didn't work ... But I noticed that when opening a new terminal I get this message: (but I don't no if it was there before)
![init_message](https://cloud.githubusercontent.com/assets/5857909/9480997/a7cbb780-4b54-11e5-9d0e-7a7c1619509a.png)
Could it be an issue from the dynamic linker ?

I'll try tomorrow on another computer.
