### ISSUE TITLE
remove binary: isct_c3d

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#487]

**Comment by SaraDupont** [comment]
List of the dependences: 
     -resample
     -resample-mm
     -pad
     -scale
     -mcs
     -omc
     -smooth
     -reslice-identity
     -int

--> Work in progress on branch sd_remove_c3d
--> Scripts to modify: 
![scripts](https://cloud.githubusercontent.com/assets/5857909/9764302/5470798e-56dc-11e5-8a67-0c2f555a15d5.png)

**Comment by jcohenadad** [comment]
note: for "-reslice-identity", you can use antsRegistration without iteration, E,g,:
~~~~
isct_antsRegistration -d 3 -t Translation[0] -m MI[dest_pad.nii,src.nii,1,16] -c 0 -f 1 -s 0 -o [regAffine,src_regAffine.nii] -n BSpline[3]'
~~~~

In most scripts, replace:
~~~~
# copy files to temporary folder
    sct.printv('\nCopy files...', verbose)
    sct.run('isct_c3d '+fname_src+' -o '+path_tmp+'/src.nii', verbose)
~~~~
with **sct_convert**. E.g.:
~~~~
from sct_convert import convert
sct.printv('\nCopying input data to tmp folder and convert to nii...', param.verbose)
convert(param.fname_data, path_tmp+'fmri.nii')
~~~~

**Comment by SaraDupont** [comment]
OK !

-resample and -resample-mm : Done in sct_resample (new flags -mm and -vox in addition to -f). The new version of sct_resample is even faster : 0.5sec for a 2x up sampling on the t2 image of the testing data instead of 2.32sec with the old version.

**Comment by SaraDupont** [comment]
-pad replaced by a function msct_image (also callable in command line see msct_image usage) 
This new version is faster : 0.05 sec instead of 0.15 sec for a padding in the 3 directions on the t2 image of the testing data.
(commits 7e25de6 and 5ec3c08)

**Comment by jcohenadad** [comment]
since **msct_image** function is not officially listed as a function for the user, i would rather gather all image manipulation under **sct_maths**. 

also, regarding the use of sct_convert, if you haven't changed it already, i would rather call the function using sct.run so that the user knows what's going on (and he can reproduce the steps by copy/pasting):
~~~~
sct.printv('\nCopying input data to tmp folder and convert to nii...', param.verbose)
sct.run(sct_convert -i '+param.fname_data+' -o '+path_tmp+'fmri.nii')
~~~~
Thanks!

**Comment by SaraDupont** [comment]
The pad is now in sct_maths instead of msct_image and the header of the padded image is updated according the new image origin (the sform and qform matrix are updated).

**Comment by SaraDupont** [comment]
**sct_maths** now allows multiple inputs/outputs. New options : -add, -sub, -scale (as preprocessing or alone)

**Comment by jcohenadad** [comment]
removed binaries (commit f4cdd96eb9de2333613c20c05998525c6bedbd99)
