### ISSUE TITLE
remove binary: sct_dice_coefficient

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#488]

**Comment by jcohenadad** [comment]
put it in **sct_maths**

**Comment by benjamindeleener** [comment]
Work in progress. See PR #1099 and issue #1098

**Comment by peristeri** [comment]
To totally eliminate all the sct_dice_coefficient references, sct_register_graymatter, sct_segment_graymatter, test_sct_register_to_template, testing_sct_propseg, isct_test_ants.

**Comment by joshuacwnewton** [comment]
I believe the future of `isct_dice_coefficient` is better handled by #2669. See https://github.com/neuropoly/spinalcordtoolbox/issues/2669#issuecomment-617441202 for more up-to-date information on this binary. So, I'm linking this issue and closing.
