### ISSUE TITLE
PropSeg spinal cord detection module fails on 0.7mm iso image

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#495]
See message of Joshua in https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/8371169b/

It is probably related to the resolution because resampling fix the issue.

**Comment by jcohenadad** [comment]
data: **20150910_joshua**

**Comment by benjamindeleener** [comment]
I don't find the data but it should be fixed with the introduction of OptiC.
