### ISSUE TITLE
register_multimodal fails for some algorithm

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#499]
I tried to extend the tests of sct_register_multimodal to all the algorithms available: it fails for the following algos:

'slicereg2d_translation': -------------> OK
'slicereg2d_rigid': ---------------------> OK
'slicereg2d_affine': -------------------> OK
'slicereg2d_syn': ----------------------> FAILS (shapes error)
'slicereg2d_bsplinesyn': ------------> FAILS (shapes error)
'slicereg':  -------------------------------> OK
'rigid': ------------------------------------> FAILS (no inverse warp step 1  …)
'affine': -----------------------------------> FAILS (no inverse warp step 1  …)
'compositeaffine':  --------------------> FAILS (no forward warp step 1...)
'similarity': ------------------------------> FAILS (ANTs error)
'translation': ----------------------------> FAILS (no forward warp step 1...)
'bspline': --------------------------------> FAILS (ANTs error)
'gaussiandisplacementfield': ------> FAILS (no inverse warp step 1  …)
'bsplinedisplacementfield': ---------> FAILS (no inverse warp step 1  …)
'syn': -------------------------------------> OK
'bsplinesyn':  ---------------------------> OK

Are the failing algorithms frequently used ?

**Comment by jcohenadad** [comment]
remove flags for non-working functions for the moment-- and adjust test for rigid/affine

**Comment by SaraDupont** [comment]
Work in progress on branch sd_improve_register_multimodal/ 

- ```slicereg2d_syn``` and ```slicereg2d_syn``` : Error was occurring because of the shrink factor parameter, fixed by adding a resampling of the warping field.

**Comment by jcohenadad** [comment]
see branch: https://github.com/neuropoly/spinalcordtoolbox/tree/sd_improve_register_multimodal
