### ISSUE TITLE
sct_register_multimodal fails on Linux/works on OSX when using algo slicereg2d_affine

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#500]
In sct_register_multimodal with the algo 'slicereg2d_affine' when sct_concat_transfo is called, isct_ComposeMultiTransform doesn't output any warp_final on Linux. (on branch sd_remove_c3d)

**Comment by SaraDupont** [comment]
isct_ComposeMultiTransform works on OSX with the warping fields obtained on Linux  ==> the problem doesn't come from the warping fields we are trying to concatenate: they are the same on Linux and on OSX.

**Comment by SaraDupont** [comment]
Seems to be related to the multi-component output: the issue appears when using the homemade -omc in sct_maths and not when using the c3d -omc function.

**Comment by jcohenadad** [comment]
for the moment, let's just remove the flags so that the user does not see them

**Comment by SaraDupont** [comment]
Fixed on branch sd_improve_register_multimodal
