### ISSUE TITLE
create dataset for extensive testing 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#506]
- put on data_shared/sct_testing_extensive
- create function: **sct_testing_extensive** based on **sct_testing**
- add data from previous issues

**Comment by jcohenadad** [comment]
ROADMAP:
- create new branch "issue_506"
- edit current tests (e.g. test_sct_propseg):
    - add a third output, which will be a panda structure with fields like MSE, blablabla
    - add 2nd input optional argument to enable custom params (typically for sct_testing_full)
- edit sct_testing:
    - refactoring to make it compatible with new tests
- sct_testing_full:
    - remove function-specific code
    - flags:
       - f: for testing specific function
       -

**Comment by benjamindeleener** [comment]
Comments on the parameters that are passed to the test:
As we would like to call test functions like this: ```isct_test_function -f sct_propseg -p "-i t2/t2.nii.gz -t t2"```, we need a way to add the path to the dataset into the parameters line. For exemple, if I would like to test PropSeg on a dataset with 50 subjects on T2w images, I don't want to copy each subject folder to be in it when I execute the test. The solution is to parse the line provided by -p option, then add the absolute path to dataset (subject folder) in front of each option of type "file". For exemple, the parameter:
```
-i t2/t2.nii.gz
```
would become
```
-i home/dataset/errsm_485/t2/t2.nii.gz
```

This is something that the parser could do:
1. We feed the parser with the -p option and the parser return a dictionnary with each parameter and its value
2. We add the path to dataset in front of each value that is a file (we can check the option to see if it's a file
3. We recompose the line from the dictionnary.

This algo should be in msct_parser and be called ```add_path_to_file(pathname)```

**Comment by jcohenadad** [comment]
why not simply cd to "home/dataset/errsm_485/" inside the test function?

**Comment by jcohenadad** [comment]
why not simply concatenate path and folder/file inside the test function, because all these are passed by arguments?

**Comment by benjamindeleener** [comment]
Yes that is what I meant (your second comment) but with a more elegant way that parsing the options line directly in the test function, while the parser could do the job easily. And because the parser knows which option is a file or not (-i, -w, etc.).

I don't want to cd in the dataset folder in the test function because I don't want to write in it, then moving all the files.

**Comment by jcohenadad** [comment]
yes, i know about the "cd" that was a stupid comment that i removed ;-)
re: parsing option line: i agree that is more elegant. Let's do that then.

**Comment by benjamindeleener** [comment]
It would be nice to have the path inside the test function because we have other images, such as manual segmentation that we want to use to test the function.

**Comment by benjamindeleener** [comment]
The choice of giving directly the options like ```-p "-i t2.nii.gz -s ..." ``` is very constraining because we can't call function as Python scripts and therefore, it is more difficult to extract results directly provided by the script (like MSE for sct_straighten_spinalcord)...

**Comment by jcohenadad** [comment]
on the other hand it also makes the test more "real life" because that's the situation the user will face. Moreover, thinking ahead, we want to make a sct_testing compatible with isc_test_function, so we need to call SCT functions from UNIX. 

Regarding your problem of getting outputs like MSE, I think it only concerns a minority of functions, so that shouldn't be a big deal.

to summarize: i see more pros than cons for calling in UNIX

**Comment by benjamindeleener** [comment]
The test for sct_straighten_spinalcord is done, and it is compatible with sct_testing.

Now I will modify the pipeline (create isct_test_function.py) that launch each test on a large dataset.

**Comment by jcohenadad** [comment]
great :+1:

**Comment by benjamindeleener** [comment]
One problem I see: if we provide the contrast folder directly in the parameter list ("-i t2/t2.nii.gz -t t2 -k ..."), we cannot generate the list of folder that contain this contrast. 
Two solutions: 
1. we provide the folder to isct_test_function.py so it can detect exactly the subjects that have this folder.
2. the function test_sct_XXX.py should return a particular status if folder is missing, for exemple status=5.

I think I will go with the second solution because we need to provide less parameters to isct_test_function.py

**Comment by jcohenadad** [comment]
i would also go for solution #2

**Comment by benjamindeleener** [comment]
Ok. I added the following lines to test_sct_straighten_spinalcord:
```
# Check if input files exist
if not os.path.isfile(dict_param_with_path['-i']):
    return 5, 'ERROR: the file(s) provided to test function do not exist in folder: ' + path_data, None
```

So, for each function, we could check the existence of mandatory files, even if it is already checked by the function itself.

**Comment by benjamindeleener** [comment]
I implemented isct_test_function but I still have some errors with multiprocessing because test functions are not picklable: https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled

**Comment by benjamindeleener** [comment]
The script isct_test_function.py is nearly functional. It can test a function (for now, only sct_straighten_spinalcord) on large datasets and return a DataFrame with all the information (status, output, dataset, subject, parameters, and results from tests, etc.). I still need to change the parser to accept a list of parameters with " ".

**Comment by benjamindeleener** [comment]
So it is now possible to test a function (for now only straightening) on large dataset with many parameters, and display the results. For exemple:
Command (algo=hanning):
```
python isct_test_function.py -f sct_straighten_spinalcord -d sct_testing_data/ -p "-i t2/t2.nii.gz -c t2/t2_seg.nii.gz"
```
Results:
```
                        dist_max   mse  \
sct_testing_data/data/      1.12  0.72  
```


Command (algo=nurbs):
```
python isct_test_function.py -f sct_straighten_spinalcord -d sct_testing_data/ -p "-i t2/t2.nii.gz -c t2/t2_seg.nii.gz"
```
Results:
```
                        dist_max   mse  \
sct_testing_data/data/       3.5  0.89  
```

Many other information are also available in the DataFrame, such as status and output for each test, path to dataset, subject, name of the script that is tested, etc. This dataframe will be easily concatenate with others to compare results of functions with different algorithms and parameters.

**Comment by benjamindeleener** [comment]
I improved the display of results at the end of isct_test_function.py. Example for sct_straighten_spinalcord:
```
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -c t2/t2_seg.nii.gz":
Dataset: /Users/benjamindeleener/data/data_testing/original_data/small/
          dist_max       mse  status
subject                             
errsm_10       NaN       NaN     200
errsm_11   1.23000  0.780000       0
errsm_12   1.69000  0.760000       0
errsm_13   1.73000  1.320000       0
errsm_14   2.77000  0.770000       0
Mean       1.85500  0.907500       0
STD        0.65082  0.275121       0

Passed: 4/5
```

Another example when adjusting the acceptable mse to 0.8:
```
Results for "sct_straighten_spinalcord -i t2/t2.nii.gz -c t2/t2_seg.nii.gz":
Dataset: /Users/benjamindeleener/data/data_testing/original_data/small/
          dist_max       mse  status
subject                             
errsm_10       NaN       NaN  200.00
errsm_11   1.23000  0.780000    0.00
errsm_12   1.69000  0.760000    0.00
errsm_13   1.73000  1.320000   99.00
errsm_14   2.77000  0.770000    0.00
Mean       1.85500  0.907500   24.75
STD        0.65082  0.275121   49.50

Passed: 3/5
```

**Comment by benjamindeleener** [comment]
Done for sct_register_to_template.

```
Results for "sct_register_to_template ":
Dataset: /Users/benjamindeleener/data/data_testing/original_data/small_C2-T2/
          dice_anat2template  dice_template2anat     status
subject                                                    
errsm_05            0.899150            0.903644   0.000000
errsm_09            0.891242            0.898611   0.000000
errsm_10            0.801188            0.786739  99.000000
errsm_11            0.900656            0.907773   0.000000
errsm_12            0.885495            0.905524   0.000000
Mean                0.875546            0.880458  19.800000
STD                 0.042018            0.052499  44.274146

Passed: 4/5
```

**Comment by benjamindeleener** [comment]
To do on isct_test_function.py:
- [ ] remove "Check folder existence..." display
- [ ] add a progression bar

**Comment by benjamindeleener** [comment]
Many improvements have been made. Let's create new issues for new improvements of the testing procedure. Examples: comparison of results with old SCT versions.
