### ISSUE TITLE
sct_maths -pad does not provide a correct header in physical coordinate

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#518]
sct_maths -pad does not provide a correct header in physical coordinate, because subsequent registration with ANTs (no iteration-- just using header) shifts the FOV in the padding direction.

data: 
~~~~
sct_issues/20150924_issue_518/data
~~~~

syntax:
~~~~
sct_maths -i data.nii.gz -o data_pad.nii.gz -pad 0x0x5
isct_antsRegistration --dimensionality 3 --transform syn[0.5,3,0] --metric MI[data_pad.nii.gz,data.nii.gz,1,32] --convergence 0 --output [test,data_reg.nii.gz] -f 1 -s 0 --verbose 1
~~~~

**Comment by SaraDupont** [comment]
Its because I corrected the origin in the header in number of voxel instead of in mm.

**Comment by benjamindeleener** [comment]
Nice!

**Comment by SaraDupont** [comment]
This change gives bad results when padding in the tests of sct_register_multimodal. Is it possible that the origin isn't always in the same unit (vox/mm) ?

**Comment by benjamindeleener** [comment]
No the origin is always in the scanner space, so in mm.

**Comment by SaraDupont** [comment]
OK.
So it's weird that sct_register_multimodal give bad results with the default parameters (the SyN test) with the origin corrected in mm and good results when it was wrongly corrected in voxels...

**Comment by benjamindeleener** [comment]
What is the spacing of the image tested by sct_register_multimodal. Check if each spacing is applied on the correct dimension (but I guess that is not the issue).

**Comment by jcohenadad** [comment]
note: i also noticed the problem when running the test ~2h ago. So i went into test_sct_register_multimodal and removed the 3rd test before integrity (which was just a repetition of test #2).

**Comment by jcohenadad** [comment]
Sara, I checked the output of each step and they are fine (i.e. padding is correct).
I think the problem just comes from a gold-standard image that is not supposed to represent what it should be.

**Comment by SaraDupont** [comment]
For me the gold standard registration result seems good : 
![reg_gold](https://cloud.githubusercontent.com/assets/5857909/10108635/1be59318-6390-11e5-9180-e7e48c02ff7f.gif)


The registration result I had is really bad (and a part of the image in the axial plan is black): 
![reg_bad](https://cloud.githubusercontent.com/assets/5857909/10108685/5599d646-6390-11e5-97ea-f0e3474c6737.gif)

**Comment by jcohenadad** [comment]
what I meant, is that the gold standard was maybe generated using other parameters, e.g., slicereg followed by syn with more iterations.

when i try running syn with iter=1 from step 1 (i.e. after step=0, which is putting src into dest space), i obtain the same result as your 2nd image. I also tried with MI and CC it does not change much.

**Comment by jcohenadad** [comment]
tried padding on RPI image:

with padding of 5x5x3, sct_maths gives:
~~~
qto_xyz:1      -0.840977  -0.000000  -0.518573  13.242122
qto_xyz:2      -0.001869  0.838979  1.311203  -21.478836
qto_xyz:3      -0.024861  -0.063066  17.443102  -78.616394
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
~~~

while c3d gives:
~~~
qto_xyz:1      -0.840977  -0.000000  -0.518573  14.795994
qto_xyz:2      -0.001869  0.838979  1.311203  -25.391268
qto_xyz:3      -0.024861  -0.063066  17.443102  -78.006065
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
~~~

Original qform is:
~~~
qto_xyz:1      -0.840977  -0.000000  -0.518573  9.035391
qto_xyz:2      -0.001869  0.838979  1.311203  -17.272106
qto_xyz:3      -0.024861  -0.063066  17.443102  -26.116396
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
~~~

So I think that padx, pady and padz offset should not simply be added, but must account for the orientation of the volume (i.e., if there is a rotation of theta about y, then padx offest should be multipled by cos(theta)).

**Comment by benjamindeleener** [comment]
Oh. I completely agree... I forgot about that when I talked to Sara but it is true. The angle between each axes must be computed and the padding must be projected onto the axis in order to take the orientation of the image into account. Not so difficult to do.

**Comment by jcohenadad** [comment]
yup... i'm spending my saturday on that. so much fun!

**Comment by jcohenadad** [comment]
i guess there are two approaches:
~~~
T = im.hdr.get_best_affine()
from nibabel import eulerangles
angle_euler = eulerangles.mat2euler(T[0:3, 0:3])
~~~
or
~~~
np.dot(T[0:3, 0:3], Vpadding)
~~~

**Comment by SaraDupont** [comment]
I did it with an approach suggested by Benjamin close to the second one you proposed : 
 ```[new_origin, 1] = np.dot(T,  [-padx, -pady, -padz, 1] ```

But in the testing case of register_multimodal, the registration doesn't seem to do anything with this new version of padding. I'm looking into it.

**Comment by SaraDupont** [comment]
sct_register_multimodal "doing nothing" is due to the shape of the warping field which is 4D instead of 5D (the X, Y, Z component of the warping field must be on the 5th dimension, not on the 4th). 
This is due to the "squeeze" when saving an image, the Image.save() is called in convert(), which is called by the generate_output _file() used to copy the resulting warping fields from the temporary directory to the working directory.

**Comment by jcohenadad** [comment]
good job! well spotted! 
it's sub-efficient to use image.open and save, if the only goal is to move the warping fields... i would suggest to use another approach for the generate_output. Maybe don't use it for the warping fields?

**Comment by SaraDupont** [comment]
Maybe when the files are already in the right format, we can use a simple copy with ```sct.run('cp ...')``` instead of convert() ?

**Comment by jcohenadad** [comment]
or even a move (faster than copy).
i would do that in sct_utils

**Comment by SaraDupont** [comment]
Yes, even better !

**Comment by SaraDupont** [comment]
Done in commit d139b2c

**Comment by jcohenadad** [comment]
I found some other data where the padding fails to provide same physical coordinates:

data: folder_shared/sct_issues/20151026_padding
command:
~~~
sct_image -i seg.nii.gz -pad 0,0,5 -o seg_pad.nii.gz
~~~

**Comment by SaraDupont** [comment]
This is due to an error in the sform im the header of the input file (```seg.nii.gz```) : the z pix dim in the diagonal of the sform is 0.5 instead of 2. When we correct the origin in the header after padding we use ``ìm.hdr.get_best_affine()``` which seems to be the sform. To avoid future issues with the sform, maybe we should use the qform instead. 
Was this image resampled in Z using the old version of ```sct_resample()```?

**Comment by jcohenadad** [comment]
ah! yes you are right. The sform of the seg image is corrupted, so it's normal that the padding doesn't work.

since sct_resample has been fixed, we can now close this issue.
