### ISSUE TITLE
why enabling several outputs?

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#525]

**Comment by jcohenadad** [comment]
ok, maybe this was enable for flag "-mcs"
however, we can simply add _x, _y, _z and create 3 outputs for this particular case.

**Comment by SaraDupont** [comment]
I think we should also use single inputs (since the -omc option will be moved to the new **sct_image** script, see issue #538 )

**Comment by jcohenadad** [comment]
yes i agree

**Comment by SaraDupont** [comment]
It's done on branch **issue538_refactoring/** : ```sct_maths``` now has single inputs and ouputs.
