### ISSUE TITLE
inaccurate registration

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#536]
data: sct_example_data (see batch_processing)

![output_y5rxqc](https://cloud.githubusercontent.com/assets/2482071/10210158/73b34e4e-67b1-11e5-9bfd-26fcc2587dd7.gif)

**Comment by jcohenadad** [comment]
WMseg vs. WMtemplate without GM segmentation (classical approach):
![wmseg_vs_templatewmwithoutgmseg](https://cloud.githubusercontent.com/assets/2482071/10228523/39f0e280-6841-11e5-965f-1d294ab3dc31.gif)

WMseg vs. WMtemplate with GM segmentation (using sct_register_graymatter):
![wmseg_vs_templatewmwithgmseg](https://cloud.githubusercontent.com/assets/2482071/10228534/52d15d02-6841-11e5-8845-e900e4e01231.gif)

WMseg vs. WMtemplate registered with GM segmentation (sct_register_multimodal between WMseg and WM from template):
~~~
sct_register_multimodal -i mt1_wmseg.nii.gz -d label/template/MNI-Poly-AMU_WM.nii.gz -p step=1,algo=slicereg,metric=MeanSquares:step=2,algo=bsplinesyn,metric=MeanSquares,iter=5
~~~
![wmseg_vs_templatewmwithgmsegdirecttransfo](https://cloud.githubusercontent.com/assets/2482071/10228560/778d8aee-6841-11e5-95fd-541f46c1dd81.gif)

Since the later results are better, maybe it is a problem of concatenation?

**Comment by SaraDupont** [comment]
For now we removed sct_register_graymatter (moved to dev/) and use a list of functions in command line instead: 
 - sct_register_multimodal: template registered on T2 --> T2* (or MT) 
 - sct_concat_transfo
 - sct_warp_template
 - sct_segment_graymatter
 - sct_register_multimodal: template WM registered to T2* --> automatic WM segmentation
 - sct_concat_transfo
 - sct_warp_template

See this batch_processing extract as example of pipeline: 

~~~~
# register mt0 on mt1
sct_register_multimodal -i mt0.nii.gz -d mt1.nii.gz -z 3 -m mask_mt1.nii.gz -p step=1,type=im,algo=slicereg,metric=MI:step=2,type=im,algo=bsplinesyn,metric=MeanSquares,iter=3,gradStep=0.2
# compute mtr
sct_compute_mtr -i mt0_reg.nii.gz -j mt1.nii.gz
# register template (in T2 space) to mt1
sct_register_multimodal -i ../t2/template2anat.nii.gz -d mt1.nii.gz -iseg ../t2/t2_seg.nii.gz -dseg mt1_seg.nii.gz -p step=1,type=seg,algo=slicereg,metric=MeanSquares:step=2,type=im,algo=bsplinesyn,metric=MeanSquares,iter=5,shrink=2
# concat transfo
sct_concat_transfo -w ../t2/warp_template2anat.nii.gz,warp_template2anat2mt1.nii.gz -d mt1.nii.gz -o warp_template2mt.nii.gz
# warp template (to get vertebral levels)
sct_warp_template -d mt1.nii.gz -w warp_template2mt.nii.gz
# keep trace of this registration of the template
mv label label_original_reg
# segment GM
sct_segment_graymatter -i mt1.nii.gz -s mt1_seg.nii.gz -l label/template/MNI-Poly-AMU_level.nii.gz 
# register WM template to WMseg
sct_register_multimodal -i label/template/MNI-Poly-AMU_WM.nii.gz -d mt1_wmseg.nii.gz -p step=1,algo=slicereg,metric=MeanSquares:step=2,algo=bsplinesyn,metric=MeanSquares,iter=5
# concat transfo
sct_concat_transfo -w warp_template2mt.nii.gz,warp_MNI-Poly-AMU_WM2mt1_wmseg.nii.gz -d mt1.nii.gz -o warp_template2mt_corrected_wm.nii.gz
# warp template (final warp template for mt1)
sct_warp_template -d mt1.nii.gz -w warp_template2mt_corrected_wm.nii.gz
# check registration result
fslview mt1.nii.gz label/template/MNI-Poly-AMU_T2.nii.gz -b 0,4000 label/template/MNI-Poly-AMU_level.nii.gz -l MGH-Cortical -t 0.5 label/template/MNI-Poly-AMU_GM.nii.gz -l Red-Yellow -b 0.5,1 label/template/MNI-Poly-AMU_WM.nii.gz -l Blue-Lightblue -b 0.5,1 &

~~~~
