### ISSUE TITLE
Command listing SCT tools with brief description

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#537]
For exemple:
`sct list` or `sct tools` or `sct_tools`
would display something like this:

``` bash
sct_propseg                    Robust, fast and automatic spinal cord segmentation
sct_register_to_template       Registration to MNI-Poly-AMU template
sct_warp_template              Warp template on a given image
sct_register_multimodal        Co-registration of two images
etc...
```

Ideally, this script would generate this list automatically so we don't need to update it frequently.
It would use a new field in the parser, containing a short description of each script.

**Comment by zougloub** [comment]
Command list available right now on Sourceforge, will become in `documentation/sphinx/source/command-line.rst`, and it doesn't seem like a concern, so closing.
