### ISSUE TITLE
add flag to display header

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#540]
e.g. `sct_image -i IMAGE.NII.GZ -header`
would output something similar than fslhd in the terminal, in addition to creating a csv file.

**Comment by benjamindeleener** [comment]
Old post, lacking description.

@jcohenadad Is it something like fslhd in order to display image headers?

**Comment by jcohenadad** [comment]
yup!

**Comment by jcohenadad** [comment]
no need for the CSV

**Comment by jcohenadad** [comment]
given that this function will often be used, maybe we could simply the usage by creating a specific CLI: `sct_header`

**Comment by joshuacwnewton** [comment]
If `fslhd` already exists, what is the motivation for replicating that functionality inside SCT?

SCT provides tools specifically for spinal cord analysis, so my fear is that if too many "general MRI analysis" tools are added, then the package might become bloated with features and end up difficult to maintain. (My hope for SCT is to keep it lean and focused -- to do something narrow and to do it well.)

So, if FSLutils is working well enough already, then it might be better to let them handle this functionality instead. (And simply recommend to have FSL installed while developing for SCT, considering its usefulness.)

**Comment by jcohenadad** [comment]
> If fslhd already exists, what is the motivation for replicating that functionality inside SCT?

to remove a 3rd dependency in case we need to be able to inspect an image header. For example, we might want to ask users to give us info on their data header to understand bugs on their end.

> My thought process here is that SCT provides tools specifically for spinal cord analysis. I fear that if too many "general MRI image analysis" tools are added, then the package might become bloated with features, thus requiring us to split our time maintaining lots of different tools. (My hope for SCT, then, is to keep it lean and focused -- to do something narrow and to do it well.)
If the tools from FSLutils are working well enough already, then it might be better to let them handle this functionality instead. (Perhaps we could simply recommend to have FSL installed while developing for SCT, considering its usefulness.)

This is a fair point. How about we discuss it during our internal meeting?

**Comment by joshuacwnewton** [comment]
> to remove a 3rd dependency in case we need to be able to inspect an image header. For example, we might want to ask users to give us info on their data header to understand bugs on their end.

Good point, this use case makes sense. Although... when debugging user concerns, which of the following is more likely to be done?

1. Ask the user to run this new command on their own image, then share the results
2. Ask the user to share their data, then run our own analysis as developers/researchers

I think 2) might be more likely, because once we have their data, we can check many things at once (without having to converse back and forth). In that case, FSL might be sufficient?

**Comment by joshuacwnewton** [comment]
> How about we discuss it during our internal meeting?

The only trouble is getting everyone up to speed quickly. Personally, I find it hard to explain the context during a meeting, so that people will understand what's being talked about. Normally I find it easier to discuss some things offline, so people have the time/space to read. :sweat_smile:

**Comment by mpompolas** [comment]
> Ask the user to share their data, then run our own analysis as developers/researchers


This is the issue we run across with the data from NeuroRx: inspecting the header would be useful when data can't be shared with us (I assume that headers are ok to share even with GDPR regulations - this needs confirmation)

**Comment by joshuacwnewton** [comment]
Thanks for taking the time to elaborate! Both of your points make perfect sense. :smile:

**Comment by joshuacwnewton** [comment]
I've just learned of @lrouhier's open branch [`lr/display_header`](https://github.com/neuropoly/spinalcordtoolbox/compare/lr/display_header) for this issue, so I'm mentioning it here.

**Comment by joshuacwnewton** [comment]
> I've just learned of @lrouhier's open branch [`lr/display_header`](https://github.com/neuropoly/spinalcordtoolbox/compare/lr/display_header) for this issue, so I'm mentioning it here.

<details>
<summary> Here is the current output of lr/display_header (i.e. the output of <code>print(Image.hdr)</code>) </summary>

```
--
Spinal Cord Toolbox (git-lr/display_header-9ff8c695eda592067b3f3afd2a208e08dcda35eb)

sct_image -i t1w-converted.nii.gz -header
--

pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [ 3 42 76 77  0  0  0  0]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'mnc2nii t1w.mnc.gz t1w-converted.nii'
aux_file        : b''
qform_code      : unknown
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : 0.0
qoffset_y       : 0.0
qoffset_z       : 0.0
srow_x          : [  1.         0.         0.       -31.219284]
srow_y          : [  0.         1.         0.       -36.213394]
srow_z          : [  0.        0.        1.      -21.32167]
intent_name     : b''
magic           : b'n+1'
```
</details>

<details>
<summary> And here is the output of <code>fslhd</code> </summary>

```
filename	t1w-converted.nii.gz

sizeof_hdr	348
data_type	FLOAT32
dim0		3
dim1		42
dim2		76
dim3		77
dim4		0
dim5		0
dim6		0
dim7		0
vox_units	mm
time_units	Unknown
datatype	16
nbyper		4
bitpix		32
pixdim0		0.000000
pixdim1		1.000000
pixdim2		1.000000
pixdim3		1.000000
pixdim4		0.000000
pixdim5		0.000000
pixdim6		0.000000
pixdim7		0.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	0.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name	
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Unknown
qform_code	0
qto_xyz:1	1.000000 0.000000 0.000000 0.000000 
qto_xyz:2	0.000000 1.000000 0.000000 0.000000 
qto_xyz:3	0.000000 0.000000 1.000000 0.000000 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Unknown
sform_code	1
sto_xyz:1	1.000000 0.000000 0.000000 -31.219284 
sto_xyz:2	0.000000 1.000000 0.000000 -36.213394 
sto_xyz:3	0.000000 0.000000 1.000000 -21.321671 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		mnc2nii t1w.mnc.gz t1w-converted.nii
aux_file	
```

</details>

Hrmm. The information seems to be mostly the same. But, because it's organized differently, I find `print(header)` to be harder to read. Plus, there seems to be some information missing, such as the qform matrix and the text orientation labels (e.g. Left-to-Right, Posterior-to-Anterior.)

I'd like to try and replicate fslhd exactly, just because it would allow us to more easily compare the output between `fslhd` and `sct_display_header` (e.g. using a diff tool). But, this could also be an opportunity to add fields if there is new information we want to display. 

Do you have any opinions about output formatting, @jcohenadad?

**Comment by jcohenadad** [comment]
> I'd like to try and replicate fslhd exactly, just because it would allow us to more easily compare the output between fslhd and sct_display_header (e.g. using a diff tool). But, this could also be an opportunity to add fields if there is new information we want to display.

👍   Please be aware that FSL's output might depend (I have not verified this) on the [NIFTI version](https://nipy.org/nibabel/nifti_images.html#the-nifti-header) (1 vs 2)

**Comment by joshuacwnewton** [comment]
> given that this function will often be used, maybe we could simply the usage by creating a specific CLI: `sct_header`

One other benefit to this is that it allows us to group other header-related utilities, such as validating the header and fixing header issues. (See: https://github.com/neuropoly/spinalcordtoolbox/issues/3283#issuecomment-806861977)
