### ISSUE TITLE
if -init-centerline is mask, can cause problems

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#544]
also doesn't work if mask is binary, linear or spline-interpolated. 

data:
~~~
sct_example_data/mt
~~~

see below result:

Using mask:
~~~
sct_register_multimodal -i ../t2/t2_seg.nii.gz -d mt1.nii.gz -p step=1,iter=0 -x nn
sct_propseg -i mt1.nii.gz -t t2 -init-centerline t2_seg_reg.nii.gz
~~~

![screen shot 2015-10-02 at 12 35 31](https://cloud.githubusercontent.com/assets/2482071/10251928/3273952c-6902-11e5-937b-58fe6f624e7c.png)

Using centerline from mask:
~~~
sct_register_multimodal -i ../t2/t2_seg.nii.gz -d mt1.nii.gz -p step=1,iter=0 -x nn
sct_process_segmentation -i t2_seg_reg.nii.gz -p centerline -o t2_seg_reg_centerline.nii.gz
sct_propseg -i mt1.nii.gz -t t2 -init-centerline t2_seg_reg_centerline.nii.gz
~~~
![screen shot 2015-10-02 at 12 36 12](https://cloud.githubusercontent.com/assets/2482071/10251934/3a38d38a-6902-11e5-9945-8290db939614.png)

**Comment by benjamindeleener** [comment]
To do: in the wrapper of sct_propseg.py, transform the mask provided into a centerline.

**Comment by jcohenadad** [comment]
Issue is reopened due to issue #673.

After fixing this issue, please add a test for propseg with centerline.
