### ISSUE TITLE
integrity issue

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#554]
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/83375254

**Comment by SaraDupont** [comment]
It's because I updated the level label file in the testing dataset. It should be fine now.

**Comment by jcohenadad** [comment]
problem still there
https://travis-ci.org/neuropoly/spinalcordtoolbox/builds

**Comment by SaraDupont** [comment]
What about now ?

**Comment by jcohenadad** [comment]
Working :-)
