### ISSUE TITLE
BUG during sct_register_to_template: bad registration of the labels

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#569]
Data available here: /Volumes/folder_shared/sct_issues/20151008_london_sub2

Command line: `sct_register_to_template -i t2.nii.gz -l labels.nii.gz -s t2_seg.nii.gz -p step=1,type=seg,algo=slicereg:step=2,type=seg,algo=bsplinesyn,iter=5,shrink=2:step=3,type=seg,algo=syn,iter=3,shrink=1`

-----------------------

The bug seems to occur during registration of labels template <--> straigth2templateAffine at this step:
[...]
`Remove labels that do not correspond with each others.
sct_label_utils -t remove-symm -i landmarks_rpi_cross3x3_straight.nii.gz -o landmarks_rpi_cross3x3_straight.nii.gz,template_label_cross.nii.gz -r template_label_cross.nii.gz`

`Estimate affine transfo: straight anat --> template (landmark-based)...`

`Computing rigid transformation (algo=translation-scaling-z) ...`
[..]

![screen shot 2015-10-08 at 7 22 18 pm](https://cloud.githubusercontent.com/assets/7769691/10382601/a6e446c2-6df3-11e5-8e52-ae2985063e71.png)
![screen shot 2015-10-08 at 7 27 08 pm](https://cloud.githubusercontent.com/assets/7769691/10382603/a6e4ab1c-6df3-11e5-85e8-5288afb330d3.png)
![screen shot 2015-10-08 at 7 28 23 pm](https://cloud.githubusercontent.com/assets/7769691/10382602/a6e45888-6df3-11e5-921a-b443f9ae657c.png)

**Comment by slevyrosetti** [comment]
The bug seems to be the same with subject 3 from London, see result on screenshots below. (Ask me if you need the data).
![screen shot 2015-10-09 at 11 43 36 am](https://cloud.githubusercontent.com/assets/7769691/10398486/51aa1a0a-6e7b-11e5-8e97-1a103b5ae9a2.png)
![screen shot 2015-10-09 at 11 43 41 am](https://cloud.githubusercontent.com/assets/7769691/10398487/51ab37be-6e7b-11e5-9a7b-d8c097f3e9d9.png)

**Comment by jcohenadad** [comment]
My suggestion would be to simply replace the following lines:
~~~
    # Estimate affine transfo: straight --> template (landmark-based)'
    sct.printv('\nEstimate affine transfo: straight anat --> template (landmark-based)...', verbose)
    # converting landmarks straight and curved to physical coordinates
    image_straight = Image('landmarks_rpi_cross3x3_straight.nii.gz')
    landmark_straight = image_straight.getNonZeroCoordinates(sorting='value')
    image_template = Image('template_label_cross.nii.gz')
    landmark_template = image_template.getNonZeroCoordinates(sorting='value')
    # Reorganize landmarks
    points_fixed, points_moving = [], []
    landmark_straight_mean = []
    for coord in landmark_straight:
        if coord.value not in [c.value for c in landmark_straight_mean]:
            temp_landmark = coord
            temp_number = 1
            for other_coord in landmark_straight:
                if coord.hasEqualValue(other_coord) and coord != other_coord:
                    temp_landmark += other_coord
                    temp_number += 1
            landmark_straight_mean.append(temp_landmark / temp_number)

    for coord in landmark_straight_mean:
        point_straight = image_straight.transfo_pix2phys([[coord.x, coord.y, coord.z]])
        points_moving.append([point_straight[0][0], point_straight[0][1], point_straight[0][2]])
    for coord in landmark_template:
        point_template = image_template.transfo_pix2phys([[coord.x, coord.y, coord.z]])
        points_fixed.append([point_template[0][0], point_template[0][1], point_template[0][2]])

    # Register curved landmarks on straight landmarks based on python implementation
    sct.printv('\nComputing rigid transformation (algo=translation-scaling-z) ...', verbose)
    import msct_register_landmarks
    (rotation_matrix, translation_array, points_moving_reg, points_moving_barycenter) = \
        msct_register_landmarks.getRigidTransformFromLandmarks(
            points_fixed, points_moving, constraints='translation-scaling-z', show=False)

    # writing rigid transformation file
    text_file = open("straight2templateAffine.txt", "w")
    text_file.write("#Insight Transform File V1.0\n")
    text_file.write("#Transform 0\n")
    text_file.write("Transform: FixedCenterOfRotationAffineTransform_double_3_3\n")
    text_file.write("Parameters: %.9f %.9f %.9f %.9f %.9f %.9f %.9f %.9f %.9f %.9f %.9f %.9f\n" % (
        1.0/rotation_matrix[0, 0], rotation_matrix[0, 1],     rotation_matrix[0, 2],
        rotation_matrix[1, 0],     1.0/rotation_matrix[1, 1], rotation_matrix[1, 2],
        rotation_matrix[2, 0],     rotation_matrix[2, 1],     1.0/rotation_matrix[2, 2],
        translation_array[0, 0],   translation_array[0, 1],   -translation_array[0, 2]))
    text_file.write("FixedParameters: %.9f %.9f %.9f\n" % (points_moving_barycenter[0],
                                                           points_moving_barycenter[1],
                                                           points_moving_barycenter[2]))
    text_file.close()
~~~
with: ``isct_ANTSUseLandmarkImagesToGetAffineTransform``

**Comment by benjamindeleener** [comment]
I agree, but it is just a temporary solution. ```isct_ANTSUseLandmarkImagesToGetAffineTransform``` computes an affine transform while the bunch of code I did computes a translation + z-scaling that is more specific and provides better results for large datasets.

**Comment by jcohenadad** [comment]
I just pushed the temporary fix to dev.
@slevyrosetti: could you please check if this fix solves your issue?  In the meantime, Benjamin is working on a better solution.

**Comment by slevyrosetti** [comment]
Ok, I'll try, I'll let you know.
Le 2015-10-09 13:18, "Julien Cohen-Adad" <notifications@github.com> a
écrit :

**Comment by slevyrosetti** [comment]
The bug is fixed (see screenshots below). Good job!
![screenshot](https://cloud.githubusercontent.com/assets/7769691/10405914/60dc60e4-6eaa-11e5-85fb-4426aa6e4188.png)
![screenshot2](https://cloud.githubusercontent.com/assets/7769691/10405915/60dc672e-6eaa-11e5-96ef-4ac9c58402db.png)

**Comment by jcohenadad** [comment]
let's keep that open and wait for Benjamin's solution (more elegant and accurate)

**Comment by benjamindeleener** [comment]
I ran some tests on a small dataset (5 subjects, T2w) for the two versions of sct_register_to_template. No bug such as reported above occured.
Results are slightly more accurate with old version of code (rotation + scaling in z) than new code (affine with ants).
Note: errsm_09 has a bad manual segmentation...

Rotation + z-scaling:
```
Results for "sct_register_to_template ":
Dataset: /Users/benjamindeleener/data/data_testing/original_data/small_C2-T2/
          dice_anat2template  dice_template2anat     status
subject                                                    
errsm_05            0.899150            0.903644   0.000000
errsm_09            0.891242            0.898611   0.000000
errsm_10            0.801188            0.786739  99.000000
errsm_11            0.900656            0.907773   0.000000
errsm_12            0.885495            0.905524   0.000000
Mean                0.875546            0.880458  19.800000
STD                 0.042018            0.052499  44.274146

Passed: 4/5
```

Affine:
```
Results for "sct_register_to_template ":
Dataset: /Users/benjamindeleener/data/data_testing/original_data/small_C2-T2/
          dice_anat2template  dice_template2anat     status
subject                                                    
errsm_05            0.904077            0.922841   0.000000
errsm_09            0.877543            0.885677   0.000000
errsm_10            0.796070            0.769586  99.000000
errsm_11            0.898320            0.908322   0.000000
errsm_12            0.894662            0.908535   0.000000
Mean                0.874134            0.878992  19.800000
STD                 0.044745            0.062590  44.274146

Passed: 4/5
```

I'll fix the bug and run more tests.

**Comment by benjamindeleener** [comment]
I found the issue. It came from sct_straighten_spinalcord and the space of landmarks. The landmark space is the same as the input image. So, if the input image as an orientation (and origin), the straightened image will have the same orientation and origin. Then, the required transformation between straight space and template is an affine transform.

Forcing the landmark space to be empty (orientation 1 0 0 0 1 0 0 0 1 and null origin) would fix the issue and simplify the computation of the transformation.

**Comment by benjamindeleener** [comment]
Finally, I kept the header from the image but I've changed the orientation so that the straightened spinal cord is straight in the scanner space, but keeps the same origin as the input image.

**Comment by jcohenadad** [comment]
sounds good :+1:

**Comment by jcohenadad** [comment]
New approach to be implemented:
- [ ] create cross after applying straightening to labels
- [ ] try to use ``msct_register_landmarks`` with fixed parameter in voxel space
- [ ] replace ``isct_ANTSUseLandmarkImagesToGetAffineTransform`` with ``msct_register_landmarks``
- [ ] use float labels (i.e., do not write/read labels, except in verbose=2 mode)

Advantages of using ``msct_register_landmarks`` with translation only + z-scaling are:
- if user positions badly labels in cross-sectional plane, this will result in spurious rotations
- better accuracy if using float
- can remove the binary from ANTs

**Comment by benjamindeleener** [comment]
I've done all that. Registration to the template works on a bunch of images. I will launch a full test this evening before merging to master.

**Comment by benjamindeleener** [comment]
We even gained some time (180 sec instead of 220 sec on one subject)!

**Comment by benjamindeleener** [comment]
It needs to be checked in all scripts but ``isct_ANTSUseLandmarkImagesToGetAffineTransform`` is not necessary anymore. We can remove it from bin/ folder.

**Comment by benjamindeleener** [comment]
I have an inversion of the result for some subjects.

**Comment by jcohenadad** [comment]
Ah shit... It means more debugging
Good thing that you tested on a large dataset

**Comment by benjamindeleener** [comment]
Ok I just needed to sort labels after computing the crosses on each image. Still need to run large tests.

**Comment by benjamindeleener** [comment]
This is fixed.
