### ISSUE TITLE
sct_warp_template: Incorrect command line specification

### ISSUE THREAD

**Issue by nguyen1j** [neuropoly/spinalcordtoolbox#571]
thanh@beep:/data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/sct_example_data/t2$ sct_warp_template -d t2.nii.gz -w warp_template2anat.nii.gz  OK: t2.nii.gz
  OK: warp_template2anat.nii.gz

Check parameters:
  Destination image ........ t2.nii.gz
  Warping field ............ warp_template2anat.nii.gz
  Path template ............ /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/
  Output folder ............ label/

rm -rf label/
mkdir label/

Read label file...
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/info_label.txt
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_T2.nii.gz
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_cord.nii.gz
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_CSF.nii.gz
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_WM.nii.gz
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_GM.nii.gz
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_level.nii.gz
mkdir label/template/
sct_apply_transfo -i /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_T2.nii.gz -o label/template/MNI-Poly-AMU_T2.nii.gz -d t2.nii.gz -w warp_template2anat.nii.gz -x linear

Parse list of warping fields...
  Transfo #0: warp_template2anat.nii.gz

Check file existence...
  OK: /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_T2.nii.gz
  OK: t2.nii.gz
  OK: warp_template2anat.nii.gz

Get dimensions of data...
  120 x 120 x 600 x 1

Apply transformation...
isct_antsApplyTransforms -d 3 -i /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_T2.nii.gz -o label/template/MNI-Poly-AMU_T2.nii.gz -t warp_template2anat.nii.gz -r t2.nii.gz -n Linear
terminate called after throwing an instance of 'itk::ExceptionObject'
what():  /home/brain/ANTs/Utilities/antsCommandLineParser.cxx:297:
itk::ERROR: CommandLineParser(0x3ebadd0): Incorrect command line specification. /data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/data/template/MNI-Poly-AMU_T2.nii.gz
/data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/scripts/sct_utils.py, line 90
/data/RnD/Thanh/spinalcord2.1[2015-10-05]/spinalcordtoolbox_v2.1_beta8_linux/build/scripts/sct_utils.py, line 90

**Comment by jcohenadad** [comment]
Hi Thanh,

did you install SCT using ``installer.py`` directly from the package?

I can see you are running the batch_processing inside SCT installation. While I don't think this should cause any problem, I would leave SCT installation untouched, and run your scripts in a separate folder. Example:
/code/spinalcordtoolbox/ --> untouched
/data/sct_example_data --> where you do your processing.

cheers
julien

**Comment by nguyen1j** [comment]
Hi Julien,

Thank you very much for your suggestions. The problems caused by using "-" in my command line. Replacing "spinalcord2.1[2015-10-05]" by "spinalcord2.1[2015_10_05]" will fix this issue.


Thanks again and have a great day.

Thanh.
