### ISSUE TITLE
Template registration should allow registration of images with small coverage

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#574]
Especially for images that do not cover two vertebral levels and for which it is not possible to provide two labels. See related discussion here: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/d93860bf/?limit=25#5d76

This issue could be easily fixed. Indeed, the reason why we want two labels is to compute an affine transformation in order to pre-register the vertebral levels. For images with small coverage, such a pre-registration is not necessary as it wouldn't affect much the images. Therefore, only one label (for exemple, on the inter-vertebral disk) would be necessary.

**Comment by benjamindeleener** [comment]
The solution would be to replace the affine transform by a translation computed between the inter-vertebral disk label provided by the user and the corresponding label in the template. Ideally, we would need to create new labels in the template space for inter-vertebral disks. However, we can also use the middle position between the two surrounding vertebral labels.

**Comment by benjamindeleener** [comment]
I've put some data on sct_issue: ```20151011_issue_574```

**Comment by jcohenadad** [comment]
working on it:
https://github.com/neuropoly/spinalcordtoolbox/tree/jca_issue574

**Comment by jcohenadad** [comment]
fixed in https://github.com/neuropoly/spinalcordtoolbox/pull/1451
it is now possible to register with only one label centered on a disc (use flag `-ldisc`)
