### ISSUE TITLE
get_centerline with a point : output too many files

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#582]
```sct_get_centerline``` with method point and default parameters outputs more than 3000 files(!) and cannot open them. 

Path to data: /Volumes/folder_shared/sdupont/2015-10-08-ismrm_abstract/pain_data/d_sp_pain_01/t2 
Command used: ```sct_get_centerline -i t2.nii.gz -method point -p t2_point.nii.gz````
Temporary fiels in folder : tmp.151014123348
Error: 
![get_centerline_point_error](https://cloud.githubusercontent.com/assets/5857909/10490887/784d7af4-7271-11e5-80d1-43c6128b99f5.png)

**Comment by SaraDupont** [comment]
Same error with a larger gap between slices (-g 10 and -g 50)

**Comment by jcohenadad** [comment]
function does not exist anymore
