### ISSUE TITLE
C2 mid-vertebral level labeling too low

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#583]
![screen shot 2015-10-14 at 3 46 05 pm](https://cloud.githubusercontent.com/assets/7769691/10495618/c1480ddc-728a-11e5-9fff-9d88cb8c9718.png)
![screen shot 2015-10-14 at 3 46 16 pm](https://cloud.githubusercontent.com/assets/7769691/10495619/c14964a2-728a-11e5-90cf-f4da7cac0c57.png)

Data: 
/Volumes/folder_shared/sct_issues/20151014_583_and_584
Command line:
`sct_label_vertebrae -i t2.nii.gz -seg t2_seg.nii.gz -initcenter 2`
`sct_label_utils -i t2_seg_labeled.nii.gz -t label-vertebrae -level 2,6`

**Comment by jcohenadad** [comment]
what subject is it? i'll add it to the extensive dataset for testing.

**Comment by slevyrosetti** [comment]
Subject: vanderbilt, subject5

**Comment by jcohenadad** [comment]
related to #515
