### ISSUE TITLE
Bad labeling of the vertebral levels

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#585]
Data: /Volumes/folder_shared/sct_issues/20151015_585 (subject sct_002)
Command line:
~~~~~
sct_label_vertebrae -i t2.nii.gz -seg t2_seg.nii.gz -initcenter 2
~~~~~
![screen shot 2015-10-14 at 4 45 35 pm](https://cloud.githubusercontent.com/assets/7769691/10497356/54ec1b52-7293-11e5-8dc3-1f12042c0980.png)

**Comment by jcohenadad** [comment]
i just noticed that the center is not at C2/C3 disc, but slightly above:
![screen shot 2015-10-14 at 18 08 41](https://cloud.githubusercontent.com/assets/2482071/10499495/a5dadf7a-729e-11e5-878e-fdd8de275281.png)

The method is very sensitive to the initialization. It works with:
~~~
sct_label_vertebrae -i t2.nii.gz -seg t2_seg.nii.gz -initz 186,2
~~~
