### ISSUE TITLE
sct_get_centerline: add QC

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#589]
for method=auto only

**Comment by SaraDupont** [comment]
Use function ```save_quality_control()``` from ```msct_image.Image```.  Several options: 
- choose the plane: 'sagittal' (default), 'coronal', or 'axial' 
- output only one slice or several slices in the same png image (set n_slices, if n_slices=1, the slice is the middle one)
- output only one png image with "raw" image or two png images: one raw, one with a segmentation added to the image in transparency (as in fslview)
- if there is a segmentation: 
  - several color maps are available : 'red', 'red-yellow' or 'blue-cyan'
  - threshold for probabilistic segmentations (values below thr are set to zero)

**Comment by jcohenadad** [comment]
Isolated use case. Will not implement unless inquired by several users.
