### ISSUE TITLE
WM atlas: make it a single file for faster warping?

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#602]
currently the WM atlas has 37 nifti separated files in it-- when apply sct_warp_template, each file is warped-- there is a lot of i/o which could be avoided if the atlas would be a single file.

however this is tricky because currently isct_apply_transfo (from ANTs) only accepts 3d (not 4d) files...  so, discussion is open...

**Comment by abtahizadeh** [comment]
@jcohenadad 
Missing description, perhaps deprecated?

**Comment by jcohenadad** [comment]
@abtahizadeh comments added-- not deprecated
