### ISSUE TITLE
sct_image: set_orientation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#605]
- function is extremely confusing. For example: what is im: fname? object? please use convention for variable name.
- Should not create fname automatically.
- when setting "-o", two outputs are given.
- please comment the code!
- we need to discuss the function to find consensual approach before doing any modification.

**Comment by tanguyduval** [comment]
I don't know what is the status of this issue. but I confirm, when setting "-o", two outputs are given

**Comment by joshuacwnewton** [comment]
I believe this was fixed by #1944 but not closed. `set_orientation` is not present in the SCT codebase, and we use `change_orientation` everywhere. Closing.
