### ISSUE TITLE
CPU number automatically set to 0

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#606]
line 349: ``self.cpu_number = 0``

@benjamindeleener: is that normal?

**Comment by benjamindeleener** [comment]
No problem with that: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L538

It is simply that when set to zero, we do not use multiprocessing for landmark computation. Slightly slower, but not much.

**Comment by jcohenadad** [comment]
i know this is different from issue #584, all i'm saying is that the variable seems to be set at 0 all the time.

**Comment by benjamindeleener** [comment]
Yes it could be set to the maximum number of cpu by default.

**Comment by jcohenadad** [comment]
well, i'm running in debug mode, without having set -cpu-nb, and my value cpu_number=0.

**Comment by jcohenadad** [comment]
actually i find that setting ``-cpu-nb 8`` brings a nice boost!

**Comment by benjamindeleener** [comment]
Nice! Do you have an exemple of time improvement?

**Comment by jcohenadad** [comment]
about factor 8!... but only in the landmark creation process. So as you said, at the end there is no much difference. Maybe ~10%.
