### ISSUE TITLE
Straightening + Affine changes integrity of spinal cord shape

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#617]
This issue was found after having observed shrinkage of spinal cord on some data (200_005_s2). What is shown below, is:
- data
- data-->affine-->curve2straight-->straight2curve-->inv_affine-->data
![output_vkd9pe](https://cloud.githubusercontent.com/assets/2482071/10698257/1eebd910-797e-11e5-81f1-808df3298e59.gif)

**Comment by benjamindeleener** [comment]
Wow... That is not good. This is probably due to the BSpline deformation model of the straightening process. We definitively need to change the deformation model.

A "quick" solution would be to modify the position of landmarks along the spinal cord or to add landmarks closer to the spinal cord so that the deformation model has to satisfy these conditions. Actually, higher is the number of landmarks and more dense are the landmarks position, the better will be the integrity of the registration.

**Comment by jcohenadad** [comment]
Reducing gapxy introduced another "very big" deformation:
![output_mgfr8s](https://cloud.githubusercontent.com/assets/2482071/10701028/9782470e-798f-11e5-8a04-995d116f0576.gif)

**Comment by jcohenadad** [comment]
arg!!! it's a problem of mesh size (again!). With 3x3x5, it looks beautiful:
![output_twttr0](https://cloud.githubusercontent.com/assets/2482071/10701174/552e2494-7990-11e5-86d9-f9c1a9f19983.gif)

**Comment by benjamindeleener** [comment]
Nice result. I hope thin-plate interpolation would remove this dependence to an option.

**Comment by jcohenadad** [comment]
should we set 3x3x5 for the next beta? maybe we can set it and run the extensive testing

**Comment by benjamindeleener** [comment]
Let's try on an extensive dataset first.

**Comment by jcohenadad** [comment]
i'm working on it

**Comment by jcohenadad** [comment]
is there an easy way to set nb-cpu=0 from the test function?  there is no flag for that.

**Comment by benjamindeleener** [comment]
Actually, no. We need to change in a similar way of sct_straighten_spinalcord:
https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L582

**Comment by jcohenadad** [comment]
no need to do that because multithreading is not used in register_to_template-- it is just used in straighten_spinalcord which is called by register_to_template, so we can just add a flag, right?

**Comment by benjamindeleener** [comment]
I am not sure to understand. ```isct_test_function``` will always test function on subjects in a multiprocessing fashion (even on one core), except if you tell it not to do it (by changing the code and not calling multiprocessing.Pool). ```sct_straighten_spinalcord``` has this feature and I need to implement it for ```isct_test_function```.

**Comment by jcohenadad** [comment]
my understanding of the problem, is that currently, both isct_test_function and sct_straighten_spinalcord use multithreading (by default). This seems to be creating errors. So my suggestino was to add a flag to register_to_template, to force cpu-nb=0, so that when we call isct_test_function test_sct_register_to_template, there is no crashing.

**Comment by benjamindeleener** [comment]
Hooo I understand now. Yes, it is possible and should definitely be done. I can do it quickly if you're not doing it. Are you working on master or on a specific branch?

**Comment by jcohenadad** [comment]
already done.

**Comment by jcohenadad** [comment]
results from extensive data (C2-T2):
~~~
Mean                0.919867            0.930437       0
STD                 0.013961            0.019939       0
Passed: 24/25
~~~

so i changed the default to 3x3x5.

**Comment by jcohenadad** [comment]
there are still issues on some dataset. Example below (200_005_s2):
1. data
2. data-->affine-->curve2straight-->straight2curve-->inv_affine-->data
3. template --> data (better registered on 2. versus 1.)

![output_uhjvra](https://cloud.githubusercontent.com/assets/2482071/10711467/0c9e4834-7a4a-11e5-9e6a-492d6d71e18d.gif)

**Comment by jcohenadad** [comment]
we should change the approach, and use thin-plate splines.

**Comment by benjamindeleener** [comment]
Fixed with the new straightening method.
