### ISSUE TITLE
the affine transformation sometimes switches the labels upside down

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#632]
data: sct_testing/small/20151026_emil
commit: cf222159f53323d1a1d3c6dd2bee58f948b7a8ef
command in debugger: -i t2.nii.gz -s t2_seg.nii.gz -l labels.nii.gz -r 0 -v 2

result transfo matrix (the -1 is suspicious):
~~~
[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.         -1.08571429]
~~~
result plots of moving/fix points:
![screen shot 2015-10-26 at 15 32 04](https://cloud.githubusercontent.com/assets/2482071/10740115/c2365008-7bf6-11e5-8809-1a02705bd174.png)

the two labels switched (2 register to 3 and 3 registered to 2):
![screen shot 2015-10-26 at 15 26 17](https://cloud.githubusercontent.com/assets/2482071/10740104/b27ab168-7bf6-11e5-94c1-81a810db01d0.png)

**Comment by benjamindeleener** [comment]
The issue came from the sorting of value when extracting coordinates of labels.

Now, the transformation is correct:
```
[[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.          1.08786251]]
```

**Comment by benjamindeleener** [comment]
Was still bugging on other dataset. Now fixed.
