### ISSUE TITLE
check if modification in sct_imaging -pad changed quality of registration  

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#647]
visually compare registration results of ``sct_testing -f sct_register_multimodal`` between:
- OLD: 263b0528f594d5df4d85e10e955801aeb93c118b
- NEW: d75201da036f6001399d3e11dd829b2e020d633d

**Comment by SaraDupont** [comment]
The testing function of ```sct_register_multimodal``` tests the algos slicereg and syn. 
  - Slicereg results are exactly identical with old and new version. 
  - Syn results are not identical but visually there is no difference (see gif below): 
    - shape is 40x40x5 (8000 voxels)
    - headers are identical
    - intensity values range from 5 to 860
    - maximum difference is 0.2 
    - sum of difference is 4.15
    - average difference per voxel is 5e-4

I think we can consider it identical and keep a threshold at 1e-3 per voxel in the integrity check of ```sct_testing -f sct_register_multimodal```

See the intensity value on the bottom left corner : here the difference is 0.004
![diff](https://cloud.githubusercontent.com/assets/5857909/10887744/a777d466-8156-11e5-8438-6defe5ac76b2.gif)

**Comment by jcohenadad** [comment]
agreed. Thanks for checking.
