### ISSUE TITLE
Saving png image on Travis is failing

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#649]
Probably an issue with Qt/Matplotlib libraries that are not supported when running script in non-gui environment.

https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/88415456

Checking if ```plt.imshow(sagittal_slice, cmap=cm.gray, interpolation='nearest')``` is working should be enough to fix this issue.

**Comment by jcohenadad** [comment]
is that high priority if we can set qc=0?

**Comment by benjamindeleener** [comment]
No we can change it.

**Comment by SaraDupont** [comment]
I added a try except where matplotlib.pyplot is called: it shouldn't happend anymore.
