### ISSUE TITLE
sct_process_segmentation: CSA averaging across vertebral levels is biased towards high values

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#663]
Change the way to compute CSA across vertebral levels. Currently, an average of the voxels inside the segmentation mask over the CSA volume is performed. Hence, it includes more voxels of high CSA value (since slices of high CSA include more voxels) and less with lower values.

Solution: find the slices corresponding to the selected vertebral levels in the output .txt file and perform an average of the CSA of these slices.

**Comment by jcohenadad** [comment]
I don't understand the description of this issue

**Comment by jcohenadad** [comment]
ok i got it-- the "CSA volume" consists of voxels inside the spinal cord, with values corresponding to CSA.
therefore the method consisting in averaging the "CSA volume" per vertebral level upward bias CSA. I agree this is an issue.

So I see two options:
1) not using sct_extract_metric
2) creating a temporary "CSA volume" which is weighted for CSA per slice, only when the option "-l" is used

**Comment by slevyrosetti** [comment]
Fixed in commit #a279187 on branch sl_issue_663.

**Comment by slevyrosetti** [comment]
Tests were run successfully.

**Comment by jcohenadad** [comment]
could you please explain briefly what you did?  just to keep track.
thanks

**Comment by jcohenadad** [comment]
ok, I just noticed that the flag "-t <path_template> " changed for "-t <vertebral_labeling_file> ".

We really need to try to avoid as much as possible changing things that break backward compatibility. Here, for user that already have their batch scripts, this is not going to work anymore. How about keeping the same flag/input?

**Comment by slevyrosetti** [comment]
This is not a problem to keep the same flag (just a few more code lines to add) but some sct developers told me that it was annoying not to be able to run the script with a file name different from "MNI-Poly-AMU_level.nii.gz" for the vertebral labeling file. Indeed, it reduces the number of possible uses of the functions (notably in other scripts or situations).
Maybe I can try to integrate both possibilities.
Let me know what you prefer.

**Comment by slevyrosetti** [comment]
To briefly sum up what I implemented:
- if slices or vertebral levels were selected:
   - if vertebral levels were selected, get the slices corresponding to the vertebral levels
   - then, get the CSA estimated for each one of these slices based on the file csa.txt that was output before
   - compute the mean (and std) across these values
   - output the result and write it in a file

**Comment by jcohenadad** [comment]
ok your implementation looks great :+1: 

regarding the flag: how about keeping your approach (input file instead of folder) but making a default mode, which is ``label/template/MNI-Poly-AMU_vert.nii.gz``

**Comment by slevyrosetti** [comment]
Yes, exactly! That's what I did.
So I just need to modify the testing and we will be ready to merge.

**Comment by slevyrosetti** [comment]
The testing is now up-to-date. The branch sl_issue_663 can be merged to master. The issues #663 and #667 are fixed.
