### ISSUE TITLE
add z-rotation for improved accuracy

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#666]
in some cases, e.g., CSM patients where the cord is extremely compressed (ovaloid shape) and rotated (sometimes >30°), the registration is poorly accurate, resulting in wrong warping of GM and WM. We should add rotation information, based on the larger axis of the cord eccentricity. But be aware of almost-circular shapes.

**Comment by benjamindeleener** [comment]
I will work on that in the next weeks. I mean integrating affine transform (rotation and scaling) in registration to the template.

**Comment by benjamindeleener** [comment]
Done by @jcohenadad in new sct_register_to_template, option `centermassrot`. Still need improvements.
