### ISSUE TITLE
add feature to estimate CSA based on labels

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#667]
example: CSA of dorsal column, etc.

**Comment by slevyrosetti** [comment]
I'm on it (see issue #663 ).

**Comment by jcohenadad** [comment]
no, we should not binarize labels otherwise we loose accuracy. We should do weighted sum of voxel counting.  My suggestion is go through ``sct_process_segmentation``. The use would do e.g.:

    sct_process_segmentation -i label/template/MNI-Poly-AMU_WM.nii.gz -p csa -l 2:3

**Comment by slevyrosetti** [comment]
It doesn't make sense to compute the CSA on the file label/template/MNI-Poly-AMU_WM.nii.gz since it is a probabilistic map but it does make sense to do it on WM atlas labels since they are fractional volume map. It works well on branch sl_issue_663.
To compute it on the whole WM, sum the WM atlas labels 0 to 29.

**Comment by slevyrosetti** [comment]
Issue will be fixed when branch sl_issue_663 will be merged to master.

**Comment by jcohenadad** [comment]
i tried to use the feature but no success-- could you please give an example how to compute CSA in dorsal column (4 tracts)?

**Comment by slevyrosetti** [comment]
Here is an example of how to compute the CSA across vertebral levels C2 to C5:
`sct_process_segmentation -i dorsal_columns.nii.gz -p csa -l 2:5 -t label/template/MNI-Poly-AMU_level.nii.gz`

Terminal window output:
~~~
OK: dorsal_columns.nii.gz

Check parameters:
.. segmentation file:             dorsal_columns.nii.gz

Create temporary folder...
mkdir tmp.151118103611_795665/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Volumes/slevy-4/data/criugm/d_sp_pain_01/t2star/dorsal_columns.nii.gz -o tmp.151118103611_795665/segmentation.nii.gz

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
  87 x 94 x 15

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 50

Compute CSA...

Smooth CSA across slices...
.. Hanning window: 50 mm

Write text file...
z=0: 9.79247361909 mm^2
z=1: 11.5236123229 mm^2
z=2: 13.7303397149 mm^2
z=3: 15.9370671069 mm^2
z=4: 17.6682058107 mm^2
z=5: 18.1840837384 mm^2
z=6: 17.592862293 mm^2
z=7: 16.7756459186 mm^2
z=8: 16.4406161606 mm^2
z=9: 16.6306952983 mm^2
z=10: 16.8207744361 mm^2
z=11: 16.485744678 mm^2

Create volume of CSA values...
sct_image -i csa_volume_RPI.nii.gz -setorient RPI -o csa_volume.nii.gz

Generate output files...
  WARNING: File /Volumes/slevy-4/data/criugm/d_sp_pain_01/t2star/csa_volume.nii.gz already exists. Deleting it...
  File created: /Volumes/slevy-4/data/criugm/d_sp_pain_01/t2star/csa_volume.nii.gz

Find slices corresponding to vertebral levels...
  Check consistency of data size...
    OK!
  Find slices corresponding to vertebral levels...
    3:10
Average CSA across slices...
Mean CSA: 17.0062438453 +/- 0.69473972221 mm^2

Write results in /Volumes/slevy-4/data/criugm/d_sp_pain_01/t2star/csa_mean.txt...

Remove temporary files...
rm -rf tmp.151118103611_795665/

Done!
Output CSA volume: csa_volume.nii.gz
Output CSA file (averaged): csa_mean.txt
Output CSA file (all slices): csa.txt
~~~

The file `dorsal_columns.nii.gz` can be obtained using the following command line:
`fslmaths label/atlas/WMtract__00.nii.gz -add label/atlas/WMtract__01.nii.gz -add label/atlas/WMtract__15.nii.gz -add label/atlas/WMtract__16.nii.gz dorsal_columns.nii.gz`

**Comment by jcohenadad** [comment]
super! can you please add example on the batch_processing for computing left and right CST CSA (do it after GM segmentation)-- also please replace fslmaths with sct_maths
thanks

**Comment by jcohenadad** [comment]
also: i don't understand your comment, stating that it does not make sense to compute CSA from the MNI-Poly-AMU_WM file. Since the WM_atlas is originating from the WM template, the sum of all tracts should equal MNI-Poly-AMU_WM, therefore it is valid to compute CSA from MNI-Poly-AMU_WM.

if the sum is not equal then that's a bug (we have an issue about that i think)

**Comment by slevyrosetti** [comment]
My comment was about the meaning of the voxel values of each of these files. My thinking is the following:
- the file MNI-Poly-AMU_WM was built as a likelihood of presence, hence the value in each voxel is the probability to find the white matter in this voxel position.
- sure the MNI-Poly-AMU_WM file was used during the atlas generation but it was binarized before that to register the Gray's Anatomy atlas to it. Therefore, once you've binarized it, the meaning of likelihood of presence disappears. And finally, the voxel values in the files WMtract__XX are a fractional volume of the tract in this voxel position (obtained from a down-sampling).
Therefore, the sum of all WM tracts don't have any reason to be equal to the file MNI-Poly-AMU_WM which is a probabilistic map of the white matter.

So my point is that computing a CSA by adding fractional volumes (multiplied by the pixel volume) makes sense but computing a CSA by adding probabilities of presence is less rigorous. However, I agree that the results might be really close.
I don't know if it's clear?

**Comment by jcohenadad** [comment]
yup, this is correct. My point was that we should make the two atlases identical (for release 3.0). The partial volume values should simply be scaled by the probability of the WM atlas.

**Comment by slevyrosetti** [comment]
All right! However, the sum of all tracts simply scaled by the probability of MNI-Poly-AMU_WM still won't equal MNI-Poly-AMU_WM?

**Comment by jcohenadad** [comment]
that's right... this is going to be tricky... but not impossible. Let's brainstorm about how to do it properly.
