### ISSUE TITLE
remove flag e, and output size mask that is requested by the user

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#677]

**Comment by benjamindeleener** [comment]
The flag e has been removed.

For which option of ```sct_create_mask```is the output size mask is useful?

**Comment by jcohenadad** [comment]
did you mean the flag -size?
it is useful for all methods

**Comment by benjamindeleener** [comment]
I am talking about the second part of the title: "and output size mask that is requested by the user"
I am not sure to understand what we would like to have. Are we talking about a bounding box including the whole mask? For exemple, the output of creating a mask along centerline on sct_example_data/t2/ is:
```
bendeleener:~/data/sct_example_data/t2 $ sct_create_mask -i t2_RPI.nii.gz -p centerline,t2_seg_RPI.nii.gz -size 20
  OK: t2_seg_RPI.nii.gz

Check if orientation is RPI...

Create temporary folder...
mkdir tmp.160302171942/

Copying input data to tmp folder and convert to nii...
sct_convert -i t2_RPI.nii.gz -o tmp.160302171942/data.nii
sct_convert -i t2_seg_RPI.nii.gz -o tmp.160302171942/centerline.nii.gz

Get dimensions of data...
  52 x 384 x 185 x 1

Create mask...
WARNING: File mask.nii.gz already exists. Deleting it.

Generate output files...
  File created: mask_t2_RPI.nii.gz

Remove temporary files...
rm -rf tmp.160302171942/

Done! To view results, type:
fslview t2_RPI.nii.gz mask_t2_RPI.nii.gz -l Red -t 0.5 &
```

Should we add mask boundaries?

**Comment by jcohenadad** [comment]
ah! ok, sorry my title was not clear. I meant, that if user asks for size=11, he does not get size=11, but e.g., size=13 (as in example below):
![image](https://cloud.githubusercontent.com/assets/2482071/13478349/a4058826-e09e-11e5-88b8-a0eabd6bb1ca.png)

BTW: it might be better to express size in mm rather than in voxel?

**Comment by benjamindeleener** [comment]
I see, I'm on it.

**Comment by benjamindeleener** [comment]
I remember we had a discussion about all this. In some case, we did not wanted to provide a mask with the size provided by the user:
- if the size provided by the user was even, we add 1 so that the center of the mask is actually the correct center and not shifted. It would be solved if we use a mm-based approach.
- if the size provided is odd, then we can use provided number, which is not the case. I'll fix that.

I would not give up a pixel-based approach, especially for maintaining reproducibility. I would allow users to type ```size=11``` (units in pixel) or ```size=11mm``` (units in mm).

**Comment by benjamindeleener** [comment]
Moreover, ```sct_create_mask``` accepts only RPI images. I'll add some lines of code to allow for any orientation.

**Comment by jcohenadad** [comment]
currently, if user asks 4, size is 7. If user asks 5, size is 7. So there is just a +1 bias for both cases.

yes, I agree we should ensure 100% retro-compatibility. To avoid any confusion, I would add a flag ``-size-mm``

RPI --> related to issue #604

**Comment by benjamindeleener** [comment]
Everything done except for mm-based size. The problem is: if Right-Left and Anterior-Posterior spacings are different, what should we take?

**Comment by jcohenadad** [comment]
ah ah good point ;-)
how about we take the mean?
this won't happen many times

**Comment by benjamindeleener** [comment]
The possibility to provide size in mm is done in commit 87b3ac4c19047c69a3666405a40884a4bb540c60.

@jcohenadad Don't hesitate to modify the help to improve understanding.
