### ISSUE TITLE
harmonize the call of "-t" to the template

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#681]
some inconsistencies:
- in **sct_register_to_template**, `-t` refers to: `SCT_DIR/data/template`
- in **sct_warp_template**: `-t` refers to: `SCT_DIR/data`

**Comment by SaraDupont** [comment]
in **sct_process_segmentation**, ```-t``` refers to ```label/template/MNI-Poly-AMU_level.nii.gz```

**Comment by joshuacwnewton** [comment]
This has been addressed. All default values for `-t` are now `os.path.join(sct.__data_dir__, "PAM50")`.
