### ISSUE TITLE
sct_register_multimodal --> enable slicereg2d_affine

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#684]
I'm using it on branch tantan_for_dudu --> best results ever
However code is too complex --> need to code it again

**Comment by benjamindeleener** [comment]
@tanguyduval I don't see the branch tantan_for_dudu on github. Can you push it online?

**Comment by tanguyduval** [comment]
Already there I think.... But I created a new one just for U :heart: 
slicereg2D_affine

**Comment by tanguyduval** [comment]
Could you look at this issue plz!

**Comment by tanguyduval** [comment]
Looks like "slicereg2D_affine" is now in the master branch, thanks for that!
Could you please clarify the parameter **detect_outlier**:
1- This parameter is 0 by default... but actually it is deleting outliers and I have no transfo (detect_outlier=1 solve this issue and I have some transfo)
2- Why is it an integer
3- What range?
4- detect that we input an outlier in the parser

Thanks!
