### ISSUE TITLE
for installation on OSX, edit the bash_profile instead of the bashrc

### ISSUE THREAD

**Issue by neuropoly** [neuropoly/spinalcordtoolbox#69]
to avoid the issue raised by Rezwan Ghassemi (2014-07-30). See emails.

**Comment by benjamindeleener** [comment]
Need to be updated. What is the problem to write in bashrc? Since bash_profile is linked, is this still an issue?

**Comment by jcohenadad** [comment]
not an issue anymore-- we use .bashrc
