### ISSUE TITLE
create function that systematically loads image in RPI orientation & another function that saves the modified data as an image in the original orientation

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#690]
- a function that loads a nifti image in RPI orientation and returns the original orientation
- another function that saves the modified data from the original image into the original orientation (given by the first function)

It will remove this source of error and simplify a lot of scripts.

**Comment by jcohenadad** [comment]
ideally use ```im.change_orientation('RPI')```
