### ISSUE TITLE
help does not display a list of all labels anymore

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#692]
something has changed from a previous version of sct_extract_metric. We used to have a list of labels (as specified by flag -f) in the help. It is not the case anymore.

**Comment by slevyrosetti** [comment]
If the user asks for help, a list of the labels from the file info_label.txt from the folder $SCT_DIR/data/atlas is now displayed (fixed on branch sl_extract_metric, commit 69f0468).
However, with the current organization of the parser, it is not possible to display the info_label.txt from a specified folder in flag -f without making heavy changes in the parser: when the parser detects that a mandatory argument is missing, it immediately returns the help without parsing the input of the user.

**Comment by slevyrosetti** [comment]
Merged via commit 7f6d9fb.
