### ISSUE TITLE
use RESTORE by default for tensor estimation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#693]
see: https://github.com/arokem/dipy-dti

**Comment by joshuacwnewton** [comment]
`"restore"` was added as an option in 6585de614bd5f1d51dac6d9c5a11a3a16bedc812. However, `standard` is still currently the default in this script:

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/scripts/sct_dmri_compute_dti.py#L65-L71

So I don't think this issue has been _completely_ addressed. Should this be `"restore"` by default, @jcohenadad?

**Comment by jcohenadad** [comment]
> Should this be "restore" by default, @jcohenadad?

no it should not-- in some cases, noise estimation ('sigma' as input of restore) is wrongly estimated, yielding wrong results. Moreover, it takes much more time to run restore.
so we can close
