### ISSUE TITLE
add download count on github

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#698]
see: https://github.com/tqdm/tqdm

**Comment by benjamindeleener** [comment]
TQDM download count actually correspond to the download count on PyPi. So not possible to do it on our side that way.

To get download count: https://help.github.com/articles/getting-the-download-count-for-your-releases/

And if we go to this address:
````
https://api.github.com/repos/neuropoly/spinalcordtoolbox/releases
````

Some other nice webpage about that:
http://stackoverflow.com/questions/4338358/github-can-i-see-the-number-of-downloads-for-a-repo

Even better, here is a nice little script that provides download count for all releases:
https://github.com/mmilidoni/github-downloads-count

Launch like this:
```
python gdc.py neuropoly spinalcordtoolbox
```
results in this:
```
spinalcordtoolbox_v2.1_linux.tar.gz: 3 downloads
spinalcordtoolbox_v2.1_osx.tar.gz: 2 downloads
patch_2.0.4.zip: 1 downloads
patch_2.0.3.zip: 2 downloads
patch_2.0.1.zip: 1 downloads
spinalcordtoolbox_v2.0_linux.tar.gz: 2 downloads
spinalcordtoolbox_v2.0_osx.tar.gz: 0 downloads
```

**Comment by joshuacwnewton** [comment]
A download count badge was added in #1713. Closing. :)
