### ISSUE TITLE
Vertebral labeling removes first vertebrae in the labelled segmentation

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#700]
Data on: ```data_processing/bdeleener/bug_vertebral_labelling```
Command:
```
sct_label_vertebrae -i t2_crop.nii.gz -s t2_crop_seg.nii.gz -initz 116,3
```

Labelling works great but C1 level does not appear.
![screen shot 2016-01-11 at 15 01 15](https://cloud.githubusercontent.com/assets/7757117/12245405/4ece36fa-b876-11e5-90fe-f6b5110ca3cd.png)
![screen shot 2016-01-11 at 15 01 23](https://cloud.githubusercontent.com/assets/7757117/12245409/504dffe2-b876-11e5-8a5d-5af8549d231c.png)

**Comment by jcohenadad** [comment]
fixed
