### ISSUE TITLE
check if all images are in the same space

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#719]
see: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/bc8d3e89/?limit=25#cf97

**Comment by jcohenadad** [comment]
create a function in sct_utils, that checks if two images are in the same space: `check_if_same_space`

**Comment by SaraDupont** [comment]
I've created a branch (``ìssue_719_chack_if_same_space```) with : 
- in ```sct_utils```: a function ```check_if_same_space(fname_1, fname_2)``` that return True if the qform of the two images are identical
- in ```sct_register_to_template```: check if data, segmentation and landmarks are in the same spae, if not, print an error message and stop the script (see https://github.com/neuropoly/spinalcordtoolbox/commit/a83574c34af26b7569ee5c5db2209ae1a973cb88)
