### ISSUE TITLE
sct_segment_graymatter: it seems that sometimes headers are partialy corrupted

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#723]
In a cohort of 30 subjects, this bug happened only twice (subjects 26 and 30).
When registering MNI-Poly-AMU_WM (registered on a T2w anatomical image) to the t2starcrop_wm_seg_corrected (output from `sct_segment_graymatter`), the uppest level (C1 and maybe a bit of C2) disappeared.
After running `fslcpgeom t2starcrop.nii.gz t2starcrop_wmseg_corrected.nii.gz` (to copy the right geometrical inf from the header), the bug was fixed.

Data can be found here: `django [...] slevy/data/criugm/d_sp_pain_26/t2star`
Command line can be found in this file: `django [...] slevy/code/template_registration_to_metrics/d_sp_pain/register_template2t2star.sh`

**Comment by SaraDupont** [comment]
Was the issue on file `t2starcrop_wmseg_reg.nii.gz` ?  If so, I could not reproduce the issue with the new version of `sct_segment_graymatter`.

**Comment by SaraDupont** [comment]
@slevyrosetti Could you check if the error persists ? (I wasn't able to reproduce it with `sct_segment_graymatter` latest version.)

**Comment by slevyrosetti** [comment]
Indeed, the bug is fixed! Good job! :)
