### ISSUE TITLE
sct_get_centerline: IndexError: index 72 is out of bounds for axis 0 with size 64

### ISSUE THREAD

**Issue by nguyen1j** [neuropoly/spinalcordtoolbox#725]
Command line
-------------------------------------------------------------------------------
sct_get_centerline -p auto -i dwi_moco_mean_0.nii -c t1
-------------------------------------------------------------------------------
Please unzip (extract) 'dwi_moco_mean_0.nii.zip' first
[dwi_moco_mean_0.nii.zip](https://github.com/neuropoly/spinalcordtoolbox/files/118311/dwi_moco_mean_0.nii.zip)

Details:

Execution of the SCAD algorithm in /.autofs/home/thanh
mkdir tmp.160204170510/
sct_convert -i dwi_moco_mean_0.nii -o tmp.160204170510/raw.nii
isct_vesselness -i raw.nii -t t1 -radius 4
Traceback (most recent call last):
  File "/data/RnD/Thanh/spinalcord2.1/spinalcordtoolbox-2.2.2/build/sct2.2.2/scripts/sct_get_centerline", line 1192, in <module>
    scad.execute()
  File "/data/RnD/Thanh/spinalcord2.1/spinalcordtoolbox-2.2.2/build/sct2.2.2/scripts/sct_get_centerline", line 988, in execute
    img.data[int(x[i]), int(y[i]), int(z[i])] = 1
IndexError: index 72 is out of bounds for axis 0 with size 64
IndexError: index 72 is out of bounds for axis 0 with size 64

**Comment by jcohenadad** [comment]
Bug is related to centerline coordinates being out of the FOV:
~~~
>>> x
array([ 72.79123426,  64.30344419,  54.        ,  43.69655581,
        35.20876574,  29.67786405,  27.09655581,  26.3309017 ,
        26.0881966 ,  25.9072949 ,  25.8381966 ,  25.8881966 ,
        26.        ,  26.1118034 ,  26.1618034 ])
~~~

**Comment by jcohenadad** [comment]
for quick fix, add symmetry constraint:
~~~
sct_get_centerline -p auto -i dwi_moco_mean_0.nii -c t1 -sym 1
~~~

**Comment by jcohenadad** [comment]
closing this issue now-- ``sct_get_centerline`` will be removed from next release
