### ISSUE TITLE
create a laucher for the toolbox

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#729]
* [x] Create a script that will source a specific python bin and library to run the toolbox
* [x] Replace the simlink with the launcher
* [x] rewrite the installation tool to reflect that
* [x] make use of `.sctrc` possible
* [x] display SCT version in the "echo" (get it in version.txt)
* [x] check speed issue (see comment below)
* [x] .bashrc not updated on installation in Docker container (UBUNTU 14.04). Maybe a sudo issue.

**Comment by poquirion** [comment]
Ready to be tested by other!

**Comment by poquirion** [comment]
Ready to be tested by other!

**Comment by poquirion** [comment]
Did not account for testing directories and scripts

**Comment by SaraDupont** [comment]
The -getorient issue (issue #765) may be responsible for the fail of other test: for ex. if the function get an image orientation in command line it will fail. (See https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/116678146 for failing tests)

If so, let me now, I'll fix it quick (I just need to merge master on branch ```poq_issue_729``` and do small changes)

**Comment by jcohenadad** [comment]
just tried `sct_testing` to compare processing time with launcher. Results are not so good:
- poq_issue_729 (82e0949273a9a7a1f6d7885902f891649bcfb69c): --> 308s
- master (8c4796ad2d7d79346e79b0270950a9c3a00539aa): --> 180s

**Comment by poquirion** [comment]
I've added a condition that setup sct_launcher variables only on the original call. 
Linux: 227s
OSX: 490s

**Comment by poquirion** [comment]
No path is modified when user 0 (super user) runs install_sct
