### ISSUE TITLE
Integrate the toolbox as a conda package 

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#730]
Make the toolbox a conda package.

**Comment by jcohenadad** [comment]
recent new ideas:
- make SCT a conda package.
- for nibabel and dipy, use conda-forge
- data will be installed under the /bin of conda
- if users already have conda, do a clone of their conda, and install the requirements specific for SCT (it prevent from re-downloading everything again)
- if users don't have conda, we can have them launch an installer that installs conda and do a conda install sct
- for having SCT work from the Terminal, we need a source activate (already done during conda installation) --> we need to figure out how to select the right conda in case we do a clone.
- do a setup.py
- good example to follow here: https://github.com/uwescience/shablona

**Comment by zougloub** [comment]
Conda is vendor-specific, pip is vendor neutral, see #1526
