### ISSUE TITLE
Integrate C/C++ code as python extension modules

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#731]
Basic recipe here https://docs.python.org/2/extending/extending.html

**Comment by joshuacwnewton** [comment]
From what I understand, we no longer actively maintain the C/C++ code, and rely on pre-compiled binaries (or external libraries) for this functionality. But, could you confirm, @jcohenadad?

**Comment by jcohenadad** [comment]
i confirm
