### ISSUE TITLE
[NEW FEATURE] Create a warper for PIESNO (included in Dipy)

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#733]
PIESNO enable the estimation of noise.
http://nipy.org/dipy/examples_built/piesno.html

**Comment by charleygros** [comment]
**Branch**: issue_733
**Commit:** 2fe7284

**Task 1:** PIESNO method
Done: sct_dmri_create_noisemask
![description sct_dmri_create_noisemask](https://cloud.githubusercontent.com/assets/14353425/13478827/f45265cc-e0a0-11e5-966d-80b5c85e18d1.png)

**Task 2:** Foreground mask by thresholding method in sct_create_mask
- _Usage:_
![usage sct_create_mask](https://cloud.githubusercontent.com/assets/14353425/13478789/c6f42502-e0a0-11e5-839d-10ac6eaa9a2d.png)

- _Command:_
sct_create_mask -i /Volumes/folder_shared/Charley/20130318_091828tsespc1mmp2FOV500s011a1001_RPI.nii.gz -p foreground,0.1

- _Results:_
Morphological operation: opening with a disk structure (radius = 4)
![circular4](https://cloud.githubusercontent.com/assets/14353425/13478982/ddd43f5e-e0a1-11e5-8519-a646c154e75f.png)

@tanguyduval

**Comment by tanguyduval** [comment]
Ok I'll test that

**Comment by charleygros** [comment]
Spinal cord mask: 
sct_create_mask -i /Volumes/folder_shared/Charley/20130318_091828tsespc1mmp2FOV500s011a1001_RPI.nii.gz -p foreground,**0.12**
![screen shot 2016-03-03 at 12 29 36 pm](https://cloud.githubusercontent.com/assets/14353425/13503124/ee3f1c3e-e13b-11e5-8d8f-8e2ba799b923.png)

Body mask:
sct_create_mask -i /Volumes/folder_shared/Charley/20130318_091828tsespc1mmp2FOV500s011a1001_RPI.nii.gz -p foreground,0.015
![screen shot 2016-03-03 at 12 30 52 pm](https://cloud.githubusercontent.com/assets/14353425/13503141/011c97be-e13c-11e5-83f1-92e79a007f7d.png)

@tanguyduval
