### ISSUE TITLE
slicereg2d_affine fails

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#735]
`````
sct_register_multimodal -i SPGRs_crop_ref_seg_reslice_bin.nii.gz -d highQ_mean_RPI.nii -iseg SPGRs_crop_ref_seg_reslice_bin.nii.gz -dseg mask_spinal_cord.nii -p step=1,type=seg,algo=slicereg2d_affine,metric=CC
`````
Error:
`````
Traceback (most recent call last):
  File "/Users/taduv_admin/codes/spinalcordtoolbox/bin/sct_register_multimodal", line 549, in <module>
    main()
  File "/Users/taduv_admin/codes/spinalcordtoolbox/bin/sct_register_multimodal", line 349, in main
    warp_forward_out, warp_inverse_out = register(src, dest, paramreg, param, str(i_step))
  File "/Users/taduv_admin/codes/spinalcordtoolbox/bin/sct_register_multimodal", line 481, in register
    ants_registration_params=ants_registration_params)
  File "/Users/taduv_admin/codes/spinalcordtoolbox/scripts/msct_register.py", line 95, in register_slicereg2d
    warp_x, inv_warp_x, warp_y, inv_warp_y = res_reg
ValueError: need more than 3 values to unpack
ERROR!!!!!!!!!!
````

Data:
`````

/Volumes/folder_shared/BUGS/sct_register_multimodal/sliceregaffine/201602_bug
`````

**Comment by tanguyduval** [comment]
Also in slicereg2d_rigid --> ANTS commandline is not outputed (only the apply transfo):
`````
Estimate transformation for step #0...
isct_antsRegistration --dimensionality 3 --transform syn[0.5,3,0] --metric MI[dest.nii,src.nii,1,32] --convergence 0 --shrink-factors 1 --smoothing-sigmas 0mm --restrict-deformation 1x1x0 --output [step0,src_regStep0.nii] --interpolation BSpline[3]  --verbose 1

Estimate transformation for step #1...
sct_apply_transfo -i src_seg.nii -d dest_seg.nii -w warp_forward_0.nii.gz -o src_seg_reg.nii -x nn
````

**Comment by tanguyduval** [comment]
@jcohenadad In this case slicereg2D_affine gave me a bug. But in most images slicereg2D_affine runs, but doesn't register (warp is 1).

**Comment by jcohenadad** [comment]
I've moved the data under ``folder_shared/sct_issues/20160223_issue735``
in the future please use this one (easier for tracking)
thanks :-)

**Comment by tanguyduval** [comment]
Alright!
Careful not to make conflict with Sara's work on branch sd_improve_register_multimodal

**Comment by tanguyduval** [comment]
Ok I added those data also:
/Volumes/folder_shared/sct_issues/20160223_issue735/GoodDataForTestingAFFINE

With Master --> no transfo.
Command:
`````
sct_register_multimodal -i src.nii -d dest.nii -p step=1,algo=slicereg2d_affine,gradStep=30,iter=100,window_length=4 -r 0
`````

**Comment by jcohenadad** [comment]
Tanguy: I've created a temporary fix to the issue, by adding a flag "slicewise". Important: always use type=im if you want to use slicereg2d_XX algo. Could you please test it in branch: `sd_improve_register_multimodal`. If it works I will cleanup the code and flags.

here are the commands for your data:
**/Volumes/folder_shared/sct_issues/20160223_issue735**
~~~
sct_register_multimodal -i SPGRs_crop_ref_seg_reslice_bin.nii.gz -d highQ_mean_RPI.nii -iseg SPGRs_crop_ref_seg_reslice_bin.nii.gz -dseg mask_spinal_cord.nii -p step=1,type=im,algo=slicereg2d_affine,metric=CC,slicewise=1
~~~

**/Volumes/folder_shared/sct_issues/20160223_issue735/GoodDataForTestingAFFINE**
~~~
sct_register_multimodal -i src.nii -d dest.nii -p step=1,algo=slicereg2d_affine,gradStep=30,iter=100,window_length=4,slicewise=1 -r 0
~~~

**Comment by tanguyduval** [comment]
:+1: I'll try that

**Comment by tanguyduval** [comment]
Ok it works perfectly on all my subjects! See Gif below (test/retest/template)
Now we just have to 
1- "slicereg2d_affine" to Affine (same for Translation/Rigid/Syn/BsplineSyn, although for the last 2 it won't change). option slicewise=1 will perform slicewise. Option slicewise=0 will perform globally.

2- clarify the documentation: 
  - Default smooth values are wrong (because they are defined per step right?)
  - window_length --> doesn't exist anymore
  - detect_outlier --> is it working?




![image](https://cloud.githubusercontent.com/assets/7785316/13303281/5c4cb158-db1c-11e5-8685-3f6df61d6e17.png)

**Comment by jcohenadad** [comment]
1. ok, i propose to have the following list of algo:
~~~
rigid: translation + rotation in X-Y plane (4dof)
affine: translation + rotation + scaling in X-Y plane (6dof)
syn: non-linear symmetric normalization
bsplinesyn: syn regularized with b-splines
slicereg: regularized translations (see: goo.gl/Sj3ZeU)
pointwise: registration based on the Center of Mass of each slice (only use with type=seg)
~~~

2. 
- default smooth value is correct (yes, they are defined per step, but if no smooth is specified, it will set smooth=0)
- window_length --> indeed, will remove
- detect_outlier --> not currently. Maybe that's something we can add in the future.

**Comment by tanguyduval** [comment]
ok perfect. 
Prevent user for using MI (CC is bad also for my data, only MeanSquares works..) with slicereg. 
In the doc Slicewise should be on TOP of options, e.g. in the following order step/type/algo/metric/slicewise/smooth/gradStep.. other options should be noted as "advanced"

Also would be really great to be able to use option `-r`of `isct_antsRegistration` at the initial step (step 0).
  - `-r [' dest ',' src ',0]` --> align the geometric center of the two images
  - `-r [' dest ',' src ',1]` --> align the maximum intensities of the two images
I use that quite often...

**Comment by jcohenadad** [comment]
ok good idea for the "-r"
easy to add

**Comment by tanguyduval** [comment]
Have you understood why affine is compatible only with type=im ??
I usually want to do `-p step=1,type=seg,algo=slicereg2d_affine,slicewise=1,smooth=1`
Indeed affine registration of segs with a smoothing should be very robust no??

I just don't understand this error message:
`warp_x, inv_warp_x, warp_y, inv_warp_y = res_reg
ValueError: need more than 3 values to unpack`

**Comment by jcohenadad** [comment]
that's related to a bug in the code-- i was planning to fix it at some point

**Comment by tanguyduval** [comment]
There were two sub-issues here:

- [ ] add option -r

- [ ] slicereg2d_affine uncompatible with type=seg (bug)

Done??

**Comment by jcohenadad** [comment]
done (flag "-init")
@tanguyduval could you please try it, and if it works fine you can close this issue
thanks

**Comment by tanguyduval** [comment]
Cool! 
Reste quelques points. Je mets tout ici (même si tout n'est pas prioritaire):
- doc: init n'est pas un <int>
- init: --> je pensais le mettre pour Step=0. Donc option indépendante hors -param --> évite que l'utilisateur l'utilise en step2 par ex...
- init: un peu perturbant de ne pas avoir de valeur par défaut.. ajouter default=none par exemple..
- `-p` ne marche plus --> plus rétrocompatible. Fais exprès??
- add check if seg is RPI
- dans le temp folder savegarder les étapes: src.nii, src_step0.nii, src_step1.nii, src_step2.nii, src_step3.nii ..
- `gradStep` is case sensitive. e.g. `gradstep=0.1` works, but uses default value gradStep=0.5

**Comment by jcohenadad** [comment]
ok, these are enhancements, now referred in this issue:
https://github.com/neuropoly/spinalcordtoolbox/issues/754
