### ISSUE TITLE
on SF website, rename spinalcordtoolbox_patch_X.Y.Z.zip as patch_sct_X.Y.Z.zip to avoid confusion during installation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#74]

**Comment by benjamindeleener** [comment]
If we do that, we lose download counting. As the patch installation works for release > 1.2, this issue is manageable.

**Comment by jcohenadad** [comment]
also-- we need to discuss if we want to call it sctoolbox instead...

**Comment by jcohenadad** [comment]
done
