### ISSUE TITLE
add flag in propseg to open a viewer to select three slices 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#741]
~~~
-init-mask viewer
-init-centerline viewer
~~~
--> will start from center slice, and automatically go through all other slices. 

nice to have: Zoom at center to see cord.

**Comment by benjamindeleener** [comment]
This option is not implemented in the branch bdl_propseg. It works only for images where the inferior-superior direction is the second dimension. Still working on it, but it already helps a lot.

**Comment by benjamindeleener** [comment]
This option has been improved to allow for images of any dimensions. The change of orientation is done in sct_propseg.
The viewer can be used using the following command:
```
sct_viewer -i my_image.nii.gz
```
but still need to be improved (particularly parameters and outputs). This is open for discussion.

Moreover, the following features have been added:
- zoom
- intensity adjustment

**Comment by benjamindeleener** [comment]
This option is available by two ways:
for initialization with three points:
```
sct_propseg -i input_image.nii.gz -c t2 -init-mask viewer
```
or for initialization with the spinal cord centerline:
```
sct_propseg -i input_image.nii.gz -c t2 -init-centerline viewer
```
