### ISSUE TITLE
INVALID orientation from getorient

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#747]
data: 
~~~
/Volumes/folder_shared/sct_issues/20160301_issue747 
~~~

~~~
sct_image -i dest_Z0000.nii -getorient
INVALID
~~~

Error probably related to the fact that the image is 2D

**Comment by SaraDupont** [comment]
Yes, it seems to because the image is 2D, since the binary we use to get orientation is made for 3D data. Is it OK to use fslhd just for 2D images or should I adapt the binary ?

**Comment by jcohenadad** [comment]
it creates a bug in sct_register_multimodal, but I've turned off this chunk of code for now (not mandatory). Not urgent, but ideally we'd like to get orientation from 2d data as well. Maybe using nibabel would be the way to go.

**Comment by SaraDupont** [comment]
I found a way to do it using nibabel, for now it's used only for 2D data but it works also for 3D if we want to use it. 
see commit 6338548

**Comment by jcohenadad** [comment]
great! thanks.

i've created an issue #751 to generalize the function (removing the dim=3 case will improve code clarity)
