### ISSUE TITLE
modify management of sct_estimate_tracts

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#75]
change name for: sct_extract_metric.py

in sct_warp_template:
- put CSF, WM, etc. into a folder called **template** to have the same folder tree of the SCT
- in this folder, add a txt file that lists all relevant files.

The list.txt file should be CSV format, organized like that:
- ID, label_name, file_name
example:
- 1,left fasciculus gracilis,vol0000.nii.gz

In the sct_extract_metric, the user will be given the flag -f, which will enable the user to choose between folder: 'atlas', 'template', etc.  by default, the folder 'template' will be selected.

in sct_extract_metric, the file list.txt will be read, and all the tracts and file name will be derived from it.

**Comment by benjamindeleener** [comment]
I believe all of this has been done and merge in master in commit 50ffa7c

**Comment by jcohenadad** [comment]
yup!
