### ISSUE TITLE
warning: could not broadcast input array from shape (happens with high-res images)

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#750]
When segmenting an image with higher in-plane resolution than the model images (0.3x0.3mm), the resampling to the model resolution and back to the image original resolution may result in a loss of information : the gray matter segmentation doesn't have the same size than the original image.

The solution would be to pad in the X and Y direction so that the resampling gives an integer number of pixels. But the size of the padding can be huge depending on the original resolution of the image.

Given px_model and px_im the pixel dimension of the images in the model and the image to segment (in the X direction), and Nx, the number of pixels (in the X direction), the number of pixels to pad in the X direction would be : 

 pad = k*(px_model/px_im) - Nx 

with k the lowest common denominator of px_model and px_im (or any denominator of px_model and px_im)

For now, a warning is displayed if this happen.

**Comment by jcohenadad** [comment]
use reslice-identity

**Comment by SaraDupont** [comment]
Reslice identity is VERY long because the images are very large (since they are in high resolution). For now, I added it only if the resolution of the image to segment is higher than the dictionary images resolution, with a warning message saying it will be longer. I'll work on how to make it faster ...

**Comment by benjamindeleener** [comment]
Cropping images around the segmentation seems to fix the issue!

**Comment by jcohenadad** [comment]
future ITK-based resampling will fix this issue

**Comment by SaraDupont** [comment]
Could not reproduce this issue by segmenting an image resampled to high resolution ...

**Comment by jcohenadad** [comment]
ok i'm closing it then

**Comment by SaraDupont** [comment]
For information, no new bug appears with the new version of sct_segment_graymatter on high resolution images.
