### ISSUE TITLE
do getorient using nibabel instead of binary file

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#751]
generalize function for all dimensions for more clarity. Currently, dim=3 is a special case.

see issue #747

**Comment by joshuacwnewton** [comment]
We now use nibabel to get the orientation! :smile: 

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/scripts/sct_image.py#L213-L215

(`nibabel` is used within `Image`)
