### ISSUE TITLE
various improvement

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#758]
- [x] for flag "-d", say what is high and what is low value. E.g.:  trade-off between distance of most promising point (d is high) and feature strength (d is low)
- [x] for flag "-alpha", say what is high/low. E.g.: trade-off between internal (alpha is high) and external (alpha is low) forces.
- [x] add "viewer" in documentation
- [ ] add info in GUI (zoom, contrast)
- [x] remove tmp. files
- [x] remove _AIL file
- [x] **in viewer: if image is not-isotropic resolution, adapt display scale**

**Comment by benjamindeleener** [comment]
Improvements on the viewer (such as 'add info in GUI (zoom, contrast)') will be part of another issue.
