### ISSUE TITLE
add max/min filtering on non-binary images

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#761]
similar to: ``fslmaths -dilF and -eroF``

**Comment by SaraDupont** [comment]
What size of kernel should we use ? (Basic 3x3 or larger ?)  This could also be an argument: ```sct_image -i im.nii.gz -eroF 5 -o im_F.nii.gz```  (accepting only odd values)

**Comment by jcohenadad** [comment]
i would do it like for option:
~~~
  -smooth <list of: float>    Gaussian smoothing filter with specified standard deviations in mm 
                              for each axis (e.g.: 2,2,1) or single value for all axis (e.g.: 2).
~~~
mm would make more sense, right?

then we also need to homogeneize with options -dilate and -erode...

let's discuss in this thread
