### ISSUE TITLE
harmonize use of -vert and -t flag

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#781]
- [x] sct_segment_graymatter
- [ ] sct_extract_metric --> add -vertfile?
- [x] sct_process_segmentation

see: https://github.com/neuropoly/spinalcordtoolbox/wiki/flags

**Comment by slevyrosetti** [comment]
- sct_extract_metric: no flag to specify the vertebral labeling file is needed
- sct_process_segmentation: fix on branch sl_sct_extract_metric

**Comment by slevyrosetti** [comment]
Merged via commit 7f6d9fb.
