### ISSUE TITLE
center origin of PAM50 template

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#783]
Previous template (MNI-Poly-AMU) and new PAM50 templates don't have their origin centered. There is a -0.5mm shift in the X dimension. See below:

![screen shot 2016-03-26 at 15 33 11](https://cloud.githubusercontent.com/assets/2482071/14062090/53df9f70-f369-11e5-9350-675ac56f076e.png)

![screen shot 2016-03-26 at 15 30 38](https://cloud.githubusercontent.com/assets/2482071/14062091/5691f06a-f369-11e5-857e-ab0b4a974800.png)

**Comment by benjamindeleener** [comment]
It is probably due to the fact that the template is generated with a field of view of 100x100 and that the center is calculated as the position of a voxel (x:50 & y:50).

A solution would be to create a field of view of 101x101 in order to have PAM50 perfectly centered.

**Comment by jcohenadad** [comment]
yes-- in fact, after re-checking, the PAM50 is correctly centered (in the physical coordinates), while the MNI-Poly-AMU is not (but we don't need to address that at this point).

For some reasons, FSL and MITKworkBench display the center of the crossmark at x=50,y=50. Having FOV of 119x119 would indeed solve the problem, but do we want it?

**Comment by benjamindeleener** [comment]
Don't know if we want it. But between the two possibilities,
1. having the center not centered and an even field of view (100x100)
2. having the center centered and an odd field of view (101x101)
I think the second one makes probably more sense.

**Comment by jcohenadad** [comment]
good, we both agree on this so let's do it.

**Comment by benjamindeleener** [comment]
OK. Next version of PAM50 (in a few days) will have a field of view of 101x101.

**Comment by jcohenadad** [comment]
101x101 is too small (we need full vertebrae). I'd go for 119x119.

**Comment by jcohenadad** [comment]
currently, command to crop and center:
~~~
sct_crop_image -i PAM50_XX.nii.gz -o PAM50_XX_cropped.nii.gz -dim 0,1 -start 40,40 -end 158,158
~~~

**Comment by jcohenadad** [comment]
updated current version of PAM50.zip:
https://dl.dropboxusercontent.com/u/20592661/sct/PAM50.zip

Now 119x119x1100. Also contains a README.txt file that lists all modifications.

**Comment by jcohenadad** [comment]
Another incentive to have odd number of voxels: our centerlines are within voxel space, therefore, they need to be in the middle!
