### ISSUE TITLE
PAM50: asymmetric CSF

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#784]
![screen shot 2016-03-26 at 15 57 47](https://cloud.githubusercontent.com/assets/2482071/14062165/b7a233c2-f36b-11e5-8b12-b46bb594ccbe.png)

**Comment by benjamindeleener** [comment]
CSF was generated with PropSeg and not very good. It would be better if created manually (or corrected manually).

**Comment by jcohenadad** [comment]
agreed-- but since the CSF mask depends on cord mask, which depends on WM atlas, let's wait for WM atlas.

**Comment by jcohenadad** [comment]
solved
