### ISSUE TITLE
check sensitivity of sct_propseg test

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#792]
if isct_propseg is missing, the test passes!

I think the problem is related to the exit status of sct_check_dependencies.

**Comment by jcohenadad** [comment]
if propseg is not compatible, test passes:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/34eb6536/?page=1

**Comment by jcohenadad** [comment]
check help from isct_propseg

**Comment by benjamindeleener** [comment]
I added some code to check the compatibility of `isct_propseg` binary. The test checks the first line of the output of `isct_propseg` command, which is `sct_propseg - Version 1.1 (2015-03-24)`.

Here is the output when `isct_propseg` is not compatible:
```
Checking test_sct_propseg...........................[WARNING]
ERROR: isct_propseg does not seem to be compatible with your system or is no up-to-date... Please contact SCT administrators.
status: [99]
Finished! Elapsed time: 0s
```
