### ISSUE TITLE
The point you selected is not in the image.

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#793]
data: **sct_testing_small/20151025_emil/t2**

~~~
sct_propseg -i t2.nii.gz -c t2 -init-mask viewer
~~~

<img width="752" alt="screen shot 2016-03-27 at 10 15 28" src="https://cloud.githubusercontent.com/assets/2482071/14260415/6bf5d66c-fa79-11e5-86ab-b7292169ffc9.png">

likely related to anisotropic resolution?

**Comment by tanguyduval** [comment]
On my images it doesn't work either. Also the doc of propseg doesn't refer to option `-init-mask viewer`
