### ISSUE TITLE
Ask before erasing/reinstalling data, python folders

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#797]
This will save time (mostly for developers): if folders are already there, no need to force deletion/reinstallation. Let's ask with a y/n question if user wants to keep it.

**Comment by poquirion** [comment]
It will none the less remove the soft link in /bin if they exist!

**Comment by jcohenadad** [comment]
yes, good point

**Comment by poquirion** [comment]
Should we ask a question for every directory or do it in bulk (I am doing that right now)?

**Comment by poquirion** [comment]
Done with options
