### ISSUE TITLE
Build a "no internet package"

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox#801]
Will do only 64 bit for now!
- [x] OSX 
- [x] LINUX

**Comment by poquirion** [comment]
Tanguy a le disque avec les packets

**Comment by poquirion** [comment]
@jcohenadad 
J'ai quelque version supplémentaire. Faudra seulement les transférer.

**Comment by jcohenadad** [comment]
nice! attends que simon/sara ont mergé avant de faire les packages. 
Pourras-tu les mettre sur folder_shared/sct/?
merci!

**Comment by poquirion** [comment]
Bon y'avais un bug que je pouvais difficilement voir avec des test sur la même machine que celle ou le package avait été créé: Il y a plein de path hardcodé dans l'install de conda/python

**Comment by poquirion** [comment]
Bon, il semble que j'ai sous estimé la difficulté du problème.

Faire une remplacement des path dans le dossier de conda nous envoie un classique:

```
. python/bin/activate root
Segmentation fault (core dumped)
```

Il semble qu'il faut tout les paquets pré installé.

**Comment by poquirion** [comment]
Bon j'ai implémenter la nouvelle approcher. Pour faire le packet:

```bash
cd spinalcordtoolbox/install
python create_package.py
```

Pour installer le package offline 

```bash
tar -zxvf sct_offline_xxx.tar.gz
cd sct_vXXX/
bash ./install_sct -o 
```
Voilà!

**Comment by poquirion** [comment]
En ce moment 
`create_package.py` fait un package qui ne peut s'installer que sur l'os de creation, mais la seul difference entre `sct_vXXX_offline_linux.tar.gz` et `sct_vXXX_offline_osx.tar.gz` sont les dossiers 
`sct_vXXX/offline/pkgs_linux` et `sct_vXXX/offline/pkgs_osx`. Si on copy l'un ou l'autre de ses dossier dans l'installeur de l'autre os, l'installeur devient fonctionnel sur OSX et LINUX!
 
Il ne suffi que de recompresser et de nommer le tarball :    `sct_vXXX_offline_none.tar.gz`
Voilà

**Comment by jcohenadad** [comment]
PO, why not using a flag -s [osx, linux] as we did before, in order to be able to create a package from any os?

**Comment by zougloub** [comment]
During installation of SCT, the bundled Python installation is made specific to the SCT install location.
Distro-specific offline archives can be made with `sct_docker_images.py` but they need to be installed in `/home/sct` in order to work (to use them, just add `PATH+=":/home/sct/sct_${version}/bin"`).
Location-independent setup can so far only be performed by wrapping all of this in a container (available now, pending official publication) or VM.
