### ISSUE TITLE
testing of sct_register_graymatter gives almost empty template

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#803]
There is a problem with the warping field used for testing sct_register_graymatter. Testing command is : `sct_register_graymatter -t mt/label/ -w mt/warp_template2mt.nii.gz -gm mt/mt0_gmseg.nii.gz -wm mt/mt0_wmseg.nii.gz -manual-gm mt/mt0_manual_gmseg.nii.gz -sc mt/mt0_seg.nii.gz -qc 0`

Check that the warping field in the testing data (`mt/warp_template2mt.nii.gz`) is the warping field corresponding to Template-->T2-->MT. 

See result of testing in `/Users/sadup/data/tmp.160407150753/results_sct_register_graymatter/tmp.160407150754_129029/label`

**Comment by jcohenadad** [comment]
this function is slowly being deprecated as of v3.2.1
