### ISSUE TITLE
./batch_processing.sh: line 137: sct_register_graymatter: command not found

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#806]
Error when running `./batch_processing.sh`

**Comment by jcohenadad** [comment]
@slevyrosetti: did you link your new binary?  please always run ./install_sct -m -d when a new script is added

**Comment by slevyrosetti** [comment]
Ok, no I didn't. I didn't get that we needed to run this command every time we pull.
It fixed it.

**Comment by jcohenadad** [comment]
not every time you pull-- only when there is a new script added (i.e., that you haven't previously linked).
