### ISSUE TITLE
sct_image -setorient --> it removes the 5th dimension. 5D data are converted to 3D data.

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#808]
data here : `/Django/folder_shared/sct_issues/20160413_issue808/gre_3d_MTC0_FA4_6ch.nii`
These data have 6 components in the 5th dimension
command:
`sct_image -i gre_3d_MTC0_FA4_6ch.nii -setorient RPI`
see also #605

**Comment by SaraDupont** [comment]
Fixed in commits 467b949, 6618745, and de257b1

**Comment by SaraDupont** [comment]
Fixed only for 5D data without 4D : 
need to split first along 5th D then along T to change orientation, and concat in the correct order

**Comment by tanguyduval** [comment]
Will be solved if #842 is solved
