### ISSUE TITLE
improve register_to_template by accounting for slight rotations

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#811]
one possible solution:
- dilate the mask
- add a first step based on image, and mask using previous mask, and allow for rotations, use CC
- next steps are the same (slicereg, bsplinesyn, syn)

**Comment by jcohenadad** [comment]
e.g. here, sct_example_data, slice #1:
![screen shot 2016-04-15 at 11 58 07](https://cloud.githubusercontent.com/assets/2482071/14567288/6235110c-0301-11e6-9302-c9fa7731fd10.png)

**Comment by benjamindeleener** [comment]
Done in new `sct_register_multimodal` and `sct_register_to_template`
