### ISSUE TITLE
NameError: name 'Coordinate' is not defined

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#816]
~~~
sct_testing -f sct_register_to_template
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Spinal Cord Toolbox (version dev)
Running /Users/julien/code/spinalcordtoolbox/scripts/sct_testing.py -f sct_register_to_template

Path to testing data: /Users/julien/sct_testing_data/data/
Checking test_sct_register_to_template..............Running /Users/julien/code/spinalcordtoolbox/scripts/sct_register_to_template.py -c t2 -l /Users/julien/sct_testing_data/data/t2/labels.nii.gz -i /Users/julien/sct_testing_data/data/t2/t2.nii.gz -t /Users/julien/sct_testing_data/data/template/ -v 1 -s /Users/julien/sct_testing_data/data/t2/t2_seg.nii.gz -r 0 -param step=1,type=seg,algo=slicereg,metric=MeanSquares,iter=5:step=2,type=seg,algo=bsplinesyn,iter=3,metric=MI:step=3,iter=0 -ofolder sct_register_to_template_data_160415125549_416705/
Check folder existence...
Check folder existence...

Check template files...
  OK: /Users/julien/sct_testing_data/data/template/template/MNI-Poly-AMU_T2.nii.gz
  OK: /Users/julien/sct_testing_data/data/template/template/landmarks_center.nii.gz
  OK: /Users/julien/sct_testing_data/data/template/template/MNI-Poly-AMU_cord.nii.gz

Check parameters:
.. Data:                 /Users/julien/sct_testing_data/data/t2/t2.nii.gz
.. Landmarks:            /Users/julien/sct_testing_data/data/t2/labels.nii.gz
.. Segmentation:         /Users/julien/sct_testing_data/data/t2/t2_seg.nii.gz
.. Path template:        /Users/julien/sct_testing_data/data/template/template
.. Path output:          sct_register_to_template_data_160415125549_416705/
.. Output type:          1
.. Remove temp files:    0

Parameters for registration:
Step #1
.. Type #seg
.. Algorithm................ slicereg
.. Metric................... MeanSquares
.. Number of iterations..... 5
.. Shrink factor............ 1
.. Smoothing factor......... 5
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #2
.. Type #seg
.. Algorithm................ bsplinesyn
.. Metric................... MI
.. Number of iterations..... 3
.. Shrink factor............ 1
.. Smoothing factor......... 1
.. Gradient step............ 0.5
.. Degree of polynomial..... 3
Step #3
.. Type #im
.. Algorithm................ syn
.. Metric................... CC
.. Number of iterations..... 0
.. Shrink factor............ 1
.. Smoothing factor......... 0
.. Gradient step............ 0.5
.. Degree of polynomial..... 3

Check if data, segmentation and landmarks are in the same space...

Check input labels...

Create temporary folder...
mkdir tmp.160415125550_125268/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/sct_testing_data/data/t2/t2.nii.gz -o tmp.160415125550_125268/data.nii
sct_convert -i /Users/julien/sct_testing_data/data/t2/t2_seg.nii.gz -o tmp.160415125550_125268/seg.nii.gz
sct_convert -i /Users/julien/sct_testing_data/data/t2/labels.nii.gz -o tmp.160415125550_125268/label.nii.gz
sct_convert -i /Users/julien/sct_testing_data/data/template/template/MNI-Poly-AMU_T2.nii.gz -o tmp.160415125550_125268/template.nii
sct_convert -i /Users/julien/sct_testing_data/data/template/template/MNI-Poly-AMU_cord.nii.gz -o tmp.160415125550_125268/template_seg.nii.gz
sct_convert -i /Users/julien/sct_testing_data/data/template/template/landmarks_center.nii.gz -o tmp.160415125550_125268/template_label.nii.gz

Smooth segmentation...
sct_maths -i seg.nii.gz -smooth 1.5 -o seg_smooth.nii.gz

Resample data to 1mm isotropic...
sct_resample -i data.nii -mm 1.0x1.0x1.0 -x linear -o data_1mm.nii
sct_resample -i seg_smooth.nii.gz -mm 1.0x1.0x1.0 -x linear -o seg_smooth_1mm.nii.gz
Position=(31,44,26) -- Value= 3
Position=(32,9,26) -- Value= 5
Useful notation:
31,44,26,3:32,9,26,5
sct_label_utils -i data_1mm.nii -p create -coord 31,44,26,3:32,9,26,5 -v 1 -o label_1mm.nii.gz
Running /Users/julien/code/spinalcordtoolbox/scripts/sct_label_utils.py -i data_1mm.nii -p create -coord 31,44,26,3:32,9,26,5 -v 1 -o label_1mm.nii.gz
Traceback (most recent call last):
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_label_utils.py", line 767, in <module>
main()
File "/Users/julien/code/spinalcordtoolbox/scripts/sct_label_utils.py", line 733, in main
arguments = parser.parse(sys.argv[1:])
File "/Users/julien/code/spinalcordtoolbox/scripts/msct_parser.py", line 363, in parse
dictionary[arg] = self.options[arg].check_integrity(param)
File "/Users/julien/code/spinalcordtoolbox/scripts/msct_parser.py", line 171, in check_integrity
return list([self.check_integrity(val, sub_type) for val in param_splitted])
File "/Users/julien/code/spinalcordtoolbox/scripts/msct_parser.py", line 128, in check_integrity
return self.checkStandardType(param, type)
File "/Users/julien/code/spinalcordtoolbox/scripts/msct_parser.py", line 186, in checkStandardType
return self.__safe_cast__(param, eval(type_option))
File "<string>", line 1, in <module>
NameError: name 'Coordinate' is not defined
/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 100
/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 100
[FAIL]
~~~

**Comment by benjamindeleener** [comment]
This issue happens when we remove the line
```
from msct_types import Coordinate
```

from ```msct_parser```.

Even if Pycharm says it is not useful, it is!

**Comment by jcohenadad** [comment]
i didn't remove this line!  i guess pycharm must have done it automatically... arg!
