### ISSUE TITLE
Output a confidence interval per tract for the ML and the MAP methods

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#824]

**Comment by tanguyduval** [comment]
On how many voxels was estimated the metric?
Can we think of a confidence interval instead of std = 0.00000??

**Comment by slevyrosetti** [comment]
Duplicate with issue #829

**Comment by tanguyduval** [comment]
I had a second issue here. I really need a confidence interval on the estimated metrics that use MAP.

**Comment by jcohenadad** [comment]
We will simply output the STD.
