### ISSUE TITLE
Indicate number of voxels in sct_extract_metric

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#829]
to add in excel + txt output

**Comment by slevyrosetti** [comment]
Could you be more precise? Do you mean the total fractional volume of the ROI? Or maybe the number of voxels where the ROI has a fractional volume > 0 (or >threshold)?

**Comment by jcohenadad** [comment]
ok, actually it's the total fractional volume of the ROI. For example: if the tract is made up with 3 voxels: 0.1, 0.5, 0.5, then the total fractional volume is 1.1

**Comment by slevyrosetti** [comment]
OK!

**Comment by slevyrosetti** [comment]
Fixed in commit 417bf06 on branch `sl_issues_825_829`.
