### ISSUE TITLE
sct_register_to_template: bug

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#830]
Data: /Volumes/folder_shared/sct_issues/20160421_issue830
Command line:
~~~
pass:/Volumes/slevy-5/data/criugm/d_sp_pain_30_retest/t2 $ sct_register_to_template.py -i t2crop.nii.gz -l t2crop_landmarks.nii.gz -s t2crop_seg.nii.gz
~~~
Output:
~~~
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/scripts/sct_register_to_template.py", line 547, in <module>
    main()
  File "/Users/slevy_local/spinalcordtoolbox/scripts/sct_register_to_template.py", line 192, in main
    fname_template = fname_template_list[0]
IndexError: list index out of range
~~~

**Comment by jcohenadad** [comment]
Cannot reproduce with commit: 3f495c806009d0da66fe9242a442c092542edb14. 
Note that the call "sct_register_to_template.py" is suspicious (extension should not be there). Maybe an installation issue on your side?

**Comment by slevyrosetti** [comment]
All right, it works without the extension .py. Do you have an idea why it would fail using the extension .py? I need to have the script `matlab_batcher.sh` in my path so I added the path to the `scripts` folder in my `.bash_profile`, that's why I have the .py extension. But I haven't had any problem until now with any of the other scripts...

**Comment by jcohenadad** [comment]
SCT should not be used like this anymore. You have to go through the launcher, which associates the proper Python distrib.
one solution for you is to add the path to /bin in matlab, and call the launcher sct_register_to_template inside bin (not in script)

**Comment by slevyrosetti** [comment]
No this is the inverse problem: I am using the matlab_batcher.sh which is
in the folder scripts and which allows to run matlab functions from the
terminal (like in a batch, without having to open Matlab).
matlab_batcher.sh hasn't a launcher as the other .py scripts.

2016-04-25 19:43 GMT-04:00 Julien Cohen-Adad <notifications@github.com>:
