### ISSUE TITLE
ERROR: The file label/template/MNI-Poly-AMU_level.nii.gz does not exist. Exit program.

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#832]
The flag -vertfile is in optional, however it produces a bug when not used.

Also, when I set "-use-levels 0", it also produces an error.

~~~
sct_segment_graymatter -i data19_mean.nii.gz -s data19_mean_seg.nii.gz 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Spinal Cord Toolbox (version dev)
Running /Users/julien/code/spinalcordtoolbox/scripts/sct_segment_graymatter.py -i data19_mean.nii.gz -s data19_mean_seg.nii.gz

ERROR: The file label/template/MNI-Poly-AMU_level.nii.gz does not exist. Exit program.

/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py, line 273
~~~

**Comment by SaraDupont** [comment]
I assume the data are the same that for issue #834 ? With those data I couldn't reproduce the error.

**Comment by jcohenadad** [comment]
hi,
yes, you could not reproduce the error, because i had to install the folder "label" to overcome the error. Now i've renamed the folder to label_old, so you can try again

**Comment by jcohenadad** [comment]
fixed
