### ISSUE TITLE
GM segmentation does not seem to account for rotations

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#834]
![output_xbzs90](https://cloud.githubusercontent.com/assets/2482071/14753371/1e301e5a-08a3-11e6-88c5-fbe22c04b394.gif)

**Comment by jcohenadad** [comment]
data: folder_shared/sct_issues/20160422_issue834
command:
~~~
sct_segment_graymatter -i data19_mean.nii.gz -s data19_mean_seg.nii.gz
~~~

**Comment by SaraDupont** [comment]
The registration of the target to the model is an affine so it should account for it. 
Idea of fix: try to add a **rigid registration first** (rotation) and then an affine (scaling). (The translation is implicitly done when cropping the image around SC and stacking the cropped squares centered on SC)

**Comment by jcohenadad** [comment]
yes, that is a possibility. But let's wait for now, because Benjamin and I discussed about a robust way to find cord rotation based on symmetry of the image. That will not be for v3.0.

**Comment by SaraDupont** [comment]
Fixed by the new implementation of `sct_segment_graymatter`:
![2016-10-17-res_gmseg](https://cloud.githubusercontent.com/assets/5857909/19449888/64034836-9475-11e6-8778-ba9e144ba8af.gif)
