### ISSUE TITLE
warnings.warn("Mean of empty slice.", RuntimeWarning)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#840]
would that be possible to remove this message during testing?
see here:
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/125891232

**Comment by jcohenadad** [comment]
likely coming from numpy.mean in ``test_sct_register_graymatter``:
https://github.com/gregversteeg/CorEx/issues/1

**Comment by jcohenadad** [comment]
yes-- confirmed: it comes from the test:
~~~
        result_dice_wm = mean(wm_dice_list)
        result_diff_dc_wm = mean(wm_diff_list)
        result_dice_gm = mean(gm_dice_list)
        result_diff_dc_gm = mean(gm_diff_list)
        result_hausdorff = mean(hausdorff_list)
        result_diff_hd = mean(hd_diff_list)
        result_median_dist = mean(max_med_list)
        result_diff_md = mean(md_diff_list)
~~~

**Comment by SaraDupont** [comment]
Ok ! Good to know, I'll try to remove the warning in the testing.

**Comment by jcohenadad** [comment]
already done it!
i'll push soone
