### ISSUE TITLE
sct_propseg add option to propagate a elliptical tube (adapted for cervical regions)

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#841]
Currently we can only specify the radius. 
Problem, on T1 images of cervical regions it nearly never works because:
(i) too elliptical
(ii) not enough contrast to deform

**Comment by tanguyduval** [comment]
Also enable better CONTRAST of the viewer

**Comment by benjamindeleener** [comment]
It would be easy to compress the initial mesh in one direction, to make it look like an elliptical tube.  The command parameter would be `-radius x,y` where x is the radius in the anterior-posterior direction and y is the radius in the left-right direction. If the user provides one radius with `-radius x`, both AP and LR radii are the same. Values of radii are in millimeters.

**Comment by jcohenadad** [comment]
Closing because:
- isolated case
- `sct_deepseg_sc` is replacing propseg
