### ISSUE TITLE
Replace isct_orientation with a python script to enable reorientation of N-D data

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#842]
isct_orientation handles only 3D data --> sct_image is slow because split the 4th/5th.. dimension.

**Comment by joshuacwnewton** [comment]
We now have `change_orientation` in `spinalcordtoolbox/image.py` which can handle 4D/5D data:

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/spinalcordtoolbox/image.py#L1017-L1025

From what I understand, we no longer use `isct_orientation3d`, too, thanks to #2459. So, I'm closing this.
