### ISSUE TITLE
Exception: Unexpected data type <type 'numpy.float32'>

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#857]
~~~
sct_process_segmentation -i data_wmseg.nii.gz -p csa -z 11:11 -o csa_z11_ -output-type xls
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Spinal Cord Toolbox (version 3.0_beta4-0ba4609559986d3928644dc916d121502978e096)
Running /Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py -i data_wmseg.nii.gz -p csa -z 11:11 -o csa_z11_ -output-type xls

Check parameters:
.. segmentation file:             data_wmseg.nii.gz

Create temporary folder...
mkdir tmp.160505042212_111770/

Copying input data to tmp folder and convert to nii...
sct_convert -i /Users/julien/GoogleDrive/Students/Benjamin_De_Leener/manuscript/sct/data/ALS_S_701_004_28/data_wmseg.nii.gz -o tmp.160505042212_111770/segmentation.nii.gz

Change orientation to RPI...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
  480 x 534 x 13

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 50

Compute CSA...

Smooth CSA across slices...
.. No smoothing!

Compute CSA per slice...
z=0: 59.1881683461 mm^2
z=1: 55.1392062318 mm^2
z=2: 58.6775120057 mm^2
z=3: 61.2072284592 mm^2
z=4: 63.3828126658 mm^2
z=5: 67.6076723573 mm^2
z=6: 60.3204502883 mm^2
z=7: 62.790078237 mm^2
z=8: 61.7390173285 mm^2
z=9: 61.1361235542 mm^2
z=10: 62.6691717769 mm^2
z=11: 61.3298672896 mm^2
z=12: 64.9718193672 mm^2
Save results in: csa_z11_csa_per_slice.txt

Create volume of CSA values...
sct_image -i csa_volume_RPI.nii.gz -setorient RPI -o csa_volume_in_initial_orientation.nii.gz

Generate output files...
  WARNING: File csa_z11_csa_volume.nii.gz already exists. Deleting it...
  File created: csa_z11_csa_volume.nii.gz

Average CSA across slices...
Mean CSA: 61.3298672896 +/- 0.0 mm^2
Save results in: csa_z11_csa_mean.xls

Compute the volume in between the selected slices...
Volume in between the selected slices: 30970.8 mm^3
Save results in: csa_z11_volume.xls

Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 950, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 245, in main
    compute_csa(fname_segmentation, output_prefix, param_default.suffix_csa_output_files, output_type, overwrite, verbose, remove_temp_files, step, smoothing_param, figure_fit, slices, vert_lev, fname_vertebral_labeling, algo_fitting = param.algo_fitting, type_window= param.type_window, window_length=param.window_length)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 630, in compute_csa
    save_results(output_prefix+output_suffixes[3], output_type, overwrite, file_data, 'volume', 'nb_voxels x px x py x pz (in mm^3)', volume, np.nan, slices, actual_vert=vert_levels_list, warning_vert_levels=warning)
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 752, in save_results
    sh.write(row_index, 6, mean)
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "/Users/julien/code/spinalcordtoolbox/python/lib/python2.7/site-packages/xlwt/Row.py", line 260, in write
    raise Exception("Unexpected data type %r" % type(label))
Exception: Unexpected data type <type 'numpy.float32'>
~~~

**Comment by slevyrosetti** [comment]
Fixed in commit 791ddd2.
