### ISSUE TITLE
swelling of multilabel registration due to smoothing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#859]
below is a gif showing:
- registered multilabel template with automatic_seg_crop_notSmoothed
- registered multilabel template with automatic_seg_crop_smoothed --> notice the swelling effect
- target image (automatic_seg_crop)
![www gifcreator me_kxr9wj](https://cloud.githubusercontent.com/assets/2482071/15061525/147b91a2-1369-11e6-9bcf-8d33397346f8.gif)

**Comment by SaraDupont** [comment]
Smoothing is already commented in sct_ergister_graymatter code ... can we close this ?

**Comment by jcohenadad** [comment]
yes, let's close it then
