### ISSUE TITLE
minor improvements on EXCEL output

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#860]
- move column F between column A and B
- when "z" is selected, the column "Vertebral level" shows "ALL", which is wrong. Please change for "NaN"

**Comment by slevyrosetti** [comment]
1st point fixed in commit 5624af9.

**Comment by slevyrosetti** [comment]
2nd point fixed in commit 0ce3d3a

**Comment by slevyrosetti** [comment]
2nd point was also applied at sct_extract_metric in commit 64675e2
