### ISSUE TITLE
Installation from package does not create the commit.txt file

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#861]
<img width="696" alt="screen shot 2016-05-09 at 05 01 30" src="https://cloud.githubusercontent.com/assets/7757117/15100403/375c2d1c-15a3-11e6-88c4-1f76ce8da19b.png">

**Comment by jcohenadad** [comment]
Benjamin: how did you install this beta8?  from the offline package of PO or from the online package?

**Comment by benjamindeleener** [comment]
From the online package.

**Comment by jcohenadad** [comment]
ok found the bug-- i'm fixing it
