### ISSUE TITLE
Minimize amount of Python packages installed using Conda

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#865]
e.g., do we need mkl?

**Comment by benjamindeleener** [comment]
mkl is installed to speed-up numpy and scipy and it causes some problem on debian for using numpy and scipy. This way of installing numpy and scipy is done by conda. I am investigating installing numpy and scipy with pip.

This issue is related to issue #906

**Comment by zougloub** [comment]
MKL is installed by default on Conda, now removed if it causes issues (detected during installation).
Conda packages are pre-compiled, whereas pip packages are often source-based and take more time to install (and require more depedencies). In the long term we should aim to be able to work with the system Python, with a simple virtualenv.
