### ISSUE TITLE
Add option in installer to make pip work in VM

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#873]
This option should add the following line in the .bashrc (or .bash_profile ?):
`export PIP REQUIRE VIRTUALENV=true`

This was suggested by an user during the SCT courses at Singapore (may 13th 2016): @jcohenadad I think you have a snapshot of his .bashrc

**Comment by zougloub** [comment]
http://docs.python-guide.org/en/latest/dev/pip-virtualenv/:

> In order to make sure that you install packages to your active virtual environment when you use pip install, consider adding the following line to your ~/.bashrc file: `export PIP_REQUIRE_VIRTUALENV=true`»

Not necessary when using the Conda bundled environment.
