### ISSUE TITLE
add  spinal levels and gm_model for new PAM50

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#877]

**Comment by SaraDupont** [comment]
The gm_model is not template dependant: it will be the same as it was for the MNI-Poly-AMU template, right ?

**Comment by jcohenadad** [comment]
good point-- how does your function behaves if users include vertebral level information that are not in the model (e.g., T12)? Just want to make sure it will not crash

**Comment by SaraDupont** [comment]
I think it would work (I recently allowed more vertebral levels) but I need to test it to be sure.

**Comment by jcohenadad** [comment]
duplicated issue
