### ISSUE TITLE
check that if user calls dmri.nii.gz dwi.nii.gz, there is no overwriting of file

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#882]
because moco is supposed to output a file called dwi.nii.gz

**Comment by peristeri** [comment]
@jcohenadad can you provide an example with the data of the problem?

**Comment by jcohenadad** [comment]
actually my mistake-- sct_dmri_moco is supposed to output files called dwi_moco, dwi_moco_mean and b0_moco_mean, so it should be fine (i.e. users should not call a file with _moco if moco has not been applied yet).
