### ISSUE TITLE
[sct_propseg] Viewer displays sagital view

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#884]
Should display the axial view!?

**data:**
/Volumes/data_shared/boston/brighams/20160204_NIFTI/1.5T_GE/1.5TGE_13332_00014_SAG_FRFSE-XL_T2_POST_TSP_00001.nii

**syntax:**
sct_propseg -i t2_sag_csp.nii.gz -c t2 -init-centerline viewer

**error:**
![screen shot 2016-06-10 at 9 54 25 am](https://cloud.githubusercontent.com/assets/14353425/15966529/8c8bbe08-2ef1-11e6-85a4-fcdda39855e9.png)

**Comment by benjamindeleener** [comment]
It actually seems to be sagittal, but the resolution in left-right direction does not seem correct. I'll check into that.
