### ISSUE TITLE
[sct_proseg] Error with absolute path

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#885]
Error with absolute path but works with relative path (ie from the folder of interest)

**syntax:**
sct_propseg -i /Volumes/data_shared/boston/brighams/20160204_NIFTI/1.5T_GE/1.5TGE_13332_00014_SAG_FRFSE-XL_T2_POST_TSP_00001.nii -c t2 -ofolder /Users/chgroc/data -init-centerline viewer

**error:**
Running /Users/chgroc/code/spinalcordtoolbox/scripts/sct_image.py -i /Volumes/data_shared/boston/brighams/20160204_NIFTI/1.5T_GE/1.5TGE_13332_00014_SAG_FRFSE-XL_T2_POST_TSP_00001.nii -o tmp./Volumes/data_shared/boston/brighams/20160204_NIFTI/1.5T_GE/1.5TGE_13332_00014_SAG_FRFSE-XL_T2_POST_TSP_00001_AIL.nii -setorient AIL -v 0
Error of writing permissions on file: tmp./Volumes/data_shared/boston/brighams/20160204_NIFTI/1.5T_GE/1.5TGE_13332_00014_SAG_FRFSE-XL_T2_POST_TSP_00001_AIL.nii
Aborted...

**Comment by charleygros** [comment]
Works without "-init-centerline viewer"!

**Comment by benjamindeleener** [comment]
Indeed, a file needs to be written in the current folder. I'll change that.
