### ISSUE TITLE
Cannot find script when called in code on Neurodebian

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#898]
I tried to install and use the toolbox on neurodebian (the one on ```folder_shared/virtual_box/NeuroDebian\ 7.4.20140423\ \ \(64bit\).ova```)  but I got several issues that seems to be related : 
- at the end of the installation, can't find `isct_test_ants` and `isct_propseg`
- when trying to launch a function, can't find any script called in the code (see screenshots below)

It seems to be related to the launcher, right ?

![installation_error](https://cloud.githubusercontent.com/assets/5857909/16206172/18cffce8-36f5-11e6-8dac-f4b8f784fa9e.png)
![script_not_found_1](https://cloud.githubusercontent.com/assets/5857909/16206174/18d24d18-36f5-11e6-9f55-ef0118d3d70b.png)
![script_not_found_2](https://cloud.githubusercontent.com/assets/5857909/16206175/18d5df0a-36f5-11e6-8272-75b630ffc474.png)
![script_not_found_3](https://cloud.githubusercontent.com/assets/5857909/16206173/18d0a6de-36f5-11e6-88f0-f7152c59c4ef.png)

**Comment by jcohenadad** [comment]
i was not able to reproduce the error. Sara, can you try again?
thanks

**Comment by SaraDupont** [comment]
Issue seems to be solved by re-running ```./install_sct```
Users may also have to run installation twice to get it working.

**Comment by cmrrswift** [comment]
The scripts it is looking for are under spinalcordtoolbox/bin. It seems you need to have this in your PATH -BEFORE- installing the software to find those scripts.

export PATH=/usr/local/spinalcordtoolbox/bin:$PATH

Also helped to make sure I was getting the spinalcordtoolbox python:

PATH=/usr/local/spinalcordtoolbox/python/bin:$PATH

**Comment by jcohenadad** [comment]
thank you @cmrrswift, let's reopen the issue until fixed as you suggested

**Comment by SaraDupont** [comment]
I re-installed SCT from scratch on Neurodebian (with git clone). 
- At the end of the installation I get the same errors as in the first screen shot of this issue (ANTs and Propseg fail)
- when opening a new window, testing runs fine
- propseg also runs fine 

I think the new version fix this !
