### ISSUE TITLE
remove ornlm dependency

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#901]
see issue here for people having OS-related difficulties to make ornlm work:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/3bf1555b/?limit=25

should be fairly easy to add a flag to remove denoising (or use another method that does not rely on ornlm).

**Comment by SaraDupont** [comment]
There is a flag for denoising, is the issue occurring even with ``` -denoising 0``` ?

**Comment by jcohenadad** [comment]
great! thanks
