### ISSUE TITLE
check if "DYLD_FALLBACK_LIBRARY_PATH" is in bashrc

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#905]
sends a warning if that's the case.

see https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/59fdc45e/

**Comment by joshuacwnewton** [comment]
As this is an isolated issue that has not reappeared in several years, I'm closing this. We can re-open if it becomes an issue for other users. :)
