### ISSUE TITLE
sct_fmri_modo does not add correct path to fslview display

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#908]
When sct_fmri_moco is used with -ofolder option, at the end when it suggest the fslview path to overlay the results, it does not add the -ofolder path to the generated files to be displayed in fslview.

**Comment by joshuacwnewton** [comment]
I tried this with current SCT:

```
sct_fmri_moco -i fmri/fmri.nii.gz -g 4 -x nn -r 0 -ofolder test-issue/
```

And got the output:

```
Done! To view results, type:
fsleyes test-issue/fmri_moco.nii.gz fmri/fmri.nii.gz &
```

So, the `ofolder` is present as expected. Closing.
