### ISSUE TITLE
Propseg initialization fails

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#915]
Path to data: `/Volumes/folder_shared/als_gm_atrophy/15_test_processing/space`
Command line : `sct_propseg -i space.nii.gz -c t2`

Error : 
![error_initalization](https://cloud.githubusercontent.com/assets/5857909/16699020/65c3f148-451f-11e6-8309-7273e31b724f.png)

It worked with flag `-init-centerline viewer`

**Comment by jcohenadad** [comment]
I can reproduce the error. 
I tried to pad and to reorient in RPI but the error is still there.

**Comment by jcohenadad** [comment]
when resampling the image to 1mm iso it works (native resolution 0.9mm iso)

**Comment by benjamindeleener** [comment]
Fixed with the introduction of OptiC.
