### ISSUE TITLE
poor registration results

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#919]
this follows the removal of rotation (only using affine to preregister straight cord to template) following Allan's issue at edge. 

sct_testing:
![screen shot 2016-07-09 at 08 40 33](https://cloud.githubusercontent.com/assets/2482071/16707998/eaf12002-45b0-11e6-92d3-8e2a2a15682c.png)
DICE~0.65

**Comment by benjamindeleener** [comment]
Rotation has not been removed yet. I just added cropping to avoid the problem but it causes other issues. Removing the rotation would fix both issues.

**Comment by benjamindeleener** [comment]
Actually the transformation is already a translation + scaling in the z direction. So the error must come from somewhere else...

**Comment by benjamindeleener** [comment]
The issue could come from the straightening, that can produce edges of segmentation that are not "flat", because of the straightening transformation.
