### ISSUE TITLE
Registration issue with default param

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#924]
Path to data : ```/Volumes/folder_shared/sct_issues/20160711_issue924```
command: ```sct_register_to_template -i space.nii.gz -s space_seg.nii.gz -l labels.nii.gz```

Result: (yellow and orange dot are the labels at C3 and T2)
![2016-07-11_issue924](https://cloud.githubusercontent.com/assets/5857909/16735689/0dd94074-4758-11e6-820f-e7a0b21240a3.png)

**Comment by SaraDupont** [comment]
Re-tried today, result is slightly different but not better:

![2016-07-11-result_param_default](https://cloud.githubusercontent.com/assets/5857909/16737147/023b14e4-475e-11e6-924a-c50d7099e839.png)

**Comment by SaraDupont** [comment]
With only one step, with an affine transformation on segmentations:

```sct_register_to_template -i space.nii.gz -s space_seg.nii.gz -l labels.nii.gz -param step=1,type=seg,algo=affine,metric=MeanSquares,slicewise=0:step=2,iter=0:step=3,iter=0 ```

![2016-07-11_step_1_affine_seg_only](https://cloud.githubusercontent.com/assets/5857909/16742215/bcaf1ac6-4774-11e6-8b64-dcedf8333274.png)

**Comment by benjamindeleener** [comment]
Fixed with the new version of straightening, that makes the image straight in the real referential frame.

![image](https://cloud.githubusercontent.com/assets/7757117/16749398/d75a70e6-4797-11e6-8a9e-089c3c36c883.png)
