### ISSUE TITLE
sct_label_vertebrae automatic fails

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#925]
Path to data: ```/Volumes/folder_shared/sct_issues/20160711_issue925/```
Command: ```sct_label_vertebrae -i space.nii.gz -s space_seg.nii.gz -c t2```

Result: 

![2016-07-11_issue925](https://cloud.githubusercontent.com/assets/5857909/16735879/bb6834e8-4758-11e6-95cc-b1c2fa085fb7.png)

**Comment by jcohenadad** [comment]
le bug est lié au pb du nouveau straightening qui crop trop-- see below:
![screen shot 2016-07-11 at 15 38 11](https://cloud.githubusercontent.com/assets/2482071/16744114/88dde9f8-477d-11e6-91c9-fc0ad4b25e6d.png)

linked to issue #917

**Comment by jcohenadad** [comment]
fixed (for this dataset) on 887d983
