### ISSUE TITLE
binaries hosted on Dropbox are not accessible from China

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#927]
issue here:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/34eb6536/

We need to find an alternative to Dropbox/Google and update `install_sct` and `sct_download_data`.

**Comment by poquirion** [comment]
We could have all the extra data as release file on git hub.

**Comment by jcohenadad** [comment]
yes but i wanted to avoid github for heavy binary data (not the philosophy of GH). We would do it last resort of course ;-)

**Comment by jcohenadad** [comment]
@poquirion: i misunderstood your suggestion-- yes, we can add zip files to the release. Good idea. I'll to that.
