### ISSUE TITLE
sct_crop_image -ref corrupts the headers

### ISSUE THREAD

**Issue by slevyrosetti** [neuropoly/spinalcordtoolbox#932]
```
sct_crop_image -i mt1.nii.gz -o mt1crop.nii.gz -ref ../t2star/t2starcrop.nii.gz
```

![screen shot 2016-07-15 at 5 31 38 pm](https://cloud.githubusercontent.com/assets/7769691/16889471/ba8ef322-4ab4-11e6-84dd-e358ebe320c8.png)
![screen shot 2016-07-15 at 5 31 46 pm](https://cloud.githubusercontent.com/assets/7769691/16889473/ba93b4b6-4ab4-11e6-8ee9-a120fc7cec92.png)
![screen shot 2016-07-15 at 5 31 49 pm](https://cloud.githubusercontent.com/assets/7769691/16889472/ba932bd6-4ab4-11e6-8ecf-7e4b23f24790.png)

Data under: folder_shared/sct_issues

**Comment by jcohenadad** [comment]
seems to be fixed now
