### ISSUE TITLE
sct_create_mask:  [bug] IndexError: list index out of range 

### ISSUE THREAD

**Issue by nguyen1j** [neuropoly/spinalcordtoolbox#951]
sct_create_mask -i T2.nii -p centerline,T2_seg.nii -size 35 -f cylinder -o T2_msk.nii

[nii_files.zip](https://github.com/neuropoly/spinalcordtoolbox/files/394070/nii_files.zip)

----------------------------------------------------------------------------------------------------
Spinal Cord Toolbox (version 3.0_beta20-506ed9a821d4b2240d0329bff537aa5d94354700)
Running /data/RnD/Thanh/SpinalCordData/code/sct/spinalcordtoolbox-3.0_beta20/build/scripts/sct_create_mask.py -i T2.nii -p centerline,T2_seg.nii -size 35 -f cylinder -o T2_msk.nii
  OK: T2_seg.nii

Create temporary folder...

Create temporary folder...
mkdir tmp.160801104637_167393/

Check orientation...
.. RPI
sct_convert -i T2.nii -o tmp.160801104637_167393/data.nii
sct_convert -i T2_seg.nii -o tmp.160801104637_167393/centerline.nii.gz

Reorient to RPI...

Get dimensions of data...
  52 x 384 x 384 x 1

Create mask...
Traceback (most recent call last):
  File "/data/RnD/Thanh/SpinalCordData/code/sct/spinalcordtoolbox-3.0_beta20/build/scripts/sct_create_mask.py", line 408, in <module>
    main()
  File "/data/RnD/Thanh/SpinalCordData/code/sct/spinalcordtoolbox-3.0_beta20/build/scripts/sct_create_mask.py", line 90, in main
    create_mask()
  File "/data/RnD/Thanh/SpinalCordData/code/sct/spinalcordtoolbox-3.0_beta20/build/scripts/sct_create_mask.py", line 204, in create_mask
    cx[iz], cy[iz] = ndimage.measurements.center_of_mass(numpy.array(data_centerline[:, :, z_centerline_not_null[iz]]))
IndexError: list index out of range

**Comment by jcohenadad** [comment]
fixed in 904418ef95547be7969018a9ebc71899261473f3
