### ISSUE TITLE
update PAM50_cord

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#954]
in Charley's DB/results/20160812_PAM50_cord

to incorporate for next release

**Comment by charleygros** [comment]
I'm trying to regularize along z the segmentation done by ITK-Snap:
![screen shot 2016-08-12 at 11 08 19 am](https://cloud.githubusercontent.com/assets/14353425/17627800/832cada2-6080-11e6-86a9-02f23ef05beb.png)

**Comment by jcohenadad** [comment]
ok thanks-- looks like there is also a slight undersegmentation compared to propseg

**Comment by charleygros** [comment]
A new version of the L1-L2 cord segmentation is now available, same folder

**Comment by jcohenadad** [comment]
fixed in v3.0_beta21
