### ISSUE TITLE
2D kernel sct_maths dilate/erode

### ISSUE THREAD

**Issue by emilljungberg** [neuropoly/spinalcordtoolbox#956]
I was playing around with `sct_maths` to dilate some spinal cord masks when I ran into an unexpected result. What I was expecting to get as a result after running `sct_maths -dilate 1` was to get a mask which is expanded by about 1 voxel but what you get is instead something like what is seen below in in red (Green is the original segmentation). I don't point this out as a bug, not at all, it is obvious that this is the correct result when using a 3D kernel for dilation which is the case here. I was thinking if it would be possible to add an option for using a 2D disk kernel instead of a 3D ball kernel for dilation to achieve results similar to what is produced by fsl when running `fslmaths t2s.nii.gz -kernel 2D -dilD t2s_dil.nii.gz`

I started to look into a possible solution to this but it seemed to be quite tricky to get a 2D kernel with the correct orientation. Thoughts on how to achieve this?

![screen shot 2016-08-16 at 9 21 51 am](https://cloud.githubusercontent.com/assets/3906827/17707019/4a394c10-6393-11e6-9c11-7b4482a4d03c.png)

**Comment by jcohenadad** [comment]
one solution would be to accept either one int, or a comma-separated series: int,int,int for anisotropic box kernel. Then we can create a structured element compatible with scikit-learn (nparray) with the given dimensions. 
Would that be ok for you?

**Comment by emilljungberg** [comment]
That would be a nice solution. I was playing around with creating a kernel that would only work in 2 dimensions but had some issues with the orientation. I tried to input a 2D matrix but that didn't work so I think it needs a 3D kernel with the correct plane in that matrix set to the 2D matrix we want to use. I might have been confused with the orientation when I tried though. You probably have a better knowledge of the orientation in nibabel.

**Comment by jcohenadad** [comment]
no worries i'll try to implement it now-- shouldn't be too long

**Comment by jcohenadad** [comment]
fixed in 43f004d0dc4e144d67b219f1bcf937ec65caf850

**Comment by emilljungberg** [comment]
Thanks!
