### ISSUE TITLE
fix the example message

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#957]
this creates confusion amongst users-- example here:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/e9e62cfd/

**Comment by jcohenadad** [comment]
I'm thinking of simply add a function to be called like: 
~~~
parser.usage.set_example('sct_label_utils -i t2.nii.gz -create 1,2,3,4')
~~~
This will allow more flexibility and less "hair-pulling"...

**Comment by jcohenadad** [comment]
for now it has been decided to remove the display of the EXAMPLE field. Later, we can go with the above-solution.

**Comment by joshuacwnewton** [comment]
Closing, as with the conversion to `argparse`, setting an example field is no longer an option. 

At this point, displaying an example is largely handled by adding `"Example: <example>"` text to the help description, or writing out instructions in plain English.
