### ISSUE TITLE
save_plane keeps figures open (memory issue)

### ISSUE THREAD

**Issue by emilljungberg** [neuropoly/spinalcordtoolbox#961]
I noticed something when I use the `save_quality_control` in a loop of many images. After a few exports I get a warning message from `matplotlib` stating that I have more than 20 figures open currently. In the loop I exported about 100 images which in the end ate up about 3 GB of memory.

After a look at it I think it can easily be resolved by closing the figure after saving it, as mentioned in this [stackoverflow thread](http://stackoverflow.com/questions/2364945/matplotlib-runs-out-of-memory-when-plotting-in-a-loop).

In the code, I think it would refer to line 1001 in `msct_image.py`, function `save_plan`
```
        try:
            fig = plt.figure(figsize=(n_lines*10, n_col*20))
            for i, slices in enumerate(slice_list):
                slice_im, slice_seg = slices
                plot = fig.add_subplot(n_lines, n_col, i+1)
                plot.imshow(slice_im, cmap=cm.gray, interpolation='nearest')
                if index[i] is None:
                    title = 'mid slice'
                else:
                    title = 'slice '+str(index[i])
                plot.set_title(title)
                if seg is not None:
                    slice_seg[slice_seg < thr] = 0
                    plot.imshow(slice_seg, cmap=cmap_seg, interpolation='nearest')
                plt.axis('off')
            # plt.imshow(slice, cmap=cm.gray, interpolation='nearest')
            # if seg is not None:
            #     plt.imshow(slice_seg, cmap=cmap_seg, interpolation='nearest')
            # plt.axis('off')
            fname_png = path_output + self.file_name + suffix + format
            plt.savefig(fname_png, bbox_inches='tight')
```
I think a `plt.close(fig)` after the `plt.savefig()` would solve this.

**Comment by SaraDupont** [comment]
Yes it makes sense !

**Comment by SaraDupont** [comment]
Does this fix the issue ?

**Comment by emilljungberg** [comment]
Should fix it. I'll try! Thanks Sara!

**Comment by jcohenadad** [comment]
is it fixed? can we close this issue?

**Comment by jcohenadad** [comment]
fixed
