### ISSUE TITLE
with "-init-centerline viewer" first slice is always black 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#962]
![screen shot 2016-08-18 at 16 52 15](https://cloud.githubusercontent.com/assets/2482071/17790386/334482d6-6564-11e6-868f-8a7e659b120d.png)

**Comment by tanguyduval** [comment]
I agree, I had this problem before. A quick fix is to start by the bottom instead (usually the first caudal slice is not black)

**Comment by benjamindeleener** [comment]
The first slice is not always black, as demonstrated for another dataset here:
<img width="724" alt="screen shot 2016-08-19 at 08 54 21" src="https://cloud.githubusercontent.com/assets/7757117/17810343/a3120c74-65ea-11e6-90e3-63d92b37fbbc.png">

Could you share the data so I can fix the issue?

**Comment by jcohenadad** [comment]
ok nevermind, i didn't realize that most of the images i've been dealing with have a zeroed slice at the top (dunno why...).
