### ISSUE TITLE
straightening is sensitive to image resolution

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#964]
i've tried the following:
- downsample x2 a segmentation
- straighten 
- upsample x2 the straight segmentation
- apply the warp_curve2straight to the native image, using the upsampled straight segmentation as the destination space.

the pros of doing straightening is that it is faster (30s at 2mm iso vs. 70s at 1mm iso). 

below is a comparison between standard and downsampled straightening. We can see a strange non-linear stretch between images, which can be problematic when one wants to keep the integrity of the spine morphometry:

![output_mje701](https://cloud.githubusercontent.com/assets/2482071/17792851/532ac5b2-6571-11e6-9597-b74cb91b31bc.gif)

**Comment by benjamindeleener** [comment]
I fixed this issue, by performing a reparametrization of the NURBS curve. Indeed, points along the curve were not uniformly distributed.

See results here:
![benjamindeleener_3](https://cloud.githubusercontent.com/assets/7757117/18491067/bcd188b4-79d2-11e6-89e9-18b6b66fa47d.gif)

**Comment by jcohenadad** [comment]
bravo! and thank you for fixing this 👍
