### ISSUE TITLE
smoothing is done two times

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#987]
https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L284
https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L402

@benjamindeleener: is there a particular reason for it?

**Comment by benjamindeleener** [comment]
Yes, the first straightening is done on the initial image. The second one is done on the padded image, after calculating the length of the spinal cord.

I believe it is not necessary anymore and can be done differently. I'll work on that.

**Comment by benjamindeleener** [comment]
I removed the second nurbs fitting as it is not necessary anymore (as the fitting is done in the physical coordinates system).
